clerk/javascript

- packages/backend-core/src/index.ts
- packages/backend-core/src/util/jwt.ts
Temporary removal of `nbf` due to clock skew miscalculation.
Following up we will add the correct logic for `nbf` checks and configurable skew time.
/+ Correct `Nullable` export.
> fix(backend-core): Correct the nbf-exp check

- packages/sdk-node/examples/node/src/clients.ts
- packages/sdk-node/src/Clerk.ts
- packages/sdk-node/src/index.ts
Restoring the`setClerkHttpOptions` method after accidental removal.
> fix(clerk-sdk-node): Restore the setClerkHttpOptions capability

- packages/backend-core/src/Base.ts
- packages/backend-core/src/api/utils/Errors.ts
- packages/backend-core/src/util/jwt.ts
Correct handling of the token expiration case introducing the new `JWTExpiredError` class.
> fix(backend-core): Correct handling of expired tokens

- packages/clerk-js/src/core/clerk.ts
Check if session is created before calling Clerk.setSession and redirecting the user.
Especially during sign ups, the session wont be created unless all the sign up requirements (e.g. names and emails)  are met.
> fix(clerk-js): Prevent post auth redirects in Metamask flow

- packages/clerk-js/src/ui/signIn/SignInFactorTwo.tsx
- packages/types/src/signIn.ts
This PR modifies the signature of `prepareSecondFactor` method in the sign in resource so that it optionally accepts the phone number id which we want to use for the second factor verification.
This aligns the `prepareSecondFactor` with the rest of the prepare methods. 
It's also more future-proof for when we introduce other types of second factor verifications (apart from phone codes).
Finally, it gives greater control to the callers to use any of their defined second factors for verification and not necessarily the default one.
> Include phone number id in prepare second factor

- packages/edge/src/vercel-edge.ts
Correct interstitial content type on vercel-edge fetcher and User-Agent setting on `getAuthState`.
> fix(edge): Correct interstitial Content-Type and User-Agent

- packages/clerk-js/src/ui/signUp/SignUp.test.tsx
- packages/clerk-js/src/ui/signUp/SignUpStart.test.tsx
- packages/clerk-js/src/ui/signUp/SignUpStart.tsx
- packages/clerk-js/src/ui/signUp/SignUpVerify.test.tsx
- packages/clerk-js/src/ui/signUp/SignUpVerify.tsx
- packages/clerk-js/src/ui/signUp/utils.test.ts
- packages/clerk-js/src/ui/signUp/utils.ts
Replace authConfig with userSettings in SignUp
> Replace AuthConfig with UserSettings in SignUp

- packages/nextjs/src/middleware/withServerSideAuth.ts
Shows error if the user does not return an object from the wSSA callback, eg:
```ts
export const getServerSideProps = withServerSideAuth(context => {
const { userId } = context.auth;
console.log(userId);
// throws type error
});
```
> Enforce withServerSideAuth callback return type

- package-lock.json
- packages/clerk-js/src/core/clerk.test.ts
- packages/clerk-js/src/core/clerk.ts
- packages/clerk-js/src/core/resources/User.ts
- packages/clerk-js/src/core/tokenCache.test.ts
- packages/clerk-js/src/ui/common/errorHandler.ts
- packages/clerk-js/src/ui/common/verifyMagicLink/VerifyMagicLink.tsx
- packages/clerk-js/src/utils/errors.ts
- packages/clerk-js/src/utils/memoizeStateListenerCallback.ts
Correctly import all resources from internal.ts
> feat(clerk-js): Import all resources from internal.ts

- packages/backend-core/src/__tests__/apis/UserApi.test.ts
- packages/backend-core/src/__tests__/apis/responses/updateUser.json
- packages/backend-core/src/api/collection/UserApi.ts
Allow username and unsafeMetadata updates from BAPI
> fix(backend-core): Allow username and unsafeMetadata updates from BAPI

- packages/nextjs/src/middleware/utils/getAuthData.ts
Fetch user and session object in parallel during SSR.
> feat(nextjs): Fetch user and session in parallel

- packages/clerk-js/src/core/fapiClient.test.ts
- packages/clerk-js/src/core/fapiClient.ts
Allows passing of any type of argument that is expected on [URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/URLSearchParams).
All search params are passing through a
`    const searchParams = new URLSearchParams(search);`
construct so we can take advantage of all the formats of the contructor.
> feat(clerk-js): Allow passing of object style search params on fapiclient

- packages/clerk-js/src/core/resources/UserSettings.test.ts
- packages/clerk-js/src/core/resources/UserSettings.ts
- packages/clerk-js/src/ui/signIn/SignInStart.test.tsx
- packages/clerk-js/src/ui/signIn/SignInStart.tsx
- packages/types/src/userSettings.ts
- The instant-password field will now only get rendered for password-based instances. 
- Still gracefully handles instances that started as password-based and become passwordless after
> Render instant password for password-based instances only

- packages/clerk-js/src/ui/signIn/SignInFactorOne.test.tsx
- packages/clerk-js/src/ui/signIn/SignInFactorOne.tsx
- packages/clerk-js/src/ui/signIn/strategies/ErrorScreen.test.tsx
- packages/clerk-js/src/ui/signIn/strategies/ErrorScreen.tsx
Changed the error message in our SignInFactor one component when trying to sign in with no available authentication method for the instance.
> fix(clerk-js): Helpful error message for sign in without factors

- packages/shared/components/phoneInput/PhoneInput.test.tsx
- packages/shared/components/phoneInput/PhoneInput.tsx
- packages/shared/components/phoneInput/__snapshots__/PhoneInput.test.tsx.snap
The phone input component's initial value should be a blank string, until the input actually changes.
> fix(shared): Phone input should start blank

- package-lock.json
- packages/remix/package.json
- packages/remix/src/client/ConnectClerk.tsx
- packages/remix/src/client/RemixClerkProvider.tsx
- packages/remix/src/client/index.ts
- packages/remix/src/client/types.ts
- packages/remix/src/errors.ts
- packages/remix/src/ssr/index.ts
- packages/remix/src/ssr/rootAuthLoader.ts
- packages/remix/src/ssr/types.ts
- packages/remix/src/ssr/utils.ts
This PR introduces small but important changes to the setup process our users need to follow in order to integrate Clerk in a Remix project.
Before this PR, the recommended `root.tsx` file would look like:
```tsx
import { ClerkProvider } from "@clerk/remix";
import { rootAuthLoader, WithClerkState } from "@clerk/remix/ssr.server";
export const loader: LoaderFunction = (args) => rootAuthLoader(args, ({ auth }) => {
const { userId } = auth;
const posts: Posts[] = database.getPostsByUser(userId);
return posts;
});
export default function App() {
const { data: posts, clerkState } = useLoaderData<WithClerkState<Posts[]>>();
return (
<ClerkProvider frontendApi={"clerk.renewing.hermit-14.lcl.dev"} clerkState={clerkState}>
<html lang="en">...</html>
);
}
```
This approach …
> Introduce ConnectClerk

- packages/clerk-js/src/ui/common/constants.ts
- packages/types/src/oauth.ts
Introduce declarations for supporting Notion OAuth
> feat(types,clerk-js): Introduce Notion OAuth

- packages/clerk-js/src/ui/common/logo/Logo.tsx
Fixes logo resizing issue on old safari browsers (mobile Safari < 13.4)
> fix(clerk-js): Don't use ResizeObserver on old browsers

- packages/expo/src/singleton.ts
- ⛔️ `npm test` runs as expected.
- ⛔️ `npm run build` runs as expected.
☝️ Both are failing but unrelated to my changes. The build succeeds for `clerk-expo` package without errors.
This fix does two things. 
The first is add a guard to check for the existence of `tokenCache.getToken` and `tokenCache.saveToken`. Previously, if a `tokenCache` was passed in, but had different methods on it, e.g. `get` / `set`, it would attempt to call `undefined` functions instead of falling back to the `getTokenFromMemory` and `saveTokenInMemory` operations, which are sensible defaults.
The second change here adds an early return if the `tokenCache` is not provided at all. This makes an assumption that the token cache is not available for the web platform, which is the case with `expo-secure-store` that is …
> Fix Expo tokenCache

- packages/backend-core/src/util/types.ts
- Adding the `orgs` claim on the JWTPayload type exposed on `sessionClaims` attribute.
> fix(backend-core): Add JWTPayload orgs claim type

- packages/types/src/organizationInvitation.ts
Missing `revoke` typing on OrganizationInvitationResource.
> fix(types): Revoke typing on organizationInvitation

- packages/backend-core/src/__tests__/apis/InvitationApi.test.ts
- packages/backend-core/src/api/collection/InvitationApi.ts
- packages/backend-core/src/api/resources/Invitation.ts
- packages/backend-core/src/api/resources/Props.ts
The invitation creation API supports sending `public_metadata` that will be attached to the user upon sign up. This PR adds the type definition to allow that metadata to be used when creating an invitation. I've also added `publicMetadata` to the `Invitation` class.
> Invitations can optionally carry metadata that will eventually end up in the created user once they sign up.
> The metadata must be a well-formed JSON object. In order to add metadata to an invitation, you can use the public_metadata property when the invitation is created:
[Clerk Invitation Documentation](https://docs.clerk.dev/popular-guides/invitations#invitation-metadata)
```bash
curl https://api.clerk.dev/v1/invitations -X POST -d '{"email_address": "devin@example.com"}' -H "Authorization:Bearer $API_KEY" -H …
```
> feat(backend-core): Add public_metadata to invitation create API

- packages/clerk-js/src/core/clerk.ts
- packages/clerk-js/src/core/devBrowserHandler.ts
- packages/clerk-js/src/core/services/authentication/AuthenticationService.ts
- packages/clerk-js/src/utils/cookies/handler.ts
- packages/types/src/clerk.ts
Cleanup of the deprecated auth v1 code.
> Remove deprecated Auth v1 code

- packages/backend-core/src/__tests__/apis/UserApi.test.ts
- packages/backend-core/src/__tests__/apis/responses/getUser.json
- packages/backend-core/src/api/resources/ExternalAccount.ts
- packages/backend-core/src/api/resources/JSON.ts
- packages/backend-core/src/api/resources/Props.ts
- packages/clerk-js/src/core/resources/ExternalAccount.ts
- packages/types/src/externalAccount.ts
- packages/types/src/json.ts
Add new external account properties:
- username
- publicMetadata
- label
> feat(types,backend-core,clerk-js): Add external account properties username, publicMetadata & label

- packages/remix/src/client/ConnectClerk.tsx
- packages/remix/src/client/ConnectClerkCatchBoundary.tsx
- packages/remix/src/client/Interstitial.tsx
- packages/remix/src/client/RemixClerkProvider.tsx
- packages/remix/src/client/index.ts
- packages/remix/src/client/types.ts
- packages/remix/src/errors.ts
- packages/remix/src/ssr/getAuth.ts
- packages/remix/src/ssr/getAuthData.ts
- packages/remix/src/ssr/rootAuthLoader.ts
- packages/remix/src/ssr/types.ts
- packages/remix/src/ssr/utils.ts
Up until now, we used `throw json()` to stop a loader from inside `getAuth` without having to change the loader api and introduce a loader wrapper (which is not recommended by Remix). However, depending on the app's structure it's possible that a nested `CatchBoundary` will catch this error before `ClerkProvider` renders the interstitial.
Remix runs all loaders in [parallel and waits for all of them to either return or throw](https://github.com/remix-run/remix/blob/5b8a0ce0aa0201aa2402fc41405ffbe89605963b/packages/remix-server-runtime/server.ts#L302). Once all the loaders have run, Remix evaluates the returned values in order, stopping when [the first error or redirect is encountered](https://github.com/remix-run/remix/blob/5b8a0ce0aa0201aa2402fc41405ffbe89605963b/packages/remix-server-run …
> Remix integration improvements

- package-lock.json
- package.json
- packages/backend-core/package.json
- packages/backend-core/tsconfig.json
- packages/clerk-js/package.json
- packages/edge/package.json
- packages/edge/tsconfig.json
- packages/expo/package.json
- packages/nextjs/package.json
- packages/react/package.json
- packages/remix/package.json
- packages/sdk-node/package.json
- packages/sdk-node/tsconfig.json
- packages/shared/package.json
- packages/types/package.json
- tsconfig.json
> chore(repo): Update Typescript to 4.6.2

- packages/react/src/contexts/ClientContext.tsx
- packages/react/src/contexts/index.ts
- packages/react/src/hooks/index.ts
- packages/react/src/hooks/useSessionList.ts
- packages/react/src/hooks/useSignIn.ts
- packages/react/src/hooks/useSignUp.ts
Aligns the useSignIn,useSignUp and useSessionList hooks with the rest of the v3 apis.
Examples: 
```
export default function CustomFlow() {
const { isLoaded, signIn } = useSignIn();
if (!isLoaded) {
return '...';
}
const start = async () => {
const res = await signIn.create({ identifier, password });
};
return (
<div>...</div>
);
}
```
```
export default function CustomFlow() {
const { isLoaded, signUp } = useSignUp();
if (!isLoaded) {
return '...';
}
const start = async () => {
const res = await signIn.signUp({ ... });
};
return (
<div>...</div>
);
}
```
```
export default function CustomFlow() {
const { isLoaded, sessions } = useSessionList();
if (!isLoaded) {
return '...';
}
return (
<div>...</div>
);
}
```
> Align useSignIn,useSignUp and useSessionList hooks

- packages/react/src/hooks/useSessionList.ts
- packages/react/src/hooks/useSignIn.ts
- packages/react/src/hooks/useSignUp.ts
- packages/types/src/clerk.ts
> feat(clerk-react): Add setSession to useSignIn, useSignUp, useSessionList

- packages/clerk-js/src/core/clerk.test.ts
- packages/clerk-js/src/core/clerk.ts
- packages/clerk-js/src/ui/common/activeAccountsManager/ActiveAccountsManager.tsx
- packages/clerk-js/src/ui/contexts/CoreClerkContext.tsx
- packages/react/src/components/SignOutButton.test.tsx
- packages/react/src/components/SignOutButton.tsx
- packages/react/src/hooks/useAuth.ts
- packages/react/src/hooks/utils.ts
- packages/react/src/isomorphicClerk.ts
- packages/react/src/types.ts
- packages/types/src/clerk.ts
Replaces signOutOne with signOut(options). 
Currently, we have 2 different signOut methods on Clerk: `signOut()` and `signOutOne` as shown below:
```
function TestComponent() {
const clerk = useClerk();
const signOutAllUsers = () => {
return clerk.signOut(() => navigate('...'));
};
const signOutCurrent = () => {
return clerk.signOutOne(() => navigate('...'));
};
}
```
Proposed change: Combine the 2 methods into a single `signOut` that accepts an optional `callback` and an optional `options`  obj
- If no sessionId is provided, the client will be destroyed and the user will be signed out
- If a sessionId is provided and
- its the only active session, the client will be destroyed and the user will be signed out
- its the current active session, the session will be removed and the user will …
> feat(clerk-js,clerk-react): Replace signOutOne with signOut(options)

- packages/backend-core/src/api/collection/SessionApi.ts
- packages/backend-core/src/api/resources/JSON.ts
- packages/backend-core/src/api/resources/Props.ts
- packages/backend-core/src/api/resources/Token.ts
- packages/backend-core/src/api/resources/index.ts
- packages/backend-core/src/api/utils/Deserializer.ts
- packages/nextjs/src/middleware/utils/getAuthData.ts
- packages/remix/src/ssr/getAuthData.ts
- packages/types/src/ssr.ts
Makes getToken({ tempalte: ''}) available during SSR.
Server caching and client keep alive will be handled in a separate PR.
> Introduce getToken for SSR

- packages/clerk-js/src/core/clerk.ts
- packages/clerk-js/src/ui/router/BaseRouter.tsx
- packages/clerk-js/src/ui/router/RouteContext.tsx
- packages/clerk-js/src/utils/beforeUnloadTracker.ts
- packages/clerk-js/src/utils/index.ts
- packages/clerk-js/src/utils/pageLifecycle.ts
- packages/remix/src/client/RemixClerkProvider.tsx
- packages/remix/src/client/useAwaitableNavigate.tsx
- packages/shared/utils/index.ts
- packages/shared/utils/ssr.ts
The default `navigate` function provided by Remix works in 5 phases:
1. calls the route loader
2. replaces the current url
3. waits for the loader to return route data
4. unmounts the old tree
5. finally, it mounts the new page
In our case, SignIn remained mounted up until step 5. Because we couldn't reliably await the navigation, withRedirectToHome in some cases would trigger before the new page is mounted causing a redirect to the home page instead of respecting the redirectUrl prop.
We used the useTransition remix hook to create a custom awaitable navigate function for use with Remix applications. The hook stores all pending navigations and resolves them when the state changes to idle (loading -> idle). 
I'm also considering adding a small delay for extra safety - keep in mind that …
> Navigation improvements 

- packages/edge/src/vercel-edge/ClerkAPI.ts
- packages/edge/src/vercel-edge/index.ts
- packages/edge/src/vercel-edge/types.ts
- packages/edge/src/vercel-edge/utils/getAuthData.ts
- packages/edge/src/vercel-edge/utils/index.ts
- packages/edge/src/vercel-edge/utils/injectAuthIntoRequest.ts
- packages/edge/vercel-edge/package.json
Align the return values and props of the `withAuth` helper in `@clerk/edge`:
- `withAuth(handler, { ...opts, loadUser, loadSession })`
Post @3 release we will look into some consolidation of the SSR state calculations between edge, next, remix and node.
> feat(edge): Align edge version of withAuth props and return values.

- packages/clerk-js/src/ui/signUp/SignUpStart.test.tsx
- packages/clerk-js/src/ui/signUp/SignUpStart.tsx
Allow users to fill in any optional fields that might be available when signing up with an invitation, instead of signing them up immediately.
If the instance supports optional fields and a user lands to our `<SignUp/>` component from an invitation email, give them a chance to enter additional information instead of immediately signing them up.
For instances with no additional information available in the form, the user will be signed up immediately.
https://user-images.githubusercontent.com/1156147/158770796-83f78050-5977-4a31-96db-21a06409d38b.mp4
> fix(clerk-js): Invitation based sign up optional fields

- packages/remix/src/ssr/rootAuthLoader.ts
- packages/remix/src/ssr/types.ts
- packages/remix/src/ssr/utils.ts
Changes the `rootAuthLoader` api from
```tsx
export const loader: LoaderFunction = args => {
return rootAuthLoader(args, ({ request, auth, user }) => {
const { userId, getToken, sessionId } = auth;
console.log(userId, user, ...)
}, { loadUser: true })
}
```
to
```tsx
export const loader: LoaderFunction = args => {
return rootAuthLoader(args, ({ request, auth, user }) => {
const { auth, user } = request;
const { userId, getToken, sessionId } = auth;
console.log(userId, user, ...)
}, { loadUser: true })
}
```
This change intends to make accessing auth state/ user/ session consistent across all environments and repos.
> feat(clerk-js): Move auth state to request in rootAuthLoader

- packages/clerk-js/src/core/clerk.test.ts
- packages/clerk-js/src/core/clerk.ts
- packages/clerk-js/src/utils/url.test.ts
- packages/clerk-js/src/utils/url.ts
When attempting to sign up with sso while we have set an allowlist that forbids the specific sso email to sign up then after getting the relative error we are redirected to [signIn page](https://github.com/clerkinc/javascript/blob/0bc7abed4ae686441f87a41ded4012cfa427b44f/packages/clerk-js/src/core/clerk.ts#L539) which doesn't have access to the signUp state to show the proper error.
The fix, after an unsuccessful sso sign up attempt, [redirects to the signUp page](https://github.com/clerkinc/javascript/blob/0bc7abed4ae686441f87a41ded4012cfa427b44f/packages/clerk-js/src/core/clerk.ts#L535-L537) so that the proper error is can be displayed.
https://www.notion.so/clerkdev/SSO-sign-up-w-Allowlist-doesn-t-display-error-58267ed1448d466b811d4d92510e2e7f
> fix(clerk-js): Redirect user to signUp url when there is an error with external account sign up

- .husky/pre-commit
- docs/PUBLISH_NEXT.md
- package-lock.json
- package.json
- Introduce pre-commit formating on staged files _(let's not solve formating stuff again)_.
- Make the `next` _(or any preid)_ publishing more correct.
We can decide if we at some point want to pass all the js files through the formatter.
> Pre commit formatting pub docs

- packages/edge/src/vercel-edge/types.ts
Using a default handler without a promisified result works fine:
```js
import { withEdgeMiddlewareAuth } from "@clerk/edge/vercel-edge";
const handler = (req) => {
console.log(req.session);
if (req.session) {
return new Response("Session");
} else {
return new Response("No session");
}
};
export default withEdgeMiddlewareAuth(handler);
```
but the TS compiler complains when the handler is async.
The PR fixes that by expanding the return type. As it seems Next.js will resolve a promise-type handler in the same manner as a non promise one.
> fix(edge): Return plain or promise-like possible results

- package-lock.json
- package.json
- packages/backend-core/package.json
- packages/backend-core/src/api/collection/SessionApi.ts
- packages/backend-core/src/index.ts
- packages/backend-core/src/util/createGetToken.ts
- packages/edge/package.json
- packages/edge/src/vercel-edge/index.ts
- packages/edge/src/vercel-edge/utils/getAuthData.ts
- packages/edge/tsconfig.json
- packages/nextjs/src/middleware/utils/getAuthData.ts
- packages/remix/src/ssr/getAuthData.ts
- packages/sdk-node/src/Clerk.ts
- packages/sdk-node/src/__tests__/middleware.test.ts
- Add getToken to the returned value of `/edge` withEdgeMiddlewareAuth
- Add getToken to the returned value of `/api` withAuth and requireAuth  
- Refactor getAuthData to use common utils - this is the first step towards refactoring getAuthData into a common util
> Align getToken api across packages

- packages/clerk-js/src/ui/userProfile/security/Security.test.tsx
- packages/clerk-js/src/ui/userProfile/security/Security.tsx
- packages/clerk-js/src/ui/userProfile/security/__snapshots__/Security.test.tsx.snap
- packages/clerk-js/src/ui/userProfile/security/index.tsx
Don't show the password section and `/security/password` route unless the instance is configured to accept passwords as first factor authentication.
> fix(clerk-js): Show password only if required

- packages/sdk-node/src/Clerk.ts
- Simple change to allow sdk-node usage of the `CLERK_JWT_KEY` when added from the environment.
- Fix correct apiKey on JWKsClient
FYI on a follow up PR we will make `jwtKey` injectable in the Base contructor making it much more comprehensive.
> feat(clerk-sdk-node): Enable CLERK_JWT_KEY usage from clerk-sdk-node

- packages/backend-core/src/api/resources/JSON.ts
- packages/backend-core/src/api/resources/Props.ts
- packages/clerk-js/src/core/clerk.test.ts
- packages/clerk-js/src/core/resources/SignUp.ts
- packages/types/src/json.ts
- packages/types/src/signUp.ts
Populate `signUp.createdUserId` from the sign up Frontend API response as currently `createdUserId` is not available in ClerkJS.
> fix(clerk-js): Add createdUserId attribute to SignUp

- packages/clerk-js/src/core/clerk.ts
The createPageLifecycle helper depends on the global document object that is only available in Browsers but not in React Native/Expo.
> fix(clerk-expo): Setup createPageLifecycle only in browser environment

- packages/backend-core/src/Base.ts
- packages/edge/src/vercel-edge/index.ts
- packages/edge/src/vercel-edge/types.ts
- packages/nextjs/src/middleware/types.ts
- packages/nextjs/src/middleware/utils/getAuthData.ts
- packages/remix/src/ssr/getAuthData.ts
- packages/remix/src/ssr/types.ts
- packages/sdk-node/README.md
- packages/sdk-node/src/Clerk.ts
- packages/sdk-node/src/__tests__/instance.test.ts
Add the capability for injected JWT verification key:
- Clerk sdk Node instance creation.
- Clerk sdk Node by default picking up the `CLERK_JWT_KEY` environment variable if available.
- `verifySessionToken` which is exposed by `base` takes also a `jwtKey` argument to use any supplied key.
- All middlewares have the option of `jwtKey` e.g. `withAuth(..., { jwtKey });`
Note:
Added support for `authorizedParties` option on remix and nextjs middleware.
https://www.notion.so/clerkdev/a853f869f69c414b85e6d5290a2c4172?v=b253a2f980c641de8992cc63ed416fa0&p=88f966d0bcda4b8c9f10a3d80c2c8219
> Clerk jwt key injection

- packages/clerk-js/src/ui/common/activeAccountsManager/ActiveAccountsManager.test.tsx
- packages/clerk-js/src/ui/common/activeAccountsManager/ActiveAccountsManager.tsx
- packages/clerk-js/src/ui/common/authPropHelpers.ts
- packages/clerk-js/src/ui/contexts/ClerkUIComponentsContext.tsx
- packages/clerk-js/src/ui/signIn/SignInAccountSwitcher.tsx
- packages/clerk-js/src/ui/userButton/UserButton.test.tsx
- packages/clerk-js/src/ui/userButton/UserButtonPopup.test.tsx
- packages/react/README.md
- packages/types/src/clerk.ts
We updated the signOut api. This PR also updates the params of UserButton because many found them confusing.
Suggested changes:
afterSignOutUrl - the standard
afterMultiSessionSingleSignOutUrl - the special case for multisession apps
> Rename UserButton signout params

- packages/expo/src/ClerkProvider.tsx
- packages/expo/src/singleton.ts
> fix(clerk-expo): Make Clerk loading smarter

- packages/remix/src/client/ClerkApp.tsx
- packages/remix/src/client/ClerkCatchBoundary.tsx
- packages/remix/src/client/index.ts
- packages/remix/src/errors.ts
Change the Remix root.tsx helpers to:
```
export default ClerkApp(App);
export const CatchBoundary = ClerkCatchBoundary()
```
> feat(remix)!: Rename ConnectClerk to ClerkApp

- packages/clerk-js/src/core/resources/Base.ts
- packages/clerk-js/src/core/resources/EmailAddress.ts
- packages/clerk-js/src/core/resources/SignIn.ts
- packages/clerk-js/src/core/resources/SignUp.ts
Apply a minor refactoring across all _baseGet usages.
> fix(clerk-js): Force client update on resource reload

- package-lock.json
- packages/sdk-node/package.json
- packages/sdk-node/src/Clerk.ts
Fix missing `getToken` attribute from the auth prop enhancer.
This PR adds @clerk/types dependency on sdk-node
> fix(clerk-sdk-node): Add ServerGetToken on AuthProp enhancers

- packages/clerk-js/src/core/resources/Session.ts
The /me/token endpoints expects a clean service name, without the `integration_` prefix
> fix(clerk-js): Remove integration_ prefix for legacy user token requests

- packages/backend-core/src/Base.ts
- Set default empty object for options on `base.verifySessionToken`
> fix(backend-core): Fix verifySessionToken to optionally allow params

- packages/clerk-js/src/ui/signIn/SignInStart.test.tsx
- packages/clerk-js/src/ui/signIn/SignInStart.tsx
- packages/clerk-js/src/ui/signUp/SignUpStart.test.tsx
- packages/clerk-js/src/ui/signUp/SignUpStart.tsx
Previously, unless the error was "sign up not allowed" or "access not granted", we would not show any error notification to the user.
However, other issues can occur, due to e.g. network errors or invalid custom scopes.
This PR introduces a fallback to a generic error so that the user can at least be notified that their sign in / up failed (besides the obvious fact that they are not signed in).
Related issue:
https://www.notion.so/clerkdev/a853f869f69c414b85e6d5290a2c4172?v=531db68c98394e709bafd5b5e1df4add&p=70223f2c7a3c4ed8aa4a97df66fd755a
> fix(clerk-js): Fall back to generic error when oauth sign in/up fails

- packages/clerk-js/src/ui/signUp/SignUpStart.test.tsx
- packages/clerk-js/src/ui/signUp/SignUpStart.tsx
With the latest BE code changes, we now support instances with optional usernames.
This means that during sign up, if the username attribute is enabled, it doesn't necessarily mean that it's also required.
This commit modifies the sign up component to reflect that and show that the username field is optional if it's enabled but not required.
> Allow usernames to be optional

- packages/types/src/session.ts
It was accidentally set as required.
> fix(clerk-js): Make GetTokenOptions.template optional

- packages/backend-core/src/Base.ts
- packages/backend-core/src/__tests__/Base.test.ts
Finally we can feel more confident deploying changes on our core API `getAuthState` and also `verifySessionToken` which is part of our public API _(also used by RW)_.
> feat(backend-core): Test Base getAuthState and verifySessionToken

- package.json
- packages/clerk-js/src/core/clerk.ts
- packages/react/src/contexts/ClerkProvider.tsx
- packages/react/src/isomorphicClerk.ts
- packages/react/src/utils/scriptLoader.ts
This PR prevents Clerk from breaking if `IsomorphicClerk.loadClerkJS` is called more than once after Clerk loaded and initialised.
`ClerkProvider` needs to be a top-level component component, wrapping most of the user's app. It should only mount *once* during the lifetime of the app, however this is something we cannot control - it is possible under certain conditions that 3rd party frameworks (eg NextJS, Remix, etc) will trigger a complete unmount-remount of the whole root component, causing effects in `ClerkProvider` to run again.
In this particular case, `ClerkProvider` was creating a new instance of `IsomorphicClerk` that was in turn loading and replacing the window.Clerk singleton, causing it to lose state.
There are a number of changes that we could do to further improve this flow. …
> Prevent re-initialization of Clerk singletons

- packages/backend-core/src/api/resources/Props.ts
- packages/backend-core/src/api/resources/User.ts
- packages/clerk-js/src/core/resources/User.ts
- packages/types/src/json.ts
- packages/types/src/user.ts
Expose new `user.last_sign_in` field.
https://www.notion.so/clerkdev/a853f869f69c414b85e6d5290a2c4172?v=531db68c98394e709bafd5b5e1df4add&p=8a55dd0331204d039009760b8347921a
https://www.notion.so/clerkdev/a853f869f69c414b85e6d5290a2c4172?v=531db68c98394e709bafd5b5e1df4add&p=a4edf7395a084aafa9fd06e67a3e34fd
> feat(types,clerk-js): Add last_sign_in_at to User

- packages/react/src/contexts/ClerkProvider.tsx
- packages/react/src/types.ts
That way, Clerk prop will be available in Next.js, Remix and all future libraries that will extend the React ClerkProvider.
https://github.com/clerkinc/javascript/pull/135
> Expose clerk prop in isomorphic clerk props

- packages/remix/src/ssr/getAuth.ts
- packages/remix/src/ssr/rootAuthLoader.ts
- Is it possible to have the package allow Node 14? AWS Lambda's latest version is Node 14 so that's what I run locally.
When Clerk returns an interstitial and the developer has caching implemented, it will continually redirect bc cached versions will continue to load the interstitial. Adding a "no cache" Cache Control header solved it on my end, which basically tells my CDN to not keep the interstitial in the cache. I think this could be a reasonable default, or at the very least, a parameter we could pass into `rootAuthLoader`
> Adding a no cache cache control header to solve infinite loop issues

- packages/backend-core/src/api/collection/UserApi.ts
- Still can't `npm install` locally since I'm on node 14 which is the latest AWS Lambda currently supports
I needed to use [this](https://reference.clerk.dev/reference/backend-api-reference/users#retrieve-the-oauth-access-token-of-a-user) API but couldn't find it on the SDK, so I added it to UsersApi based on the docs.
> add get user oauth access tokens to clerk sdk

- packages/clerk-js/src/core/resources/ExternalAccount.test.ts
- packages/clerk-js/src/core/resources/ExternalAccount.ts
- packages/types/src/externalAccount.ts
Allow users to delete a connected external account
> feat(types,clerk-js): Allow users to delete external accounts

- packages/backend-core/src/api/resources/Props.ts
- packages/backend-core/src/api/resources/User.ts
- packages/clerk-js/src/core/resources/User.ts
- packages/types/src/json.ts
- packages/types/src/user.ts
Expose user.externalId field in frontend in backend SDKs.
The externalId is used during imports. If developers had an Auth0, Firebase, ... id and need to use that to reference the user after migrating to clerk they can store the value there via the [Clerk backend API](https://app.gitbook.com/o/-MR3KHqfIZeA28O45hN0/s/I9lfkxGTyVexN5kBVE7A/reference/backend-api-reference/users#create-a-user).
#180
> Expose user.external_id attribute

- packages/remix/src/client/ClerkCatchBoundary.tsx
- packages/remix/src/client/Interstitial.tsx
- packages/remix/src/client/RemixClerkProvider.tsx
- packages/remix/src/client/types.ts
- packages/remix/src/ssr/getAuthData.ts
- packages/remix/src/ssr/rootAuthLoader.ts
- packages/remix/src/ssr/utils.ts
Add the `Auth-Result` response header on Remix.
> feat(remix): Add Auth-Result response header

- packages/clerk-js/src/ui/signIn/SignInFactorOne.tsx
Problem
When back button was clicked, it hides the all strategies page and renders the factor-one
But we have no first factors hence it renders empty page
Solution
When no local strategies exist, we display the all strategies page and when back button is clicked we go back to `/sign-in`
> fix(clerk-js): Go back to sign in when back button is clicked and no local factor strategies exist

- packages/clerk-js/src/core/resources/Organization.test.ts
- packages/clerk-js/src/core/resources/Organization.ts
- packages/clerk-js/src/core/resources/OrganizationMembership.test.ts
- packages/clerk-js/src/core/resources/__snapshots__/Organization.test.ts.snap
- packages/clerk-js/src/core/resources/__snapshots__/OrganizationMembership.test.ts.snap
- packages/types/src/json.ts
- packages/types/src/organization.ts
Added support for organization `publicMetadata`. The metadata can be read from server responses, but not modified.
> feat(clerk-js): Support organization metadata

- packages/clerk-js/src/core/resources/SignUp.ts
- packages/clerk-js/src/ui/signUp/SignUpStart.tsx
Modified the sign up flow in the SignUpStart component when a ticket is present in the query parameters, but the sign up cannot be completed. 
We check if there's any social login method available and render it. When the user then clicks on the social login provider button, we'll check if there's an existing sign up object and opt to update it instead of creating a new one.
> feat(clerk-js): OAuth with ticket

- packages/backend-core/API.md
- packages/backend-core/src/__tests__/apis/OrganizationApi.test.ts
- packages/backend-core/src/api/collection/OrganizationApi.ts
- packages/backend-core/src/api/resources/JSON.ts
- packages/backend-core/src/api/resources/Organization.ts
- packages/backend-core/src/api/resources/Props.ts
Added support for organization public and private metadata. Both can be set upon organization creation by the backend.
> feat(backend-core): Organization metadata

- packages/react/src/components/controlComponents.tsx
- packages/react/src/contexts/StructureContext.tsx
Make our controlled components compatible with the latest `@types/react@18` package.
`React.FC` no longer includes `children` by default, as seen in this PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56210
> feat(clerk-react): Explicitly type children for React.FC components

- packages/clerk-js/src/core/clerk.ts
- packages/clerk-js/src/core/resources/Organization.test.ts
- packages/clerk-js/src/core/resources/Organization.ts
- packages/clerk-js/src/core/resources/OrganizationMembership.test.ts
- packages/clerk-js/src/core/resources/__snapshots__/Organization.test.ts.snap
- packages/clerk-js/src/core/resources/__snapshots__/OrganizationMembership.test.ts.snap
- packages/types/src/clerk.ts
- packages/types/src/json.ts
- packages/types/src/organization.ts
Added support for organization slugs. Added slug as a parameter in `clerk.createOrganization()`.
> feat(clerk-js): Organization slugs

- packages/backend-core/API.md
- packages/backend-core/src/__tests__/apis/OrganizationApi.test.ts
- packages/backend-core/src/api/collection/OrganizationApi.ts
- packages/backend-core/src/api/resources/JSON.ts
- packages/backend-core/src/api/resources/Organization.ts
- packages/backend-core/src/api/resources/Props.ts
Added support for organization slugs in the backend-core package. The organization API's `create()` function accepts an optional string argument for the slug.
> feat(backend-core): Organization slug

- packages/clerk-js/src/core/fapiClient.ts
- packages/clerk-js/src/core/resources/Base.ts
- packages/clerk-js/src/core/resources/EmailAddress.ts
- packages/types/src/resource.ts
Add _rotating_token_nonce parameter to reload function for each ClerkJS resource.
This token nonce can is used to safely update `__client` jwt in authentication scenarios where the auth takes place across two different outlets e.g. OAuth in native apps.
> fix(clerk-js): Introduce rotating_token_nonce param

- packages/backend-core/src/api/utils/ErrorHandler.ts
- packages/nextjs/src/api/index.ts
Expose Clerk singleton on @clerk/nextjs/api
Errors are returned as shown below in the response body from the Clerk backend. 
Previously we did not decode them as needed resulting in failure to return them to the user in a proper manner. This resulted in a cryptic error `(error.data || []).forEach forEach is not a function`
The `export *` syntax does not include default exports. This resulted in the singleton Clerk object not being available to pull from the `@clerk/nextjs/api` .
> fix(nextjs,backend-core): Fix handleError parsing

- packages/backend-core/src/api/utils/RestClient.ts
Fixes the type mismatch between the ClerkFetcher body and the returned type from snakecase-keys.
This is a hotfix that just casts the type of snakecase-keys to be what the fetcher is expecting. Ideally this should have a proper fix eventually.
https://github.com/clerkinc/javascript/issues/205
> cast snakecaseKeys return type to match ClerkFetcher body

- packages/backend-core/src/Base.ts
- When `buildAuthState` returned an erroneous AuthState status _(`!== SignedIn`)._ the response was not returned as it should be to the user.
> fix(backend-core): Fix case of buildAuthState erroneous return value

- packages/clerk-js/src/core/resources/Organization.ts
- packages/clerk-js/src/core/resources/__snapshots__/Organization.test.ts.snap
- packages/clerk-js/src/core/resources/__snapshots__/OrganizationMembership.test.ts.snap
- packages/types/src/organization.ts
This PR adds two new methods on the organization resource:
Allows an admin to delete the current organization.
Allows an admin to add other users as members without having to go via the invitation flow.
This method accepts two parameters (given as an object):
* `userId`: The id of the user that will be added as a member to the organization.
* `role`: The role that this user will have in the organization. Valid values for the role are: `admin` and `basic_member`.
Please note that in order to add a user as a member to an organization, he needs to be in the same instance of the organization and not already be a member of that organization.
> ClerkJS delete organizations and add members without the invitation flow

- packages/clerk-js/src/core/resources/Organization.test.ts
- packages/clerk-js/src/core/resources/Organization.ts
- packages/clerk-js/src/core/resources/OrganizationMembership.test.ts
- packages/clerk-js/src/core/resources/__snapshots__/Organization.test.ts.snap
- packages/clerk-js/src/core/resources/__snapshots__/OrganizationMembership.test.ts.snap
- packages/types/src/json.ts
- packages/types/src/organization.ts
Added an `Organization.setLogo()` method to set or update an organization's logo. Accepts the file as a parameter. 
Added support for the `Organization.logoURL` attribute.
> ClerkJS Organization logo

- packages/clerk-js/src/core/devBrowserHandler.ts
- packages/clerk-js/src/utils/cookies/handler.ts
In Auth V2 Dev Browser cookie is handled 100% by local storage. As a result the PSL domain resolution is not required anymore in ClerkJS since in V3 Auth V1 support was dropped.
> Auth v1 cookie cleanups

- packages/clerk-js/src/ui/signIn/SignInStart.tsx
- packages/clerk-js/src/ui/signIn/__snapshots__/SignInStart.test.tsx.snap
- packages/nextjs/src/middleware/withServerSideAuth.ts
When a user opens sign in page on a mobile the input field is focused causing the mobile keyboard to open and hiding the oauth sign in strategies.
This change aims to disable autofocus when oauth is used so that they are properly presented to the user
https://www.notion.so/clerkdev/a853f869f69c414b85e6d5290a2c4172?v=b253a2f980c641de8992cc63ed416fa0&p=fb3e1055f0a144ba96482c505a65248d
> fix(clerk-js): Disable input autofocus when oauth is used

- packages/backend-core/API.md
- packages/backend-core/src/__tests__/apis/OrganizationApi.test.ts
- packages/backend-core/src/api/collection/OrganizationApi.ts
Added a new method in the organizations API to update and merge organization metadata. 
The method name is `updateOrganizationMetadata`. It triggers a `PATCH /v1/organizations/:id/metadata` request to the Clerk API and accepts `publicMetadata` and `privateMetadata` parameters.
The metadata will be merged with any existing metadata on the organization.
> feat(backend-core): Update organization metadata

- packages/remix/src/client/Interstitial.tsx
This should fix issues when apps are using https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Embedder-Policy
| NOTE: This change may need to happen in other places but this is one that I need.
> set intersticial script tag as crossOrigin='anonymous'

- packages/backend-core/API.md
- packages/backend-core/src/__tests__/apis/OrganizationApi.test.ts
- packages/backend-core/src/api/collection/OrganizationApi.ts
Added support for updating an organization in the backend-core package. The new method signature is `Organization#update(organizationId, params)`.
> feat(backend-core): Update organization

- packages/backend-core/API.md
- packages/backend-core/src/__tests__/apis/OrganizationApi.test.ts
- packages/backend-core/src/api/collection/OrganizationApi.ts
Added a method to delete an organization in our backend-core package.
The signature is `organizations.deleteOrganization(organizationId)`.
> feat(backend-core): Delete an organization

- packages/clerk-js/src/core/resources/UserSettings.test.ts
- packages/clerk-js/src/core/resources/UserSettings.ts
- packages/clerk-js/src/ui/signUp/SignUpStart.test.tsx
- packages/clerk-js/src/ui/signUp/SignUpStart.tsx
- packages/types/src/userSettings.ts
Hide signup input form when an oauth exists but we have no auth factor
https://www.notion.so/clerkdev/Hide-name-in-SignUp-when-OAuth-is-the-only-factor-dd5341fba63c4237a7f66672d234e97a
> fix(clerk-js): Hide signup input form when an oauth exists but we have no auth factor

- packages/clerk-js/src/ui/signIn/SignIn.tsx
- packages/clerk-js/src/ui/signUp/SignUp.tsx
Teach ClerkJS to respect redirect_url upon completion of OAuth and email verification flows.
> fix(clerk-js): Use redirect_url across all auth flows

- packages/types/src/web3.ts
Introduce Web3 provider types and helpers the same way we do for OAuth providers
> feat(types): Introduce Web3 provider types and helpers

- packages/backend-core/API.md
- packages/backend-core/src/__tests__/apis/OrganizationApi.test.ts
- packages/backend-core/src/__tests__/utils/Deserializer.test.ts
- packages/backend-core/src/api/collection/OrganizationApi.ts
- packages/backend-core/src/api/resources/Enums.ts
- packages/backend-core/src/api/resources/JSON.ts
- packages/backend-core/src/api/resources/Organization.ts
- packages/backend-core/src/api/resources/OrganizationMembership.ts
- packages/backend-core/src/api/resources/Props.ts
- packages/backend-core/src/api/resources/index.ts
- packages/backend-core/src/api/utils/Deserializer.ts
This PR adds support for organization membership related operations in our `backend-core` package. It also adds resources for `OrganizationMembership` and `OrganizationMembershipPublicUserData`.
More specifically:
- Added a method to fetch all organization memberships for a given organization. The method signature is `organizations.getOrganizationMembershipList(params)`.
- Added a method to create organization memberships. The signature is `organizations.createOrganizationMembership(params)`.
- Added a method to update an organization membership. The signature is `organizations.updateOrganizationMembership(params)`.
- Added a method to delete an organization membership. The signature is `organizations.deleteOrganizationMembership(params)`.
> feat(backend-core): Organization memberships

- packages/backend-core/API.md
- packages/backend-core/src/__tests__/apis/OrganizationApi.test.ts
- packages/backend-core/src/__tests__/utils/Deserializer.test.ts
- packages/backend-core/src/api/collection/OrganizationApi.ts
- packages/backend-core/src/api/resources/Enums.ts
- packages/backend-core/src/api/resources/JSON.ts
- packages/backend-core/src/api/resources/OrganizationInvitation.ts
- packages/backend-core/src/api/resources/Props.ts
- packages/backend-core/src/api/resources/index.ts
- packages/backend-core/src/api/utils/Deserializer.ts
- packages/sdk-node/src/index.ts
- packages/sdk-node/src/instance.ts
Added support for organization invitations in our NodeJS SDK through the backend-core package.
Added a new `OrganizationInvitation` resource and the following methods on the organizations API:
- `createOrganizationInvitation` to create and send an invitation to join an organization.
- `getPendingOrganizationInvitationList` to retrieve a list of pending invitations for an organization.
- `revokeOrganizationInvitation` to revoke a pending organization invitation
> Support for organization invitations in NodeJS SDK

- packages/clerk-js/src/core/resources/Session.ts
When we do a session touch, we should include the active orgnization id if there is one.
This ensures that when we move from tab to tab where each tab has the same session but different organizations, each tab keeps the correct active organization.
> feat(clerk-js): Session touch includes the active organization

- packages/backend-core/API.md
- packages/backend-core/src/__tests__/apis/OrganizationApi.test.ts
- packages/backend-core/src/api/collection/OrganizationApi.ts
- packages/sdk-node/README.md
Added a method in the organizations API to retrieve a list of organizations for the instance specified by the API key. 
The method signature is `organizations.getOrganizationList()`.
The results can be paginated and are sorted by descending creation date. Most recent organizations are returned first.
> feat(backend-core): Retrieve instance organizations

- packages/backend-core/API.md
- packages/backend-core/src/__tests__/apis/OrganizationApi.test.ts
- packages/backend-core/src/api/collection/OrganizationApi.ts
Added a method on the organizations API to retrieve an organization by either ID or slug. 
The signature is `organizations.getOrganization({ organizationIdOrSlug: "acme-inc" })`.
> feat(backend-core): Get organization by ID or slug

- packages/gatsby-plugin-clerk/src/GatsbyClerkProvider.tsx
- [] `npm test` runs as expected.
Add the firefox redirect form method on gatsby plugin. _(This could have been breaking FF clients with gatsby)_.
> fix(gatsby-plugin-clerk): Add firefox interstitial parameter reload case

- package-lock.json
- packages/types/package.json
Remove typedoc as we don't use it for now.
> fix(types): Remove typedoc capability

- packages/clerk-js/src/v4/primitives/Button.tsx
- packages/clerk-js/src/v4/primitives/Flex.tsx
- packages/clerk-js/src/v4/primitives/Heading.tsx
- packages/clerk-js/src/v4/primitives/index.ts
- packages/clerk-js/src/v4/styledSystem/createCssVariables.ts
- packages/clerk-js/src/v4/styledSystem/createVariants.test.ts
- packages/clerk-js/src/v4/styledSystem/createVariants.ts
- packages/clerk-js/src/v4/styledSystem/fastDeepMerge.ts
- packages/clerk-js/src/v4/styledSystem/index.ts
This PR introduces more primitives, improvements to the `createVariants` algorithm (allows deep merging of pseudo-selector blocks) and lastrly, introduces `createCssVariables` method. This method makes defining locally-scoped variables inside different variants easy.
In the following example, we have a `colorScheme` variant that sets the color of the  `accentColor` CSS variable. Notice that the `type` variant does not need to defined the colors again - you can simply use the CSS variable we defined earlier.
```ts
const { accentColor } = createCssVariables('accentColor');
const { applyVariants, filterProps } = createVariants(theme => ({
variants: {
colorScheme: {
primary: {
[accentColor]: theme.colors.$primary500,
},
danger: {
[accentColor]: theme.colors.$danger500,
},
},
type: {
solid: { …
```
> Introduce more v4 primitives

- .eslintrc.js
- packages/clerk-js/src/v4/styledSystem/StyledSystemProvider.tsx
- packages/clerk-js/src/v4/styledSystem/createCssVariables.ts
- packages/clerk-js/src/v4/styledSystem/createVariants.test.ts
- packages/clerk-js/src/v4/styledSystem/createVariants.ts
- packages/clerk-js/src/v4/styledSystem/index.ts
- packages/clerk-js/src/v4/styledSystem/types.ts
- Gives access to component props inside the createVariants callback
- Restricts direct imports from `emotion`. This commit will be reverted when design-system is extracted as its own package
> chore(repo): Give access to props inside the createVariants callback

- packages/clerk-js/src/v4/primitives/Flex.tsx
- packages/clerk-js/src/v4/primitives/FormControl.tsx
- packages/clerk-js/src/v4/primitives/FormErrorText.tsx
- packages/clerk-js/src/v4/primitives/FormLabel.tsx
- packages/clerk-js/src/v4/primitives/Input.tsx
- packages/clerk-js/src/v4/primitives/hooks/index.ts
- packages/clerk-js/src/v4/primitives/hooks/useFormControl.tsx
- packages/clerk-js/src/v4/styledSystem/types.ts
New `FormControl` structure.
When using a FormControl, we need to make sure we keep some markup standards in place _(schematic and wai-aria)_.
For better internal DX the convention designed is something like:
```tsx
<FormControl hasError id='email'>
<FormLabel>Email</FormLabel>
<Input />
<FormErrorText>Email is required</FormErrorText>
</FormControl>
<FormControl isRequired id='username'
>
<FormLabel>Username</FormLabel>
<Input />
<FormErrorText>Username is required</FormErrorText>
</FormControl>
```
> chore(clerk-js): Add v4 FormControl system

- packages/clerk-js/src/core/clerk.test.ts
- packages/clerk-js/src/core/clerk.ts
- packages/clerk-js/src/ui/common/activeAccountsManager/ActiveAccountsManager.tsx
- packages/clerk-js/src/ui/common/verifyMagicLink/VerifyMagicLink.test.tsx
- packages/clerk-js/src/ui/signIn/SignIn.test.tsx
- packages/clerk-js/src/ui/signIn/SignInAccountSwitcher.test.tsx
- packages/clerk-js/src/ui/signIn/SignInFactorOne.test.tsx
- packages/clerk-js/src/ui/signIn/SignInFactorTwo.test.tsx
- packages/clerk-js/src/ui/signIn/SignInFactorTwo.tsx
- packages/clerk-js/src/ui/signIn/SignInStart.test.tsx
- packages/clerk-js/src/ui/signIn/SignInStart.tsx
- packages/clerk-js/src/ui/signIn/factorOne/SignInFactorOneInputBased.tsx
- packages/clerk-js/src/ui/signIn/factorOne/SignInFactorOneMagicLink.tsx
- packages/clerk-js/src/ui/signUp/SignUp.test.tsx
- packages/clerk-js/src/ui/signUp/SignUpContinue.test.tsx
- packages/clerk-js/src/ui/signUp/SignUpContinue.tsx
- packages/clerk-js/src/ui/signUp/SignUpStart.test.tsx
- packages/clerk-js/src/ui/signUp/SignUpStart.tsx
- packages/clerk-js/src/ui/signUp/SignUpVerify.test.tsx
- packages/clerk-js/src/ui/signUp/SignUpVerify.tsx
- packages/clerk-js/src/ui/signUp/SignUpVerifyEmailAddressWithMagicLink.tsx
- packages/clerk-js/src/ui/userButton/UserButtonPopup.test.tsx
- packages/clerk-js/src/v4/signIn/SignInStart.tsx
- packages/react/src/hooks/useSessionList.ts
- packages/react/src/hooks/useSignIn.ts
- packages/react/src/hooks/useSignUp.ts
- packages/react/src/isomorphicClerk.ts
- packages/types/src/clerk.ts
This PR introduces a new method called `setActive`. 
This basically replaces the older `setSession` which is now deprecated.
In addition to setting the active session, it can also be used to set the active organization for the session.
Its signature is:
```
export type SetActiveParams = {
session?: ActiveSessionResource | string | null;
organization?: string | null;
beforeEmit?: BeforeEmitCallback;
};
setActive: (SetActiveParams) => Promise<void>;
```
The session parameter can accept either an `ActiveSessionResource` or the id of such a session. It also accepts `null` in which case the current session will be removed.
The organization parameter accepts the id that we want to set as active in the session.
If no session parameter is passed, the currently active session will be used. …
> New `setActive` method to set the active session and organization

- packages/clerk-js/src/core/clerk.ts
- packages/clerk-js/src/ui/signUp/SignUp.tsx
- packages/types/src/clerk.ts
This commit fixes a navigation bug, after a successful OAuth flow but the sign up still missing some requirements to complete. We navigate to SignUpContinue form and as this is a same component navigation, it didn't properly work before
> fix(types,clerk-js): Same component navigate after OAuth flow with missing requirements

- packages/clerk-js/src/ui/common/errorHandler.test.ts
- packages/clerk-js/src/ui/common/errorHandler.ts
- packages/clerk-js/src/ui/userProfile/EditableListFieldRemoveCard.tsx
- packages/clerk-js/src/ui/userProfile/UserProfile.test.tsx
- packages/clerk-js/src/ui/userProfile/__snapshots__/UserProfile.test.tsx.snap
- packages/clerk-js/src/ui/userProfile/account/index.tsx
- packages/clerk-js/src/ui/userProfile/account/profileCard/ProfileCard.test.tsx
- packages/clerk-js/src/ui/userProfile/account/profileCard/ProfileCard.tsx
- packages/clerk-js/src/ui/userProfile/account/profileCard/ProfileWeb3Wallets.tsx
- packages/clerk-js/src/ui/userProfile/account/profileCard/__snapshots__/ProfileCard.test.tsx.snap
- packages/clerk-js/src/ui/userProfile/connectedAccounts/ConnectedAccountDetail.tsx
- packages/clerk-js/src/ui/userProfile/web3Wallets/AddNewWeb3Wallet.test.tsx
- packages/clerk-js/src/ui/userProfile/web3Wallets/AddNewWeb3Wallet.tsx
- packages/clerk-js/src/ui/userProfile/web3Wallets/Web3WalletDetail.test.tsx
- packages/clerk-js/src/ui/userProfile/web3Wallets/Web3WalletDetail.tsx
- packages/clerk-js/src/ui/userProfile/web3Wallets/Web3WalletList.test.tsx
- packages/clerk-js/src/ui/userProfile/web3Wallets/Web3WalletList.tsx
- packages/clerk-js/src/ui/userProfile/web3Wallets/__snapshots__/AddNewWeb3Wallet.test.tsx.snap
- packages/clerk-js/src/ui/userProfile/web3Wallets/__snapshots__/Web3WalletDetail.test.tsx.snap
- packages/clerk-js/src/ui/userProfile/web3Wallets/__snapshots__/Web3WalletList.test.tsx.snap
- packages/clerk-js/src/ui/userProfile/web3Wallets/index.tsx
- packages/types/src/user.ts
Allow users to list, preview, create/connect and delete a web3 wallet from their UserProfile, the same way they do for email addresses & phone numbers
> feat(types,clerk-js): Introduce web3 wallet operations in UserProfile

- packages/clerk-js/src/ui/signUp/SignUpContinue.test.tsx
- packages/clerk-js/src/ui/signUp/SignUpContinue.tsx
- packages/clerk-js/src/ui/signUp/SignUpForm.tsx
- packages/clerk-js/src/ui/signUp/SignUpStart.test.tsx
- packages/clerk-js/src/ui/signUp/SignUpStart.tsx
- packages/clerk-js/src/ui/signUp/signUpFormHelpers.test.ts
- packages/clerk-js/src/ui/signUp/signUpFormHelpers.ts
- packages/types/src/userSettings.ts
Add support in signUp form, for required/optional email address & phone number inputs. The feature is only supported for instances opt-in to upcoming Progressive sign up feature.
Below you can find some new scenarios that this PR adds ability for
> feat(types,clerk-js): Support required/optional email/phone for Progressive sign up instances

- packages/clerk-js/src/ui/common/verifyMagicLink/VerifyMagicLink.test.tsx
- packages/clerk-js/src/ui/common/verifyMagicLink/VerifyMagicLink.tsx
- packages/clerk-js/src/ui/signUp/SignUp.tsx
- packages/clerk-js/src/ui/signUp/SignUpContinue.test.tsx
- packages/clerk-js/src/ui/signUp/SignUpContinue.tsx
- packages/clerk-js/src/ui/signUp/SignUpStart.test.tsx
- packages/clerk-js/src/ui/signUp/SignUpStart.tsx
- packages/clerk-js/src/ui/signUp/SignUpVerify.test.tsx
- packages/clerk-js/src/ui/signUp/SignUpVerify.tsx
- packages/clerk-js/src/ui/signUp/SignUpVerifyEmailAddressWithMagicLink.tsx
- packages/clerk-js/src/ui/signUp/util.test.ts
- packages/clerk-js/src/ui/signUp/util.ts
During a signUp, might there be more than one identifier that need verification (e.g email & phone). Support the above flow, by teaching our accounts components to properly redirect to the corresponding screens
> feat(clerk-js): Support multiple unverified identifiers during Sign up flow

- packages/clerk-js/src/ui/userProfile/EditableListFieldRemoveCard.tsx
- packages/clerk-js/src/ui/userProfile/__snapshots__/UserProfile.test.tsx.snap
- packages/clerk-js/src/ui/userProfile/account/profileCard/ProfileCard.test.tsx
- packages/clerk-js/src/ui/userProfile/account/profileCard/ProfileCard.tsx
- packages/clerk-js/src/ui/userProfile/account/profileCard/__snapshots__/ProfileCard.test.tsx.snap
- packages/clerk-js/src/ui/userProfile/connectedAccounts/ConnectedAccountDetail.test.tsx
- packages/clerk-js/src/ui/userProfile/connectedAccounts/ConnectedAccountDetail.tsx
- packages/clerk-js/src/ui/userProfile/connectedAccounts/__snapshots__/ConnectedAccountDetail.test.tsx.snap
- packages/clerk-js/src/ui/userProfile/emailAdressess/EmailDetail.tsx
- packages/clerk-js/src/ui/userProfile/phoneNumbers/PhoneDetail.tsx
- packages/clerk-js/src/ui/userProfile/web3Wallets/Web3WalletDetail.tsx
- packages/clerk-js/src/ui/userProfile/web3Wallets/__snapshots__/Web3WalletDetail.test.tsx.snap
This PR includes:
- Improve connected account & web3 wallet removal page copyright
- Don't render connected account UserProfile section, if there isn't any OAuth provider enabled
> Improve UserProfile removal page copyright & render connected account section only if at least one OAuth provider is enabled

- packages/clerk-js/src/ui/common/constants.ts
- packages/clerk-js/src/ui/userProfile/__snapshots__/UserProfile.test.tsx.snap
- packages/clerk-js/src/ui/userProfile/web3Wallets/__snapshots__/AddNewWeb3Wallet.test.tsx.snap
- packages/types/src/web3.ts
Rename `Metamask` to `MetaMask` as the provider name
> fix(clerk-js,types): Typo for MetaMask web3 provider name

- packages/clerk-js/src/ui/signUp/SignUpForm.tsx
- packages/clerk-js/src/ui/signUp/SignUpStart.tsx
- packages/clerk-js/src/ui/signUp/signUpFormHelpers.test.ts
- packages/clerk-js/src/ui/signUp/signUpFormHelpers.ts
This commit fixes a regression introduced in our recent changes for Progressive SignUp. The actual problem was that we filtered out values even with empty string value, for our sign up payload request. This issue, lead the form to not render properly any input error if any of them was required and missing
> fix(clerk-js): Render SignUp form input errors if missing

- packages/react/src/isomorphicClerk.ts
Fixes the correct annotation for `setSession`, `setActive` .
Before:
After:
> fix(clerk-react): Correct annotations in isomorphicClerk for setSession

- packages/clerk-js/src/core/clerk.ts
This commit fixes `setActive` to set the active organization as `null` if the organization parameter that was passed in `setActive` is `null`.
> fix(clerk-js): If organization is `null`, set the active org as null

- package-lock.json
- packages/edge/package.json
- packages/edge/src/vercel-edge/index.ts
- packages/edge/src/vercel-edge/types.ts
- packages/nextjs/src/middleware/types.ts
- packages/remix/src/ssr/getAuthData.ts
- packages/sdk-node/src/Clerk.ts
- packages/types/src/ssr.ts
Add the correct claims type on all `claims` attributes. Mostly used on SSR and API routes.
> fix(edge,nextjs,remix,clerk-sdk-node,types): Correct SSR claims typing

- packages/backend-core/src/api/endpoints/OrganizationApi.ts
- packages/backend-core/src/api/endpoints/UserApi.ts
Fixed issue with unneeded metadata param stringification. With the current changes, metadata parameters were stringified twice, resulting in errors on api's like `users.createUser`. 
- Removed unneeded stringification.
> fix(backend-core): Remove unneeded stringifyMetadata function

- packages/clerk-js/src/core/resources/User.test.ts
- packages/clerk-js/src/core/resources/User.ts
- packages/types/src/user.ts
Introduce 2 new attributes on the User resource
- hasVerifiedEmailAddress: denote if the user has at least one verified email address
- hasVerifiedPhoneNumber: denote if the user has at least one verified phone number
> feat(types,clerk-js): Introduce user hasVerifiedEmailAddress & hasVerifiedPhoneNumber attributes

- packages/react/src/hooks/useOrganization.ts
Customer reported a hooks error on `useOrganization` in Discord. It is not clear why this made it through tests, but we do indeed appear to have conditional hooks here.
This PR is currently untested. We must ensure the organizations-demo still works before merging/publishing.
> [WIP] Attempt to resolve hooks error

- packages/clerk-js/src/ui/signIn/SignInStart.tsx
- packages/clerk-js/src/ui/signIn/__snapshots__/SignInStart.test.tsx.snap
- packages/clerk-js/src/ui/signIn/strategies/Password.tsx
- packages/clerk-js/src/ui/signIn/strategies/__snapshots__/Password.test.tsx.snap
- packages/clerk-js/src/ui/signUp/SignUpForm.tsx
- packages/clerk-js/src/ui/signUp/__snapshots__/SignUpContinue.test.tsx.snap
- packages/clerk-js/src/ui/signUp/__snapshots__/SignUpStart.test.tsx.snap
- packages/shared/components/form/Form.tsx
The addition of HTML ids aims to differentiate sign-in and sign-up forms so that tools like Hubspot treat them separately.
HubSpot groups form submissions based on the CSS ID or class attribute of your non-HubSpot form. If you have multiple forms with the same identifiers, submissions to these different forms will be associated with the same non-HubSpot form in the forms dashboard.
More information can be found at
https://knowledge.hubspot.com/forms/pop-up-forms-and-non-hubspot-forms-faq#do-non-hubspot-forms-work-with-my-form-builder
> fix(clerk-js): Add HTML ids to <SignIn/> and <SignUp/> forms

- packages/clerk-js/src/core/clerk.test.ts
- packages/clerk-js/src/core/clerk.ts
This commit fixes a logical error in our redirect logic during an OAuth flow and progressive sign up. If the external account was verified and were still missing requirements for sign up to complete, we redirected to the sign-up continue url. Although the right thing to do, is to first check if there is an error on the external account verification. Image a scenario where an instance uses sign-up restrictions for emails. The user tries to sign-up using an OAuth account whose email is not listed on the allowlist. We should redirect them back on the sign-up url and preview the error, instead of the sign up continue path
https://www.notion.so/clerkdev/PSU-asks-for-email-after-OAuth-flow-although-it-s-already-provided-when-Allowlists-are-on-e8129bd8b7ca488abc5f07ef5b382a93
> fix(clerk-js): Fix navigation when an error occurs during progressive sign up flow

- packages/backend-core/package.json
- packages/backend-core/tsconfig.json
- packages/sdk-node/package.json
- packages/sdk-node/tsconfig.json
Minimum required Node.js version becomes Node 14. Targets have been chosen using https://github.com/microsoft/TypeScript/wiki/Node-Target-Mapping#node-14
> feat(clerk-sdk-node,backend-core)!: Upgrade targets to Node.js 14

- packages/clerk-js/src/core/errors.ts
> chore(clerk-js): Tweak error message when path prop is missing

- packages/clerk-js/src/core/clerk.test.ts
- packages/clerk-js/src/core/clerk.ts
- packages/clerk-js/src/core/fapiClient.ts
- packages/clerk-js/src/core/services/authentication/AuthenticationService.ts
- packages/types/src/clerk.ts
> Introduce touchSession Clerk option and onAfterResponseCallbacks improvements

- packages/nextjs/src/middleware/utils/sanitizeAuthData.ts
This allows for sensitive fields like `organization.privateMetadata` to be available inside the `withServerSideAuth` callback while ensuring that these fields will not get serialized into the client-accessible __NEXT_DATA__ script.
> fix(nextjs): Remove organization private metadata from __NEXT_DATA__

- packages/clerk-js/src/core/clerk.ts
- packages/clerk-js/src/utils/index.ts
- packages/clerk-js/src/utils/runtime.ts
- packages/expo/src/ClerkProvider.tsx
- packages/expo/src/runtime.ts
- packages/types/src/clerk.ts
This PR introduces the necessary frontend infrastructure in order to support Capacitor.js, browser extensions and similar stacks.
The new `standardBrowser` option controls if ClerkJS will load with the standard browser setup using Clerk cookies. Nonstandard browser stacks are browser extensions or hybrid frameworks such as Capacitor or Cordova.
> Non standard browser mode

- packages/clerk-js/src/ui/SignIn/SignInStart.tsx
- packages/clerk-js/src/ui/SignUp/SignUpStart.tsx
- packages/clerk-js/src/ui/common/constants.ts
Correctly handle any oauth errors upon redirect. Firing `signUp.create` without passing an empty `[]` dep array to the useEffect forced the component to go continuously rerender.
This PR also updates the error code to be in line with the BE changes
> fix(clerk-js): Correctly handle oauth error on redirect

- packages/clerk-js/src/core/resources/Image.test.ts
- packages/clerk-js/src/core/resources/Image.ts
When calling `Image.create` it performs a POST request to FAPI to create an image resource. 
Since it's a FAPI request, the response will be wrapped with the current client. 
So, the actual image JSON representation will be under the "response" key.
Before this fix, calling `Image.create` would return an image JSON object with all attributes set to `undefined`.
> fix(clerk-js): Image create returns a wrapped response

- packages/clerk-js/src/ui/UserProfile/RemoveResourcePage.tsx
Handle error while deleting user's last identification from UserProfile component
https://user-images.githubusercontent.com/22435234/186377734-b78e6482-b3a8-4218-a5aa-b2c572dd335a.mov
https://user-images.githubusercontent.com/22435234/186377767-5c98fbdc-d2d1-434f-8edd-9ea0bfc20fcd.mov
https://www.notion.so/clerkdev/Handle-error-while-deleting-last-user-identification-in-accounts-d590e08cb21b4efe996f64031fcaa7df
> fix(clerk-js): Handle error while deleting user's last identification

- packages/backend-core/src/__tests__/endpoints/OrganizationApi.test.ts
- packages/backend-core/src/api/endpoints/OrganizationApi.ts
- packages/backend-core/src/api/resources/JSON.ts
- packages/backend-core/src/api/resources/OrganizationMembership.ts
- packages/clerk-js/src/core/resources/OrganizationMembership.test.ts
- packages/clerk-js/src/core/resources/OrganizationMembership.ts
- packages/clerk-js/src/core/resources/__snapshots__/OrganizationMembership.test.ts.snap
- packages/types/src/json.ts
- packages/types/src/organization.ts
- packages/types/src/organizationMembership.ts
We've recently added public and private metadata fields for organization memberships. Both metadata fields can be  accessed from the Backend API, but public metadata can only be read from the Frontend API.
This PR adds support for the organization metadata fields by:
- Adding `publicMetadata` in the `OrganizationMembershipResource` type.
- Adding `publicMetadata` in the `OrganizationMembership` resource in clerkJS.
- Adding support for updating an organization membership's public and private metadata in backend-core and exposing it to our Node SDK.
The new backend-core method for the organizations API is `organizations.updateOrganizationMembershipMetadata()`.
> Organization membership metadata

- packages/backend-core/src/__tests__/endpoints/InvitationApi.test.ts
- packages/backend-core/src/api/endpoints/InvitationApi.ts
In the invitations API `createInvitation()` method, we were stringifying the value of the `publicMetadata` property. 
Since `publicMetadata` is already a JSON object, the additional stringify call is redundant.
Fixes #338
> fix(backend-core): Don't stringify invitations metadata

- packages/backend-core/API.md
- packages/backend-core/src/__tests__/endpoints/UserApi.test.ts
- packages/backend-core/src/api/endpoints/UserApi.ts
- packages/backend-core/src/api/resources/JSON.ts
- packages/backend-core/src/api/resources/User.ts
This PR introduces 2 related TOTP fields for user operations:
- A `user.totp_enabled` field that denotes if the user has enabled & verified TOTP
- A new optional parameter `totp_secret` for create user operation
> Introduce user.totp_enabled field and totp_secret optional param for create user operation

- packages/clerk-js/src/ui/SignUp/SignUpForm.tsx
This fixes a bug in the sign up form in the special case of email or phone. When email & phone are both optional, actually at least one must be provided for the sign up to complete, thus we have to render the special input instead of hiding it based on the layout showOptionalFields prop
###Before
https://user-images.githubusercontent.com/22435234/187372278-55012584-fbe4-4ab2-8faf-4161d1e06cc0.mov
https://user-images.githubusercontent.com/22435234/187372314-e0448de1-6ac6-43d9-ab33-f6a90ef8b5c0.mov
Part of https://www.notion.so/clerkdev/Return-error-for-missing-phone-in-email-or-phone-case-where-no-phone-is-submitted-69492036ccf542cda8e6d020113abe2b
> fix(clerk-js): Render email/phone input in case of both are optional

- packages/clerk-js/src/ui/SignUp/SignUpStart.tsx
- Replace 2 setSession invocations with the latest setActive api
> fix(clerk-js): Replace setSession with setActive

- packages/clerk-js/src/core/clerk.ts
Using the setActive() call from useOrganization() correctly sets the CSR version of the organization.
However, the session sent to the server page does not yet include the active organization as the previous __session JWT is still cached.
> fix(clerk-js): Clear session token cache when switching organizations

- packages/clerk-js/src/ui/SignUp/SignUpContinue.tsx
- packages/clerk-js/src/ui/SignUp/SignUpStart.tsx
This fixes a bug in the sign up form in the special case of email or phone. When email & phone are both optional and neither of them is provided the form rendered an error only in the input of the active identifier. We change this behavior to also render the respective error in the 'inactive' identifier input as well.
https://user-images.githubusercontent.com/22435234/187421188-9680b2f9-2b23-49f5-b045-567d3b80c76e.mov
https://user-images.githubusercontent.com/22435234/187421206-8b769001-7044-4297-95f3-cc929f6b4178.mov
_Note: There is some code duplication in the two SignUpStart & SignUpContinue components which we will tackle in a separate PR_
https://www.notion.so/clerkdev/Return-error-for-missing-phone-in-email-or-phone-case-where-no-phone-is-submitted-69492036ccf542cda8e6d020113abe2b
> fix(clerk-js): Render both errors in case of emailOrPhone in sign up form

- packages/clerk-js/src/ui/elements/Header.tsx
- packages/clerk-js/src/ui/foundations/typography.ts
- packages/clerk-js/src/ui/styledSystem/common.ts
Slightly increase the font sizes of all smaller elements according to the latest Figma designs.
> fix(clerk-js): Slightly increase the base font size for smaller elements

- packages/backend-core/API.md
- packages/backend-core/src/__tests__/endpoints/UserApi.test.ts
- packages/backend-core/src/api/endpoints/UserApi.ts
Introduce a new user operation `DisableUserMFA` which disables all user's MFA methods
https://www.notion.so/clerkdev/Deactivate-2FA-from-BAPI-c9c85987e8ce464baa703dcc77ea0360
> feat(backend-core): Introduce operation to disable user's MFA methods

- packages/clerk-js/src/ui/SignUp/SignUpForm.tsx
- packages/clerk-js/src/ui/SignUp/SignUpStart.tsx
Properly handles the following scenario: 
- an auth factor is enabled and set to optional (`required: false`)
- no other `required` fields exist
- `appearance.layout.showOptionalFields` is set to `false` (the default)
Before:
After:
> fix(clerk-js): Hide form if no required fields exist

- packages/gatsby-plugin-clerk/src/ssr/getAuthData.ts
- packages/gatsby-plugin-clerk/src/ssr/utils.ts
- packages/types/src/jwt.ts
Added the actorId of impersonation sessions to the withServerAuth() function for SSR. See #363 for more context.
> Make actorId available to gatsby SSR

- packages/clerk-js/src/core/resources/Session.test.ts
- packages/clerk-js/src/core/resources/Session.ts
- packages/nextjs/src/middleware/utils/injectAuthIntoRequest.ts
- packages/react/src/contexts/AuthContext.ts
- packages/react/src/contexts/ClerkContextProvider.tsx
- packages/react/src/hooks/useAuth.ts
- packages/remix/src/ssr/utils.ts
- packages/sdk-node/src/Clerk.ts
- packages/sdk-node/src/__tests__/middleware.test.ts
- packages/types/src/json.ts
- packages/types/src/session.ts
- packages/types/src/ssr.ts
Provide a way to determine whether the current session is impersonated by another user. 
The impersonating user is the "actor" and the user that's appeared to be signed in the session is the "subject".
- Add `Session.actorId` and `Session.isImpersonated()` in clerk-js.
```js
const session = useSession();
if (session.isImpersonated()) {
console.log(`The real user is ${session.actorId}`);
}
```
- Make the `actorId` available in the react `useAuth()` hook.
```js
const { userId, actorId } = useAuth();
if (actorId) {
console.log(`User ${actorId} is logged in as user ${userId}`);
}
```
- Make `actorId` available in sdk-node withAuth middleware.
```js
withAuth((req, res) => {
const { userId, actorId } = req.auth;
console.log(`User ${actorId} is logged in as user ${userId}`);
});
```
- Make …
> Authentication context for impersonation sessions

- packages/clerk-js/src/ui/UserProfile/EmailSection.tsx
- packages/clerk-js/src/ui/UserProfile/PhoneSection.tsx
For PSU instances, where isn't required to verify the email/phone to sign up, we should handle the case of a primary unverified email/phone as well. Right now the user can't do anything and thus can't verify it via the UserProfile
https://user-images.githubusercontent.com/22435234/189301885-cef2a4d0-820e-45e2-b4ec-5770f67e98a6.mov
https://user-images.githubusercontent.com/22435234/189301901-3e29133a-c58a-4838-8996-7a72434134e3.mov
https://www.notion.so/clerkdev/In-UserProfile-handle-case-of-unverified-primary-email-phone-bd048eba7bb34c3abcafbcb163f89c76
> fix(clerk-js): Handle the case of unverified primary email/phone in UserProfile

- packages/clerk-js/src/core/resources/DisplayConfig.ts
- packages/types/src/displayConfig.ts
This option denotes whether we need to show or hide the field form during sign up, when a developer wants to force their users to sign up with an oauth provider before filling in the other fields. This also needs to be tackled on the BE side as well, but for now hiding the forms through accounts/appearance should suffice.
The purpose of this PR is to update DisplayConfig to completely match the returned value from the Clerk BR
> fix(clerk-js): Introduce experimental__forceOauthFirst in DisplayConfig

- packages/clerk-js/src/ui/UserProfile/UserProfile.tsx
- packages/clerk-js/src/ui/UserProfile/VerifyWithLink.tsx
The following workaround is used in order to make magic links work when the `<UserProfile/>` is used as a modal. In modals, the routing is virtual. For magic links the flow needs to end by invoking the `/verify` path of the `<UserProfile/>` that renders the `<VerificationSuccessPage/>`. So, we use the `userProfileUrl` that defaults to Clerk Hosted Pages `/user` as a fallback.
> fix(clerk-js): Fix magic link verification in <UserProfile/> when used as a modal

- packages/clerk-js/src/ui/UserProfile/AddAuthenticatorApp.tsx
…e dep array
A user reported that the TOTP UserProfile component infinitely renders, causing the QR code to change for every new request.
We couldn't successfully reproduce this behavior, but it's most likely cause by the `[user]` dependency which we removed.
> fix(clerk-js): Stop infinite TOTP re-renders

- packages/sdk-node/package.json
- packages/sdk-node/tsconfig.build.json
- packages/sdk-node/tsconfig.esm.json
…packages
This package used to generate a `dist` and a `esm` *top level* directories. Our main build script deletes all `dist` directories prior to building but the `esm` dir in sdk-node remained in place,  resulting in repeated issues in case-sensitive filesystems.
To avoid further confusion in the future, this PR aligns the dist directory structure for the `clerk-sdk-node` package with everything else.
> chore(clerk-sdk-node): Align dist directory structure

- packages/clerk-js/src/core/resources/Error.ts
- packages/clerk-js/src/ui/SignIn/SignInStart.tsx
- packages/clerk-js/src/ui/SignUp/SignUpContinue.tsx
- packages/clerk-js/src/ui/SignUp/SignUpStart.tsx
- packages/clerk-js/src/ui/elements/ReversibleContainer.tsx
- packages/clerk-js/src/ui/elements/SocialButtons.tsx
- packages/clerk-js/src/ui/hooks/useEnabledThirdPartyProviders.tsx
- packages/clerk-js/src/ui/utils/errorHandler.ts
This PR add the ability to show or hide the web3 providers independently of the other oauth providers and completely aligns all related rules in SignInStart, SignUpStart and SignUpContinue to the equivalent rules of the Clerk v3 components.
To avoid duplicating the checks for the Divider, the Divider component is now decleratively added between the children elements of `SocialButtonsReversibleContainerWithDivider`
Lastly, this PR adds error handling for the Metamask plugin errors by showing a global card message (instead of rethrowing).
https://user-images.githubusercontent.com/1811063/191356228-cae8b8cc-34b7-4cbf-b247-055010c0c8f0.mp4
Note 2:
If no web3, oauth or other methods are enable, the components render nothing: 
However, this state should be made impossible via DAPI. …
> Handle web3 providers during PSU and correctly handle metamask errors

- packages/clerk-js/src/core/resources/Error.ts
- packages/clerk-js/src/ui/utils/errorHandler.ts
- packages/clerk-js/tsconfig.json
Found a small issue while testing the latest staging changes. Specifically: 
```
globalErrors[0].longMessage
```
could potentially throw an error, since the [0] element can be undefined. 
I'd like to enable the `noUncheckedIndexedAccess` strict TSC check but it results in many unhandled errors right now. Let's enable it periodically and progressively fix the errors from now on.
> fix(clerk-js): Handle undefined global errors in errorHandler

- packages/clerk-js/src/core/resources/BackupCode.ts
- packages/clerk-js/src/core/resources/User.test.ts
- packages/clerk-js/src/core/resources/User.ts
- packages/types/src/backupCode.ts
- packages/types/src/index.ts
- packages/types/src/json.ts
- packages/types/src/user.ts
- Introduce the new BackupCode resource and the relevant types
- Introduce a new `user.createBackupCode()` method, that generates a set for backup codes for a user
https://www.notion.so/clerkdev/Introduce-new-FAPI-me-backup-codes-endpoints-31f0832bb7544d4d90ba27758cac2a54
> feat(types,clerk-js): Introduce BackupCodeResource and user.createBackupCode() oepration

- packages/backend-core/API.md
- packages/backend-core/src/__tests__/endpoints/UserApi.test.ts
- packages/backend-core/src/api/endpoints/UserApi.ts
Added a `users.getOrganizationMembershipList()` method to fetch a user's organization memberships.
Results can be paginated with optional limit and offset parameters.
> feat(backend-core): User organization memberships

- packages/clerk-js/src/ui/elements/SocialButtons.tsx
Use the actual name of the 3rd party provider instead of the provider id in `SocialButtons`
> fix(clerk-js): Use provider name instead of id in SocialButtons

- packages/clerk-js/src/ui/common/PrintableComponent.tsx
- packages/clerk-js/src/ui/common/index.ts
This PR introduces a `<PrintableComponent/>` util allowing to print the contents of that component by calling `print`. The `print` method creates a hidden iframe, copies all relevant styles from the host document's head into the iframe, clones the component, and finally opens the print dialog.
Example usage:
```
import { PrintableComponent, usePrintable } from '../common';
const { print, printableProps } = usePrintable();
<PrintableComponent {...printableProps}>
<Heading>Your backup codes are:</Heading>
<Col gap={2}>
{backupCodes.map(code => (
<BackupCodeTile code={code} />
))}
</Col>
</PrintableComponent>
```
> Introduce <PrintableComponent />

- packages/clerk-js/src/core/errors.ts
- packages/clerk-js/src/core/resources/SignIn.ts
- packages/clerk-js/src/core/resources/SignUp.ts
- packages/clerk-js/src/ui/SignIn/SignInFactorOneCodeForm.tsx
- packages/clerk-js/src/ui/SignIn/SignInFactorOnePasswordCard.tsx
- packages/clerk-js/src/ui/SignIn/SignInFactorTwoBackupCodeCard.tsx
- packages/clerk-js/src/ui/SignIn/SignInFactorTwoCodeForm.tsx
- packages/clerk-js/src/ui/SignIn/SignInStart.tsx
That way, there will be no alert when ClerkJS components don't talk to an actual FAPI (e.g. in preview mode).
> chore(clerk-js): Print unexpected FAPI errors in console, not in alerts

- packages/backend-core/src/ClerkClient.ts
- packages/backend-core/src/__tests__/__snapshots__/exports.test.ts.snap
- packages/backend-core/src/index.ts
- packages/edge/src/vercel-edge/ClerkAPI.ts
- packages/edge/src/vercel-edge/index.ts
- packages/nextjs/server.d.ts
- packages/nextjs/server.js
- packages/nextjs/src/client/index.tsx
- packages/nextjs/src/middleware/utils/serializeProps.ts
- packages/nextjs/src/server/getAuthEdge.ts
- packages/nextjs/src/server/getAuthNode.ts
- packages/nextjs/src/server/types.ts
- packages/nextjs/src/server/utils/getAuth.ts
- packages/nextjs/src/server/utils/getAuthDataFromClaims.ts
- packages/nextjs/src/server/utils/withClerkMiddleware.ts
- packages/sdk-node/package.json
- packages/sdk-node/src/index.ts
This PR adds the following optional `options` arg to the `getAuth` helper: 
```
type GetAuthOptions = {
loadUser?: boolean;
loadSession?: boolean;
loadOrg?: boolean;
};
```
As usual, depending on the values of `options` the returned value of getAuth changing both during runtime and build time.
(similarly for loadSession and loadOrg)
This leads as to desired API that correctly supports accessing init clerk state during SSR, hydration and CSR. In essence, this can now replace `withServerSideAuth`
```
import { getAuth } from "@clerk/nextjs/server";
export const getServerSideProps = ({ req }) => {
const { userId, user, authServerSideProps } =  getAuth(req);
return {
props: { foo: "bar", authServerSideProps },
};
};
```
> feat(nextjs): Add user, session and org load capability to getAuth

- packages/clerk-js/package.json
- packages/clerk-js/src/core/resources/User.ts
- packages/clerk-js/src/ui/UserProfile/Content.tsx
- packages/clerk-js/src/ui/UserProfile/MfaBackupCodeAccordion.tsx
- packages/clerk-js/src/ui/UserProfile/MfaBackupCodeCreatePage.tsx
- packages/clerk-js/src/ui/UserProfile/MfaBackupCodeList.tsx
- packages/clerk-js/src/ui/UserProfile/MfaBackupCodePage.tsx
- packages/clerk-js/src/ui/UserProfile/MfaBackupCodeTile.tsx
- packages/clerk-js/src/ui/UserProfile/MfaPage.tsx
- packages/clerk-js/src/ui/UserProfile/MfaSection.tsx
- packages/clerk-js/src/ui/UserProfile/utils.ts
- packages/clerk-js/src/ui/icons/dot-circle-horizontal.svg
- packages/clerk-js/src/ui/icons/index.ts
- packages/types/src/json.ts
- packages/types/src/user.ts
- packages/types/src/userSettings.ts
Add the supported operations for backup codes in UserProfile. Users can select and generate a new set of backup codes if not already set and any other multi-factor method is enabled. Can also regenerate to get a new fresh set anytime they want. Users can copy in clipboard, download as txt file and print the codes
Not supported
https://user-images.githubusercontent.com/22435234/192485087-14380056-fbb8-4570-81ba-d0fb249e9ba5.mov
https://www.notion.so/clerkdev/Introduce-backup-code-operations-in-UserProfile-fdec6cbc1ffc4c5aa66456f3ca348b5e
> feat(types,clerk-js): Add support for backup code operations in UserProfille

- packages/clerk-js/src/core/resources/PhoneNumber.ts
- packages/clerk-js/src/core/resources/TOTP.ts
- packages/clerk-js/src/ui/UserProfile/MfaBackupCodeCreatePage.tsx
- packages/clerk-js/src/ui/UserProfile/MfaBackupCodeList.tsx
- packages/clerk-js/src/ui/UserProfile/MfaPhoneCodePage.tsx
- packages/clerk-js/src/ui/UserProfile/MfaTOTPPage.tsx
- packages/clerk-js/src/ui/UserProfile/SuccessPage.tsx
- packages/clerk-js/src/ui/UserProfile/VerifyTOTP.tsx
- packages/types/src/json.ts
- packages/types/src/phoneNumber.ts
- packages/types/src/totp.ts
**Must be merged after https://github.com/clerkinc/javascript/pull/393**
When a user enables a new MFA method for the first time also list the generated backup codes when applicable
https://user-images.githubusercontent.com/22435234/192973575-b9effcea-088e-46fe-a74f-2cfc84cfc5e2.mov
https://www.notion.so/clerkdev/Expand-existing-MFA-methods-phone-code-TOTP-and-generate-backup-codes-as-well-ca0a5ca55d664652b511de7f23df2fa4
> feat(types,clerk-js): Expand existing MFA methods with backup codes

- packages/nextjs/src/server/utils/getAuth.ts
> feat(nextjs): Make buildClerkProps return early if not signed in

- packages/clerk-js/src/ui/SignIn/utils.ts
- packages/clerk-js/src/ui/UserProfile/MfaBackupCodeAccordion.tsx
Phone code should take priority over backup code when determining and calculating the starting sign in second factor. That means the user should land on the phone OTP screen first instead of the backup code one
https://user-images.githubusercontent.com/22435234/193761202-94b3321e-e41c-4ca0-a469-56526cbcc6e8.mov
https://user-images.githubusercontent.com/22435234/193761215-b3a8fb39-5c73-4bdc-81da-73caaa684efe.mov
> fix(clerk-js): Phone code takes priority over backup code as second factor

- packages/clerk-js/src/ui/SignIn/SignInFactorTwoAlternativeMethods.tsx
- packages/clerk-js/src/ui/utils/factorSorting.ts
Instead of relying on the BE for the second factor alternative methods, apply the comparator logic in the component explicitly
> fix(clerk-js): Control sorting of second factor alternative methods

- packages/clerk-js/src/ui/elements/SocialButtons.tsx
> fix(clerk-js): Correctly truncate social buttons

- packages/clerk-js/src/ui/UserProfile/ActiveDevicesSection.tsx
- packages/clerk-js/src/ui/UserProfile/AddAuthenticatorApp.tsx
- packages/clerk-js/src/ui/UserProfile/MfaBackupCodeCreatePage.tsx
- packages/clerk-js/src/ui/elements/FullHeightLoader.tsx
- packages/clerk-js/src/ui/elements/index.ts
Replace the regular Spinner component with the new FullHeightLoader component in the following UserProfile places:
- Generate backup code page
- Adding TOTP page
- Active session section
https://user-images.githubusercontent.com/22435234/194555006-16c13bd9-077a-4e60-b24e-b13aff1d3bdf.mov
https://user-images.githubusercontent.com/22435234/194555037-5ed31634-c26c-4ac8-8703-8d1e8e8d57dc.mov
> fix(clerk-js): Introduce FullHeightLoader element and replace Spinner in UserProfile

- packages/clerk-js/src/ui/UserProfile/RootPage.tsx
- packages/clerk-js/src/ui/elements/Tabs.tsx
- packages/clerk-js/src/ui/elements/index.ts
- packages/clerk-js/src/ui/utils/getValidReactChildren.ts
- packages/clerk-js/src/ui/utils/index.ts
Implement tabs components. 
Note: Tabs are also accessible and can be navigated with arrow keys.
```jsx
<Tabs>
<TabsList>
<Tab>Active</Tab>
<Tab>Invited</Tab>
<Tab>Danger</Tab>
</TabsList>
<TabPanels>
<TabPanel>section 1</TabPanel>
<TabPanel>section 2</TabPanel>
<TabPanel>section 3</TabPanel>
</TabPanels>
</Tabs>
```
https://user-images.githubusercontent.com/23478420/194306448-a748c9cf-e629-4d97-a66f-ecbec67cd92b.mov
With disabled tabs
https://user-images.githubusercontent.com/23478420/194340255-5616d336-c798-4bc4-b2b9-acb0e56b4edd.mov
> fix(clerk-js): Implement tabs components

- packages/clerk-js/src/ui/ImpersonationFab/ImpersonationFab.tsx
The ImpersonationFab content now fades in and out when the Fab is hovered. Also, the entire Fab is now draggable.
> feat(clerk-js): Update impersonation fab behaviour

- packages/backend-core/API.md
- packages/backend-core/src/__tests__/endpoints/UserApi.test.ts
- packages/backend-core/src/api/endpoints/UserApi.ts
Add support for updating user's totp secret and backup codes
https://www.notion.so/clerkdev/Allow-updating-totp_secret-backup_codes-for-a-user-via-BAPI-77ed76eeed3d4681b54f04e2ae566016
> feat(backend-core): Add support for updating user's totp secret and backup codes

- packages/clerk-js/src/core/resources/UserSettings.test.ts
- packages/clerk-js/src/core/resources/UserSettings.ts
- packages/clerk-js/src/ui/components/SignIn/SignInStart.tsx
- packages/clerk-js/src/ui/components/SignUp/SignUpContinue.tsx
- packages/clerk-js/src/ui/components/SignUp/SignUpStart.tsx
- packages/clerk-js/src/ui/components/SignUp/signUpFormHelpers.ts
- packages/clerk-js/src/ui/elements/SocialButtons.tsx
- packages/clerk-js/src/ui/hooks/useEnabledThirdPartyProviders.tsx
- packages/types/src/userSettings.ts
Take into account the authenticatable flag for each OAuth provider and list only those that the value equals true in Sign in/up account. The available OAuth provides in Connect flow are not affected by this change
https://user-images.githubusercontent.com/22435234/195404163-340cabe5-bd39-43ed-b064-cbed6c3e0671.mov
Part of https://www.notion.so/clerkdev/Support-authenticatable-OAuth-ee443a7b777d4e47818844b8495a5633
> feat(types,clerk-js): List only authenticatable OAuth providers in Sign in/up components

- packages/clerk-js/src/ui/localization/defaultEnglishResource.ts
Since oauth can be used for more than authentication, we need to make the removal text more generic.
Related issue:
https://www.notion.so/clerkdev/Support-authenticatable-OAuth-ee443a7b777d4e47818844b8495a5633
> fix(clerk-js): Make connected account removal copywriting more generic

- packages/clerk-js/src/ui/Components.tsx
- packages/clerk-js/src/ui/components/OrganizationProfile/MemberListTable.tsx
- packages/clerk-js/src/ui/components/OrganizationProfile/OrganizationProfile.tsx
- packages/clerk-js/src/ui/components/OrganizationSwitcher/OrganizationSwitcherPopover.tsx
- packages/clerk-js/src/ui/components/OrganizationSwitcher/OrganizationSwitcherTrigger.tsx
- packages/clerk-js/src/ui/components/OrganizationSwitcher/OtherOrganizationActions.tsx
- packages/clerk-js/src/ui/elements/OrganizationPreview.tsx
- packages/clerk-js/src/ui/elements/PersonalWorkspacePreview.tsx
- packages/clerk-js/src/ui/elements/UserPreview.tsx
- packages/clerk-js/src/ui/elements/contexts/CardStateContext.tsx
- packages/clerk-js/src/ui/localization/defaultEnglishResource.ts
- packages/clerk-js/src/ui/styledSystem/common.ts
- packages/types/src/localization.ts
- Adds org-switching functionality to OrganizationSwitcher
- Some small refactors here and there, nothing too big
WIP: 
- Create organization button is a noop for now
- showPersonalAccount is still hardcoded
https://www.notion.so/clerkdev/ClerkJS-Orgs-Introduce-OrganizationSwitcher-55803f6a78374fa181cdb6a9234803f2
> Add org switcher functionality

- packages/clerk-js/src/ui/elements/Tabs.tsx
> fix(clerk-js): Prioritize focus of tabs when keyboard navigating

- packages/clerk-js/src/ui/ImpersonationFab/ImpersonationFab.tsx
Correctly guard the ImpersonationFab from throwing during the session switch flow (user -> undefined -> user), or when the user is signed out (null)
> fix(clerk-js): Wrap ImpersonationFab with withCoreUserGuard

- packages/clerk-js/src/ui/elements/Avatar.tsx
Re-provide a fallback url for the `Avatar` element.
> fix(clerk-js): Fallback to Default Gravatar when not provided an imageUrl

- packages/clerk-js/src/ui/components/OrganizationSwitcher/OtherOrganizationActions.tsx
> fix(clerk-js): Remove unwanted scrollbar space from the OrgSwitcher

- packages/clerk-js/src/ui/elements/TagInput.tsx
> fix(clerk-js): Match TagInput line height to TagPill height

- packages/clerk-js/src/core/resources/OrganizationInvitation.test.ts
- packages/clerk-js/src/core/resources/OrganizationInvitation.ts
- packages/clerk-js/src/core/resources/__snapshots__/OrganizationInvitation.test.ts.snap
- packages/types/src/json.ts
- packages/types/src/organization.ts
- packages/types/src/organizationInvitation.ts
Added support for OrganizationInvitation publicMetadata. 
They can be set when calling the Organization#inviteMember() method.
> feat(clerk-js,types): Organization invitation metadata

- packages/backend-core/API.md
- packages/backend-core/src/__tests__/endpoints/OrganizationApi.test.ts
- packages/backend-core/src/api/endpoints/OrganizationApi.ts
- packages/backend-core/src/api/resources/JSON.ts
- packages/backend-core/src/api/resources/OrganizationInvitation.ts
Added support for passing public metadata when creating an organization invitation.
> feat(backend-core): Organization invitation metadata

- packages/clerk-js/src/core/clerk.ts
- packages/clerk-js/src/index.browser.ts
- packages/clerk-js/src/index.headless.browser.ts
- packages/react/src/isomorphicClerk.ts
- packages/react/src/types.ts
Store frontendAPI value on window as a fallback. This value can be used as a fallback during ClerkJS hot loading in case ClerkJS fails to find the "data-clerk-frontend-api" attribute on its script tag.
This can happen when the DOM is altered completely during client rehydration. For example, in Remix with React 18 the document changes completely via `hydrateRoot(document)`.
For more information refer to:
- https://github.com/remix-run/remix/issues/2947
- https://github.com/facebook/react/issues/24430
> fix(clerk-react): Add frontendAPI on window as a fallback

- packages/clerk-js/webpack.dev.js
Current our webpack-powered UMD packaging was setting `seld` as the output global object.
Historically, accessing the global object has required different syntax in different JavaScript environments. On the web you can use window, self, or frames - but in Web Workers only self will work. In Node.js none of these work, and you must instead use global. The this keyword could be used inside functions running in non–strict mode, but this will be undefined in Modules and inside functions running in strict mode. You can also use Function('return this')(), but environments that disable eval(), like CSP in browsers, prevent use of Function in this way.
This issue came up in Remix when ClerkJS is not hotloaded and should be bundled in the application. To fix it we use the `globalThis`.
The …
> fix(clerk-js): Fix globalObject for UMD packaging

- packages/clerk-js/src/core/resources/OrganizationInvitation.ts
- packages/types/src/organization.ts
Back in #486 we introduced the ability to set organization invitation metadata when inviting a new member to an organization. It was a mistake.
The public metadata for an organization invitation shouldn't be written through ClerkJS, but they can be read.
Removed the publicMetadata argument from the Organization#inviteMember method.
> fix(clerk-js,types): Invite org member public metadata

- packages/clerk-js/src/ui/hooks/usePopover.ts
As per floating-ui docs, popovers that use the `bubbles:false` prop need to remain in focus for accessibility controls to work as expected. When focus is lost inside our popover, it needs to be reinstated. 
I have not yet tested this for nested non-bubbling popovers(both popovers would have `bubbles:false`) as we do not use or intend to use them in the close future. We should see if the behaviour suits us in that case as well if we decide to use them in such manner.
> fix(clerk-js): Return focus to non-bubbling popovers when it is lost

- packages/clerk-js/src/utils/instance.test.ts
- packages/clerk-js/src/utils/instance.ts
Simplify FAPI checks in ClerkJS. That would also help local development flow.
> fix(clerk-js): Simplify FAPI checks in ClerkJS

- packages/clerk-js/src/ui/components/OrganizationProfile/InviteMembersForm.tsx
- packages/clerk-js/src/ui/components/OrganizationProfile/MemberListTable.tsx
Display the guest role only in the Active/Invited members tabled. Admins can set a guest to Admin/Member via the UI. Admin/Members can't be set to Guest. Guest role will not appear in the Invite screen.
> fix(clerk-js): Remove ability to select guest role from the UI

- packages/clerk-js/src/ui/components/SignUp/SignUpContinue.tsx
In the edge case an instance has both email & phone as optional and the user ends up in the sign up continue component after an OAuth flow, we should take into account the sign up missing fields to determine if we need to add extra fields in the payload
https://user-images.githubusercontent.com/22435234/199991227-1f2e8e87-2e8e-4795-a6b4-f3d38f54c37f.mov
https://user-images.githubusercontent.com/22435234/199991237-6878d4d1-1da2-4953-8013-3e9ac266c87c.mov
> fix(clerk-js): In case of emailOrPhone take into account missing fields for Sign up continue screen

- packages/clerk-js/src/ui/elements/SocialButtons.tsx
This PR fixes the error occurred by React when `SocialButtonIcon` is rendered and cannot handle the `providerName` attribute.
> fix(clerk-js): Fix React error on handling providerName attribute on SocialButtonIcon

- packages/clerk-js/src/ui/elements/AvatarUploader.tsx
If the components are mounted within an app using CSP, the developer will need to explicitly enable either the `data:` or the `blob:` protocols. The base64 (data:) protocol is more common, so we'll use that by default.
> fix(clerk-js): Replace createObjectUrl with a base64 transformation

- packages/types/src/signUp.ts
The sign up prepare verification method also supports an oauth strategy along with the redirect urls. This commit adds the missing params in the PrepareVerificationParams type
https://www.notion.so/clerkdev/Fix-inconsistencies-with-v1-client-sign_ups-signUpID-prepare_verification-endpoint-for-oauth-e63d5e662bf04c818a12162b02f92e40
> fix(types): Allow oauth strategy for sign up prepare verification

- packages/clerk-js/src/ui/elements/Avatar.tsx
`objectFit: 'contain'` causes this behaviour and overrides the `objectFit:'cover'` set on the container.
> fix(clerk-js): Remove object-fit:contain from Avatar

- packages/clerk-js/src/ui/elements/Navbar.tsx
Active navbar id is not correctly set when navigating between routes without clicking the navbar buttons. This PR makes sure that the active id is set on path changes.
Also reobserve navbar sections if the route changes, so that the active id changes based on which section is visible.
> fix(clerk-js): Set navbar active id based on path

- packages/clerk-js/src/ui/components/SignIn/SignInFactorOneEmailLinkCard.tsx
- packages/clerk-js/src/ui/components/SignUp/SignUpEmailLinkCard.tsx
- packages/clerk-js/src/ui/components/UserProfile/EmailPage.tsx
When the user leaves the magic link verification screen of the <SignIn/> or <SignUp/> open in a forgotten tab, the components should not re-trigger another delivery.
Before this fix, components were sending a magic link email every 10 minutes.
> fix(clerk-js): Stop re-triggering a magic link delivery on expiration

- package-lock.json
- packages/nextjs/package.json
- packages/nextjs/src/app-beta/auth.tsx
- packages/nextjs/src/server/utils/withClerkMiddleware.ts
> fix(nextjs): Pass auth-result from middleware to auth()

- packages/clerk-js/src/ui/components/SignUp/SignUpStart.tsx
The reason for this is that SignUp.create needs to be called to know the email of the invitee. If it is called with an email as the only required field, the sign up is completed and the user is created, so we cannon successfully let the user fill optional fields in this screen.
> fix(clerk-js): Proceed with token flow if email is the only required field

- packages/backend-core/src/__tests__/__snapshots__/exports.test.ts.snap
- packages/backend-core/src/__tests__/endpoints/PhoneNumberApi.test.ts
- packages/backend-core/src/__tests__/endpoints/UserApi.test.ts
- packages/backend-core/src/api/endpoints/UserApi.ts
- packages/backend-core/src/api/resources/Deserializer.ts
- packages/backend-core/src/api/resources/JSON.ts
- packages/backend-core/src/api/resources/OauthAccessToken.ts
- packages/backend-core/src/api/resources/index.ts
Fixes https://github.com/clerkinc/javascript/issues/447
> fix(backend-core): Add missing OauthAccessToken types

- packages/clerk-js/headless/index.d.ts
- packages/clerk-js/headless/index.js
- packages/clerk-js/src/core/resources/index.ts
- packages/clerk-js/src/index.headless.ts
- packages/clerk-js/src/index.ts
- packages/expo/src/ClerkProvider.tsx
- packages/expo/src/index.ts
- packages/expo/src/singleton.ts
- packages/react/src/index.ts
- packages/react/src/types.ts
- packages/shared/src/utils/date.test.ts
- packages/shared/src/utils/date.ts
This PR exposes all ClerkJS error utilities so that users who import ClerkJS in their codebases (e.g. in Expo) can reuse the internal error handling logic. This came as a response to a customer request.
> Rework clerk js exports

- packages/clerk-js/src/ui/components/OrganizationSwitcher/OrganizationSwitcher.tsx
- packages/clerk-js/src/ui/components/OrganizationSwitcher/OrganizationSwitcherPopover.tsx
- packages/clerk-js/src/ui/components/UserButton/UserButton.tsx
- packages/clerk-js/src/ui/components/UserButton/UserButtonPopover.tsx
- packages/clerk-js/src/ui/elements/Menu.tsx
- packages/clerk-js/src/ui/elements/Modal.tsx
- packages/clerk-js/src/ui/elements/Navbar.tsx
- packages/clerk-js/src/ui/elements/Popover.tsx
- packages/clerk-js/src/ui/elements/Select.tsx
- packages/clerk-js/src/ui/elements/Tabs.tsx
- packages/clerk-js/src/ui/elements/contexts/CardStateContext.tsx
- packages/clerk-js/src/ui/elements/contexts/FloatingTreeContext.tsx
- packages/clerk-js/src/ui/elements/contexts/index.ts
- packages/clerk-js/src/ui/elements/index.ts
- packages/clerk-js/src/ui/hooks/usePopover.ts
- packages/clerk-js/src/ui/primitives/Button.tsx
When having nested popovers, clicking the second popover will result in all popovers being closed.
This PR attempts to fix this issue by utilizing more of the floating-ui library and take advantage of its focus-trap, focus-return mechanisms and its ability to allow or block dismissal bubbling in each popover.
I have introduced a new `<Popover>` component which wraps the `children` with the appropriate components needed by the `floating-ui` library. The new component also receives an `isOpen` props and hides `children` accordingly. It also traps the focus into the Popover and returns the focus once it is closed. 
The `usePopover` hook now receives the `bubbles?: boolean` prop which determined if the Popover dismissal should stop or continue in the popover. This makes more in sense in …
> feat(clerk-js): Improve Popover behaviour

- packages/clerk-js/src/ui/elements/PhoneInput/PhoneInput.tsx
> fix(clerk-js): Use ch to calculate phone input padding

- packages/clerk-js/src/ui/components/OrganizationSwitcher/OtherOrganizationActions.tsx
- packages/clerk-js/src/ui/components/SignIn/SignInAccountSwitcher.tsx
- packages/clerk-js/src/ui/components/UserButton/OtherSessionActions.tsx
- packages/clerk-js/src/ui/elements/Actions.tsx
- packages/clerk-js/src/ui/elements/Menu.tsx
- packages/clerk-js/src/ui/primitives/Button.tsx
The hoverAsFocus prop will enable the hover style on focus of the button. Useful for accessibility when we set the focusRing to false.
> feat(clerk-js): Add hoverAsFocus prop to Button primitive

- packages/clerk-js/src/testUtils.ts
- packages/clerk-js/src/ui/components/SignIn/__tests__/SignInFactorTwo.test.tsx
- packages/clerk-js/src/ui/utils/test/runFakeTimers.ts
Abstract `act` and jest timers behind a `runFakeTimers` HOF
> test(clerk-js): Add jest timers abstraction

- packages/shared/package.json
- packages/shared/tsup.config.ts
> fix(shared): Use legacy esm output

- packages/clerk-js/src/ui/components/UserProfile/AddAuthenticatorApp.tsx
- packages/clerk-js/src/ui/components/UserProfile/MfaBackupCodeCreatePage.tsx
- packages/clerk-js/src/ui/components/UserProfile/MfaBackupCodePage.tsx
- packages/clerk-js/src/ui/components/UserProfile/VerifyTOTP.tsx
- packages/clerk-js/src/ui/elements/SuccessPage.tsx
Add some missing button element descriptors in UserProfile TOTP & backup related screens, so a user can target them as well within the appearance prop
> fix(clerk-js): Add button element descriptors in TOPT & backup code related UserProfile screens

- packages/clerk-js/src/core/clerk.test.ts
- packages/clerk-js/src/core/clerk.ts
- packages/types/src/clerk.ts
The introduction of cookieless-auth for development instances makes Clerk redirection function crucial for application development as developers should use them to handle all redirection logic in their applications.
Url builders are meant to be used by non-browser environments such as Expo where as redirection functions use the url builders and operate in a browser context.
> feat(clerk-js): Separate url builders from Clerk redirection functions

- packages/clerk-js/src/ui/components/SignIn/__tests__/SignInFactorOne.test.tsx
- packages/clerk-js/src/ui/components/SignIn/__tests__/SignInFactorTwo.test.tsx
> test(clerk-js): Run fake timers in SignIn tests where necessary

- packages/clerk-js/src/ui/components/UserProfile/MfaBackupCodeList.tsx
- packages/clerk-js/src/ui/localization/defaultEnglishResource.ts
- packages/types/src/localization.ts
Add some missing localization keys for users to be able to translate all the text in the backup codes finish screen. This PR also adds some new localization resources which are the below:
- `userProfile.backupCodePage.title__codelist`
- `userProfile.backupCodePage. actionLabel__copy`
- `userProfile.backupCodePage. actionLabel__copied`
- `userProfile.backupCodePage. actionLabel__download`
- `userProfile.backupCodePage. actionLabel__print`
> fix(clerk-js): Add missing localization keys on backup codes finish screen

- packages/clerk-js/src/core/services/authentication/AuthenticationPoller.ts
- packages/shared/src/utils/index.ts
- packages/shared/src/utils/poller.ts
- packages/shared/src/utils/workerTimers/createWorkerTimers.ts
- packages/shared/src/utils/workerTimers/index.ts
- packages/shared/src/utils/workerTimers/workerTimers.types.ts
- packages/shared/src/utils/workerTimers/workerTimers.worker.ts
- packages/shared/tsconfig.json
- packages/shared/tsup.config.ts
For more context, you can read this [introductory article](https://developer.chrome.com/blog/timer-throttling-in-chrome-88/) briefly explaining what timer throttling is.
Our authentication poller uses a usual `setInterval` timer to check if the JWT needs to be refreshed and update the `__session` cookie accordingly. Even though most browsers claim to fire the timers at least once per minute, even when throttled, our tests have shown that background tabs under certain conditions will throttle the timers more, and the once-per-minute claim is not guaranteed. 
If the authentication poller does not fire at the correct interval and given that by default, we're using a very short-lived token for security reasons (~1min TTL), the token can expire, and any background requests using that token …
> Use web workers to fire timeouts and intervals

- packages/clerk-js/src/core/devBrowserHandler.ts
ClerkJS assumes it starts in cookieless mode by default. Then it switches to cookie based only if the FAPI POST /dev_browser request fails.
That way, redirecting from localhost to accounts will work correctly.
> fix(clerk-js): Fix cookieless logic

- packages/clerk-js/src/ui/components/OrganizationSwitcher/OtherOrganizationActions.tsx
- packages/clerk-js/src/ui/elements/OrganizationPreview.tsx
- packages/clerk-js/src/ui/elements/UserPreview.tsx
> feat(clerk-js): Align avatars in organization switcher popover

- packages/clerk-js/src/core/clerk.ts
> fix(clerk-js): Set organization to null when in personal workspace

- packages/clerk-js/src/ui/common/QRCode.tsx
- packages/clerk-js/src/ui/common/index.ts
- packages/clerk-js/src/ui/components/UserProfile/AddAuthenticatorApp.tsx
- packages/clerk-js/src/ui/customizables/elementDescriptors.ts
- packages/types/src/appearance.ts
Add a white border of 10px to the QR code svg so that it is scannable when the background is dark
Example with dark background:
> feat(clerk-js): Add white border to QR code svg

- packages/clerk-js/src/ui/elements/Avatar.tsx
Seems like we have the `object-fit: cover`  on the wrong element.
Before: 
After:
> fix(clerk-js): Set objectFit on the image in Avatar

- packages/clerk-js/src/ui/common/__tests__/authPropHelpers.test.ts
- packages/clerk-js/src/ui/common/authPropHelpers.ts
- packages/clerk-js/src/ui/portal/index.tsx
- packages/react/src/components/withClerk.tsx
- packages/types/src/clerk.ts
- packages/types/src/utils.ts
After this PR, when the `routing` prop is not passed, and the `path` prop is passed, `routing` will default to `'path'`.
The types for this are also stricter so the path prop will throw a typescript error if passed without `routing='path'`
> feat(clerk-js,types): Terse paths parameters

- packages/remix/src/errors.ts
- packages/remix/src/experimental/errors.ts
- packages/remix/src/experimental/ssr/getAuth.ts
- packages/remix/src/experimental/ssr/rootAuthLoader.ts
- packages/remix/src/experimental/ssr/utils.ts
- packages/remix/src/ssr/getAuth.ts
- packages/remix/src/ssr/rootAuthLoader.ts
- packages/remix/src/ssr/utils.ts
We temporarily throw the interstitial page from within getAuth in addition to the rootAuthLoader.ts
See https://github.com/remix-run/remix/issues/4791 for details
> fix(remix): Remix 1.8 hotfix

- packages/clerk-js/src/core/clerk.ts
- packages/clerk-js/src/core/resources/Session.ts
- packages/clerk-js/src/core/tokenCache.test.ts
- packages/clerk-js/src/core/tokenCache.ts
- packages/clerk-js/tsconfig.dev.json
- packages/clerk-js/tsconfig.json
- packages/clerk-js/webpack.dev.js
- packages/types/src/clerk.ts
**This is not the actual seActive fix**
- Deprecates setSession
- Adds better sourcemap support for debugging clerkjs locally
> setActive house keeping - p1

- packages/clerk-js/src/ui/elements/Actions.tsx
Tweak options spacing in organization switcher
> fix(clerk-js): Tweak options spacing in organization switcher

- packages/react/src/components/withClerk.tsx
- packages/types/src/clerk.ts
- packages/types/src/utils.ts
For users that incorrectly use the routing and path props on our components, this is a breaking change. To avoid unintentionally breaking production apps, we will delay this for v5
> Revert "feat(clerk-js,types): Terse paths parameters (#572)"

- packages/sdk-node/.gitignore
- packages/sdk-node/cjs/instance.d.ts
- packages/sdk-node/cjs/instance.js
- packages/sdk-node/esm/instance.d.ts
- packages/sdk-node/esm/instance.js
- packages/sdk-node/instance.d.ts
- packages/sdk-node/instance.js
- packages/sdk-node/package.json
Adds support for:
```
import Clerk from '@clerk/clerk-sdk-node/esm/instance';
```
and 
```
const Clerk = require('@clerk/clerk-sdk-node/cjs/instance').default;
```
As shown in the [clerk-sdk-node docs](https://clerk.dev/docs/reference/node/getting-started#esm)
> fix(clerk-sdk-node): Add esm/instance and cjs/instance import paths

- packages/clerk-js/src/core/resources/User.test.ts
- packages/clerk-js/src/core/resources/User.ts
It now returns just the first name or the last name.
This PR fixes the `fullName` value on the `User` resource. It now returns a value even if only First name or only Last name is set.
Until now:
- `firstName: 'A', lastName: 'B' => fullName: 'A B'`
- `firstName: 'A', lastName: '' => fullName: null`
- `firstName: '', lastName: 'B' => fullName: null`
- `firstName: '', lastName: '' => fullName: null`
After this PR:
- `firstName: 'A', lastName: 'B' => fullName: 'A B'`
- `firstName: 'A', lastName: '' => fullName: 'A'`
- `firstName: '', lastName: 'B' => fullName: 'B'`
- `firstName: '', lastName: '' => fullName: null`
Fixes [JS-73](https://linear.app/clerk/issue/JS-73/fix-the-fullname-property-returning-null-when-first-name-or-last-name)
> fix(clerk-js): Fix the fullName property returning null when First name or Last name is empty

- packages/clerk-js/src/ui/elements/PhoneInput/PhoneInput.tsx
- packages/clerk-js/src/ui/elements/Select.tsx
Since the `Select` component now uses the `withFloatingTree` HOC, its type defaults to the `Option`, which is the type the passed option is supposed to extend. To combat this, we now assert the type of the component.
> fix(clerk-js): Assert the Select type since it uses HOC with generic

- packages/clerk-js/src/ui/components/OrganizationProfile/MemberListTable.tsx
Leave the default border for the Select in order to appear aligned with the table headers.
> fix(clerk-js): Leave default border in Role Select in MemberListTable

- package-lock.json
- packages/sdk-node/cjs/instance.d.ts
- packages/sdk-node/cjs/instance.js
- packages/sdk-node/esm/instance.d.ts
- packages/sdk-node/esm/instance.js
- packages/sdk-node/package.json
- packages/sdk-node/tsconfig.build.json
- packages/sdk-node/tsconfig.esm.json
- packages/sdk-node/tsconfig.json
- packages/sdk-node/tsup.config.ts
- packages/shared/package.json
This PR introduces changes to the build process of the `clerk/clerk-sdk-node` package. Specifically,
- Transpile and bundle the package using `tsup` instead of `tsc`
- Correctly export the `/esm` and `/cjs` paths while retaining their default exports
- Introduce the `exports` field in package.json in preparation for `clerk/clerk-sdk-node@5`
Supporting all possible host app build configurations (module vs commonjs, pure JS vs TS, and the various `moduleResolution` strategies that can be used by TS) without introducing breaking changes to the exports of this package is impossible right now. 
This PR correctly supports the APIs we've exported so far, with slight modifications that should improve compatibility with the latest node and TS versions.
Currently, the following formats are …
> Revamp clerk-sdk-node build

- packages/clerk-js/src/ui/components/OrganizationProfile/OrganizationMembers.tsx
- packages/clerk-js/src/ui/components/OrganizationProfile/OrganizationSettings.tsx
- packages/clerk-js/src/ui/components/SignIn/AlternativeMethods.tsx
- packages/clerk-js/src/ui/components/SignIn/SignInFactorOnePasswordCard.tsx
- packages/clerk-js/src/ui/components/SignIn/SignInFactorTwoAlternativeMethods.tsx
- packages/clerk-js/src/ui/components/SignIn/SignInFactorTwoBackupCodeCard.tsx
- packages/clerk-js/src/ui/components/SignIn/SignInStart.tsx
- packages/clerk-js/src/ui/components/SignUp/SignUpContinue.tsx
- packages/clerk-js/src/ui/components/SignUp/SignUpStart.tsx
- packages/clerk-js/src/ui/elements/Footer.tsx
- packages/clerk-js/src/ui/elements/VerificationCodeCard.tsx
- packages/clerk-js/src/ui/elements/VerificationLinkCard.tsx
- packages/types/src/appearance.ts
This PR adds some extra classes to allow hiding of specific footer actions.
Example (in the sign-in screen):
Also fixing the casing for some elementIds that were recently introduced, and adding the type for a couple more, to get rid of some typescript errors.
> feat(clerk-js,types): Add footerLink elementIds

- packages/backend/README.md
- packages/backend/src/index.ts
- packages/remix/src/experimental/api/index.ts
- packages/remix/src/experimental/ssr/authenticateRequest.ts
Replaces the default Clerk export from clerk/backend with a named export to allow for easier CJS/ESM interoperability support
> fix(backend,remix): Replace default with a named Clerk export

- packages/react/src/isomorphicClerk.ts
As per the comment above the function which has been changed, we should only throw the error in development.
> fix(clerk-react): Only throw loadClerkJS error in development

- packages/clerk-js/src/ui/components/OrganizationSwitcher/OrganizationSwitcherTrigger.tsx
- packages/clerk-js/src/ui/components/OrganizationSwitcher/OtherOrganizationActions.tsx
- packages/clerk-js/src/ui/elements/Avatar.tsx
- packages/clerk-js/src/ui/elements/OrganizationPreview.tsx
- packages/clerk-js/src/ui/elements/UserPreview.tsx
- packages/clerk-js/src/ui/foundations/opacity.ts
Allow customization of the OrganizationSwitcher text color without having to target specific `p` elements.
Example: 
by doing: 
```
<OrganizationSwitcher
organizationProfileMode={'navigation'}
appearance={{
elements: {
organizationSwitcherTrigger: {
'&:hover': {
background: 'blue',
},
color: 'white',
background: 'blue',
},
},
}}
/>
```
> fix(clerk-js): Use inherited color in Previews

- packages/clerk-js/src/ui/elements/Navbar.tsx
- packages/clerk-js/src/ui/elements/RootBox.tsx
Set the color in these places to prevent the inheritance of the body color, since this was not the behaviour we currently have in v4.
> fix(clerk-js): Set color for RootBox and Navbar to prevent breaking change

- packages/nextjs/README.md
- packages/nextjs/src/server/utils/withClerkMiddleware.ts
When accessing the public interstitial endpoint the `frontentApi` passed in the query params so that BAPI can interpolate it in the interstitial HTML.
It's value it set to `process.env.NEXT_PUBLIC_CLERK_FRONTEND_API`.
For the new publishable keys, the `publishable_key` query param will be set instead if `process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY` is populated.
Note: current commit addresses only the existing public intestitial mechanism, not the upcoming clerk-backend version.
> feat(nextjs): Support publishable key in public interstitial

- packages/backend/src/tokens/request.ts
This commit adds support for the new issuer format we are going to introduce for our dev instances. The new format is `https://foo-bar-13.clerk.accounts.dev` when the old one would be `https://clerk.foo.bar-13.lcl.dev`
> feat(backend): Support new issuer format for dev instances

- packages/clerk-js/package.json
- packages/clerk-js/src/ui/elements/PhoneInput/PhoneInput.tsx
Added the logic to replace the emojis on Windows. A text for now, but we can add a sprite whenever it's ready!
Before:
After:
> fix(clerk-js): Display unsupported country emojis as Text

- packages/backend/src/tokens/keys.test.ts
- packages/backend/src/tokens/keys.ts
- packages/backend/tests/suites.ts
Add support for PEM JWT keys in the backend package
> feat(backend): Add support for PEM JWT key

- packages/clerk-js/src/ui/styledSystem/common.ts
Some letters were being cut off in this button variant.
Before: 
After:
> fix(clerk-js): Fix buttonSmallRegular line height

- packages/react/src/types.ts
- packages/remix/src/client/RemixClerkProvider.tsx
- packages/remix/src/client/types.ts
- packages/remix/src/errors.ts
- packages/remix/src/ssr/getAuth.ts
- packages/remix/src/ssr/utils.ts
- Correctly propagate `frontendApi` and `publishableKey` from rootAuthLoader to ClerkProvider
- Environment variables are no longer required, so `rootAuthLoader` now accepts all different keys (`apiKey, frontendApi, jwtKey, secretKey, publishableKey`). In order to fully support configurable keys during runtime, this PR makes `getAuth` accept a `frontendApi` or a `secretKey` so it's fully aligned with `rootAuthLoader`
> Support setting runtime api keys in @clerk/remix

- packages/react/src/contexts/ClerkProvider.tsx
- packages/react/src/isomorphicClerk.ts
- packages/react/src/utils/scriptLoader.ts
- packages/shared/src/errors/thrower.test.ts
- packages/shared/src/errors/thrower.ts
Before this change, when neither of the keys were set (publishableKey or frontendApi), the following error would be thrown:
The publishableKey passed to Clerk is invalid. You can get your
Publishable key at
https://dashboard.clerk.dev/last-active?path=api-keys. (key=)
This was misleading, since it implies that publishableKey is the only actionable from the user, whereas someone has to set either publishableKey _or_ frontendApi. Therefore, this patch changes the error message to the following when both keys are missing:
Missing frontendApi or publishableKey. You can get your key at
https://dashboard.clerk.dev/last-active?path=api-keys.
Similarly it renders more relevant messages when either of the keys were passed but was invalid.
Fixes AUTH-121
> fix(clerk-react): Proper error on missing API keys

- packages/sdk-node/src/clerkClient.ts
- packages/sdk-node/src/instance.ts
Clerk needs to be a *named* function in order to support the older new Clerk() syntax for v4 compatibility. Arrow functions can never be called with the new keyword because they do not have the [[Construct]] method.
> Bucket of pre-release fixes vol 2

- packages/backend/src/util/instance.ts
- packages/react/src/utils/scriptLoader.ts
The new FAPI/Accounts hosts when publishable key is used, end in accountsstage.dev. Therefore we fix the interstitial to properly detect that we're on staging and load the appropriate version, instead of using `latest`.
Resolves AUTH-127
> fix(backend,clerk-react): Staging detection for new hosts

- packages/react/src/contexts/ClerkContextProvider.tsx
This is a hotfix as more investigation is required. It looks like a mutation causes state.session.user.organizationMembership to be [] under certain conditions, while state.user.organizationMembership contains the expected memberships.
> fix(clerk-react): Fix useAuth failing after user update

- packages/backend/src/api/factory.test.ts
- packages/backend/src/api/request.ts
- packages/backend/src/constants.ts
- packages/backend/src/tokens/authObjects.ts
- packages/backend/src/tokens/request.ts
- packages/sdk-node/src/authenticateRequest.ts
- packages/sdk-node/src/clerkExpressRequireAuth.ts
- packages/sdk-node/src/clerkExpressWithAuth.ts
- packages/sdk-node/src/types.ts
- Fix an error parsing issue
- Introduces the auth.debug function in the `backend` package
Example usage: 
```tsx
app.use(clerk.expressWithAuth())
app.get('/', async (req: WithAuthProp<Request>, res: Response) => {
const { userId, debug } = req.auth;
console.log(debug());
res.json({ auth: req.auth });
});
```
- Decorate the response in clerk-sdk-node with the requestState observability headers when applicable:
These headers are: 
```
AuthStatus: 'x-clerk-auth-status',
AuthReason: 'x-clerk-auth-reason',
AuthMessage: 'x-clerk-auth-message',
```
> Improve authenticateRequest observability

- package-lock.json
- packages/backend/package.json
- packages/backend/src/tokens/interstitial.ts
- packages/backend/src/tokens/request.ts
- packages/nextjs/src/api/requireAuth.ts
- packages/nextjs/src/api/withAuth.ts
This PR ensures that the frontendApi key is correctly populated when Publishable Key is used.
> chore(backend,nextjs): Correctly propagate PK in backend

- packages/backend/src/api/factory.ts
- packages/backend/src/api/request.ts
- packages/backend/src/tokens/authObjects.ts
- packages/backend/src/tokens/errors.ts
- packages/backend/src/tokens/factory.ts
- packages/backend/src/tokens/keys.ts
- packages/backend/src/tokens/request.test.ts
- packages/backend/src/tokens/request.ts
- packages/backend/src/tokens/verify.ts
- packages/nextjs/src/middleware/utils/authenticateRequest.ts
- packages/nextjs/src/server/clerk.ts
- packages/nextjs/src/server/withClerkMiddleware.ts
- packages/remix/src/errors.ts
- packages/remix/src/ssr/authenticateRequest.ts
- packages/sdk-node/src/authenticateRequest.test.ts
- packages/sdk-node/src/authenticateRequest.ts
- packages/sdk-node/src/clerkExpressRequireAuth.ts
- packages/sdk-node/src/clerkExpressWithAuth.ts
Add support for the new `secretKey` prop & `CLERK_SECRET_KEY` env variable and flag the old apiKey as deprecated
> feat(backend,nextjs,remix,clerk-sdk-node): Support new secretKey prop

- packages/nextjs/src/server/clerk.ts
- packages/nextjs/src/server/getAuth.ts
<In the next.js server package we were ignoring the new secretKey prop (CLERK_SECRET_KEY). This was causing any Backend request failing as there were no key
> fix(nextjs): Propagate correctly the new secretKey prop in nextjs server package

- packages/backend/src/tokens/interstitialRule.ts
- packages/backend/src/tokens/request.ts
Purpose of this PR is to extract the interstitial rules to separate module and allow those roles to be unit tested and covered extensively!
Related to: https://github.com/clerkinc/javascript/pull/669
> fix(backend): Extract interstitial rules from tokens/request

- packages/backend/src/constants.ts
- packages/backend/src/tokens/keys.test.ts
- packages/backend/src/tokens/keys.ts
Use the same approach as clerk-ruby-sdk and refresh jwks from remote when kid is not found only if more than 5 minutes have passed since the latest cache update!
> fix(backend): Refresh jwks when kid not found if at least 5 min have passed

- package-lock.json
- packages/backend/package.json
- packages/backend/src/tokens/interstitial.ts
- packages/backend/src/tokens/request.ts
- packages/backend/src/util/parsePublishableKey.ts
NextJS cannot treeshake some of the modules within @clerk/shared. 
We're temporarily replacing the dependency with a copy of the required helpers while we investigate further
> fix(backend): Temporarily drop the `clerk/shared` dependency

- package-lock.json
- packages/sdk-node/package.json
This dependency has been incorrectly listed in our package.json. Removed as we no longer use it.
> fix(clerk-sdk-node): Remove unused jsonwebtoken dependency

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- packages/backend-core/README.md
- packages/edge/README.md
This is a prerequisite in order to deprecate @clerk/backend-core and @clerk/edge. We need to publish one last version in order to update the relevant README files at https://www.npmjs.com/package/@clerk/backend-core and https://www.npmjs.com/package/@clerk/edge
Deleting the actual files follows with a separate PR
> fix(backend-core,edge): Mark @clerk/backend-core and @clerk/edge as deprecated

- packages/nextjs/src/client/index.tsx
- packages/react/src/types.ts
- packages/types/src/key.ts
…
The usual _app.tsx provider (nextjs) should not throw an error if none of the keys were passed as props, because the keys can be configured via env variables.
Passing `{...pageProps}` mutes the error because `pageProps` is of type `any`
```
export default function App({ Component, pageProps }: AppProps) {
return <ClerkProvider>
<UserButton/>
<SignInButton/>
<Component {...pageProps} />
}
```
> fix(nextjs,types): Make frontendApi or publishableKey mutually exclusive but optional

- packages/nextjs/src/server/withClerkMiddleware.ts
…
The interstitial page was returned with a 200 code. This PR correctly sets the code to 401
> fix(nextjs): Correctly set 401 status code for the interstitial in withClerkMiddleware

- packages/react/src/contexts/ClerkProvider.tsx
This PR fixes the issue: 
When parsing the new Publishable Key, its Frontend API gets extracted and populated in the legacy `frontendApi` variable. This erroneously throws an error. Added an extra check to prevent this when PK is used.
> fix(clerk-react): Fix erroneously throwing an error when using the new Publishable Key

- packages/backend/src/tokens/authStatus.ts
- packages/backend/src/tokens/request.test.ts
- packages/backend/src/tokens/request.ts
- packages/nextjs/src/middleware/withServerSideAuth.ts
- packages/nextjs/src/server/withClerkMiddleware.ts
- packages/remix/src/ssr/getAuth.ts
- packages/remix/src/ssr/rootAuthLoader.ts
- packages/sdk-node/src/authenticateRequest.ts
- packages/sdk-node/src/clerkExpressRequireAuth.ts
- packages/sdk-node/src/clerkExpressWithAuth.ts
We have introduced the new `Unknown` state in `RequestState` and the `isUnknown` helper method to support the case of header expired token that should result in returning an http 401 without body before running any other middleware.
The reason we introduced another state instead of reusing the `Interstitial` as i initially suggested in the original discussion is to separate this case and avoid any more confusion about interstitial. With introducing the new state we are closer to the flow diagram and it is more clear to implement and understand. This is also easier to rollout since it's a new state and it will not affect the current implementation.
> Fix: Header token case of unknown 401

- packages/backend/package.json
- packages/gatsby-plugin-clerk/package.json
- packages/remix/package.json
This is a follow-up of https://github.com/clerkinc/javascript/commit/fdcd6b3f7c61490297a5fdfa80228cbb7787b49b
> fix(repo): Set the correct node engine for the SDKs

- packages/backend/src/runtime/index.ts
Invoking the global.fetch without binding it first to the globalObject fails in Cloudflare Workers with an "Illegal Invocation" error. To fix the issue, we have to bind fetch to the globalThis object. A customer reported this issue using @clerk/remix on Cloudflare Pages.
The globalThis object is supported for Node >= 12.0.
For more information, refer to https://github.com/supabase/supabase/issues/4417
> fix(backend): Prevent illegal invocation error

- package-lock.json
- packages/backend/package.json
- packages/backend/src/runtime/node/fetch.js
- packages/backend/tsconfig.json
- packages/sdk-node/tsconfig.json
- packages/shared/tsconfig.json
Drop support for Node 12, as Node 12 reached its end-of-life on 30 Apr 2022 and it no longer receives security updates.
The minimum required Node version is now 14.
> fix(backend,clerk-sdk-node,shared): Drop support for NodeJS 12

- packages/clerk-js/src/ui/Components.tsx
This PR may be fixing a race condition that causes components not to render on soft redirections on Next and Remix projects. According to the React 18 upgrade guide, ReactDOM.render should be replaced with createRoot. (https://reactjs.org/link/switch-to-createroot)
Error in console:
```
ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it’s running React 17.
```
> fix(clerk-js): Use createRoot instead of ReactDOM.render

- packages/backend/src/tokens/interstitial.ts
- packages/backend/src/tokens/request.ts
> fix(backend): Reverting priority of frontendApi over publishableKey

- packages/backend/src/index.ts
- packages/backend/src/tokens/authObjects.ts
- packages/backend/src/tokens/factory.ts
- packages/backend/src/tokens/index.ts
- packages/backend/src/tokens/interstitialRule.ts
- packages/backend/src/tokens/request.ts
- packages/backend/src/tokens/verify.ts
- packages/nextjs/src/server/getAuth.ts
- packages/nextjs/src/server/withClerkMiddleware.ts
- packages/react/src/utils/errorThrower.ts
- packages/remix/src/errorThrower.ts
- packages/remix/src/ssr/authenticateRequest.ts
- packages/remix/src/ssr/utils.ts
- packages/types/src/key.ts
Inline type imports were introduced in TS 4.5, which, at the moment of writing, can be considered a recent release. Customers using older TS/babel versions reported build errors when trying to compile the new clerk/backend package. We decided to replace inline type imports with the older syntax as we have no apparent need for it right now.
> fix(backend,types): Remove inline type imports

- packages/backend/src/tokens/keys.ts
- packages/react/src/types.ts
- packages/react/src/utils/scriptLoader.ts
- packages/sdk-node/src/clerkExpressRequireAuth.ts
- packages/types/src/clerk.ts
Mark `frontendApi` & `apiKey` props as deprecated
> chore(backend,clerk-react,clerk-sdk-node,types): Mark frontendApi & apiKey props as deprecated

- packages/backend/src/tokens/keys.test.ts
- packages/backend/src/tokens/keys.ts
- packages/backend/src/tokens/verify.test.ts
- packages/backend/src/tokens/verify.ts
Slightly modified the tokens.verifyToken() function into the below behavior:
- If a JWK KEY provided, use it to verify the provided token
- If a apiKey or secretKey provided, use the Backend API to fetch the JWKs and verify the provided token
- If an issuer of type string provided, use the Frontend API and well known endpoint to fetch the JWKs and verify the provided token
> feat(backend): Use Frontend API to fetch JWKs for token verification when issuer provided

- packages/clerk-js/src/core/clerk.ts
- packages/clerk-js/src/core/fapiClient.test.ts
- packages/clerk-js/src/core/fapiClient.ts
- packages/clerk-js/src/index.browser.ts
- packages/clerk-js/src/index.headless.browser.ts
- packages/nextjs/src/app-beta/client/ClerkProvider.tsx
- packages/nextjs/src/client/index.tsx
- packages/react/src/isomorphicClerk.ts
- packages/react/src/types.ts
- packages/react/src/utils/scriptLoader.ts
- packages/types/src/clerk.ts
Silenty introducing a new prop to handle FAPI requests through a proxy
> Add support for Reverse proxy

- packages/eslint-config-custom/index.js
This PR adds the `@typescript-eslint/consistent-type-imports` rule, with options to force separate type imports. This is useful to prevent the codebase from having inline type imports which are supported after TypeScript 4.5.
Documentation of this rule: https://typescript-eslint.io/rules/consistent-type-imports/
Relates to #713
> chore(eslint-config-custom): Add consistent-type-imports rule

- packages/clerk-js/src/core/clerk.ts
- packages/clerk-js/src/ui/Components.tsx
- packages/shared/src/utils/createDeferredPromise.ts
- packages/shared/src/utils/index.ts
When we replaced ReactDom.render with the new, React18, createRoot we noticed that the async (concurrent) nature of the new react version caused a race condition during the initial bootstrap phase.
```
ReactDom.render (pre r18)
- Components layout effect runs, componentControls is populated
- clerk isready
- mountUserButton
- Components mount
```
```
ReactDom.createRoot (r18)
- clerk isready
- mountUserButton // FAILS
- Components layout effect runs, componentControls is populated
- Components mount
```
The example above shows that when createRoot is used, the useLayoutEffect that populates the component rendered methods is fired asyncronously, possibly after clerk has loaded. If a mountComponent method is called before then (eg mountSignIn), clerk-js will throw. By awaiting the …
> fix(clerk-js): Await mountComponentRenderer to mount the components before firing loaded event

- packages/clerk-js/src/core/clerk.test.ts
- packages/clerk-js/src/core/clerk.ts
- packages/clerk-js/src/core/resources/Session.ts
This tickets tries to resolve cookie and session syncing issues found in setActive upon user and organization switching.
Steps to reproduce:
1. user with multiple organizations signin
2. visit `/organization` page from tab A with organization A
3. open Application tab in Developer tools and find `__session` cookie
4. open a new tab B
5. go back to tab A
6. switch to organization B
Cookie `__session` will include id of organization A instead of organization B.
Extra improvements in performance achieved with this PR:
1. org switch will not request `/tokens`
3. user switch will not request `/tokens`
5. poller will not request `/tokens` before 60 seconds (minus leeway) of inactivity (session cookie is being updated in every `/touch` request)
> Fix(clerk-js): setActive issue with cookie and session syncing

- packages/clerk-js/src/core/clerk.test.ts
- packages/clerk-js/src/core/clerk.ts
- packages/clerk-js/src/globals.d.ts
- packages/nextjs/src/client/index.tsx
- packages/nextjs/src/client/invalidateNextRouterCache.ts
- packages/nextjs/src/index.ts
See comment within the changes files
> chore(nextjs): Invalidate next sdc/sbc router cache before setActive

- packages/clerk-js/src/core/errors.ts
- packages/clerk-js/src/core/resources/Session.ts
- packages/clerk-js/src/core/tokenCache.test.ts
- packages/clerk-js/src/core/tokenCache.ts
getToken() makes the decision about returning from cache by comparing the exp claim on the JWT against the user's computer time. exp is generated on our server (GCP's clock), not the computer's time.
We're accounting for slow/fast clocks by measuring the elapsed time since the token was cached, instead of comparing GCP's clock with the user's clock.
> fix(clerk-js): Account for user clock skew in TokenCache

- packages/clerk-js/src/utils/url.ts
When a new image is uploaded, we show the base64 encoded image. In that case, we don't want to append any search params.
> fix(clerk-js): Do not modify src if it is data

- packages/clerk-js/src/core/clerk.ts
- packages/clerk-js/src/core/fapiClient.test.ts
- packages/clerk-js/src/core/fapiClient.ts
- packages/shared/src/errors/thrower.ts
- packages/shared/src/utils/index.ts
- packages/shared/src/utils/proxy.test.ts
- packages/shared/src/utils/proxy.ts
This PR allows users to use the following values for the proxyUrl prop
- `https://my-clerk-app.dev/api/__clerk` (useful for Expo)
- `/api/__clerk` (useful for web)
The previous pattern of `my-clerk-app.dev/api/__clerk` is no longer valid
> Allow absolute and relative paths for ProxyUrl

- packages/clerk-js/src/ui/common/authPropHelpers.ts
- packages/clerk-js/src/ui/contexts/ClerkUIComponentsContext.tsx
We want to support the following session for URL-based session syncing for development instances:
1. Visit https://happy-hippo.accounts.dev?redirect_url=https://my-local-app.dev
2. Sign-in via Clerk Hosted Pages
3. Redirect to https://my-local-app.dev and preserve the same session from step 2
This fix ensures that users will land on https://my-local-app.dev?#__dev_session=dev_browser_jwt_goes_here.
The fix should also resolve the experimental_after_impersonation_url scenario.
> fix(clerk-js): Decorate redirect urls for URL Based session syncing

- packages/nextjs/src/client/index.tsx
> fix(nextjs): Use useSafeLayoutEffect to mute Nextjs warning

- packages/clerk-js/src/core/clerk.test.ts
- packages/clerk-js/src/core/clerk.ts
Bug:
It seems that when signing out of one of the sessions, and now being in the "Choose a user to continue with" screen, the signout button does nothing. This happens because there is no session at that point and the function returns.
Fix:
Instead of checking that a session exists, check the number of the sessions and return based on that.
> fix(clerk-js): Fix sign out of all accounts when there is no active session

- packages/clerk-js/src/ui/elements/ApplicationLogo.tsx
> fix(clerk-js): Fetch larger image for application logos

- packages/backend/src/constants.ts
- packages/remix/src/errors.ts
- packages/remix/src/ssr/rootAuthLoader.ts
- packages/remix/src/ssr/utils.ts
We used to accept only plain objects as valid return values from the Remix `rootAuthLoader` helper. This PR adds support for custom instances of the Response class and custom headers. 
It's also important to note with this change, the API of the root loader for Remix apps using Clerk is now aligned to the api of any other loader, as both can return the same type of responses.
One limitation that remains is that if a custom non-redirect response is returned, its body must be a valid json object or a valid json string; otherwise we won't be able to inject the Clerk state.
Example usage:
```ts
export const loader: LoaderFunction = args => rootAuthLoader(args, ({ auth }) => {
const { userId } = auth;
const posts: Post[] = database.getPostsByUserId(userId);
return json({ data: posts })
})
``` …
> Support custom responses and headers in Remix rootAuthLoader

- packages/clerk-js/package.json
- packages/clerk-js/src/ui/elements/Menu.tsx
- packages/clerk-js/src/ui/elements/Modal.tsx
- packages/clerk-js/src/ui/elements/Popover.tsx
- packages/clerk-js/src/ui/elements/Select.tsx
- packages/clerk-js/src/ui/elements/contexts/FloatingTreeContext.tsx
- packages/clerk-js/src/ui/hooks/usePopover.ts
This will increase our bundlesize a bit since the floating-ui package has increased in size. Their implementation change that enables us to do this is quite recent as well. If the firefox issue (https://bugzilla.mozilla.org/show_bug.cgi?id=1363964) were to be resolved, we would not really need this, but the updates from floating-ui make our lives a little bit easier nonetheless.
> fix(clerk-js): Fix modals not closing in firefox when focus is lost

- packages/clerk-js/src/core/clerk.ts
- packages/shared/src/utils/browser.test.ts
- packages/shared/src/utils/browser.ts
- packages/shared/testUtils/setupGlobals.ts
- packages/shared/vite.config.ts
This PR tries to reduce the errors thrown when ClerkJS tries to initialize and fails on the first `/environment` and `/client` API calls to FAPI.
The following properties of the Navigator API have been used:
- [Navigator.userAgent](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/userAgent), to determine if the page is accessed by web crawlers/bots.
- [Navigator.webdriver](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/webdriver): This flag is enabled by automated tools (e.g. puppeteer) when accessing a web app.
- [Navigator.connection](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/connection): This **experimental** property holds information about the browser's network connection. As it is still an experimental feature, we use it with caution.
If the …
> Add extra checks before throwing error on ClerkJS initial network calls

- packages/clerk-js/src/core/clerk.ts
- packages/clerk-js/src/core/fapiClient.ts
- packages/clerk-js/src/index.browser.ts
- packages/clerk-js/src/index.headless.browser.ts
- packages/clerk-js/src/utils/getClerkQueryParam.ts
- packages/nextjs/src/client/index.tsx
- packages/react/src/isomorphicClerk.ts
- packages/react/src/types.ts
- packages/react/src/utils/scriptLoader.ts
- packages/types/src/clerk.ts
- packages/types/src/key.ts
As part of this PR we are introducing 2 new props for <ClerkProvider /> 
- isSatellite?: boolean → This prop will dictate whether or not we should perform Syncing with the primary app
- domain?: string → It should be the FAPI key of the satellite app e.g. clerk.satellite.dev 
Syncing with the primary app: 
- If isSatellite === true we should perform the syncing process to sync sessions with the primary app
- Redirect to https://clerk.satellite.dev/v1/client/sync?redirect_url=https://clerk.satellite.dev?synced=true 
- As part of the redirect_url we append ?synced=true as a way to determine that syncing was attempted
In a following PR we will tackle the necessary changes for interstitial
> Support multi-domain authentication

- packages/sdk-node/src/authenticateRequest.ts
- packages/sdk-node/src/withAuth.ts
- playground/fastify/.env.sample
- playground/fastify/.gitignore
- playground/fastify/package-lock.json
- playground/fastify/package.json
- playground/fastify/src/server.ts
- playground/nextjs/pages/organization/[[...index]].tsx
- playground/nextjs/pages/user/[[...index]].tsx
Allows `withAuth` of `@clerk/clerk-sdk-node` to become framework agnostic by introducing generics. Currently to avoid breaking our customers so we will drop the default types in v5 release.
I have also introduced a `fastify` playground to test the changes and the required steps to use that module in fastify. We will proceed in creating a `fastify` package to make it easier for our customers to consume (see playground/fastify code).
> Refactor @clerk/clerk-sdk-node `withAuth` and create fastify playground

- packages/remix/src/ssr/authenticateRequest.ts
Allowing to bypass the default api url (set in @clerk/backend) by using the `CLERK_API_URL` in remix
> fix(remix): Use CLERK_API_URL internally

- packages/backend/src/tokens/authObjects.ts
- packages/nextjs/src/api/__tests__/__snapshots__/exports.test.ts.snap
- packages/nextjs/src/edge-middleware/__tests__/__snapshots__/exports.test.ts.snap
- packages/nextjs/src/middleware/withServerSideAuth.ts
- packages/nextjs/src/server/getAuth.ts
- packages/sdk-node/src/__tests__/__snapshots__/exports.test.ts.snap
Auth objects moving through the server -> client boundary need to be serializable as we need to ensure that they can be transfered via the network as pure strings. Some frameworks like Remix or Next (/pages dir only) handle this serialization by simply ignoring any non-serializable keys, however Nextjs /app directory is stricter and throws an error if a non-serializable value is found.
> fix(backend,nextjs): Serialize auth objects before sending to client

- packages/clerk-js/src/ui/components/CreateOrganization/CreateOrganizationPage.tsx
- packages/clerk-js/src/ui/components/OrganizationProfile/InviteMembersForm.tsx
- packages/clerk-js/src/ui/components/OrganizationProfile/ProfileSettingsPage.tsx
- packages/clerk-js/src/ui/components/UserProfile/ProfilePage.tsx
- packages/clerk-js/src/ui/elements/TagInput.tsx
> fix(clerk-js): Add missing autoFocus prop to inputs

- packages/backend/src/index.ts
- packages/backend/src/tokens/authStatus.ts
- packages/backend/src/tokens/factory.ts
- packages/backend/src/tokens/interstitial.ts
- packages/backend/src/tokens/interstitialRule.ts
- packages/backend/src/tokens/request.test.ts
- packages/backend/src/tokens/request.ts
- packages/backend/src/tokens/verify.ts
- packages/backend/src/util/request.ts
- packages/nextjs/src/middleware/utils/authenticateRequest.ts
- packages/nextjs/src/middleware/withServerSideAuth.ts
- packages/nextjs/src/server/clerk.ts
- packages/nextjs/src/server/withClerkMiddleware.ts
- packages/remix/src/ssr/authenticateRequest.ts
- packages/remix/src/ssr/rootAuthLoader.ts
- packages/remix/src/ssr/types.ts
- packages/remix/src/ssr/utils.ts
Add proxyUrl prop and refactor verifyToken function so it can be called with the proxy url if it is present
> COR-51 fix(backend): Add proxyUrl prop

- packages/backend/src/tokens/authStatus.ts
- packages/backend/src/tokens/factory.ts
- packages/backend/src/tokens/interstitial.ts
- packages/backend/src/tokens/request.test.ts
- packages/backend/src/tokens/request.ts
- packages/clerk-js/src/core/clerk.ts
- packages/nextjs/src/server/clerk.ts
- packages/remix/src/ssr/authenticateRequest.ts
- packages/remix/src/ssr/types.ts
- packages/remix/src/ssr/utils.ts
How to use in a Remix app 
```typescript
export const loader: LoaderFunction = args => {
return rootAuthLoader(
args,
({ request }) => {....},
{ loadUser: true, isSatellite: true, domain: 'clerk.satellite.dev' },
);
};
```
and also 
```typescript
export default ClerkApp(App, {
isSatellite: true,
domain: 'clerk.satellite.dev',
});
```
⚠️ This is an experimental feature under active development
- You can use these properties and their values when this PR is merged
- You will receive type errors as `isSatellite` & `domain` are not available in types yet
> Include isSatellite and domain to interstitial and authenticateRequest

- packages/clerk-js/src/core/clerk.ts
- packages/clerk-js/src/core/constants.ts
- packages/clerk-js/src/utils/getClerkQueryParam.ts
FAPI now appends the `__clerk_synced` query string parameter as a result of syncing a satellite domain with its primary. 
There's no need to include it in the `redirect_url` parameter, but we still have to check its value to determine if a sync has completed.
Refactored the logic a bit so that each function does only one thing.
> FAPI determines if we're synced

- packages/shared/setupJest.ts
- packages/shared/src/utils/browser.test.ts
- packages/shared/src/utils/browser.ts
This PR adds the [Navigator API `onLine` property](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/onLine) when isValidBrowserOnline utility function is deciding if the network status of the user agent is online.
> Add an extra check for network status using the Navigator API `onLine` property

- packages/clerk-js/src/core/clerk.ts
- packages/nextjs/src/server/clerk.ts
- packages/nextjs/src/server/withClerkMiddleware.ts
- packages/remix/src/ssr/authenticateRequest.ts
- packages/remix/src/ssr/rootAuthLoader.ts
- packages/remix/src/ssr/types.ts
- packages/remix/src/ssr/utils.ts
- packages/types/src/clerk.ts
After this PR, you should be able to pass function that accepts a parameter of type `URL` and returns a boolean
```typescript
isSatellite={(url) => url.hostname !== 'exaple.com'}
```
We are also introducing the `CLERK_IS_SATELLITE` environment variable with expected values of `'true'` `'false'`
> Allow function to be passed in isSatellite prop

- packages/clerk-js/src/core/resources/Error.ts
- packages/clerk-js/src/core/services/authentication/AuthenticationService.ts
Updates the `toString` implementation of the ClerkAPIResponseError class to include more error details. 
Before:
After:
> fix(clerk-js): Include more error details when stringifying ClerkAPIResponseError

- packages/nextjs/src/server/types.ts
- packages/nextjs/src/server/utils.ts
- packages/nextjs/src/server/withClerkMiddleware.ts
This PR introduces the behaviour listed bellow
- isSatellite as function
```typescript
export default withClerkMiddleware((req) => {
return NextResponse.next()
}, {
isSatellite: (url) => {
return (url.hostname === "example.com")
}
});
```
- isSatellite as boolean
```typescript
export default withClerkMiddleware((req) => {
return NextResponse.next()
}, {
isSatellite: true
});
```
> Add isSatellite as option in withClerkMiddleware

- packages/clerk-js/src/core/clerk.ts
- packages/clerk-js/src/core/warnings.ts
- packages/clerk-js/src/ui/common/withRedirectToHome.tsx
- Replace console.warn with console.info
- Change the wording used to demonstrate better that these messages are only used for documentation purposes, and they are not actual warnings.
> fix(clerk-js): Display redirection warnings as info messages

- packages/nextjs/src/server/withClerkMiddleware.ts
- tsconfig.json
This param causes issues in esm module resolution
when an app in the monorepo does not have a dedicated `tsconfig.json` and there is a dependency with the same name as a packages/<package> module.
Eg fastify import in playground/fastify app
> chore(repo): Drop unused tsconfig baseUrl param

- packages/nextjs/src/client/index.tsx
- packages/remix/src/client/RemixClerkProvider.tsx
- packages/remix/src/client/types.ts
- packages/remix/src/ssr/utils.ts
This PR ensures that the  following env vars are used and passed correctly to ClerkProvider
- NextJS
- NEXT_PUBLIC_CLERK_PROXY_URL
- NEXT_PUBLIC_CLERK_IS_SATELLITE
- NEXT_PUBLIC_CLERK_DOMAIN
- Remix
- CLERK_PROXY_URL
- CLERK_IS_SATELLITE
- CLERK_DOMAIN
> Pass env var for multi-domain and proxy in NextJS and Remix

- packages/clerk-js/src/ui/components/CreateOrganization/CreateOrganizationPage.tsx
- packages/localizations/src/de-DE.ts
- packages/localizations/src/en-US.ts
- packages/localizations/src/fr-FR.ts
- packages/localizations/src/it-IT.ts
- packages/localizations/src/pt-BR.ts
- packages/types/src/localization.ts
The primary submit button inside <CreateOrganization /> was not localized and it was hard-coded as a string in English
Before this PR
After this PR
> fix(clerk-js,localizations,types): Localize submit button of <CreateOrganization/>

- packages/types/src/jwtv2.ts
…ject via CustomJwtSessionClaims
Introduce the `CustomJwtSessionClaims` globally defined interface to allow user-defined types for the auth.sessionClaims objects, similar to `PublicUserMetadata` etc.
To use, re-declare `CustomJwtSessionClaims` as shown:
```ts
declare global {
interface UserPublicMetadata {
showAds: boolean;
}
interface CustomJwtSessionClaims {
publicMetadata: UserPublicMetadata;
anotherProp: { hello: string };
}
}
```
Usage:
server-side:
client-side (public metadata example)
In the future, we might want to drop the `global` declaration and opt-in for a more explicit `declare module @clerk/types` instead - however, I expect that conflicts won't be common at all, and I prefer the DX of the global namespace.
My preferred way to go about it would be to bound the types with …
> feat(types): Support user defined types for auth.sessionClaims

- packages/react/src/isomorphicClerk.ts
This fix ensures that the stack trace is printed correctly across all frameworks and Expo.
> fix(clerk-react): Report error stack from IsomorphicClerk

- packages/backend/src/tokens/factory.ts
- packages/backend/src/tokens/interstitial.ts
- packages/nextjs/src/middleware/withServerSideAuth.ts
- packages/nextjs/src/server/withClerkMiddleware.ts
This PR will pass the correct params down to interstitial when it is loaded from BAPI
> COR-121: Include isSatellite, domain, proxy for remotePublicInterstitialUrl

- packages/sdk-node/examples/express/package-lock.json
- packages/sdk-node/examples/express/package.json
- packages/sdk-node/examples/node/package-lock.json
- packages/sdk-node/examples/node/package.json
- playground/cra-js/package.json
- playground/fastify/package.json
- playground/gatsby/package-lock.json
- playground/gatsby/package.json
- playground/nextjs/package-lock.json
- playground/nextjs/package.json
- playground/nextjs12/package.json
- playground/remix-cf-pages/package.json
- playground/remix-cf-worker/package.json
- playground/remix-node/package.json
After this change we should just use once `yalc add --pure {sdk} {sdk-dependency}` per playground app and always run `npm run build` in `packages/<pkg>` when changes are made, for the playground app to be updated.
Also after this change the `npm audit` in the repo is in sync with dependabot reported issues.
see: https://www.notion.so/clerkdev/Testing-changes-in-clerk-javascript-d21ad8ca16fe447a813f67b9f1f6b16e
> chore(repo): Fix playground apps using local packages and their deps

- packages/clerk-js/src/ui/elements/Avatar.tsx
Before (the color is inherited, so it may be inconsistent with the theme): 
After:
> fix(clerk-js): Set initials color to colorText

- packages/backend/src/tokens/interstitial.ts
- packages/clerk-js/src/core/clerk.ts
- packages/clerk-js/src/utils/getClerkQueryParam.ts
- packages/nextjs/src/server/withClerkMiddleware.ts
Further changes required to ensure that 
- remix and local interstitial  
- nextjs and BAPI interstitial 
have the same behaviour
> COR-121 Prevent infinite loop from interstitial in nextjs

- packages/clerk-js/src/ui/components/OrganizationProfile/OrganizationMembers.tsx
- packages/clerk-js/src/ui/components/SignUp/SignUpContinue.tsx
- packages/clerk-js/src/ui/elements/FormButtons.tsx
> chore(clerk-js): Drop unused imports

- packages/clerk-js/src/ui/components/UserProfile/RemoveResourcePage.tsx
- packages/clerk-js/src/ui/utils/fastDeepMerge.ts
When successfully deleting the resource, the properties of the object are overwritten by the response from FAPI. This seems to have been a "bug" for a long time, but was somehow working fine before React 18.
> fix(clerk-js): Fix undefined appearing after deleting a resource

- packages/remix/src/ssr/getAuth.ts
- packages/remix/src/ssr/index.ts
- packages/remix/src/ssr/rootAuthLoader.ts
- packages/remix/src/ssr/utils.ts
- playground/remix-node/app/root.tsx
Even though we can add the observability headers in the Response object of remix, they are not returned to the client response. 
To return them from the loader function the customers should explicitly add the headers from there `headers` function in the endpoint or from the root level (`root.tsx`) using the following lines of code (also used in playground/remix-node):
```
import { getClerkDebugHeaders } from '@clerk/remix/ssr.server';
export function headers({
actionHeaders,
loaderHeaders,
parentHeaders,
}: {
actionHeaders: Headers;
loaderHeaders: Headers;
parentHeaders: Headers;
}) {
return {
// other headers from parent or action
...getClerkDebugHeaders(loaderHeaders)
}
}
```
To help customers add those debugging headers i exposed a new function `getClerkDebugHeaders(headers: Headers)` …
> Chore(remix): Add observability headers in unknown and interstitial

- packages/backend/src/tokens/interstitial.ts
- packages/backend/src/util/parsePublishableKey.ts
- packages/nextjs/src/server/utils.ts
- packages/nextjs/src/server/withClerkMiddleware.ts
- packages/react/src/utils/scriptLoader.ts
- packages/remix/src/errors.ts
- packages/remix/src/ssr/authenticateRequest.ts
- packages/shared/src/utils/keys.ts
- packages/shared/src/utils/proxy.ts
- Uses proxyUrl as src of clerk script
- Validates for absoluteUrl proxyUrl and throws error in Remix & nextjs
> COR-136 Use proxyUrl for as src for script

- packages/nextjs/src/server/utils.ts
- packages/shared/src/utils/proxy.test.ts
- packages/shared/src/utils/proxy.ts
- [] 🐛 Bug fix
This PR adds tests for `isHttpOrHttps` utility
and  isHttpOrHttps now uses regex instead of .startsWith()
> fix(shared,nextjs): Tests for `isHttpOrHttps` utility

- packages/expo/README.md
This PR updates the README file of the Expo package, adding a try/catch block when using SecureStore methods because, on Android, they happen to fail sometimes. ([See here](https://github.com/expo/expo/issues/19018) for more)
> chore(clerk-expo): Add try/catch blocks in SecureStore code snippet

- packages/backend/package.json
The edge-light runtime key was recently added as a condition name for the edge runtime in this PR: https://github.com/vercel/next.js/pull/45188
However, this PR also introduced a change (which might not be intentional): the `node` runtime key is now a valid condition key for the edge runtime, so it matches before our `default` import.
This PR adds the `edge-light` key before `node` so that we guarantee that the correct imports will always be used.
> fix(backend): Support the Vercel edge-light runtime key

- packages/clerk-js/src/ui/elements/UserPreview.tsx
When the text is too long, truncate only the identifier and still show the badge if provided.
Before: 
After:
> fix(clerk-js): Do not truncate badge in UserPreview

- package.json
- playground/fastify/README.md
- playground/fastify/package-lock.json
- playground/fastify/src/loadEnv.ts
- playground/fastify/src/routes/private.ts
- playground/fastify/src/server.ts
The most interesting part in this PR is the `playground/fastify/README.md` which indicates a way to use yalc to link packages and playground apps.
> Chore(repo): Fix fastify playground and yalc

- packages/clerk-js/src/ui/components/OrganizationProfile/InviteMembersForm.tsx
> fix(clerk-js): Prevent errorText from leaking into React elements

- packages/backend/package.json
Similar to: https://github.com/clerkinc/javascript/pull/841
> fix(backend): Support the `browser` and `worker` runtime keys

- packages/localizations/src/es-ES.ts
- packages/localizations/src/index.ts
- [x ] `npm test` runs as expected.
Adding Spanish (Spain) localization :)
> feat(localizations): Add spanish localization

- packages/clerk-js/src/core/resources/SignUp.ts
- packages/types/src/signUp.ts
Unsafe metadata can be set by developers using authenticateWithWeb3 and authenticateWithRedirect custom flows.
Unsafe metadata can be set by developers using authenticateWithWeb3 and authenticateWithRedirect custom flows.
> fix(clerk-js): Pass unsafe metadata to sign up methods

- packages/backend/src/tokens/interstitial.ts
- packages/clerk-js/src/core/clerk.ts
- packages/nextjs/src/server/withClerkMiddleware.ts
- packages/remix/src/ssr/utils.ts
This is an attempt to be less aggressive when syncing with primary. We should let interstitial decide if the app should sync/link and not run this process on every page refresh
Before this PR 
After this PR 
Before this PR
After this PR
> fix(clerk-js,backend): Only interstitial will dictate sync/link

- packages/backend/src/tokens/authStatus.ts
The missing secretKey was causing the following error:
```
Missing Clerk Secret Key or API Key. Go to https://dashboard.clerk.dev ...
```
Since the backendApi created to be used in getToken when template was provided did not have in scope the secretKey.
Fixes https://github.com/clerkinc/javascript/issues/850
> fix(backend): Fix missing secretKey from signedInAuthObject

- packages/nextjs/src/middleware/withServerSideAuth.ts
- packages/nextjs/src/server/withClerkMiddleware.ts
Encoding error caused by non latin1 (ISO-8859-1) value in headers:
Cannot convert argument to a ByteString because the character atindex {} has a value of {} which is
greater than 255.
https://github.com/clerkinc/javascript/issues/840
> fix(nextjs): Encode debug headers to avoid encoding issues

- packages/remix/src/ssr/utils.ts
This PR adds the following to `request.auth`:
- sessionClaims: JwtPayload;
- orgId: string | undefined;
- orgRole: string | undefined;
- orgSlug: string | undefined;
- organization: Organization | undefined;
- debug: AuthObjectDebug;
Fixes https://github.com/clerkinc/javascript/issues/826
> fix(remix): Align request.auth object (add sessionClaims)

- packages/remix/src/client/RemixClerkProvider.tsx
Remix hydration errors should not stop Clerk navigation from working, as the components mount only afterhydration is done (in the case of a hydration error, the components will simply mount after client-side hydration)In the case of a hydration error, the first `navigate` function we get from the `useNavigate` hook will not workbecause the RemixClerkProvider (which is part of the host app) will unmount before the following useEffect within `navigate` fires:https://github.com/remix-run/react-router/blob/main/packages/react-router/lib/hooks.tsx#L175so isomorphicClerk will initialise with a `navigate` function that will never have `activeRef.current` set to true.This variable is just an object ref/cache outside the React rendering cycle that holds a reference to thelatest `navigate` …
> fix(remix): Always use the latest useAwaitableNavigate reference

- packages/nextjs/src/middleware/withServerSideAuth.ts
- packages/nextjs/src/server/clerk.ts
- packages/nextjs/src/server/withClerkMiddleware.ts
We can use CLERK_JS_VERSION to populate pkgVersion when `remotePublicInterstitialUrl` is called and middleware returns the interstitial
Currently we do not offer a way for passing a value set by the developers as `pkgVersion` when [remotePublicInterstitialUrl](https://github.com/clerkinc/javascript/blob/1d1b937318c427abcf559341bb39c044f1070e24/packages/nextjs/src/server/withClerkMiddleware.ts#L91) is called.
Using the env variable CLERK_JS_VERSION, the developers can solve the problem mentioned above.
That way they can control the version of clerk-js that will be used as the `src` when loading clerk-js from the BAPI interstitial
> fix(nextjs): Introduce CLERK_JS_VERSION env

- packages/clerk-js/src/core/clerk.redirects.test.ts
- packages/clerk-js/src/core/clerk.test.ts
- packages/clerk-js/src/core/services/authentication/AuthenticationService.ts
Add environment option in `AuthenticatedServices`. 
This also fixes the issue of client uat cookie being set twice for proxied apps
> COR-159 fix(clerk-js): Add environment option

- packages/clerk-js/src/core/clerk.redirects.test.ts
- packages/clerk-js/src/core/clerk.test.ts
- packages/clerk-js/src/core/resources/Environment.ts
- packages/clerk-js/src/core/services/authentication/AuthenticationService.ts
- packages/types/src/environment.ts
Environment should exist and not be production to prevent setting `__client_uat` with value of 0
> Only set client uat cookie for dev instances when environment is defined

- packages/localizations/src/fr-FR.ts
> fix(clerk-js,localizations): Correct French syntax error

- packages/backend/src/tokens/factory.ts
- packages/backend/src/tokens/interstitialRule.ts
- packages/backend/src/tokens/request.test.ts
- packages/backend/src/tokens/request.ts
- packages/nextjs/src/server/withClerkMiddleware.ts
- packages/remix/src/ssr/authenticateRequest.ts
This is a necessary step in order to hide the logic of we handle the sync with primary process from the end users.
> COR-164 Accept the search params of request in `authenticateRequest`

- packages/backend/src/tokens/interstitial.ts
- packages/backend/src/tokens/request.ts
- packages/clerk-js/src/core/clerk.ts
- packages/nextjs/src/server/withClerkMiddleware.ts
- packages/react/src/utils/scriptLoader.ts
- packages/shared/src/utils/url.test.ts
- packages/shared/src/utils/url.ts
This PR supports an actual domain to be passed for a satellite and and not FAPI. 
Before: `CLERK_DOMAIN=clerk.satellite.dev`
After: `CLERK_DOMAIN=satellite.dev`
This changes applies for the environment variable, props, and options for wrapper functions.
We continue to pass around the domain value without the prefix and we add it when it is needed(clerk-js & clerk-react)
It will be used when constructing the src url of for clerk-js script and inside Clerk class by clerk-js
We also send the domain to BAPI without the prefix and the endpoint will handle the rest.
While this solution may not seem ideal, because we need to construct the correct url each time we want to use it, the other approach of constructing the url at top level creates more issues than it solves. Happy to talk more about …
> Expect actual satellite domain and not FAPI

- packages/backend/src/tokens/interstitial.ts
- packages/shared/src/utils/url.test.ts
- packages/shared/src/utils/url.ts
The previous regex was also matching anything that ended with the top level domain `.dev`, and this behaviour is not correct
> fix(backend,shared): Updated tests for addClerkPrefix

- package.json
- scripts/nuke.sh
> chore(repo): Remove turbo cache and reset playground yalc with nuke command

- packages/expo/src/ClerkProvider.tsx
- packages/react/src/isomorphicClerk.ts
- packages/types/src/multiDomain.ts
Otherwise, TS will complain if `domain` or `proxyUrl` is missing for  apps not using the multi domain feature.
> fix(types): Make DomainOrProxyUrl optional

- packages/clerk-js/package.json
- packages/clerk-js/webpack.config.js
clerk-js depends on clerk/shared that currently, imports React.
As a result, we cannot mark React as an external dep unless we refactor the imports. Let's revisit this after the bundle-size changes are merged.
In this PR we also introduce `npm run dev:headless` for easier local testing and we also aligned the build config for prod and dev so the bundles used for local testing match the prod builds more closely.
> fix(clerk-js): Temporarily do not mark react as an external dep

- packages/clerk-js/src/core/resources/Organization.ts
- packages/clerk-js/src/core/resources/OrganizationMembership.ts
- packages/clerk-js/src/core/resources/__snapshots__/Organization.test.ts.snap
- packages/clerk-js/src/core/resources/__snapshots__/OrganizationMembership.test.ts.snap
- packages/types/src/deletedObject.ts
- packages/types/src/externalAccount.ts
- packages/types/src/identificationLink.ts
- packages/types/src/organization.ts
- packages/types/src/organizationInvitation.ts
- packages/types/src/organizationMembership.ts
- packages/types/src/verification.ts
This PR implements the `reload` method for **OrganizationResource** and **OrganizationMembershipResource**, as it is needed for reloading the resource when `publicMetadata` gets updated.
We also update all resource types to extend the `ClerkResource`.
> [JS-167] Implement the `reload` method for Organization and OrganizationMembership

- packages/nextjs/src/app-beta/currentUser.ts
`currentUser` should always return a promise, otherwise its signature would change depending on whether the user is signed in or not. 
Explanation:
`auth` is a sync method, and since we check `userId` before returning a `Promise`, `currentUser` would be sync when `userId` is `null` and async otherwise. 
This PR makes this method async and adds an explicit return type to avoid this issue in the future.
> fix(nextjs): Correct currentUser() return type

- packages/backend/src/api/endpoints/SessionApi.ts
Deploying to the edge (or `experimental-edge`) runtime on Vercel currently fails with a couple of cryptic errors, however the real cause of the issue is is a "Must call super constructor in derived class before accessing 'this' or returning from derived constructor" error we get from within the `@clerk/backend` package.
I've found out that the SessionApi class has a couple of methods defined as class properties (arrow functions defined as class properties rather than class methods).
With out current settings, (target ES2020) the build results in the following code:
```tsx
var SessionAPI = class extends AbstractAPI {
constructor() {
super(...arguments);
this.getSessionList = async (queryParams) => this.request({
method: "GET",
path: basePath9,
queryParams
});
this.getSession = async …
```
> fix(backend): Convert all methods of SessionApi to class methods

- packages/clerk-js/src/ui/elements/Navbar.tsx
Seems like we're hitting some kind of conflict with the scrolling from floating-ui here when focus is returned. Found no way to turn it off, but a small timeout seems to fix the issue.
> fix(clerk-js): Fix UserProfile section scroll in mobile view

- packages/clerk-js/src/ui/localization/__tests__/makeLocalizable.test.tsx
- packages/clerk-js/src/ui/localization/makeLocalizable.tsx
- packages/clerk-js/src/ui/utils/test/createFixtures.tsx
- packages/localizations/src/de-DE.ts
- packages/localizations/src/en-US.ts
- packages/localizations/src/es-ES.ts
- packages/localizations/src/fr-FR.ts
- packages/localizations/src/it-IT.ts
- packages/localizations/src/pt-BR.ts
- packages/types/src/localization.ts
The field-related FAPI errors include a `meta.paramName` prop we can append to the keys within unstable_errors in order to allow for more fine-grained translations.
This commit adds the necessary infra to support the above.
Usage:
```tsx
<ClerkProvider
localization={{
unstable__errors: {
form_identifier_exists: 'Το πεδίο υπάρχει ήδη',
form_identifier_exists__username: 'Το όνομα χρήστη υπάρχει ηδη',
},
}}
```
Example:
> Add dynamic localization keys in unstable_errors

- packages/react/src/types.ts
- packages/types/src/multiDomain.ts
This is an attempt to improve typesafety for the props that were introduced for the proxy and multi-domain features
Before someone was allowed to have the following config 
```jsx
<ClerkProvider domain={'satellite.dev'} />
```
This is perfectly valid, but a user should use this in combination with `isSatellite` prop in order to ensure the the mutl-domain feature in a satellite application will work.
After this PR the above code will result in a type error which is a hint for the developers that they've missed a prop.
Here's a list of configuration someone is allowed to use related to types
- NONE of them (regular app)
```jsx
<ClerkProvider />
```
- proxyUrl (primary app)
```jsx
<ClerkProvider proxyUrl={'/__clerk'} />
```
- proxyUrl  + isSatellite (satellite app)
```jsx
<ClerkProvider …
```
> COR-189 Include isSatellite in DomainOrProxyUrl

- packages/clerk-js/src/core/resources/ExternalAccount.test.ts
- packages/clerk-js/src/core/resources/ExternalAccount.ts
- packages/clerk-js/src/ui/components/UserProfile/ConnectedAccountsSection.tsx
- packages/localizations/src/en-US.ts
- packages/types/src/clerk.ts
- packages/types/src/externalAccount.ts
- packages/types/src/localization.ts
Enables users to be able to pass during runtime, additional scopes for each OAuth provider in the UserProfile component. This can be useful in the scenario where a user has already connected an account, and the application requires more scopes for its functionality.
In this case, the component will understand that more scopes are required and will prompt the user to reauthorize their account to grand all the new necessary scopes.
The underlaying implementation is using the new clerk.js `externalAccount.reauthorize()` method
> Ability to define additional OAuth scopes in UserProfile & reauthorize existing account

- packages/clerk-js/src/ui/components/UserProfile/ConnectedAccountsPage.tsx
- packages/clerk-js/src/ui/components/UserProfile/__tests__/ConnectedAccountsPage.test.tsx
While connecting an external account via the UserProfile, we take into account if additional scopes have been provided for this provider. If yes, pass them along so the user will approve those as well
> feat(clerk-js): Pass additional OAuth scopes while connecting an extenal account in UserProfile

- packages/types/src/session.ts
Adds the missing lastActiveAt property in SessionResource
> fix(types): Add the `lastActiveAt` property in SessionResource

- packages/clerk-js/src/ui/components/SignIn/__tests__/SignInAccountSwitcher.test.tsx
- packages/clerk-js/src/ui/components/UserButton/__tests__/UserButton.test.tsx
Nothing major, just a tiny "cleanup" - I just confirmed that initializing the config function within the describe block is safe. However, I did move it outside of the block just so we're aligned with other similar tests files.
> test(clerk-js): Move initConfig block out of describe block

- packages/clerk-js/src/ui/elements/ApplicationLogo.tsx
Clicking the application logo (if found) will navigate the browser to `displayConfig.logoUrl`.
This was a customer request.
> feat(clerk-js): Navigate to homeUrl when clicking the application logo

- packages/clerk-js/src/core/fapiClient.ts
- packages/clerk-js/src/core/resources/Base.ts
- packages/clerk-js/src/core/resources/Environment.ts
- packages/clerk-js/src/ui/components/SignUp/SignUpForm.tsx
- packages/clerk-js/src/ui/components/UserProfile/PhonePage.tsx
- packages/clerk-js/src/ui/elements/FormControl.tsx
- packages/clerk-js/src/ui/elements/PhoneInput/PhoneInput.tsx
- packages/clerk-js/src/ui/elements/PhoneInput/useFormattedPhoneNumber.ts
- packages/clerk-js/src/ui/utils/test/fixtures.ts
- packages/types/src/environment.ts
- packages/types/src/json.ts
Read the country code from FAPI response and make it the default value. This is a change that will only affect newcomers.
> COR-152 fix(clerk-js): Read country code from FAPI response

- packages/nextjs/src/server/getAuth.ts
- packages/nextjs/src/server/utils.ts
- packages/nextjs/src/server/withClerkMiddleware.ts
- playground/nextjs/middleware.ts
- playground/nextjs/pages/api/hello.ts
Pass `authMessage` and `authReason` from middleware to the routes by adding them in headers or query params (same approach as `authReason`).
> chore: Fix nextjs debug in route files

- packages/clerk-js/src/core/fapiClient.test.ts
- packages/clerk-js/src/core/fapiClient.ts
This issue was introduced by the commit that added meta in response payload and is caused by the destructuring of the array json response which converts the array response payload to object.
Issue:
> fix(clerk-js): Fix infinite loading of active devices in user profile

- packages/types/src/factors.ts
We enhance the sign in supported first factors property, with a new field 'primary', which denotes if the corresponding identification is the user's primary
> feat(types): Expose in sign in factor if identification is user's primary

- packages/clerk-js/src/ui/components/SignUp/SignUpStart.tsx
- packages/clerk-js/src/ui/components/SignUp/__tests__/SignUpStart.test.tsx
Preserve the sign up fields in SignUpStart by setting their `initialState` from the `sua` value returned from FAPI.
> feat(clerk-js): Preserve sign up fields upon return to SignUpStart

- packages/clerk-js/src/ui/Components.tsx
- packages/clerk-js/src/ui/components/UserButton/useMultisessionActions.tsx
- packages/clerk-js/src/ui/components/UserProfile/ConnectedAccountsSection.tsx
- packages/types/src/clerk.ts
- packages/types/src/externalAccount.ts
- packages/types/src/oauth.ts
- packages/types/src/user.ts
As we allow users to pass any additional OAuth scopes to the <UserProfile /> component, we now allow users to define the same prop in the <UserButton /> component as well.
> Add the ability to pass additionalOAuthScopes prop to <UserButton />

- packages/nextjs/src/server/getAuth.ts
Return signed-out auth object in `buildClerkProps` instead of empty object to avoid loading state in SSR.
https://github.com/clerkinc/javascript/issues/889
> fix(nextjs): Return signedOut state in buildClerkProps #889

- packages/clerk-js/src/ui/components/UserProfile/RemoveResourcePage.tsx
- packages/clerk-js/src/ui/utils/fastDeepMerge.ts
This seems to happen as a result of this line https://github.com/clerkinc/javascript/blob/c85ca2c7a81298821100c7ca2467bc25ef074995/packages/clerk-js/src/ui/utils/fastDeepMerge.ts#L17
when the email is associated with an external account. We try to call the constructor for the `linkedTo` field which corresponds to an `IdentificationLink` and it fails. I suppose this function was not supposed to be a general utility and is probably best fitted for our theme utilities? @nikosdouvlis  Let me know on that. I'll make another simpler deepMerge utility for this case.
> fix(clerk-js): Fix error when removing an email linked to an external account

- packages/clerk-js/src/ui/elements/Card.tsx
- packages/clerk-js/src/ui/elements/InputWithIcon.tsx
- packages/clerk-js/src/ui/elements/Modal.tsx
- packages/shared/src/hooks/createContextAndHook.ts
* Add a new `ModalContext` that contains information about the most recent modal opened. We can close the modal using the hook. 
* Place the close modal button inside the `BaseCard` and only show it if we can find the `ModalContext`. It toggles the modal upon click(retrieves the `toggle` function from the context).
> fix(clerk-js): Add margin for clerk tag and refactor the modal close button

- package-lock.json
- packages/backend/package.json
Miniflare is used as a dev dependency to run the tests. If the tests pass, then i believe we are okay to merge this.
> chore(repo): Update miniflare@2.12.1 to resolve sec vulnerabilities

- packages/clerk-js/src/core/resources/OrganizationInvitation.ts
- packages/types/src/clerk.ts
- packages/types/src/organization.ts
This commit removes removes the unused `redirectUrl` property from the organization member invitation.
This property is supported when creating organization invitations from BAPI, but not from FAPI.
Unfortunately, they were accidentally added in our FE types and should be removed because they cause confusion, given that the FAPI will return an error if someone tries to use them.
> fix(clerk-js): Removed unsupported props when inviting org members

- packages/clerk-js/src/index.browser.ts
- packages/clerk-js/src/index.ts
- packages/clerk-js/src/utils/setWebpackChunkPublicPath.ts
A combination of setting a fixed __PKG_VERSION__ during build time and the runtime __webpack_public_path__ config option (https://webpack.js.org/guides/public-path/). We explicitly set the public path in order to account for all chunk caching scenarios. A specific version of clerk.browser.js file should always try to load its corresponding chunk versions, otherwise we risk hitting caching issues.
Scenario:
1. We release clerk-js@1.0.0 containing: clerk.browser.js, chunkA-1.0.0.js, chunkB-1.0.0.js
2. A user opens an app using Clerk
3. The browser downloads and caches `/npm/@clerk/clerk-js@latest/dist/clerk.browser.js`
4. chunkA is needed so the browser downloads and caches `/npm/@clerk/clerk-js@latest/dist/chunkA-1.0.0.js`
5. Meanwhile, we release clerk-js@1.2.0 containing: …
> fix(clerk-js): Load chunks using __PKG_VERSION__ defined during build time

- packages/sdk-node/src/authenticateRequest.ts
- [-] `npm test` runs as expected.
Related issue: https://github.com/clerkinc/javascript/issues/953
Related PR: https://github.com/clerkinc/javascript/pull/851
> fix(clerk-sdk-node): Encode debug headers to avoid Node app crash

- package-lock.json
- packages/remix/package.json
Locally, the package exists in the root node_modules dir
When installed, the package gets installed as a dependency of clerk/clerk-react. However, it should be listed explicitly as a dependency
> chore(remix): List @clerk/shared as a dependency

- packages/clerk-js/src/core/resources/Environment.ts
- packages/clerk-js/src/ui/components/SignUp/__tests__/SignUpStart.test.tsx
- packages/clerk-js/src/ui/elements/PhoneInput/PhoneInput.tsx
- packages/clerk-js/src/ui/elements/PhoneInput/__tests__/useFormattedPhoneNumber.test.ts
- packages/clerk-js/src/ui/elements/PhoneInput/countryCodeData.ts
- packages/clerk-js/src/ui/elements/PhoneInput/useFormattedPhoneNumber.ts
- packages/clerk-js/src/ui/utils/__tests__/phoneUtils.test.ts
- packages/clerk-js/src/ui/utils/formatSafeIdentifier.test.ts
- packages/clerk-js/src/ui/utils/formatSafeIdentifier.ts
- packages/clerk-js/src/ui/utils/phoneUtils.ts
- packages/types/src/environment.ts
Refactors the phone utils to make phone parsing more accurate.
This PR also improves PhoneInput component  as it now correctly handles more user input events.
In general, the input now respects this priority order:
- "us" as a default fallback, or
- country iso from the header, or
- country iso from localstorage, or
- country iso from the previous signup.phoneNumber value, or
- country iso from the paste event, or
- country iso after the user explicitly picked a country using the picker (this is persisted locally)
Fixes JS-276
Fixes JS-275
> Improve phone input parsing

- packages/react/src/isomorphicClerk.ts
This change makes clerk/clerk-react compatible with both clerk-js@3 and clerk-js@4 in regards to loading in standards browser. This allows the accounts project to load any of these 2 versions on a per-request basis, even if the latest clerk/clerk-react package is installed
> fix(clerk-react): Fallback to Clerk.isReady if Clerk.loaded is not available

- packages/clerk-js/src/ui/elements/CodeControl.tsx
This change fixes a UX issue.
The issue is that Safari on iOS won't let you programmatically focus an input field if no user interaction has happened first. So the user has to focus on the input area by tapping, and the bad part is that they have to aim for the first digit, or else the autofill from the messages starts filling from the digit they focused on.
With this change, we focus on the first digit the first time the user clicks/taps on any of the digit inputs. This way, the autofill works smoothly, and even if they don't use the autofill, they will start typing from the first digit.
> fix(clerk-js): Focus on the first digit the first time user clicks on Phone code input

- packages/react/jest.config.js
- packages/react/src/hooks/useAuth.ts
- packages/react/src/hooks/utils.ts
- packages/react/src/isomorphicClerk.ts
Memoize the values of useAuth getToken and signOut
Closes #201
Closes #455
> fix(clerk-react): Memoize useAuth.getToken and useAuth.signOut

- packages/clerk-js/src/core/clerk.ts
Currently the check in handleRedirectCallback for isReady because instead of checking for the value via this.#isReady or this.isReady(), we were checking that !this.isReady which will always be false since the this.isReady is a method and it will always exist.
> fix(clerk-js): Fix typo of private #isReady method in handleRedirectCallback

- packages/backend/src/tokens/interstitial.ts
- packages/backend/src/util/isDevOrStagingUrl.ts
- packages/clerk-js/src/core/clerk.ts
- packages/clerk-js/src/core/fapiClient.ts
- packages/clerk-js/src/utils/__tests__/url.test.ts
- packages/clerk-js/src/utils/url.ts
- packages/nextjs/src/server/withClerkMiddleware.ts
- packages/react/src/isomorphicClerk.ts
- packages/react/src/utils/isDevOrStageUrl.tsx
- packages/react/src/utils/scriptLoader.ts
- packages/remix/src/errors.ts
- packages/remix/src/ssr/authenticateRequest.ts
- packages/shared/src/utils/keys.test.ts
- packages/shared/src/utils/keys.ts
- packages/types/src/clerk.ts
- packages/types/src/multiDomain.ts
This PR tackles:
- changes to fapiClient when domain is used in dev instances
- constructing clerk.js script url when domain is used in dev instances (affects the react package and interstitial)
- Clerk.js throws an error if isSatellite is set without proxyUrl or domain. (for both prod and dev instances)
- withClerkMiddleware and rootAuthLoader  throw the same error mentioned in the previous line
In order to complete the above items some refactor was needed:
- `isDevOrStagingUrl` utility function  was moved from `clerk-js` to `shared`
- fixed types for Clerk.js Singleton (domain, isSatellite)
> Append `__domain` query param to FAPI requests for satellite apps with dev instances

- packages/clerk-js/src/ui/components/SignUp/SignUpContinue.tsx
Clerk offers a progressive sign up flow, which means that using an OAuth provider to sign up, users will be able to fill any required and missing fields, such as name, username, in order to complete the flow. There was a bug in our components, where an instance had only Social Connection enabled as first factor, method to sign in, and required other fields (first/last name) which are not used for sign in of course. If a user tried to sign up with an OAuth provider, which doesn't provide these info (first/last name), the sign up wasn't completed but a user end up in blank screen without a chance to fill the missing fields. This was because we were rendering the form conditionally, based in the instance auth factor settings, which were not applicable in this case …
> fix(clerk-js): Don't take into account auth instance settings in SignUpContinue form

- packages/clerk-js/src/index.ts
- packages/clerk-js/webpack.config.js
Lazily-loading chunks is mostly inteded to be used in a browser environment from the host app OR used with a true UMD bundle that will be loaded and executed as a standalone lib in the browser's global namespace.
We've found that in most webpack configurations, a chunked bundle cannot go through another bundling process again unless the host bundler config accounts for that use case explicitly. For example, importing Clerk from `@clerk/clerk-js` within a React app generated using CRA will fail as the default CRA webpack config cannot parse and bundle the lazy chunks and the app will fail during runtime with a ChunkLoadError.
This PR adjust our webpack config accordingly to account for the above issues. The clerk.js bundle includes all the dependencies, while clerk.browser.js is split …
> fix(clerk-js): Eagerly include the dynamic chunks for the clerk.js entry

- packages/nextjs/src/client/index.tsx
> fix(nextjs): Pass value of NEXT_PUBLIC_CLERK_SIGN_IN_URL in CSR

- packages/clerk-js/src/core/clerk.ts
This probably got removed during a rebase when resolving conflicts.
> fix(clerk-js): Bring back error for missing proxyUrlAndDomain

- packages/clerk-js/src/core/resources/User.test.ts
- packages/clerk-js/src/core/resources/User.ts
The updated endpoint for changing a user's password is `POST /v1/me/password/change`.
> fix(clerk-js): Change update user password URL

- packages/clerk-js/src/ui/primitives/Image.tsx
As described in https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Embedder-Policy.
We also had to add the necessary CORS header in the image proxy: https://github.com/clerkinc/cloudflare-workers/pull/2
> feat(clerk-js): Support COEP for image resources

- packages/react/src/isomorphicClerk.ts
- packages/react/src/utils/inClientSide.ts
- packages/react/src/utils/index.ts
- packages/shared/src/utils/ssr.ts
This change resolve issues with react Native where `window` is defined but the API is not the same with the Browser resulting in failures when trying to use window.location or any other property.
- Drop `inClientSide()` from `react/utils` in favour of `shared` package implementation
- Fix `inClientSide()` in `shared` to check for `document` instead of `window`
issue: https://github.com/clerkinc/javascript/issues/998
> fix(clerk-react,shared): Update inClientSide() util to check for document

- packages/backend/src/exports.test.ts
- packages/backend/tests/suites.ts
- [] 📖 Refactoring / dependency upgrade / documentation
> fix(backend): Add exports test to validate package API

- packages/chrome-extension/package.json
> fix(chrome-extension): Build before publish & add some other scripts

- packages/clerk-js/src/ui/hooks/useClerkModalStateParams.tsx
It seems that `useRef` was causing issues with the `urlStateParams` so it was replaced with `useState` which resolves the problem
> fix(clerk-js): Replace useRef with useState

- package-lock.json
- packages/nextjs/package.json
- packages/nextjs/tsconfig.json
- packages/nextjs/tsup.config.ts
- playground/nextjs12/app/app-dir/page.tsx
> chore(nextjs): Use tsup to bundle and minify package

- packages/backend/src/api/endpoints/OrganizationApi.ts
Adds missing API types.
Fixes #1023
> fix: add missing organization query param types

- packages/chrome-extension/README.md
> chore(chrome-extension): Add more instructions for FAPI URL on the README

- packages/clerk-js/src/ui/elements/FormControl.tsx
> fix(clerk-js): Slug icon breaks layout spacing due to its margin

- packages/clerk-js/src/ui/elements/PasswordInput.tsx
Increase right padding of Password inputs to avoid overlapping with the icons or buttons of password manager extensions
> COR-269: Avoid overlapping with password manager icons

- packages/clerk-js/src/ui/components/SignIn/SignInStart.tsx
> fix(clerk-js): Hide instant password field when it's autofilled and is emptied

- packages/localizations/src/de-DE.ts
- packages/localizations/src/index.ts
Seems like deDe is wrong, it should be deDE to stay consistent with all the other keys.
> deDe should be deDE instead

- packages/clerk-js/src/ui/components/OrganizationProfile/OrganizationProfileRoutes.tsx
- packages/clerk-js/src/ui/elements/NavigateToFlowStartButton.tsx
- packages/clerk-js/src/ui/router/Route.tsx
- packages/clerk-js/src/utils/url.ts
- packages/shared/src/utils/url.ts
We also need to replace the `basePath` when generating the `flowStartPath` since it will be appended by `navigateToFlowStart`. This was an issue for path routing since that's when the `basePath` was actually populated.
> fix(clerk-js): Replace the basePath for flowStartPath to work in path routing

- packages/clerk-js/src/ui/components/SignIn/SignInFactorOneCodeForm.tsx
- packages/clerk-js/src/ui/elements/VerificationCodeCard.tsx
+ Conditionally displaying alternative methods. We continue to display them by default
NOTE: This PR does not remove the previous UI, it only expands the customisation of `<VerificationCodeCard />`
> feat(clerk-js): Add back button to VerificationCodeCard

- packages/clerk-js/src/ui/components/SignIn/SignInStart.tsx
It seems that some times (it's inconsistent), the browser will autofill the field in SignInStart after the user has chosen to switch the identifier. If the autofilled value is a phone number, the user will be unable to switch to "email or username", since the component will detect the "+" value and automatically switch to the phone input once again. This commit makes it so the auto-switch can only happen the first time. We might be able to solve this in the future by changing the id of the input depending on the type, but that may cause more problems than it solves.
> fix(clerk-js): Prevent a switch loop when browser autofills again after switching

- packages/clerk-js/src/ui/elements/OrganizationAvatar.tsx
- packages/clerk-js/src/ui/elements/UserAvatar.tsx
> fix(clerk-js): Ignore imageUrl in UserAvatar and OrganizationAvatar

- packages/clerk-js/src/core/resources/SignIn.ts
- packages/clerk-js/src/core/resources/SignUp.ts
Pass the dev browser JWT during OAuth sign-in/sign-up and transfer flows as  redirectUrl parameter and ensure that all the steps are executed as part of the same dev browser.
Resolves AUTH-335 and AUTH-416.
> fix(clerk-js): Preserve the dev browser JWT during OAuth

- packages/clerk-js/src/utils/__tests__/url.test.ts
- packages/clerk-js/src/utils/url.ts
> fix(clerk-js): Avoid merging twice in mergeFragmentUrl

- packages/clerk-js/src/ui/components/UserProfile/PasswordPage.tsx
- packages/clerk-js/src/ui/elements/FormControl.tsx
- packages/clerk-js/src/ui/utils/useFormControl.ts
https://user-images.githubusercontent.com/19269911/231273142-ab6abed3-4f56-480d-aa34-a604078e7b3b.mov
https://user-images.githubusercontent.com/19269911/231272976-7579a731-b483-4eae-8f15-eba8c57a1e91.mov
This ensures that we don't break other input fields that where using the previous behaviour
> fix(clerk-js): Treat displaying errors onBlur as opt-in option

- packages/backend/src/api/resources/index.ts
I noticed that I can't import WebhookEvent type from the `@clerk/backend` package and I tracked it down to this missing export in resources.
> Add missing Webhooks export

- packages/clerk-js/src/utils/__tests__/devbrowser.test.ts
- packages/clerk-js/src/utils/devBrowser.ts
That way we will avoid appending it twice for OAuth provider flows were a redirectUrl is passed in but it already includes a db jwt.
In most cases, the redirectUrl will be provided by the user so if a db jwt does not exist, we do need to append it.
However, flows that append a redirectUrl before the mounting of the components (eg, using one of our redirect helpers like RedirectToSignIn) do no need the extra db jwt appended, as the components will already decorate the URL in ClerkUIComponents
Tested with a brand new nextjs + clerk app, using:
```
import '@/styles/globals.css';
import {ClerkProvider, RedirectToSignIn, SignedIn, SignedOut, UserButton} from '@clerk/nextjs';
import type { AppProps } from 'next/app';
export default function App({ Component, pageProps }: AppProps) {
return ( …
```
> fix(clerk-js): Do not append __clerk_db_jwt if it already exists

- packages/expo/src/useOAuth.ts
Allow users to pass redirectUrl and unsafeMetadata to startOAuthFlow.
> fix(clerk-expo): Improve useOAuth DX

- packages/backend/src/api/resources/Enums.ts
- packages/backend/src/api/resources/JSON.ts
- packages/clerk-js/src/core/resources/DisplayConfig.ts
- packages/clerk-js/src/ui/utils/test/fixtures.ts
- packages/types/src/displayConfig.ts
We have recently deprecated some fields from the sign, sign up and display config responses as they were part of an older API schema. This commit removes them from the types as well, as it's no longer used to keep them clean.
Display Config
- backend_host
Sign In
- allowed_identifier_types
- allowed_factor_one_strategies
- factor_one_verification
- factor_two_verification
Sign Up
- identification_requirements
- email_address_verification
- phone_number_verification
- external_account_strategy
- external_account_verification
> Remove deprecated fields from Sign In, Sing Up, Display Config resources & types

- packages/clerk-js/src/ui/components/SignIn/__tests__/SignInFactorTwo.test.tsx
> fix(clerk-js): Remove leftover .only from MFA tests

- packages/clerk-js/src/ui/elements/Form.tsx
- packages/clerk-js/src/ui/elements/FormControl.tsx
This is introduced due to enableErrorAfterBlur option from useFormControl that will delay an error message from being displayed until user moves clicks away from the field at least once.
This was a necessary change I had to make, in order to support displaying error messages while typing a password, but for better UX to delay giving users feedback for the errors until they move away (only the first time).
In order to fix this, I introduced a flag that keeps track of whether the form was submitted  by pressing enter inside the field. If that's the case then I bypass that the logic above and directly display the error message.
> fix(clerk-js): Form errors not displayed when form submitted with enter

- packages/clerk-js/src/utils/__tests__/devbrowser.test.ts
- packages/clerk-js/src/utils/devBrowser.ts
Replacing state on every navigation during local development breaks routers that depend on the history API.
> fix(clerk-js): Do not replaceState if a db JWT is not found in the url

- .vscode/launch.json
- playground/nextjs/README.md
- playground/nextjs/package.json
- playground/nextjs12/README.md
- playground/nextjs12/package.json
- playground/remix-node/README.md
- playground/remix-node/package.json
Introduce debug command for VSCode for the `playground/nextjs12` application.
> chore(repo): Support debug for playground/nextjs12 in VSCode

- packages/clerk-js/src/core/clerk.ts
- packages/clerk-js/src/ui/contexts/ClerkUIComponentsContext.tsx
- packages/clerk-js/src/ui/contexts/utils.ts
- packages/clerk-js/src/utils/__tests__/devbrowser.test.ts
- packages/clerk-js/src/utils/devBrowser.ts
- packages/types/src/clerk.ts
URL based session synced dev instances don't set a cookie on FAPI. For OAuth2 IDP and future SSO flows, we get around this by appending the dev browser JWT as a query parameter instead of hash. This way, FAPI can retrieve the dev browser jwt from the url and complete the sso flow.
> fix(clerk-js): Handle SSO flows in dev instances with URL based session syncing

- packages/nextjs/src/client/NextProviderContext.tsx
- packages/nextjs/src/client/index.tsx
If `signInUrl` or `signUpUrl` are set in the repo-level, we can default to path-based routing for the SignIn or SignUp components respectively.
This PR depends on #1098
> feat(clerk-js): Use path-based routing as default when repo-level paths exist

- packages/clerk-js/src/ui/contexts/ClerkUIComponentsContext.tsx
- packages/clerk-js/src/ui/contexts/utils.ts
- packages/clerk-js/src/utils/__tests__/url.test.ts
- packages/clerk-js/src/utils/url.ts
> fix(clerk-js): Add a dummy base when constructing the url in isRedirectForFAPIInitiatedFlow

- packages/clerk-js/src/ui/contexts/ClerkUIComponentsContext.tsx
Reasons for partially reverting commit d53432e:
- navigation inside SignInContext does not make any sense
- after navigating it should stop the execution flow since control passes to the navigated route
We will revert that change and come back to fix this after the release of `app-router` changes!
> fix(clerk-js): Partially revert commit d53432e

- packages/clerk-js/src/core/resources/UserSettings.test.ts
- packages/clerk-js/src/core/resources/UserSettings.ts
The setting for password maximum allowed length is 72.
> fix(clerk-js): Password settings maximum allowed length

- packages/nextjs/src/server/authMiddleware.ts
> chore(nextjs): Use redirectToSignIn in app-router auth middleware

- .github/workflows/ci.js.yml
Resolves the following deprecation warnings:
> chore(repo): Bump GH actions dependencies due to deprecation warning

- packages/nextjs/src/server/authMiddleware.test.ts
- packages/nextjs/src/server/authMiddleware.ts
> chore(nextjs): Add test coverage for app-router authMiddleware

- packages/clerk-js/src/ui/contexts/ClerkUIComponentsContext.tsx
This PR persists the session when the user is being redirected from the app to the accounts page. 
Uses `redirectWithAuth` in order to inject the session JWT into the URL and the accounts app to pick it up.
https://user-images.githubusercontent.com/19269911/235620593-7fb7521c-87e1-478a-9e04-ed1df96f313b.mov
https://user-images.githubusercontent.com/19269911/235620504-ffde5c08-b484-46f9-aee4-313274f9c4b9.mov
> fix(clerk-js): Use redirectWithAuth after multi session signOut

- packages/clerk-js/src/core/errors.ts
- packages/clerk-js/src/core/resources/SignIn.ts
FAPI will throw a similar error if the request fails
> chore(clerk-js): Remove unnecessary runtime error

- packages/nextjs/src/app-router/server/utils.ts
Otherwise Next12 apps will break because next/headers was introduced in next@13
> fix(nextjs): Import next/headers dynamically

- packages/clerk-js/src/core/resources/SignIn.ts
- packages/clerk-js/src/core/resources/SignUp.ts
- packages/clerk-js/src/ui/components/SignIn/SignInStart.tsx
- packages/clerk-js/src/ui/components/SignIn/__tests__/SignInStart.test.tsx
- packages/clerk-js/src/ui/components/SignUp/SignUpStart.tsx
- packages/clerk-js/src/ui/components/SignUp/__tests__/SignUpStart.test.tsx
- packages/clerk-js/src/ui/components/SignUp/__tests__/util.test.ts
- packages/clerk-js/src/ui/components/SignUp/util.ts
- packages/types/src/redirects.ts
- packages/types/src/signUp.ts
Note: Draft PR
First commit addresses signing in with SAML.
~~If the sign-up created contains `saml` in the supported_first_factors, then we navigate to the `/sign-in/factor-one` route, where the actual redirection is initiated.~~
~~Note: debating whether I should keep the handling in `SignInStart.tsx` instead.~~
Redirection is handled in `SignUpStart.tsx` for sign-up & `SignInStart.tsx` for`sign-in`, respectively.
> feat(clerk-js,types): Support sign in with SAML strategy

- packages/nextjs/src/server/authMiddleware.test.ts
- packages/nextjs/src/server/authMiddleware.ts
> fix(nextjs): Use signInUrl and signUpUrl from the env

- packages/backend/src/api/factory.test.ts
- packages/backend/src/api/resources/Deserializer.ts
- packages/backend/src/api/resources/Email.ts
- packages/backend/src/api/resources/JSON.ts
- packages/backend/src/api/resources/SMSMessage.ts
- packages/backend/src/fixtures/responses/email.json
- playground/nextjs/pages/api/sendEmail.ts
Update `Email` & `SmsMessage` resources types and fix isPaginated condition to check that `data` contained in the resource response should be array.
I have also added a test with the actual response of BAPI call to `POST v1/emails` to verify the fix.
> fix(backend): error parsing POST v1/emails response

- packages/clerk-js/src/ui/elements/Modal.tsx
- packages/clerk-js/src/ui/hooks/usePopover.ts
This fixes the issue with the 1Password button where the modal would close when that was pressed. It also fixes the issue where having two modals open and clicking the latest one would close the first one.
> fix(clerk-js): Only close modals when pressing on their overlay

- packages/backend/src/tokens/request.ts
- packages/clerk-js/src/core/clerk.ts
- packages/nextjs/src/server/utils.ts
- packages/nextjs/src/server/withClerkMiddleware.ts
- packages/react/src/errors.ts
- packages/react/src/isomorphicClerk.ts
- packages/remix/src/ssr/authenticateRequest.ts
- packages/shared/src/utils/proxy.ts
- packages/types/src/multiDomain.ts
```jsx
<ClerkProvider proxyUrl={'/__clerk'}>
{...}
```
```jsx
<ClerkProvider proxyUrl={'/__clerk'}>
{...}
{/* or*/}
<ClerkProvider 
proxyUrl={(url) => {
/* Do something with the url */
return new Url('/__clerk',url).toString(); // or simply return  '/__clerk'
}}
>
{...}
```
This PR adds support for proxyUrl function in react, nextjs(middleware), remix(rootLoader)
> Support passing a function as proxyUrl

- packages/clerk-js/src/core/resources/DisplayConfig.ts
- packages/clerk-js/src/ui/elements/ApplicationLogo.tsx
- packages/types/src/displayConfig.ts
Instead of going with the per-instance FF approach, we decided to introduce 2 new fields on displayConfig:
```
logoImageUrl
faviconImageUrl
```
They will gradually replace the existing imageUrl and faviconUrl fields
> fix(clerk-js,types): Deprecate private imageUrl and use logoImageUrl

- package-lock.json
- packages/localizations/src/en-US.ts
- packages/types/src/localization.ts
Add password bytes exceeded error message
> COR-350 fix(clerk-js): Add password bytes exceeded error message

- packages/react/src/isomorphicClerk.ts
When using strict mode in React 18, the component will mount twice and so, `handleRedirectCallback` will also run two time, resulting in an error the second time. This is handled in the same manner in clerk-js, but it was not handled in this case here.
> fix(clerk-react): Catch handleRedirectCallback error that occurs in strict mode

- packages/clerk-js/src/ui/elements/FormControl.tsx
> fix(clerk-js): Update `useCalculateErrorTextHeight` to increase spacing

- packages/clerk-js/src/utils/__tests__/url.test.ts
- packages/clerk-js/src/utils/url.ts
Check the origin in `isAllowedRedirectOrigin`, since we are aiming for origin whitelisting.
> fix(clerk-js): Only check origin in isAllowedRedirectOrigin

- packages/clerk-js/package.json
> chore(clerk-js): Increase the bundle watch limit

- packages/clerk-js/src/ui/components/SignIn/AlternativeMethods.tsx
- packages/clerk-js/src/ui/components/SignIn/ForgotPasswordAlternativeMethods.tsx
- packages/clerk-js/src/ui/components/SignIn/SignInFactorOne.tsx
- packages/clerk-js/src/ui/components/SignIn/SignInFactorOnePasswordCard.tsx
- packages/clerk-js/src/ui/components/SignIn/__tests__/SignInFactorOne.test.tsx
- packages/clerk-js/src/ui/components/SignIn/useResetPasswordFactor.tsx
- packages/clerk-js/src/ui/components/SignIn/withHavingTrouble.tsx
- packages/clerk-js/src/ui/hooks/useAlternativeStrategies.ts
- packages/localizations/src/da-DK.ts
- packages/localizations/src/de-DE.ts
- packages/localizations/src/en-US.ts
- packages/localizations/src/es-ES.ts
- packages/localizations/src/fr-FR.ts
- packages/localizations/src/it-IT.ts
- packages/localizations/src/nl-NL.ts
- packages/localizations/src/pt-BR.ts
- packages/localizations/src/sv-SE.ts
- packages/types/src/localization.ts
This PR has the following changes
- Change text from 'Forgot Password' to 'Forgot Password?' in <SignIn />
- When user clicks on the link show a screen with the following options:
- Add Reset Password Option
- Social Connection and Web3 Options
- If other authentication factors are turned on
- Email Code
- Email Link
- SMS Code
https://github.com/clerkinc/javascript/assets/19269911/a9d55752-150a-4127-b305-46858067a844
> Forgot password link displays new screen before reset password code

- packages/clerk-js/src/utils/__tests__/url.test.ts
- packages/clerk-js/src/utils/url.ts
- packages/types/src/clerk.ts
- Add regex support
- Trim trailing slashes from origins to improve DX for glob matching
-
> fix(clerk-js): Support RegExp for allowedRedirectOrigins

- packages/clerk-js/src/ui/components/OrganizationProfile/ProfileSettingsPage.tsx
- packages/clerk-js/src/ui/components/UserProfile/ProfilePage.tsx
- packages/clerk-js/src/utils/image.ts
- packages/clerk-js/src/utils/index.ts
- packages/clerk-js/src/utils/user.ts
- packages/types/src/image.ts
Also fixed the issue of not checking for org image removal ability correctly.
I'd consider adding this as a method on the user/org objects as well.
> fix(clerk-js,types): Update isDefaultProfileImage util

- packages/types/src/factors.ts
- packages/types/src/signIn.ts
- playground/nextjs/middleware.ts
- playground/nextjs/pages/custom/forgotPassword.tsx
This PR 
- Updates types for `signIn.create` and `signIn. attemptFirstFactor` to properly allow the reset password params
- Adds an example usage in a playground app
> Support Reset password for custom flows

- packages/nextjs/src/server/authMiddleware.test.ts
- packages/nextjs/src/server/authMiddleware.ts
Add skipped failing test for supporting sign-in and sign-up urls from env and update the code to retrieve the envs each time the middleware tun to support support the testing.
> fix(nextjs): Enable authMiddleware testing for sign-in/sign-up urls from env

- packages/expo/src/useOAuth.ts
The default path parameter shouldn't start with a / otherwise the final URL contains /// when the scheme is concatenated.
https://linear.app/clerk/issue/JS-406/expo-useoauth-hook-breaks-production
> fix(clerk-expo): Fix default useOAuth callback

- packages/nextjs/src/client-boundary/uiComponents.tsx
- packages/nextjs/src/index.ts
- playground/nextjs/pages/_app.tsx
`SignOutButton` wasn't exported from `@clerk/nextjs`. This PR simply re-exports it from `@clerk/clerk-react`.
I also added `SignOutButton` into the NextJS playground for a simple "gut check."
Fixes #1213
> fix(nextjs): Export SignOutButton

- packages/clerk-js/src/ui/components/SignIn/__tests__/ResetPassword.test.tsx
- packages/clerk-js/src/ui/components/SignIn/__tests__/SignInFactorTwo.test.tsx
- packages/clerk-js/src/ui/components/UserProfile/__tests__/PasswordPage.test.tsx
Due to the delayed mount and unmount of the animated field errors some tests fail in an inconsistent pattern. Increasing the timeout for this test fixes the problem
> Fix flaky test regarding UI errors in forms

- packages/clerk-js/src/ui/customizables/elementDescriptors.ts
- packages/clerk-js/src/ui/elements/CodeControl.tsx
- packages/clerk-js/src/ui/elements/FormControl.tsx
- packages/types/src/appearance.ts
> fix(clerk-js): Use FormFeedback abstraction instead of FormErrorText

- package-lock.json
- packages/sdk-node/package.json
- packages/sdk-node/src/authenticateRequest.ts
- packages/sdk-node/src/shared.ts
@clerk/shared inside @clerk/clerk-sdk-node breaks customers as it requires react to be installed on the project as well.
> fix(clerk-sdk-node): Remove @clerk/shared as dependency

- packages/clerk-js/src/core/clerk.ts
Separate release to enable clerk images so we can rollback easily in case anything breaks. Not removing the FF also allows us to individually rollback dashboard or accounts by explicitly settings the ff to false. 
This is the final release before we remove the experimental prefix tomorrow.
> fix(clerk-js): Enable clerk images

- packages/clerk-js/src/ui/components/SignIn/__tests__/ResetPassword.test.tsx
- packages/clerk-js/src/ui/components/SignIn/__tests__/SignInFactorOne.test.tsx
- packages/clerk-js/src/ui/components/SignIn/__tests__/SignInFactorTwo.test.tsx
- packages/clerk-js/src/ui/components/UserProfile/__tests__/PasswordPage.test.tsx
This PR wraps parts of code in our tests that depend on real time to elapse (usage of `setTimeout`). Wrapping those part with `runFakeTimers` prevents the code from being delayed while executing setTimeout inside tests.
This results to test taking less time to run and there is much less change for a test to fail due to timeouts
> Fix flaky UI error tests

- packages/clerk-js/src/ui/components/OrganizationProfile/InviteMembersForm.tsx
`npm test` was outputting `Warning: React does not recognize the 'X' prop on a DOM element.`
This PR ensures that those props don't make their way to the DOM element.
> fix(clerk-js): Remove invalid props on DOM element

- packages/clerk-js/src/ui/components/SignIn/ResetPassword.tsx
- packages/clerk-js/src/ui/components/SignIn/__tests__/ResetPassword.test.tsx
- packages/clerk-js/src/ui/components/UserProfile/PasswordPage.tsx
- packages/clerk-js/src/ui/components/UserProfile/__tests__/PasswordPage.test.tsx
> Add identifier for password managers where password changes

- packages/nextjs/src/server/withClerkMiddleware.ts
Deprecate `withClerkMiddleware` in favour of the new `authMiddleware`.
> chore(nextjs): Deprecate withClerkMiddleware

- packages/clerk-js/src/utils/__tests__/url.test.ts
Mocks `console.warn` in `url.test.ts` to ensure clean Jest log output. Added minimal checks to ensure the correct message is being sent.
I discovered that the `isAllowedRedirectOrigin` test was being run using `fdescribe` meaning that only that test in the current file was being run. I updated it to `describe`.
> chore(clerk-js): Mock `console.warn` in `url.test.ts`

- packages/nextjs/src/server/authMiddleware.test.ts
- packages/nextjs/src/server/authMiddleware.ts
> chore(nextjs): Use req.cookies instead of getCookie

- packages/clerk-js/src/ui/elements/PhoneInput/countryCodeData.ts
Before:
src="https://github.com/clerkinc/javascript/assets/73396808/f6170948-572d-49dc-9c91-e4d3af4a6905">
After:
> fix(clerk-js): Correct china phone number hyphen positions

- packages/clerk-js/webpack.config.js
Optimizes SVGs automatically via Webpack. 
It contains all of the settings I used via SVGOMG in #1222 with the exception of `floatPrecision` and `transformPrecision` so as to not cause undue rendering issues.
While this is a good step, it's largely a catch-all. `floatPrecision` being set to `3` is a safe and will catch any errant SVGs, but is unlikely to get you the true optimization you're looking for.
I would still suggest manually optimizing new SVGs with [SVGOMG](https://jakearchibald.github.io/svgomg/) as you're able. It'll allow you to fine-tune the `floatPrecision` and, if need be, `transformPrecision` and seeing if, and how, the SVG is affected. Make sure to enable "Prefer viewBox to width/height" when using SVGOMG.
As with #1222, I did my best to check the output "in the wild" …
> chore(clerk-js): Enable SVGO in Webpack through SVGR

- packages/remix/src/client/useAwaitableNavigate.tsx
When using a catchall route (`$.tsx`) in remix, the transition state `useTransition().state` remains idle during the navigation, so we are never able to resolve the promise we create in our `awaitableNavigate`.
I've replaced that with the `useLocation` hook, which is exported straight from the `react-router` package. This will rerender the component even if we navigate to the same url (in that case `location.key` will be different).
> fix(remix): Use location to verify navigation completion

- packages/gatsby-plugin-clerk/src/gatsby-browser.tsx
- packages/gatsby-plugin-clerk/src/gatsby-ssr.tsx
This PR propagates the Gatsby plugin options to ClerkProvider as props.
Example using localization:
```ts
import type { GatsbyConfig } from "gatsby"
import type { ClerkProviderProps } from "gatsby-plugin-clerk"
import { frFR } from "@clerk/localizations"
const config: GatsbyConfig = {
...
plugins: [
{
resolve: `gatsby-plugin-clerk`,
options: {
localization: frFR,
} as ClerkProviderProps
},
],
}
export default config
```
> fix(gatsby-plugin-clerk): Pass the plugin options as ClerkProvider props

- packages/backend/src/util/request.test.ts
- packages/backend/src/util/request.ts
- packages/nextjs/src/server/authenticateRequest.ts
Changes:
- Use the first value in `x-forwarded-proto`, `x-forwarded-port` when multiple values passed in headers
- Pass `x-forwarded-proto` header from `@clerk/nextjs` to `@clerk/backend`
- Use `x-forwarded-proto` as fallback when `x-forwarded-proto` and `x-forwarded-port` mismatch (fixes Railway App issue with headers)
- Drop `async` from requests test
> fix(backend): Fixes issue with the forwarded headers

- packages/clerk-js/src/ui/components/OrganizationProfile/__tests__/OrganizationMembers.test.tsx
- packages/clerk-js/src/ui/router/__tests__/HashRouter.test.tsx
- packages/clerk-js/src/ui/router/__tests__/PathRouter.test.tsx
Updates `act` to `waitFor` or removes `act` altogether from the specs.
Fixes multiple similar errors:
```
Warning: An update to ActiveMembersList inside a test was not wrapped in act(...).
@clerk/clerk-js:test:       
@clerk/clerk-js:test:       When testing, code that causes React state updates should be wrapped into act(...):
@clerk/clerk-js:test:       
@clerk/clerk-js:test:       act(() => {
@clerk/clerk-js:test:         /* fire events that update state */
@clerk/clerk-js:test:       });
@clerk/clerk-js:test:       /* assert on the output */
@clerk/clerk-js:test:       
@clerk/clerk-js:test:       This ensures that you're testing the behavior the user would see in the browser. Learn more at https://reactjs.org/link/wrap-tests-with-act
```
This, along with #1237 and #1235, removes all …
> test(clerk-js): Update usage of `act`

- packages/remix/src/client/ClerkCatchBoundary.tsx
While working on the Clerk Remix docs, I noticed that class components were not allowed to be passed as a custom catch boundary, even though there doesn't appear to be any reason for this in the code.
This PR makes an update to the TS typings to fix this issue.
> fix(remix): Enable RootCatchBoundary to be a class component

- packages/backend/src/util/request.test.ts
- packages/backend/src/util/request.ts
- packages/nextjs/src/server/authenticateRequest.ts
> Revert AWS and Railway Apps `x-forwarded-*` headers changes

- packages/expo/src/useOAuth.ts
This fixes the empty object requirement to use startOAuthFlow. All parameters are optional anyway so we shouldn't require the empty object.
This fixes the requirement of sending an empty object to start an OAuth flow.
JS-451
> Fix - JS-451:  empty object requirement expo startOAuthFlow 

- packages/clerk-js/README.md
In the README of the `clerk-js` package, the instructions to get up and running are incorrect, as they're missing the publishable key.
I discovered this while working on the Clerk beta docs, and think that we should make sure that the README of the package is up-to-date with our new docs.
> docs(clerk-js): Fix instructions in the README

- .changeset/pretty-horses-suffer.md
- packages/clerk-js/src/core/clerk.ts
- packages/clerk-js/src/core/fapiClient.ts
- packages/clerk-js/src/core/resources/SignUp.ts
- packages/clerk-js/src/utils/captcha.ts
> feat(clerk-js): Use fapi client url to load CF turnstile

- packages/clerk-js/src/core/resources/Image.ts
- packages/types/src/user.ts
```tsx
import { useUser } from '@clerk/nextjs';
const toBase64 = (file: File) =>
new Promise<string>((resolve, reject) => {
const reader = new FileReader();
reader.readAsDataURL(file);
reader.onload = () => resolve(reader.result as string);
reader.onerror = reject;
});
const UserProfilePage = () => {
const { user } = useUser();
return (
<input
type='file'
onChange={async event => {
const file = event.target.files[0];
const base64 = await toBase64(file);
const imgRes = await user?.setProfileImage({
file: base64,
})
}}
/>
);
};
```
> User.setProfileImage accepts file a Base64 string

- packages/clerk-js/src/ui/elements/FormControl.tsx
- packages/clerk-js/src/ui/elements/PasswordInput.tsx
- packages/clerk-js/src/ui/hooks/usePassword.ts
- packages/clerk-js/src/ui/primitives/FormControl.tsx
- packages/clerk-js/src/ui/primitives/hooks/useFormControl.tsx
- packages/clerk-js/src/ui/utils/useFormControl.ts
https://github.com/clerkinc/javascript/assets/19269911/70bc9f1e-6c32-4fa2-ad5a-e2e02aebd980
> Display zxcvbn errors as a warning when focus is not lost

- .changeset/seven-mayflies-push.md
- packages/nextjs/package.json
- packages/nextjs/src/server/authMiddleware.test.ts
- packages/nextjs/src/server/authMiddleware.ts
- packages/nextjs/src/server/authenticateRequest.ts
- packages/nextjs/src/server/utils.ts
This commit introduces a new `apiRoutes` param on `authMiddleware`.
If `apiRoutes` is omitted, then the following heuristic is used: 
- If the route path is `['/api/(.*)', '/trpc/(.*)']` 
- or Request has `Content-Type: application/json` 
- or Request method is not-`GET,OPTIONS,HEAD`,
then this is considered an API route.
After this commit, a 401 JSON Response is returned on the following 3 cases:
- When the `authenticateRequest` function returns the `Unknown` state.
- When the `authenticateRequest` function returns the `Interstitial` state and the route is an API route.
- When the user is signed out, the route is protected (not public), and the route is an API route. _(this one happens inside our default implementation of `afterAuth`. If it is overwritten, then the user needs to handle …
> feat(nextjs): Return 401 Response on protected API routes

- .changeset/lemon-trains-wash.md
- package-lock.json
- packages/backend/src/constants.ts
- packages/fastify/src/__snapshots__/constants.test.ts.snap
- packages/nextjs/src/server/authMiddleware.test.ts
- packages/nextjs/src/server/authMiddleware.ts
- packages/nextjs/src/server/redirect.ts
- packages/nextjs/src/server/utils.ts
This PR refactors and improves #1241.
This PR also introduces a new header `x-clerk-redirect-to` which indicates that `redirectToSignIn` or `redirectToSignUp` have been called.
After this PR, Dev Browser on redirects will only be appended if all of the following conditions apply:
- `redirectToSignIn` or `redirectToSignUp` have been called,
- the Secret Key hints a development Clerk instance,
- the redirection is cross-origin
This change fixes the dev browser issue on implementations that use custom domains for sign-in or sign-up pages, other than Clerk Hosted Pages.
> fix(nextjs): Append DevBrowser on cross-origin redirects

- .changeset/brave-ravens-repeat.md
- .changeset/eighty-lamps-joke.md
- .changeset/grumpy-dragons-complain.md
- .changeset/real-pillows-dance.md
- .changeset/thick-dodos-eat.md
- packages/backend/src/tokens/interstitialRule.ts
- packages/backend/src/tokens/request.test.ts
- packages/backend/src/util/request.test.ts
- packages/backend/src/util/request.ts
- packages/nextjs/src/server/authMiddleware.ts
- packages/nextjs/src/server/authenticateRequest.ts
The @clerk/backend was failing to verify the session due to the `Non Browser [3y]` assertion in interstitial rules which was checking that the userAgent of the request should start with Mozilla/. The AWS Amplify replaces the userAgent with `Amazon CloudFront` which results in `authMiddleware` having a signed-out state as auth. 
Also, the AWS passes comma separated list of values as x-forward-* header value, which was causing the `cross-origin referer [2y]` assertion in interstitial rules to fail.
The Railway App passes comma separated list of values as x-forward-* header value, which was causing the `cross-origin referer [2y]` assertion in interstitial rules to fail.
Also, there is an inconsistency between the x-forwarded-proto and the x-forwarded-port which in most cases and platforms …
> Fix(backend,nextjs): issue with forward proto cross origin in AWS and Railway Apps

- .changeset/old-stingrays-tap.md
- packages/clerk-js/src/ui/components/UserProfile/PasswordPage.tsx
- packages/clerk-js/src/ui/components/UserProfile/ProfilePage.tsx
- packages/clerk-js/src/ui/components/UserProfile/__tests__/PasswordPage.test.tsx
- packages/clerk-js/src/ui/components/UserProfile/__tests__/ProfilePage.test.tsx
- packages/clerk-js/src/ui/elements/InformationBox.tsx
- packages/clerk-js/src/ui/elements/index.ts
- packages/clerk-js/src/ui/icons/index.ts
- packages/clerk-js/src/ui/icons/information-circle.svg
- packages/localizations/src/en-US.ts
- packages/types/src/localization.ts
When a user has enterprise accounts, then first name & last name should not be editable because they are generally provided by the IdP.
Also, if password is enabled, it should not be editable because SAML takes precedence and password cannot effectively be used.
> feat(clerk-js,localizations,types): Readonly fname/lname/password for user with SAML accounts

- .changeset/silver-days-sit.md
- packages/clerk-js/src/core/fapiClient.ts
- packages/clerk-js/src/core/resources/Image.ts
- packages/types/src/user.ts
> Image.create sends base64 string with application/octet-stream

- .changeset/small-bikes-complain.md
- packages/clerk-js/src/ui/elements/CodeControl.tsx
This PR fixes an issue SMS Otp autofill in iOS devices that use Chrome. I could not figure exactly why but [this](https://github.com/chakra-ui/chakra-ui/issues/4095#issuecomment-1057077519) might give a hint about why this issue exist.
> fix(clerk-js): SMS TOP autofill broken in Chrome for iOS

- .changeset/twelve-avocados-kneel.md
- .vscode/launch.json
- packages/sdk-node/src/authenticateRequest.test.ts
- packages/sdk-node/src/authenticateRequest.ts
- packages/sdk-node/src/clerkClient.ts
- packages/sdk-node/src/requireAuth.ts
- packages/sdk-node/src/withAuth.ts
- playground/express/src/routes/private.ts
- playground/express/src/server.ts
> fix(clerk-sdk-node): load config on first use

- .changeset/witty-books-jam.md
- packages/backend/src/tokens/interstitial.ts
- packages/nextjs/src/server/__tests__/__snapshots__/exports.test.ts.snap
- packages/nextjs/src/server/authenticateRequest.ts
- packages/nextjs/src/server/clerkClient.ts
- packages/nextjs/src/server/withClerkMiddleware.ts
- packages/nextjs/src/ssr/withServerSideAuth.ts
- packages/nextjs/src/utils/mergeNextClerkPropsWithEnv.ts
- packages/remix/src/client/RemixClerkProvider.tsx
- packages/remix/src/client/types.ts
- packages/remix/src/ssr/utils.ts
- packages/sdk-node/src/authenticateRequest.ts
- packages/sdk-node/src/clerkClient.ts
Review per commit. (Changes for each package)
> Pass `clerkJSVersion` in interstitial

- .changeset/slow-falcons-design.md
- packages/backend/src/api/resources/index.ts
- packages/react/package.json
- packages/react/tsup.config.ts
- packages/sdk-node/package.json
- packages/sdk-node/src/authenticateRequest.ts
- packages/sdk-node/src/clerkClient.ts
- packages/sdk-node/src/instance.ts
- packages/sdk-node/src/utils.ts
- packages/sdk-node/tsconfig.declarations.json
- packages/sdk-node/tsconfig.json
- packages/sdk-node/tsup.config.ts
- packages/shared/package.json
- packages/shared/tsup.config.ts
- playground/express/package.json
- fix proxy initialisation. The clerkClient never initialised before
- align esm/cjs build config with the other related packages
- various cleanups
- enable isolatedModules for clerk/clerk-sdk-node
A proxy is used for the top-levle clerkClient object as we want to read the env variables only when clerkClient is actually used for the first time.
The alternative approach would be to turn all env-related props into getters, however, we're making heavy use of the `...` destructuring operator. When a getter is destructured into a new object, the value is copied and not the getter function.
> Correctly initialize clerkClient in clerk-sdk-node

- .changeset/silent-maps-complain.md
- packages/fastify/src/clerkPlugin.test.ts
- packages/fastify/src/clerkPlugin.ts
- packages/fastify/src/types.ts
Adds support for option `{hookName: 'onRequest'}`, which binds the callback to the specified hook.
By default, or when specified as such, the callback will continue to be bound to `preHandler`.
This update prevents binding to any other hook to minimize compatibility requirements going forward.
Fixes #1350
> feat(fastify): Support `{hookName: 'onRequest'}`

- .changeset/wise-turtles-study.md
- packages/clerk-js/src/ui/components/OrganizationProfile/OrganizationProfileAvatarUploader.tsx
- packages/clerk-js/src/ui/components/UserButton/UserButtonTrigger.tsx
- packages/clerk-js/src/ui/components/UserProfile/UserProfileAvatarUploader.tsx
- packages/clerk-js/src/ui/customizables/index.ts
- packages/clerk-js/src/ui/customizables/makeResponsive.tsx
- packages/clerk-js/src/ui/elements/Avatar.tsx
- packages/clerk-js/src/ui/elements/OrganizationPreview.tsx
- packages/clerk-js/src/ui/elements/UserPreview.tsx
- packages/clerk-js/src/ui/primitives/Image.tsx
- packages/clerk-js/src/ui/styledSystem/types.ts
- packages/clerk-js/src/utils/url.ts
- packages/shared/src/utils/index.ts
- packages/shared/src/utils/isRetinaDisplay.ts
This is the complimentary clerk-js work , for more information and examples go to: https://github.com/clerkinc/cloudflare-workers/pull/31 
Introduce a makeResponsive HOC that adds the `srcset` attribute on all images served by the img-service worker. 
Primitives shouldn't be aware of any Clerk-specific logic. All the image optimization logic is now extracted into its own makeResponsive HOC.
Apart from resizing te image, more optimizations are now enabled:
- dynamic format negotiation (avif and webp support, falls back to jpeg when needed). This offers up to ~50% size reduction.
- scale down to a max width of 1920
- set a default quality of 80
- respect height, width, fit and quality params
Before: 
After:
> Optimize images

- .changeset/serious-mirrors-return.md
- packages/localizations/src/ko-KR.ts
Update sign in start to read as Sign In versus "Join Membership"
This changes the Korean localization from "Join Membership" to "Sign In"
> Update sign in start for Korean

- .changeset/eighty-planes-taste.md
- packages/localizations/src/fr-FR.ts
Missing fr-FR translations use_email & use_phone (see screenshots).
> Missing fr-FR translations use_email & use_phone

- .changeset/fifty-eels-work.md
- packages/clerk-js/src/core/resources/User.ts
- packages/clerk-js/src/core/resources/UserSettings.ts
- packages/clerk-js/src/ui/components/OrganizationSwitcher/OtherOrganizationActions.tsx
- packages/clerk-js/src/ui/components/OrganizationSwitcher/__tests__/OrganizationSwitcher.test.tsx
- packages/types/src/json.ts
- packages/types/src/user.ts
- packages/types/src/userSettings.ts
If the "user can create organizations" permission is false, the "create organization" button will not appear in the `OrganizationSwitcher` component.
> Implement organization creation permission controls

- .changeset/pink-carpets-matter.md
- packages/backend/src/index.ts
- packages/backend/src/tokens/index.ts
- packages/backend/src/tokens/request.ts
- packages/backend/src/util/request.ts
- packages/sdk-node/src/authenticateRequest.ts
- packages/sdk-node/src/types.ts
This PR simplifies the signature of `authenticateRequest` for better DX on both `@clerk/backend` and `@clerk/clerk-sdk-node` packages:
- One pair of legacy or new instance keys are required now and not all 4 of them
- `@clerk/backend` now can handle the `"Bearer "` prefix in Authorization header for better DX
- `host` parameter is now optional in `@clerk/backend`
Before:
```ts
import clerkClient from '@clerk/clerk-sdk-node';
// `Bearer asdgfjdkhgmsfngl`
const authHeader = request.headers.get('authorization') || '';
const authToken = authHeader.split(` `)[1];
const res = await clerkClient.authenticateRequest({
headerToken: authToken,
publishableKey: process.env.CLERK_PUB_KEY,
secretKey: process.env.CLERK_SECRET_KEY,
apiKey: ``,
frontendApi: ``,
host: ``,
});
...
```
After this PR:
```ts …
```
> feat(backend,clerk-sdk-node): Simplify the authenticateRequest signature

- .changeset/old-eggs-own.md
- packages/clerk-js/src/core/resources/Organization.ts
- packages/clerk-js/src/core/resources/OrganizationSettings.ts
- packages/clerk-js/src/core/resources/User.ts
- packages/clerk-js/src/core/resources/__snapshots__/Organization.test.ts.snap
- packages/clerk-js/src/core/resources/__snapshots__/OrganizationMembership.test.ts.snap
- packages/clerk-js/src/ui/components/OrganizationProfile/ActionConfirmationPage.tsx
- packages/clerk-js/src/ui/components/OrganizationProfile/OrganizationProfileRoutes.tsx
- packages/clerk-js/src/ui/components/OrganizationProfile/OrganizationSettings.tsx
- packages/localizations/src/en-US.ts
- packages/types/src/json.ts
- packages/types/src/localization.ts
- packages/types/src/organization.ts
- packages/types/src/organizationSettings.ts
Adds the ability for admins to delete organizations from the UI, as long as the `adminDelete` permission is present.
> Add ability to delete an organization

- docs/CONTRIBUTING.md
As requested by @nikosdouvlis - added a short section on why we use changesets for versioning to the contributing guide!
> Add 'why we use changesets' section to contributing guide

- .changeset/pretty-moose-taste.md
- packages/localizations/src/pt-BR.ts
fix(localizations): Missing pt-BR translations couldBeStronger & goodPassword
screenshot of the bug:
> fix(localizations): Missing pt-BR translations

- .changeset/new-llamas-complain.md
- packages/nextjs/src/server/authMiddleware.ts
Even though the `isApiRoute` is added to AfterAuthHandler['auth'] object, the type is not updated to indicate this.
> fix(nextjs): Add isApiRoute to AfterAuthHandler['auth'] type

- .changeset/fifty-ravens-double.md
- packages/localizations/src/fr-FR.ts
Missing fr-FR translations for reset password page (see screenshots).
> fix(localizations): Missing fr-FR translations for reset password page

- .changeset/metal-dolphins-act.md
- packages/clerk-js/src/utils/cookies/handler.ts
- packages/clerk-js/src/utils/runtime.ts
…
This change allows e2e suites running on cypress to work without additional setup.
> fix(clerk-js): Only set the __session cookie as `none` for secure iframes

- .changeset/nice-kangaroos-teach.md
- packages/nextjs/src/server/authMiddleware.ts
- packages/nextjs/src/server/clerkClient.ts
- [] `npm test` runs as expected.
- [] `npm run build` runs as expected.
Override the `req.nextUrl` host with the `HOSTNAME` environment variable.
With this fix we can resolve the incorrect hostname in the NextJS applications deployed outside Vercel platform.
> fix(nextjs): Support req.clerkUrl to fix issue with NextJS hostname on proxied apps

- packages/types/src/organization.ts
OrganizationResource.logoUrl is deprecated in favor of OrganizationResource.imageUrl
> fix(types): Deprecate OrganizationResource.logoUrl

- .changeset/orange-bats-learn.md
- packages/localizations/src/de-DE.ts
added missing translation for "deleting an account" in the  dangerSection of the userProfile
> fix(localizations): Added missing translation in de-DE.ts

- packages/nextjs/src/utils/pathMatchers.ts
Minor fix of a error. The link had a period at the end so if a user clicked on the link they got a 404 on GitHub.
> Removed period from end of link to avoid 404

- .changeset/slow-needles-jam.md
- packages/nextjs/src/server/authMiddleware.ts
Issue: https://github.com/clerkinc/javascript/issues/1413
PR introducing issue: https://github.com/clerkinc/javascript/pull/1394
> fix(nextjs): Avoid setting clerkUrl port when http(s) forwarded port and protocol is defined

- .changeset/swift-doors-shop.md
- packages/nextjs/src/server/authMiddleware.ts
This PR adds incorrect keys as a reason on the Infinite Loop Detection error text.
Before:
```
Reason 2:
You changed Clerk instance keys (Publishable Key, Secret Key).
How to resolve:
-> Make sure you have cleared your browser's application data and cookies everytime you change keys.
```
After:
```
Reason 2:
Your Clerk instance keys are incorrect, or you recently changed keys (Publishable Key, Secret Key).
How to resolve:
-> Make sure you're using the correct keys from the Clerk Dashboard. If you changed keys recently, make sure to clear your browser application data and cookies.
```
> fix(nextjs): Add incorrect keys as a reason on the Infinite Loop Detection error text

- .changeset/thirty-chefs-unite.md
- packages/backend/src/tokens/jwt/verifyJwt.ts
This change will make the `verifyJwt` function to be more tolerant by default to clock skew, increasing it from 2 seconds to 5 seconds.
> feat(backend): Increase the default value for clock skew in `verifyJwt` from 2 to 5 seconds

- .changeset/proud-cycles-type.md
- packages/backend/src/tokens/interstitialRule.ts
- packages/backend/src/tokens/request.test.ts
Requests to satellite apps visited by non browsers should be treated as signed out
This is necessary, because tools like `opengraph.xyz` will not follow redirects, and they will always end up with parsing our interstitial template.
> Non browsers requests to satellite apps  should not throw intestitial

- .changeset/rude-glasses-hang.md
- packages/react/src/isomorphicClerk.ts
This was causing `const {openCreateOrganization} = useClerk()` to result in an error when the function was called
> Add `openCreateOrganization` method to isomorphicClerk

- .changeset/shaggy-spiders-sit.md
- packages/backend/src/index.ts
- packages/backend/src/tokens/index.ts
- packages/backend/src/tokens/interstitialRule.ts
- packages/backend/src/tokens/request.ts
- packages/sdk-node/src/authenticateRequest.ts
- packages/sdk-node/src/types.ts
Make all 4 keys (legacy and new) optional in `authenticateRequest`. That will make the `@clerk/backend` easier to use.
> fix(backend): Make all 4 keys (legacy and new) optional in `authenticateRequest`

- .changeset/bright-rules-agree.md
- packages/clerk-js/src/ui/components/UserProfile/RootPage.tsx
Moves the "delete account" UI down to the bottom of the profile page UI, under the security section
> Move 'delete account' UI to security section (USR-58)

- .changeset/stale-starfishes-watch.md
- packages/clerk-js/src/ui/components/SignIn/SignInFactorOnePasswordCard.tsx
- packages/clerk-js/src/ui/components/SignIn/SignInStart.tsx
> fix(clerk-js): Auto focus on password field after email input

- .changeset/smooth-crabs-build.md
- packages/backend/src/tokens/jwt/verifyJwt.ts
- packages/backend/src/tokens/request.ts
- packages/backend/src/tokens/verify.ts
The `clockSkewInSeconds` property is now deprecated from the `verifyJWT` options in favour of the new `clockSkewInMs` property. The old value incorrectly accepted a value in milliseconds so the behaviour will remain the same.
> feat(backend): Deprecate clockSkewInSeconds in favour of clockSkewInMs

- .changeset/lucky-panthers-draw.md
- packages/sdk-node/src/clerkClient.ts
- packages/sdk-node/src/utils.ts
> fix(clerk-sdk-node): Add jwtKey in api envs and use it redwood compatibility

- .changeset/ninety-llamas-act.md
- packages/react/src/isomorphicClerk.ts
Issue: https://github.com/clerkinc/javascript/issues/1451
> fix(clerk-react): IsomorphicClerk#addListener should return unsubscribe method

- .changeset/few-dingos-happen.md
- packages/clerk-js/src/ui/components/OrganizationProfile/ActionConfirmationPage.tsx
- packages/clerk-js/src/ui/components/UserProfile/DeletePage.tsx
- packages/localizations/src/en-US.ts
- packages/localizations/src/nb-NO.ts
- packages/localizations/src/vi-VN.ts
- packages/types/src/appearance.ts
- packages/types/src/localization.ts
Add delete confirmation input as an additional check when doing destructive actions.
The action added when users try to:
- delete an organization(USR-60)
- delete their account(URS-61)
- leaves an organization
https://github.com/clerkinc/javascript/assets/23478420/f16db3f8-c0db-4278-aa8b-671fb00e4f42
> Add delete confirmation

- .changeset/funny-melons-swim.md
- packages/backend/package.json
- packages/backend/src/exports.test.ts
- packages/backend/src/index.ts
- packages/backend/src/runtime/browser/fetch.mjs
- packages/backend/src/runtime/index.ts
- packages/backend/src/runtime/node/fetch.js
- packages/backend/src/tokens/index.ts
- packages/backend/src/tokens/request.ts
- packages/backend/src/util/IsomorphicRequest.ts
- packages/backend/tsconfig.declarations.json
- packages/backend/tsconfig.json
- packages/backend/tsup.config.ts
- packages/fastify/src/withClerkMiddleware.test.ts
- packages/fastify/src/withClerkMiddleware.ts
- packages/gatsby-plugin-clerk/src/ssr/authenticateRequest.ts
- packages/nextjs/src/api/__tests__/__snapshots__/exports.test.ts.snap
- packages/nextjs/src/edge-middleware/__tests__/__snapshots__/exports.test.ts.snap
- packages/nextjs/src/server/__tests__/__snapshots__/exports.test.ts.snap
- packages/nextjs/src/server/authenticateRequest.ts
- packages/remix/src/ssr/authenticateRequest.ts
- packages/sdk-node/package.json
- packages/sdk-node/src/__tests__/__snapshots__/exports.test.ts.snap
- packages/sdk-node/src/authenticateRequest.test.ts
- packages/sdk-node/src/authenticateRequest.ts
- playground/app-router/src/app/protected/page.tsx
Introducing the new utility `createIsomorphicRequest` for the `@clerk/backend` package, so that the `authenticateRequest` signature will be more simplified, and it will be easier to integrate with more frameworks.
> feat(backend): Introduce `createIsomorphicRequest`

- .changeset/spotty-months-worry.md
- packages/backend/src/api/endpoints/OrganizationApi.ts
- packages/backend/src/api/endpoints/UserApi.ts
- packages/backend/src/api/request.ts
This PR adds: 
- `updateOrganizationLogo` method in `OrganizationApi` class
- `updateUserProfileImage` method in `UserApi` class
> feat(backend): Add methods for uploading images to User and Organization

- .changeset/six-carrots-visit.md
- packages/clerk-js/src/ui/components/OrganizationSwitcher/OrganizationSwitcherPopover.tsx
- packages/clerk-js/src/ui/components/OrganizationSwitcher/OrganizationSwitcherTrigger.tsx
- packages/clerk-js/src/ui/elements/UserPreview.tsx
> Remove user identifiers from OrganizationSwitcher + Hide avatar on `hidePersonal`

- .changeset/nervous-poets-remember.md
- packages/shared/src/hooks/useOrganizations.tsx
The `useOrganizations` only contains logic that can be directly exported from `useClerk()` and `useOrganization` and `useOrganizationList` can be used as replacement with more functionality and better DX
> chore(shared): Deprecate useOrganizations

- .changeset/stupid-worms-change.md
- packages/clerk-js/src/ui/customizables/elementDescriptors.ts
- packages/clerk-js/src/ui/elements/AvatarUploader.tsx
- packages/types/src/appearance.ts
Enables the ability to target the Avatar upload and remove action buttons.
Fixes USR-98
> fix(clerk-js,types): Add keys targeting avatar buttons

- package-lock.json
- package.json
Upgrades `zx` to fix an [observed issue](https://github.com/google/zx/issues/443) with args parsing. This was impacting the snapshot release workflow ([example](https://github.com/clerkinc/javascript/actions/runs/5524436859/jobs/10076740933)).
> chore(repo): Bump zx to fix an issue with how args are parsed

- .changeset/four-monkeys-smell.md
- packages/backend/src/api/request.ts
- packages/backend/src/util/mockFetch.ts
This PR introduces a small fix for the Response Headers Content-Type check.
> fix(backend): Access the correct headers to determine the Response Content-Type

- .changeset/thin-hounds-arrive.md
- packages/clerk-js/src/ui/components/CreateOrganization/CreateOrganizationPage.tsx
This commit modifies the logic of the <CreateOrganization /> component to handle the case the newly create organization has max allowed memberships equal to 1. In this case, we shouldn't render the invitation page, as the user can't invite any more members, and they will need to skip it either way
https://github.com/clerkinc/javascript/assets/22435234/b53378f0-1326-40c2-9e30-1d6daba6702b
https://github.com/clerkinc/javascript/assets/22435234/b67868b5-ee15-4bfa-9ecf-caddecdcf394
> fix(clerk-js): In <CreateOrganization /> skip invitation page if max allowed memberships equal 1

- .changeset/fifty-keys-burn.md
- packages/clerk-js/src/ui/components/SignIn/SignInStart.tsx
- packages/clerk-js/src/ui/components/SignUp/SignUpStart.tsx
Although this doesn't seem like a big deal, it causes problem when a developer wants to override a value with an empty string. When that happens, we would render the children that I've removed instead of the empty string.
> fix(clerk-js): Remove leftover strings in SignInStart and SignUpStart

- .changeset/heavy-chicken-care.md
- packages/localizations/src/fr-FR.ts
Add missing "delete account" French translations
> Add missing "delete account" French translations

- .changeset/smooth-avocados-compete.md
- packages/fastify/src/clerkPlugin.test.ts
- packages/fastify/src/clerkPlugin.ts
The `ClerkFastifyOptions` type wasn't being passed through to the client, so typescript was complaining. :)
> fix(fastify): Correct fastify options type

- .changeset/tame-tomatoes-develop.md
- packages/react/src/hooks/useSessionList.ts
- packages/react/src/hooks/useSignIn.ts
- packages/react/src/hooks/useSignUp.ts
- packages/types/src/clerk.ts
This function was already deprecated but was not marked as such when re-exported from the hooks
> chore(clerk-react): Mark `setSession` as deprecated

- .changeset/curvy-rice-buy.md
- packages/chrome-extension/package.json
- packages/chrome-extension/src/ClerkProvider.tsx
- packages/chrome-extension/tsconfig.declarations.json
- packages/chrome-extension/tsup.config.ts
- packages/clerk-js/package.json
- packages/clerk-js/webpack.config.js
- playground/app-router/src/app/client/page.tsx
- playground/app-router/src/app/protected/page.tsx
> Correctly load clerk-js in clerk/chrome-extension

- .changeset/weak-ducks-double.md
- packages/clerk-js/src/ui/components/OrganizationProfile/OrganizationSettings.tsx
- packages/clerk-js/src/ui/components/OrganizationProfile/__tests__/OrganizationMembers.test.tsx
- packages/clerk-js/src/ui/components/OrganizationProfile/__tests__/OrganizationSettings.test.tsx
- packages/clerk-js/src/ui/components/OrganizationProfile/__tests__/utils.ts
- packages/clerk-js/src/ui/utils/test/createFixtures.tsx
- packages/types/src/organization.ts
This commit fixes a bug in our <OrganizationProfile /> component where an admin couldn't leave the organization even though there were more org admins present.
> fix(types,clerk-js): Allow organization admin to leave, if there are more admins

- .changeset/mighty-days-push.md
- packages/localizations/src/en-US.ts
- packages/types/src/localization.ts
New localization keys for max length exceeded validation:
- Organization name (form_param_max_length_exceeded__name)
- First name (form_param_max_length_exceeded__first_name)
- Last name (form_param_max_length_exceeded__last_name)
> chore(types,localizations): New localization keys for max length exceeded validation

- .changeset/little-donkeys-exist.md
- packages/clerk-js/src/ui/components/SignIn/ResetPassword.tsx
- packages/clerk-js/src/ui/components/SignUp/SignUpContinue.tsx
- packages/clerk-js/src/ui/components/SignUp/SignUpStart.tsx
- packages/clerk-js/src/ui/hooks/__tests__/usePasswordComplexity.test.tsx
- packages/clerk-js/src/ui/hooks/usePasswordComplexity.ts
- packages/clerk-js/src/ui/utils/passwordUtils.test.tsx
- packages/clerk-js/src/ui/utils/passwordUtils.ts
- packages/clerk-js/src/ui/utils/useFormControl.ts
fix(clerk-js): Eliminate pre/post onBlur states for password field
Eliminate pre/post onBlur states for password field and prioritize minimum character count error message over other complexity errors.
https://github.com/clerkinc/javascript/assets/23478420/2d00071a-bb47-4430-af7a-adc7df485b91
https://github.com/clerkinc/javascript/assets/23478420/37f13b56-29b1-4c1e-9aa7-2a9c9a88e58a
https://github.com/clerkinc/javascript/assets/23478420/ed264166-97a1-4229-9f48-e7dcef812781
> USR-194 fix(clerk-js): Eliminate pre/post onBlur states for password field

- .changeset/sixty-eyes-attend.md
- packages/backend/src/api/endpoints/InvitationApi.ts
Add filter by status(pending, accepted, revoked) support for getInvitationList method since it is supported by our [BE](https://clerk.com/docs/reference/backend-api/tag/Invitations#operation/ListInvitations)
> USR-165 fix(backend): Add filter by status support for getInvitationList() method

- .changeset/shaggy-vans-relax.md
- packages/clerk-js/src/core/resources/User.ts
- packages/clerk-js/src/core/resources/UserOrganizationInvitation.ts
- packages/clerk-js/src/core/resources/internal.ts
- packages/types/src/api.ts
- packages/types/src/index.ts
- packages/types/src/json.ts
- packages/types/src/user.ts
- packages/types/src/userOrganizationInvitation.ts
+ UserOrganizationInvitationResource
+ UserOrganizationInvitationJSON
+ ClerkPaginatedResponse that handles FAPI paginated responses
> feat(clerk-js,types): Introduce UserOrganizationInvitation

- .changeset/swift-rivers-behave.md
- packages/clerk-js/src/core/resources/Client.ts
- packages/clerk-js/src/core/resources/Session.ts
- packages/clerk-js/src/core/tokenCache.ts
- packages/types/src/client.ts
- packages/types/src/session.ts
The `Clerk.client.clearCache` method clears the internal token cache for each session of the current client.
Fixes https://github.com/clerkinc/javascript/issues/1525
> feat(clerk-js): Introduce Clerk.client.clearCache()

- .changeset/quiet-shirts-notice.md
- packages/backend/src/api/resources/JSON.ts
- packages/backend/src/api/resources/Organization.ts
- packages/backend/src/api/resources/OrganizationMembership.ts
- packages/backend/src/api/resources/User.ts
- packages/clerk-js/src/core/resources/Organization.test.ts
- packages/clerk-js/src/core/resources/Organization.ts
- packages/clerk-js/src/core/resources/OrganizationMembership.test.ts
- packages/clerk-js/src/core/resources/OrganizationMembership.ts
- packages/clerk-js/src/core/resources/User.ts
- packages/clerk-js/src/core/resources/__snapshots__/Organization.test.ts.snap
- packages/clerk-js/src/core/resources/__snapshots__/OrganizationMembership.test.ts.snap
- packages/types/src/json.ts
- packages/types/src/organization.ts
- packages/types/src/session.ts
- packages/types/src/user.ts
> Update the resources / types to include has_Image

- .changeset/wise-badgers-cover.md
- packages/clerk-js/src/ui/customizables/__tests__/parseAppearance.test.tsx
- packages/clerk-js/src/ui/customizables/parseAppearance.ts
- packages/clerk-js/src/ui/elements/ApplicationLogo.tsx
- packages/types/src/appearance.ts
> feat(clerk-js,types): Introduce logoLinkUrl prop in appearance

- .changeset/green-rocks-refuse.md
- packages/clerk-js/src/core/resources/UserOrganizationInvitation.ts
- packages/types/src/userOrganizationInvitation.ts
This method will be used in order for a user to accept an Invitation that has been assigned to them
> feat(types,clerk-js): Introduce UserOrganizationInvitation.accept()

- .changeset/strange-owls-behave.md
- packages/clerk-js/src/ui/components/CreateOrganization/CreateOrganizationPage.tsx
- packages/clerk-js/src/ui/components/CreateOrganization/__tests__/CreateOrganization.test.tsx
- packages/clerk-js/src/ui/components/OrganizationSwitcher/OrganizationSwitcherPopover.tsx
- packages/clerk-js/src/ui/components/OrganizationSwitcher/__tests__/OrganizationSwitcher.test.tsx
- packages/clerk-js/src/ui/contexts/ClerkUIComponentsContext.tsx
- packages/clerk-js/src/utils/__tests__/dynamicParamParser.test.ts
- packages/clerk-js/src/utils/dynamicParamParser.ts
- packages/clerk-js/src/utils/index.ts
- packages/types/src/clerk.ts
You can test the changes of this PR in [this app](https://b2b-saas-starter.clerkpreview.com/)
- Url changes when switching between organizations
- after creation of an organization we are navigated to it's profile with the constructed url
> Construct urls based on Organization or User <OrganizationSwitcher/>

- .changeset/orange-tigers-act.md
- package-lock.json
- packages/clerk-js/src/core/resources/UserOrganizationInvitation.ts
- packages/clerk-js/src/ui/contexts/CoreClerkContextWrapper.tsx
- packages/clerk-js/src/ui/contexts/CoreOrganizationContext.tsx
- packages/clerk-js/src/ui/hooks/__tests__/useCoreOrganizationList.test.tsx
- packages/clerk-js/src/ui/utils/test/createFixtures.tsx
- packages/clerk-js/src/utils/pagesToOffset.ts
- packages/react/src/contexts/ClerkContextProvider.tsx
- packages/react/src/contexts/OrganizationContext.tsx
- packages/shared/package.json
- packages/shared/src/hooks/contexts.tsx
- packages/shared/src/hooks/types.ts
- packages/shared/src/hooks/useOrganizationList.tsx
- packages/shared/src/index.ts
- packages/types/src/user.ts
- Creates `UserOrganizationInvitation` and `UserOrganizationInvitationResource`
- Updates useOrganization to return `userInvitations`
- Adds the ability to aggregate the `userInvitations` when fetched from `useOrganization` (Very useful from infinite scrolling)
You might be familiar with `OrganizationInvitation` that already exists in our codebase.
Both `UserOrganizationInvitation` and `OrganizationInvitation` describe the same entity. The former is from the perspective of a user where the later from the perspective of an organization.
```ts
const {
isLoaded,
organizationList, // Same as before
createOrganization, // Same as before
setActive, // Same as before
userInvitations: {
data,
count,
isFetching,
isLoading,
isError,
page,
pageCount,
fetchPage,
fetchNext,
fetchPrevious,
hasNextPage, …
```
> ORG-83 userInvitations in useOrganizationList

- .changeset/mighty-boxes-reply.md
- packages/clerk-js/src/core/resources/Organization.ts
- packages/clerk-js/src/core/resources/OrganizationDomain.test.ts
- packages/clerk-js/src/core/resources/OrganizationDomain.ts
- packages/clerk-js/src/core/resources/UserOrganizationInvitation.ts
- packages/clerk-js/src/core/resources/__snapshots__/Organization.test.ts.snap
- packages/clerk-js/src/core/resources/__snapshots__/OrganizationDomain.test.ts.snap
- packages/clerk-js/src/core/resources/__snapshots__/OrganizationMembership.test.ts.snap
- packages/clerk-js/src/core/resources/internal.ts
- packages/shared/src/hooks/useOrganization.tsx
- packages/types/src/index.ts
- packages/types/src/json.ts
- packages/types/src/organization.ts
- packages/types/src/organizationDomain.ts
This PR:
- Introduces a new resource called OrganizationDomain
- exposes a list of domains of the above type from the useOrganization hook
> 4️⃣ [ORG-61] Introduce OrganizationDomain and return domains from useOrganization

- .changeset/nervous-lizards-repeat.md
- packages/clerk-js/bundlewatch.config.json
- packages/clerk-js/src/core/resources/OrganizationDomain.ts
- packages/clerk-js/src/core/resources/__snapshots__/OrganizationDomain.test.ts.snap
- packages/clerk-js/src/ui/common/CalloutWithAction.tsx
- packages/clerk-js/src/ui/common/index.ts
- packages/clerk-js/src/ui/components/OrganizationProfile/AddDomainPage.tsx
- packages/clerk-js/src/ui/components/OrganizationProfile/CalloutWithAction.tsx
- packages/clerk-js/src/ui/components/OrganizationProfile/DomainList.tsx
- packages/clerk-js/src/ui/components/OrganizationProfile/OrganizationMembers.tsx
- packages/clerk-js/src/ui/components/OrganizationProfile/OrganizationProfileNavbar.tsx
- packages/clerk-js/src/ui/components/OrganizationProfile/OrganizationProfileRoutes.tsx
- packages/clerk-js/src/ui/components/OrganizationProfile/OrganizationSettings.tsx
- packages/clerk-js/src/ui/components/OrganizationProfile/RemoveDomainPage.tsx
- packages/clerk-js/src/ui/components/OrganizationProfile/VerifiedDomainPage.tsx
- packages/clerk-js/src/ui/components/OrganizationProfile/VerifyDomainPage.tsx
- packages/clerk-js/src/ui/components/OrganizationProfile/__tests__/OrganizationMembers.test.tsx
- packages/clerk-js/src/ui/components/OrganizationProfile/__tests__/OrganizationSettings.test.tsx
- packages/clerk-js/src/ui/components/OrganizationProfile/__tests__/utils.ts
- packages/clerk-js/src/ui/elements/BlockWithAction.tsx
- packages/clerk-js/src/ui/elements/index.ts
- packages/clerk-js/src/ui/hooks/index.ts
- packages/clerk-js/src/ui/hooks/useFetch.ts
- packages/localizations/src/en-US.ts
- packages/types/src/appearance.ts
- packages/types/src/localization.ts
- packages/types/src/organizationDomain.ts
**Tests will be added in a following PR**
🚨This PR adds `<2 KB` in the organizationprofile.js chunk 🚨
_This is not by accident_
https://github.com/clerkinc/javascript/assets/19269911/8f70dceb-9dbb-4112-a6fb-0fdb47d3b039
> 5️⃣ <OrganizationProfile/> List, add, edit, remove Domains

- .changeset/orange-taxis-eat.md
- packages/clerk-js/src/core/resources/OrganizationSuggestion.test.ts
- packages/clerk-js/src/core/resources/OrganizationSuggestion.ts
- packages/clerk-js/src/core/resources/User.ts
- packages/clerk-js/src/core/resources/__snapshots__/OrganizationSuggestion.test.ts.snap
- packages/clerk-js/src/core/resources/internal.ts
- packages/shared/src/hooks/useOrganizationList.tsx
- packages/types/src/index.ts
- packages/types/src/json.ts
- packages/types/src/organizationSuggestion.ts
- packages/types/src/user.ts
We introduce a new OrganizationSuggestion resource and the corresponding types, in order to preview user with suggestions of organizations they can join. The available methods for the time being are retrieve() which return a list of organization suggestions of the user and accept() which allows a user to request to join the organization
> feat(types,clerk-js): Introduce OrganizationSuggestion resource and types

- .changeset/thin-moles-obey.md
- packages/clerk-js/src/ui/components/OrganizationProfile/VerifiedDomainPage.tsx
- packages/clerk-js/src/ui/components/OrganizationSwitcher/OrganizationSwitcher.tsx
- packages/clerk-js/src/ui/components/OrganizationSwitcher/OtherOrganizationActions.tsx
- packages/clerk-js/src/ui/components/OrganizationSwitcher/UserInvitationList.tsx
- packages/clerk-js/src/ui/components/OrganizationSwitcher/UserSuggestionList.tsx
- packages/clerk-js/src/ui/elements/OrganizationPreview.tsx
- packages/clerk-js/src/ui/primitives/Button.tsx
- packages/localizations/src/en-US.ts
- packages/types/src/json.ts
- packages/types/src/localization.ts
> feat(clerk-js): Add list of suggestions in OrganizationSwitcher

- .changeset/red-deers-happen.md
- packages/clerk-js/src/ui/components/UserProfile/UsernamePage.tsx
Allow to delete username if optional
> USR-238 fix(clerk-js): Allow to delete username if optional
