.changeset/pink-keys-shake.md, packages/clerk-js/src/ui/components/OrganizationProfile/VerifyDomainPage.tsx
This commit implements the Resend OTP functionality on the Organization Domain page, that tries to send again the email that contains the OTP code in order to complete the verification flow
=> feat(clerk-js): Implement resend OTP functionality for Organization Domain

.changeset/gold-jeans-turn.md, packages/clerk-js/src/core/clerk.ts, packages/clerk-js/src/core/resources/OrganizationMembership.ts, packages/clerk-js/src/core/resources/User.ts, packages/clerk-js/src/ui/components/OrganizationSwitcher/utils.ts, packages/shared/src/hooks/useOrganizationList.tsx, packages/types/src/user.ts
This PR 
- marks as `deprecated` the `Clerk.getOrganizationMemberships` method
- updates the signature of `User.getOrganizationMemberships` method and `OrganizationMembership.retrieve`
This PR aims to support backwards compatibility at the type level but also at runtime by adding a new supported parameter to `OrganizationMembership.retrieve` the `paginated:true`
Examples: 
```ts
// Works as before and does not accept parameters (now marked as deprecated)
const memberships = await clerk.getOrganizationMemberships()
// ^ this will be of type OrganizationMemberships[]
// Works as before and accepts parameters
const memberships = await user.getOrganizationMemberships()
// ^ this will be of type OrganizationMembershipResource[]
const memberships = await …
```
=> feat(clerk-js): Support Paginated response in OrganizationMembership.retrieve & `userMemberships` in useOrganizationList

.changeset/rotten-rules-argue.md, packages/clerk-js/src/core/resources/OrganizationMembershipRequest.ts, packages/clerk-js/src/core/resources/__snapshots__/OrganizationMembershipRequest.test.ts.snap, packages/clerk-js/src/ui/components/OrganizationProfile/InvitedMembersList.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/RequestToJoinList.tsx, packages/clerk-js/src/ui/elements/UserPreview.tsx, packages/clerk-js/src/ui/elements/contexts/CardStateContext.tsx, packages/localizations/src/en-US.ts, packages/types/src/localization.ts, packages/types/src/organizationMembershipRequest.ts
=> feat(clerk-js): Reject a membership request as an organization admin

.changeset/healthy-carrots-turn.md, packages/clerk-js/src/ui/components/OrganizationSwitcher/OrganizationSwitcher.tsx, packages/clerk-js/src/ui/components/OrganizationSwitcher/OrganizationSwitcherTrigger.tsx, packages/clerk-js/src/ui/components/OrganizationSwitcher/__tests__/OrganizationSwitcher.test.tsx, packages/clerk-js/src/ui/customizables/elementDescriptors.ts, packages/clerk-js/src/ui/customizables/index.ts, packages/clerk-js/src/ui/hooks/useDelayedVisibility.ts, packages/clerk-js/src/ui/primitives/NotificationBadge.tsx, packages/clerk-js/src/ui/primitives/index.ts, packages/clerk-js/src/ui/styledSystem/animations.ts, packages/types/src/appearance.ts
This PR implements the below UI
=> Invitation+Suggestion count in OrganizationSwitcherTrigger

.changeset/serious-dragons-provide.md, packages/clerk-js/src/core/clerk.test.ts, packages/clerk-js/src/core/clerk.ts, packages/clerk-js/src/testUtils.ts
'
Ensures we call `this.#touchLastActiveSession()` in `setActive()` when we are in a non-standard browser environment. Practically, this currently applies to react native / expo environments.
As part of adding tests, I also added a small test helper that mocks a "native" runtime environment: `mockNativeRuntime()`. This can wrap any number of `it()` or `describe()` blocks and will ensure that they run as if they are in a non-browser environment.
fixes JS-653
=> fix(clerk-js): Ensure new session is touched when setActive is called from non-standard browser

.changeset/thick-timers-wave.md, packages/clerk-js/jest.config.js, packages/clerk-js/setupJest.ts, packages/clerk-js/src/__tests__/headless.test.ts, packages/clerk-js/webpack.config.js
Updates the `clerk/headless` build configuration to disable chunking. This ensures we don't attempt to load chunks at runtime, causing issues with public path resolution.
fixes JS-689, fixes #1644
=> fix(clerk-js): Disable chunking for clerk headless build

.changeset/little-cobras-wash.md, packages/clerk-js/src/ui/components/OrganizationSwitcher/__tests__/OrganizationSwitcher.test.tsx, packages/localizations/src/en-US.ts
This is the first PR that brings some UI updates to organization switcher.
- It updates the label from "Personal workspace" to "Personal account"
=> feat(clerk-js): Update `personalWorkspace` to display Personal account

.changeset/curly-owls-marry.md, packages/clerk-js/src/ui/common/NotificationCountBadge.tsx, packages/clerk-js/src/ui/common/index.ts, packages/clerk-js/src/ui/components/OrganizationProfile/OrganizationMembers.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/__tests__/OrganizationMembers.test.tsx, packages/clerk-js/src/ui/components/OrganizationSwitcher/OrganizationSwitcherPopover.tsx, packages/clerk-js/src/ui/components/OrganizationSwitcher/OrganizationSwitcherTrigger.tsx, packages/clerk-js/src/ui/components/OrganizationSwitcher/__tests__/OrganizationSwitcher.test.tsx, packages/clerk-js/src/ui/elements/Actions.tsx, packages/clerk-js/src/ui/elements/Tabs.tsx
This PR is an improvement for the notification badge in OrganizationSwitcher
- Include the number of pending requests in the active organization in switcher (for organization admins)
- Add the same number to the "Requests" tab  in OrganizationProfile
https://github.com/clerkinc/javascript/assets/19269911/03e91fdd-2dd2-497d-9baa-96cf3ea3ce42
=> feat(clerk-js): Notify admins for pending requests in OrganizationSwitcher

.changeset/gentle-carpets-clap.md, packages/clerk-js/src/core/clerk.test.ts, packages/clerk-js/src/core/clerk.ts, packages/clerk-js/src/ui/components/SignIn/SignIn.tsx, packages/types/src/clerk.ts
=> feat(clerk-js,types): Handle verification of unverified email on sign-in

.changeset/hot-crabs-applaud.md, packages/clerk-js/src/core/clerk.test.ts, packages/clerk-js/src/core/clerk.ts
This change adds support for redirecting to "factor-one" step during the account transfer flow (from sign-up to sign-in).
https://github.com/clerkinc/javascript/assets/684680/18e0fded-0cbb-4970-875e-1e1fe010c105
=> feat(clerk-js): Add factor-one support for account transfer flow

.changeset/green-snails-tickle.md, packages/shared/src/hooks/clerk-swr.ts, packages/shared/src/hooks/contexts.tsx, packages/shared/src/hooks/useOrganization.tsx, packages/shared/src/hooks/usePagesOrInfinite.ts
This PR fixes a bug where the application would break if the SWR Devtools extention was enabled in the broswer.
See 👉  [SWR Devtool Issue](https://github.com/koba04/swr-devtools/issues/125)
By overriding the window.__SWR_DEVTOOLS_USE__ with a false value before importing swr, enables us to [disable swr from "hinting"](https://github.com/vercel/swr/blob/4d20bff6759d4478380963654a560a1cf9ae7be1/_internal/src/utils/devtools.ts#L12) to swr-devtools which react version to use.
https://github.com/clerkinc/javascript/assets/19269911/ad4cd3f0-51d5-4ea1-abaa-dca0d2a54315
https://github.com/clerkinc/javascript/assets/19269911/8393132b-a56f-41df-a16a-45950609c7bb
=> fix(shared): Force disable swr devtools for organization hooks

.changeset/two-rabbits-chew.md, packages/clerk-js/src/ui/components/OrganizationList/OrganizationListPage.tsx, packages/clerk-js/src/ui/components/OrganizationList/UserMembershipList.tsx, packages/clerk-js/src/ui/components/OrganizationList/shared.tsx
Change sizes and spacing in OrganizationList that results in UI consistency alongside the rest of the components
=> fix(clerk-js): Improve spacing consistency OrganizationList

.changeset/silly-numbers-sell.md, packages/clerk-js/src/ui/components/OrganizationProfile/ActionConfirmationPage.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/OrganizationProfileNavbar.tsx, packages/clerk-js/src/ui/components/UserProfile/ConnectedAccountsPage.tsx, packages/clerk-js/src/ui/components/UserProfile/EmailPage.tsx
=> fix(clerk-js): Missing or broken breadcrumbs

docs/PUBLISH.md
The `clerkJSVersion` prop requires another input then what was shown before. I also removed the note that one can use `!snapshot name` because that functionality doesn't currently exist.
=> chore(repo): Correct `PUBLISH` docs about `clerkJSVersion`

.github/workflows/release-snapshot.yml
This limits the `!snapshot` command to Clerk org members only, preventing malicious 3rd-party users from opening a PR and releasing a `snapshot` test version with unverified code.
=> chore(repo): Only allow snapshot releases for Clerk org members

.changeset/brown-poets-hang.md, packages/nextjs/src/client-boundary/uiComponents.tsx, packages/nextjs/src/index.ts
`<SignInWithMetamaskButton/>` wasn't exported from `@clerk/nextjs` package.
This PR re-exports it's from `@clerk/clerk-react`.
Fixes JS-709
=> fix(nextjs): Export SignInWithMetamaskButton

docs/PUBLISH.md
Github membership needs to be public before publishing a snapshot version. The docs are updated to reflect the new requirement.
=> chore(repo): Update snapshot docs

.changeset/breezy-horses-raise.md, packages/clerk-js/src/ui/customizables/__tests__/parseAppearance.test.tsx
This PR removes dummy `test` text from appearance layout unit tests with valid URLs for improved readbility.
=> chore(clerk-js): Use URLs for appearance layout unit tests for improved readability

.changeset/nice-games-rule.md, packages/backend/src/api/resources/JSON.ts, packages/backend/src/api/resources/Organization.ts
`members_count` was not populated even if users would explicitly ask to be returned.
`clerkClient.organizations.getOrganizationList({ includeMembersCount: true, });`
Turns out the property has never populated in the first place
=> fix(backend): Populate members_count of an Organization

.changeset/lucky-rockets-yawn.md, packages/clerk-js/src/ui/components/OrganizationProfile/ActiveMembersList.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/__tests__/OrganizationMembers.test.tsx
Disable the admin's select menu that changes the role, if there is only one admin left.
Previously this would result in a UI error. This change improves UX
=> fix(clerk-js): Disable role toggle in <OrganizationMembers />, if last admin

docs/PUBLISH.md
@BRKalow pointed out in https://github.com/clerkinc/javascript/pull/1730 that the functionality works so I'm reverting that change there and I'm adding a note on the pitfalls of it.
=> chore(repo): Revert a change to PUBLISH.md

.changeset/shy-jeans-share.md, packages/backend/src/util/IsomorphicRequest.ts, packages/fastify/src/withClerkMiddleware.ts, packages/sdk-node/src/__tests__/middleware.test.ts, packages/sdk-node/src/authenticateRequest.ts
Refactor clerk-sdk-node to build the request origin in order to centralize the way we construct the origin for all of our JS backend packages.
Those changes may make the code more complex or may not provide much value, that's why the we should evaluate if centralizing the origin construction by using a function from the `clerk/backend` package is worth it.
=> fix(clerk-sdk-node): Cleanup clerk-sdk-node request url generation

.changeset/lazy-papayas-vanish.md, packages/backend/src/tokens/jwt/assertions.test.ts, packages/backend/src/tokens/jwt/assertions.ts, packages/backend/src/tokens/jwt/verifyJwt.ts
Split jwt assertions to separate module. This change is an attempt to improve readability and testability of the code.
Tests will be added for the rest of the assertions if this approach is deemed to be worthy.
=> fix(backend): Split jwt assertions to separate module

.changeset/breezy-countries-play.md, packages/clerk-js/src/ui/components/UserProfile/EmailSection.tsx, packages/clerk-js/src/ui/components/UserProfile/PhoneSection.tsx
This bug was introduced when we moved the "unverified" badges from the body of the expandable to the trigger. Previously the "primary" badge always had priority over the "unverified". We decided to display both. 
This PR displays both badges when needed.
=> fix(clerk-js): Correctly display all badges email/phone

.changeset/little-grapes-compete.md, packages/backend/src/tokens/interstitialRule.ts, packages/backend/src/tokens/request.ts, packages/clerk-js/src/core/clerk.ts, packages/clerk-js/src/core/constants.ts, packages/clerk-js/src/utils/getClerkQueryParam.ts
This is safe to remove, as the code that was adding this query param has been removed for at least 6 releases.
To give more context `__clerk_referrer_primary` was introduced in order to identify when a primary was redirected back to a satellite app and interstitial was triggered. This was later replaced by using `__clerk_synced` and the `isInterstitial` parameter from the `load` method.
=> chore(clerk-js,backend): Remove deprecated `__clerk_referrer_primary`

.changeset/shiny-meals-marry.md, packages/backend/src/tokens/jwt/assertions.test.ts
The tests were failing from time to time due to differences in the dates in the error messages asserted in the assertions test files. The difference was 1 second.
Example of failed run: https://github.com/clerkinc/javascript/actions/runs/6260901259/job/16999859243?pr=1743
=> fix(backend): Use fakeTimers() in tests to resolve test flakiness

.changeset/seven-rivers-greet.md, packages/shared/src/utils/deprecated.test.ts, packages/shared/src/utils/deprecated.ts, packages/shared/src/utils/index.ts
This PR introduces `deprecated` and `deprecatedProperty` helpers that will be used to warn users when using a marked (already marked using JSDoc) class property/method or function by showing a console WARNING.
The warnings will be shown EACH the property is being accessed on the method is being called to urge the users to remove the deprecated usages.
=> feat(shared): Introduce deprecated/deprecatedProperty for deprecation warnings

packages/remix/package.json, packages/remix/src/errors.ts
We will cater the deprecated properties inside `@clerk/backend`, so we added a npm run command to the Remix package (for constancy) and we updated an option in an example of an error message.
=> chore(remix): Apply deprecation warnings for remix

.changeset/nervous-ducks-battle.md, package-lock.json, packages/fastify/package.json, packages/fastify/src/constants.ts
Warn about deprecations of the following environment variables in Clerk Fastify plugin:
- CLERK_API_KEY
- CLERK_FRONTEND_API
=> chore(fastify): Apply deprecation warnings for fastify

.changeset/stupid-tips-destroy.md, package-lock.json, packages/expo/package.json
From the https://github.com/clerkinc/javascript/issues/1608, I've found that the `1.3.0`
`react-native-url-polyfill` did not had official support for Expo Web.
The error was that because we rely on `react-native-url-polyfill/auto`, the would also apply the polyfill if executed on the web, which is not required as the `URL` has support for all modern browsers and there is no need to pollyfill it.
This PR upgrades the version of `react-native-url-polyfill` from `1.3.0` to `2.0.0` to fix the error.
Fixes https://github.com/clerkinc/javascript/pull/1680
=> chore(clerk-expo): Upgrade react-native-url-polyfill from 1.3.0 to 2.0.0

.github/workflows/quality.yml
As per the [Github docs](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue), in order to enable merge queues we need to make sure that our quality checks run when a PR is added to the queue.
This PR updates the quality.yml workflow.
=> chore(repo): Enable merge queues

.changeset/five-swans-dream.md, packages/clerk-js/src/ui/hooks/useLocalStorage.ts, packages/shared/src/utils/localStorageBroadcastChannel.ts
Check if `window` is `undefined` and then have fallback cases for that. Since the hook seems to be modeled after https://usehooks-ts.com/react-hook/use-local-storage I applied its `window` checks that it has.
Fixes https://github.com/clerkinc/javascript/issues/1620
=> fix(clerk-js,shared): Safer usage of localStorage

.changeset/fast-books-kiss.md, .changeset/three-carrots-remain.md, packages/clerk-js/src/core/resources/Organization.ts, packages/clerk-js/src/core/resources/__snapshots__/Organization.test.ts.snap, packages/clerk-js/src/core/resources/__snapshots__/OrganizationMembership.test.ts.snap, packages/clerk-js/src/ui/components/OrganizationProfile/InvitedMembersList.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/__tests__/OrganizationMembers.test.tsx, packages/shared/src/hooks/useOrganization.tsx, packages/types/src/organization.ts
This PR
- deprecates `getPendingInvitations` which did not allow for filtering by status
- introduces `getInvitations` which support the new pagination params and filtering
- deprecates `invitationList` as params and return value of useOrganization
- introduces `invitations` which support paginated responces, build-in pagination, and infinite loading.
It was the missing part that brings our organization hooks in harmony between their APIs
=> New `getInvitations` in clerk-js  and `invitations` from useOrganization

.github/ISSUE_TEMPLATE/BUG_REPORT.yml
We'd like to avoid duplicate support cases and have seen several of these recently - this PR adds an extra checkbox to confirm the issue opener hasn't already reached out to support via another channel.
=> chore: Add "I haven't reached out to support already" to issue template

.changeset/silver-onions-look.md, packages/shared/src/utils/deprecated.test.ts, packages/shared/src/utils/deprecated.ts, packages/shared/src/utils/index.ts, packages/shared/src/utils/runtimeEnvironment.ts
Introduce 2 helpers (`isTestEnvironment()` / `isProductionEnvironment()`) in `@clerk/shared` package to be used for identifying the current environment and change the deprecations warnings condition from visible only on the development environment to hidden only on production and test environment.
After this change, the deprecation warning will be visible to applications without `process.env.NODE_ENV` defined.
=> fix(shared): Hide warnings on test/production environments

.changeset/smart-poems-film.md, packages/react/package.cjs.json, packages/react/package.esm.json, packages/react/package.json, packages/react/tsup.config.ts
A customer is using webpack Module federation and shared this error with us:
```shell
"WARNING in shared module @clerk/clerk-react -> C:\path\to\project\node_modules@clerk\clerk-react\dist\esm\index.js No version specified and unable to automatically determine one. No version in description file (usually package.json). Add version to description file C:\path\to\project\node_modules@clerk\clerk-react\dist\esm\package.json, or manually specify version in shared config."
```
And yes, previously the nested `package.json` files inside `dist/cjs` and `dist/esm` only had `sideEffects` in there. But we don't need those files because `sideEffects` can also just be in the top-level package.json with the paths to it.
=> fix(clerk-react): Remove nested `package.json` files

.changeset/giant-needles-exercise.md, packages/shared/src/utils/runtimeEnvironment.ts
Trying to support vite `import.meta.env.DEV` to detect the environment as fallback is causing an Error:
```
Uncaught SyntaxError: Cannot use 'import.meta' outside a module ...
```
when it's being imported as script tag or used with CommonJS.
We will drop the support for now since vite supports `process.env.NODE_ENV`.
ref: https://vitejs.dev/guide/env-and-mode.html
=> fix(shared): Fix SyntaxError on non-module imports by dropping support for import.meta used in vite

.changeset/three-tigers-tell.md, packages/shared/src/hooks/clerk-swr.ts, packages/shared/src/hooks/contexts.tsx, packages/shared/src/hooks/useOrganization.tsx, packages/shared/src/hooks/usePagesOrInfinite.ts
Our patch was preventing swr-devtools from running with the react version the clerkjs components use, causing the hosting app to break.
This has now been [patched from the maintainer of swr-devtools ](https://github.com/koba04/swr-devtools/pull/126) and in a setup where both patches run the devtools will alway be disabled.
This PR removes our patch and allows swr-devtools to run only for the hosting app (not hotloaded clerkjs components)
=> chore(shared): Remove patch for swr-devtools

.changeset/spicy-toys-change.md, packages/nextjs/src/server/clerkClient.ts, packages/nextjs/src/server/constants.ts, packages/nextjs/src/server/withClerkMiddleware.ts, packages/nextjs/src/ssr/withServerSideAuth.ts, turbo.json
** REVIEW IT PER COMMIT **
Warn about deprecations of the following in Clerk Nextjs:
- `withClerkMiddleware`
- `withServerSideAuth`
- `CLERK_JS_VERSION` environment variable
- `CLERK_API_KEY` environment variable
- `NEXT_PUBLIC_FRONTEND_API` environment variable
=> chore(nextjs): Apply deprecation warnings

.changeset/four-brooms-live.md, packages/clerk-js/src/ui/components/OrganizationProfile/InviteMembersForm.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/__tests__/InviteMembersPage.test.tsx, packages/clerk-js/src/ui/elements/Alert.tsx, packages/localizations/src/en-US.ts
This PR improves the localized message and also the implementation of the constructed message.
=> fix(clerk-js): Improve error message during Organization invitation

.changeset/large-baboons-hope.md, packages/clerk-js/src/ui/elements/ArrowBlockButton.tsx
Added some padding when the `ArrowBlockButton` is in loading state and has a left icon to prevent layout shift.
fixes JS-723
https://github.com/clerkinc/javascript/assets/6823226/d801173e-757c-42d8-9d6b-cfefaa357723
https://github.com/clerkinc/javascript/assets/6823226/064d9f7f-26ce-4920-a04f-3176d2e03041
=> fix(clerk-js): Added padding for ArrowBlockButton to prevent layout shift

.changeset/fresh-papayas-cheat.md, packages/clerk-js/src/core/clerk.ts, packages/clerk-js/src/core/constants.ts, packages/clerk-js/src/ui/components/SignIn/SignInStart.tsx, packages/clerk-js/src/ui/components/SignIn/__tests__/SignInStart.test.tsx, packages/clerk-js/src/ui/components/SignUp/SignUpContinue.tsx, packages/clerk-js/src/ui/components/SignUp/SignUpStart.tsx, packages/clerk-js/src/ui/components/SignUp/__tests__/SignUpStart.test.tsx, packages/clerk-js/src/ui/contexts/ClerkUIComponentsContext.tsx, packages/clerk-js/src/ui/elements/PhoneInput/PhoneInput.tsx, packages/clerk-js/src/utils/__tests__/url.test.ts, packages/clerk-js/src/utils/url.ts, packages/react/src/components/controlComponents.tsx, packages/react/src/isomorphicClerk.ts, packages/react/src/types.ts, packages/types/src/clerk.ts
This PR implements the functionality of prefilling specific input fields of `<SignIn/>` and `<SignUp/>` with the `initialValues` prop. 
The switching mechanism in `<SignIn/>` is smart, meaning that if you switch from email to phone, the phone number will be prefilled with the `initialValues.phoneNumber` value initially.
https://github.com/clerkinc/javascript/assets/73396808/3503dff3-ac36-4cbd-bf0e-9d0a06e36766
https://github.com/clerkinc/javascript/assets/73396808/1f437e46-b903-416c-a2b8-ff9644f448de
https://github.com/clerkinc/javascript/assets/73396808/5ebabcc7-0d02-4f07-be47-63f3e1744a29
=> Pre fill form fields in <SignIn/> and <SignUp/>

.changeset/thick-rings-complain.md, packages/backend/src/api/endpoints/OrganizationApi.ts
Introduce a new getOrganizationInvitationList() method on the Organization resource, which you can use in order to list the invitations. The new method supports filtering by status and also the default paginated parameters, limit and offset
We also mark as deprecated the old getPendingOrganizationInvitationList, which was used to only list the pending organization invitations
=> feat(backend): Introduce a new getOrganizationInvitationList() method

.changeset/forty-crews-fetch.md, .changeset/four-chairs-lay.md, packages/clerk-js/src/core/clerk.ts, packages/clerk-js/src/core/resources/DisplayConfig.ts, packages/clerk-js/src/core/resources/ExternalAccount.ts, packages/clerk-js/src/core/resources/Organization.ts, packages/clerk-js/src/core/resources/OrganizationMembership.ts, packages/clerk-js/src/core/resources/OrganizationMembershipRequest.ts, packages/clerk-js/src/core/resources/User.ts, packages/clerk-js/src/core/resources/__snapshots__/Organization.test.ts.snap, packages/clerk-js/src/core/resources/__snapshots__/OrganizationMembership.test.ts.snap, packages/clerk-js/src/ui/common/constants.ts
**Review it per commit**
Deprecation warnings added in `@clerk/clerk-js`:
-  `Organization.create()` using string parameter
-  `Organization.retrieve()` `limit` & `offset`
-  `Clerk.getOrganizationMemberships()`
- `svgUrl`
- `avatarUrl`/`logoUrl`/`faviconUrl`/`profileImageUrl`
Notes: We cannot show deprecation warnings in console for deprecated type properties (eg `UserJSON.profile_image_url`)
TODO:
=> chore(clerk-js): Apply deprecation warnings

.changeset/tender-cameras-yawn.md, packages/clerk-js/src/core/clerk.ts
Since we are deprecation the `setSession` hook from `@clerk/clerk-react` and there is a `@experimental` directive on `Clerk.setActive` which indicates that it's gonna replace the `Clerk.setSession`, I deprecated the `Clerk.setSession`.
=> Deprecate clerk set session

.changeset/strange-lamps-knock.md, packages/clerk-js/src/ui/common/SSOCallback.tsx, packages/clerk-js/src/ui/components/UserProfile/ConnectedAccountsSection.tsx, packages/clerk-js/src/ui/components/UserProfile/EnterpriseAccountsSection.tsx, packages/clerk-js/src/ui/hooks/useEnabledThirdPartyProviders.tsx, packages/clerk-js/src/ui/utils/test/fixtureHelpers.ts, packages/gatsby-plugin-clerk/src/GatsbyClerkProvider.tsx, packages/react/src/isomorphicClerk.ts
Replace subpath imports with top level ones to avoid breaking changes upon restructuring our SDKs.
=> fix(clerk-js, clerk-react,gatsby-clerk-plugin): Cleanup subpath imports

.changeset/cyan-pots-invite.md, packages/clerk-js/src/ui/elements/FormControl.tsx, packages/localizations/src/de-DE.ts, packages/localizations/src/en-US.ts, packages/types/src/localization.ts
Enables you to translate the tooltip hint while creating an organization
Fixes https://github.com/clerkinc/javascript/issues/1795
Fixes ORG-239
=> fix(clerk-js,localizations,types): Add `formFieldHintText__slug` key

.changeset/friendly-gorillas-smash.md, packages/types/src/json.ts, packages/types/src/user.ts
There is no reference in our FAPI responses (`/v1/me`) about `password` field. 
The password is only used as part of the `UpdateUserParams` type, so i moved it from UserJSON to that type.
Also there is no reference in our Frontend API docs: https://reference.clerk.dev/reference/frontend-api-reference/users/user
=> chore(types): Drop `password` property from UserJSON

.changeset/chilled-parrots-pump.md, packages/clerk-js/src/ui/components/OrganizationSwitcher/OrganizationSwitcherPopover.tsx, packages/clerk-js/src/ui/components/UserButton/useMultisessionActions.tsx, packages/types/src/clerk.ts
This PR 
-  introduces `organizatinonProfileProps` as prop of `<OrganizationSwitcher />`. This allows for the customization of OrganizationProfile when it is opened through the switcher.
- introduces `appearance` in `userProfileProps` of `<UserButton/>`.
- deprecates the usage of `appearance.userProfile` of `<UserButton/>`.
After these changes a developer can customize the Profiles like this:
```tsx
<OrganizationSwitcher
organizationProfileProps={{
appearance: {
elements: {
formButtonPrimary: {
background: 'black',
},
},
},
}}
/>
```
```tsx
<UserButton
userProfileProps={{
appearance: {
elements: {
formButtonPrimary: {
background: 'orange',
},
},
},
}}
/>
```
```tsx
<UserButton
appearance={{
userProfile: {
elements: {
formButtonPrimary: {
background: 'black',
},
},
},
}}
/>
```
Fixes #1534 …
=> feat(clerk-js): Allow customization of OrganizationProfile through OrganizationSwitcher

.changeset/friendly-pillows-cough.md, packages/backend/src/constants.ts, packages/backend/src/tokens/request.test.ts, packages/backend/src/tokens/request.ts, packages/backend/src/util/request.test.ts, packages/fastify/src/__snapshots__/constants.test.ts.snap
Initial implementation and discussion can be found in: https://github.com/clerkinc/javascript/pull/1547
This PR is meant to add some tests and help with merging the commit by reducing the back and forwards caused by the PR of the contributor being out of sync with main.
=> fix(backend): Fix issue with Cloudfront forwarded protocol

.changeset/weak-geckos-cheer.md, packages/clerk-js/src/ui/components/OrganizationProfile/__tests__/LeaveOrganizationPage.test.tsx
Removes `.skip` from the test. And adds one more simple case.
=> test(clerk-js): Allow for tests in LeaveOrganizationPage to run

.changeset/shiny-flowers-draw.md, packages/clerk-js/src/ui/primitives/Table.tsx, packages/clerk-js/src/ui/primitives/Th.tsx
Fixes a UI bug on Safari, that was causing the border of tables to be displayed incorrectly.
=> fix(clerk-js): Table UI issue with borders in Safari

.changeset/cool-planes-shake.md, packages/backend/src/tokens/keys.test.ts, packages/backend/src/tokens/keys.ts
When the `jwk-remote-missing` error is thrown be previously printed out this:
```shell
Unable to find a signing key in JWKS that matches the kid='whatever' of the provided session token. Please make sure that the __session cookie or the HTTP authorization header contain a Clerk-generated session JWT.
```
This PR improves this message by appending the available keys:
```shell
Unable to find a signing key in JWKS that matches the kid='whatever' of the provided session token. Please make sure that the __session cookie or the HTTP authorization header contain a Clerk-generated session JWT. The following kid are available: foobar, local
```
This way a person and/or customer support can compare the kid with the available ones on the JWKS endpoint. Might help with debugging since you know what …
=> fix(backend): Add available kid to jwk-remote-missing error

.changeset/light-spoons-poke.md, packages/backend/src/tokens/request.ts, packages/types/src/clerk.ts
We can safely remove the experimental tags, as the feature has gone through 2 iterations already and we consider it stable.
// TODO: create one once this is approved
=> chore(types,backend): Remove experimental jsdoc tags from multi-domain types

.changeset/curly-scissors-buy.md, packages/clerk-js/src/core/resources/Error.ts, packages/clerk-js/src/core/resources/SignUp.ts, packages/clerk-js/src/ui/elements/contexts/CardStateContext.tsx, packages/clerk-js/src/ui/localization/makeLocalizable.tsx, packages/clerk-js/src/ui/utils/errorHandler.ts, packages/localizations/src/en-US.ts, packages/shared/src/errors/Error.ts, packages/types/src/api.ts, packages/types/src/localization.ts
With the introduction of ClerkRuntimeError class, we can localize error messages and display them in ClerkJS components. This functionality existed for FAPI errors, and we are now adding support for runtime errors.
Displays an error message caused when lazy loading a 3rd party library. In this case, the sign up process cannot continue and we need to provided the end user with some feedback.
=> feat(clerk-js,shared,types): Add ClerkRuntimeError class

.changeset/dull-gifts-yawn.md, packages/react/package.json, packages/remix/package.json, packages/shared/package.json
The [TypeScript docs](https://www.typescriptlang.org/docs/handbook/esm-node.html#packagejson-exports-imports-and-self-referencing) recommends so, but it's also because the "exports" field is order-based.
For example, a scenario where both the "types" and "import" condition could be active, "types" should be first so that it matches and returns a .d.ts file, rather than a .js file from the "import" condition.
=> fix(clerk-react,remix,shared): Make `exports.types` the first key in `exports`

.changeset/stupid-jeans-flash.md, packages/nextjs/src/app-beta/ClerkProvider.tsx, packages/nextjs/src/app-beta/auth.ts, packages/nextjs/src/app-beta/clerkClient.ts, packages/nextjs/src/app-beta/client/ClerkProvider.tsx, packages/nextjs/src/app-beta/client/clerk-react.ts, packages/nextjs/src/app-beta/client/ui-components.tsx, packages/nextjs/src/app-beta/control-components.tsx, packages/nextjs/src/app-beta/currentUser.ts, packages/nextjs/src/app-router/server/currentUser.ts
The implementation in `app-beta` was an attempt to support the NextJS `app-router` early on. Since the `app-router` release is stable we will deprecate the `@clerk/nextjs/app-beta` subpath export and suggest using the stable `@clerk/nextjs` exports instead.
In this PR the following hacks were applied to add JSDocs and console warnings deprecations:
- we could not add a single deprecation warning in the `app-beta/index.ts` because it did not work so `deprecated` was added in each file
- Replaced import from `@clerk/clerk-react` with module to show deprecation warning (see: packages/nextjs/src/app-beta/client/clerk-react.ts)
- Use import with aliases for re-exported modules of `@clerk/clerk-react` to add JSDoc deprecations only for the exports from the `app-beta`
Since the whole folder …
=> chore(nextjs): Add deprecation warning for app-beta subpath export

.changeset/empty-donuts-walk.md, packages/clerk-js/src/core/resources/Error.ts, packages/clerk-js/src/core/resources/SignUp.ts, packages/shared/src/errors/Error.ts
This PR reverts the unintended removal of `clerkError`. When missing it would cause the `isClerkAPIResponseError` return a wrong value
=> fix(shared): Removal of `clerkError` property

.changeset/moody-coats-serve.md, packages/backend/src/api/request.ts
Removes a deprecation warning that I believe is logging more than intended. This is not actionable when reported through our SDKs.
=> chore(backend): Remove noisy deprecation warning

.changeset/loud-foxes-love.md, .changeset/proud-dolls-yawn.md, packages/clerk-js/src/core/resources/OrganizationMembership.ts, packages/clerk-js/src/core/resources/Session.test.ts, packages/clerk-js/src/core/resources/Session.ts, packages/clerk-js/src/core/resources/__snapshots__/OrganizationMembership.test.ts.snap, packages/clerk-js/src/core/test/fixtures.ts, packages/clerk-js/src/ui/common/Gate.tsx, packages/clerk-js/src/ui/common/index.ts, packages/clerk-js/src/ui/hooks/useFetch.ts, packages/types/src/json.ts, packages/types/src/organizationMembership.ts, packages/types/src/session.ts
This PR
- Introduces a new method `isAuthorized` in the `Session` class.  Returns a promise (future proofing) and checks whether the active user is allowed to perform an action based on the passed (required)  permission and the ones attached to the membership.
- Introduces an internal Gate component (supporting hook and HOC) which enables us to conditionally render parts of our components based on a users permissions. (it will replace all `isAdmin` checks)
=> Introduce internal Gate component

.changeset/shy-dolls-serve.md, packages/clerk-js/src/ui/components/UserProfile/MfaPhoneCodePage.tsx
Set the card to the `idle` state after success or error.
=> fix(clerk-js): Correctly set idle card state on add mfa error

.changeset/polite-elephants-travel.md, packages/clerk-js/headless/index.d.ts
Users reported types missing on this issue #1847
=> fix(clerk-js): Missing types when importing clerk-js headless

.changeset/polite-rats-care.md, packages/backend/src/tokens/request.test.ts, packages/backend/src/tokens/request.ts, packages/clerk-js/src/core/clerk.ts, packages/clerk-js/src/core/errors.ts
=> feat(clerk-js,backend): Throw error if signInUrl is on same origin as a satellite app

.changeset/honest-countries-repair.md, packages/clerk-js/src/ui/common/InfiniteListSpinner.tsx, packages/clerk-js/src/ui/components/OrganizationList/shared.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/DomainList.tsx, packages/clerk-js/src/ui/elements/Actions.tsx, packages/clerk-js/src/ui/elements/ArrowBlockButton.tsx, packages/clerk-js/src/ui/elements/SocialButtons.tsx, packages/clerk-js/src/ui/primitives/Spinner.tsx
This PR fixes layout shift that is happening when Social block button is in loading state.
https://github.com/clerkinc/javascript/assets/6823226/0334d15c-7228-4f70-9f79-c024c1cf0a94
https://github.com/clerkinc/javascript/assets/6823226/78d402a6-cb83-4bb5-a733-2a493adb0a0a
Fixes JS-792
=> fix(clerk-js): Fix layout shift for Social block buttons

.changeset/serious-zebras-sip.md, packages/backend/src/api/resources/Enums.ts, packages/clerk-js/src/ui/utils/test/fixtures.ts, packages/types/src/oauth.ts
LinkedIn has changed the OAuth flow by replacing it with OpenID Connect. We have already added support for this in the backend.
=> feat(backend,clerk-js,types): Support the new LinkedIn OAuth Provider

.changeset/loud-mugs-notice.md, packages/localizations/src/he-IL.ts
=> add missing types hebrew localization

.changeset/tasty-toes-pump.md, packages/backend/src/tokens/factory.ts, packages/sdk-node/src/authenticateRequest.ts, packages/sdk-node/src/utils.ts
Avoid **always** showing `frontendApi` and `apiKey` on `@clerk/clerk-sdk-node`!
=> Fix noisy deprecations sdk node

.changeset/seven-shrimps-train.md, packages/sdk-node/src/clerkClient.ts, playground/cra-js/package.json, playground/express/package.json, playground/express/src/routes/private.ts, playground/fastify/package.json, playground/remix-cf-pages/package.json, playground/vite-react-ts/package.json
The `sdk-node` package is extending the backend `Clerk` with some extra methods. To do this, we expose a different `Clerk` from the `sdk-node` that returns the `clerkClient` instance of backend with some extra methods.
To add those extra methods to the return value we currently destruct the `clerkClient` to a new object and add the extra methods. By destructing the `clerkClient`, all it's methods and properties are being accessed, causing the `__unstable_options` deprecation warning to trigger and show the warning every time in applications using the `sdk-node` package.
To resolve this, we introduced an `ExtendedClerk` type as the return value of the sdk-node `Clerk` and changed the destructing to `Object.assign(clerkClient, ...extra...)`.
Warning :
```
DEPRECATION WARNING: …
```
=> chore(clerk-sdk-node): Drop noisy deprecation of unstable_options in sdk-node

.changeset/large-rockets-return.md, packages/clerk-js/src/ui/components/SignIn/SignInStart.tsx
Start with the phone input if the only sign in initial value is the phone number.
=> feat(clerk-js): Autoswitch to phone input if the only sign in initial value is the phone number

.changeset/afraid-bobcats-mate.md, .changeset/ten-wolves-cry.md, packages/clerk-js/src/ui/components/OrganizationSwitcher/OrganizationSwitcher.tsx, packages/clerk-js/src/ui/components/OrganizationSwitcher/OrganizationSwitcherPopover.tsx, packages/clerk-js/src/ui/components/OrganizationSwitcher/OrganizationSwitcherTrigger.tsx, packages/clerk-js/src/ui/components/OrganizationSwitcher/OtherOrganizationActions.tsx, packages/clerk-js/src/ui/components/OrganizationSwitcher/UserInvitationSuggestionList.tsx, packages/clerk-js/src/ui/components/OrganizationSwitcher/UserMembershipList.tsx, packages/clerk-js/src/ui/components/OrganizationSwitcher/__tests__/OrganizationSwitcher.test.tsx, packages/clerk-js/src/ui/components/UserButton/UserButton.tsx, packages/clerk-js/src/ui/components/UserButton/UserButtonPopover.tsx, packages/clerk-js/src/ui/components/UserButton/UserButtonTrigger.tsx, packages/clerk-js/src/ui/components/UserButton/__tests__/UserButton.test.tsx, packages/clerk-js/src/ui/elements/Actions.tsx, packages/clerk-js/src/ui/elements/PoweredByClerk.tsx
This is an effort to improve the underlying semantics of UserButton and OrganizationSwitcher and provide a better accessibility experience. 
In order to come up with this changes i followed the implementation of similar components created with 
- [React aria spectrum](https://react-spectrum.adobe.com/react-aria/)
- Shadcn & Radix
- Vercel's team switcher and user button
Tested with 
- Lighthouse
- [WAVE](https://wave.webaim.org/)
=> chore(clerk-js): Improve accessibility in UserButton and OrganizationSwitcher

.changeset/unlucky-carrots-exist.md, packages/clerk-js/src/core/clerk.test.ts, packages/clerk-js/src/core/clerk.ts, packages/clerk-js/src/core/resources/Organization.ts, packages/clerk-js/src/ui/components/OrganizationList/UserInvitationList.tsx, packages/clerk-js/src/ui/components/OrganizationList/__tests__/OrganizationList.test.tsx, packages/react/src/isomorphicClerk.ts, packages/types/src/clerk.ts
This PR fixes 2 methods that seems to be flawed.
https://github.com/clerkinc/javascript/blob/214f658cf79983b8b44ae3228b0500d88e215345/packages/clerk-js/src/core/resources/Organization.ts#L325
https://github.com/clerkinc/javascript/blob/214f658cf79983b8b44ae3228b0500d88e215345/packages/clerk-js/src/core/clerk.ts#L1086
To provide you with more context, these 2 methods rely on endpoints that resolve with paginated data and the iterate through them and filter the array based on an organizatinoID. This concept is flawed, as there is great chance that the organization id you are looking for, might not be part of the first page of the results.
=> chore(clerk-js): Fix broken Organization methods

.changeset/metal-lizards-build.md, packages/clerk-js/src/ui/elements/CodeControl.tsx
=> fix(clerk-js): Enforce LTR direction in code inputs

.changeset/witty-boats-joke.md, packages/clerk-js/src/ui/common/Gate.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/ActiveMembersList.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/OrganizationMembers.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/OrganizationMembersTabInvitations.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/OrganizationMembersTabRequests.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/__tests__/OrganizationMembers.test.tsx
This PR replaces the role based check with permission based checks inside the OrganizationMembers component
=> feat(clerk-js): Use Gate in OrganizationMembers

.changeset/tender-planets-explain.md, packages/clerk-js/src/ui/components/OrganizationProfile/DomainList.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/OrganizationProfileRoutes.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/OrganizationSettings.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/__tests__/OrganizationMembers.test.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/__tests__/OrganizationSettings.test.tsx
This PR replaces the role based check with permission based checks inside the OrganizationSettings component
=> feat(clerk-js): Use Gate in OrganizationSettings

.changeset/shy-seahorses-begin.md, packages/clerk-js/src/ui/components/OrganizationProfile/__tests__/OrganizationMembers.test.tsx, packages/clerk-js/src/ui/components/OrganizationSwitcher/OrganizationSwitcherPopover.tsx, packages/clerk-js/src/ui/components/OrganizationSwitcher/OrganizationSwitcherTrigger.tsx, packages/clerk-js/src/ui/components/OrganizationSwitcher/__tests__/OrganizationSwitcher.test.tsx
This PR replaces role based check with permission based checks inside the OrganizationSwitcher component.
=> feat(clerk-js): Use Gate in OrganizationSwitcher

.changeset/itchy-olives-pay.md, packages/shared/src/utils/deprecated.test.ts, packages/shared/src/utils/deprecated.ts
Add `Clerk` prefix in deprecation warnings
=> fix(shared): Add Clerk prefix in deprecation warnings

.changeset/yellow-pumpkins-buy.md, packages/clerk-js/src/ui/components/OrganizationProfile/InviteMembersForm.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/__tests__/InviteMembersPage.test.tsx, packages/shared/src/errors/Error.ts, packages/types/src/api.ts, packages/types/src/json.ts
In invite members screen of the <OrganizationProfile /> component, consume any invalid email addresses as they are returned in the API error and remove them from the input automatically.
https://github.com/clerkinc/javascript/assets/22435234/e81e36b4-813f-4ab8-b29b-5df9689ce44a
https://github.com/clerkinc/javascript/assets/22435234/5f343ea0-9c63-4592-9e8f-8e46a55bcf0c
=> feat(clerk-js,shared,types): Remove invalid email addresses from input for Organization Invitation

.changeset/quiet-points-applaud.md, packages/clerk-js/src/ui/components/SignUp/SignUp.tsx, packages/clerk-js/src/ui/components/SignUp/SignUpContinue.tsx
By adding these two new routes, we can navigate back to the `continue` step when needed, instead of going back to the start of the sign up flow.
=> fix(clerk-js): Correctly navigate to the continue route if needed during verification

.changeset/clean-bears-fold.md, packages/clerk-js/src/ui/components/OrganizationProfile/MemberListTable.tsx, packages/clerk-js/src/ui/customizables/elementDescriptors.ts, packages/clerk-js/src/ui/elements/Pagination.tsx, packages/themes/src/createTheme.ts, packages/types/src/appearance.ts
Add missing appearance keys for Pagination text and buttons and Table head.
=> feat(clerk-js,types): Add appearance keys for pagination and table head

.changeset/wild-moons-develop.md, packages/clerk-js/src/core/clerk.ts, packages/clerk-js/src/core/resources/SignUp.ts, packages/clerk-js/src/utils/retrieveCaptchaInfo.ts, packages/types/src/clerk.ts
This PR deprecates the usage of the experimental captcha getter from Clerk singleton. We still need to retrieve this information for the feature to continue to work, so I have introduced a new util function `retrieveCaptchaInfo`
=> chore(clerk-js): Deprecate experimental captcha from Clerk singleton

.changeset/wise-spiders-hammer.md, packages/clerk-js/src/core/clerk.ts, packages/clerk-js/src/utils/__tests__/url.test.ts, packages/clerk-js/src/utils/url.ts
When calling `Clerk.redirectToSignIn/Up()`, the initial values query params were being added as normal query params, instead of being appended after the hash. This means that they were not being picked up in a hash routing environment. This PR addresses that issue and appends them the same way as the redirect urls.
=> fix(clerk-js): Append initial values query params after hash

.changeset/pretty-frogs-turn.md, packages/clerk-js/src/core/resources/Organization.ts, packages/clerk-js/src/core/resources/OrganizationMembership.ts
Previously the deprecation warnings will be used when limit or offset was not used.
=> fix(clerk-js): Properly show the deprecation warnings for usage of limit and offset

.changeset/selfish-pens-laugh.md, packages/nextjs/src/server/errors.ts
For NextJS 13 application, if the `/src` directory is used then the middleware file needs to be nested under it, otherwise the middleware will not run.
This is a very common user error - this commit updates the error message to list moving middleware under /src as a potential fix.
Fixes SDK-818
=> fix(nextjs): Warn about misplaced middleware file when using auth or getAuth

.changeset/olive-pants-hide.md, packages/clerk-js/src/ui/components/SignIn/SignInFactorOnePasswordCard.tsx
This PR adds `formFieldInputPlaceholder__password` to the placeholder of the password input in the `<SignInFactorOnePasswordCard/>` component.
=> fix(clerk-js): Add localization for password input in SignInFactorOnePasswordCard component

.changeset/shiny-experts-notice.md, packages/clerk-js/src/ui/components/OrganizationProfile/InviteMembersForm.tsx, packages/clerk-js/src/ui/elements/contexts/CardStateContext.tsx
This PR removes the custom Alert from invitation page and displays it as a global error instead (at the top of the component).
https://github.com/clerkinc/javascript/assets/19269911/d1d581f1-f62c-42f2-b211-b1b42ebf029e
https://github.com/clerkinc/javascript/assets/19269911/f558b871-9964-4a9a-9999-135eaaa0938e
=> chore(clerk-js): Remove custom Alert from invitation page and display error as global

.changeset/hot-shoes-roll.md, packages/clerk-js/src/ui/components/CreateOrganization/CreateOrganizationForm.tsx
In this pr we disable the form of `CreateOrganizationForm` when avatar has been selected but organization name is empty in order to have the same experience when no avatar has been selected
https://github.com/clerkinc/javascript/assets/14893769/ff97cb63-acea-4427-980c-cd083e21f8e0
https://github.com/clerkinc/javascript/assets/14893769/dbb6b000-982b-4fd8-a06f-c99b6518d3ac
=> chore(clerk-js): Keep CreateOrganizationForm disabled if avatar has been uploaded and org name is empty

.github/workflows/release-prod.yml
The PR https://github.com/clerkinc/javascript/pull/1891 added `permissions` to the release workflow - and apparently they are not additive.
So this PR looks at https://github.com/clerkinc/javascript/actions/runs/6558834152/job/17813206786#step:1:16 and implements the needed stuff from it. (https://github.com/changesets/action/issues/179#issuecomment-1139116421)
=> chore(repo): Fix release workflow permissions

.changeset/pretty-planes-kick.md, packages/clerk-js/src/core/resources/DisplayConfig.ts, packages/clerk-js/src/ui/utils/test/fixtures.ts, packages/types/src/displayConfig.ts
We are dropping the `experimental_force_oauth_first` & `experimental__forceOauthFirst` from the `DisplayConfig` and `DisplayConfigJSON`. The feature that those 2 were introduced for, is not used anymore, so we will drop those 2 and create an internal ticket to support that use case as part of a more generic solution / feature.
=> chore(clerk-js,types): Drop `experimental_force_oauth_first` & `experimental__forceOauthFirst`

.changeset/grumpy-swans-taste.md, packages/shared/src/__tests__/browser.test.ts, packages/shared/src/__tests__/callWithRetry.test.ts, packages/shared/src/__tests__/keys.test.ts, packages/shared/src/__tests__/url.test.ts, packages/shared/src/callWithRetry.ts, packages/shared/src/utils/__tests__/createDeferredPromise.test.ts, packages/shared/src/utils/__tests__/instance.test.ts, packages/shared/src/utils/__tests__/runWithExponentialBackOff.test.ts, packages/shared/src/utils/instance.ts
Improves our test coverage of `@clerk/shared` by testing some more utilities.
=> chore(shared): Improve test coverage

.changeset/loud-peaches-travel.md, packages/remix/src/ssr/rootAuthLoader.ts, packages/remix/src/ssr/utils.ts, playground/remix-node/app/root.tsx
Add logic to support `defer()` usage in the wrapped loader. Currently, this isn't handled and we end up dropping the return value.
> **Note**
> I'm working on some integration tests for this locally, they will come in a followup.
=> feat(remix): Support defer() usage in rootAuthLoader()

.changeset/curly-ties-mix.md, packages/nextjs/src/server/authMiddleware.ts
This PR reverts a change in the types that caused `authMiddleware` types to not accept anything except static routes when using the experimental typed routes feature in nextjs.
=> fix(nextjs): Stop ts errors for non-static nextjs typed routes in authMiddleware

.changeset/tasty-countries-walk.md, packages/sdk-node/src/clerkClient.ts
Resolves https://github.com/clerkinc/javascript/issues/1938
=> fix(clerk-sdk-node): Fix types of ClerkExpressWithAuth/ClerkExpressRequireAuth args

.changeset/late-dolphins-peel.md, packages/backend/src/runtime/browser/fetch.mjs, packages/backend/src/runtime/index.ts, packages/backend/src/runtime/node/fetch.js
Next14 seems to have changed the way it handles default exports when using the webpack bundler for some of their build variants when using `npm run dev`. This commit ensures that we no longer use the default export in an effort to improve compat between the different nextjs versions. 
More information can be found here: https://esbuild.github.io/content-types/#default-interop
and here: https://github.com/clerkinc/javascript/pull/612
=> fix(backend): Support NextJS 14

.changeset/sour-comics-stare.md, packages/backend/src/api/factory.test.ts, packages/backend/src/api/request.ts, packages/backend/src/util/mockFetch.ts, packages/shared/src/error.ts
This PR adds `clerkTraceId` in `ClerkBackendApiResponse`. This can help debug issues with API responses especially when errors happen server side or transiently and they can't be viewed in the console. 
1. Use `ClerkAPIResponseError` from `@clerk/shared`. 
2. Updated `ClerkBackendApiResponse` interface to include `clerkTraceId` when available.
3. Extract `clerkTraceId` either from backend error response or headers in `buildRequest`.
4. Pass the new `clerkTraceId` value to `withLegacyReturn` and then to the constructor of `ClerkAPIResponseError`.
5. Update `toString` for `ClerkAPIResponseError` so it can also log the clerkTraceId.
Now callining `.toString()` on an error should show the trace id
The same is true for simply calling console.log on the error
DX is a bit weird here since fields …
=> Include clerkTraceId for backend api errors

.changeset/green-spies-leave.md, packages/clerk-js/src/ui/components/OrganizationProfile/InviteMembersForm.tsx
=> fix(clerk-js): Deconstruct new feedback props to avoid prop polluting

.changeset/tough-roses-hunt.md, packages/clerk-js/src/ui/customizables/parseAppearance.ts, packages/types/src/appearance.ts
This PR enables the avatar shimmer by default for `<UserButton/>` and `<OrganizationSwitcher/>`.
=> feat(clerk-js,types): Enable avatar shimmer by default

.changeset/three-rings-wash.md, packages/nextjs/src/server/getAuth.ts
Deprecation before removal of resources. See #1947
=> fix(nextjs): Deprecate `user`, `session`, `organization` from `auth()`

.changeset/thin-phones-drop.md, packages/nextjs/src/server/getAuth.ts
In this PR we are dropping  `user`, `session`, and `organization` resouces from the returned value of `auth()`. They were never officially supported as the middleware didn't support types for `loadUser`, `loadSession`.
Although by passing the types errors you could still load the resources. We consider bad practice to have extra 1-3 requests for each request that middleware captures so we should not allow developers to expect the resources returned from auth will be populated.
=> fix(nextjs): Drop `user`, `session`, `organization` from `auth()`

.changeset/fair-cameras-boil.md, packages/shared/package.json, scripts/subpath-workaround.mjs
Backporting #1974 to the main-v4 branch
(cherry picked from commit a68eb3083ff68459cd33098e2df190a5ba26c841)
=> fix(shared): Remove "sideEffects" and fix postbuild script (#1974)

.changeset/flat-pots-hear.md, packages/backend/src/tokens/interstitial.ts
This checks if the user prefers dark color schemes, and then sets the body to black. This could reduce 'flashes of white'.
=> Added style for prefers-color-scheme to interstitial head

.changeset/late-dolphins-peel.md, .changeset/tasty-countries-walk.md, packages/backend/src/runtime/browser/fetch.mjs, packages/backend/src/runtime/index.ts, packages/backend/src/runtime/node/fetch.js, packages/sdk-node/src/clerkClient.ts
PRs synced:
- https://github.com/clerkinc/javascript/pull/1939
- https://github.com/clerkinc/javascript/pull/1948
=> fix: Types and NextJS 14 support (#1939, #1948)

.changeset/flat-pots-hear.md, packages/backend/src/tokens/interstitial.ts
Backporting #1935 to the main-v4 branch
(cherry picked from commit 8b6b094b9c7d09eeae90f8bdfac44d53513aa63d)
=> Added style for prefers-color-scheme to interstitial head (#1935)

.changeset/sour-comics-stare.md, packages/backend/src/api/factory.test.ts, packages/backend/src/api/request.ts, packages/backend/src/util/mockFetch.ts, packages/shared/src/error.ts
Reopening this pull request since the previous (https://github.com/clerkinc/javascript/pull/1894) was accidentally only merged in main-v4.
=> chore(backend,shared): Include clerkTraceId for backend api errors

.changeset/bright-trainers-sort.md, packages/clerk-js/src/ui/components/OrganizationProfile/AddDomainPage.tsx, packages/clerk-js/src/ui/components/SignUp/SignUpForm.tsx, packages/clerk-js/src/ui/components/UserProfile/UsernamePage.tsx, packages/clerk-js/src/ui/elements/FieldControl.tsx, packages/clerk-js/src/ui/elements/Form.tsx, packages/clerk-js/src/ui/elements/FormControl.tsx, packages/clerk-js/src/ui/elements/RadioGroup.tsx, packages/clerk-js/src/ui/primitives/FormControl.tsx, packages/clerk-js/src/ui/primitives/Input.tsx, packages/clerk-js/src/ui/primitives/hooks/useFormControl.tsx, packages/clerk-js/src/ui/utils/useFormControl.ts
This is PR starts the refactoring process for our forms. The main focus is refactoring how our fields are structure, starting the `PlainInput` which represents a simple input element.
In the immediate feature we want to completely drop Form.Control and offer these alternatives
- Form.PasswordInput
- Form.Checkbox
- Form.RadioGroup
- Form.InputGroup
Their API will remain simple and those will be opinionated about the UI they represent, the underlying implementation will allow for easy changes tho.
- Replace Form.Control with Form.PlainInput (example usage)
- Top level API remains simple, but the internally Form.PlainInput is very modular.
- Renaming contexts and hooks with the `field` prefix in order to clearly indicate that the internal state reflects to a field not the entire form
- …
=> chore(clerk-js): Deprecate FormControl

.changeset/two-terms-speak.md, packages/types/src/appearance.ts
Simplifies the WithOptions generic by providing defaults to the generic.
=> refactor(types): Simplify WithOptions type generic

.changeset/twenty-turkeys-tell.md, packages/nextjs/src/server/getAuth.ts
This PR fixes an issue with imports & subpaths.
It also casts authStatus in order the pre-commit hooks to allow for the commit.
This needs to only be merged to v4, because this code was previously only merged to v4.
=> fix(nextjs): Import `deprecatedObjectProperty` from subpath

CODEOWNERS
After an internal structure team-js was renamed to team-sdk. Even though the team-sdk exists in organization, the codeowners were not updated.
=> fix(repo): Apply rename of team-js to team-sdk

.changeset/long-icons-share.md, packages/gatsby-plugin-clerk/src/constants.ts, packages/gatsby-plugin-clerk/src/gatsby-browser.tsx, packages/gatsby-plugin-clerk/src/gatsby-ssr.tsx, packages/gatsby-plugin-clerk/src/ssr/authenticateRequest.ts, packages/gatsby-plugin-clerk/src/ssr/clerkClient.ts, packages/gatsby-plugin-clerk/src/ssr/withServerAuth.ts
=> chore(gatsby-plugin-clerk): Drop deprecations

.changeset/fifty-rats-rhyme.md, packages/nextjs/src/server/constants.ts, packages/nextjs/src/utils/mergeNextClerkPropsWithEnv.ts, packages/remix/src/ssr/authenticateRequest.ts, packages/sdk-node/src/utils.ts, packages/shared/src/__tests__/underscore.test.ts, packages/shared/src/underscore.ts
Small QoL improvement to use an `isTruthy` helper for cases when we check if an env var is `true`. Could lead to subtle bugs if people not use the String `"true"` but something else that is truthy.
=> fix(nextjs,remix,clerk-sdk-node,shared): Use isTruthy helper

.changeset/mean-houses-juggle.md, packages/clerk-js/src/ui/components/UserProfile/ActiveDevicesSection.tsx, packages/clerk-js/src/ui/customizables/elementDescriptors.ts, packages/clerk-js/src/ui/elements/Accordion.tsx, packages/types/src/appearance.ts
Adds the following appearance keys for "Active devices":
- `cl-activeDeviceListItem`
- `cl-activeDeviceListItem__current`
- `cl-activeDevice`
- `cl-activeDevice__current`
SDK-859
=> feat(clerk-js): Enable element descriptors for active devices [SDK-859]

.changeset/lovely-plums-sin.md, packages/chrome-extension/tsup.config.ts, packages/nextjs/tsup.config.ts, packages/react/tsup.config.ts
If you look at e.g. https://unpkg.com/browse/@clerk/chrome-extension@0.4.12/dist/cjs/ you'll see that we bundle `exports.test.js` and `exports.test.js.map` 😱 
You can tell tsup to not add test files to the bundling like this:
```ts
entry: ['./src/**/*.{ts,tsx}', '!./src/**/*.test.{ts,tsx}'],
```
It uses [globby](https://www.npmjs.com/package/globby) so you can use `!` to ignore stuff.
Fixes SDK-801
=> fix(chrome-extension,nextjs,react): Ignore tests from build output

.changeset/poor-kings-marry.md, package-lock.json, packages/react/package.json, packages/react/src/utils/versionSelector.ts
Replaces the brittle logic of `getPrereleaseTag` and `getMajorVersion` with [`semver`](https://www.npmjs.com/package/semver) as it's battle-tested and will cover more of the edge cases.
=> fix(clerk-react): Use semver pkg

.changeset/loud-lions-compete.md, packages/chrome-extension/jest.config.js, packages/clerk-js/jest.config.js, packages/fastify/jest.config.js, packages/nextjs/jest.config.js, packages/react/jest.config.js, packages/sdk-node/jest.config.js, packages/shared/jest.config.js
Make `displayName` in `jest.config.js` consistent across all monorepo packages.
=> chore(repo): Fix tests display name

.changeset/blue-ghosts-float.md, packages/clerk-js/src/ui/components/OrganizationList/UserInvitationList.tsx, packages/clerk-js/src/ui/components/OrganizationList/UserSuggestionList.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/ActiveMembersList.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/RemoveDomainPage.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/RequestToJoinList.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/VerifiedDomainPage.tsx, packages/clerk-js/src/ui/components/OrganizationSwitcher/UserInvitationSuggestionList.tsx, packages/clerk-js/src/ui/components/OrganizationSwitcher/utils.ts, packages/shared/src/react/hooks/useOrganization.tsx, packages/shared/src/react/hooks/useOrganizationList.tsx, packages/shared/src/react/hooks/usePagesOrInfinite.ts, packages/shared/src/react/types.ts
**Issue:** 
So far our organization hooks did not officially support mutations. Developers did not have a way to alternate the cache or simply revalidate on demand.
**Background:** 
For `invitationList` (from useOrganization) we didn't encounter such issues, because we are forcing an update under the hood when `lastOrganizationMember` changes. In the case of deleted resource, the hook would refetch and the deleted items would disappear from the cache. In the new flows we introduce with <OrganizationList/> we need to update the cache in place and avoid refetching, in order to avoid layout shifts.
We want developers to explicitly call either `revalidate` or `setData` after a resource is updated and let them decide which method best suits their use-case.
This PR exposes the mutate function …
=> feat(shared): Organization hooks with `setData` and `revalidate`

.changeset/soft-birds-thank.md, packages/clerk-js/src/core/clerk.test.ts, packages/clerk-js/src/core/resources/Client.test.ts, packages/clerk-js/src/core/resources/Client.ts, packages/clerk-js/src/core/test/fixtures.ts
This PR will assign the Client properties to the default values on destroy.
=> fix(clerk-js): Re-initialize Client singleton instance on Client destroy

.changeset/blue-ghosts-float.md, packages/clerk-js/src/ui/components/OrganizationList/UserInvitationList.tsx, packages/clerk-js/src/ui/components/OrganizationList/UserSuggestionList.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/ActiveMembersList.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/RemoveDomainPage.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/RequestToJoinList.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/VerifiedDomainPage.tsx, packages/clerk-js/src/ui/components/OrganizationSwitcher/UserInvitationSuggestionList.tsx, packages/clerk-js/src/ui/components/OrganizationSwitcher/utils.ts, packages/shared/src/react/hooks/useOrganization.tsx, packages/shared/src/react/hooks/useOrganizationList.tsx, packages/shared/src/react/hooks/usePagesOrInfinite.ts, packages/shared/src/react/types.ts
Backporting #1745 to the release/v4 branch
(cherry picked from commit 743c4d20423790b554e66923466081c0d3b0d9ed)
=> feat(shared): Organization hooks with `setData` and `revalidate` (#1745)

.changeset/soft-birds-thank.md, packages/clerk-js/src/core/resources/Client.test.ts, packages/clerk-js/src/core/resources/Client.ts, packages/clerk-js/src/core/test/fixtures.ts
Backporting #1913 to the release/v4 branch
(cherry picked from commit 93a611570b836fc9bd50eed973e76cf8d413963d)
=> fix(clerk-js): Re-initialize Client singleton instance on Client destroy (#1913)

.changeset/many-weeks-march.md, packages/remix/src/client/RemixClerkProvider.tsx, packages/remix/src/client/types.ts, packages/remix/src/errors.ts, packages/remix/src/ssr/authenticateRequest.ts, packages/remix/src/ssr/getAuth.ts, packages/remix/src/ssr/types.ts, packages/remix/src/ssr/utils.ts
Drop deprecations. Migration steps:
- use `CLERK_SECRET_KEY` instead of `CLERK_API_KEY` env variable
- use `secretKey` instead of `apiKey`
- use `CLERK_PUBLISHABLE_KEY` instead of `CLERK_FRONTEND_API` env variable
- use `publishableKey` instead of `frontendApi`
Extra:
- refactor to use `isDevelopmentFromApiKey` from `@clerk/shared`
=> chore(remix): Drop deprecations

.changeset/gorgeous-insects-reply.md, packages/clerk-js/src/ui/elements/__tests__/PlainInput.test.tsx, packages/clerk-js/src/ui/primitives/hooks/useFormControl.tsx
This PR adds tests cases in order to be sure that the behaviour of input texts didn't broke during refactoring
=> test(clerk-js): Test cases for parity between PlainInput and FormControl

.changeset/rude-jobs-yawn.md, packages/clerk-js/src/utils/url.ts, packages/fastify/src/constants.ts, packages/gatsby-plugin-clerk/src/constants.ts, packages/nextjs/src/server/constants.ts, packages/nextjs/src/server/url.ts, packages/remix/src/ssr/authenticateRequest.ts, packages/shared/.gitignore, packages/shared/package.json, packages/shared/src/__tests__/apiUrlFromPublishableKey.test.ts, packages/shared/src/apiUrlFromPublishableKey.ts, packages/shared/src/constants.ts, packages/shared/src/index.ts, packages/shared/src/keys.ts, packages/shared/src/url.ts, packages/shared/src/utils/index.ts, packages/shared/subpaths.mjs
Improve the default value for CLERK_API_URL by utilizing the publishable key to differentiate between local, staging and prod environments.
We can also add this to other packages that can import the shared package.
=> feat(nextjs,shared): Improve CLERK_API_URL default value

.changeset/famous-forks-buy.md, packages/clerk-js/src/core/resources/Organization.ts, packages/clerk-js/src/core/resources/Permission.ts, packages/clerk-js/src/core/resources/Role.ts, packages/clerk-js/src/core/resources/__snapshots__/Organization.test.ts.snap, packages/clerk-js/src/core/resources/__snapshots__/OrganizationMembership.test.ts.snap, packages/clerk-js/src/ui/components/CreateOrganization/CreateOrganizationForm.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/ActiveMembersList.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/InviteMembersForm.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/InviteMembersPage.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/InvitedMembersList.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/MemberListTable.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/__tests__/InviteMembersPage.test.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/__tests__/OrganizationMembers.test.tsx, packages/clerk-js/src/ui/hooks/useFetch.ts, packages/clerk-js/src/ui/hooks/useFetchRoles.ts, packages/clerk-js/src/ui/utils/roleLocalizationKey.ts, packages/types/src/index.ts, packages/types/src/json.ts, packages/types/src/localization.ts, packages/types/src/organization.ts, packages/types/src/organizationMembership.ts, packages/types/src/permission.ts, packages/types/src/role.ts
This PR
- Introduces RoleResource and PermissionResource.
- Updates RoleSelect to accept roles as a prop.
- Fetch custom roles from FAPI inside `InviteMembersPage` & `ActiveMembers`.
- Accept custom localizations based on role key when this is passed in the localization object via ClerkProvider.
**This PR will need to backported to v4 as it is complementary to "custom roles & permissions"**
=> feat(clerk-js,types): Fetch custom roles and localize them

.github/actions/init/action.yml, .github/workflows/ci.yml, .github/workflows/labeler.yml, integration/playwright.config.ts, package.json, turbo.json
**NPM:**
- Cache `node_modules` based off of `package-lock.json` not `**/package-lock.json`. This was likely the culprit of the missing caches due to the integration tests updating their own package-lock.json files.
**Turborepo:**
- Remove `GITHUB_ACCESS_TOKEN` from `globalEnv` as it rotates regularly.
- Remove, ultimately, unnecessary files from `globalDependencies`.
- Summarize the task runs, for future analysis.
**Playwright:**
- Fail fast.
- Use all available resources.
- When we were on the smaller GHA boxes, this was limited to 50% (1 vCPU), so when we upgraded to 8 vCPU, it was only using 4. This ensures that we're using one less than all available vCPUs for workers.
- _**Outcome:**_ Reduced the box to medium as Playwright requires (and only utilizes) less resources. Regardless of …
=> fix(repo): GHA optimizations

.github/workflows/base-build.yml, .github/workflows/lock-threads.yml
Fix `error when evaluating 'timeout-minutes'` for :
- lock-threads ( i will restart the latest failed job this PR is merged)
- base-build
=> fix(repo): Fix error when evaluating 'timeout-minutes'

.github/ISSUE_TEMPLATE/BUG_REPORT.yml
Add jam.dev as an option for creating reproductions in our bug report template 🐛
=> Add jam.dev to bug report template

.changeset/new-eels-mix.md, packages/backend/src/tokens/authObjects.ts, packages/nextjs/src/server/getAuth.ts
=> fix(nextjs): Improve type inference for the return type of auth helper

.changeset/metal-cougars-fail.md, .changeset/pretty-months-greet.md, packages/clerk-js/src/ui/components/CreateOrganization/CreateOrganizationForm.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/ActionConfirmationPage.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/ProfileSettingsPage.tsx, packages/clerk-js/src/ui/components/UserProfile/DeletePage.tsx, packages/clerk-js/src/ui/components/UserProfile/EmailPage.tsx, packages/clerk-js/src/ui/components/UserProfile/ProfilePage.tsx, packages/localizations/src/en-US.ts, packages/types/src/localization.ts
Droping the usage of Form.Control for simple text field with type `text` or `email`.
=> chore(clerk-js): Replace text and email fields with Form.PlainInput

playground/nextjs/package.json
I'm trying to deploy `playground/nextjs` to Vercel so the deps need to be valid versions, not Yalc stuff
=> chore(repo): Use valid deps in playground/nextjs

.changeset/new-eels-mix.md, packages/backend/src/tokens/authObjects.ts, packages/nextjs/src/server/getAuth.ts
=> fix(nextjs): Improve type inference for the return type of auth helper (#2047)

.changeset/orange-pumpkins-poke.md, packages/backend/src/tokens/authObjects.ts, packages/chrome-extension/src/__snapshots__/exports.test.ts.snap, packages/clerk-js/src/core/resources/Session.test.ts, packages/clerk-js/src/core/resources/Session.ts, packages/clerk-js/src/ui/common/Gate.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/OrganizationProfileRoutes.tsx, packages/clerk-js/src/ui/utils/test/mockHelpers.ts, packages/nextjs/src/app-router/server/controlComponents.tsx, packages/nextjs/src/client-boundary/controlComponents.ts, packages/nextjs/src/components.client.ts, packages/nextjs/src/components.server.ts, packages/nextjs/src/index.ts, packages/react/src/components/controlComponents.tsx, packages/react/src/components/index.ts, packages/react/src/hooks/useAuth.ts, packages/react/src/utils/deriveState.ts, packages/types/src/jwtv2.ts, packages/types/src/session.ts
=> feat(nextjs,clerk-react,types,clerk-js): Add experimental support for `<Gate/>` (#1942)

.changeset/curvy-mails-rhyme.md, .github/workflows/release-canary.yml, docs/CICD.md, docs/PUBLISH.md, package-lock.json, package.json, packages/clerk-js/scripts/purge-cache.mjs, packages/clerk-js/src/utils/setWebpackChunkPublicPath.ts, packages/shared/src/__tests__/url.test.ts, packages/shared/src/url.ts, scripts/.eslintrc.js, scripts/canary.mjs
This PR renames the `@staging` package tag to `@canary`.
We need to make changes to other parts of the Clerk infrastructure first to support this change.
=> chore(repo): Rename `@staging` tag to `@canary`

.github/workflows/release.yml
Environment variable access between these actions isn't playing out well. This PR simply moves the build process out of the changelog publish cmd.
=> fix(repo): Build ahead of release creation

.github/workflows/release.yml
When entering a pre-release mode (using changeset pre-mode) we should not prepare versions for production release in `clerkjs-proxy` worker from the `main` branch since they are ONLY meant to be released upon being stable. Also by leaving the action to be triggered with pre-release tags the clerk-js-proxy release production with the latest stable version is being overwritten and this may cause an accidental release of an alpha-v5 tag as stable.
=> fix(repo): Disable preparating clerk-js-proxy production release PR on pre-mode

.changeset/ten-scissors-applaud.md, packages/sdk-node/src/instance.ts
Warn about `@clerk/clerk-sdk-node/{esm|cjs}/instance` deprecation warning
Will be dropped in the next major version with : https://github.com/clerk/javascript/pull/2021
=> chore(clerk-sdk-node): Warn about `{esm|cjs}/instance` subpath import deprecation warning

.vscode/settings.json
Remove the organize imports flag as it may go against eslint in some cases.
=> fix(repo): Remove organize imports rule as eslint fix all suffices

.changeset/chatty-boats-tease.md, packages/clerk-js/src/ui/components/OrganizationProfile/ActiveMembersList.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/InvitedMembersList.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/MemberListTable.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/RequestToJoinList.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/__tests__/OrganizationMembers.test.tsx, packages/shared/src/react/hooks/useOrganization.tsx
This PR fixes issues with incorrect values in table pagination as users select pages
Page 2
Page 2
=> fix(clerk-js): Incorrect result counters in data tables

.github/workflows/release-canary.yml, .github/workflows/release-snapshot.yml
A few minor fixes.
- No need to use --force for canary releases
- No need to build the packages if changesets did not result in a new version bump
=> chore(repo): Do not build if no version changed

.changeset/slow-wombats-battle.md, packages/clerk-js/src/ui/components/OrganizationProfile/VerifiedDomainPage.tsx, packages/clerk-js/src/ui/elements/FieldControl.tsx, packages/clerk-js/src/ui/elements/Form.tsx, packages/clerk-js/src/ui/elements/RadioGroup.tsx, packages/clerk-js/src/ui/elements/__tests__/RadioGroup.test.tsx
Refactor internal form radio, previously this was nested under FormControl, now it is a top level component. Tests are added to make sure nothing was broken during refactoring.
=> chore(clerk-js): Introduce Form.RadioGroup

.changeset/chatty-boats-tease.md, packages/clerk-js/src/ui/components/OrganizationProfile/ActiveMembersList.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/InvitedMembersList.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/MemberListTable.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/RequestToJoinList.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/__tests__/OrganizationMembers.test.tsx, packages/shared/src/react/hooks/useOrganization.tsx
Backporting #2056 to the release/v4 branch
(cherry picked from commit 64d3763ec73747ad04c4b47017195cf4114e150c)
=> fix(clerk-js): Incorrect result counters in data tables (#2056)

.github/workflows/release-canary.yml
Fix typo in cherry-picking backported changes from the https://github.com/clerk/javascript/pull/2066
=> fix(repo): Fix workflow name in accounts repo

.changeset/purple-rules-prove.md, packages/clerk-js/src/core/clerk.test.ts, packages/clerk-js/src/core/clerk.ts, packages/clerk-js/src/core/constants.ts, packages/clerk-js/src/ui/components/SignIn/SignInStart.tsx, packages/clerk-js/src/ui/components/SignUp/SignUpStart.tsx
Backporting #2019 to the release/v4 branch
(cherry picked from commit d1b524ffba0be0cd683e6ace85b91b382ad442bb)
=> feat(clerk-js): Handle user_locked error during oauth flow with redirect to /sign-up or /sign-in (#2019)

.changeset/thirty-doors-peel.md, packages/clerk-js/src/ui/components/OrganizationProfile/ActiveMembersList.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/InvitedMembersList.tsx, packages/shared/src/react/hooks/useOrganization.tsx
This ensures that the list of members invited to an organization is revalidated upon the revocation of an invitation.
Fixes SDK-890
=> fix(clerk-js,shared): Refresh invited members upon revocation

.changeset/clever-vans-flash.md, packages/clerk-js/src/core/clerk.ts
Backporting #2072 to the release/v4 branch
(cherry picked from commit 034abeb762744c4948ef6600b21cd9dd68d165a8)
=> fix(clerk-js): Use strict equality operator to check for lockout errors in handleRedirectCallback (#2072)

.changeset/honest-onions-work.md, packages/nextjs/src/server/errors.ts
Removes the typo that breaks the link on a nextjs-clerk  authAuthHeaderMissing  Error, which added the annoying dot to the link and was breaking it.
- [x ] `npm test` runs as expected.
- [x ] `npm run build` runs as expected.
- [x ] 🐛 Bug fix
- [x ] `@clerk/nextjs`
=> fix(nextjs): Removes the dot that breaks the link to the docs

.changeset/dry-students-reflect.md, packages/clerk-js/src/core/resources/Organization.ts, packages/clerk-js/src/utils/memoizeStateListenerCallback.ts
This PR allows for clerk-js to detect when the role or permissions of the active organization memberships of the user has changed and emit them for subscribers (in this case clerk-react is what we are interested in).
https://github.com/clerk/javascript/assets/19269911/5a391888-d798-45f0-a1ed-6aa21e3ed9db
https://github.com/clerk/javascript/assets/19269911/492f0e4b-27e0-46b0-b1d2-2803b02bab81
=> fix(clerk-js): Emit session when permissions or role of the active memberships change

.changeset/dry-students-reflect.md, packages/clerk-js/src/core/resources/Organization.ts, packages/clerk-js/src/utils/memoizeStateListenerCallback.ts
Backporting #2073 to the release/v4 branch
(cherry picked from commit 5f49568f6e345ce63b15a4c301fc81c3af30211a)
=> fix(clerk-js): Emit session when permissions or role of the active memberships change (#2073)

.changeset/plenty-bottles-grow.md, packages/remix/src/ssr/utils.ts
Avoid always showing `frontendApi` on `@clerk/remix`!
Similar to: https://github.com/clerk/javascript/pull/1856
Resolves comment: https://github.com/clerk/javascript/pull/1823#issuecomment-1801389095
=> fix(remix): Avoid always showing `frontendApi` deprecation

.changeset/thirty-doors-peel.md, packages/clerk-js/src/ui/components/OrganizationProfile/ActiveMembersList.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/InvitedMembersList.tsx
Backporting #2058 to the release/v4 branch
(cherry picked from commit 59336d3d468edd205c0e5501b7d5046611ee217d)
=> fix(clerk-js,shared): Refresh invited members upon revocation (#2058)

.github/workflows/release.yml
In our CI unit tests, we run against Node 18 and Node 20 and we cache the `node_modules` output.
Node 20, however, continuously creates a new cache and the reason for this is that we run CI on the `merge_group` event and not on `main`.
Branches and PRs only have access to caches created within the scope of their branch, their base branch, and the default branch, which does not include merge groups.
This adds a simple job which ensures that `node_modules` for specific node versions (in this case, just v20) are cached in a way that follow-on branches are able to access it.
The job itself will add a very minimal amount of time to `main` and `release/v4` while having significant benefits downstream.
=> chore(repo): Cache extraneous node_module versions

.changeset/flat-donuts-sleep.md, packages/clerk-js/src/ui/components/SignIn/SignInFactorOneCodeForm.tsx, packages/clerk-js/src/ui/components/SignIn/SignInFactorTwoCodeForm.tsx
Was not returning the rejection in the handler for code forms.
Thanks to @nikosdouvlis for pointing out.
=> fix(clerk-js): Return reject(err) in factor one & two code forms

.github/workflows/preview.yml, docs/CICD.md, docs/CONTRIBUTING.md, docs/PUBLISH.md
Add deploy preview `!preview` capability to our docs.
Fix some bugs in the workflow itself.
Follow-up to https://github.com/clerk/javascript/pull/2079
=> chore: Add Deploy preview to docs & improve workflow

.changeset/tough-pots-grow.md, packages/react/src/components/withClerk.tsx, packages/react/src/components/withSession.tsx, packages/react/src/components/withUser.tsx, packages/react/src/contexts/assertHelpers.ts, packages/react/src/errors.ts, packages/react/src/hooks/useAuth.ts, packages/react/src/isomorphicClerk.ts, packages/react/src/utils/childrenUtils.tsx, packages/react/src/utils/errorThrower.ts, packages/react/src/utils/useMaxAllowedInstancesGuard.tsx, packages/shared/src/error.ts, packages/shared/src/utils/logErrorInDevMode.ts
This PR includes the following:
- Adds a new function to the shared `errorThrower` utility with the simple name `throw` that accepts a `string` with the message to be thrown.
- Fix the React package name passed to the `errorThrower`.
- Use the `errorThrower` to throw all errors in the `@clerk/clerk-react` package.
=> [SDK-805] Use the `errorThrower` shared util when throwing errors

.changeset/weak-elephants-grin.md, packages/backend/src/tokens/authObjects.test.ts, packages/backend/src/tokens/authObjects.ts, packages/backend/tests/suites.ts
Strip `experimental__has` from the auth object in `makeAuthObjectSerializable()`. This fixes an issue in Next.js where an error is being thrown when this function is passed to a client component as a prop.
fixes #2097
=> fix(backend): strip experimental__has from serializable auth object

.changeset/weak-elephants-grin.md, packages/backend/src/tokens/authObjects.test.ts, packages/backend/src/tokens/authObjects.ts, packages/backend/tests/suites.ts
Backporting #2101 to the release/v4 branch
(cherry picked from commit a6451aecef0bac578b295b524f1246dede3a7598)
=> fix(backend): strip experimental__has from serializable auth object (#2101)

.changeset/gentle-pants-matter.md, packages/clerk-js/src/ui/components/OrganizationProfile/ActiveMembersList.tsx, packages/shared/src/react/hooks/usePagesOrInfinite.ts
The changes introduced from this PR affect all organization hooks with the new API that perform requests to FAPI endpoints.
=> fix(clerk-js,shared): Increase time-to-stale for less frequent revalidations

.changeset/friendly-tables-chew.md, packages/clerk-js/src/ui.retheme/components/OrganizationSwitcher/UserMembershipList.tsx, packages/clerk-js/src/ui.retheme/components/OrganizationSwitcher/__tests__/OrganizationSwitcher.test.tsx, packages/clerk-js/src/ui/components/OrganizationSwitcher/UserMembershipList.tsx, packages/clerk-js/src/ui/components/OrganizationSwitcher/__tests__/OrganizationSwitcher.test.tsx
This PR replaces the deprecated usage of `organizationList` from useOrganizationList with `userMemberships` that is returned from the same hook.
This PR also unblocks #2102
=> chore(clerk-js): Use `userMemberships` instead of `organizationList` inside `OrganizationSwitcher`

.changeset/dry-sheep-poke.md, integration/testUtils/appPageObject.ts, integration/testUtils/index.ts, integration/tests/sign-out-smoke.test.ts, integration/tsconfig.json, integration/types.d.ts, packages/clerk-js/src/core/clerk.ts
This PR enables the BrodcastChannel functionallity, that is going to allow us to signout from multiple tabs at once.
=> feat(clerk-js): Sign Out from multiple tabs at once

.changeset/old-actors-beg.md, packages/clerk-js/src/core/resources/OrganizationMembership.ts, packages/nextjs/src/server/authMiddleware.ts, packages/types/src/clerk.retheme.ts, packages/types/src/clerk.ts, packages/types/src/json.ts, packages/types/src/organizationMembership.ts, packages/types/src/session.ts, packages/types/src/utils.ts
Adds Autocomplete Typescript generic util.
SDK-900
=> refactor(clerk-js,nextjs,types): Add Autocomplete generic [SDK-900]

.changeset/khaki-spoons-teach.md, packages/clerk-js/src/ui.retheme/components/OrganizationProfile/InviteMembersForm.tsx, packages/clerk-js/src/ui.retheme/components/OrganizationProfile/__tests__/InviteMembersPage.test.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/InviteMembersForm.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/__tests__/InviteMembersPage.test.tsx
This PR disabled the submit button until the role is selected otherwise a FAPI request would fire and fail.
Unfortunately field errors are not supported for the internal Select component, and it would be too much work for a v4 hot fix.
*The changes are introduced for both `ui` and `ui.retheme` as this is a bug fix and needs to be backported to v4.*
=> fix(clerk-js): Require role to be selected before sending organization invite

.changeset/cuddly-cougars-check.md, packages/clerk-js/src/ui/hooks/__tests__/useCoreOrganizationList.test.tsx, packages/react/src/contexts/OrganizationContext.tsx, packages/shared/src/error.ts, packages/shared/src/proxy.ts, packages/shared/src/react/contexts.tsx, packages/shared/src/react/hooks/useOrganizationList.tsx, packages/shared/src/react/index.ts
Drop deprecations. Migration steps:
- use `EmailLinkError` instead of `MagicLinkError`
- use `isEmailLinkError` instead of `isMagicLinkError`
- use `EmailLinkErrorCode` instead of `MagicLinkErrorCode`
- use `useEmailLink` instead of `useMagicLink`
- use `buildRequestUrl` from `@clerk/backend` instead of `getRequestUrl` from `@clerk/shared`
- use `OrganizationProvider` instead of `OrganizationContext`
- use `userMemberships` instead of `organizationList` from `useOrganizationList`
Depends on:
- clerk-js : https://github.com/clerk/javascript/pull/2082
=> chore(shared): Drop deprecations

.changeset/red-coats-itch.md, packages/backend/src/api/factory.ts, packages/backend/src/api/request.ts, packages/backend/src/tokens/authObjects.ts, packages/backend/src/tokens/authStatus.ts, packages/backend/src/tokens/factory.ts, packages/backend/src/tokens/index.ts, packages/backend/src/tokens/interstitialRule.ts, packages/backend/src/tokens/request.test.ts, packages/backend/src/tokens/request.ts, packages/nextjs/src/server/getAuth.ts
Changes: 
- drop options that can be retrieved from `headers` or `cookies` of request
- enforce usage of `request` param
- refactor types to fix the cyclic type dependency and allow separating the options passed in `authenticateRequest` from the options used internally
=> chore(backend): Enforce `request` param in `authenticateRequest`

.changeset/clever-scissors-reflect.md, packages/backend/src/api/endpoints/InvitationApi.ts, packages/chrome-extension/src/ClerkProvider.tsx, packages/chrome-extension/src/singleton.ts, packages/clerk-js/headless/index.d.ts, packages/clerk-js/src/core/clerk.redirects.test.ts, packages/clerk-js/src/core/clerk.test.ts, packages/clerk-js/src/core/clerk.ts, packages/clerk-js/src/core/devBrowserHandler.test.ts, packages/clerk-js/src/core/devBrowserHandler.ts, packages/clerk-js/src/core/fapiClient.test.ts, packages/clerk-js/src/core/fapiClient.ts, packages/clerk-js/src/core/resources/internal.ts, packages/clerk-js/src/index.browser.ts, packages/clerk-js/src/index.headless.browser.ts, packages/clerk-js/src/index.headless.ts, packages/clerk-js/src/index.ts, packages/clerk-js/src/ui/utils/test/createFixtures.tsx, packages/clerk-js/src/utils/retrieveCaptchaInfo.ts, packages/expo/src/singleton.ts, packages/react/src/contexts/ClerkContextProvider.tsx, packages/react/src/hooks/useAuth.ts, packages/react/src/hooks/utils.ts, packages/react/src/isomorphicClerk.ts, packages/sdk-node/src/__tests__/__snapshots__/exports.test.ts.snap, packages/sdk-node/src/index.ts, packages/sdk-node/src/instance.ts
Drop default exports from all packages. Migration guide:
- use `import { Clerk } from '@clerk/backend';`
- use `import { clerkInstance } from '@clerk/clerk-sdk-node';`
- use `import { Clerk } from '@clerk/clerk-sdk-node';`
- use `import { Clerk } from '@clerk/clerk-js';`
- use `import { Clerk } from '@clerk/clerk-js/headless';`
- use `import { IsomorphicClerk } from '@clerk/clerk-react'`
=> chore(*): Drop default exports

.changeset/brown-clouds-divide.md, packages/clerk-js/src/ui.retheme/components/OrganizationSwitcher/OrganizationSwitcherTrigger.tsx, packages/clerk-js/src/ui/components/OrganizationSwitcher/OrganizationSwitcherTrigger.tsx
In order to see notifications for suggestions and invitations you don't have to have a permission or have an active organization. Previously we incorrectly wrapped this component with `Gate`. Instead we only want to check if you have have the `org:sys_memberships:mananage` permission in order to fetch and include in the counter the requests of an active organization.
https://github.com/clerk/javascript/assets/19269911/2fc086ce-223e-45d0-92a7-7b9b02482ace
https://github.com/clerk/javascript/assets/19269911/a6c3215f-6462-4605-a457-3307b8e65913
=> fix(clerk-js): Avoid wrapping NotificationCountBadge of OrgSwitcher with Gate

.github/workflows/nightly-checks.yml
Currently, the `Nightly upstream tests` Github action seems to run with the latest next version instead of the next canary. This PR adds the missing env to make it run with the canary and also adds a step in the action to show the packages (with their version) that the tests run
=> chore(repo): Fix nextjs canary release & show tests package versions

.changeset/mighty-pugs-knock.md, packages/backend/src/api/factory.test.ts, packages/backend/src/api/request.ts, packages/backend/src/tokens/authStatus.ts, packages/backend/src/util/assertResponse.ts, packages/backend/src/util/mockFetch.ts, packages/nextjs/src/app-router/server/currentUser.ts, packages/sdk-node/examples/express/src/runtime-keys-middleware.ts, packages/sdk-node/examples/node/src/organizations.ts, packages/sdk-node/examples/node/src/sessions.ts, packages/sdk-node/examples/node/src/users.ts, packages/sdk-node/src/__tests__/middleware.test.ts, packages/sdk-node/src/authenticateRequest.ts, packages/sdk-node/src/clerkExpressRequireAuth.ts, packages/sdk-node/src/clerkExpressWithAuth.ts
Currently the BAPI responses are in `{ data: unknown | null, errors: [] | null }` format but to avoid introducing a breaking change we convert those responses and return only the `data` part or `throw` an error if there are `errors`.
With this PR we will drop the transformation and return the actual response. This is a breaking change since from now on
- no error will be thrown from the BAPI requests client
- the caller will have to check for the `errors` prop in the return value to verify if the request succeeded
- the caller will have to retrieve the response data from the `data` prop in the return value
- [] `@clerk/fastify`
- [] `gatsby-plugin-clerk`
- [] `@clerk/remix`
=> chore(backend,nextjs,clerk-sdk-node): Drop legacy return response in BAPI responses

.github/workflows/ci.yml, integration/constants.ts, integration/models/application.ts, integration/models/applicationConfig.ts, integration/presets/express.ts, integration/presets/index.ts, integration/presets/longRunningApps.ts, integration/presets/next.ts, integration/presets/react.ts, integration/presets/remix.ts, integration/scripts/clerkJsServer.ts, integration/scripts/waitForServer.ts, integration/templates/express-vite/.gitignore, integration/templates/express-vite/package.json, integration/templates/express-vite/src/server/main.ts, integration/templates/express-vite/src/views/index.ejs, integration/templates/express-vite/src/views/protected.ejs, integration/templates/express-vite/src/views/sign-in.ejs, integration/templates/express-vite/src/views/sign-up.ejs, integration/templates/express-vite/tsconfig.json, integration/templates/express-vite/vite.config.ts, integration/templates/index.ts, integration/tests/sign-in-smoke.test.ts, package.json, scripts/nuke.sh, turbo.json
Add integration test to verify that `@clerk/shared` tree-shaking works in backend application that do not use `react` as dependency.
We have introduced an Express + Vite template application that uses `@clerk/clerk-sdk-node` with the following endpoints
- `/api/protected` endpoint that uses `expressRequireAuth()` from `@clerk/clerk-sdk-node` to verify authentication
- `/sign-in` renders HTML that mounts `<SignIn/>` client-side component using ClerkJS
- `/sign-up` renders HTML that mounts `<SignUp/>` client-side component using ClerkJS
- `/protected` renders HTML `SignedIn` or `SignedOut` context and makes a request to the `/api/protected` to fetch the response that will be appended in body and asserted via playwright.
https://github.com/clerkinc/javascript/issues/1883
=> chore(repo): Introduce integration test for vite with sdk-node

.changeset/fast-ads-mix.md, packages/clerk-js/src/core/clerk.test.ts, packages/clerk-js/src/core/clerk.ts, packages/clerk-js/src/utils/__tests__/url.test.ts, packages/clerk-js/src/utils/url.ts
This PR introduces default values for the `allowedRedirectOrigins` option, the current implementation does not provide any defaults, with this change if there is no option provided the default will be similar to the example below.
Let's say the host of the application is `test.host`, the origins will be
- `https://test.host/`
- `https://yourawesomeapp.clerk.accounts.dev/`
- `https://*.yourawesomeapp.clerk.accounts.dev/`
=> feat(clerk-js): Add default Allowed redirect origins

.changeset/bright-plants-swim.md, integration/templates/next-app-router/package.json, integration/templates/react-cra/package.json, integration/templates/react-vite/package.json, integration/templates/remix-node/package.json, package-lock.json, package.json, packages/backend/package.json, packages/chrome-extension/package.json, packages/clerk-js/package.json, packages/expo/package.json, packages/fastify/package.json, packages/gatsby-plugin-clerk/package.json, packages/localizations/package.json, packages/nextjs/examples/next/package.json, packages/nextjs/package.json, packages/react/package.json, packages/remix/package.json, packages/sdk-node/examples/express/package.json, packages/sdk-node/package.json, packages/shared/package.json, packages/themes/package.json, packages/types/package.json, playground/express/package.json, playground/gatsby/package.json
To support Vercel (using node@18.17) for node@18 runtime we need to downgrade our minimum node version.
=> chore(*): Downgrade minimum version to node@18.17

.changeset/rich-actors-cross.md, packages/clerk-js/src/ui.retheme/components/OrganizationProfile/OrganizationMembers.tsx, packages/clerk-js/src/ui.retheme/components/OrganizationProfile/OrganizationProfileNavbar.tsx, packages/clerk-js/src/ui.retheme/components/OrganizationProfile/OrganizationProfileRoutes.tsx, packages/clerk-js/src/ui.retheme/components/OrganizationProfile/__tests__/OrganizationMembers.test.tsx, packages/clerk-js/src/ui.retheme/components/OrganizationProfile/__tests__/OrganizationProfile.test.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/OrganizationMembers.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/OrganizationProfileNavbar.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/OrganizationProfileRoutes.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/__tests__/OrganizationMembers.test.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/__tests__/OrganizationProfile.test.tsx
This PR hides the members pages if both the "manage" or "read" permissions are missing. In the case of only `org:sys_memberships:manage` existing we display the page but hide the "memberships" tab
https://github.com/clerk/javascript/assets/19269911/a876c7be-1f71-45af-ad93-4f678aff90de
https://github.com/clerk/javascript/assets/19269911/b36315a3-1e3f-4d91-82aa-d06d490931b1
https://github.com/clerk/javascript/assets/19269911/6e577a3e-bb34-4626-b7a7-f3413f2fa723
https://github.com/clerk/javascript/assets/19269911/673866ab-ba20-4d25-bf40-a51fe4fc66a9
=> fix(clerk-js): Hide Members page of OrgProfile if user doesn't have any member related permissions

.changeset/rich-actors-cross.md, packages/clerk-js/src/ui/components/OrganizationProfile/OrganizationMembers.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/OrganizationProfileNavbar.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/OrganizationProfileRoutes.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/__tests__/OrganizationMembers.test.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/__tests__/OrganizationProfile.test.tsx
=> fix(clerk-js): Hide Members page of OrgProfile if user doesn't have any member related permissions (#2138)

.changeset/slimy-windows-grab.md, packages/backend/src/api/endpoints/SMSMessageApi.ts
The deprecation commit of https://github.com/clerk/javascript/pull/2165 for release in v4
=> feat(backend): Deprecate createSMSMessage

.changeset/wise-lions-type.md, packages/clerk-js/src/ui.retheme/components/OrganizationSwitcher/OrganizationSwitcherPopover.tsx, packages/clerk-js/src/ui.retheme/components/OrganizationSwitcher/OrganizationSwitcherTrigger.tsx, packages/clerk-js/src/ui.retheme/components/OrganizationSwitcher/UserInvitationSuggestionList.tsx, packages/clerk-js/src/ui.retheme/components/OrganizationSwitcher/UserMembershipList.tsx, packages/clerk-js/src/ui/components/OrganizationSwitcher/OrganizationSwitcherPopover.tsx, packages/clerk-js/src/ui/components/OrganizationSwitcher/OrganizationSwitcherTrigger.tsx, packages/clerk-js/src/ui/components/OrganizationSwitcher/UserInvitationSuggestionList.tsx, packages/clerk-js/src/ui/components/OrganizationSwitcher/UserMembershipList.tsx, packages/types/src/elementIds.ts
This PR introduces some breaking changes and some additions to the `organzationPreview` descriptor
- The `organizationSwitcher` id has been renamed to `organizationSwitcherTrigger` and the generated element class will be `.cl-organizationPreview__organizationSwitcherTrigger`
- The `organizationSwitcherListedOrganization` for styling listed organization in the `<OrganizationSwitcher/>` and the generated class will be `.cl-organizationPreview__organizationSwitcherListedOrganization`
- The `organizationSwitcherActiveOrganization` for styling the active organization in the `<OrganizationSwitcher/>` and the generated class will be `.cl-organizationPreview__organizationSwitcherActiveOrganizationn`
=> feat(clerk-js,types): Update OrganizationPreview appearance descriptors for OrganizationSwitcher 

.changeset/curvy-timers-play.md, packages/localizations/src/en-US.ts
Added missing parameter for localizations
=> fix(localizations): Added missing key and en-US localization

.github/workflows/nightly-checks.yml
Drop `Show package versions` in nightly-checks since the current script fails. We will revisit this in the future.
=> chore(repo): Drop `Show package versions` in nightly-checks

.changeset/clever-moose-act.md, packages/clerk-js/src/ui/components/OrganizationProfile/VerifyDomainPage.tsx
=> fix(clerk-js): Reset CodeControl when resetting wizard in VerifyDomainPage (#2200)

.changeset/brave-suits-drive.md, packages/clerk-js/src/core/errors.ts, packages/clerk-js/src/ui/common/__tests__/authPropHelpers.test.ts, packages/clerk-js/src/utils/authPropHelpers.ts
This PR introduces a breaking change for all the components using routing, if the a `path` property is provided with a routing strategy other than `path` a runtime error will be thrown.
Example that will throw an error:
```tsx
<SignIn routing='hash' path='/sign-in' />
```
=> feat(clerk-js): Throw error if routing options are used incorrectly

.changeset/new-cougars-taste.md, packages/backend/src/api/factory.test.ts, packages/backend/src/api/request.ts, packages/backend/src/api/resources/Deserializer.ts, packages/backend/src/api/resources/JSON.ts, packages/backend/src/util/mockFetch.ts
The backend clerkClient will return a `totalCount: number` in the responses for BAPI responses:
- with `total_count` prop of response
- with an array of objects as `data` prop of response
The `totalCount` is NOT included in:
- single resource responses
- error responses
=> feat(backend): Support totalCount on BAPI responses

.changeset/quick-countries-scream.md, packages/backend/src/api/endpoints/OrganizationApi.ts, packages/backend/src/api/endpoints/OrganizationPermissionApi.ts, packages/backend/src/api/endpoints/OrganizationRoleApi.ts, packages/backend/src/api/endpoints/UserApi.ts, packages/clerk-js/src/ui.retheme/components/CreateOrganization/CreateOrganization.tsx, packages/clerk-js/src/utils/pagesToOffset.ts, packages/types/src/api.ts, packages/types/src/index.retheme.ts, packages/types/src/index.ts, packages/types/src/organization.ts, packages/types/src/pagination.ts, packages/types/src/user.ts
Changes:
PS: Review it per commit
=> chore(types,clerk-js,backend): Re-use common pagination types

.changeset/gold-islands-cover.md, .changeset/smart-suns-train.md, .changeset/stupid-suits-accept.md, integration/templates/react-vite/src/main.tsx, integration/testUtils/signInPageObject.ts, integration/tests/navigation.test.ts, packages/chrome-extension/README.md, packages/clerk-js/src/core/clerk.redirects.test.ts, packages/clerk-js/src/core/clerk.test.ts, packages/clerk-js/src/core/clerk.ts, packages/clerk-js/src/ui/router/PathRouter.tsx, packages/gatsby-plugin-clerk/src/GatsbyClerkProvider.tsx, packages/nextjs/src/app-router/client/ClerkProvider.tsx, packages/nextjs/src/app-router/client/useAwaitableNavigate.ts, packages/nextjs/src/pages/ClerkProvider.tsx, packages/remix/src/client/ClerkApp.tsx, packages/remix/src/client/RemixClerkProvider.tsx, packages/remix/src/client/useAwaitableNavigate.tsx, packages/types/src/clerk.ts, playground/vite-react-ts/src/App.tsx
When using path routing and clicking on a sign-in/up link, we get rerouted to a hash based url which automatically gets converted to a path based url (that's happening inside PathRouter.tsx). After that, when the back button is pressed, we arrive at the hash-based url that got converted and not at the actual previous page we were on.
Solution: Add a `routerReplace` prop to `<ClerkProvider/>` and use that for merging the fragment into the url.
Edit: This PR also includes the new `routerPush` prop that replaces the `navigate` prop for v5.
Before: 
https://github.com/clerkinc/javascript/assets/73396808/436b9029-22b0-47ad-9fb1-d93135eaa8dd
After:
https://github.com/clerkinc/javascript/assets/73396808/818ed562-01f0-4013-80a5-832d9e3dabb2
=> fix(clerk-js): Add push/replace props & replace state when merging fragment into url

.changeset/curly-parrots-camp.md, package-lock.json, packages/expo/package.json, packages/expo/src/polyfills/base64Polyfill.ts
This PR revert's the change about using the isomorphic `encode` and `decode` helpers from `@clerk/shared` to use the [base-64](https://www.npmjs.com/package/base-64) package.
=> fix(clerk-expo): Use base-64 package instead of isomorphic from @clerk/shared

.changeset/tiny-forks-sit.md, .github/workflows/ui-retheme-changes-reminder.yml, .prettierignore, packages/react/src/contexts/__tests__/ClerkProvider.test.tsx, packages/react/src/types.ts, packages/types/src/clerk.retheme.ts, packages/types/src/clerk.ts
Changes (review per commit for more info):
- Use `Without` generic to resolve issues with `Omit` and complex types
- Make `routerPush` and `routerReplace` options both required or both optional
- Improve performance of formatting CICD step by ignoring some git ignored or already formatted (since they are auto-generated) files
=> chore(types,clerk-react): Make `routerPush` / `routerReplace` both required or both optional

.changeset/mean-poets-bow.md, packages/clerk-js/src/core/clerk.ts, packages/react/src/errors.ts, packages/react/src/isomorphicClerk.ts, packages/types/src/clerk.ts
=> fix(clerk-react): Missing methods and properties from IsomorphicClerk (#2226)

.changeset/young-experts-attack.md, packages/clerk-js/src/core/clerk.ts
Backporting #2237 to the release/v4 branch
(cherry picked from commit 0551488fb67fc6ec117e8d19796094c4601013d2)
=> fix(clerk-js): Add setter for sdkMetadata to address error (#2237)

integration/models/applicationConfig.ts, integration/playwright.config.ts, integration/scripts/logger.ts
Improvements to the output you see when running our integration tests / Playwright:
- Color the text, not the text background. This improves readability
- Change the [`reporter`](https://playwright.dev/docs/test-reporters) to `line` in CI and `list` locally. Before we used `html` in CI but we didn't do anything with the output
Example of new output: https://github.com/clerk/javascript/actions/runs/7058789001/job/19215097030?pr=2243
Before:
After:
=> chore(integration): Improve Playwright logging

.changeset/strong-cows-sit.md, packages/clerk-js/src/ui.retheme/components/OrganizationProfile/OrganizationSettings.tsx, packages/clerk-js/src/ui.retheme/components/OrganizationProfile/__tests__/OrganizationSettings.test.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/OrganizationSettings.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/__tests__/OrganizationSettings.test.tsx
Users that are missing the `org:sys_domains:manage` should not be able to see the Add Domain button.
The route for adding a domain is already protected :)
=> fix(clerk-js): Hide Add domain button when user is missing `org:sys_domains:manage`

handshake.test.ts, handshakeTestConfigs.ts, integration/templates/next-app-router/package.json, jest.config.handshake.js, packages/backend/src/tokens/interstitialRule.ts, packages/backend/src/tokens/jwt/verifyJwt.ts, packages/backend/src/tokens/keys.ts, packages/backend/src/tokens/request.ts, packages/backend/src/tokens/verify.ts, playground/nextjs/middleware.ts, playground/nextjs/package.json
=> Client handshake tests

.changeset/late-flies-switch.md, packages/backend/README.md, packages/chrome-extension/README.md, packages/expo/README.md, packages/fastify/README.md, packages/gatsby-plugin-clerk/README.md, packages/nextjs/README.md, packages/react/README.md, packages/remix/README.md, packages/sdk-node/README.md
Set correct information on required Node.js and React versions in READMEs. This was missed in the previous updates when changing the minimum Node.js version to 18.18.0 and then down to 18.17.0
=> chore(*): Set correct info on required Node & React version

.changeset/moody-zoos-deliver.md, packages/clerk-js/src/core/test/fixtures.ts, packages/clerk-js/src/ui.retheme/components/OrganizationProfile/ActiveMembersList.tsx, packages/clerk-js/src/ui.retheme/components/OrganizationProfile/DomainList.tsx, packages/clerk-js/src/ui.retheme/components/OrganizationProfile/OrganizationProfileRoutes.tsx, packages/clerk-js/src/ui.retheme/components/OrganizationProfile/VerifiedDomainPage.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/ActiveMembersList.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/DomainList.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/OrganizationProfileRoutes.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/VerifiedDomainPage.tsx, packages/types/src/organizationMembership.ts
The `delete` permission has been merged with `manage`. We are still keeping `org:sys_profile:delete` as a separate permission.
=> chore(clerk-js,types): Remove system delete permission for domains and memberships

.changeset/funny-lamps-work.md, packages/backend/src/api/endpoints/UserApi.ts, packages/backend/src/api/resources/JSON.ts, packages/backend/src/api/resources/User.ts
- **[backend]**: Adds the `User.last_active_at` timestamp field in the user model, see [Backend API docs](https://clerk.com/docs/reference/backend-api/tag/Users#operation/GetUser).
- **[backend]**: Adds the `last_active_at_since` filtering parameter when requesting the list of users, see [Backend API docs](https://clerk.com/docs/reference/backend-api/tag/Users#operation/GetUserList).
- **[backend]**: Adds the `last_active_at` as a valid option for the `orderBy` parameter for the UserList request, see [Backend API docs](https://clerk.com/docs/reference/backend-api/tag/Users#operation/GetUserList).
=> feat: Introduce user latest session activity date and allow ordering & filtering when listing users 

.changeset/rare-bottles-sell.md, packages/clerk-js/src/ui.retheme/utils/passwordUtils.ts, packages/clerk-js/src/ui/utils/passwordUtils.ts
Fallback to fapi error when the password has been found in a data breach. This is a very small fix for support, will follow up with a ticket to fix the larger issue with this utility.
=> fix(clerk-js): Fallback to FAPI error message for password pwned case

.changeset/rare-bottles-sell.md, packages/clerk-js/src/ui/utils/passwordUtils.ts
Backport of  https://github.com/clerk/javascript/pull/2273
=> fix(clerk-js): Fallback to FAPI error message for password pwned case (#2273)

.changeset/bright-knives-jump.md, packages/types/src/api.ts
=> feat(types): Add `permissions` to `meta` field of fapi error

.changeset/bright-knives-jump.md, packages/types/src/api.ts
Backporting #2282 to the release/v4 branch
(cherry picked from commit 1db1f4068466d967df0de39f032a476ca8163651)
=> feat(types): Add `permissions` to `meta` field of fapi error (#2282)

.changeset/little-dolphins-scream.md, packages/backend/src/api/endpoints/UserApi.ts, packages/sdk-node/src/clerkClient.ts
Resolves
- https://github.com/clerk/javascript/issues/2281
- https://github.com/clerk/javascript/issues/2280
=> fix(backend,clerk-sdk-node): Resolve reported signature issues

.changeset/fast-swans-smile.md, packages/backend/src/api/endpoints/InvitationApi.ts
Backporting #2268 to the release/v4 branch
(cherry picked from commit de6519daa84732023bcfd74ad816a2654f457952)
=> fix(backend): Added missing types to create invitation (#2268)

.changeset/tall-roses-invent.md, packages/clerk-js/src/ui.retheme/components/SignIn/SignInStart.tsx, packages/clerk-js/src/ui/components/SignIn/SignInStart.tsx
When the instant password field was autofilled, we were showing it based on styles we were detecting, but we had no access to the value via js yet. This means we also need to make it focusable even if it does not have a value, but we have detected it has been autofilled.
=> fix(clerk-js): Make the instant password field focusable if autofilled

.changeset/little-dolphins-scream.md, packages/backend/src/api/endpoints/UserApi.ts, packages/sdk-node/src/clerkClient.ts
Backporting https://github.com/clerk/javascript/pull/2284 to the backport-release/v4-2284 branch
=> fix(backend,clerk-sdk-node): Resolve reported signature issues (#2284)

.changeset/smooth-baboons-shake.md, packages/backend/src/exports.test.ts, packages/backend/src/tokens/index.ts, packages/nextjs/src/server/__tests__/__snapshots__/exports.test.ts.snap, packages/sdk-node/src/__tests__/__snapshots__/exports.test.ts.snap
Removes both `TokenVerificationErrorAction` & `TokenVerificationErrorCode` from `@clerk/backend` exports as both are internal.
It also happens to support @flawnn's work/use-case in https://github.com/clerk/javascript/pull/1980, once we backport to `release/v4`.
=> chore(backend): Limit exposed token verification related errors

.changeset/cold-coins-listen.md, packages/clerk-js/src/core/clerk.test.ts, packages/clerk-js/src/ui.retheme/components/OrganizationProfile/__tests__/InviteMembersPage.test.tsx, packages/clerk-js/src/ui.retheme/components/OrganizationProfile/__tests__/OrganizationMembers.test.tsx, packages/clerk-js/src/ui.retheme/components/OrganizationProfile/__tests__/OrganizationProfile.test.tsx, packages/clerk-js/src/ui.retheme/components/OrganizationSwitcher/__tests__/OrganizationSwitcher.test.tsx, packages/clerk-js/src/ui.retheme/elements/__tests__/PlainInput.test.tsx, packages/clerk-js/src/ui.retheme/elements/__tests__/RadioGroup.test.tsx, packages/clerk-js/src/ui.retheme/hooks/__tests__/useCoreOrganization.test.tsx, packages/clerk-js/src/ui.retheme/hooks/__tests__/useCoreOrganizationList.test.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/__tests__/InviteMembersPage.test.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/__tests__/OrganizationMembers.test.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/__tests__/OrganizationProfile.test.tsx, packages/clerk-js/src/ui/components/OrganizationSwitcher/__tests__/OrganizationSwitcher.test.tsx, packages/clerk-js/src/ui/elements/__tests__/PlainInput.test.tsx, packages/clerk-js/src/ui/elements/__tests__/RadioGroup.test.tsx, packages/clerk-js/src/ui/hooks/__tests__/useCoreOrganization.test.tsx, packages/clerk-js/src/ui/hooks/__tests__/useCoreOrganizationList.test.tsx
Fixes `act` (and one `console.log`) output in Jest tests for `clerk-js`.
SDK-1054
=> fix(clerk-js): Fix act output in tests [SDK-1054]

.changeset/six-carrots-type.md, integration/testUtils/appPageObject.ts, packages/clerk-js/src/core/clerk.ts, packages/react/src/isomorphicClerk.ts, packages/types/src/clerk.ts
Deprecate `Clerk.isReady()` in favor of `Clerk.loaded`
=> chore(types,clerk-js,clerk-react): Deprecate `Clerk.isReady()` in favor of `Clerk.loaded`

.changeset/khaki-buttons-march.md, integration/testUtils/appPageObject.ts, packages/clerk-js/src/core/clerk.ts, packages/react/src/isomorphicClerk.ts, packages/types/src/clerk.retheme.ts, packages/types/src/clerk.ts
Drop deprecated `Clerk.isReady()` in favor of `Clerk.loaded`.
Deprecation PR: https://github.com/clerk/javascript/pull/2293
=> chore(types,clerk-js,clerk-react): Drop `Clerk.isReady()` in favor of `Clerk.loaded`

.changeset/selfish-books-matter.md, packages/nextjs/src/client-boundary/ClerkProvider.tsx, packages/nextjs/src/pages/ClerkProvider.tsx
Currently users of `@clerk/nextjs` and Next.js 12 (or older) are seeing an error when booting up their app:
```shell
error - ./node_modules/@clerk/nextjs/dist/esm/app-router/client/ClerkProvider.js:3:0
Module not found: Can't resolve 'next/navigation'
Import trace for requested module:
./node_modules/@clerk/nextjs/dist/esm/client-boundary/ClerkProvider.js
./node_modules/@clerk/nextjs/dist/esm/components.client.js
./node_modules/@clerk/nextjs/dist/esm/index.js
<path-to-where-they-mount-clerk-provider>
```
From what I can tell the error must have existed since https://github.com/clerk/javascript/pull/1840 was merged. But we only recently got a report about this so hopefully not too many people where impacted 🤞 
This only needs to be fixed for v4 (as v5 will drop Next.js 12), so that's why …
=> fix(nextjs): Use dynamic imports in ClerkProvider

playground/nextjs/middleware.ts
This PR fixes the Regex for public paths in the Next.js Playground
=> fix(repo): Fix incorrect regex for public paths in NextJs playground

.changeset/chatty-beans-fix.md, packages/shared/package.json
https://github.com/clerk/javascript/pull/2164 added `react-dom` to `@clerk/shared` as a peerDependency. We should also mark this peerDep as optional since `@clerk/shared` can also be used outside of React.
=> fix(shared): Add missing peerDependenciesMeta key

.changeset/witty-forks-cheer.md, packages/react/src/components/controlComponents.tsx, packages/react/src/isomorphicClerk.ts, packages/types/src/clerk.retheme.ts, packages/types/src/clerk.ts
…
Aligns return types for redirectTo methods in ClerkJS
Breaking Changes:
- `redirectToUserProfile` now returns `Promise<unknown>` instead of `void`
- `redirectToOrganizationProfile` now returns `Promise<unknown>` instead of `void`
- `redirectToCreateOrganization` now returns `Promise<unknown>` instead of `void`
- `redirectToHome` now returns `Promise<unknown>` instead of `void`
SDK-1037
=> chore(clerk-react,types): Align return types for redirectTo methods in ClerkJS [SDK-1037]

.npmrc, .vscode/settings.json, package-lock.json
This applies three changes to `.npmrc` and `.vscode/settings.json`:
- Add `legacy-peer-deps=false` since I have this globally set to `true` so every time I did `npm install` I changed the lockfile due to my global setting. By defining this in the repo it overrides my global setting and I'm not annoyed anymore 😬 
- Latest VSCode changed `codeActionsOnSave` and my editor always wants to change it: https://code.visualstudio.com/updates/v1_85#_code-actions-on-save-and-auto
- Remove cspell since we don't use it
=> chore(repo): Adjust npmrc and VSCode settings

.changeset/eight-badgers-speak.md, .changeset/fuzzy-years-taste.md, .changeset/metal-ears-cheat.md, .changeset/shiny-pumas-share.md, .changeset/small-cats-check.md, .changeset/sour-avocados-sin.md, integration/cleanup/cleanup.setup.ts, integration/testUtils/index.ts, packages/backend/README.md, packages/backend/src/api/endpoints/InvitationApi.ts, packages/backend/src/exports.test.ts, packages/backend/src/index.ts, packages/fastify/src/clerkClient.test.ts, packages/fastify/src/clerkClient.ts, packages/fastify/src/withClerkMiddleware.test.ts, packages/gatsby-plugin-clerk/src/ssr/clerkClient.ts, packages/nextjs/src/server/__tests__/__snapshots__/exports.test.ts.snap, packages/nextjs/src/server/clerkClient.ts, packages/remix/src/api/index.ts, packages/remix/src/ssr/authenticateRequest.ts, packages/sdk-node/src/clerkClient.ts, packages/sdk-node/src/clerkExpressRequireAuth.ts, packages/sdk-node/src/types.ts
Replace `Clerk` with `createClerkClient` [SDK-1058]
```js
import { Clerk } from '@clerk/backend';
const clerk = Clerk({ secretKey: '...' });
```
now becomes:
```js
import { createClerkClient } from '@clerk/backend';
const clerk = createClerkClient({ secretKey: '...' });
```
No longer returning `Clerk`. Please replace with `createClerkClient`
No longer returning `Clerk`. Please replace with `createClerkClient`
No longer returning `Clerk`. Please replace with `createClerkClient`
SDK-1058
=> chore(backend): Replace `Clerk` with `createClerkClient` [SDK-1058]

.changeset/thirty-chicken-divide.md, packages/nextjs/src/app-router/server/auth.ts
=> feat(nextjs): Accept `redirectUrl` as option for `auth().protect()` #2329

integration/.keys.json.sample, integration/README.md, integration/constants.ts, integration/presets/envs.ts, integration/presets/longRunningApps.ts, integration/templates/next-app-router/src/app/api/settings/route.ts, integration/templates/next-app-router/src/app/page.tsx, integration/templates/next-app-router/src/app/settings/auth-has/page.tsx, integration/templates/next-app-router/src/app/settings/auth-protect/page.tsx, integration/templates/next-app-router/src/app/settings/rcc-protect/page.tsx, integration/templates/next-app-router/src/app/settings/rsc-protect/page.tsx, integration/templates/next-app-router/src/app/settings/useAuth-has/page.tsx, integration/templates/next-app-router/src/app/switcher/page.tsx, integration/templates/next-app-router/src/middleware.ts, integration/testUtils/index.ts, integration/testUtils/organizationSwitcherPageObject.ts, integration/testUtils/usersService.ts, integration/tests/protect.test.ts, package.json
This PR introduces a integration test for `<Protect/>`, `useAuth().has()`, `auth().has()` and `auth().protect()`
- Uses the Nextjs template
- For now is using keys from staging as the feature is behind a feature flag in production
- Checks for `admin`, `viewer`, and a signed-out user
=> tests(repo): Integration tests for Protect

package.json
- this allows running `npm run yalc:all` work if `yalc` is not installed on the development machine
=> chore(repo): Fix npm run yalc:all

playground/nextjs/pages/session-examples/index.tsx, playground/nextjs/pages/user-examples/index.tsx
There were changes to `@clerk/clerk-react` in #2328 which weren't updated in the nextjs playground used as the retheme template.
=> fix(*): Update playground to support changes in #2328 for retheme

.changeset/polite-mice-live.md, packages/nextjs/src/server/errors.ts
Backports https://github.com/clerk/javascript/pull/2355
=> chore(nextjs): Fix quickstarts link in error msg

.changeset/weak-bears-cover.md, packages/sdk-node/src/clerkClient.ts
This error was silent due to an existing ts-expect-error that was added in the past for a different reason. To allow type checking for the import, we splitted it to 2 different lines and added the ts-expect-error only to the part that we wanted to.
=> fix(clerk-sdk-node): Fix forgotten Clerk instead of createClerkClient

.changeset/wise-scissors-know.md, .github/workflows/preview.retheme.yml, .github/workflows/preview.yml, packages/nextjs/src/server/constants.ts, packages/nextjs/src/utils/mergeNextClerkPropsWithEnv.ts
=> chore(nextjs): Rename to NEXT_PUBLIC_CLERK_JS_URL

.changeset/famous-penguins-bow.md, .changeset/modern-buses-sort.md, .changeset/modern-mayflies-sort.md, packages/clerk-js/src/core/clerk.redirects.test.ts, packages/clerk-js/src/core/clerk.test.ts, packages/clerk-js/src/core/clerk.ts, packages/clerk-js/src/core/devBrowser.ts, packages/clerk-js/src/core/resources/AuthConfig.ts, packages/nextjs/src/server/authMiddleware.ts, packages/react/src/isomorphicClerk.ts, packages/shared/src/__tests__/devbrowser.test.ts, packages/shared/src/devBrowser.ts, packages/types/src/authConfig.ts, packages/types/src/clerk.ts
Remove hashing and third-party cookie based session syncing for development instances in favor of URL-based session syncing.
SDK-645
=> refactor(clerk-js,nextjs,clerk-react,shared,types): Remove hashing and third-party cookie based session syncing for development instances. [SDK-645]

.changeset/dull-ants-argue.md, .changeset/mighty-rice-marry.md, .changeset/proud-trees-yell.md, packages/backend/README.md, packages/backend/src/__tests__/exports.test.ts, packages/backend/src/errors.ts, packages/backend/src/jwt/__tests__/signJwt.test.ts, packages/backend/src/jwt/__tests__/verifyJwt.test.ts, packages/backend/src/jwt/signJwt.ts, packages/backend/src/jwt/types.ts, packages/backend/src/jwt/verifyJwt.ts, packages/backend/src/tokens/__tests__/verify.test.ts, packages/backend/src/tokens/handshake.ts, packages/backend/src/tokens/request.ts, packages/backend/src/tokens/verify.ts, packages/backend/src/util/testUtils.ts, packages/nextjs/src/server/getAuth.ts, packages/types/src/utils.ts
Change return values of `signJwt`, `hasValidSignature`, `decodeJwt`, `verifyJwt`, `verifyToken`
to return `{ result, error }`. Example of keeping the same behaviour using those utilies:
```typescript
import { signJwt, hasValidSignature, decodeJwt, verifyJwt } from '@clerk/backend/jwt';
import { verifyToken } from '@clerk/backend/jwt';
const { result, error } = await signJwt(...)
if (error) throw error;
const { result, error } = await hasValidSignature(...)
if (error) throw error;
const { result, error } = decodeJwt(...)
if (error) throw error;
const { result, error } = await verifyJwt(...)
if (error) throw error;
const { result, error } = await verifyToken(...)
if (error) throw error;
```
=> chore(*): Improve @clerk/backend DX [Part 6 - token and jwt utils return values]

packages/nextjs/src/app-router/server/auth.ts
=> fix(nextjs): Type of `auth().protect()` when user is signed out

.changeset/lovely-experts-deny.md, packages/clerk-js/src/ui/components/OrganizationProfile/MemberListTable.tsx
After the release of Custom Roles, roles should always be dynamically fetched.
=> chore(clerk-js): Remove legacy roles fallback

.changeset/orange-files-end.md, packages/clerk-js/src/core/resources/OrganizationInvitation.ts, packages/clerk-js/src/core/resources/OrganizationMembership.ts, packages/clerk-js/src/core/resources/UserOrganizationInvitation.ts, packages/clerk-js/src/ui/common/Gate.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/InviteMembersForm.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/MemberListTable.tsx, packages/clerk-js/src/ui/utils/roleLocalizationKey.ts, packages/react/src/hooks/useAuth.ts, packages/types/src/clerk.ts, packages/types/src/json.ts, packages/types/src/jwt.ts, packages/types/src/jwtv2.ts, packages/types/src/organization.ts, packages/types/src/organizationInvitation.ts, packages/types/src/organizationMembership.ts, packages/types/src/session.ts, packages/types/src/ssr.ts, packages/types/src/userOrganizationInvitation.ts
`MemberRole` would always include the old role keys `admin`, `member`, `guest_member`. If developers still depend on them after the introduction of custom roles, the can provide them as their custom types for authorization.
=> chore(clerk-js,types,backend): Remove MemberRole Type

.changeset/thick-doors-smile.md, packages/clerk-js/src/ui/utils/useFormControl.ts
We still have a lot of places in clerk-js where we call `setError(undefined)` instead of `clearFeedback`
=> fix(clerk-js): Clear feedback when `undefined` is passed to `setError`

.changeset/thick-doors-smile.md, packages/clerk-js/src/ui/utils/useFormControl.ts
We still have a lot of places in clerk-js where we call `setError(undefined)` instead of `clearFeedback`
(cherry picked from commit bf09d18d6408ac89f8b9207d05e0f3660d27a6cf)
=> fix(clerk-js): Clear feedback when `undefined` is passed to `setError` (#2399)

.changeset/happy-panthers-approve.md, packages/clerk-js/src/ui/components/UserButton/UserButton.tsx, packages/clerk-js/src/ui/components/UserButton/UserButtonTopLevelIdentifier.tsx, packages/clerk-js/src/ui/components/UserButton/UserButtonTrigger.tsx
This PR makes the user name on `<UserButton showName />` part of the button's trigger.
It also changes the `border-radius` of the button in case `showName=true`.
Note ❗️: This change inverts the positions of `cl-userButtonTrigger` and `cl-userButtonBox`, the latter now being a child of the former. 
It fixes the issue #1625.
=> fix(clerk-js): Make user name on <UserButton showName /> clickable

.changeset/spotty-ravens-sleep.md, packages/backend/src/api/endpoints/UserApi.ts, packages/backend/src/api/resources/JSON.ts, packages/backend/src/api/resources/User.ts
=> fix(backend): Add `createOrganizationEnabled` param in User.update()

.changeset/beige-eyes-relate.md, packages/backend/src/api/resources/Enums.ts
This will be backported by #2405
=> fix(backend): Replace `OrganizationMembershipRole` with custom types for authorization

.changeset/rude-deers-fetch.md, packages/backend/src/api/__tests__/factory.test.ts, packages/backend/src/api/request.ts
This PR fixes an issue where errors returned from backend api requests are not converted to camelCase.
=> Parse backend errors that don't throw exceptions.

.changeset/selfish-flies-care.md, packages/clerk-js/src/core/clerk.test.ts, packages/clerk-js/src/core/clerk.ts, packages/clerk-js/src/ui/components/UserButton/__tests__/UserButton.test.tsx, packages/clerk-js/src/ui/contexts/ClerkUIComponentsContext.tsx, packages/react/src/components/SignOutButton.tsx, packages/react/src/isomorphicClerk.ts, packages/types/src/clerk.ts
Support the examples below:
```typescript
Clerk.signOut({ redirectUrl: '/' })
<SignOutButton redirectUrl='/' />
// uses Clerk.signOut({ redirectUrl: '/' })
<UserButton afterSignOutUrl='/after' />
// uses Clerk.signOut({ redirectUrl: '/after' })
<ClerkProvider afterSignOutUrl='/after' />
// uses Clerk.signOut({ redirectUrl: '/after' })
```
=> feat(clerk-js,types): Support `redirectUrl` param in `Clerk.signtOut()` and `Clerk#afterSignOutUrl` property

.changeset/silly-zebras-dream.md, packages/clerk-js/src/ui/components/SignIn/SignInAccountSwitcher.tsx, packages/clerk-js/src/ui/components/UserProfile/DeleteUserForm.tsx, packages/clerk-js/src/ui/contexts/ClerkUIComponentsContext.tsx, packages/react/src/components/controlComponents.tsx
Consolidate `afterSignOut*Url` options and avoid using Dashboard settings in ClerkJS.
Since this is part of v5 we don't need to have a rollout plan for the AP to release the consolidation. We will pass the afterSignOut*Url values retrieved from the Dashboard Settings to AP ClerkJS initialization to keep the current behaviour.
=> chore(clerk-js,types): Consolidate `afterSignOut*Url` options and avoid using Dashboard settings

.changeset/chatty-insects-run.md, packages/clerk-js/src/core/clerk.ts, packages/clerk-js/src/utils/__tests__/devbrowser.test.ts, packages/clerk-js/src/utils/cookies/devBrowser.ts, packages/clerk-js/src/utils/devBrowser.ts, packages/nextjs/src/server/authMiddleware.ts, packages/shared/.gitignore, packages/shared/package.json, packages/shared/src/__tests__/devbrowser.test.ts, packages/shared/src/devBrowser.ts, packages/shared/src/index.ts, packages/shared/subpaths.mjs
Support reading from `__clerk_db_jwt` and `__dev_session` query param the dev browser jwt. This is a preparation step to support Account Portal with v5 version.
2 more PRs will follow:
- in AP to bump to this `@clerk/nextjs` version
- in ClerkJS to replace `__dev_session` with `__clerk_db_jwt`
REVIEW IT PER COMMIT
SDK-746
=> chore(clerk-js,shared,nextjs): Support `__clerk_db_jwt` and `__dev_session` query params

.changeset/wise-clocks-type.md, packages/clerk-js/src/core/clerk.test.ts, packages/nextjs/src/server/authMiddleware.test.ts, packages/shared/src/__tests__/devbrowser.test.ts, packages/shared/src/devBrowser.ts
Should be released after Account Portal supports reading both search params.
This change is a preparation step for the v5 version where `__clerk_db_jwt` is only used.
=> feat(shared): Replace `__clerk_db_jwt` with `__dev_browser` in redirects

.changeset/tough-cherries-smoke.md, integration/testUtils/appPageObject.ts, packages/clerk-js/src/core/clerk.ts, packages/react/src/isomorphicClerk.ts
This reverts commit a624798102236f77a667d8da13363b77486640f8.
Using a `Clerk@v3` instance in `IsomorphichClerk` of `@clerk/clerk-react@v4` was failing to render the components because the latest v4 `IsomorphicClerk` depends on `Clerk.loaded` and Clerk@v3 does not have that property defined.
=> chore(clerk-js,clerk-react): Revert change to support ClerkJS@v3 in Account Portal with latest @clerk/nextjs

.changeset/happy-dolls-taste.md, packages/shared/src/telemetry/collector.ts
Browsers controlled via automation regularly set the `navigator.webdriver` property. This gives us a reasonable signal to disable telemetry collection in those cases. Tests and automation have the potential to send a large volume of events that won't be meaningful to us, so we're disabling collection.
fixes SDK-1127
=> fix(shared): Disable telemetry collection from browsers controlled via automation

.changeset/two-crews-talk.md, packages/clerk-js/src/ui/components/OrganizationProfile/RemoveDomainForm.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/VerifiedDomainForm.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/VerifyDomainForm.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/__tests__/OrganizationMembers.test.tsx, packages/clerk-js/src/ui/components/OrganizationSwitcher/OrganizationSwitcherPopover.tsx, packages/clerk-js/src/ui/components/OrganizationSwitcher/OrganizationSwitcherTrigger.tsx, packages/clerk-js/src/ui/components/OrganizationSwitcher/__tests__/OrganizationSwitcher.test.tsx, packages/clerk-js/src/ui/elements/OrganizationPreview.tsx, packages/clerk-js/src/ui/hooks/useFetch.ts, packages/clerk-js/src/ui/hooks/useFetchRoles.ts
In order to display a custom role we need to fetch them, so far we didn't have a robust way of fetching resources in clerk-js. A while back i had implemented `useFetch`, today I'm extending it in order to use a cache in order to fetch and share resources across components more efficiently.
When a component need to display the custom roles we had to fetch those each time the component was mounted.
We fetch the resource once, other subscribers will not trigger a refetch unless the data is stale (in cache for 2 mins).
The goal of this PR is to provide a good enough fix for the issue with an efficient solution. This is a bug in v4 as well, and a simple solution is better when backporting is necessary. If we think this solution is limiting, we should consider migrating to swr as its bundlesize …
=> fix(clerk-js): Fetching custom role in OrganizationSwitcher  with cache

.changeset/flat-bugs-visit.md, packages/clerk-js/src/ui/components/SignUp/SignUpEmailCodeCard.tsx, packages/clerk-js/src/ui/components/SignUp/SignUpPhoneCodeCard.tsx, packages/clerk-js/src/ui/components/SignUp/__tests__/SignUpVerifyEmail.test.tsx, packages/clerk-js/src/ui/components/SignUp/__tests__/SignUpVerifyPhone.test.tsx, packages/clerk-js/src/ui/hooks/useFetch.ts
https://github.com/clerk/javascript/assets/19269911/5a94d861-be69-4007-addd-bb239924f5b3
https://github.com/clerk/javascript/assets/19269911/5af85b9d-ea13-42c5-8b03-31d007278664
=> fix(clerk-js): Avoid triggering prepare verification twice

.changeset/thirty-cooks-cheer.md, packages/clerk-js/src/ui/hooks/__tests__/useCoreOrganization.test.tsx, packages/shared/src/react/hooks/useOrganization.tsx
This PR fixes a bug which would make the `useOrganization` with the `invitations` param to work unexpectedly.
=> fix(shared): Invitations depends on wrong options (useOrganization)

.changeset/giant-rice-crash.md, packages/clerk-js/src/ui/components/CreateOrganization/CreateOrganizationForm.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/ActionConfirmationPage.tsx
Since we increased the time-to-stale duration we've been having a few caching issues with the fetched resources and their respective UI.
This PR solves those issues, by requesting a revalidation when a user deletes, leaves or creates an organization. The cases for accepting/rejecting invitations & suggestions should already be handled.
=> fix(clerk-js): Revalidate when user deletes organization

.changeset/thirty-cooks-cheer.md, packages/clerk-js/src/ui/hooks/__tests__/useCoreOrganization.test.tsx, packages/shared/src/react/hooks/useOrganization.tsx
Backporting #2472 to the release/v4 branch
(cherry picked from commit 38d8b3e8a0387bcf0b9c8d16e3bbfcfe9b643ca2)
=> fix(shared): Invitations depends on wrong options (useOrganization) (#2472)

.changeset/dirty-sheep-warn.md, packages/shared/src/__tests__/telemetry.test.ts, packages/shared/src/telemetry/collector.ts, packages/shared/src/telemetry/events/component-mounted.ts, packages/shared/src/telemetry/types.ts
Introduces event-specific sampling rates, and adds a 0.1 (10%) sampling rate on the `COMPONENT_MOUNTED` event. This ensures we won't get flooded with a large volume of events in the case where they are fired in a hot code path.
=> feat(shared): Introduce event-specific telemetry sampling rates

.changeset/lucky-snails-help.md, packages/backend/src/api/factory.test.ts, packages/backend/src/api/request.ts
This was caused by API errors being parsed twice. Once in the response  error handling code and again when initializing a new `ClerkAPIResponseError`. 
This is was fixed in v5 with the removal of `ClerkAPIResponseError`. 
`ClerkAPIResponseError` is also used by clerk-js the change was to the backend package.
=> Fix backend error message details

.changeset/giant-rice-crash.md, packages/clerk-js/src/ui/components/CreateOrganization/CreateOrganizationForm.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/ActionConfirmationPage.tsx
=> fix(clerk-js): Revalidate when user deletes organization (#2473)

.changeset/cold-points-carry.md, package-lock.json, packages/shared/package.json, packages/shared/scripts/postinstall.mjs
One thing I noticed over the holiday break was that we still print the message in CI even though it's not actionable and relevant. With a simple check we can hide it.
This PR adds a new dep to `shared`: https://github.com/unjs/std-env
It's a really helpful package and we can refactor some of our code in the future to use more of this. We might want to re-export it from `shared` in the future, too. But to keep this PR slim I didn't do that just yet.
Bundle size wise it's a small addition with tree-shaking: https://bundlejs.com/?q=std-env&treeshake=%5B%7B+isCI+%7D%5D
=> fix(shared): Do not display telemetry notice in CI

.changeset/spotty-nails-double.md, packages/react/src/hooks/__tests__/__snapshots__/useRoutingProps.test.tsx.snap, packages/react/src/hooks/__tests__/useRoutingProps.test.tsx, packages/react/src/hooks/useRoutingProps.ts
Avoid raising error when eg `<SignIn />` and `<SignUp />` path is passed from the env via the ClerkProvider options hook.
=> fix(clerk-react): Avoid error on `useRoutingOptions()` when `path` passed from options

.changeset/modern-plums-invent.md, packages/clerk-js/src/core/resources/Organization.ts, packages/clerk-js/src/core/resources/OrganizationMembership.ts, packages/clerk-js/src/core/resources/OrganizationSuggestion.ts, packages/clerk-js/src/core/resources/UserOrganizationInvitation.ts
Remove fallback data and allow promise to throw for paginated endpoint methods.
Affected methods:
- Organization.getDomains
- Organization.getInvitations
- Organization.getMembershipRequests
- Organization.getMemberships
- User.getOrganizationInvitations
- User.getOrganizationSuggestions
- User.getOrganizationMemberships
The react hooks will continue to fallback to `total_count:0` and `data = []` in case of an error, but the `isError` property will be correctly populated as `true`
=> chore(clerk-js): Remove fallback data for paginated endpoint methods

.changeset/loud-tomatoes-jam.md, packages/clerk-js/src/ui/elements/Navbar.tsx
When the external links were included as part of custom pages the clerk-js router would break as it couldn't match against it. Previously adding external links to custom pages would cause all pages that are defined below it to throw an error.
=> fix(clerk-js): Exclude external custom links from route matching

.changeset/happy-beers-push.md, packages/clerk-js/src/core/clerk.ts, packages/clerk-js/src/core/fapiClient.ts
Detects whether clerk-js runs in the context of a known framework and appends `__clerk_framework_hint` and `__clerk_framework_version`, if available. 
Currently, NextJs is the only framework that can be detected. We will add support for the rest in an upcoming PR.
=> Telemetry: Append `__clerk_framework_hint` if a known framework is detected

.changeset/many-moons-matter.md, packages/backend/src/api/resources/JSON.ts, packages/backend/src/errors.ts, packages/backend/src/tokens/authStatus.ts
=> feat(backend): Replace enums with `as const` objects

.changeset/early-carpets-fly.md, packages/backend/src/api/resources/User.ts
User FAPI and User BAPI cannot be fully aligned, but we should aim for keeping their signature as similar as possible.
=> fix(backend): Fix minor misalignment's with the User FAPI and BAPI classes

.changeset/tender-phones-explain.md, packages/react/src/hooks/__tests__/__snapshots__/useRoutingProps.test.tsx.snap, packages/react/src/hooks/__tests__/useRoutingProps.test.tsx, packages/react/src/hooks/useRoutingProps.ts
This PR error when path is passed from context and a routing strategy other than `path` is passed as a prop.
=> fix(clerk-react): Fix routing strategy priority when it's directly passed on the component

.changeset/few-rings-push.md, integration/tests/handshake.test.ts, packages/backend/src/tokens/request.ts
Fixes a bug in the handshake flow that would cause an unhandled error if the handshake payload or session token in the handshake payload fails to be verified.
=> fix(backend): Fix unhandled handshake error

.changeset/wild-emus-whisper.md, packages/nextjs/internal/package.json, packages/nextjs/package.json, packages/nextjs/src/client-boundary/controlComponents.ts, packages/nextjs/src/internal.ts
Export MultisessionAppSupport from @clerk/nextjs/internal
=> feat(nextjs): Export MultisessionAppSupport from @clerk/nextjs/internal

.changeset/thin-coats-serve.md, packages/backend/package.json, packages/backend/src/api/__tests__/factory.test.ts, packages/backend/src/api/request.ts, packages/backend/src/constants.ts, packages/backend/src/tokens/__tests__/keys.test.ts, packages/backend/src/tokens/__tests__/verify.test.ts, packages/backend/tsup.config.test.ts, packages/backend/tsup.config.ts, packages/fastify/src/__snapshots__/clerkClient.test.ts.snap, packages/fastify/src/clerkClient.ts, packages/gatsby-plugin-clerk/src/ssr/clerkClient.ts, packages/nextjs/src/server/__tests__/clerkClient.test.ts, packages/nextjs/src/server/clerkClient.ts, packages/remix/src/ssr/authenticateRequest.ts, packages/sdk-node/src/clerkClient.ts
Changes:
- Update `@clerk/backend` test builds to use tsup to supporting testing with build-time constants
- Replace `Clerk-Backend-SDK` header with `User-Agent` for all server Clerk packages
- Add Clerk package version for each SDK in `User-Agent` header
=> feat(backend): Use `User-Agent` header with package name and version in BAPI requests

.changeset/eight-cherries-tan.md, packages/backend/src/api/endpoints/SessionApi.ts, packages/backend/src/tokens/authObjects.ts
Change `SessionApi.getToken()` to return consistent `{ data, errors }` return value  and fix the `getToken()` from requestState to have the same return behavior as v4  (return Promise<string> or throw error).
This change fixes issues with `getToken()` in `@clerk/nextjs` / `@clerk/remix` / `@clerk/fastify` / `@clerk/sdk-node` / `gatsby-plugin-clerk`:
Example:
```typescript
import { getAuth } from '@clerk/nextjs/server';
const { getToken } = await getAuth(...);
const jwtString = await getToken(...);
```
The change in `SessionApi.getToken()` return value is a breaking change, to keep the existing behavior use the following:
```typescript
import { ClerkAPIResponseError } from '@clerk/shared/error';
const response = await clerkClient.sessions.getToken(...);
if (response.errors) {
const { …
```
=> fix(backend): Fix `getToken()` from `getAuth()` return value in v5

.changeset/rich-years-help.md, packages/backend/src/api/endpoints/EmailApi.ts
Add a deprecation warning for `EmailAPI.createEmail`.
PR that removes the method for v5 https://github.com/clerk/javascript/pull/2548
=> feat(backend): Deprecate createEmail

.changeset/witty-shirts-dream.md, packages/react/src/errors/messages.ts, packages/react/src/hooks/__tests__/__snapshots__/useRoutingProps.test.tsx.snap, packages/react/src/hooks/__tests__/useRoutingProps.test.tsx, packages/react/src/hooks/useRoutingProps.ts
Apply the following changes to components with routing props:
- default is `routing="path"` and `path` prop is required to be set via env or context
- when `routing="hash"` or `routing="virtual"` is set the implicit (via env or context) `path` option is ignored
- when `routing="hash"` or `routing="virtual"` then `path` prop is not allowed to be set
Examples of components with routing props:
- `<CreateOrganization />`
- `<OrganizationProfile />`
- `<SignIn />`
- `<SignUp />`
- `<UserProfile />`
=> fix(clerk-react): Improve error message and checks for routing strategies

.changeset/five-lamps-beam.md, packages/backend/README.md, packages/clerk-js/README.md, packages/gatsby-plugin-clerk/README.md, packages/nextjs/README.md, packages/remix/README.md, packages/sdk-node/README.md
=> chore(repo): Update READMEs

.changeset/neat-poets-push.md, packages/clerk-js/src/core/resources/Session.ts
Ensure that the session cookie stays in sync with the cookie returned from getToken().
=> fix(clerk-js): sync session cookie from cache

.changeset/curly-toes-complain.md, packages/clerk-js/src/ui/components/UserProfile/MfaPhoneCodeScreen.tsx
https://github.com/clerk/javascript/assets/19269911/5337b0f2-2ce8-4d38-9d72-d97781b1b191
https://github.com/clerk/javascript/assets/19269911/556d95c3-adbc-40b1-a9d3-1b8ffde403bb
=> fix(clerk-js): Hide backup codes when adding phone_code mfa and instance setting is off

.changeset/rare-bulldogs-cheer.md, packages/clerk-js/src/ui/primitives/Input.tsx
We would like to support special characters like "ö" in emails. Using type="email" does not allow that.
_I've verified that password managers will still correctly store the email._
=> fix(clerk-js): Use pattern for email input fields

.changeset/giant-bags-stare.md, packages/backend/src/api/request.ts, packages/clerk-js/src/core/resources/Error.ts, packages/clerk-js/src/core/resources/Verification.ts, packages/clerk-js/src/core/warnings.ts, packages/nextjs/src/server/errors.ts
Update `@clerk/nextjs` error messages to refer to `clerkMiddleware()` and deprecated `authMiddleware()` and fix a typo in `cannotRenderSignUpComponentWhenSessionExists` error message.
There was also some internal refactoring for `parseError` helper.
=> fix(*): Apply fixes reported before ship week

.changeset/afraid-experts-eat.md, .changeset/strange-trains-bow.md, packages/backend/src/tokens/__tests__/request.test.ts, packages/backend/src/tokens/authObjects.ts, packages/remix/src/ssr/authenticateRequest.ts, packages/remix/src/ssr/getAuth.ts, packages/remix/src/ssr/loadOptions.ts, packages/remix/src/ssr/rootAuthLoader.ts, playground/remix-node/app/entry.server.tsx, playground/remix-node/app/root.tsx, playground/remix-node/app/routes/sign-in.$.tsx, playground/remix-node/package.json, playground/remix-node/remix.config.js
As part of this PR the following changes were applied:
- Dropped `user`, `session`, `organization` resources from the SignedOut authObject
- Fix setting the `user`, `session`, `organization` resources in remix `remix`
=> Fix(backend,remix): Issues with v5 and resources loading in request object

.changeset/neat-crabs-know.md, packages/sdk-node/src/types.ts
Changes the `request.auth` type from `LegacyAuthObject` to `AuthObject`.
=> Fix(clerk-sdk-node): `request.auth` type

.changeset/unlucky-frogs-tap.md, packages/backend/src/jwt/__tests__/verifyJwt.test.ts, packages/backend/src/jwt/signJwt.ts, packages/backend/src/jwt/types.ts, packages/backend/src/jwt/verifyJwt.ts, packages/backend/src/tokens/handshake.ts, packages/backend/src/tokens/request.ts, packages/backend/src/tokens/verify.ts, packages/nextjs/src/server/createGetAuth.ts
Affected helpers:
- signJwt
- verifyJwt
- hasValidSignature
- decodeJwt
- verifyToken
=> fix(nextjs,backend): Replace `error` with `errors` for jwt / token helpers return value

.changeset/gold-shrimps-behave.md, packages/clerk-js/src/core/errors.ts, packages/clerk-js/src/core/resources/OrganizationMembership.ts
The only class that overrides the reload method from Base is OrganizationMembership. And it is broken, because the logic inside it no longer makes sense with the paginated endpoints. There is no endpoint to fetch by id so we need to notify developers with a descriptive error
=> fix(clerk-js): Throw error for unsupported method `OrganizationMembership.reload`

.changeset/clever-hounds-flow.md, packages/clerk-js/src/core/devBrowser.test.ts, packages/clerk-js/src/core/devBrowser.ts, packages/clerk-js/src/core/errors.ts
This fix informs users of legacy Clerk development instances to migrate to URL Based Sessing syncing if they want to upgrade to ClerkJS v5
=> fix(clerk-js): Throws FAPI errors during dev browser creation

.changeset/sweet-ladybugs-sneeze.md, packages/backend/src/api/endpoints/UserApi.ts
Add `password_hasher` and `password_digest` to `users.updateUser(userId, params)`
=> fix(backend): Add UserPasswordHashingParams to updateUser

.changeset/tender-wasps-hope.md, packages/clerk-js/src/core/clerk.ts, packages/clerk-js/src/utils/getClerkQueryParam.ts
On load of clerk-js, clean up any handshake related query parameters. These can exist if we trigger a flow that returns the handshake payload from a client-side-only application.
In the future, we can attempt to detect if the host SDK has SSR support, and if not we can avoid sending the handshake payload. This will likely require passing additional context to FAPI calls.
=> fix(clerk-js): Remove handshake paramters when clerk-js loads

.changeset/early-cars-cross.md, packages/nextjs/src/client-boundary/uiComponents.tsx, packages/nextjs/src/client-boundary/usePathnameWithoutCatchAll.tsx
Detailed explanation is in the comments, please take a look at the code itself.
This PR allows using all components with path routing without passing the path manually
=> feat(nextjs): Infer the path the component is mounted at automatically in pages and app router

.changeset/gentle-radios-shout.md, integration/cleanup/cleanup.setup.ts, integration/testUtils/usersService.ts, integration/tests/protect.test.ts, packages/backend/src/api/__tests__/factory.test.ts, packages/backend/src/api/endpoints/OrganizationApi.ts, packages/backend/src/api/endpoints/UserApi.ts, packages/backend/src/api/request.ts, packages/backend/src/api/resources/Deserializer.ts, packages/backend/src/index.ts, packages/backend/src/jwt/index.ts, packages/backend/src/jwt/legacyReturn.ts, packages/backend/src/jwt/signJwt.ts, packages/backend/src/tokens/authObjects.ts, packages/backend/src/tokens/handshake.ts, packages/backend/src/tokens/request.ts, packages/backend/src/tokens/verify.ts, packages/backend/src/util/decorateObjectWithResources.ts, packages/nextjs/src/app-router/server/currentUser.ts, packages/nextjs/src/server/buildClerkProps.ts, packages/nextjs/src/server/createGetAuth.ts, packages/sdk-node/examples/express/src/runtime-keys-middleware.ts, packages/sdk-node/examples/node/src/organizations.ts, packages/sdk-node/examples/node/src/sessions.ts, packages/sdk-node/examples/node/src/users.ts
Revert changing the `{ data, errors }` return value of the following helpers. Instead those helpers return the values or  throw error (same behaviour with v4):
- `import { verifyToken } from '@clerk/backend'`
- `import { signJwt, hasValidSignature, decodeJwt, verifyJwt } from '@clerk/backend/jwt'`
- BAPI `clerkClient` methods eg (`clerkClient.users.getUserList(...)`)
Also fixed the following BAPI methods to return the correct PaginatedResources. This is a breaking change and converts the return value of the following methods from `T[]` to `{ data: T[], totalCount: number }`:
- `clerkClient.users.getOrganizationMembershipList(...)`
- `clerkClient.organization.getOrganizationList(...)`
- `clerkClient.organization.getOrganizationInvitationList(...)`
=> fix(backend,nextjs): Revert `{ data, errors }` return values to v4 format for clerkClient methods and jwt/token helpers

.changeset/dry-bugs-flash.md, packages/nextjs/src/app-router/server/auth.ts
Adjust how we import `next/navigation` in the `auth()` helper to ensure our package can be safely imported in Next.js v12. The [current recommended approach](https://clerk.com/docs/references/nextjs/usage-with-older-versions) to use `webpack.IgnorePlugin` doesn't when the package is externally required in a CJS environment.
=> fix(nextjs): Ensure package works with next 12

.changeset/calm-socks-cough.md, .changeset/eight-pots-guess.md, .changeset/tame-forks-refuse.md, packages/backend/src/index.ts, packages/nextjs/src/server/index.ts, packages/remix/src/ssr/index.ts
Export Backend API resources
- backend
```ts
import { Organization } from '@clerk/backend'
```
- Nexjts
```ts
import { Organization } from '@clerk/nextjs/server'
```
- Remix
```ts
import { Organization } from '@clerk/remix/ssr'
```
=> fix(backend): Expose resources types

.changeset/tough-peas-teach.md, packages/clerk-js/src/ui/components/OrganizationProfile/DomainList.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/OrganizationMembersTabInvitations.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/OrganizationMembersTabRequests.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/OrganizationProfileRoutes.tsx, packages/clerk-js/src/ui/contexts/ClerkUIComponentsContext.tsx
Backport of #2600 (Code is similar, not the same as the PR for v5, but they solve the same problem)
=> fix(clerk-js): Take account custom pages when redirecting inside OrganizationProfile

.github/workflows/lock-threads.yml
We have a lot of issues that have been awaiting reproduction for months - in an effort to keep our issues section clean, we'd like to close these issues faster. If it's taking a while to produce a reproduction, that's ok, we can always re-open once one is provided.
=> Close issues without a reproduction specified after 8 days

.changeset/chilly-crews-perform.md, packages/clerk-js/src/utils/cookies/handler.ts
Update how cookies are set such that they can be read from applications rendered in frames.
=> fix(clerk-js): Update cookie attributes for iframes

.changeset/twenty-lamps-rule.md, packages/clerk-js/src/core/clerk.ts
For the OAuth2 IDP flow, we should not redirect when the referrer is the sign up url. This way, a second factor can be completed after a first factor like email verification link. Previously, users were being redirected back to `FAPI /oauth/authorize` prematurely. This change ensures that users will not be redirected as such and have the chance to complete their second factor verification, like phone code.
Fixes CORE-1567
Video of fix below (there's a jump in the middle because I cut out retrieving the email link from my inbox):
https://github.com/clerk/javascript/assets/27433835/63e4ec43-1107-4c90-8ee5-f9196be7210c
Previously, the user would be redirected back to the sign in page without being able to complete sign up.
=> fix(clerk-js): Fix FAPI initiated redirect flow for OAuth2 IDP flow with email_link verification

.github/workflows/alpha.elements.yml
Follow up to https://github.com/clerk/javascript/pull/2686 - the dry run worked in https://github.com/clerk/javascript/actions/runs/7726668169/job/21063401975 so 🤞 that this now will also work
=> chore(repo): Remove dry-run from Clerk Elements Alpha workflow

.changeset/smooth-numbers-shout.md, packages/backend/src/api/resources/Enums.ts, packages/clerk-js/src/ui/utils/test/fixtures.ts, packages/types/src/oauth.ts
Add required types for X/Twitter v2.
=> feat(types): Add support for X/Twitter v2 OAuth provider

.changeset/slow-carrots-eat.md, packages/clerk-js/src/utils/cookies/handler.ts
```
__client_uat is samesite=none
__session is samesite=lax
__clerk_db_jwt is samesite=lax
__initted is samesite=lax
```
Fixes https://github.com/clerk/javascript/pull/2668
=> fix(clerk-js): Fix same site in ClerkJS cookies

.changeset/twenty-lamps-rule.md, packages/clerk-js/src/core/clerk.ts
Backporting #2677 to the release/v4 branch
(cherry picked from commit 750337633a07bf3bb92d015f558ead2bfdca8613)
=> fix(clerk-js): Fix FAPI initiated redirect flow for OAuth2 IDP flow with email_link verification (#2677)

.changeset/spotty-penguins-admire.md, packages/clerk-js/src/ui/primitives/Input.tsx
Fixes the error in the browser console
=> fix(clerk-js): Escape characters in pattern for inputs of [type="email"]

.changeset/chilled-bikes-rule.md, integration/templates/next-app-router/package.json, packages/backend/src/constants.ts, packages/backend/src/createRedirect.ts, packages/fastify/src/__snapshots__/constants.test.ts.snap, packages/nextjs/src/app-router/server/auth.ts, packages/nextjs/src/server/authMiddleware.ts, packages/nextjs/src/server/clerkMiddleware.test.ts, packages/nextjs/src/server/clerkMiddleware.ts, packages/nextjs/src/server/protect.ts, packages/nextjs/src/server/utils.ts, packages/nextjs/src/utils/response.ts
The `auth().redirectToSignIn()` helper no longer needs to be explicitly returned when called within the middleware. The following examples are now equivalent:
```js
// Before
export default clerkMiddleware(auth => {
if (protectedRoute && !auth.user) {
return auth().redirectToSignIn()
}
})
// After
export default clerkMiddleware(auth => {
if (protectedRoute && !auth.user) {
auth().redirectToSignIn()
}
})
```
Calling `auth().protect()` from a page will now automatically redirect back to the same page by setting `redirect_url` to the request url before the redirect to the sign-in URL takes place.
=> v5: NextJS improvements

.changeset/eight-dolphins-float.md, integration/templates/next-app-router/package.json, packages/nextjs/src/app-router/client/useAwaitableNavigate.ts
Attempting to avoid CSR de-opt due to `useSearchParams()` usage. Refactors `useAwaitableNavigate()` to rely on `useTransition` instead of Next's route state hooks. This avoids any potential de-opt and provides a more reliable implementation by relying on React's native transition behavior.
Fixes SDK-1266
=> chore(nextjs): Remove useSearchParams usage

.changeset/late-geckos-impress.md, packages/clerk-js/src/ui/components/OrganizationSwitcher/OrganizationSwitcherPopover.tsx, packages/clerk-js/src/ui/contexts/ClerkUIComponentsContext.tsx, packages/types/src/clerk.ts
`skipInvitationScreen` should be something that affects the flow of creating an organization. `<CreateOrganization/>` and `<OrganizationList/>` already handles this correctly. This PR adds this functionality to `<OrganizationSwitcher/>` as well.
This implementation is compatible with v4 and does not introduce breaking changes and will be backported.
Grouping `skipInvitationScreen` and `afterCreateOrganizationUrl` under `createOrganizationProps` could be part of a followup PR only for v5.
=> feat(clerk-js): Accept `skipInvitationScreen` as a prop from OrganizationSwitcher

.changeset/friendly-dryers-rush.md, packages/clerk-js/src/ui/components/OrganizationList/OrganizationListPage.tsx, packages/clerk-js/src/ui/elements/Card.tsx
=> fix(clerk-js): Add padding to app logo inside OrganizationList

packages/nextjs/src/utils/serverRedirectWithAuth.ts
Avoid polluting the `@clerk/nextjs/server` subpath with client related imports.
=> fix(nextjs): Use shared subpath import in server related utils to avoid bundling unused helpers

.changeset/curly-cycles-march.md, packages/clerk-js/src/ui/components/CreateOrganization/CreateOrganizationForm.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/AddDomainForm.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/ProfileForm.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/VerifyDomainForm.tsx, packages/clerk-js/src/ui/components/UserProfile/DeleteUserForm.tsx, packages/clerk-js/src/ui/primitives/Input.tsx, packages/clerk-js/src/ui/primitives/hooks/useFormControl.tsx, packages/clerk-js/src/ui/utils/useFormControl.ts
Add data-1p-ignore to input fields that do not benefit from password manager suggestions.
=> chore(clerk-js): Use data-1p-ignore for better UX in Clerk Components with 1password

.changeset/witty-eggs-punch.md, packages/clerk-js/src/ui/elements/ApplicationLogo.tsx
Go to [SDK 1298](https://linear.app/clerk/issue/SDK-1298/logo-in-sign-in-component-is-squished) and visit the preview URL with Firefox or Safari. The application logo should be too wide/squished.
Apply the fix of this PR to the `<img />` with `.logoImage` class and it should look fine.
=> fix(clerk-js): Give application logo correct CSS width

.changeset/witty-eggs-punch.md, packages/clerk-js/src/ui/elements/ApplicationLogo.tsx
Backporting #2735 to the release/v4 branch
(cherry picked from commit 11fbfdeec6aa609d02d23d997b319c94793e452f)
=> fix(clerk-js): Give application logo correct CSS width (#2735)

.changeset/yellow-walls-worry.md, packages/backend/src/util/__tests__/path.test.ts, packages/backend/src/util/path.ts
Internally when `joinPaths` was used to join strings that included a url protocol like `https://` the utility function would remove the duplicate `/` from the protocol resulting in a string with this form `'https:/api.lclclerk.com/v1/organizations/org_2YRy2Bcrc05EMTY0nMY3qHTjbwj'`
When this string was passed in a `URL` constructor like `new URL(...)` the URL would either be fixed automatically or throw an "Invalid URL" error. 
I believe it came down to node version and different implementations of the URL class under the hood. In any case this PR ensures that absolute url string that is generated from `joinPaths` will keep the protocol intact.
Fixes https://github.com/clerk/javascript/issues/2706
=> fix(backend): Preserve url protocol when joining paths

.changeset/yellow-walls-worry.md, packages/backend/src/util/path.test.ts, packages/backend/src/util/path.ts
Backporting #2745 to the release/v4 branch
(cherry picked from commit c2b98274970bac5af33c9bb2e84c70ad90225180)
=> fix(backend): Preserve url protocol when joining paths (#2745)

.changeset/shiny-games-buy.md, package-lock.json, packages/clerk-js/package.json, packages/react/package.json, packages/react/src/utils/__tests__/versionSelector.test.ts, packages/react/src/utils/versionSelector.ts
The semver package doesn't provide exports map in its package.json. Vitest is ESM-only and relies more on these things whereas Jest is more forgiving. Instead of tweaking build config for clerk-react and given that we only rely on major() and prerelease() and the bundle-size considerations, we replaced semver with custom regexes
=> fix(clerk-react): Replace semver with custom regex in versionSelector

.changeset/sixty-lions-obey.md, packages/shared/src/react/hooks/useOrganization.tsx, packages/shared/src/react/hooks/useOrganizationList.tsx, packages/shared/src/react/hooks/usePagesOrInfinite.ts, packages/shared/src/react/types.ts
This PR gives access to the `error` object for consumer of our organization hooks
=> fix(shared): Return api errors from organization hooks

.changeset/brown-lemons-film.md, packages/react/src/contexts/ClerkContextProvider.tsx, packages/react/src/isomorphicClerk.ts
In case of mounting-unmounting-mounting the `IsomorphicClerk.addOnLoaded` would not fire correctly, hence `derivedState` would return the initialState instead of the client side state.
In addition to the above fix, we are now cleaning up the IsomorphicClerk instance when the provider is unmounted.
=> fix(clerk-react): Properly fire onLoad event when clerk-js is already loaded

.changeset/brown-lemons-film.md, packages/react/src/contexts/ClerkContextProvider.tsx, packages/react/src/isomorphicClerk.ts
Backporting #2757 to the release/v4 branch
(cherry picked from commit 6ac9e717a7ce8f09c1604f324add5e7e02041c07)
=> fix(clerk-react): Properly fire onLoad event when clerk-js is already loaded (#2757)

.changeset/olive-files-listen.md, packages/clerk-js/src/core/clerk.redirects.test.ts, packages/clerk-js/src/core/clerk.test.ts, packages/clerk-js/src/core/clerk.ts, packages/clerk-js/src/ui/router/BaseRouter.tsx, packages/nextjs/src/app-router/client/useAwaitableNavigate.ts, packages/nextjs/src/client-boundary/usePathnameWithoutCatchAll.tsx, packages/types/src/clerk.ts
A few things going on in this PR.
When using `router.push` from `next/navigation` (app router) the components in the current page will unmount before the navigation. In our case, if a component uses path-routing all internal navigations (for example `/user` > `/user/security` use `router.push` but that means that the component will unmount and immediately mount again in the new URL.
However, our components are client components and they can support client-side-only navigations. This type of navigation is usually called shallow navigation. App router apps can use the native `window.history` APIs in order to trigger shallow navigations.
We need to differentiate between internal navigations (navigations within the component) and external navigations (navigation outside the scope of the …
=> fix(nextjs,clerk-js,types): Stop Clerk component flickering when used in App Router

.changeset/dull-seals-type.md, packages/fastify/src/withClerkMiddleware.test.ts, packages/fastify/src/withClerkMiddleware.ts
Introduce handshake handling and add `auth-status` in response headers.
=> feat(fastify): Introduce handshake

.changeset/brown-masks-wonder.md, packages/backend/src/api/endpoints/UserApi.ts
This PR adds the `unbanUser`, `lockUser` and `unlockUser` methods in the @clerk/backend package in order for developers to perform these administrative operations.
BAPI had them already in place, see [documentation](https://clerk.com/docs/reference/backend-api/tag/Users#operation/UnbanUser)
=> feat(backend): Add `unbanUser`, `lockUser`,`unlockUser` to UserApi

.github/workflows/lock-threads.yml
This is an attempt of fixing our current behavior of the stale bot. If you look at https://github.com/clerk/javascript/issues/2137 you'll see that the robots 🤖 fight each other. You can see that in this log here: https://github.com/clerk/javascript/actions/runs/7784119012/job/21224032011
Since https://github.com/clerk/javascript/pull/2641 we run the stale action twice to have different behavior for everything vs. `needs-reproduction` issues. My fix here in this PR ensures that they both only run on issues they are intended for.
=> chore(repo): Adjust stale bot action

.changeset/heavy-phones-rest.md, .changeset/tiny-beds-yell.md, packages/clerk-js/src/ui/contexts/ClerkUIComponentsContext.tsx
Use signUpUrl from context as email-link redirectUrl in sign-up flow.
For more information check https://github.com/clerk/javascript/pull/2727 in which the fix is applied for sign-in.
=> Apply email link change to sign up

.changeset/happy-points-relax.md, packages/clerk-js/src/core/devBrowser.ts, packages/shared/src/__tests__/devbrowser.test.ts, packages/shared/src/devBrowser.ts, packages/shared/src/index.ts
Update the debBrowser handling logic to remove hash-based devBrowser JWTs from the URL. Even if v5 does not use the hash-based JWT at all, we still need to remove it from the URL in case clerk-js is initialised on a page after a redirect from an older clerk-js version, such as an AccountPortal using the v4 components
=> fix(clerk-js,shared): Remove __clerk_db_jwt from hash on clerk-js init

.changeset/witty-jokes-repair.md, packages/shared/src/devBrowser.ts
Even though we're not using the legacy jwt anymore, we need to remove it from the URL to keep the URL clean
=> fix(shared): Remove legacy __dev_session from URL search params

.changeset/gentle-masks-retire.md, packages/clerk-js/src/ui/components/OrganizationList/OrganizationListPage.tsx
This will only happen rarely as we are not mounting the component when the feature is off. In the rare change the component is mounted and by the time the form is submitted an admin turns the feature off a duplicate error would appear in the UI.
https://github.com/clerk/javascript/assets/19269911/e9476ea9-d9a0-42fa-a4c1-a19ee62cf0e9
https://github.com/clerk/javascript/assets/19269911/a38e1099-412a-4858-b494-f59851beaf70
=> fix(clerk-js): Avoid duplicate global errors in OrganizationList

.changeset/short-bikes-kneel.md, package-lock.json, packages/clerk-js/src/core/clerk.ts, packages/clerk-js/src/utils/getClerkQueryParam.ts
This fix is applied to support core-1 apps navigating to core-2 AP and using OAuth / SAML sign-in.
cherry-picked https://github.com/clerk/javascript/pull/2624
=> fix(clerk-js): Remove handshake related query params in clerk-js

.changeset/curvy-kids-sip.md, packages/types/src/appearance.ts
We already have the functionality to support an array of `BaseTheme` items that stack on each other. We also document examples of usage here: https://clerk.com/docs/components/customization/overview#using-a-pre-built-theme
=> fix(types): Fix the `appearance.baseTheme` type to accept array of `BaseTheme`

.changeset/twenty-yaks-behave.md, packages/remix/src/utils/utils.ts
Fixes #2778
Remix + Cloudflare pages now accesses  environment variables via `context.cloudflare.env` https://remix.run/blog/remix-vite-stable#cloudflare-pages-support
=> fix(remix): Get env variables in Cloudflare Pages context

.changeset/late-insects-doubt.md, packages/clerk-js/src/core/resources/Passkey.ts, packages/clerk-js/src/core/resources/User.ts, packages/clerk-js/src/core/resources/Verification.ts, packages/clerk-js/src/core/resources/internal.ts, packages/clerk-js/src/utils/__tests__/passkeys.test.ts, packages/clerk-js/src/utils/passkeys.ts, packages/shared/src/error.ts, packages/types/src/index.ts, packages/types/src/json.ts, packages/types/src/passkey.ts, packages/types/src/user.ts, packages/types/src/userSettings.ts, packages/types/src/verification.ts
Any TODO comments will be handled in follow up PRs that address those tickets.
For further information about the feature please check out internal documentation.
Includes tests for transforming payloads and responses from Base64Url strings to buffers and vice versa.
=> feat(clerk-js): Adds experimental support for registering a passkey

.changeset/thirty-news-mate.md, packages/clerk-js/src/ui/components/OrganizationProfile/InviteMembersForm.tsx
This PR handles to show an error when an invalid email is submitted when inviting members to an Organization.
=> fix(clerk-js): Show errors when invalid email submitted when inviting members to an Org

.changeset/sweet-queens-tan.md, packages/clerk-js/src/ui/common/NotificationCountBadge.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/OrganizationMembers.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/__tests__/OrganizationMembers.test.tsx
Show counter of members/invitations/requests even if it is 0. Remove some unnecessary logic from the `<NotificationBadge />` and fix the spacing to match designs.
=> fix(clerk-js): Show counter of members/invitations/requests even if it is 0

.changeset/rotten-ligers-move.md, packages/react/src/types.ts
Introducing stricter types for custom pages for UserProfile and OrganizationProfile.
=> chore(clerk-react): Stricter types for custom pages

.changeset/wet-carpets-double.md, packages/clerk-js/src/core/resources/Passkey.ts, packages/clerk-js/src/core/resources/User.ts, packages/clerk-js/src/utils/passkeys.ts, packages/types/src/json.ts, packages/types/src/passkey.ts, packages/types/src/user.ts
Experimental support for reading, updating, and deleting a user's registered passkeys.
- Get the user's passkeys
`clerk.user.__experimental__passkeys`
- Update the name of a passkey
`clerk.user.__experimental__passkeys?.[0].update({name:'work laptop passkey'})`
- Delete a passkey
`clerk.user.__experimental__passkeys?.[0].delete()`
=> feat(clerk-js): Experimental CRUD methods for passkeys

.changeset/quiet-kings-relate.md, packages/nextjs/src/constants.ts, packages/nextjs/src/server/protect.ts
Using auth().protect inside clerkMiddleware will perform a redirection instead of throwing a not found error when internal navigation in pages router occurs and the user is unauthenticated.
Original issue:
Case1: When auth().redirectToSignIn() is used
signing out on the client-side triggers the middleware and the middleware returns a 307 redirect to /sign-in . This is the expected behavior
Case2: When auth().protect() is used
event though signing out on the client-side triggers the middleware, protect() treats the request as an api/route handler request and returns 404, so the redirect does not happen. This should be like case 1.
=> fix(nextjs): Middleware protect detects internal navigation in pages router

.changeset/four-crabs-sneeze.md, packages/clerk-js/src/ui/elements/OrganizationPreview.tsx
The organizationPreviewSecondaryIdentifier element will no longer be rendered empty inside the organization switcher's list.
=> fix(clerk-js): Fix the conditional render condition for organizationPreviewSecondaryIdentifier

.changeset/light-doors-teach.md, packages/clerk-js/src/ui/primitives/Input.tsx
This PR addresses an issue in iOS Webkit for iOS versions <=16.x with the `box-shadow` on input elements.
We added the `-webkit-appearance: none` to all the input elements.
=> fix(clerk-js): Fix the input box-shadow on iOS 16 devices

.changeset/shiny-ties-complain.md, packages/remix/src/ssr/utils.ts
This PR fixes a Cloudflare Worker specific error, see the error reported to the [Wrangler repo](https://github.com/cloudflare/workers-sdk/issues/3259)
=> fix(remix): Fix issue of creating multiple branches of a single stream on Cloudflare Workers

.changeset/witty-pens-arrive.md, packages/clerk-js/src/ui/components/SignIn/SignInStart.tsx, packages/clerk-js/src/ui/components/SignIn/__tests__/SignInStart.test.tsx, packages/clerk-js/src/ui/components/SignUp/SignUpStart.tsx, packages/clerk-js/src/ui/components/SignUp/__tests__/SignUpStart.test.tsx
Remove the **clerk_ticket and **clerk_invitation_token query params after they are consumed.
=> fix(clerk-js): Remove ticket params after they are consumed

.changeset/mean-ties-talk.md, packages/clerk-js/src/ui/elements/Navbar.tsx
The fix already exists in core-2
Fixes #2919
=> fix(clerk-js): Avoid calling `router.matches()` for external routes

.changeset/lemon-starfishes-buy.md, packages/backend/src/tokens/__tests__/authStatus.test.ts, packages/backend/src/tokens/authStatus.ts, packages/backend/tests/suites.ts, packages/fastify/src/withClerkMiddleware.test.ts, packages/fastify/src/withClerkMiddleware.ts, packages/nextjs/src/server/authMiddleware.ts, packages/nextjs/src/server/clerkMiddleware.ts, packages/nextjs/src/server/utils.ts, packages/remix/src/ssr/index.ts, packages/remix/src/ssr/utils.ts, packages/sdk-node/src/authenticateRequest.ts, packages/sdk-node/src/clerkExpressRequireAuth.ts, packages/sdk-node/src/clerkExpressWithAuth.ts
This refactoring task is to populate debug headers in `@clerk/backend` and expose them in the dependent SDKs.
Up until now, we are re-using internals to populate in each SDK the debug headers.
The debug headers are the : status, message, reason
=> chore(*): Expose requestState.headers to response and populate debug headers only in backend

.changeset/famous-bugs-tell.md, packages/fastify/src/__snapshots__/exports.test.ts.snap, packages/fastify/src/clerkClient.ts, packages/fastify/src/index.ts
Re-export `@clerk/backend` from `@clerk/fastify`
=> fix(fastify): Re-export @clerk/backend

.changeset/polite-avocados-suffer.md, packages/clerk-js/src/core/errors.ts
=> chore(clerk-js): Remove unused error helpers

.changeset/fifty-flies-greet.md, packages/remix/src/ssr/utils.ts
Backport of #2953
… stream on Cloudflare Workers
=> Port CF Remix issues changes to v4

.changeset/early-poets-leave.md, packages/backend/src/api/__tests__/factory.test.ts, packages/backend/src/api/resources/JSON.ts, packages/backend/src/api/resources/OauthAccessToken.ts
This change adds the `external_account_id` field to the OAuth access token response so that it is parity with the Backend API response.
=> feat(backend): Add `external_account_id` to OAuth access token response

package-lock.json, packages/themes/package.json
There is an issue with Yarn PNP requiring a package extension to safely resolve @clerk/themes. This patch resolves this issue.
=> fix(themes): Add tslib and @clerk/types as dependencies to @clerk/themes

.changeset/loud-pianos-compete.md, packages/clerk-js/src/ui/components/SignUp/SignUpForm.tsx
=> fix(clerk-js): Disable emailAdress field in SignUp if `fields.emailAddress.disabled` is true

.changeset/light-ligers-beam.md, packages/clerk-js/src/core/errors.ts, packages/clerk-js/src/core/resources/Passkey.ts, packages/clerk-js/src/core/resources/SignIn.ts, packages/clerk-js/src/core/resources/Verification.ts, packages/clerk-js/src/utils/__tests__/passkeys.test.ts, packages/clerk-js/src/utils/passkeys.ts, packages/types/src/factors.ts, packages/types/src/json.ts, packages/types/src/passkey.ts, packages/types/src/signIn.ts, packages/types/src/strategies.ts, packages/types/src/verification.ts
This PR exposes the `SignIn.__experimental_authenticateWithPasskey()` method.
https://github.com/clerk/javascript/assets/19269911/ceaa87b6-e2f3-40af-b17e-68a2f096961e
=> feat(clerk-js): Experimental method for authenticating with a passkey

.changeset/forty-cows-attend.md, packages/clerk-js/src/ui/primitives/Input.tsx
This PR fixes a styling issue for checkboxes, where it appears that the checkbox is not working at all when clicked, the issue is caused by another fix we applied couple days ago to fix some other issues with inputs on iOS =< 16
=> chore(clerk-js): Fix issue where checkbox styling seems broken

.changeset/great-seals-punch.md, packages/clerk-js/src/ui/components/SignIn/AlternativeMethods.tsx, packages/clerk-js/src/ui/elements/ArrowBlockButton.tsx
=> fix(clerk-js): Fix button font size for alternative methods on <SignIn/>

.changeset/short-tigers-breathe.md, integration/templates/next-app-router/package.json, package-lock.json, package.json, packages/backend/package.json, packages/elements/package.json, packages/expo/package.json, packages/nextjs/package.json, packages/sdk-node/package.json
Investigate and fix dependabot security alerts and results from `npm audit`.
=> fix(*): Update dependencies to resolve security alerts

.changeset/four-ties-yawn.md, packages/clerk-js/src/ui/components/SignIn/SignInFactorOnePasswordCard.tsx, packages/clerk-js/src/ui/components/SignIn/__tests__/ResetPassword.test.tsx, packages/clerk-js/src/ui/components/SignIn/__tests__/SignInFactorOne.test.tsx, packages/localizations/src/cs-CZ.ts, packages/localizations/src/da-DK.ts, packages/localizations/src/en-US.ts, packages/localizations/src/es-ES.ts, packages/localizations/src/es-MX.ts, packages/localizations/src/fr-FR.ts, packages/localizations/src/he-IL.ts, packages/localizations/src/it-IT.ts, packages/localizations/src/ko-KR.ts, packages/localizations/src/nl-NL.ts, packages/localizations/src/pl-PL.ts, packages/localizations/src/pt-BR.ts, packages/localizations/src/pt-PT.ts, packages/localizations/src/ru-RU.ts, packages/localizations/src/sk-SK.ts, packages/localizations/src/sv-SE.ts, packages/localizations/src/tr-TR.ts, packages/localizations/src/uk-UA.ts, packages/localizations/src/utils/enUS_v4.ts, packages/localizations/src/vi-VN.ts, packages/localizations/src/zh-CN.ts, packages/localizations/src/zh-TW.ts
If password_settings.enforce_on_sign_in is true, then it will be possible for a password sign-in to succeed but require a new password that conforms to updated password requirements.
Hence, if sign_in.needs_new_password is true, the password form will navigate to reset-password.
Since we are reusing a flow initially created for resetting passwords after an oauth flow, the error message has been made more generic.
=> feat(clerk-js,localizations): Nav to `reset-password` if `needs_new_password`

.changeset/odd-rats-smash.md, packages/clerk-js/src/ui/components/SignIn/utils.ts
Previously a readable UI error would appear to users. 
Now we treat them a "passwordless" attempt to sign in so we display the otp factors first.
=> fix(clerk-js): Define priority for strategy passkey when user is missing that first factor

.changeset/khaki-poems-press.md, packages/nextjs/src/server/clerkClient.ts, packages/nextjs/src/server/clerkMiddleware.ts
Adds a telemetry event to `clerkMiddleware` initialization so we can get better insight into usage, also passes `publishableKey` to the internal `createClerkClient` call so it can get passed along.
=> chore(nextjs): Adds telemetry event to clerkMiddleware initialization

.changeset/chilly-tips-compete.md, packages/backend/src/tokens/__tests__/keys.test.ts, packages/backend/src/tokens/keys.ts
=> fix(backend): Fix typo in jwk-remote-missing error message

.changeset/lazy-games-destroy.md, packages/clerk-js/src/index.headless.browser.ts
We were missing the `setWebpackChunkPublicPath` util in the `clerk.headless.browser` variant, making this variant break when there was a difference between latest published version and the pinned version in the cloudflare proxy. The util is necessary to replace chunk loading snippets with the fixed version of its entry file version.
=> fix(clerk-js): Correct chunk loading logic in clerk.headless.browser variant

.changeset/lazy-games-destroy.md, packages/clerk-js/src/index.headless.browser.ts
Backporting #3062 to the release/v4 branch
(cherry picked from commit d1dc44cc771c27c95fac96e6ffa805cd6d36c3f7)
=> fix(clerk-js): Correct chunk loading logic in clerk.headless.browser variant (#3062)

.changeset/large-clouds-flash.md, packages/clerk-js/src/core/resources/Session.ts
Avoid persisting a legacy integration token (eg Firebase) into `__session` cookie.
=> fix(clerk-js): Legacy integration tokens should not set __session cookie

.changeset/tiny-taxis-smell.md, packages/clerk-js/src/core/resources/Session.test.ts, packages/clerk-js/src/core/resources/Session.ts, packages/clerk-js/src/core/resources/Token.test.ts, packages/clerk-js/src/core/resources/Token.ts, packages/clerk-js/src/core/resources/__snapshots__/Session.test.ts.snap, packages/clerk-js/src/core/services/authentication/SessionCookieService.ts, packages/clerk-js/src/core/test/fixtures.ts, packages/clerk-js/src/core/tokenCache.ts, packages/types/src/token.ts
Error resolved by returning an empty string or null instead of trying to decode the `jwt` property from the response data. After this fix an `token.getRawString()` will return an empty string and  `session.getToken()` will return `null`  on Network failure and when request fails and browser is offline.
Current error message example:
```
Error: ClerkJS: Token refresh failed (error='Cannot read properties of null (reading 'jwt')')
```
=> chore(clerk-js): Improve Token.create to handle network failures errors

.changeset/wet-toes-knock.md, packages/backend/src/api/endpoints/UserApi.ts
Add a new enum value for `scrypt_werkzeug` in `UserAPI` -> `PasswordHasher`.
=> feat(backend): Add scrypt_werkzeug to supported hashers

.changeset/wicked-pumpkins-repair.md, packages/clerk-js/src/ui/components/UserProfile/PasskeySection.tsx, packages/clerk-js/src/ui/components/UserProfile/__tests__/PasskeysSection.test.tsx
RP ID for web credentials need to match the domain they are registered in but also the domain where they will be used for authentication.
In satellite app we redirect the user to the primary for signing in. Hence, the user needs to register the passkey in the primary's UserProfile.
=> fix(clerk-js): Hide "Add passkey" button in UP when app is satellite

.changeset/gold-flies-attend.md, packages/clerk-js/src/core/resources/Session.test.ts, packages/clerk-js/src/core/resources/Session.ts, packages/clerk-js/src/core/resources/Token.test.ts, packages/clerk-js/src/core/resources/Token.ts, packages/clerk-js/src/core/resources/__snapshots__/Session.test.ts.snap, packages/clerk-js/src/core/services/authentication/SessionCookieService.ts, packages/clerk-js/src/core/test/fixtures.ts, packages/clerk-js/src/core/tokenCache.ts, packages/types/src/token.ts
Error resolved by returning an empty string or null instead of trying to decode the `jwt` property from the response data. After this fix an `token.getRawString()` will return an empty string and  `session.getToken()` will return `null`  on Network failure and when request fails and browser is offline.
Current error message example:
```
Error: ClerkJS: Token refresh failed (error='Cannot read properties of null (reading 'jwt')')
```
Backport: https://github.com/clerk/javascript/pull/3035
=> chore(clerk-js): Improve Token.create to handle error due to network failure

.changeset/wet-toes-knock.md, packages/backend/src/api/endpoints/UserApi.ts
Backporting #3060 to the release/v4 branch
(cherry picked from commit 9879949)
Also included `sha256` from #1941 (It wasn't back ported and caused a conflict).
=> feat(backend): Add scrypt_werkzeug to supported hashers (#3060)

README.md, packages/backend/README.md, packages/chrome-extension/README.md, packages/clerk-js/README.md, packages/elements/README.md, packages/expo/README.md, packages/fastify/README.md, packages/gatsby-plugin-clerk/README.md, packages/localizations/README.md, packages/nextjs/README.md, packages/react/README.md, packages/remix/README.md, packages/sdk-node/README.md, packages/themes/README.md, packages/types/README.md
Since the main branch is for the beta version, links to the docs should accurately represent this.
Fixes SDK-1566
=> Fix docs links on main branch

.changeset/two-ways-buy.md, packages/clerk-js/src/ui/components/UserProfile/ConnectedAccountsSection.tsx, packages/clerk-js/src/ui/components/UserProfile/PasswordSection.tsx, packages/clerk-js/src/ui/elements/Section.tsx
This PR fixes some height misalignment of the **Password Section** with the designs.
=> fix(clerk-js): Fix height misalignment of Password section in UP

.changeset/cold-ducks-cross.md, packages/localizations/src/pt-BR.ts
This PR is intended to fix many ptBR exclusive language inconsistencies. Here's an example of language inconsistency: 
- [] 🐛 Bug fix
=> [Localization] Improve ptBR locale

.changeset/cuddly-wasps-cheat.md, packages/clerk-js/src/ui/components/OrganizationProfile/OrganizationMembers.tsx
This PR fixes an issue for the `<OrganizationSwitcher/>` component, where organization members with only `org:sys_memberships:read` could not see the counter on the **Members** tab.
=> fix(clerk-js): Allow members with membership read permissions to see memberships count

.changeset/famous-plums-fold.md, packages/clerk-js/src/core/test/fixtures.ts, packages/types/src/json.ts, packages/types/src/signIn.ts
Neither are used in their respective classes and `supported_external_accounts` is not inside `/environment` response
=> chore(types): Deprecate `supported_identifiers` and remove `supported_external_accounts`

.changeset/five-shoes-promise.md, packages/clerk-js/src/ui/components/OrganizationSwitcher/UserInvitationSuggestionList.tsx
**Background**: In order to provide a better UX, we are manually updating the cache where userInvitations are stored. This allows us to update the invitation in place and avoid layout shifts, if we would simply revalidate this would not be possible.
We are also manually updating `count` in the local cache in order to display the correct number of invitations available, without revalidating as this would cause a layout shift.
=> fix(clerk-js): Avoid depending on `count` as it can be zero but invitations may still exist

.changeset/ten-pumpkins-begin.md, packages/clerk-js/src/core/clerk.ts
Fixes a customer-reported issue where we were attempting to call `window.addEventListener()` via our Expo SDK.
=> fix(clerk-js): Fix unsafe window.addEventListener() call

.changeset/modern-hounds-push.md, packages/clerk-js/src/ui/components/SignIn/SignInAccountSwitcher.tsx, packages/clerk-js/src/ui/components/UserButton/SessionActions.tsx
This PR fixes a very small misalignment between icons of the "Add account" and "Sign out of all accounts" buttons in the account switcher screen.
=> chore(clerk-js): Fix misalignment of icons in account switcher

.changeset/quiet-pears-joke.md, packages/localizations/src/pt-BR.ts
Fixes typos from `pt-BR` localization module, and also translates a couple of English snippets to Portuguese.
=> fix(localizations): Fix typos from pt-BR localization

.changeset/light-beers-share.md, package-lock.json, packages/clerk-js/tsconfig.dev.json, packages/clerk-js/tsconfig.json, packages/localizations/tsconfig.json, packages/nextjs/tsconfig.json, packages/react/tsconfig.json, packages/shared/tsconfig.json
This enables support for older iOS mobile browsers. The client-side Clerk SDK now support all webkit-based browsers from version iOS 12 and upwards.
This change has minimal impact on the bundle-size and the generated code. From now on, changing the target to a newer version should be considered a breaking change that can only be released after a major version bump.
=> Switch compilation target to es2019

packages/clerk-js/src/ui/common/Billing/ManageBillingPlanScreen.tsx, packages/localizations/src/en-US.ts, packages/types/src/localization.ts
In this commit we are adding a button to expand and show all the available features in the billing plan card.
=> chore(clerk-js): Add show all button for features list

.changeset/sharp-months-rule.md, packages/localizations/src/th-TH.ts
- Added Thai translation keys for pwned password, form identifier, passkey
- Change Thai translation keys for Authenticator related to match the context
=> feat(localizations): Added Thai translation keys for pwned password, form identifier, passkey

.changeset/lovely-planets-suffer.md, package-lock.json, package.json, packages/backend/package.json, packages/backend/src/tokens/__tests__/clerkRequest.test.ts, packages/backend/src/tokens/clerkRequest.ts
The usual way to duplicate a request object is to
pass the original request object to the Request constructor both as the `input` and `init` parameters, eg: super(req, req) However, this fails in certain environments like Vercel Edge Runtime when a framework like Remix polyfills the global Request object. This happens because `undici` performs the following instanceof check which, instead of testing against the global Request object, tests against the Request class defined in the same file (local Request class). For more details, please refer to:
https://github.com/nodejs/undici/issues/2155
https://github.com/nodejs/undici/blob/7153a1c78d51840bbe16576ce353e481c3934701/lib/fetch/request.js#L854
=> fix(backend,remix): Tweak ClerkRequest initialization to work-around edge-runtime and undici limitations

packages/clerk-js/src/ui/components/OrganizationProfile/OrganizationBillingPage.tsx
=> fix(clerk-js): Add organization id to getAvailablePlans & getCurrentPlan cache keys

packages/backend/src/tokens/authObjects.ts, packages/clerk-js/src/core/resources/OrganizationMembership.ts, packages/clerk-js/src/core/resources/User.ts, packages/nextjs/src/app-router/server/controlComponents.tsx, packages/nextjs/src/server/protect.ts, packages/react/src/components/controlComponents.tsx, packages/react/src/contexts/AuthContext.ts, packages/react/src/contexts/ClerkContextProvider.tsx, packages/react/src/hooks/useAuth.ts, packages/react/src/utils/deriveState.ts, packages/types/src/authorization.ts, packages/types/src/index.ts, packages/types/src/json.ts, packages/types/src/jwtv2.ts, packages/types/src/organizationMembership.ts, packages/types/src/session.ts, packages/types/src/ssr.ts, packages/types/src/user.ts
- Update `has()`, `protect()` and `<Protect/>` to handle `plan` in the app and organization context for a user
- Expect `plan` in ClerkAuthorization in order developers to provide custom types for improved typesafety
- Update the User and OrganizationMembership resources in order to support the functionality described above.
=> feat(types,clerk-js,clerk-react,nextjs): Treat `plan` as authorization parameter

packages/clerk-js/src/ui/common/Gate.tsx
Internally we should **not** depend on roles. Since custom roles was introduced we have updated our internal clerk-js component to work with permissions only.
There are no references to `<Protect role="..."/>` in clerk-js.
This PR narrows the types in order to avoid confusion when protect is used inside clerk-js. Public APIs are not affected.
=> chore(clerk-js): Only allow permission authorizations internally

.changeset/eighty-pens-mix.md, packages/clerk-js/src/core/resources/DisplayConfig.ts, packages/clerk-js/src/core/resources/SignUp.ts, packages/clerk-js/src/ui/components/SignUp/SignUpForm.tsx, packages/clerk-js/src/ui/components/SignUp/SignUpStart.tsx, packages/clerk-js/src/ui/elements/CaptchaElement.tsx, packages/clerk-js/src/utils/captcha.ts, packages/clerk-js/src/utils/retrieveCaptchaInfo.ts, packages/types/src/displayConfig.ts
This PR adds support for different CAPTCHA widgets coming from the FAPI.
Currently, we support only an invisible captcha widget. This widget gets rendered in an injected div element at the end of the document body.
For backward compatibility, we will support the previous functionality when the user has selected the `"invisible"` widget. This is the setting to which all current users will be migrated.
This PR adds support for a visible challenge if needed on sign-up. This challenge gets rendered on the `<div id="clerk-captcha" />` element in the SignUp form.
Users with custom sign-up flows must have the `<div id="clerk-captcha" />` element inside their DOM when calling the `signUp.create` function.
=> feat(clerk-js): Support different CAPTCHA widget types

.changeset/modern-bobcats-love.md, packages/clerk-js/src/ui/components/SignIn/shared.ts
=> fix(clerk-js): Correctly call __internal_navigateWithError when authenticating with passkey

.changeset/rare-shoes-hunt.md, integration/tests/handshake.test.ts, packages/backend/src/tokens/__tests__/request.test.ts, packages/backend/src/tokens/authStatus.ts, packages/backend/src/tokens/request.ts, packages/express/src/__tests__/clerkMiddleware.test.ts
Trigger the handshake in development when no dev browser is present. This ensures stale auth state from the account portal is picked up if a redirect happens.
=> fix(backend): Trigger handshake in dev when no dev browser present

packages/clerk-js/src/ui/common/Billing/BillingProvider.tsx, packages/clerk-js/src/ui/common/Billing/PlanAndBillingScreen.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/OrganizationBillingPage.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/OrganizationProfileNavbar.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/OrganizationProfileRoutes.tsx, packages/types/src/organizationMembership.ts
In this pr we are adding protect to billing components
⚠️ merge this pr after fapi/dapi introduce `org:sys_billing:read` & `org:sys_billing:read`
=> feat(clerk-js,types): Add protect to billing components

.changeset/two-paws-search.md, packages/clerk-js/src/ui/common/__tests__/redirects.test.ts, packages/clerk-js/src/ui/common/redirects.ts, packages/clerk-js/src/ui/components/SignIn/__tests__/SignInStart.test.tsx, packages/react/src/errors/messages.ts
If a routing strategy is not provided, default to hash routing. All routing strategies know how to convert a hash-based url to their own format Example: navigating from a hash-based to a path-based component, the path-based component can parse and fix the URL automatically /#/sso-callback?code=123 -> /sso-callback?code=123
=> fix(clerk-js,clerk-react): Make UI-triggered redirects default to hash-based routing

.changeset/unlucky-cheetahs-suffer.md, packages/backend/src/tokens/__tests__/clerkRequest.test.ts, packages/backend/src/tokens/clerkRequest.ts, packages/nextjs/src/server/clerkMiddleware.ts
Introduce debug logging for the `clerkMiddleware` helper, similar to the one used in the existing `authMiddleware`
=> fix(nextjs,backend): Add debug logger to clerkMiddleware

.changeset/slimy-games-cover.md, packages/backend/src/api/resources/Organization.ts
Backport https://github.com/clerk/javascript/pull/3094 by introducing the `membersCount` property and deprecating the `members_count`.
=> fix(backend): Deprecate Organization.members_count

.changeset/wise-dogs-swim.md, packages/clerk-js/src/ui/components/UserProfile/MfaSection.tsx
This PR fixes a bug that was introduced with the re-theme of our components, when you were adding TOTP as your MFA without having any other factor available the backup codes where not showing up, after this fix this will work correctly.
=> fix(clerk-js): Fixed issue that prevented backup codes showing up for TOTP

.changeset/wicked-worms-draw.md, packages/remix/src/client/uiComponents.tsx, packages/remix/src/client/usePathnameWithoutSplatRouteParams.tsx
This PR allows to automatically infer the path for where the component is mounted.
This functionality is already introduced for `@clerk/nextjs` (#2634)
=> fix(remix): Automatically infer path to where component is mounted

.changeset/curly-cheetahs-act.md, packages/clerk-js/src/ui/elements/PhoneInput/PhoneInput.tsx
This PR aligns country code text position to be fully aligned with the phone number input
=> fix(clerk-js): Align country code position with phone number input

.changeset/violet-buckets-taste.md, packages/clerk-js/src/ui/components/SignIn/SignInAccountSwitcher.tsx, packages/clerk-js/src/ui/components/UserButton/SessionActions.tsx, packages/clerk-js/src/ui/elements/Actions.tsx
This PR aligns action button in `<UserButton/>` with User preview
=> fix(clerk-js): Align action buttons with user preview in <UserButton/>

.changeset/two-bugs-relate.md, packages/clerk-js/src/ui/components/UserProfile/ActiveDevicesSection.tsx, packages/clerk-js/src/ui/components/UserProfile/ConnectedAccountsSection.tsx, packages/clerk-js/src/ui/components/UserProfile/EmailsSection.tsx, packages/clerk-js/src/ui/components/UserProfile/EnterpriseAccountsSection.tsx, packages/clerk-js/src/ui/components/UserProfile/PhoneSection.tsx, packages/clerk-js/src/ui/components/UserProfile/Web3Section.tsx
This PR removes hoverable state from sections that are not interactive/clickable in the `<UserProfile/>` component
=> fix(clerk-js): Removing hoverable state from no-interactive sections in UP

.changeset/happy-lamps-march.md, packages/localizations/src/ar-SA.ts, packages/localizations/src/cs-CZ.ts, packages/localizations/src/da-DK.ts, packages/localizations/src/en-US.ts, packages/localizations/src/es-ES.ts, packages/localizations/src/he-IL.ts, packages/localizations/src/it-IT.ts, packages/localizations/src/ja-JP.ts, packages/localizations/src/ko-KR.ts, packages/localizations/src/nb-NO.ts, packages/localizations/src/nl-NL.ts, packages/localizations/src/pl-PL.ts, packages/localizations/src/ru-RU.ts, packages/localizations/src/sk-SK.ts, packages/localizations/src/sv-SE.ts, packages/localizations/src/tr-TR.ts, packages/localizations/src/uk-UA.ts, packages/localizations/src/zh-CN.ts, packages/localizations/src/zh-TW.ts, packages/types/src/localization.ts
Backporting #3073  to the `release/v4` branch
=> feat(types,localizations): Add translation keys for form_identifier_exists error

.changeset/eighty-pens-mix.md, packages/clerk-js/src/core/resources/DisplayConfig.ts, packages/clerk-js/src/core/resources/SignUp.ts, packages/clerk-js/src/ui/common/SSOCallback.tsx, packages/clerk-js/src/ui/components/SignUp/SignUpForm.tsx, packages/clerk-js/src/ui/components/SignUp/SignUpStart.tsx, packages/clerk-js/src/ui/elements/CaptchaElement.tsx, packages/clerk-js/src/utils/captcha.ts, packages/clerk-js/src/utils/retrieveCaptchaInfo.ts, packages/types/src/displayConfig.ts
This PR backports the following PRs to v4 (Core 1):
https://github.com/clerk/javascript/pull/3191
https://github.com/clerk/javascript/pull/3205
https://github.com/clerk/javascript/pull/3202
https://github.com/clerk/javascript/pull/3154
=> Backport to Core 1: feat(clerkjs): Add support for different Bot Protection widget types

.changeset/cold-files-refuse.md, .changeset/friendly-masks-obey.md, .github/workflows/ci.yml, package.json, packages/clerk-js/src/core/constants.ts, packages/clerk-js/src/ui/contexts/ClerkUIComponentsContext.tsx, packages/clerk-js/src/utils/__tests__/redirectUrls.test.ts, packages/clerk-js/src/utils/assertNoLegacyProp.ts, packages/clerk-js/src/utils/redirectUrls.ts, packages/nextjs/src/global.d.ts, packages/nextjs/src/utils/mergeNextClerkPropsWithEnv.ts, packages/types/src/clerk.ts, packages/types/src/redirects.ts
To avoid introducing a huge breaking change, we decided to introduce compat support for the legacy props.
The legacy props are now used as the fallback props unless overridden by *any* of the new props
=> fix(clerk-js,types,nextjs): Allow legacy redirect props as a fallback

.changeset/tasty-ghosts-kick.md, packages/backend/src/api/endpoints/UserApi.ts
Added missing parameter for getUserList
=> fix(backend): Added missing organizationId to UserCountParams for getUserList

.changeset/mighty-timers-end.md, packages/backend/src/index.ts, packages/nextjs/src/server/index.ts
- Export webhook events and types from `@clerk/backend`
- Export webhook events and types from `@clerk/nextjs/server`
As requested by multiple users, these types are useful when extracting webhook handler behavior into smaller functions, eg: 
```
export handleUserUpdated(data: UserJSON) {}
```
Closes SDK1678
=> Export webhook types

.changeset/chilly-tips-smash.md, packages/clerk-js/src/utils/assertNoLegacyProp.ts
Check if legacy property has a value and display a warning if present.
=> fix(clerk-js): Check if legacy property has value before display warning

.changeset/poor-onions-retire.md, packages/clerk-js/src/ui/primitives/Input.tsx
Tailwind forms targets via the `type` attribute. By adding this type, we make sure all our inputs are reset by that plugin.
=> fix(clerk-js): Default to text type for inputs, fix tailwind forms inconsistencies

.changeset/grumpy-rings-sleep.md, .vscode/settings.json, packages/clerk-js/src/ui/components/SignUp/SignUpEmailCodeCard.tsx, packages/clerk-js/src/ui/components/SignUp/SignUpPhoneCodeCard.tsx, packages/clerk-js/src/ui/components/SignUp/SignUpVerificationCodeForm.tsx
=> fix(clerk-js): Set card error on prepare code verification

.changeset/mean-planets-share.md, packages/backend/src/api/endpoints/TestingTokenApi.ts, packages/backend/src/api/endpoints/index.ts, packages/backend/src/api/factory.ts, packages/backend/src/api/resources/JSON.ts, packages/backend/src/api/resources/TestingToken.ts, packages/backend/src/api/resources/index.ts, packages/backend/src/index.ts
This PR adds support for the [Testing Tokens API](https://clerk.com/docs/reference/backend-api/tag/Testing-Tokens) to `@clerk/backend`
Introduces the `testingTokens` resource and the `createTestingToken()` method.
=> feat(backend): Add support for the Testing Token API

.changeset/sharp-lies-dream.md, packages/clerk-js/src/ui/components/UserProfile/DeleteUserForm.tsx
After this PR the form will not be submitted on enter if the confirmation value is incorrect.
This PR also changes the expected value from the hard coded string "Delete Account" to whatever value the localization key of `formFieldInputPlaceholder__confirmDeletionUserAccount` corresponds to.
For example if we have this
```tsx
<ClerkProvider
localization={{
formFieldInputPlaceholder__confirmDeletionUserAccount: 'Konto abmelden', // <-- Delete account in german 
}}
>
```
The end user would need to type "Konto abmelden" in order for the submit button to become enabled.
=> fix(clerk-js): Prevent account deletion when confirmation value is incorrect

.changeset/mean-snakes-appear.md, packages/localizations/package.json, packages/themes/package.json
- Also drops `@type/nodes` as devDependency
=> chore(localizations,themes): Drop react as peer dependency

.changeset/gorgeous-ladybugs-sit.md, packages/testing/package.json, packages/testing/playwright/package.json, packages/testing/tsup.config.ts
ESM imports from the testing package currently fail with e.g.
`SyntaxError: The requested module '@clerk/testing/playwright' does not provide an export named 'clerkSetup'`
A reproduction can be found [here](https://github.com/gcascio/playwright-clerk-nextjs-example) which is a clone of the official [clerk](https://github.com/clerk/playwright-clerk-nextjs-example) example changed to `type: "module"`.
This PR removes the `legacyOutput` flag from the tsup config and instead exports ESM modules with the `.mjs` extension.
=> fix(testing): Use .mjs for esm exports

.changeset/wild-hats-marry.md, packages/clerk-js/src/core/clerk.ts, packages/react/src/types.ts, playground/vanillajs/index.html
Originally raised (https://github.com/clerk/javascript/pull/3277/commits) but had to re-open here due GitHub permissions issues on running integrations from a forked branch.
Removes references from deprecated clerk_frontend_api, clerk_publishable_key should be used instead.
=> chore(repo, clerk-react, clerk-js): Remove references to deprecated clerk_frontend_api key

.changeset/chatty-panthers-beam.md, packages/clerk-js/src/core/clerk.ts
Avoid throwing error for missing an active organization when no user is signed in
fixes #3236
=> fix(clerk-js): Avoid throwing error for missing an active organization when no user is signed in

.changeset/metal-bulldogs-destroy.md, packages/shared/src/__tests__/telemetry.test.ts, packages/shared/src/telemetry/clientCache.ts, packages/shared/src/telemetry/collector.ts, packages/shared/src/telemetry/throttler.ts
Originally raised (https://github.com/clerk/javascript/pull/3267/files) but had to re-open here due GitHub permissions issues on running integrations from a forked branch.
Currently blocking SDK-1672 (https://github.com/clerk/javascript/pull/3257) and https://github.com/clerk/javascript/pull/3279
Introduces client-side caching for telemetry events. This prevents event flooding in frequently executed code paths, such as for React hooks or components.
Event sampling by rate will be executed on the server-side, or when neither the browser storage or window are available.
=> feat(shared): Introduce client-side caching for telemetry events

.changeset/violet-lobsters-scream.md, packages/elements/src/internals/machines/sign-in/verification.machine.ts, packages/elements/src/react/sign-in/context/router.context.ts
Fixes an issue where multiple prepare calls were being fired, resulting in multiple verification codes being sent. We're doing this by relying on the response from FAPI, which contains an `expireAt` property indicating when the code is expired. If it's not expired, we won't send a new prepare call by default.
=> fix(elements): Prevent multiple verification codes from being sent

.changeset/olive-points-own.md, .changeset/violet-lobsters-scream.md, packages/elements/examples/nextjs/next.config.js, packages/elements/src/internals/machines/sign-in/verification.machine.ts
Handles a case where Elements is configured correctly but the Clerk instance may not be. This ensures that the appropriate error messaging is displayed to the developer.
=> chore(elements): Add addtional misconfigured instance error messaging

.changeset/empty-wombats-invite.md, packages/nextjs/src/client-boundary/hooks/useEnforceCatchAllRoute.tsx, packages/nextjs/src/client-boundary/hooks/useEnforceRoutingProps.tsx, packages/nextjs/src/client-boundary/uiComponents.tsx
This PR aims to improve the way we detect catch-all routes for the following edge cases: 
1. A component that requires an active session (eg UserProfile) is mounted in a route protected by middleware. Upon signing out, the catch-all route check will always fail with a 404 because of the middleware protection. To resolve this edge case, we only fire the catch-all route request when a session is active. The only exception here is the SignIn and SIgnUp components, which require no active session 
2. We've improved the error message to indicate that if a path-based component is mounted in a route that is completely protected by the middleware, the component will fail to work. The usual mistake is to mount SignIn in /sign-in, but then forget to mark all children routes as public in your …
=> Improve catch-all detection

.changeset/strong-snakes-search.md, packages/eslint-config-custom/package.json
Canary release for eslint-config-custom failed in https://github.com/clerk/javascript/actions/runs/8984793785/job/24677395550. This PR adds the missing properties to its `package.json` to hopefully make it work 🤞
=> chore(eslint-config-custom): Set package.json properties for publishing

packages/elements/src/internals/machines/sign-up/continue.machine.ts, packages/elements/src/internals/machines/sign-up/continue.types.ts, packages/elements/src/internals/machines/sign-up/router.machine.ts, packages/elements/src/internals/machines/sign-up/router.types.ts, packages/elements/src/internals/machines/sign-up/start.machine.ts, packages/elements/src/internals/machines/sign-up/start.types.ts, packages/elements/src/internals/machines/sign-up/verification.machine.ts, packages/elements/src/internals/machines/sign-up/verification.types.ts, packages/elements/src/internals/machines/types/router.types.ts, packages/elements/src/react/sign-up/context/index.ts, packages/elements/src/react/sign-up/context/router.context.ts, packages/elements/src/react/sign-up/continue.tsx, packages/elements/src/react/sign-up/start.tsx, packages/elements/src/react/sign-up/verifications.tsx
As development of Elements progressed certain decisions were made which invalidated the benefits of spawning the child machines the way we were. As-such, this PR serves to do the following for Sign Up:
Fixes SDK-1715
=> refactor(elements): Reduce Sign Up reliance on useEffect [SDK-1715]

.changeset/chatty-jeans-fry.md, packages/react/src/hooks/useSignIn.ts, packages/react/src/hooks/useSignUp.ts, packages/shared/src/react/hooks/useOrganization.tsx, packages/shared/src/react/hooks/useOrganizationList.tsx
Resolves SDK-1672
Add telemetry events for `useSignIn`, `useSignUp`, `useOrganizations` and `useOrganizationList`. This will allow us to track the usage of hooks for custom flows.
=> feat(clerk-react,shared): Add telemetry events for React hooks

.changeset/fair-months-camp.md, packages/nextjs/src/server/__tests__/clerkMiddleware.test.ts, packages/nextjs/src/server/clerkMiddleware.ts
In situations where a redirect is triggered from a custom middleware handler, usually the result of using `auth().protect()`, we were not applying response headers from the `authenticateRequest()` result. This caused a bug where a handshake was not resolved, resulting in a broken auth state.
=> fix(nextjs): Apply response headers on redirect

.changeset/empty-cobras-sit.md, packages/remix/src/ssr/utils.ts
When authenticating a request, it's possible we may pass multiple headers with the same name (e.g. multiple `Set-Cookie` headers). By using `headers.set()`, we were only accepting the last header of that name. Switching to `headers.append()` should fix this.
=> fix(remix): Ensure headers with the same name do not get overwritten

.changeset/thirty-seas-agree.md, packages/clerk-js/src/utils/__tests__/url.test.ts, packages/clerk-js/src/utils/cookies/__tests__/getCookieDomain.test.ts, packages/clerk-js/src/utils/cookies/clientUat.ts, packages/clerk-js/src/utils/cookies/devBrowser.ts, packages/clerk-js/src/utils/cookies/getCookieDomain.ts, packages/clerk-js/src/utils/url.ts
Set an explicit domain value for our `clientUat`  cookie. This mirrors logic in FAPI. Without this, we were seeing duplicate `__client_uat` cookies, which causes issues when they get out of sync. I also removed an unused helper method, `getAllETLDs()`, that I stumbled across.
=> fix(clerk-js): Set eTLD+1 as the domain for client_uat

.changeset/short-llamas-remember.md, packages/clerk-js/src/ui/elements/CodeControl.tsx, packages/clerk-js/src/ui/elements/PhoneInput/PhoneInput.tsx
This PR fixes 2 UI issues that were found when using `@tailwindcss/forms`, the first problem was that phone number had the country code flowing over the phone input and the other one was that the OTP where huge due to `box-sizing: content-box`
=> fix(clerk-js): UI fixes for phone input and OTP inputs

.changeset/green-eggs-kiss.md, packages/clerk-js/src/ui/elements/LoadingCard.tsx, packages/clerk-js/src/utils/captcha.ts
This PR fixes the logic determining if the captcha should fallback to 'Invisible' if the element for the 'Smart' captcha is not found in the DOM. The widget is now selected and rendered synchronously.
Previously the order of the events was the following:
1. Determine if clerk-js should use the `Smart` or the `Invisible` Captcha widget.
2. Download the CF Turnstile script.
3. Render the Captcha.
The 2nd step above runs asynchronously and sometimes loading states can remove the `#clerk-captcha` element from the DOM.
After this change, we move the 2nd step to be done first and synchronously decide the widget and render it (step 1 and 3).
The addition of the captcha element on the loading card may solve our current issue. However, the change described above is a better practice for avoiding …
=> fix(clerk-js): Fix Smart captcha on Sign Up ticket flow

.changeset/plenty-comics-matter.md, packages/expo/src/polyfills/base64Polyfill.ts
Use a polyfill for the `atob` function to prevent errors when using the Hermes JS engine, since the engine's implementation is stricter than it should be and errors when the publishable key's base64 encoded part's length is not divisible by 4.
Related issue by the default JS engine for expo 51: https://github.com/facebook/hermes/issues/1379
=> fix(clerk-expo): Use atob polyfill when using Hermes JS engine

.changeset/wet-peaches-grow.md, packages/clerk-js/src/core/__tests__/clerk.redirects.test.ts, packages/clerk-js/src/core/clerk.ts, packages/clerk-js/src/ui/contexts/ClerkUIComponentsContext.tsx, packages/clerk-js/src/ui/router/RouteContext.tsx, packages/clerk-js/src/utils/__tests__/redirectUrls.test.ts, packages/clerk-js/src/utils/__tests__/url.test.ts, packages/clerk-js/src/utils/querystring.ts, packages/clerk-js/src/utils/redirectUrls.ts, packages/clerk-js/src/utils/url.ts, packages/react/src/components/SignInButton.tsx, packages/react/src/components/SignUpButton.tsx, packages/react/src/components/__tests__/SignInButton.test.tsx, packages/react/src/components/__tests__/SignUpButton.test.tsx
This PR updates the buildSignInUrl and buildSignUpUrl methods to correctly propagate the redirect props via URL search params. This allows the SignInButton and SignUpButton components to be configurable via their props as well.
Additionally,  this PR: 
- simplifies the RedirectUrl class by dropping the concern of appending params to the URL. This is now handled by the low-level buildUrl util 
- it fixes an issues when serializing initial values in the buildSignInUrl and buildSignUpUrl helpers. Search params need to be snake_cased in order to be respected
- buildUrl now accepts a new hashSearchParams prop and it snake_cases all search params by default
=> fix(clerk-js): Respect props passed to `buildSignInUrl` and `buildSignUpUrl`

.changeset/modern-steaks-think.md, .changeset/rotten-mice-juggle.md, packages/chrome-extension/src/index.ts
The previous PR wasn't supposed to be merged.
Reverts clerk/javascript#3363
=> Revert "fix(chrome-extension): Remove Origin from API mutation request headers"

.changeset/fast-timers-matter.md, packages/clerk-js/src/core/resources/SignUp.ts, packages/clerk-js/src/utils/captcha.ts
This PR adds a `console.error` on every CAPTCHA error.
Also, when script loading fails, we log it in the FAPI, meaning that the `/sign_ups` API call will be executed and will include the following value:
```
captchaError: 'captcha_script_failed_to_load'
```
=> fix(clerk-js): Improve logging for CAPTCHA script loading errors

.changeset/odd-coins-carry.md, package-lock.json, packages/elements/package.json, packages/elements/src/internals/machines/sign-in/router.machine.ts, packages/elements/src/internals/machines/sign-in/router.types.ts, packages/elements/src/internals/machines/sign-up/router.machine.ts, packages/elements/src/internals/machines/sign-up/router.types.ts, packages/elements/src/internals/machines/types/router.types.ts, packages/elements/src/react/sign-in/root.tsx, packages/elements/src/react/sign-in/verifications.tsx, packages/elements/src/react/sign-up/root.tsx
This is an addendum to the sign in/sign up updates seen in #3343.
This PR does the following:
Fixes SDK-1746
=> fix(elements): Fix follow-on initialization discrepancies

.changeset/chilled-laws-pump.md, .changeset/tricky-tomatoes-repair.md, packages/clerk-js/src/core/clerk.ts, packages/clerk-js/src/ui/common/EmailLinkCompleteFlowCard.tsx, packages/clerk-js/src/ui/common/EmailLinkStatusCard.tsx, packages/clerk-js/src/ui/common/EmailLinkVerify.tsx, packages/clerk-js/src/utils/getClerkQueryParam.ts, packages/localizations/src/en-US.ts, packages/shared/src/error.ts, packages/types/src/localization.ts
Add new `client_mismatch` verification status for email link sign in and sign up flows. This new status will _only_ be sent in as a query param if the corresponding setting is turned on in dashboard (future work).
https://github.com/clerk/javascript/assets/27433835/c6bf6844-ae6a-43a4-9454-fb81cabb795b
=> feat(clerk-js,shared,types,localizations): New client_mismatch status for email link sign in/up

.changeset/pretty-elephants-kiss.md, packages/backend/src/api/endpoints/UserApi.ts
Add the `phpass` and `bcrypt_sha256_django` hashers to the `PasswordHasher` type.
=> fix(backend): Add missing hashers to PasswordHasher type

.changeset/fast-timers-matter.md, .changeset/rotten-rats-carry.md, packages/clerk-js/src/utils/captcha.ts, packages/clerk-js/src/utils/runtime.ts
This PR backports 2 fixes from Core 2:
- Set Clerk cookies as first-party cookies when in a Cypress environment (#3245)
- Send captcha error to FAPI when captcha script loading fails (#3374)
=> [Core 1 Backport] Fix cookies on Cypress + Improve script loading failure logging

.changeset/quiet-games-brake.md, packages/elements/src/react/common/form/index.tsx
Fix types for GlobalError/FieldError render fns
Fixes SDK-1751
=> fix(elements): Fix types for GlobalError/FieldError render fns

.changeset/fluffy-turtles-applaud.md, packages/clerk-js/src/core/__tests__/clerk.test.ts, packages/clerk-js/src/core/clerk.ts, packages/nextjs/src/app-router/client/ClerkProvider.tsx
**Problem:**
Right now when signing out on Next.js with app router, there is a chance that you will get an error as we are clearing the app router cache before removing the session cookie.
**Solution:**
The solution is to move the removal of the session cookie before clearing the app router cache.
=> fix(clerk-js): Remove session cookie when signing out and `onBeforeSetActive`

.changeset/ninety-geese-knock.md, packages/elements/src/internals/machines/sign-up/router.machine.ts
Fixes Sign Up `setActive` not appropriately firing.
Ensures that ThirdParty machine doesn't try to initialized again after reset, if already running.
Fixes: SDK-1752
=> fix(elements): Sign-Up `setActive` not firing

.changeset/fast-singers-dress.md, packages/elements/src/react/common/form/index.tsx, packages/elements/src/react/utils/is-react-fragment.ts
Update `<FieldError />` composable similar to how `<GlobalError />` currently works.
```tsx
// Input
<Clerk.FieldError className='text-red-400' />
// Output
<span id="radix-:ru:">Error message</span>
```
```tsx
// Input
<Clerk.FieldError className='text-red-400'>
{({ message }) => {
return <span>{message}</span>;
}}
</Clerk.FieldError>
// Output
<span id="radix-:ru:"><span>Error message</span></span>
```
```tsx
// Input
<Clerk.FieldError className='text-red-400' asChild>
{({ message }) => {
return <p>{message}</p>;
}}
</Clerk.FieldError>
// Output
<p id="radix-:ru:">Error message</p>
```
Fixes issue with invalid markup when using the render function and providing a `p` or `div` tag as the child element.
=> refactor(elements): `FieldError` to enable `asChild` usage

.changeset/grumpy-plants-think.md, packages/testing/README.md, packages/testing/src/cypress/setup.ts, packages/testing/src/cypress/utils.ts
This PR adds the following console message on the node process that runs the `clerkSetup` function from `@clerk/testing/cypress`:
```
@clerk/testing: Cypress is an experimental project and subject to change in the future.
```
=> chore(testing): Add experimental console warning on Cypress setup

.changeset/ten-onions-learn.md, packages/backend/src/api/resources/JSON.ts, packages/backend/src/api/resources/SamlAccount.ts, packages/backend/src/api/resources/User.ts, packages/backend/src/fixtures/user.json
We fix an omission on our end where we didn't expose the 'saml_accounts' user property and therefore customers were not able to use it via our SDK
=> fix(backend): Expose user saml_accounts property

.github/workflows/ci.yml, .github/workflows/pr-title-linter.yml, .husky/commit-msg
Remove commitlint running as part of pre-commit checks. Instead, run it on the PR title. Due to squash merging, this will ensure that commits to `main` have formatted messages, but commits to branches unchecked. ⏩
fixes SDK-1753
=> chore(repo): Remove commitlint as part of pre-commit checks

.changeset/loud-tables-rush.md, packages/clerk-js/src/ui/components/SignUp/SignUpContinue.tsx
Resolves SDK-1689 - fixes Web3 sign-up flow with social connections.
The SDK was creating a new `SignUp` object on OAuth callback when continuing a signup flow, overriding properties such as `web3_wallet`. 
Instead of creating a new `SignUp` object, it should update the existing one.
=> fix(clerk-js): Update existing `SignUp` object on `SignUpContinue` OAuth

.changeset/clean-kings-brake.md, packages/clerk-js/src/utils/__tests__/url.test.ts, packages/clerk-js/src/utils/assertNoLegacyProp.ts, packages/clerk-js/src/utils/url.ts, packages/shared/package.json, packages/shared/src/__tests__/logger.test.ts, packages/shared/src/index.ts, packages/shared/src/logger.ts, packages/shared/subpaths.mjs
=> feat(clerk-js,shared): Custom logger to enable logging once per session

.changeset/sharp-apples-think.md, packages/elements/src/react/common/form/index.tsx
Updates `FieldError`/`GlobalError` types to allow render function children while using the `asChild` prop
Fixes SDK-1767
=> fix(elements): Update `FieldError`/`GlobalError` types to allow render function children while using the `asChild` prop

.changeset/hot-phones-serve.md, packages/nextjs/package.json, packages/react/package.json, packages/shared/package.json
With the next major release, NextJS@15 will deped on react and react-dom v19 that is still in beta. We are updating our peer dependencies for the related packages, otherwise the package managers will fail to resolve the package versions when users try to install or update the Clerk packages.
Due to the semver specification for prerelease tags (https://semver.org/#spec-item-11), we can't be very exact here. Adding `19.0.0-beta` to the list will also allow `19.0.0-canary` and `19.0.0-rc` releases as well, but this is not something we can or need to solve at the moment.
=> chore(clerk-react,nextjs,shared): Allow react and react-dom 19.0.0-beta

.changeset/small-frogs-march.md, packages/nextjs/src/app-router/client/ClerkProvider.tsx, packages/nextjs/src/app-router/client/useAwaitablePush.ts, packages/nextjs/src/app-router/client/useAwaitableReplace.ts, packages/nextjs/src/app-router/client/useInternalNavFun.ts
Create an `awaitableReplace` function, similar to the `awaitableNavigate` that we utilize for app router. This is essential in order to immediately be able to set state and render components, when we convert a hash based path to a path based one, inside `PathRouter.tsx`.
Fixes #3403
=> fix(nextjs): Redirect URL fixes

.changeset/good-paws-wonder.md, packages/elements/package.json, packages/elements/src/index.ts, packages/elements/src/internals/machines/shared/shared.actors.ts, packages/elements/src/react/router/__tests__/router.test.ts
Widen optional peerDependency of `next` to include `>=15.0.0-rc`. This way you can use Next.js 15 with Clerk Elements without your package manager complaining.
Also fixed two smaller TODOs and improved a test.
Fixes SDK-1289
=> fix(elements): Update peerDeps to allow Next 15 and React 19

.changeset/violet-geese-walk.md, packages/clerk-js/src/core/clerk.ts, packages/clerk-js/src/utils/windowNavigate.ts
v4 port of the v5 fix  (https://github.com/clerk/javascript/commit/b91e0ef4036d215da09d144f85b0a5ef2afe6cba)
=> Validate protocol before navigation

.changeset/cold-chicken-drop.md, integration/templates/react-vite/src/main.tsx, integration/tests/update-props.test.ts, packages/clerk-js/src/ui/Components.tsx
Support remounting ClerkProvider multiple times by making sure that the `updateProps` call during the loading phase does not override any defaults set by `Clerk.load()` for values that are missing
=> fix(clerk-js): Update props while respecting defaults set by Clerk.load

integration/tests/sign-up-flow.test.ts
One of our sign up tests has been flaking recently due to the fact that the test has been locating multiple elements with the password error message. This is a result of our our form field feedback is rendered, where one is an "info" and one is an "error". It's valid for both of these to be rendered, one visible and one hidden. This can be recreated on the Clerk Dashboard sign up form. Entering a password < 8 characters will render both info and feedback elements with the same message.
I'm not exactly sure why both are only rendered sometimes during this test, but we should be able to safely grab the first rendered element and assert on its visibility.
=> fix(repo): Adjust flaky sign up test

.changeset/shy-phones-leave.md, packages/localizations/src/ko-KR.ts
Fixing typo and translating to Korean in the navbar of user profile in ko-KR localization
title: 게정 → 계정
account: Profile → 프로필     (same as headerTitle__account: '프로필')
security: Security → 보안     (same as headerTitle__security: '보안')
=> fix(localizations): review ko-KR (user profile - navbar)

.changeset/unlucky-buckets-roll.md, packages/localizations/src/es-MX.ts
Hey!
With this PR I'm adding some missing translation for the ES-MX localizations file, mainly for the newly added passkeys functionality in Clerk. Also added one missing translation relating to the maintenance mode.
Open to any feedback related to my translations and about the PR. Thanks in advance!
=> feat(localizations): Added passkeys localizations for es-mx

.changeset/proud-fans-report.md, package-lock.json, packages/backend/package.json, packages/elements/package.json, packages/expo/package.json, packages/express/package.json, packages/gatsby-plugin-clerk/package.json, packages/localizations/package.json, packages/nextjs/package.json, packages/remix/package.json, packages/sdk-node/package.json, packages/shared/package.json
When installing a Clerk package that has @clerk/types as a dev dep, the types packages is usually not installed (depending on the package manager/ or the user's setup). I think this should be a normal dependency similar to how "@clerk/shared" is used across the monorepo.
Seems to fix the issue I noticed: 
With `latest`: 
WIth snapshot of this PR:
=> fix(repo): Set @clerk/types as normal dep

.changeset/warm-candles-thank.md, packages/clerk-js/src/ui/components/OrganizationProfile/ActiveMembersList.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/InvitedMembersList.tsx, packages/clerk-js/src/ui/components/OrganizationProfile/RequestToJoinList.tsx, packages/clerk-js/src/ui/customizables/elementDescriptors.ts, packages/types/src/appearance.ts
This PR adds a descriptor for the formatted dates and a descriptor id that indicates the usage within a table
=> fix(clerk-js): Add descriptor for formatted dates in tables

.changeset/strong-weeks-destroy.md, packages/elements/src/react/hooks/use-password.hook.ts
Password settings **could** be `undefined`, as such, we should handle that scenario.
Fixes SDK-1801
=> fix(elements): Ensure missing passwordSettings don't throw

.changeset/eleven-toes-poke.md, packages/clerk-js/src/ui/components/UserProfile/MfaPhoneCodeScreen.tsx
https://github.com/clerk/javascript/assets/19269911/bf9c3c00-7a4c-46b0-86be-319247452f77
https://github.com/clerk/javascript/assets/19269911/18e06ef9-6a57-48c3-acc5-1dfb29385881
=> fix(clerk-js): Sms phone code verification lists available phone numbers on cancel

.changeset/giant-poems-drum.md, packages/expo/src/ClerkProvider.tsx
The `EXPO_PUBLIC_` prefix is available since SDK 49. More details [here](https://docs.expo.dev/guides/environment-variables/)
=> chore(clerk-expo): Support `EXPO_PUBLIC_` prefixes for env variables

.changeset/perfect-penguins-swim.md, packages/clerk-js/src/ui/components/UserProfile/ActiveDevicesSection.tsx, packages/clerk-js/src/ui/hooks/useFetch.ts
Fixes this view when revoking:
=> fix(clerk-js): Only render active sessions in devices section

.github/workflows/ci.yml
According to https://unix.stackexchange.com/a/560315 you can use an OR in bash like that 😅 
This PR skips the required changeset check for Renovate PRs.
Got the login ID through checking with GitHub's API:
```json
"url": "https://api.github.com/repos/clerk/javascript/pulls/3493",
"id": 1898965849,
"title": "fix(shared): Update minor & patch dependencies",
"user": {
"login": "renovate[bot]",
"id": 29139614,
"type": "Bot",
"site_admin": false
},
```
=> chore(repo): Remove changeset check for renovate PRs

.github/workflows/ci.yml
The PR https://github.com/clerk/javascript/pull/3431 was in the correct state at some point but when it was merged the functionality of running the integration tests of Next.js both in Next 13 and 14 actually didn't work.
After reading https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-expanding-configurations I think what we had previously won't work.
Proof that Next 13 is used:
https://github.com/clerk/javascript/actions/runs/9379903450/job/25825965337?pr=3516#step:7:91
Proof that Next 14 is used:
https://github.com/clerk/javascript/actions/runs/9379903450/job/25825965564?pr=3516#step:7:89
=> fix(repo): Actually run Next.js integration for v13 & v14

.changeset/small-cycles-hug.md, packages/nextjs/src/app-router/server/utils.ts
in a [pull request introduced last january](https://github.com/vercel/next.js/commit/3008af6b0e7b2c8aadd986bdcbce5bad6c39ccc8#diff-20c354509ae1e93e143d91b67b75e3df592c38b7d1ec6ccf7c4a2f72b32ab17d) in next.js (`dynamic-rendering.ts:153`), the message passed in `React.unstable_postpone` thrown for PPR bailout was changed, meaning the check implemented by #2518 was not enough anymore, and the bailout was not being rethrown anymore, breaking next.js builds using ppr, and probably other issues. 
i've updated it to match the latest version, but kept the old check for the sake of not causing a breaking change.
to test:
- run a next.js build on an app that uses ppr with the latest version of @clerk/nextjs ([should fail](https://gist.github.com/ceIia/dacd8c2fe3f0363278bc4dff5f4a4004))
- run …
=> fix: handle ppr error message refactor

.changeset/soft-beers-hunt.md, packages/clerk-js/src/ui/lazyModules/providers.tsx
With the introduction of `GoogleOneTap` in `clerk-js@5.4.0` the bundle for clerk-js.browser.js was increased from 69KB to 166KB. This PR fixes that.
=> chore(clerk-js): Lazily load  VirtualBodyRootPortal

.changeset/cyan-gifts-cheer.md, packages/backend/src/tokens/keys.test.ts, packages/backend/src/tokens/keys.ts
Re-implementing #3321 for `release/v4`
=> fix(backend): Remove cache timer to fix empty cache bug

packages/backend/src/tokens/__tests__/authenticateContext.test.ts, packages/backend/src/tokens/authenticateContext.ts, packages/backend/src/tokens/request.ts, packages/backend/src/util/optionsAssertions.ts, packages/backend/src/util/shared.ts, packages/clerk-js/src/core/auth/AuthCookieService.ts, packages/clerk-js/src/core/auth/cookies/clientUat.ts, packages/clerk-js/src/core/auth/cookies/devBrowser.ts, packages/clerk-js/src/core/auth/cookies/session.ts, packages/clerk-js/src/core/auth/devBrowser.ts, packages/clerk-js/src/core/clerk.ts, packages/shared/jest.setup.ts, packages/shared/src/__tests__/keys.test.ts, packages/shared/src/keys.ts
Improve the cookie suffixes from the publishableKey to a fixed length 8 char string (hashed substring of publishableKey) to reduce the cookie size.
This change will also reduce the handshake payload by ~ 120 bytes.
=> fix(backend,shared,clerk-js): Improve cookie suffixes

packages/ui/bundlewatch.config.json, packages/ui/package.json
Adds bundlewatch config to ui directory and set arbitrary limits for both the sign-in and sign-up components. Limits are definitely open for discussion.
=> feat(ui): Add bundlewatch config

.changeset/warm-shoes-dance.md, packages/clerk-js/src/ui/elements/OrganizationPreview.tsx
Adds a `title` attribute to the span rendered for organization previews so that users can hover and see the full organization name without having to switch.
=> feat(clerk-js): Add title attribute to organization preview

.changeset/smart-pants-rule.md, packages/nextjs/src/app-router/client/ClerkProvider.tsx, packages/nextjs/src/app-router/server-actions/invalidateCache.ts
Fixes a reported issue where the following error was reported: https://nextjs.org/docs/messages/invalid-use-server-value
I'm not able to reproduce myself across a number of versions, but based on the documentation above, this function must be async, so I'm updating it.
=> fix(nextjs): Make exported server action async

.changeset/friendly-dots-join.md, packages/elements/examples/nextjs/app/sign-up/[[...sign-up]]/page.tsx, packages/elements/src/react/common/form/index.tsx, packages/elements/src/react/sign-in/root.tsx, packages/elements/src/react/sign-up/root.tsx
The sign in/up root fallbacks were still being held up by client-side requirements. This moves the logic such that this is no longer the case.
Fixes SDK-1842
=> fix(elements): Sign-in/up root fallbacks not rendering properly

.changeset/polite-poems-cross.md, packages/clerk-js/src/core/clerk.ts, packages/clerk-js/src/utils/windowNavigate.ts
Follow up to https://github.com/clerk/javascript/pull/3584 and https://github.com/clerk/javascript/pull/3564 - we were missing the allowlist in the second place where this check lives.
=> fix(clerk-js): Correctly use allowlist for protocol extensions in all codepaths

.changeset/metal-shrimps-repeat.md, package-lock.json, packages/elements/examples/nextjs/package.json, packages/elements/package.json
Update to https://www.radix-ui.com/primitives/docs/overview/releases#june-19-2024 which adds React 19 peerDeps to Radix packages and adds `'use client'` to their components. And also https://github.com/radix-ui/primitives/pull/2934
=> chore(elements): Update Radix deps

.github/actions/init/action.yml, .github/actions/verdaccio/action.yml, .github/workflows/ci.yml
This PR updates our Verdaccio process to unblock the upgrade to Node v18.20.3, which includes npm v10.7.0.
In modern versions of npm, you need to have an `authToken` in your `.npmrc` to be able to run `npm publish`. We achieved this previously with the use of the packages `npm-cli-adduser` and `npm-cli-login`. These packages were last updated six years ago. npm v10.7.0 included a rework of the CLI output, which breaks those packages since they relied on a specific output structure. We can achieve the same end result as those packages by simply adding an `_authToken` entry to `.npmrc` manually. Our Verdaccio configuration doesn't rely on the `_authToken` being any specific value due to the use of `$all`, which [allows all users, both anonymous and logged in, to publish …
=> fix(repo): Bump Node to latest version

package-lock.json, package.json
Follow up to https://github.com/clerk/javascript/pull/3620, which removes the now unneeded dependencies.
=> chore(repo): Remove npm-cli-* dependencies

.changeset/wise-bags-kneel.md, packages/clerk-js/src/ui/components/OrganizationSwitcher/__tests__/OrganizationSwitcher.test.tsx, packages/clerk-js/src/ui/hooks/useFetchRoles.ts
=> fix(clerk-js): Update cache key for roles when organization changes

.changeset/tall-hairs-dream.md, packages/remix/src/ssr/utils.ts
This PR fixes an issue that was introduced by https://github.com/clerk/javascript/pull/3495, where the `duplex` property was already defined and couldn't not be modified.
=> fix(remix): Fix issues caused by modifying duplex on Request

.changeset/chilled-dots-talk.md, packages/elements/src/react/sign-in/choose-strategy.tsx
Fixes scenario where sign-in factors get returned as empty values, therefore breaking iteration on `choose-strategy` component.
=> fix(elements): Fallback sign-in factors to empty array

.changeset/forty-kings-roll.md, packages/elements/src/internals/machines/sign-up/router.machine.ts, packages/elements/src/internals/machines/sign-up/router.types.ts, packages/elements/src/react/common/loading.tsx, packages/elements/src/react/sign-up/continue.tsx, packages/elements/src/react/sign-up/start.tsx, packages/elements/src/react/sign-up/verifications.tsx
This is a fast-follow to #3648, to bring sign-in and sign-up loading in-line with one another.
=> refactor(elements): Bring sign-up loading in-line with sign-in

.changeset/forty-kings-roll.md, .changeset/tricky-hotels-smell.md, packages/elements/src/internals/machines/sign-in/router.machine.ts, packages/elements/src/internals/machines/sign-in/router.types.ts, packages/elements/src/internals/machines/sign-up/router.machine.ts, packages/elements/src/internals/machines/sign-up/router.types.ts, packages/elements/src/internals/machines/types/router.types.ts, packages/elements/src/react/common/loading.tsx, packages/elements/src/react/sign-in/choose-strategy.tsx, packages/elements/src/react/sign-in/reset-password.tsx, packages/elements/src/react/sign-in/start.tsx, packages/elements/src/react/sign-in/verifications.tsx, packages/elements/src/react/sign-up/continue.tsx, packages/elements/src/react/sign-up/start.tsx, packages/elements/src/react/sign-up/verifications.tsx, packages/elements/src/react/utils/map-scope-to-strategy.ts
- Rename `route:` to `step:` for consistency.
- Clean up loading logic thus negating the need for context
Fast-Follow: Apply similar changes/logic to sign-up.
Fixes SDK-1863
=> refactor(elements): Fix loading oddities

.changeset/yellow-carrots-provide.md, packages/nextjs/src/server/clerkMiddleware.ts, packages/nextjs/src/server/utils.ts
Fixes https://github.com/clerk/javascript/issues/3660
- Uses `AsyncLocalStorage` available as a global polyfill for the edge runtime, instead of importing from Node.js: https://nextjs.org/docs/pages/api-reference/edge#nextjs-specific-polyfills
- Imports `logger` from nested import
=> fix(nextjs): Update imports to avoid Node.js build warnings on edge runtime

.changeset/soft-dragons-thank.md, integration/presets/astro.ts, packages/astro/src/env.d.ts, packages/astro/src/integration/create-integration.ts, packages/astro/src/server/get-safe-env.ts
This replaces the previous prefix `PUBLIC_ASTRO_APP`, and aligns it with the [standard from Astro](https://docs.astro.build/en/guides/environment-variables/#setting-environment-variables)
Given the fact that the astro sdk is in v0, we are not considering this change as breaking.
=> feat(astro): Change prefix for public env variables to `PUBLIC_`.

.changeset/thirty-icons-laugh.md, packages/astro/src/integration/create-integration.ts
Pretty much what the title says
=> fix(astro): Accessing import.meta at build causes app to break

.changeset/fair-cows-taste.md, packages/astro/README.md, packages/astro/src/internal/merge-env-vars-with-params.ts, packages/astro/src/server/clerk-middleware.ts, turbo.json
This PR removes the `ASTRO_APP` prefix to some of the env variables. This was already tackled in https://github.com/clerk/javascript/pull/3669 but some of the files are still using the old prefix
=> chore(astro): Update public env variables prefix

.changeset/strong-mugs-dress.md, packages/clerk-js/src/ui/lazyModules/providers.tsx
Fixes this error while impersonating a user
=> fix(clerk-js): ImpersonationFab needs a router to navigate on sign out

packages/ui/src/components/sign-in/sign-in.tsx, packages/ui/src/utils/format-safe-identifier.ts, packages/ui/src/utils/is-phone-number.ts
Add formatSafeIdentifier util to format phone number during sign in verification step
BEFORE:
AFTER:
https://linear.app/clerk/issue/SDKI-121/signin-verifications-phone-number-should-be-formatted-according-to
=> fix(ui): Format safe identifier phone number during sign in verification step

packages/nextjs/src/utils/__tests__/matcher.test.ts
The matcher we currently document breaks Clerk for the following scenario. 
- Have an app using the currently documented matcher
- Have a URL structure similar to `/articles/:article-slug`. `:article-slug` would be something like `${article_title}_${article_id}` , eg: `/article/hello-team-support_123a` - pretty common stuff so far.
If an article contains a `.` in its name, eg `/article/i-use-clerk.com-and-why-you-should-too_123`, then `auth()` and related helpers will fail because the matcher will not match the request URL and the middleware will be skipped.
This bug recently hit a few customers. This PR updates the matcher with a simplified version that no longer handles files as an edge case. We want to update our own dashboard first to further test the new matcher, before we reach out …
=> chore(nextjs): Add tests covering the new middleware matcher

.changeset/perfect-chairs-work.md, package-lock.json, packages/nextjs/package.json, packages/nextjs/src/app-router/server/auth.ts, packages/nextjs/src/app-router/server/currentUser.ts, packages/nextjs/src/server/__tests__/exports.test.ts
Resolves https://github.com/clerk/javascript/issues/3660
Uses the `server-only` package to throw a build-time error if Clerk server-side helpers get accidentally imported on the client side.
=> chore(nextjs): Introduce build-time error for server-only helpers on client-side

.changeset/cyan-pets-relax.md, .changeset/small-bears-yell.md, .changeset/three-houses-deny.md, package-lock.json, packages/elements/package.json, packages/elements/src/internals/machines/sign-up/router.machine.ts, packages/elements/src/internals/machines/sign-up/verification.machine.ts, packages/elements/src/internals/machines/sign-up/verification.types.ts, packages/elements/src/react/hooks/use-active-tags.hook.ts
- Handle call to `hasTags` on undefined `state`
- Pass Sign Up resource directly to machine over getSnapshot to avoid empty context
- Update XState from 5.13.x to 5.15.x
Fixes SDK-1879
=> fix(elements): Pass sign up resource directly to child machine

.changeset/lucky-olives-explode.md, packages/nextjs/src/app-router/server/auth.ts, packages/nextjs/src/app-router/server/currentUser.ts
https://github.com/clerk/javascript/pull/3758 introduces an issue where `server-only` gets resolved when importing any module from `@clerk/nextjs/server`. An example of that is that the error gets thrown when using `getAuth` from `getServerSideProps`. 
This PRs moves the `server-only` resolution to runtime within `auth` and `currentUser`.
=> fix(nextjs): Move `server-only` resolution to runtime

.changeset/plenty-snakes-repeat.md, packages/elements/src/react/common/form/index.tsx, packages/ui/src/common/password-field.tsx
Fixes issue where an invalid password field was immediately being refocused after submission causing the validation to run and show the success state.
BEFORE:
https://github.com/user-attachments/assets/b57e424d-69aa-42fc-aa37-88c40ae4a426
AFTER:
https://github.com/user-attachments/assets/e9f8b817-efc2-4c8e-86c1-2b2a2e62e29d
https://linear.app/clerk/issue/SDKI-154/validatepassword-usage-causing-inconsistent-errors-with-pwnd-message
=> fix(elements): Add check for `relatedTarget` to avoid validation running immediately after unsuccessful form submission

.changeset/cyan-gorillas-live.md, packages/testing/README.md, packages/testing/src/cypress/custom-commands.ts, packages/testing/src/cypress/index.ts
This PR adds Custom commands on the Cypress integration to better sign-in and sign-out.
To use these commands, you must import them in your `cypress/support/commands.ts` file.
```ts
// cypress/support/commands.ts
/// <reference types="cypress" />
import { addClerkCommands } from '@clerk/testing/cypress';
addClerkCommands({ Cypress, cy });
export {};
```
The `cy.clerkSignIn` command is used to sign in a user using Clerk. This custom command supports only the following first factor strategies:
- Password
- Phone code
- Email code
**Note:** Multi-factor authentication is not supported.
This helper internally uses the `setupClerkTestingToken`, so you don't need to call it separately.
**Prerequisites**
- You must call `cy.visit` before calling this command.
- Navigate to a non-protected page …
=> feat(testing): Introduce Cypress Custom commands for sign-in and sign-out

.changeset/cold-lobsters-drive.md, packages/elements/src/react/common/form/index.tsx
Reverting the changes in https://github.com/clerk/javascript/pull/3762 to fix failing E2E tests.
=> fix(elements): Reverts addition of `relatedTarget` check within `onFocus` input handler

.changeset/cool-pens-film.md, packages/clerk-js/src/ui/elements/Avatar.tsx
update the image alt attribute to fix the following issue reported in Lighthouse report
```
Image elements have [alt] attributes that are redundant text.
```
=> fix(clerk-js): Update the image alt attribute to fix accessibility issues reported by Lighthouse

.changeset/poor-rockets-peel.md, packages/clerk-js/src/core/__tests__/clerk.test.ts, packages/clerk-js/src/core/clerk.ts
Fixes the following flow that mainly affected nextjs apps:
Setup:
- Dev instance
- Latest next, clerk/nextjs and clerk-js
- Multi-app-same-domain FF disabled
Steps:
- Go to app
- Enter email and hit continue (signIn.create):  client_uat is 0
- Enter password and hit continue (signIn.attemptFirstFactor) : client_uat > 0 (for accounts)
- Clerk-js invalidates cache : **client_uat is 0 because  clerk-js does not set it correctlly**
The main issue in the clerk-js codebase was that during sign-in/sign-up, we set the cookies **implicitly** when we update the current Client resource (Base -> updateClient -> Client.fromJson() -> new Session -> hydrate token cache).  However, the Clerk.client only gets updated AFTER the token cache is hydrated, so setting the client_uat token failed because when it …
=> fix(clerk-js): Set __session and __client_uat before invalidating cache

.changeset/strong-beers-compete.md, packages/elements/src/react/common/form/index.tsx
Fix issue where a password field containing an error was refocused on submission causing the validation to run updating to successful field state. This PR updates the logic to make sure the value has changed before running the check again to ensure the error message is rendered.
BEFORE:
https://github.com/user-attachments/assets/f01c5d1d-9af6-4485-b628-616e396448df
AFTER:
https://github.com/user-attachments/assets/cd52913f-1998-48eb-b76c-507325ca6759
https://linear.app/clerk/issue/SDKI-171/passwordfield-error-message-is-being-wiped-on-submission-due-to
=> fix(elements): only validate `onFocus` or `onBlur` when value has changed

.changeset/weak-pumpkins-train.md, packages/clerk-js/src/core/resources/SignIn.ts, packages/clerk-js/src/ui/components/SignIn/SignInFactorTwoAlternativeMethods.tsx, packages/clerk-js/src/ui/components/SignIn/utils.ts, packages/elements/src/internals/machines/sign-in/utils/starting-factors.ts, packages/types/src/signIn.ts
This PR updates the types for `supportedSecondFactors` to account for the fact that the API can return a `null` value. This was mostly already encoded into the application logic, so the only logic change was adding a logical AND where we were calling `Array.sort` on a value that was potentially `null`.
=> fix(types,elements,clerk-js): Update types to account for null second factors

.changeset/wet-games-deliver.md, packages/localizations/src/de-DE.ts
The code changes add support for the German passkey-text localization and translations for some texts that haven't been translated.
=> feat(localizations): Add support for German (de-DE) passkey-text localization

.changeset/ninety-toes-fix.md, packages/chrome-extension/src/utils/cookies.ts
Depending on certain setups, we were receiving fulfulled, but null, promises. This updates that check.
=> fix(chrome-extension): Appropriately handle fulfilled, but null, cookie promises

.changeset/tasty-brooms-check.md, packages/elements/src/internals/machines/form/form.machine.ts, packages/elements/src/internals/machines/form/form.types.ts, packages/elements/src/internals/machines/sign-in/reset-password.machine.ts, packages/elements/src/internals/machines/sign-up/utils/__tests__/fields-to-params.test.ts, packages/elements/src/react/common/form/index.tsx
Add support for checkbox input usage and `signOutOfOtherSessions` functionality in sign in password reset flow
Usage:
```tsx
<Common.Field name="signOutOfOtherSessions">
<Common.Input type="checkbox" />
<Common.Label>Sign out of all other devices</Common.Label>
</Common.Field>
```
https://linear.app/clerk/issue/SDKI-146/signin-reset-password-sign-out-of-all-other-devices-checkbox
=> feat(elements): Add support for signOutOfOtherSessions checkbox

.changeset/tiny-glasses-teach.md, packages/dev-cli/package.json
The `package.json` was missing some keys that we typically have in our other packages.
=> chore(dev-cli): Adjust package.json

.changeset/ninety-squids-appear.md, packages/astro/src/server/clerk-middleware.ts
The middleware contains logic to check for a passed handler. When no handler is provided, it automatically executes the [next function](https://github.com/clerk/javascript/blob/195fd46bd5cff3b54161ede02848d1c08e695116/packages/astro/src/server/clerk-middleware.ts#L108).  However, the return type doesn't handle this scenario and still expects us to call the `next` function. It should be optional.
This small PR addresses the issue.
=> fix(astro): Middleware return type

.changeset/heavy-pillows-sparkle.md, packages/dev-cli/src/commands/init.js
Ensure the directory where we write the config file exists.
=> fix(dev-cli): Call mkdir before attempting to write the config file

.changeset/rude-wasps-wonder.md, packages/clerk-js/src/core/resources/SignUp.ts
Adjust how we pass captcha parameters when signing up via Google.
=> feat(clerk-js): Adjust captcha parameter handling for sign ups with Google

.changeset/four-pots-type.md, packages/astro/src/env.d.ts, packages/astro/src/integration/create-integration.ts, packages/astro/src/internal/merge-env-vars-with-params.ts, packages/astro/src/server/clerk-client.ts, packages/astro/src/server/get-safe-env.ts, packages/astro/src/types.ts
Adds opt-out support to the TelemetryCollector by passing an option to the integration or with environment variables similar to [existing frameworks](https://clerk.com/docs/telemetry).
Fixes ECO-65
=> feat(astro): Add opt-out support for SDK telemetry

.changeset/curly-lemons-rhyme.md, packages/elements/src/internals/machines/sign-in/utils/starting-factors.ts
Fixes issue where we were seeing `email_code` strategy being returned when it should have been `email_link`.
https://linear.app/clerk/issue/SDKI-153/email-code-is-rendering-when-email-link-verification-step-should-be
=> fix(elements): Update sign in first factor sorting strategies

.changeset/famous-tools-thank.md, packages/localizations/src/es-MX.ts
Spanish localization issue, currently, if you write 'Delete account' in the text field, it will not work because it expects 'Eliminar cuenta'. This disrupts the user experience. 
- [x ] 🐛 Bug fix
=> Replaced "Delete account" with spanish translation "Eliminar cuenta"

.changeset/bright-crabs-speak.md, packages/remix/src/ssr/utils.ts
This PR fixes a bug where the body has already been read and we try to clone the whole request and this results to an error.
Fixes [#3769](https://github.com/clerk/javascript/issues/3759)
=> fix(remix): Fix issue where request body has already been read

.changeset/funny-berries-jam.md, packages/elements/src/react/sign-in/choose-strategy.tsx, packages/ui/src/components/sign-in/first-factor-connections.tsx, packages/ui/src/components/sign-in/sign-in.tsx
Ensure correct supported strategies are rendered based on first or second factor needs.
https://linear.app/clerk/issue/SDKI-294/choose-strategy-step-returning-incorrect-supportedstrategy-for-second
BEFORE:
AFTER:
=> fix(elements): Update supported factors based on status

.changeset/smooth-worms-retire.md, packages/clerk-js/src/ui/components/OrganizationSwitcher/OtherOrganizationActions.tsx, packages/clerk-js/src/ui/components/UserButton/SessionActions.tsx, packages/clerk-js/src/ui/components/UserButton/UserButtonPopover.tsx, packages/clerk-js/src/ui/constants.ts, packages/clerk-js/src/ui/contexts/ClerkUIComponentsContext.tsx, packages/clerk-js/src/ui/customizables/elementDescriptors.ts, packages/clerk-js/src/ui/elements/Actions.tsx, packages/clerk-js/src/ui/utils/__tests__/createCustomMenuItems.test.ts, packages/clerk-js/src/ui/utils/createCustomMenuItems.tsx, packages/clerk-js/src/ui/utils/createCustomPages.tsx, packages/clerk-js/src/ui/utils/index.ts, packages/clerk-js/src/ui/utils/sanitizeCustomLinkURL.ts, packages/react/src/components/uiComponents.tsx, packages/react/src/errors/messages.ts, packages/react/src/types.ts, packages/react/src/utils/__tests__/useCustomMenuItems.test.tsx, packages/react/src/utils/componentValidation.ts, packages/react/src/utils/index.ts, packages/react/src/utils/useCustomMenuItems.tsx, packages/react/src/utils/useCustomPages.tsx, packages/types/src/appearance.ts, packages/types/src/clerk.ts, packages/types/src/customMenuItems.ts, packages/types/src/index.ts
Introduce support for custom menu items in `<UserButton/>`.
- Use `<UserButton.MenuItems>` as a child component to wrap custom menu items.
- Use `<UserButton.Link/>` for creating external or internal links.
- Use `<UserButton.Action/>` for opening a specific custom page of "UserProfile" or to trigger your own custom logic via `onClick`.
- If needed, reorder existing items like `manageAccount` and `signOut`
```jsx
<UserButton>
<UserButton.MenuItems>
<UserButton.Link label='Terms' labelIcon={<Icon />} href='/terms' />
<UserButton.Action label='Help' labelIcon={<Icon />} open='help' /> // Opens help page in UserProfileModal
<UserButton.Action label='manageAccount' labelIcon={<Icon />} />
<UserButton.Action label='Chat Modal' labelIcon={<Icon />} onClick={() => setModal(true)} /> …
```
=> feat(clerk-js,clerk-react,types): Introduce `UserButton` custom menu items

.changeset/wicked-seahorses-juggle.md, packages/clerk-js/src/core/__tests__/clerk.test.ts, packages/clerk-js/src/core/clerk.ts, packages/clerk-js/src/utils/__tests__/organization.test.ts, packages/clerk-js/src/utils/index.ts, packages/clerk-js/src/utils/organization.ts, packages/types/src/clerk.ts
This PR introduces ability to set an active organization by slug and updates existing org tests to use a proper Org ID format (`org_*`).
```ts
setActive({ organization: 'some-cool-slug' })
```
Fixes ORGS-17
=> feat(clerk-js): Add ability to set active organization by slug

.changeset/chilled-swans-work.md, packages/localizations/src/ar-SA.ts
Some Arabic Localization in the Organization Section was still in English. I translated the ones in the Organization Profile Component.
=> fix(localizations): arabic localization for org profile

.changeset/dirty-dragons-swim.md, packages/elements/examples/nextjs/app/sign-in/[[...sign-in]]/page.tsx, packages/elements/examples/nextjs/app/sign-up/[[...sign-up]]/page.tsx, packages/elements/src/internals/machines/sign-in/router.machine.ts, packages/elements/src/internals/machines/sign-up/router.machine.ts, packages/elements/src/react/common/connections.tsx, packages/elements/src/react/hooks/use-third-party-provider.hook.ts, packages/elements/src/utils/third-party-strategies.ts
`<Clerk.Connection name="saml">Continue with SAML</Clerk.Connection>`
Requires the following inputs: 
- Sign In: `identifier`
- Sign Up: `emailAddress`
=> feat(elements): Add SAML support

.changeset/friendly-bags-whisper.md, packages/astro/src/astro-components/control/Protect.astro, packages/astro/src/react/controlComponents.tsx, packages/astro/src/types.ts
This PR addresses an issue where the `<Protect />` component was accepting any prop without TypeScript raising errors. All the Astro components does not have a build step, and directly copied to `components/*`, so relative paths will not be resolvable.
=> fix(astro): Protect component prop types

.changeset/wicked-pianos-argue.md, packages/dev-cli/src/utils/getClerkPackages.js
This PR updates the `getClerkPackages` function of `clerk-dev` to use the configured monorepo root. In a previous iteration of `clerk-dev` it was expected that the CLI would be installed from the local checkout of `javascript`. We switched instead to installing it via `npm`, but the logic for `getClerkPackages` was not updated.
=> fix(dev-cli): Use configured monorepo root when calculating Clerk packages

packages/elements/src/internals/machines/form/form.types.ts, packages/elements/src/react/common/form/index.tsx, packages/elements/src/react/hooks/use-password.hook.ts, packages/elements/src/react/utils/generate-password-error-text.ts, packages/ui/src/common/password-field.tsx, packages/ui/src/utils/makeLocalizable.ts
This PR builds upon the work in #3812 to return password validation errors with their relevant config entries rather than asking the user to collate them themselves.
Errors are now returned as `(ErrorMessagesKey | [ErrorMessagesKey, Record<string, string | number>])[]`. This would allow users to localize error messages with something as simple as:
```tsx
{codes.map(c => Array.isArray(c) ? <p>{t(c[0], c[1])}</p> : <p>{t(c)}</p>)}
```
=> feat(elements,ui): Return password validation error codes with relevant config entries

package.json, playground/nextjs/package.json
The PR https://github.com/clerk/javascript/pull/3868 has the failed renovate update with this comment:
```shell
npm ERR! notsup Not compatible with your version of node/npm: astro@4.11.3
npm ERR! notsup Required: {"node":"^18.17.1 || ^20.3.0 || >=21.0.0","npm":">=9.6.5","pnpm":">=7.1.0"}
```
We're using an ancient `npm` version for our monorepo (8.5.0) so I'm updating it to 10.7.0 because in https://nodejs.org/en/about/previous-releases it shows that Node.js v18 ships with that version. We use v18 in our CI.
=> chore(repo): Update npm version

.changeset/poor-cheetahs-rhyme.md, packages/nextjs/src/server/__tests__/clerkMiddleware.test.ts, packages/nextjs/src/server/clerkMiddleware.ts
We are using the `withLogger` wrapper to handle the logger.commit on every time the wrapped function is executed.
In `clerkMiddleware` we are wrapping the whole function with the `withLogger` instead of the returned nextMiddleware that is executed in every request causing the `logger.commit()` to be executed once during the initialization of the `clerkMiddleware()` (on 1st request). To make debug logs working for `clerkMiddleware` on every request we need to move the `withLogger` to wrap the returned middleware instead.
In `authMiddleware` we are wrapping the returned nextMiddleware which makes the debugging logs works without any change.
- [x ] 🐛 Bug fix
=> fix(nextjs): Execute logger.commit() on every middleware invocation

.changeset/old-points-raise.md, package-lock.json, packages/dev-cli/README.md, packages/dev-cli/package.json, packages/dev-cli/src/commands/watch.js
This PR removes the macOS-specific functionality that was used to spawn a new Terminal window containing the builder for `clerk-js` in favor of simply using `concurrently` to run everything in the same terminal instance. To make it easier to distinguish the output, we use concurrently's `prefixColors` feature which prepends `[packages]` for the build process of dependencies and `[clerk-js]` for the `clerk-js` build.
=> feat(dev-cli): Remove macOS-specific Terminal functionality

.changeset/config.json, .changeset/fluffy-wolves-itch.md, packages/gatsby-plugin-clerk/README.md
This PR adds notice of plan to EOL Gatsby SDK
Fixes ECO-86 and ECO-92
=> chore(gatsby-plugin-clerk): Add transition period notice

.changeset/rich-parrots-crash.md, packages/elements/src/internals/machines/sign-in/router.machine.ts, packages/elements/src/internals/machines/sign-in/start.machine.ts, packages/elements/src/internals/machines/sign-in/start.types.ts, packages/elements/src/internals/machines/sign-up/router.machine.ts, packages/elements/src/internals/machines/sign-up/start.machine.ts
This PR adds support for sign up and sign in with Metamask.
=> feat(elements): Add sign up/sign in with Metamask

.changeset/fluffy-wolves-itch.md
Together with https://github.com/clerk/javascript/pull/3883 this should ensure that in https://github.com/clerk/javascript/pull/3873 we don't release a new major of `gatsby-plugin-clerk` but only push a path release on the old v4 release branch.
=> chore(repo): Make Gatsby changeset empty

.changeset/metal-mirrors-attack.md
In https://github.com/clerk/javascript/pull/3877 the changeset was left blank. In order to publish it, it needs to be filled out. This is relevant since the proposed release in https://github.com/clerk/javascript/pull/3873 (a major release) is incorrect.
=> chore(repo): Correct changeset

.changeset/hungry-clouds-return.md, packages/clerk-js/src/core/resources/DisplayConfig.ts, packages/clerk-js/src/ui/components/CreateOrganization/CreateOrganizationPage.tsx, packages/clerk-js/src/ui/customizables/elementDescriptors.ts, packages/clerk-js/src/ui/customizables/parseAppearance.ts, packages/clerk-js/src/ui/elements/Card/CardClerkAndPagesTag.tsx, packages/clerk-js/src/ui/elements/Card/CardContent.tsx, packages/clerk-js/src/ui/elements/Card/CardFooter.tsx, packages/clerk-js/src/ui/elements/DevModeNotice.tsx, packages/clerk-js/src/ui/elements/Navbar.tsx, packages/clerk-js/src/ui/elements/PopoverCard.tsx, packages/clerk-js/src/ui/elements/index.ts, packages/clerk-js/src/ui/hooks/useDevMode.tsx, packages/clerk-js/src/ui/polishedAppearance.ts, packages/clerk-js/webpack.config.js, packages/types/src/appearance.ts, packages/types/src/displayConfig.ts, playground/nextjs/pages/_app.tsx
Adding a development mode warning to our components to avoid going to productions with development keys by accident.
To be able to disable the development mode warning in order to preview how the components will look like in production the `appearance.layout.unsafe_disableDevelopmentModeWarnings` key has been added.
**Globally using the `<ClerkProvider />`:**
```typescript
<ClerkProvider appearance={{
layout: {
unsafe_disableDevelopmentModeWarnings: true,
}
}}>
...
```
**On each component:**
```typescript
<UserProfile appearance={{
layout: {
unsafe_disableDevelopmentModeWarnings: true,
}
}} />
```
Original PR: #3511
=> feat(clerk-js): Add dev mode warning to components (#3511)

.changeset/khaki-experts-pretend.md, packages/clerk-js/src/ui/Components.tsx, packages/clerk-js/src/ui/components/OrganizationSwitcher/OrganizationSwitcherPopover.tsx, packages/types/src/clerk.ts
…
Due to the decision not to ship support for custom items for OrganizationSwitcher, opening the OrganizationProfile in a specific page should not be supported.
=> chore(clerk-js,types): Remove `__experimental_startPath` from `OrganizationProfileProps`

.changeset/smart-llamas-ring.md, packages/dev-cli/src/cli.js, packages/dev-cli/src/utils/getPackageVersion.js
This PR fixes the hardcoded version string in `clerk-dev` to correctly report the currently executing version number.
=> fix(dev-cli): Correctly return package version
