clerk/javascript

.changeset/slow-dingos-hammer.md
packages/elements/src/react/common/form/otp.tsx

Recently noticed a "yellow" flash during MacOS "autofill"
https://github.com/user-attachments/assets/fe9f0dc1-3cc0-40b4-927c-bad2208f1c81
After some debugging, I was able to determine this was the underlying input that powers the OTP; extending the "transparent" styles to include `opacity: 0;`
Appreciate there may be some context missing here though, given the value was previously `opacity: 1;`
**After**
https://github.com/user-attachments/assets/50f6f12c-c02a-4fd1-898f-87806e81c25f

fix(elements): Prevent flash of "hidden" OTP input

---

.changeset/three-ghosts-develop.md
packages/backend/src/api/endpoints/UserApi.ts
packages/backend/src/api/resources/JSON.ts
packages/backend/src/api/resources/User.ts
packages/clerk-js/src/core/resources/User.ts
packages/types/src/json.ts
packages/types/src/user.ts

This PR adds a new field for the `user.update()` called `createOrganizationsLimit` which can be either number or null. This field is used to control how many orgs an user can create.

feat(backend): Add param in User.update()

---

.changeset/purple-chicken-flash.md
packages/clerk-js/src/ui/elements/PopoverCard.tsx

Fixes issue where no horizontal padding was used within `<UserButton />` and page urls were present.
BEFORE:
AFTER:

fix(clerk-js): Add missing x padding to ClerkAndPagesTag

---

.github/workflows/release.yml

Notify our own dashboard repo for a stable clerk/nextjs to ensure the dependency is always up to date.

chore(repo): Notify clerk/dashboard for stable nextjs releases

---

.changeset/hungry-pianos-punch.md
packages/elements/src/internals/machines/sign-in/router.machine.ts
packages/elements/src/internals/machines/sign-up/router.machine.ts

This PR adds support for `?redirect_url` in Elements to both sign in and sign up.
It really feels like this behavior should be delegated to `clerk-js`, possibly in the form of updating `buildAfterSignInUrl` to take in parameters such as `redirect_url`. Currently `buildAfterSignInUrl` only captures parameters when Clerk is initialized, not at the time of authentication.
Fixes SDKI-295

feat(elements): Add support for redirect_url URL parameter

---

.changeset/few-guests-collect.md
.changeset/fuzzy-elephants-warn.md
integration/templates/next-app-router/src/app/csp/page.tsx
integration/templates/next-app-router/src/middleware.ts
integration/tests/content-security-policy.test.ts
packages/nextjs/src/app-router/server/ClerkProvider.tsx
packages/nextjs/src/app-router/server/utils.ts
packages/nextjs/src/utils/clerk-js-script.tsx
packages/react/src/isomorphicClerk.ts
packages/react/src/types.ts
packages/react/src/utils/loadClerkJsScript.ts
packages/shared/src/loadScript.ts

When using a [strict-dynamic](https://content-security-policy.com/strict-dynamic/) content security policy, Clerk currently will not work, as we do not pass a nonce to the hotloaded clerk-js script. This PR adds a `nonce` prop to `ClerkProvider` that can be used to thread the nonce value through to the clerk-js script load. It also includes an extra feature for next.js where the nonce will be automatically pulled from the CSP header and threaded through without needing any props so long as the provider is server-rendered.

feat(clerk-react): Add 'nonce' prop to ClerkProvider

---

.changeset/ninety-numbers-serve.md
package-lock.json
packages/tanstack-start/package.json
packages/tanstack-start/src/server/getAuth.ts
packages/tanstack-start/src/server/index.ts
packages/tanstack-start/src/utils/errors.ts

This PR introduces `getAuth` server function that can be used inside the TanStack start `createServerFn`.
Example:
```tsx
import { getAuth } from '@clerk/tanstack-start/server'
import { createServerFn } from '@tanstack/start'
export const fetchCurrentUserPosts = createServerFn('GET', async (_payload, ctx) => {
const { userId } = await getAuth(ctx)
if (!userId) {
...
}
...
})
```

feat(tanstack-start): Add `getAuth` server function

---

.changeset/rotten-mangos-hear.md
packages/tanstack-start/README.md
packages/tanstack-start/src/client/ClerkProvider.tsx
packages/tanstack-start/src/utils/errors.ts

Right now when the `clerkHandler` is not configured in the SSR entrypoint `app/ssr.tsx` an error is thrown that in can't access the `__internal_clerk_state` which is not helpful on what is wrong, after this PR we throw a more useful error to  guide the user on how to setup the `clerkHandler()`

chore(tanstack-start): Throw more useful error when clerkHandler is not configured

---

.changeset/rotten-donkeys-sin.md
packages/clerk-js/src/ui/elements/AvatarUploader.tsx

The current `toggle` function passed to the placeholder logo click handler is toggling visibility between the placeholder and uploaded image and I believe we should be opening the upload dialog here instead
https://github.com/user-attachments/assets/b6a6b12e-7e76-4ac4-949e-0e74c42341c2

fix(clerk-js): Open the upload organization logo dialog on placeholder click

---

.changeset/pink-mails-try.md
package-lock.json
packages/elements/src/internals/machines/form/form.machine.ts
packages/elements/src/internals/machines/form/form.types.ts
packages/elements/src/internals/machines/sign-up/router.machine.ts
packages/elements/src/internals/machines/sign-up/router.types.ts
packages/elements/src/internals/machines/sign-up/start.machine.ts
packages/elements/src/internals/machines/sign-up/start.types.ts

Handles ticket-based invitation sign-up workflows. No direct additions/updates are required for implementation unless you're looking to conditionally disable the input which is made available via `FieldState` render props.
Fixes SDKI-167

feat(elements): Handle ticket-based invitation sign-up workflows

---

.changeset/young-spies-provide.md
packages/backend/src/api/endpoints/UserApi.ts

This adds `awscognito` to our `PasswordHasher` type.

feat(backend): Add `awscognito` to `PasswordHasher` type

---

.changeset/twelve-books-glow.md
packages/nextjs/src/server/nextFetcher.ts
packages/nextjs/src/server/protect.ts

Bug fix: Handle `nextGetStore.getStore()` returning `undefined`. Previously a TypeError would occur, when `pagePath` was accessed.
Fixes: #3772

fix(nextjs): Handle `__nextGetStaticStore` returning `undefined`

---

.changeset/shy-ghosts-flash.md
packages/astro/src/server/clerk-middleware.ts

This PR removes the redundant part where we set the `x-clerk-auth-*` headers twice, ensuring each header appears only once in the response. This also cleans up some types and unused non-null assertions.

fix(astro): Remove duplicate auth headers values

---

.changeset/itchy-geckos-tell.md
packages/elements/src/react/router/__tests__/router.test.ts
packages/elements/src/react/router/router.ts
packages/elements/src/utils/is-absolute-url.ts

Adds support for navigating to absolute URLs via `context.router.push`. This allows `redirect_url` to be an absolute URL.

fix(elements): Preserve absolute URLs passed via `redirect_url`

---

.changeset/nine-shoes-hug.md
package-lock.json
packages/astro/package.json
packages/astro/src/internal/create-clerk-instance.ts
packages/astro/src/internal/run-once.ts
packages/astro/src/types.ts

Since clerk-js is being hotloaded it is unnecessary to keep the npm package as a dependency

chore(astro): Remove dependency `@clerk/clerk-js`

---

.changeset/clean-flies-own.md
.changeset/plenty-drinks-drive.md
.changeset/red-bobcats-change.md
packages/dev-cli/src/cli.js
packages/dev-cli/src/commands/init.js
packages/dev-cli/src/commands/setup.js
packages/dev-cli/src/commands/watch.js
packages/dev-cli/src/utils/errors.js
packages/dev-cli/src/utils/getClerkPackages.js
packages/dev-cli/src/utils/getMonorepoRoot.js

This PR adds more error messages to `clerk-dev` to notify the user of invalid configurations. It now warns in the following instances:
- Running `clerk-dev init` with an existing configuration file
- Running `clerk-dev setup` or `clerk-dev watch` with a `null` `root` configuration
- Running `clerk-dev setup` with an invalid `publishableKey` or `secretKey`

feat(dev-cli): Improve warnings for invalid configurations

---

.changeset/fair-squids-deny.md
packages/clerk-js/src/ui/elements/ApplicationLogo.tsx

Fixes issue where application logos were rendering smaller then intended. Reverts the changes to application logo from https://github.com/clerk/javascript/pull/2716
Fixes SDKI-576
Square logo:
Horizontal logo:
Vertical logo:
Clerk logo before and after:
| Before | After |
| <img width="637" alt="Screenshot 2024-08-14 at 3 58 19 PM" src="https://github.com/user-attachments/assets/8e9f1c70-8e4e-4cb8-b6df-466ede0d5bb7"> | <img width="637" alt="Screenshot 2024-08-14 at 3 58 28 PM" src="https://github.com/user-attachments/assets/da3bee67-b15b-4e1e-bd73-1faa02ff3e11"> |

fix(clerk-js): Application logo rendering size

---

.changeset/fifty-terms-switch.md
packages/elements/examples/nextjs/app/page.tsx
packages/elements/examples/nextjs/app/sign-in/[[...sign-in]]/page.tsx
packages/elements/examples/nextjs/app/sign-up/[[...sign-up]]/page.tsx
packages/elements/src/internals/constants/index.ts
packages/elements/src/internals/machines/sign-in/router.machine.ts
packages/elements/src/internals/machines/sign-in/router.types.ts
packages/elements/src/react/sign-in/action/action.tsx
packages/elements/src/react/sign-in/action/navigate.tsx
packages/elements/src/react/sign-in/action/set-active-session.tsx
packages/elements/src/react/sign-in/choose-session.tsx
packages/elements/src/react/sign-in/choose-session/__tests__/choose-session.test.tsx
packages/elements/src/react/sign-in/choose-session/choose-session.hooks.ts
packages/elements/src/react/sign-in/choose-session/choose-session.tsx
packages/elements/src/react/sign-in/choose-session/index.tsx
packages/elements/src/react/sign-in/index.ts
packages/elements/src/react/sign-in/step.tsx
packages/elements/src/react/utils/is-valid-component-type.ts

Introduce multi-session choose account step and associated actions/components.
Example:
```tsx
<SignIn.Step name='choose-session'>
<SignIn.SessionList>
<SignIn.SessionListItem>
{({ session }) => <>{session.identifier} | <SignIn.Action setActiveSession>Switch...</SignIn.Action></>}
</SignIn.SessionListItem>
</SignIn.SessionList>
</SignIn.Step>
```
By default, `SessionList` does not include the current session. Adding `includeCurrentSession` to `SignIn.SessionList` will include it.
Fixes SDKI-290

feat(elements): Add active session selection [SDKI-290]

---

.changeset/big-cheetahs-exercise.md
packages/localizations/src/th-TH.ts

- Added Thai translation keys for signup start action link translations
- Updated Thai strings to correct grammatical errors

feat(localizations): Added Thai translation keys for signup start action link translations

---

.changeset/chatty-toys-relax.md
packages/localizations/src/cs-CZ.ts

- add some of missing translations for `cs-CZ` locale 🇨🇿

feat(localizations): Update `cs-CZ` translations

---

packages/ui/src/common/connections.tsx
packages/ui/src/components/sign-in/sign-in.tsx
packages/ui/src/components/sign-in/steps/choose-session.tsx
packages/ui/src/components/sign-in/steps/choose-strategy.tsx
packages/ui/src/components/sign-in/steps/forgot-password.tsx
packages/ui/src/components/sign-in/steps/get-help.tsx
packages/ui/src/components/sign-in/steps/reset-password.tsx
packages/ui/src/components/sign-in/steps/start.tsx
packages/ui/src/components/sign-in/steps/verifications.tsx
packages/ui/src/components/sign-up/steps/continue.tsx
packages/ui/src/components/sign-up/steps/start.tsx
packages/ui/src/components/sign-up/steps/verifications.tsx
packages/ui/src/hooks/use-appearance.ts
packages/ui/src/hooks/use-dev-mode-warning.ts
packages/ui/src/primitives/card.tsx

Use context parse appearance and remove useAppearance hook.

chore(ui): Use parsed appearance

---

packages/ui/src/components/sign-in/sign-in.tsx
packages/ui/src/contexts/AppearanceContext.tsx

This PR removes the need to manually call `useAppearance` and pass the resulting `appearance` to nested `AppearanceProvider` contexts by calling `usePartialAppearance` within the provider itself. This allows us to arbitrarily nest `AppearanceProvider`s without losing values. It also adjusts the `parseAppearance` call to use `parsedAppearance` instead, similarly to support arbitrary nesting levels.

feat(ui): Remove need to manually pass globalAppearance

---

.changeset/sour-bulldogs-explode.md
packages/clerk-js/src/utils/captcha/hcaptcha.ts
packages/clerk-js/src/utils/captcha/turnstile.ts

This PR improves the error message thrown when falling back to invisible CAPTCHA, if the captcha DOM element is not found.

fix(clerk-js): Better CAPTCHA widget console error

---

.changeset/few-teachers-brake.md
packages/backend/src/api/endpoints/UserApi.ts

This PR adds  the `DELETE /users/{user_id}/profile_image` ([reference](https://clerk.com/docs/reference/backend-api/tag/Users#operation/DeleteUserProfileImage)) endpoint to the Backend SDK under the `deleteUserProfileImage` method on `UserAPI` class

feat(backend): Add Delete user profile image

---

packages/ui/src/components/sign-in/steps/choose-strategy.tsx
packages/ui/src/components/sign-in/steps/start.tsx
packages/ui/src/components/sign-up/steps/start.tsx
packages/ui/theme-builder/app/components/logo.tsx
packages/ui/theme-builder/app/page.tsx
packages/ui/theme-builder/app/theme-builder.tsx

Implements `socialButtonsPlacement` logic.
Example:
```tsx
<SignIn
appearance={{
layout: {
socialButtonsPlacement: 'bottom',
},
}}
/>
```
| Top | Bottom |
| <img width="1392" alt="Screenshot 2024-08-20 at 4 09 33 PM" src="https://github.com/user-attachments/assets/7c20ba2d-a592-472d-8228-cffabc22ec4c"> | <img width="1392" alt="Screenshot 2024-08-20 at 4 08 12 PM" src="https://github.com/user-attachments/assets/3391e411-990f-41be-8f87-fb53ab1106cc"> | 
Closes SDKI-559

feature(ui): Implement `socialButtonsPlacement` layout logic

---

.changeset/plenty-news-visit.md
packages/localizations/src/is-IS.ts

Fixes two typos in the Icelandic localization file

fix(localizations): Update Icelandic translations

---

.changeset/pretty-peas-search.md
package-lock.json
packages/astro/package.json
packages/astro/src/stores/external.ts
packages/astro/src/stores/internal.ts

This PR fixes an issue where the `$authStore` nanostore goes back to its initial values (`null/undefined`) after clerk-js has been loaded. See what's happening in the screen recording below:
https://github.com/user-attachments/assets/66a73350-34eb-4d76-9b0a-db91683b0df4
This is happening because `computed` stores react each time any of their dependencies get updated. In our case, the `$csrStore` and `$initialState` stores. It resets back to `undefined` even though we have an initial value because of how the [`derivedStore`](https://github.com/clerk/javascript/blob/main/packages/shared/src/deriveState.ts) function works:
1. We set the `$initialState` coming from SSR, we have an `$authStore` value [available](https://github.com/clerk/javascript/blob/ed7baa0488df0ee4c48add2aac934ffb47e4a6d2/p …

fix(astro): Use batched stores to avoid race conditions in auth store

---

.changeset/three-feet-nail.md
packages/clerk-js/src/ui/components/UserProfile/MfaSection.tsx

Currently, when you have both an TOTP + sms code two-step verification, we show the ability to set an SMS code as default but TOTP always takes precedence which makes for confusing behavior where users think they can set the SMS code as the default.
There is also a scenario where a user doesn't have a TOTP code setup, and two sms codes but they are not able to set the default SMS code due to TOTP code not available https://github.com/clerk/javascript/blob/22f19d3bfa987268610e93d2028815d12b374110/packages/clerk-js/src/ui/components/UserProfile/MfaSection.tsx#L96
This PR updates the `MfaPhoneCodeMenu` logic to only allow setting sms code as default when there is no TOTP code set, and disables set default on sms codes when current sms code is already set as default. …

fix(clerk-js): Update MFA second factor default UI logic

---

.changeset/friendly-waves-cheat.md
packages/astro/src/astro-components/control/SignedOut.astro
packages/astro/src/internal/create-clerk-instance.ts

This PR fixes an issue where `$clerkStore` never gets updated even after Clerk JS has been loaded.
See comment in [this PR](https://github.com/clerk/javascript/pull/3911/files#r1720870617) for more info.
```ts
import { $clerkStore } from '@clerk/astro/client'
$clerkStore.subscribe((clerk) => {
console.log('clerk', clerk?.loaded) // loaded now gives correct values
})
```

fix(astro): Remove extra character and improve Clerk nanostore

---

.changeset/famous-eggs-cough.md
packages/clerk-js/src/ui/hooks/useEnabledThirdPartyProviders.tsx

In this pr we are fixing undefined properties error in `ConnectedAccountsMenu.tsx` when Custom OAuth Provider is `active` and `authenticatable` is `false`
The error was:
The bug was that we populated the `strategyToDisplayData` with `authenticatable` instead of `active` Custom OAuth Providers.

fix(clerk-js): Fix undefined properties error in `ConnectedAccountsMenu.tsx`

---

package-lock.json
packages/ui/package.json
packages/ui/src/contexts/AppearanceContext.test.tsx
packages/ui/src/contexts/AppearanceContext.tsx
packages/ui/testSetup.js
packages/ui/vitest.config.mts

This PR adds support for component testing to the `ui` package. This allows us to render the `AppearanceProvider` component within tests and ensure that the resulting `parsedAppearance` is the value we expect based on the provided values.

test(ui): Add support for component testing

---

.changeset/strong-emus-sleep.md
packages/tailwindcss-transformer/src/__tests__/__snapshots__/transform-classname-cl-test.test.ts.snap
packages/tailwindcss-transformer/src/__tests__/__snapshots__/transform-classname-empty.test.ts.snap
packages/tailwindcss-transformer/src/__tests__/transform-classname-cl-test.test.ts
packages/tailwindcss-transformer/src/__tests__/transform-classname-empty.test.ts
packages/tailwindcss-transformer/src/index.ts

This PR adds support for empty class names and `cl-test` prefixed class names to our Tailwind transformer. This allows us to use code like `className: ''` without causing a build error. Additionally, it allows for classes such as `cl-test-one` to remain unchanged, and prevents them from throwing errors. This is useful when writing unit tests within source files since it alleviates the need to use actual Tailwind classes.

feat(tailwindcss-transformer): Add support for empty class names

---

.changeset/two-apricots-serve.md
packages/elements/src/internals/machines/sign-in/__tests__/router.selectors.test.ts
packages/elements/src/internals/machines/sign-in/router.selectors.ts

Fix `SignIn.SafeIdentifier` potentially outputting an incorrect identifier when using similar multi-session sign in strategies.
Fixes: SDKI-609

fix(elements): Fix `SignIn.SafeIdentifier` potentially outputting an incorrect value

---

.changeset/selfish-dogs-taste.md
packages/clerk-js/src/ui/hooks/__tests__/useEnabledThirdPartyProviders.test.tsx
packages/types/src/oauth.ts

Add constants for Hugging Face built in OAuth Provider.

feat(types): Add Hugging Face OAuth Provider constants

---

.changeset/calm-rabbits-talk.md
packages/clerk-js/src/core/resources/User.ts

Dropping the unnecessary  sessionId parameter from the path. Verifying a session should only be applied to the current active session of a user and can be implicitly defined.

chore(clerk-js): Remove sessionId parameter from all verify session methods

---

.changeset/cuddly-mails-lie.md
packages/clerk-js/src/ui/common/constants.ts
packages/types/src/web3.ts

As part of the preparation of introducing a new Web3 provider (Coinbase Wallet) we make sure to update the relevant types

feat(clerk-js,types): Introduce Coinbase Wallet Web3 provider types

---

.changeset/purple-rockets-fetch.md
packages/tanstack-start/src/server/authenticateRequest.ts
packages/tanstack-start/src/server/loadOptions.ts
packages/tanstack-start/src/server/utils/index.ts

This PR fixes a bug occurred when using `getAuth` in multiple server functions

fix(tanstack-start): Fix bug for getAuth

---

packages/ui/src/contexts/AppearanceContext.test.tsx

Adds a few tests for the `theme` prop on `AppearanceProvider`.

test(ui): Add tests for theme prop

---

.changeset/gorgeous-crabs-judge.md
packages/clerk-js/bundlewatch.config.json
packages/clerk-js/src/ui/lazyModules/components.ts

Monitor bundle size of google one tap.

chore(clerk-js): Add GoogleOneTap to bundlewatch

---

.changeset/purple-rice-tell.md
packages/clerk-js/src/core/resources/User.ts
packages/clerk-js/src/ui/components/UserProfile/Web3Form.tsx
packages/clerk-js/src/utils/web3.ts
packages/localizations/src/en-US.ts
packages/types/src/localization.ts
packages/types/src/user.ts

Allow users to connect their Coinbase Wallet to their account via `<UserProfile />`
https://github.com/user-attachments/assets/6989682b-a938-4b2f-9ddb-e76e52cbd92c

feat(clerk-js,types): Support connecting Coinbase Wallet via <UserProfile />

---

.changeset/sixty-kids-sparkle.md
packages/clerk-js/src/core/__tests__/clerk.test.ts
packages/clerk-js/src/core/clerk.ts

Otherwise, in Nextjs apps the invalidate cache server action will result in a 404 if current route is being protected by auth().protect()

fix(clerk-js): Keep the session cookie while cache is being invalidated

---

.changeset/neat-vans-wonder.md
packages/types/src/saml.ts

Updates `SAML_IDPS` to mention Microsoft Entra ID instead of Azure AD.
Microsoft Entra ID is the new name for Azure AD. The names Azure Active Directory, Azure AD, and AAD are replaced with Microsoft Entra ID.

chore(types): Update `SAML_IDPS` constant for Microsoft Entra ID

---

.changeset/quiet-ravens-sneeze.md
packages/backend/src/api/endpoints/UserApi.ts

`deleteSelfEnabled` was missing from the `UpdateUserParams` type

fix(backend): Add missing `deleteSelfEnabled` property in `UpdateUserParams`

---

.changeset/thin-gorillas-deliver.md
packages/clerk-js/src/core/clerk.ts
packages/clerk-js/src/core/resources/SignIn.ts
packages/clerk-js/src/core/resources/SignUp.ts
packages/clerk-js/src/ui/components/SignIn/SignInSocialButtons.tsx
packages/clerk-js/src/ui/components/SignUp/SignUpSocialButtons.tsx
packages/clerk-js/src/utils/web3.ts
packages/react/src/isomorphicClerk.ts
packages/types/src/clerk.ts
packages/types/src/signIn.ts
packages/types/src/signUp.ts
packages/types/src/web3Wallet.ts

Adds support for authenticating using the Coinbase Wallet browser extension
https://github.com/user-attachments/assets/3c02edf7-aa57-4e43-8ba4-5dcf5697f92e

feat(clerk-js,types): Support Coinbase Wallet strategy during sign in/up flows

---

.changeset/mighty-roses-give.md
packages/astro/src/astro-components/unstyled/SignInButton.astro
packages/astro/src/astro-components/unstyled/SignOutButton.astro
packages/astro/src/astro-components/unstyled/SignUpButton.astro

This PR sets a default element type to the [Polymorphic](https://docs.astro.build/en/guides/typescript/#polymorphic-type) unstyled Astro components and addresses prop spreading to resolve TS union errors and simplify type evaluation:
With a default element:
Fixes ECO-172

fix(astro): Set default element for Polymorphic components

---

.changeset/stale-feet-tease.md
packages/tanstack-start/src/client/ClerkProvider.tsx
packages/tanstack-start/src/client/useAwaitableNavigate.ts

This PR fixes hard reload navigation issue happening when navigating to component internal routes

fix(tanstack-start): Fix hard reload flicker

---

.changeset/good-snakes-confess.md
packages/backend/src/api/resources/Invitation.ts

Adds the `url` property to the Invitation object for the Backend SDK

fix(backend): Add missing url property to Invitation object

---

.changeset/chilly-shrimps-stare.md
package-lock.json
packages/clerk-js/bundlewatch.config.json
packages/clerk-js/package.json
packages/clerk-js/src/core/clerk.ts
packages/clerk-js/src/core/resources/SignIn.ts
packages/clerk-js/src/core/resources/SignUp.ts
packages/clerk-js/src/ui/common/constants.ts
packages/clerk-js/src/utils/injectedWeb3Providers.ts
packages/clerk-js/src/utils/web3.ts
packages/clerk-js/webpack.config.js
packages/elements/src/react/hooks/use-third-party-provider.hook.ts
packages/react/src/isomorphicClerk.ts
packages/types/src/clerk.ts
packages/types/src/signIn.ts
packages/types/src/signUp.ts
packages/types/src/web3.ts

Coinbase Wallet is a new generic web3 provider and strategy that supports both Smart Wallets and Coinbase Wallet browser extension. Users can use it to authenticate themselves using their own web3 address as an identifier
In order to take advantage of the Coinbase Wallet we are lazy loading `@coinbase/wallet-sdk` and all its direct dependencies. Resulting in a new chunk ~58KB which will only be loading when the end user selects that provider.

feat(clerk-js,types,clerk-react): Support Coinbase Wallet web3 provider and authentication strategy

---

.changeset/modern-foxes-run.md
packages/clerk-js/src/utils/injectedWeb3Providers.ts
packages/clerk-js/src/utils/web3.ts

This PR makes sure to **NOT** call browser specific methods (`addEventListener`, `dispatchEvent`) implemented in [4059](https://github.com/clerk/javascript/pull/4059) in non-browser environments. Even though we are trying to block calls by [checking `window` object](https://github.com/clerk/javascript/blob/c63a5adf0ba4b99252146f168318f51b709bb5dd/packages/clerk-js/src/utils/injectedWeb3Providers.ts#L40), it'll still pass because React Native does have some polyfills to the `window` object.
Fixes SDK-1922

fix(clerk-js): Ensure we do not access `addEventListener` and `dispatchEvent` in non-browser environments

---

.changeset/light-donuts-shake.md
packages/clerk-js/src/core/clerk.ts
packages/clerk-js/src/core/resources/SignIn.ts
packages/clerk-js/src/core/resources/SignUp.ts
packages/clerk-js/src/ui/common/constants.ts
packages/clerk-js/src/utils/injectedWeb3Providers.ts
packages/clerk-js/src/utils/web3.ts
packages/elements/src/internals/machines/sign-in/start.machine.ts
packages/elements/src/internals/machines/sign-in/verification.machine.ts
packages/elements/src/internals/machines/sign-up/start.machine.ts
packages/elements/src/react/hooks/use-third-party-provider.hook.ts
packages/elements/src/react/utils/map-scope-to-strategy.ts
packages/react/src/isomorphicClerk.ts
packages/types/src/clerk.ts
packages/types/src/signIn.ts
packages/types/src/signUp.ts
packages/types/src/web3.ts

The current 'coinbase' web3 provider has been replaced by a generic 'coinbase_wallet' provider which supports both Smart Wallets and the Coinbase Wallet browser extension. The feature is not yet released, so it's safe to remove them

chore(clerk-js,types,clerk-react,elements): Drop coinbase web3 provider

---

.changeset/bright-falcons-move.md
packages/clerk-js/src/core/resources/Session.ts
packages/clerk-js/src/core/resources/__tests__/Session.test.ts

Fixes a bug where `getToken()` would read stale organization data from `clerk.organization`. This is problematic because in the `setActive()` flow we call `getToken()` before `clerk.organization` is updated, and so we were reading a stale org ID when attempting to fetch a token for a new session.
For impersonation specifically, this was problematic as the impersonator's session would be in memory while `setActive()` was being called with the impersonated session.

fix(clerk-js): Ensure getToken() reads correct organization ID

---

.changeset/silent-students-vanish.md
packages/elements/src/internals/machines/sign-in/router.machine.ts
packages/elements/src/internals/machines/sign-in/verification.machine.ts

Enables `AUTHENTICATE.PASSKEY` to be called from within the First Factor verification step.
Fixes SDKI-640

feat(elements): Allow for Passkey events in verifications

---

.changeset/proud-coats-look.md
packages/elements/src/internals/errors/index.ts
packages/elements/src/internals/machines/form/form.machine.ts
packages/shared/src/error.ts

Started getting a type error where `errors` was returning as any vs the correct error type.

fix(elements): Form machine error typing

---

.changeset/rare-onions-rest.md
integration/templates/astro-node/src/pages/buttons.astro
packages/astro/src/astro-components/unstyled/SignInButton.astro
packages/astro/src/astro-components/unstyled/SignOutButton.astro
packages/astro/src/astro-components/unstyled/SignUpButton.astro
packages/astro/src/astro-components/unstyled/utils.ts
packages/astro/src/types.ts

This PR adds the option to use custom elements/components inside our unstyled components, similar to the [React counterpart](https://clerk.com/docs/components/unstyled/sign-in-button#custom-usage), and adds a deprecation notice for the `as` prop.
With this change, we can now do:
```astro
---
import { SignInButton } from '@clerk/components/astro'
---
<SignInButton asChild>
<button>Sign in with Clerk</button>
</SignInButton>
```
The new `asChild` prop determines if we should render the default slot as an element or just a string. We need this prop because Astro doesn't have a way to determine if a slot contains an element/component or a string.
Previously, we used the `as` prop to render a different element:
```astro
---
import { SignInButton } from '@clerk/components/astro'
--- …
```

chore(astro): Allow child elements in unstyled Astro components

---

.changeset/thirty-hotels-buy.md
packages/astro/src/integration/vite-plugin-astro-config.ts

This small PR pre-bundles `@clerk/astro/client` to ensure proper processing of  `<script>` tags and nanostore imports in our exported control components. This resolves runtime issues in development when these components are used in other projects.
Resolves ECO-188

fix(astro): Pre-bundle client dependency for exported control components

---

.changeset/moody-donuts-explode.md
packages/expo/src/provider/singleton/createClerkInstance.ts

This PR addresses an issue where the `isMobile` value of a [`SessionActivity`](https://clerk.com/docs/references/javascript/session-with-activities#session-activity) is incorrectly set to `false` for iOS devices. The problem is caused by some iOS devices sending an empty `user-agent` header:
Here's an example of an expo login request in iOS (notice there's no `user-agent` header and `isMobile` is false):
The backend relies on either the `x-mobile` or `user-agent` headers to determine if a request is from a mobile device. This update adds the `x-mobile` header for all native requests, ensuring that the backend correctly records session activities as mobile, regardless of the `user-agent` value.
Here's a [`SessionActivity`](https://clerk.com/docs/references/javascript/session-with-activities …

fix(clerk-expo): Ensure correct mobile detection for native requests

---

.changeset/poor-months-share.md
packages/tanstack-start/src/server/clerkClient.ts
packages/tanstack-start/src/server/constants.ts
packages/tanstack-start/src/server/index.ts
packages/tanstack-start/src/server/loadOptions.ts
packages/tanstack-start/src/utils/env.ts

This PR re-exports types from `@clerk/backend` from the `@clerk/tanstack-start/server` subpath and also introduces 
`clerkClient` which gives access to backend client but with using the environment variables by default.

feat(tanstack-start): Export @clerk/backend from server subpath

---

.changeset/angry-phones-nail.md
packages/backend/src/api/resources/JSON.ts
packages/backend/src/api/resources/User.ts

Bug fix: Introducing missing `deleteSelfEnabled` from User.

fix(backend): Missing `deleteSelfEnabled` from User

---

.changeset/yellow-ads-beam.md
packages/localizations/src/es-ES.ts

Missing update profile translation for es-ES.ts, causes no button to render not allowing user to update the profile image.
Fixes: https://linear.app/clerk/issue/DOCS-9198/add-missing-es-ests-translation-for-update-profile-button

fix(localizations): update missing field for profile button

---

.changeset/mean-swans-relax.md
packages/backend/src/api/resources/JSON.ts
packages/backend/src/api/resources/Webhooks.ts

Resolves ORGS-165
Add webhook event types for roles and permissions. Those events were introduced a while ago and weren't included in the types here.

chore(backend): Add webhook event types for roles and permissions

---

.changeset/witty-knives-build.md
package-lock.json
packages/express/package.json
packages/express/src/__tests__/clerkMiddleware.test.ts
packages/express/src/__tests__/helpers.ts
packages/express/src/clerkMiddleware.ts
packages/express/src/types.ts

Our SDK development guidelines suggests to [add handshake support](https://clerk.com/docs/references/sdk/fullstack#add-handshake-support) for Fullstack SDKs. This PR makes handshaking in our Express SDK opt-in since this is a [Backend-only SDK](https://clerk.com/docs/references/sdk/backend-only).
This should be a safe minor version bump since we didn't advertise and document our Express SDK yet.
_This is part of making our Express SDK ready. Tests to be added_
Resolves **ECO-195**

feat(express): Make handshake opt-in

---

.changeset/popular-coats-turn.md
packages/express/README.md
packages/express/src/__tests__/__snapshots__/exports.test.ts.snap
packages/express/src/__tests__/requireAuth.test.ts
packages/express/src/index.ts
packages/express/src/requireAuth.ts

This pull request modifies the `requireAuth` middleware to return a custom `UnauthorizedError` via `next()` instead of throwing a 401 directly. The core change:
```ts
// Before
if (!getAuth(request).userId) {
return response.status(401).send('Unauthorized');
}
// After
if (!getAuth(request).userId) {
return next(new UnauthorizedError());
}
```
This aligns the `requireAuth` middleware with Express [error handling patterns](https://expressjs.com/en/guide/error-handling.html) and makes it customizable. Userland can now configure their own error handling middleware to process the `UnauthorizedError` as needed. Here's an example:
```ts
import { clerkMiddleware, requireAuth, UnauthorizedError } from '@clerk/express'
const app = express()
app.use(clerkMiddleware())
app.get('/protected', …
```

feat(express): Make `requireAuth` middleware flexible

---

.changeset/smart-mice-worry.md
packages/astro/src/integration/vite-plugin-astro-config.ts

Previously, the integration was [stringifying the entire Astro config](https://github.com/clerk/javascript/blob/d8954948d08e3d8090b2be41b4670d76341c6dfd/packages/astro/src/integration/vite-plugin-astro-config.ts#L33), which causes a a "Converting circular structure to JSON" error when the Clerk integration was last in the integrations config. This PR fix removes the full config stringification and instead only uses the `output` property from the Astro config, as that's the only part needed.
Resolves SDK-1930
Fixes https://github.com/clerk/javascript/issues/4142

fix(astro): Prevent circular JSON error with complex Astro configs

---

.changeset/spotty-students-judge.md
package-lock.json
packages/backend/src/constants.ts
packages/backend/src/tokens/__tests__/request.test.ts
packages/backend/src/tokens/request.ts
packages/fastify/src/__tests__/__snapshots__/constants.test.ts.snap

Chrome aggressively caches inactive tabs. If we don't set the header here, all 307 redirects will be cached and the handshake will end up in an infinite loop.

fix(backend): Do not cache 307 redirects

---

.changeset/friendly-bottles-sin.md
package-lock.json
packages/dev-cli/package.json
packages/dev-cli/src/commands/watch.js

This PR updates `concurrently` to the latest version which has improved TypeScript types, removing the need to use `ts-expect-error`.

chore(dev-cli): Update to latest concurrently

---

.changeset/shaggy-lobsters-film.md
packages/shared/package.json
packages/shared/subpaths.mjs
scripts/subpath-workaround.mjs

The last couple of PRs merged did miss adding the new subpaths to the `files` array in package.json. The script that should have checked it miss it, it'll catch it now.

fix(shared): Add missing entries to "files" array in package.json

---

.changeset/wild-seals-beg.md
packages/clerk-js/src/ui/elements/PhoneInput/PhoneInput.tsx

Fixes issue where phone input combobox select options were not rendering correctly in dark theme due to no color being defined on select options.
| ![Screenshot 2024-09-16 at 2 52 45 PM](https://github.com/user-attachments/assets/83381c3d-2a68-40c6-b122-38a2528f0083) | ![Screenshot 2024-09-16 at 2 52 21 PM](https://github.com/user-attachments/assets/1bb17851-6055-47a4-b5ef-3e998e1bc99d) |
| ![Screenshot 2024-09-16 at 3 01 23 PM](https://github.com/user-attachments/assets/711d2d7e-9c5b-435e-b001-3a1455aeef61) | ![Screenshot 2024-09-16 at 3 01 59 PM](https://github.com/user-attachments/assets/cc20097d-0095-49cf-b068-ddcb1fd0aa10) |
| ![Screenshot 2024-09-16 at 3 02 …

fix(clerk-js): Add explicit text color to phone number combobox select option

---

.changeset/ten-months-kick.md
packages/nextjs/src/server/__tests__/clerkMiddleware.test.ts
packages/nextjs/src/server/clerkClient.ts
packages/nextjs/src/server/clerkMiddleware.ts

Resolves SDK-1932 
Allows to dynamically access the Next.js `request` object when providing options to `clerkMiddleware`: 
```ts
export default clerkMiddleware((auth) => {
return NextResponse.next();
}, (req) => {
return ({
domain: req.nextUrl.host,
})
});
```
Another example of a use case where Clerk keys could be fetched based on tenant: 
```ts
export default clerkMiddleware((auth, req) => {
return NextResponse.next();
}, (req) => {
const tenant = getTenant(req)
const { publishableKey, secretKey } = getClerkKeys(tenant)
return {
publishableKey,
secretKey,
}
})
```
---
This is another improvement for the ["Next.js dynamic keys" feature](https://clerk.com/docs/references/nextjs/clerk-middleware#dynamic-keys). So far we propagate `secretKey` and `publishableKey` from the middleware to the …

feat(nextjs): Allows access to `request` object to dynamically define `clerkMiddleware` options

---

.changeset/warm-cows-beam.md
integration/tests/handshake.test.ts
packages/backend/src/constants.ts
packages/backend/src/tokens/request.ts

This PR introduces the following query params on the handshake URL, so we can have better observability:
- `__clerk_hs_reason`: the reason handshake was triggered.
- `__clerk_refresh`: the status of the refresh token. It can have the following values:
- `no-cookie` if the refresh token cookie does not exist
- `non-eligible` if the refresh token exists but it's not eligible to be used
- `invalid-session-token` if verifyToken fails for the returned session token
- `<backend_error_code>` if the refresh fails on the backend
- `unexpected-refresh-error` if any other unexpected error happens when attempting to refresh the token

fix(backend): Append the handshake reason as a query param

---

.changeset/cyan-mirrors-notice.md
packages/expo/src/provider/ClerkProvider.tsx
packages/react/src/types.ts
packages/types/src/clerk.ts

PR for https://github.com/clerk/clerk-docs/pull/1553
Fixes ECO-198

chore(types): Improve ClerkProvider JSDoc

---

.changeset/nasty-walls-double.md
packages/clerk-js/src/ui/elements/Card/CardFooter.tsx

This PR fixes wrong padding on the footer of UP and OP components when development notice was enabled and it was viewed in small screens

fix(clerk-js): UP/OP footer padding on small screens

---

.changeset/big-elephants-add.md
packages/shared/src/compiled/path-to-regexp/index.d.ts
packages/shared/src/compiled/path-to-regexp/index.js
packages/shared/src/pathToRegexp.ts

This surfaces a new path-to-regexp function, [match](https://github.com/pillarjs/path-to-regexp/tree/6.x?tab=readme-ov-file#match), that upcoming functionality depends on.
Thanks to @nikosdouvlis for giving me the run-down. The procedure goes:
To create the new minified code (high-level)
- Create a minimal typescript project with an index.ts that imports the functionality that you need
- Use tsup to bundle it into a minified file
- Beautify the minified file (e.g. add newlines)
More details for internal folks here: https://clerkinc.slack.com/archives/C07LN8YS9HB/p1726666913614259?thread_ts=1726240424.533199&cid=C07LN8YS9HB

chore(shared): Exports `match` utility from the `path-to-regexp` lib

---

.changeset/heavy-planes-smash.md
packages/astro/package.json

This small PR allows our Clerk SDK to show up in the [Astro integrations list page](https://astro.build/integrations). More info on how they pull up repositories from NPM [here](https://docs.astro.build/en/reference/publish-to-npm/#packagejson-data).

chore(astro): Add `@clerk/astro` to Astro integrations page

---

.changeset/green-hairs-drive.md
packages/shared/src/router/router.ts

This PR fixes an issue with `createClerkRouter` where class-based routers were unable to access private members in the `pathname` and `searchParams` methods due to losing the scope of `this`.

fix(shared): Allow routers to access private members

---

.changeset/ninety-comics-scream.md
packages/backend/src/errors.ts
packages/backend/src/jwt/assertions.ts
packages/backend/src/tokens/__tests__/request.test.ts
packages/backend/src/tokens/authStatus.ts
packages/backend/src/tokens/request.ts

This PR replaces the `'session-token-outdated'` auth error reason with the following 4 more specific ones:
1. `'session-token-expired'`: Session token has expired.
2. `'session-token-iat-before-client-uat'`: Session token was issued before the timestamp depicted in `__client_uat`
3. `'session-token-not-active-yet'`: Current time was before session token's nbf claim (possible clock skew)
4. `'session-token-iat-in-the-future'`:  Session token was issued in the future (possible clock skew)

fix(backend): Replace `session-token-outdated` error with more specific errors

---

.changeset/violet-kangaroos-lay.md
packages/clerk-js/src/ui/components/UserButton/UserButtonPopover.tsx

Only render the `Sign out of all accounts` button if the user has more than one other session open.
| ![Screenshot 2024-09-20 at 11 58 48 AM](https://github.com/user-attachments/assets/02c3e069-fede-4f3d-bd94-224e68822aeb) | ![Screenshot 2024-09-20 at 11 58 14 AM](https://github.com/user-attachments/assets/200abb4f-4a58-47d3-ad48-dccc1ef356b1) | 
Multiple sessions still visible:
Fixes SDKI-670

fix(clerk-js): UserButton sign out of all accounts visibility

---

.changeset/light-geckos-allow.md
packages/backend/src/api/endpoints/OrganizationApi.ts

Part of ORGS-197
`include_members_count` query param for `/organizations/{organizationID}` recently got supported on BAPI, therefore forwarding this param here as well.

chore(backend): Introduce `include_members_count` parameter to `getOrganization`

---

.changeset/tender-apes-smile.md
integration/tests/handshake.test.ts
packages/backend/src/constants.ts
packages/backend/src/tokens/__tests__/request.test.ts
packages/backend/src/tokens/authStatus.ts
packages/backend/src/tokens/request.ts

This PR is dropping the `__clerk_refresh` debugging query param and uses the `__clerk_hs_reason` param for all the different handshake scenarios. 
All errors are the following:
- 'client-uat-but-no-session-token'
- 'dev-browser-missing'
- 'dev-browser-sync'
- 'primary-responds-to-syncing'
- 'satellite-needs-syncing'
- 'session-token-and-uat-missing'
- 'session-token-iat-before-client-uat'
- 'session-token-nbf'
- 'session-token-iat-in-the-future'
- 'session-token-but-no-client-uat'
- 'session-token-expired-refresh-non-eligible-no-refresh-cookie'
- 'session-token-expired-refresh-non-eligible-non-get'
- 'session-token-expired-refresh-invalid-session-token'
- 'session-token-expired-refresh-missing-api-client'
- 'session-token-expired-refresh-missing-session-token'
- …

fix(backend): Drop the `__clerk_refresh` debugging query param

---

.changeset/large-chefs-move.md
packages/clerk-js/src/core/resources/OrganizationSettings.ts
packages/clerk-js/src/ui/components/OrganizationProfile/InviteMembersForm.tsx
packages/clerk-js/src/ui/components/OrganizationProfile/__tests__/InviteMembersPage.test.tsx
packages/clerk-js/src/ui/utils/test/fixtureHelpers.ts
packages/types/src/organizationSettings.ts

Resolves ORGS-211
Prepares `OrganizationProfile` for the upcoming `default_role` changes. When inviting a member, the `default_role` will be automatically selected, otherwise it falls back to the only available role. 
Currently behind a feature flag in the Dashboard, we're now allowing updating `default_role` regardless of whether verified domains are enabled. 
---
https://github.com/user-attachments/assets/4750a26a-105c-4b10-9586-b2cb952bbe48

feat(clerk-js,types): Supports default role on `OrganizationProfile` invitations

---

.changeset/lazy-rabbits-fry.md
packages/clerk-js/src/ui/elements/PhoneInput/PhoneInput.tsx
packages/types/src/clerk.ts
packages/ui/src/common/phone-number-field.tsx

This PR adds the type for `__internal_country`, which allows us to remove a few `ts-expect-error` statements and `as any` casts.

fix(clerk-js,types): Add type for __internal_country

---

.changeset/gold-lamps-appear.md
packages/clerk-js/bundlewatch.config.json
packages/clerk-js/src/core/constants.ts
packages/clerk-js/src/ui/components/SignIn/SignInStart.tsx
packages/clerk-js/src/ui/components/SignIn/__tests__/SignInStart.test.tsx
packages/clerk-js/src/ui/utils/test/fixtureHelpers.ts
packages/types/src/userSettings.ts
packages/ui/src/components/sign-in/steps/start.tsx
packages/ui/src/constants/user-settings.ts

Hide sign up url from <SignIn /> component when the Invite-Only mode is turned on.
In a following pr we're going to introduce e2e tests

feat(clerk-js,ui,types): Hide sign up url from <SignIn /> component mode is restricted

---

.changeset/gold-vans-swim.md
packages/clerk-js/src/core/resources/SignUp.ts

There is a chance that as a first time visitor when you try to setup and use the Coinbase Wallet from scratch in order to authenticate, the initial generate signature request to be rejected. For this reason we retry the request once more in order for the flow to be able to be completed successfully.
https://github.com/user-attachments/assets/26ec0c8b-055b-4df3-a71b-482ed02b4b34
https://github.com/user-attachments/assets/0cdc578f-c810-46b8-ac6e-92511bcc5c8f

fix(clerk-js): Handle gracefully Coinbase Wallet initial configuration

---

.changeset/fresh-forks-talk.md
packages/backend/src/api/resources/JSON.ts
packages/backend/src/api/resources/SamlAccount.ts
packages/backend/src/api/resources/SamlConnection.ts
packages/clerk-js/bundlewatch.config.json
packages/clerk-js/src/core/resources/SamlAccount.ts
packages/clerk-js/src/ui/components/UserProfile/AccountPage.tsx
packages/clerk-js/src/ui/components/UserProfile/ConnectedAccountsSection.tsx
packages/clerk-js/src/ui/components/UserProfile/EmailsSection.tsx
packages/clerk-js/src/ui/components/UserProfile/PhoneSection.tsx
packages/clerk-js/src/ui/components/UserProfile/Web3Section.tsx
packages/clerk-js/src/ui/components/UserProfile/__tests__/AccountPage.test.tsx
packages/types/src/index.ts
packages/types/src/json.ts
packages/types/src/samlAccount.ts
packages/types/src/samlConnection.ts

This pull request introduces a new feature for SAML connections. On the dashboard, users will be able to turn on/off a new flag called `disable_additional_identifications`. This is responsible for blocking the users to add any new identification other than their saml account. This pull request adds the new `saml_connection` field on the `saml_accounts`, and perform a logical check on the `<UserProfile />` to conditional render the other sections (and add buttons).

feat(clerk-js,backend,types): Implement "disable additional identifiers" for SAML connection

---

.changeset/tame-forks-type.md
packages/backend/src/api/endpoints/OrganizationApi.ts
packages/backend/src/api/resources/OrganizationDomain.ts
packages/backend/src/api/resources/Verification.ts
packages/backend/src/api/resources/index.ts
packages/types/src/json.ts

Introduces the organization domain CRUD under the `organizations` API on the backend.

feat(backend,types): Introduces organization domains CRUD API

---

.changeset/loud-tables-rush.md
packages/clerk-js/src/ui/components/SignUp/SignUpContinue.tsx

This is a v4 backport of #3401

fix(clerk-js): Update existing `SignUp` object on `SignUpContinue` OAuth [backport]

---

.changeset/honest-falcons-tie.md
packages/clerk-js/src/core/constants.ts
packages/clerk-js/src/ui/components/SignIn/SignInStart.tsx

Handle `sign_up_mode_restricted` error encountered in an oauth flow

chore(clerk-js): Handle `sign_up_mode_restricted` error encountered in an oauth flow

---

.changeset/cyan-turtles-fly.md
packages/clerk-js/src/ui/components/OrganizationSwitcher/OrganizationSwitcher.tsx

Fixes issue where `defaultOpen` prop was not being passed correctly to the `OrganizationSwitcher` popover instance.
https://github.com/user-attachments/assets/0bfd3121-28f9-4268-8bd2-3d8dcb503155

fix(clerk-js): Pass `defaultOpen` prop within org switcher

---

.changeset/early-seahorses-warn.md
packages/backend/src/tokens/request.ts

Adds the `session-token-expired-refresh-expired-session-token-missing-sid-claim` handshake reason

fix(backend): Add a new handshake reason for debug

---

.changeset/wise-dryers-perform.md
packages/express/README.md
packages/express/src/__tests__/__snapshots__/exports.test.ts.snap
packages/express/src/__tests__/clerkMiddleware.test.ts
packages/express/src/__tests__/helpers.ts
packages/express/src/__tests__/requireAuth.test.ts
packages/express/src/authenticateRequest.ts
packages/express/src/clerkMiddleware.ts
packages/express/src/errors.ts
packages/express/src/getAuth.ts
packages/express/src/index.ts
packages/express/src/requireAuth.ts
packages/express/src/types.ts
packages/express/src/utils.ts

This PR refactors both `clerkMiddleware` and `requireAuth` Express middlewares to simplify DX and reduce confusion when choosing between middlewares:
1. `clerkMiddleware`
Removed option to pass a handler. It does not do anything at all, which can be replaced by a one-liner from userland:
```ts
// Before
app.use(clerkMiddleware((req, res, next) => {
// req.auth here is undefined so it's not useful at all
}));
// After
app.use(clerkMiddleware());
app.use((req, res, next) => {
// do stuff
})
```
2. `requireAuth`
Is now using the same logic as `clerkMiddleware` (use `authenticateRequest` and attach `auth` to `request`), except it will redirect to `signInUrl` if unauthenticated instead of calling `next(new Error())`. So you can have `requireAuth` middleware without `clerkMiddleware`:
```ts
// …
```

chore(express): Refactor `requireAuth` and `clerkMiddleware` middlewares

---

.changeset/brave-plants-lick.md
packages/clerk-js/src/ui/components/SignIn/SignInFactorOnePasswordCard.tsx

Maintain focus on password input after error in sign in first factor.
https://github.com/user-attachments/assets/e57f501e-9053-4724-9753-6380b362624f
Fixes SDKI-664

chore(clerk-js): Preserve password input focus on error

---

.changeset/yellow-lobsters-smile.md
packages/backend/src/tokens/__tests__/authStatus.test.ts
packages/backend/src/tokens/authStatus.ts

Headers.set can throw a "Cannot convert argument to a ByteString" when trying to set/append a string containing unicode characters as headers can only accept ASCII chars in the range of [0-255]. Under certain cases, verifyToken can throw an error containing the unicode character that caused the error which then we would try to include in the debug header.
This would cause the *only current request* to fail so we are adding extra error handling to prevent this edge scenario.

fix(backend): Handle "Cannot convert argument to a ByteString" errors

---

.changeset/cold-mayflies-happen.md
packages/clerk-js/src/ui/components/UserProfile/UsernameForm.tsx

In this pr we are allowing single-character usernames in `<UserProfile />` validation

chore(clerk-js): Allow single-character usernames in `<UserProfile />` validation

---

.changeset/quiet-chicken-cover.md
packages/express/src/__tests__/clerkMiddleware.test.ts
packages/express/src/__tests__/requireAuth.test.ts
packages/express/src/authenticateRequest.ts
packages/express/src/types.ts

This PR enables the handshake flow by default. Typically, a backend SDK will be used alongside a Clerk frontend SDK, and we aim to provide seamless integration without requiring users to manually set `enableHandshake` to `true`. Even in cases where there's no frontend SDK, authorization will be handled via headers, in which handshake is not supported.
We will still keep this option in case user wants to disable adding the debug headers (e.g. `x-clerk-auth-status`) and to still support our [backend-only SDK guide](https://clerk.com/docs/references/sdk/backend-only) in which handshake is not supported.

chore(express): Set default `enableHandshake` option value to true

---

.changeset/three-nails-fetch.md
packages/clerk-js/src/core/clerk.ts
packages/clerk-js/src/ui/components/UserButton/__tests__/UserButton.test.tsx
packages/clerk-js/src/ui/components/UserButton/useMultisessionActions.tsx
packages/clerk-js/src/ui/utils/test/mockHelpers.ts

https://github.com/user-attachments/assets/66e41cbd-2059-4808-9ae8-5dc3ccc58796
Fixes SDKI-671

fix(clerk-js): Navigate to `/choose` when signing out during multi session

---

.changeset/hot-pants-change.md
packages/clerk-js/src/ui/hooks/useEnabledThirdPartyProviders.tsx

If FAPI returns a Web3 provider that is not yet known to our types and components, then we fail to render them. We fix that by filtering them out, as we do for OAuth

fix(clerk-js): Handle gracefully yet unknown to our components Web3 providers

---

.changeset/shy-sloths-laugh.md
integration/presets/envs.ts
integration/presets/longRunningApps.ts
integration/templates/next-app-router/src/app/layout.tsx
integration/templates/react-vite/src/client-id.tsx
integration/templates/react-vite/src/main.tsx
integration/tests/sign-out-smoke.test.ts
packages/clerk-js/src/core/__tests__/clerk.test.ts
packages/clerk-js/src/core/clerk.ts

We would like to keep around the `persistClient` flag under the `experimental` settings for a bit longer as an escape hatch in case folks encounter any weird behaviour.

feat(clerk-js): Enable persisted clients by default

---

.changeset/breezy-crabs-crash.md
packages/chrome-extension/src/__tests__/__snapshots__/exports.test.ts.snap
packages/clerk-js/src/core/clerk.ts
packages/nextjs/src/client-boundary/uiComponents.tsx
packages/nextjs/src/index.ts
packages/react/src/components/index.ts
packages/react/src/components/uiComponents.tsx
packages/react/src/isomorphicClerk.ts
packages/types/src/clerk.ts

Drop the experimental mounted variant of `UserVerification`.
Removes:
- `<__experimental_UserVerification/>`
- `__experimental_mountUserVerification()`
- `__experimental_unmountUserVerification()`

chore(nextjs,clerk-react,clerk-js): Drop the mounted variant of `UserVerification`

---

.changeset/purple-goats-applaud.md
packages/clerk-js/bundlewatch.config.json
packages/clerk-js/src/core/resources/Session.ts
packages/clerk-js/src/core/resources/__tests__/Session.test.ts
packages/clerk-js/src/ui/components/UserVerification/useUserVerificationSession.tsx
packages/react/src/hooks/__tests__/useAuth.test.ts
packages/shared/src/authorization.ts
packages/types/src/clerk.ts
packages/types/src/session.ts
packages/types/src/sessionVerification.ts

Rename `__experimental_assurance` to `__experimental_reverification`.
- Supported levels are now are `firstFactor`, `secondFactor`, `multiFactor`.
- Support maxAge is now replaced by maxAgeMinutes and afterMinutes depending on usage.
- Introduced `____experimental_SessionVerificationTypes` that abstracts away the level and maxAge
- Allowed values 'veryStrict' | 'strict' | 'moderate' | 'lax'

chore(clerk-js, clerk-react,types): Rename assurance to reverification

---

package-lock.json
packages/ui/package.json
packages/ui/src/common/password-field.tsx
packages/ui/src/common/router-link.tsx
packages/ui/src/components/sign-in/steps/start.tsx
packages/ui/src/components/sign-up/steps/continue.tsx
packages/ui/src/components/sign-up/steps/start.tsx
packages/ui/src/primitives/card.tsx

Implements `<RouterLink />` component to allow navigations without full page reloads when navigating between `SignIn`/`SignUp` flows.

feat(ui): Add `<RouterLink />` component

---

.changeset/heavy-bulldogs-wash.md
packages/clerk-js/src/ui/components/OrganizationProfile/InviteMembersForm.tsx
packages/clerk-js/src/ui/components/OrganizationProfile/__tests__/InviteMembersPage.test.tsx

Fixes issue where "Send invitation" button is getting disabled even tho there's a default role loaded: 
https://github.com/user-attachments/assets/fe18d474-5cf3-4396-94ec-a008db7a99cf
The issue relies on the fact that we're overriding the `field.value` property when rendering it, instead of passing it to the form controls state: 
https://github.com/user-attachments/assets/c3a6696c-2e62-40b8-8e55-bb346fb528d6

fix(clerk-js): Initialize default role with form controls

---

.changeset/late-kiwis-warn.md
package-lock.json
packages/elements/package.json

Building `@clerk/ui` no longer depends on `@clerk/react`

chore(elements): Align clerk dependencies

---

.changeset/young-llamas-prove.md
packages/nextjs/tsconfig.declarations.json

Noticed that `@clerk/nextjs` was building declaration files for files in `__tests__` directory. Adding this directory to the `exclude` in testing tsconfig.

fix(nextjs): do not build test file declarations

---

.changeset/shiny-files-smash.md
packages/localizations/src/de-DE.ts

The confirmation prompt under deletePage["confirm"] currently displays ‘Konto löschen’, while the placeholder and required input are ‘Account löschen’.
Given the importance of clarity in account deletion processes, especially in GDPR-compliant countries like Germany, this adjustment prevents any potential confusion or hindrance to users attempting to delete their account.”

fix(localizations): Update de-DE translation to be GDPR-compliant

---

.changeset/unlucky-steaks-protect.md
packages/types/src/clerk.ts
packages/ui/src/components/sign-in/sign-in.tsx
packages/ui/src/components/sign-up/sign-up.tsx
packages/ui/src/contexts/AppearanceContext.tsx
packages/ui/src/primitives/card.tsx
packages/ui/src/themes/full.ts
packages/ui/src/themes/layout.ts

This PR adds support for the `__experimental.appearance` prop which is distinct from the existing `appearance` prop. If the new `SignIn`/`SignUp` component is rendered with `__experimental.newComponents`, it will pull the appearance from `__experimental.appearance` instead of `appearance`. If the components are rendered directly (outside of `clerk-js` such as in Theme Builder) they will continue to read from `appearance`.
This PR also adds descriptors to the `Card.Logo` component since we want to target it in Dashboard.

feat(types,ui): Add support for `__experimental.appearance` prop

---

packages/clerk-js/global.d.ts
packages/clerk-js/src/global.d.ts
packages/clerk-js/src/ui/new/renderer.tsx
packages/clerk-js/webpack.config.js

This PR adds support for inserting the new UI stylesheet as the first stylesheet in the document. This is to allow user styles to take precedence over our own. For example:
```
// @clerk/ui/styles.css
.cl-button { display: flex; }
```
```
// app/style.css
.hidden { display: none; }
```
If the UI stylesheet appears _after_ the app stylesheet in the DOM, `cl-button` will override `hidden` given they have the same specificity. By _prepending_ our stylesheet, we allow our users' styles to take precedence.
To support this, I had to remove Webpack's experimental support for CSS which doesn't currently support emitting the URL of the stylesheet; it always wants to append it to the DOM.

feat(clerk-js): Add support for loading UI styles as first CSS stylesheet

---

.changeset/khaki-cycles-appear.md
packages/clerk-js/src/core/resources/SignIn.ts

There is a chance that as a user when you try to setup and use the Coinbase Wallet with an existing Passkey in order to authenticate, the initial generate signature request to be rejected. For this reason we retry the request once more in order for the flow to be able to be completed successfully.
https://github.com/user-attachments/assets/e8224c4c-6386-4706-a4d9-8b4c2fa157e7
https://github.com/user-attachments/assets/a1a196c3-5870-41a2-b660-344ff810e58d

fix(clerk-js): Handle gracefully Coinbase Wallet use of existing Passkey

---

packages/clerk-js/src/ui/new/renderer.tsx
packages/clerk-js/webpack.config.js

This PR updates the CJS and ESM builds of `clerk-js` to bundle imported CSS files instead of emitting a URL to the file. This is required since we don't have the capability to dynamically load anything on account of not knowing the public path (like we do in our browser bundles). This impacts consumers who directly consume the `clerk.js` and `clerk.mjs` bundles of `clerk-js`, which includes Chrome extensions (and possibly others).

fix(clerk-js): Bundle CSS into CJS and ESM bundles

---

.changeset/lemon-terms-begin.md
packages/clerk-js/src/ui/components/OrganizationSwitcher/OrganizationSwitcherPopover.tsx

Resolves ORGS-246
Replaces `OrganizationSwitcher` small gear icon action with a labeled button to make it less confusing to end-users.
Now:
Previously:

chore(clerk-js): Update `OrganizationSwitcher` popover action to include label

---

.changeset/neat-wasps-explain.md
README.md
packages/sdk-node/README.md
packages/sdk-node/src/index.ts

This PR adds an EOL notice for `@clerk/clerk-sdk-node` and provides a link for migrating to `@clerk/express`
Resolves ECO-209

chore(clerk-sdk-node): Add transition period notice and migration info

---

.changeset/eight-kids-attack.md
packages/backend/src/api/resources/OrganizationMembership.ts

This PR exposes the `permissions` field on the `OrganizationMembership` resource.

fix(backend): Expose permissions field for OrganizationMembership

---

.changeset/three-timers-sneeze.md
packages/elements/examples/nextjs/app/sign-up/[[...sign-up]]/page.tsx
packages/elements/src/internals/constants/index.ts
packages/elements/src/internals/machines/sign-up/router.machine.ts
packages/elements/src/internals/machines/sign-up/router.types.ts
packages/elements/src/react/sign-up/restricted-access.tsx
packages/elements/src/react/sign-up/restricted.tsx
packages/elements/src/react/sign-up/step.tsx

Adds support for "restricted" apps when users attempt to sign-up without a ticket.
```tsx
<SignUp.Step name='restricted'>
<h1>Restricted Access</h1>
<p>Access to this app is limited, and an invitation is required to sign up.</p>
</SignUp.Step>
```
Fixes SDKI-675

feat(elements): Add support for `restricted` mode

---

.changeset/blue-pumpkins-travel.md
packages/clerk-js/src/utils/__tests__/url.test.ts
packages/clerk-js/src/utils/url.ts

fix(clerk-js): Update isAllowedRedirectOrigin to handle malformed or protocol-relative URLs

---

.changeset/shy-peaches-grow.md
packages/clerk-js/src/core/resources/DisplayConfig.ts
packages/clerk-js/src/core/resources/SignUp.ts
packages/types/src/displayConfig.ts

- We want to be able to control when captcha is bypassed on a per-instance or per-provider level.
- We want to rollout these changes gradually to ensure that changes in bot detection logic have no negative impact in sing up conversions.
This PR introduces the `displayConfig.captchaOauthBypass` field to replace the hard-coded values in `clerk-js`. The bypassed strategies will now be controlled by FAPI instead. If for any reason FAPI needs to be rolled back, `clerk-js` will bypass captcha for google/ microsoft/ apple oauth as it does at the moment.

feat(types,clerk-js): Bypass captcha for providers dynamically provided in environment

---

.changeset/odd-squids-dress.md
packages/clerk-js/src/utils/captcha/turnstile.ts

This PR adds support for loading the Turnstile CAPTCHA script from the Cloudflare host. If the script fails to load from the Cloudflare URL, it falls back to a FAPI-proxied URL.

fix(clerk-js): Add support for loading Turnstile from Cloudflare host

---

.changeset/tender-badgers-rule.md
packages/elements/src/internals/machines/form/form.machine.ts
packages/elements/src/internals/machines/shared/shared.actions.ts
packages/elements/src/internals/machines/shared/shared.types.ts
packages/elements/src/internals/machines/sign-up/router.machine.ts
packages/elements/src/internals/machines/sign-up/start.machine.ts
packages/elements/src/internals/machines/sign-up/start.types.ts
packages/elements/src/react/sign-up/context/router.context.ts

Fixed a bug in the sign up flow where the sign up form was unable to accept additional requirements when initiated from a ticket.
fixes SDKI-697

fix(elements): Progressive sign up ticket flow

---

.changeset/nasty-melons-cross.md
packages/clerk-js/src/core/resources/SignUp.ts
packages/shared/src/error.ts

We only want to reload env and retry if the error thrown was related to captcha falling.

fix(clerk-js): Only retry oauth if captcha failed

---

.changeset/serious-moose-design.md
packages/clerk-js/src/utils/captcha/turnstile.ts

This PR adds the `?render=explicit` query param on the CF Turnstile script URL.
Currently, the script is working because the Turnstile script fallbacks to 'explicit' rendering when there is no `cf-turnstile` element in the DOM, and we use `clerk-captcha` and `clerk-invisible-captcha` for the DOM elements.
However, it's better to be explicit about the rendering strategy so that we can avoid accidental issues in the future.

fix(clerk-js): Add the render query param on the captcha script

---

integration/templates/tanstack-start/app.config.ts

`config.plugins` now expects an array instead of a function that returns an array. This was changed in [this PR to TanStack Start](https://github.com/TanStack/router/pull/2544/files).

fix(e2e): Use new config plugin type

---

.changeset/fluffy-goats-protect.md
packages/clerk-js/src/core/resources/Session.ts
packages/types/src/session.ts
packages/types/src/sessionVerification.ts

Drop `maxAgeMinutes` from `__experimental_startVerification`.
Drop types `__experimental_SessionVerificationConfig` and `__experimental_SessionVerificationMaxAgeMinutes`.

chore(clerk-js,types): Drop `maxAgeMinutes` from `__experimental_startVerification`

---

.changeset/violet-games-dream.md
packages/backend/src/api/resources/JSON.ts
packages/backend/src/api/resources/Verification.ts
packages/clerk-js/src/core/resources/SignIn.ts
packages/clerk-js/src/core/resources/SignUp.ts
packages/clerk-js/src/core/resources/Verification.ts
packages/clerk-js/src/ui/components/UserProfile/Web3Form.tsx
packages/clerk-js/src/utils/web3.ts
packages/types/src/json.ts
packages/types/src/verification.ts

In this commit we are updating our Web3 flows logic to use the new 'message' property of a Web3 verification, which follows the [EIP-4361 spec](https://eips.ethereum.org/EIPS/eip-4361#message-format), to sign a new request. This message format provides a better experience to the end user by let them know additional information for the application they are about to use

feat(clerk-js,types,backend): Use EIP-4361 message spec for Web3 wallets

---

.changeset/gorgeous-teachers-scream.md
package-lock.json
packages/express/src/__tests__/__snapshots__/exports.test.ts.snap
packages/express/src/index.ts

This can be useful to use directly for express users who want to go down to bare metal
For some users of the express SDK, they may want to directly use `authenticateRequest`, which is notably different from the backend SDK version since it's adapted to express' request wrapper. This makes that possible.

feat(express): Export `authenticateRequest`

---

.changeset/serious-moose-design.md
packages/clerk-js/src/utils/captcha/turnstile.ts

fix(clerk-js): Add the render query param on the captcha script (#4332) [Core 1 backport]

---

.changeset/forty-laws-swim.md
packages/shared/src/loadScript.ts

It's impossible to inspect the error that caused `on error` or the `error` event to be fired, so I intentionally left the initial and subsequent delays short.
This is a "best effort" strategy to retry network errors while still falling back to loading the turnstile script through our proxy if loading fails due to CSP, as we cannot reliably detect that a CSP error occurred.
This change is expected to reduce the "Clerk: Failed to load" errors as well.

fix(shared): Retry with exponential backoff if loadScript fails

---

.changeset/fair-flies-compare.md
packages/backend/src/tokens/request.ts

The `console.error` appears on the server logs of our users, and a refresh token flow can fail in a common valid scenario.

fix(backend): Remove console error message from refresh token flow failures

---

.changeset/fair-avocados-tap.md
packages/clerk-js/src/ui/components/UserVerification/index.tsx
packages/clerk-js/src/ui/components/UserVerification/useUserVerificationSession.tsx
packages/clerk-js/src/ui/hooks/useFetch.ts

Invalidate Session Verification on component unmount

chore(clerk-js): Invalidate Session Verification when UserVerification unmounts

---

packages/nextjs/src/server/__tests__/clerkMiddleware.test.ts
packages/nextjs/src/server/clerkMiddleware.ts
packages/upgrade/src/codemods/__tests__/__fixtures__/transform-async-request.fixtures.js

Converts `auth` in `clerkMiddleware` to async. The API now becomes:
```ts
clerkMiddleware(async auth => {
const { redirectToSignIn } = await auth();
})
```

fix(nextjs): Convert middleware auth to async

---

.changeset/fluffy-eyes-arrive.md
packages/nextjs/src/server/nextFetcher.ts
packages/nextjs/src/server/protect.ts

In next 15, the `next-url` header exists while in dev mode, but it's missing in the production build so we need to update our fallback detection as well.
Also `__fetch.__nextGetStaticStore().getStore().pagePath` has been replaced with `__fetch.__nextGetStaticStore().getStore().page`.

fix(nextjs): Improve page detection for Next 15

---

.changeset/wild-guests-occur.md
packages/upgrade/src/components/Codemod.js
packages/upgrade/src/components/SDKWorkflow.js

Improving the output of `clerk-upgrade` CLI command to match the styling of core-1 to core-2 migration

feat(upgrade): Improve CLI output

---

.changeset/light-cooks-wink.md
package-lock.json
packages/ui/package.json

Replaces file-based ranges in `@clerk/ui` for internal packages with our pinned versions we use in other packages.
Fixes https://github.com/clerk/javascript/issues/4395

fix(ui): Use regular version ranges for internal packages

---

.changeset/khaki-weeks-give.md
package-lock.json
packages/clerk-js/package.json

This PR moves `@clerk/ui` to `devDependencies`. This is because the `ui` package is bundled by Webpack, and does not need to be separately installed by the package manager when a user installs `@clerk/clerk-js`.

fix(clerk-js): Move ui package to devDependencies

---

.changeset/two-wasps-dance.md
packages/clerk-js/src/ui/components/UserProfile/Web3Form.tsx

If Web3 wallet already claimed preview error on UserProfile.

fix(ui): If Web3 wallet already claimed preview error on <UserProfile />

---

.changeset/selfish-pianos-push.md
packages/nextjs/src/app-router/server/auth.ts

During #4366 we typed the arguments of `protect()` for page/route/action as `any`

fix(nextjs): Include protect types in `auth`

---

.changeset/thirty-jobs-leave.md
packages/localizations/src/fr-FR.ts

AFTER
https://github.com/user-attachments/assets/1e2f1d00-49cc-4242-bf1e-ad756eabe92b
Fixes issue where delete account button was not becoming active when the field value matched the expected string value.

fix(localizations): Ensure confirm delete account text aligns with prompt

---

.changeset/few-swans-cough.md
packages/clerk-js/src/ui/components/OrganizationSwitcher/OrganizationSwitcher.tsx
packages/clerk-js/src/ui/components/OrganizationSwitcher/OrganizationSwitcherPopover.tsx
packages/clerk-js/src/ui/components/UserButton/UserButton.tsx
packages/clerk-js/src/ui/components/UserButton/UserButtonPopover.tsx
packages/types/src/clerk.ts

The new callback will fire upon "closing" the pop-over
Example usage 
```tsx
const [open, setOpen] = useState(false)
{open && <OrganizationSwitcher.Outlet asStandalone={setOpen} />}
```

feat(clerk-js, types): `asStandalone` accepts a callback

---

.github/workflows/ci.yml
integration/cleanup/cleanup.setup.ts
turbo.json

Fixes caching for integration test tasks, all task dependencies incorrectly contained `^`, which means the task should depend on its package's dependencies running the tasks specified with `^`. This was effectively a no-op when used for a root task with package-specific tasks in its dependencies. This should fix integration test caching 🤞
Also fixes an issue with the integration test cleanup script where not all instances were being cleaned up.

chore(repo): Test task cache, instance cleanup

---

.changeset/silly-moose-tease.md
packages/tanstack-start/src/server/middlewareHandler.ts

This PR fixes bug where the initialisation of Clerk overwrites the context, by merging the original/existing context with the `clerkInitialState`.

fix(tanstack-start): Merge router context instead of updating

---

.changeset/giant-roses-heal.md
packages/clerk-js/src/ui/elements/FieldControl.tsx
packages/clerk-js/src/ui/elements/LegalConsentCheckbox.tsx

Improve checkbox label alignment.
| ![Screenshot 2024-10-29 at 4 02 44 PM](https://github.com/user-attachments/assets/b3710e17-e7b3-4cab-a17d-d450b8ef6dd2) | ![Screenshot 2024-10-29 at 3 58 57 PM](https://github.com/user-attachments/assets/53c9d2f5-dbd9-432d-862e-b7409490e644) | 
| ![Screenshot 2024-10-29 at 4 03 47 PM](https://github.com/user-attachments/assets/9aba8e55-9a4e-4bde-8ed2-0b6a09973884) | ![Screenshot 2024-10-29 at 4 04 00 PM](https://github.com/user-attachments/assets/c836439a-e7cd-488f-842b-1b8f2d34f12e) |

fix(clerk-js): Improve checkbox label alignment

---

.github/workflows/lock-threads.yml

We've been getting a lot of noise from locked PRs the last couple of weeks and it doesn't really add any value since it's so rare that people comment on old PRs. So this PR removes the functionality to lock old PRs (it'll still lock issues).

chore(repo): Do not lock old PRs

---

.changeset/mighty-ears-cough.md
packages/tanstack-start/src/server/middlewareHandler.ts

This PR brings back the `router.load` after the context is updated in the middlewareHandler

fix(tanstack-start): Load router after updating context

---

.changeset/beige-bananas-look.md
packages/react/src/components/SignOutButton.tsx
packages/react/src/components/__tests__/SignOutButton.test.tsx

Our [docs](https://clerk.com/docs/components/unstyled/sign-out-button#properties) indicate that the `<SignOutButton />` component accepts a [`signOutOptions`](https://clerk.com/docs/components/unstyled/sign-out-button#sign-out-options) object, which allows you to customize behavior such as [signing out of a specific session](https://clerk.com/docs/components/unstyled/sign-out-button#sign-out-of-a-specific-session). We already accept the prop, but we don't use it in the component at all. This PR fixes that.

fix(clerk-react): Make `signOutOptions` prop functional

---

.github/workflows/ci.yml
turbo.json

Currently, args pass to turbo tasks are (understandably) included in the hash, and ultimately the cache key. As it relates to e2e tests, we pass a `--project` argument to the turbo task run, along with `--only`. What this means is turbo doesn't consider the task's dependencies when determining if the task has been cached or not.
This is problematic for us, as only the `integration/` directory is included in the inputs. I've changed the command to not pass the `--project` arg, as it only has the `chrome` value today, and is otherwise unused. I also removed the `--only` flag. This should allow turbo to only re-run the integration tests if dependent packages have changed.

fix(repo): Ensure turbo cache is used properly for e2e tests

---

.changeset/purple-eels-fix.md
packages/nextjs/src/server/errors.ts
packages/upgrade/src/components/SDKWorkflow.js

Fixes some docs URLs that were linking to 404 pages due to missing `/reference` paths.

fix(upgrade,nextjs): Update broken Clerk documentation references

---

.changeset/wild-cycles-cough.md
packages/shared/package.json

fix(shared): Fix package.json issue with shared package

---

.changeset/friendly-sloths-travel.md
packages/nextjs/src/app-router/client/ClerkProvider.tsx
packages/nextjs/src/pages/ClerkProvider.tsx

Fixes issue in `<ClerkProvider />` where window is undefined.
https://clerkinc.slack.com/archives/C05GH6N5LLS/p1730730591481319?thread_ts=1730509835.841509&cid=C05GH6N5LLS

fix(nextjs): Ensure window is defined within `<ClerkProvider />`

---

.changeset/fair-dots-invite.md
packages/nextjs/src/app-router/server-actions.ts

Ensure a cookie doesn't get set when the cache invalidation server action is called.

fix(nextjs): Do not set cookie during cache invalidation

---

.changeset/chilled-crabs-stare.md
packages/clerk-js/src/utils/__tests__/redirectUrls.test.ts
packages/clerk-js/src/utils/__tests__/url.test.ts
packages/clerk-js/src/utils/redirectUrls.ts
packages/clerk-js/src/utils/url.ts

fix(clerk-js): Directory traversal relative URL detection

---

.changeset/nine-pets-rhyme.md
packages/clerk-js/src/core/clerk.ts

We need to re-init the options during the updateProps() call  in order to keep the options passed to ClerkProvider in sync with the state of clerk-js. If we don't init the options here again, the following scenario is possible:
1. User renders <ClerkProvider propA={undefined} propB={1} />
2. clerk-js initializes propA with a default value
3. The customer update propB independently of propA and window.Clerk.updateProps is called
4. If we don't merge the new props with the current options, propA will be reset to undefined

fix(clerk-js): Init options on updateProps

---

.changeset/funny-pens-move.md
.changeset/late-camels-talk.md
package-lock.json
packages/clerk-js/src/core/clerk.ts
packages/clerk-js/src/core/resources/Passkey.ts
packages/clerk-js/src/core/resources/SignIn.ts
packages/clerk-js/src/utils/passkeys.ts
packages/expo-passkeys/README.md
packages/expo-passkeys/example/App.tsx
packages/expo-passkeys/example/package-lock.json
packages/expo-passkeys/example/package.json
packages/expo-passkeys/package.json
packages/expo/package.json
packages/expo/passkeys/package.json
packages/expo/src/passkeys/index.ts
packages/expo/src/provider/ClerkProvider.tsx
packages/expo/src/provider/singleton/createClerkInstance.ts
packages/expo/src/provider/singleton/types.ts
packages/shared/src/error.ts
packages/types/src/passkey.ts

🔐  This PR introduces passkey support for Expo iOS, Android, and Web.  🚀
To enable passkeys in your Expo project, update your `ClerkProvider` as follows:
```tsx
import { ClerkProvider } from '@clerk/clerk-expo';
import { passkeys } from '@clerk/clerk-expo/passkeys';
<ClerkProvider __experimental__passkeys={passkeys}>
{/* Your app here */}
```
```tsx
const { user } = useUser();
const handleCreatePasskey = async () => {
if (!user) return;
try {
return await user.createPasskey();
} catch (e: any) {
// handle error
}
};
```
```tsx
const { signIn, setActive } = useSignIn();
const handlePasskeySignIn = async () => {
try {
const signInResponse = await signIn.authenticateWithPasskey();
await setActive({ session: signInResponse.createdSessionId });
} catch (err: any) {
// handle …
```

feat(clerk-expo): Support expo passkeys

---

packages/clerk-js/rspack.config.js

The bundlers produced are already different so we might as well benefit from easier debugging straight in the browser console :)

chore(clerk-js): Use esnext as the target for dev builds

---

.changeset/eleven-doors-shop.md
packages/expo-passkeys/turbo.json

Correcting the `output` of `@clerk/expo-passkeys` build task to include the `build` dir

fix(expo-passkeys): Correct turborepo outputs

---

.changeset/itchy-icons-destroy.md
packages/astro/src/integration/create-integration.ts
packages/astro/src/internal/swap-document.ts

This PR fixes an issue where custom client-side routing (using History API's pushState) triggers unexpected full page reloads due to conflicts with Astro's internal [`popstate` event handlers](https://github.com/withastro/astro/blob/e10b03e88c22592fbb42d7245b65c4f486ab736d/packages/astro/src/transitions/router.ts#L574)
Resolves SDK-1976

fix(astro): Avoid importing transition functions when View Transitions is disabled

---

.changeset/spotty-books-tie.md
packages/clerk-js/src/core/resources/DisplayConfig.ts
packages/types/src/displayConfig.ts

This pr adds afterJoinWaitlistUrl to DisplayConfig resource

chore(clerk-js,types): Add afterJoinWaitlistUrl to DisplayConfig resource

---

.changeset/rich-badgers-pump.md
packages/elements/examples/nextjs/app/sign-in/[[...sign-in]]/page.tsx
packages/elements/src/internals/machines/third-party/third-party.actors.ts
packages/elements/src/react/sign-in/captcha.tsx
packages/elements/src/react/sign-in/sso-callback.tsx
packages/elements/src/react/sign-in/step.tsx

Introduces support for `<SignIn.Captcha>` as well as `<SignIn.Step name='sso-callback'>`. This allows rendering of the CAPTCHA widget when a sign in flow is transferred to a sign up flow.
Also fixes a bug with the SSO callback where a successful auth would navigate to the incorrect URL. This was due to a recent change that switched to passing a URL directly to `setActive()`, instead of `beforeEmit`.

feat(elements): Support SignIn.Captcha and sso-callback step

---

.changeset/spotty-pans-give.md
packages/clerk-js/src/ui/components/Waitlist/WaitlistForm.tsx
packages/clerk-js/src/ui/contexts/components/Waitlist.ts
packages/types/src/clerk.ts

In this pr we're replacing the `redirectUrl` with `afterJoinWaitlistUrl` in `<Waitlist />` component
We can safely replace because no one using the `<Waitlist />` component yet

refactor(clerk-js,types): Replace redirectUrl with afterJoinWaitlistUrl in `<Waitlist />` component

---

.github/workflows/ci.yml

Updates our CI config to run all jobs in parallel. This should improve iteration speeds and reveal test failures faster 🤞. We'll explore additional cost optimizations that don't compromise on feedback speed.

feat(repo): Run all CI jobs in parallel

---

integration/playwright.config.ts
integration/testUtils/appPageObject.ts

This PR increases our `retries`, `maxFailures`, and `timeout` in CI in an effort to combat some of our flaky tests.
The hypothesis is that our runners are simply being overwhelmed during more complicated tests like sessions, which runs multiple applications and a proxy server. These increases are intended to suss out whether we might see better pass rates if we throw more hardware at the problem.

chore(repo): Increase timeouts and retries in CI

---

.changeset/new-forks-flash.md
packages/clerk-js/src/ui/components/Waitlist/WaitlistForm.tsx

In this pr we're displaying the logo in the `<Waitlist />` chore

chore(clerk-js): Display logo in `<Waitlist />` component

---

.github/workflows/pr-title-linter.yml

Specifying `pnpm` version in the PR title linter action. Seeing the following error in CI:
```
Error: No pnpm version is specified.
Please specify it by one of the following ways:
- in the GitHub Action config with the key "version"
- in the package.json with the key "packageManager"
```

fix(repo): PR title linter

---

.changeset/friendly-melons-argue.md
packages/react/src/components/SignInButton.tsx
packages/react/src/types.ts

Follow up to https://github.com/clerk/javascript/pull/4567
```tsx
<SignInButton
initialValues={{
emailAddress: "example@clerk.dev",
}}
/>
```

feat(clerk-react): Expose `initialValues` within `<SignInButton />`

---

.changeset/spotty-eagles-applaud.md
packages/nextjs/src/client-boundary/PromisifiedAuthProvider.tsx

Related: SDKI-735
Removing the following error in development:
```
Clerk: useAuth() called in static mode, wrap this component in <ClerkProvider dynamic> to make auth data available during server-side rendering.
```

feat(nextjs): Remove useAuth() error in DEV

---

packages/clerk-js/src/core/fraudProtection.ts
packages/clerk-js/src/core/resources/Session.ts

Block all /token requests until the captcha challenge is solved. 
For getToken():
- this ensures that if a getToken() triggers fraud protection, all subsequent getToken() invocations will wait for the captcha challenge to be complete AND the initial getToken() to resolve
- if multiple getToken() invocation are queued, they will all resolve at the same time using the value of the first getToken. Only a single request will fire because of the in-memory token cache
For getToken({ skipCache: true }):
- similar to above, but multiple requests will be fired once the first getTOken() resolves
- we will optimize this behavior if needed

fix(clerk-js): Block /tokens requests until fraud detection completes

---

.changeset/fifty-cameras-tease.md
packages/expo-passkeys/.eslintrc.js
packages/expo-passkeys/src/utils.ts
packages/expo/package.json
pnpm-lock.yaml

In this commit, we are importing the `Buffer` from `buffer` instead of `node:buffer`.
We are also moving the `@clerk/expo-passkeys` back to `devDependencies` at `@clerk/clerk-expo`

chore(clerk-expo-passkeys): fix breaking changes

---

.changeset/shaggy-donuts-cry.md
packages/dev-cli/src/commands/setup.js

Currently, we're only checking for a `next.config` file to determine if Next.js is being used. We can make this more robust by checking for a `next` dependency. This fixes an issue where your local dev keys would not be properly added to a Next.js project.

fix(dev-cli): Fix `clerk-dev` Next.js detection

---

.changeset/clever-bats-own.md
.changeset/empty-fans-attack.md
packages/clerk-js/sandbox/app.js
packages/clerk-js/sandbox/template.html
packages/clerk-js/src/core/clerk.ts
packages/clerk-js/src/ui/Components.tsx
packages/clerk-js/src/ui/components/AccountlessPrompt/index.tsx
packages/clerk-js/src/ui/lazyModules/components.ts
packages/types/src/clerk.ts

> [!WARNING]
> This code will also reach our customers, but the use of `__internal_claimAccountlessKeysUrl` and the fact that this prop will not be documented should prevent them from accidentally using it.
> [!NOTE]
> This will not be the final design of the prompt

feat(clerk-js): Introduce internal Accountless UI prompt in sandbox

---

.changeset/early-games-taste.md
packages/clerk-js/src/utils/captcha/retrieveCaptchaInfo.ts

Enables captcha for development instances.
Previously captcha was only usable on production instances and with recent changes, we now allow development instances running on localhost or other domains to also use captcha for parity with production.
We now rely on the value in the environment to determine if captcha is enabled or not (`userSettings.signUp.captcha_enabled`). For current development instances, it is disabled by default so this will be a no-op.

fix(clerk-js): Enable captcha for development instances

---

.changeset/many-bees-mate.md
packages/shared/src/authorization-errors.ts
packages/shared/src/authorization.ts
packages/shared/src/react/hooks/useReverification.ts

chore(shared): Gracefully handle missing reverification error metadata

---

.changeset/chilled-zoos-appear.md
packages/astro/src/server/clerk-middleware.ts

fix(astro): ignore prerendered pages in middleware

---

.github/actions/init-blacksmith/action.yml
.github/actions/init/action.yml

The Cypress binary is being needlessly installed on every CI setup phase, however we're not using it. As such, we can cut out a few seconds out of each CI run.
~4 seconds on each runner = ~1m48s in total billable time.
```
.../cypress@13.9.0/node_modules/cypress postinstall: Note: Skipping binary installation: Environment variable CYPRESS_INSTALL_BINARY = 0.
.../cypress@13.9.0/node_modules/cypress postinstall: Done
```
Fixes: ECO-251

chore(repo): Disable Cypress binary installation on CI

---

.changeset/empty-roses-peel.md
packages/astro/src/astro-components/index.ts
packages/astro/src/astro-components/interactive/InternalUIComponentRenderer.astro
packages/astro/src/astro-components/interactive/Waitlist.astro
packages/astro/src/internal/mount-clerk-astro-js-components.ts
packages/astro/src/react/uiComponents.tsx

In this pr we're introducing `<Waitlist />` component for astro

feat(astro): Introduce `<Waitlist />` component

---

.changeset/mean-apples-approve.md
packages/clerk-js/src/ui/components/UserProfile/ActiveDevicesSection.tsx
packages/clerk-js/src/ui/components/UserProfile/__tests__/SecurityPage.test.tsx

fix(clerk-js): Persist "this" when revoking a session, from UserProfile

---

.changeset/chilly-kids-cry.md
.changeset/early-mice-marry.md
packages/nextjs/src/client-boundary/hooks.ts
packages/nextjs/src/errors.ts
packages/react/src/errors.ts

chore(clerk-react,nextjs): Re-export `isClerkRuntimeError`

---

.changeset/bright-carpets-beam.md
packages/clerk-js/src/utils/memoizeStateListenerCallback.ts

Fixes a bug where an updated Session resource is not emitted from Clerk if only the user data has changed. This causes an issue for our React hooks where the internal state is not updated by Clerk even though the underlying Clerk data has changed, so the return value of `useSession()` can drift from `Clerk.session`.

fix(clerk-js): Ensure updated session is emitted on user change

---

.changeset/clever-cougars-argue.md
.changeset/famous-experts-begin.md
.changeset/short-mails-wash.md
packages/backend/src/constants.ts
packages/clerk-js/src/core/clerk.ts
packages/clerk-js/src/core/constants.ts
packages/clerk-js/src/core/resources/SignIn.ts
packages/clerk-js/src/core/resources/UserSettings.ts
packages/clerk-js/src/ui/components/SignIn/SignInStart.tsx
packages/clerk-js/src/ui/components/SignIn/__tests__/SignInStart.test.tsx
packages/clerk-js/src/ui/components/UserProfile/AccountPage.tsx
packages/clerk-js/src/ui/components/UserProfile/__tests__/AccountPage.test.tsx
packages/clerk-js/src/ui/components/UserProfile/__tests__/EnterpriseAccountsSection.test.tsx
packages/clerk-js/src/ui/components/UserProfile/__tests__/PasswordSection.test.tsx
packages/clerk-js/src/ui/components/UserProfile/__tests__/UserProfileSection.test.tsx
packages/clerk-js/src/ui/utils/test/fixtureHelpers.ts
packages/clerk-js/src/ui/utils/test/fixtures.ts
packages/clerk-js/src/utils/__tests__/completeSignUpFlow.test.ts
packages/clerk-js/src/utils/completeSignUpFlow.ts
packages/types/src/factors.ts
packages/types/src/redirects.ts
packages/types/src/signIn.ts
packages/types/src/signUp.ts
packages/types/src/strategies.ts
packages/types/src/userSettings.ts

This PR adds support for the new `enterprise_sso` strategy for signing in and signing up. 
This strategy supersedes SAML to provide a single strategy as the entry point for Enterprise Single Sign On regardless of the underlying protocol used to authenticate the user. For now there are two new types of connections that are supported in addition to SAML, Custom OAuth and EASIE (multi-tenant OAuth).
This new strategy will is available from API version `2024-10-01` and after because the way the API responds for Sign In's with an email address that matches a **SAML connection** changes.
From this version and onwards the API will respond with a status of `needs_first_factor`, the only strategy that will be included in supported first factors is `enterprise_sso` and the email address that …

feat(types,clerkjs,backend): Add support for enterprise_sso strategy 

---

.changeset/sharp-crabs-wave.md
packages/backend/src/api/endpoints/OrganizationApi.ts
packages/backend/src/api/resources/JSON.ts
packages/backend/src/api/resources/Organization.ts

Resolves ORGS-144, ORGS-392
As part of SSO per org (https://github.com/clerk/clerk_go/pull/7782), we've updated BAPI to allow creating organizations without an owner therefore turning `createdBy` from required to optional. This unblocks B2B customers to create empty organizations as part of onboarding. 
Docs PR: https://github.com/clerk/clerk-docs/pull/1754
Proposing this a minor version update, although not a breaking change [according to our definitions](https://clerk.com/docs/backend-requests/versioning/overview#what-constitutes-a-breaking-change), some customers might be relying on the fact that organizations always have an owner.

chore(backend): Allow to create organizations without initial owner

---

.changeset/tame-lamps-rule.md
packages/astro/src/server/clerk-middleware.ts

This PR is a follow up to #4640 which ignores prerendered routes in Clerk Astro middleware.
The v4 version of Astro uses [`_isPrerendered`](https://github.com/withastro/astro/blob/6eac6ba7331c3af7c2b704dc15a133748a2fd18b/packages/astro/src/core/render-context.ts#L248) property while v5 uses [`isPrerendered`](https://github.com/withastro/astro/blob/84ce4be5227cf71ac3f7c82c90718625fe58b1f6/packages/astro/src/core/render-context.ts#L310).

chore(astro): Add backwards compatibility for ignoring prerendered routes in Astro middleware

---

.changeset/small-buckets-peel.md
packages/shared/src/react/hooks/useReverification.ts

While this could be considered breaking, it is not since FAPI requests are not part of the Public Beta yet.

fix(shared): Use `session_reverification_required` as api error code

---

.changeset/dull-cooks-fry.md
packages/clerk-js/src/core/clerk.ts
packages/clerk-js/src/core/resources/SignIn.ts
packages/clerk-js/src/core/resources/SignUp.ts
packages/clerk-js/src/ui/common/constants.ts
packages/clerk-js/src/utils/injectedWeb3Providers.ts
packages/clerk-js/src/utils/web3.ts
packages/elements/src/internals/machines/sign-in/start.machine.ts
packages/elements/src/internals/machines/sign-in/verification.machine.ts
packages/elements/src/internals/machines/sign-up/start.machine.ts
packages/elements/src/react/hooks/use-third-party-provider.hook.ts
packages/elements/src/react/utils/map-scope-to-strategy.ts
packages/react/src/isomorphicClerk.ts
packages/types/src/clerk.ts
packages/types/src/signIn.ts
packages/types/src/signUp.ts
packages/types/src/web3.ts

We add support for a new Web3 provider and Web3 wallet, OKX Wallet, as an authentication strategy
https://github.com/user-attachments/assets/79312aa6-6e53-4c17-ba43-702c47a42171

feat(clerk-js,elements,react,types): Support OKW Wallet Web3 provider and authentication strategy

---

.changeset/four-hats-allow.md
packages/remix/src/client/index.ts

exports from the "enhanced" UserProfile and OrganizationProfile where ignored, instead the one from `@clerk/clerk-react` were exported until now.

feat(remix): Automatically use dynamic path for OrganizationProfile and UserProfile

---

.changeset/blue-teachers-remember.md
packages/clerk-js/src/core/__tests__/clerk.test.ts
packages/clerk-js/src/core/clerk.ts
packages/clerk-js/src/utils/windowNavigate.ts
packages/types/src/clerk.ts

Introduce a new Clerk option, `allowedRedirectProtocols` that allows users to specify custom protocols to be allowed as part of user-provided redirect URLs. This is necessary for cases where deep-linking is used, in an Electron app for example.
As part of this, I've removed the protocol check from `windowNavigate`. This is an internal method that is used in only a few places, none of which should be accepting arbitrary, user-provided URLs. I've also added a JSDoc comment indicating `windowNavigate` should never be used when accepting user-provided URLs.
fixes SDKI-782
Closes: https://github.com/clerk/javascript/issues/4667

feat(clerk-js): Add allowedRedirectProtocols

---

packages/clerk-js/src/ui/common/redirects.ts
packages/clerk-js/src/ui/components/SignIn/SignIn.tsx
packages/clerk-js/src/ui/components/SignIn/SignInStart.tsx
packages/clerk-js/src/ui/components/SignUp/SignUpStart.tsx
packages/clerk-js/src/ui/contexts/components/SignIn.ts
packages/types/src/clerk.ts

chore(clerk-js,types): Add experimental `SignInCombinedProps` option

---

.changeset/ten-berries-march.md
packages/expo/src/web/uiComponents.tsx

In this pr we're introducing `<Waitlist />` component for `@clerk/clerk-expo` (Web only)

feat(clerk-expo): Introduce <Waitlist /> component

---

.changeset/hungry-bugs-repeat.md
packages/nextjs/package.json
packages/nextjs/src/app-router/server-actions.ts
packages/nextjs/src/app-router/server/ClerkProvider.tsx
packages/nextjs/src/app-router/server/utils.ts
pnpm-lock.yaml

The current build of `ezheaders` is causing issues in downstream projects with `vitest` . Removing the package for now.

feat(nextjs): No ezheaders

---

.changeset/lucky-shrimps-switch.md
packages/clerk-js/src/ui/components/UserProfile/EmailForm.tsx
packages/clerk-js/src/ui/components/UserProfile/UsernameForm.tsx

Resolves SDK-1999
Stale values were sent to the FAPI methods on `useReverification` callback. This PR fixes the issue by passing form field values as arguments on the form handler, instead of accessing the state reference.
https://github.com/user-attachments/assets/46c1dc90-e0a1-4841-871e-e20b0eadd760
Refer to the following logs (first happens within the component, and second within the FAPI `createEmailAddress` closure)

fix(clerk-js): Do not send stale field value when creating email address and username

---

.changeset/four-beans-argue.md
integration/templates/vue-vite/src/components/CustomUserButton.vue
integration/templates/vue-vite/src/router.ts
integration/templates/vue-vite/src/views/custom-pages/OrganizationProfile.vue
integration/templates/vue-vite/src/views/custom-pages/UserProfile.vue
integration/tests/vue/components.test.ts
packages/vue/src/components/uiComponents.ts
packages/vue/src/errors/messages.ts
packages/vue/src/keys.ts
packages/vue/src/types.ts
packages/vue/src/utils/useCustomElementPortal.ts
packages/vue/src/utils/useCustomPages.ts

This PR adds support for [custom pages](https://clerk.com/docs/customization/user-profile) to the `<UserProfile />` and `<OrganizationProfile />` components of the Vue SDK.
Example usage:
```html
<script setup>
import { UserProfile } from '@clerk/vue' 
</script>
<UserProfile path="/user-profile" routing="path">
<UserProfile.Page label="Custom Page" url="custom-page">
<template #labelIcon>
<div>Icon</div>
</template>
<div>
<h1>Custom Terms Page</h1>
<p>This is the custom terms page</p>
</div>
</UserProfile.Page>
<UserProfile.Link label="Homepage" url="/">
<template #labelIcon>
<div>Icon</div>
</template>
</UserProfile.Link>
</UserProfile>
```
Also, unlike the React counterpart where we [loop over the `children` prop](https://github.com/clerk/javascript/blob/20d857188d3c66aaf70e4303f2fc451c7 …

chore(vue): Add custom pages and links

---

.changeset/curvy-sloths-dress.md
.changeset/honest-news-peel.md
.changeset/quiet-timers-mate.md
packages/clerk-js/src/ui/common/constants.ts
packages/clerk-js/src/ui/hooks/useEnabledThirdPartyProviders.tsx
packages/elements/src/utils/third-party-strategies.ts
packages/shared/package.json
packages/shared/src/oauth.ts
packages/shared/src/web3.ts
packages/types/src/web3.ts
packages/ui/src/descriptors.ts

This PR deprecate the runtime utilities exported from `@clerk/types` and moves only the used ones from `@clerk/shared`.

chore(shared,types): Move constants from types to shared

---

.changeset/clean-rivers-sleep.md
packages/clerk-js/src/ui/components/SignUp/SignUpContinue.tsx
packages/clerk-js/src/ui/components/SignUp/__tests__/SignUpContinue.test.tsx

Fixes an issue during sign-up flow where a user lands on the continue step, and proceeds successfully through the sign-up process and gets redirected to AP sign-up due to `signUp.id` being undefined.
BEFORE:
https://github.com/user-attachments/assets/3e18db33-6c23-41fe-bfbb-d9d05b55272e
AFTER:
https://github.com/user-attachments/assets/a87c5140-d585-4431-9c11-88b18e8d662f
Fixes SDKI-785

fix(clerk-js): Move signup id check into an effect within continue step

---

.changeset/young-lemons-marry.md
packages/localizations/src/ru-RU.ts

- `organizationSwitcher.action__manageOrganization` is set to `"Настройки"` because that is the common name and also the previous text was too long
- `organizationSwitcher.personalWorkspace` is set to `"Личный профиль"` because that is the common name and shorter
- fixed typo in  `organizationProfile.navbar.members`

fix(localizations): Update translations and fix typos in `ru-RU`

---

.changeset/fuzzy-carrots-push.md
packages/localizations/package.json
packages/localizations/src/en-GB.ts
packages/localizations/src/index.ts

Replaces a couple of "Americanisms" with their British versions:
- authorize with authorise
- organization with organisation

feat(localization): Add en-GB

---

.changeset/red-rice-attend.md
packages/backend/src/api/endpoints/PhoneNumberApi.ts

The `reserved_for_second_factor` property is currently missing in `CreatePhoneNumberParams` and in `UpdatePhoneNumberParams`, the Typescript types for the `POST /phone_numbers` and `PATCH /phone_numbers/{id}` backend API bodies.

fix(backend): Add missing `reservedForSecondFactor` property to `PhoneNumberAPI` types

---

.changeset/tiny-brooms-learn.md
packages/clerk-js/bundlewatch.config.json
packages/clerk-js/src/ui/customizables/elementDescriptors.ts
packages/clerk-js/src/ui/elements/SocialButtons.tsx
packages/types/src/appearance.ts

I noticed in https://github.com/clerk/clerk-docs/pull/1777 that we're documenting hiding the social buttons in certain situations. Currently hiding social buttons results in extra space between rendered in its place since the parent wrapping div is not being hidden as there is not descriptor on the element, which results in the gap showing between the wrapping div and the following elements. This PR introduces a descriptor to hide the social buttons wrapping div.

feat(clerk-js,types): Add `socialButtonsRoot` descriptor

---

.changeset/lemon-news-agree.md
.github/workflows/ci.yml
integration/templates/react-router-node/app/routes/protected.tsx
integration/tests/react-router/basic.test.ts
packages/react-router/src/client/ReactRouterClerkProvider.tsx
packages/react-router/src/client/types.ts
packages/react-router/src/ssr/loadOptions.ts
packages/react-router/src/ssr/types.ts
packages/react-router/src/utils/env.ts
packages/react-router/src/utils/errors.ts

- Add and activate E2E tests for React Router SDK
- Add some JSDoc comments here and there
- Allow `VITE_` prefixed env vars for the new redirect URL options

fix(react-router): Add E2E tests & improve redirect URL env var loading

---

.changeset/lemon-planes-dress.md
packages/react/src/components/controlComponents.tsx
packages/react/src/contexts/ClerkContextProvider.tsx
packages/react/src/contexts/ClerkProvider.tsx
packages/react/src/utils/useCustomElementPortal.tsx

This PR removes explicit `JSX.Element` return type annotations in favor of inferred return types, which will be `React.JSX.Element`. This should improve compatibility with React 19's types, which removed the global `JSX` namespace.

fix(clerk-react): Infer React.JSX.Element instead of explicit JSX.Element

---

.changeset/slow-cars-worry.md
packages/clerk-js/src/core/resources/AuthConfig.ts
packages/types/src/authConfig.ts
packages/types/src/json.ts

`claimed_at` is a timestamp of when the instance was claimed. This only applies to applications created with the Keyless mode.

feat(clerk-js): Include a `claimed_at` property inside AuthConfig

---

.changeset/hungry-fishes-invent.md
packages/astro/src/integration/create-integration.ts
packages/astro/src/internal/index.ts
packages/astro/src/internal/remove-query-param.ts
packages/astro/src/server/clerk-middleware.ts

Netlify caches the responses from pages. When the middleware initiates a handshake redirect and returns to the original URL, Netlify serves the cached response (along with the cookies), leading to an infinite handshake redirect loop.
I've tried using Netlify's [cache key variations](https://docs.netlify.com/platform/caching/#cache-key-variation) but it doesn't seem to work.
This PR adds a cache bust parameter to the original URL to prevent Netlify from serving the cached response. The parameter is automatically removed from the URL after the page loads.
I don't have e2e tests for it, but you can compare the ff.:
1. https://astro-clerk-template.netlify.app - one without fix, notice the redirect loop after signing in
2. https://deploy-preview-2--astro-clerk-template.netlify.app - the one …

fix(astro): Prevent Netlify from doing a handshake redirect loop

---

.changeset/two-doors-rush.md
packages/clerk-js/src/core/constants.ts
packages/clerk-js/src/ui/components/SignIn/SignInStart.tsx
packages/clerk-js/src/ui/components/SignUp/SignUpStart.tsx
packages/elements/src/internals/constants/index.ts
packages/elements/src/internals/machines/sign-in/router.machine.ts
packages/elements/src/internals/machines/sign-up/router.machine.ts

SSO per org introduces new errors for when org memberships are maxed out for the given organization. We want to display user friendly error messages in these cases.

feat(clerk-js,elements): Handle new organization membership quota exceeded error for SSO

---

.changeset/cold-tomatoes-float.md
packages/clerk-js/src/core/resources/UserSettings.ts
packages/clerk-js/src/ui/components/SignUp/SignUpStart.tsx
packages/clerk-js/src/ui/utils/index.ts
packages/clerk-js/src/ui/utils/useFormControl.ts
packages/clerk-js/src/ui/utils/usernameUtils.ts
packages/localizations/src/en-US.ts
packages/types/src/userSettings.ts

Adds missing min_length and max_length values within `form_username_invalid_length` error.
Resolves SDK-2006

fix(clerk-js,localizations,types): Add min and max lengths to username field error

---

.changeset/young-swans-sin.md
packages/clerk-js/src/ui/components/SignIn/SignIn.tsx
packages/clerk-js/src/ui/components/SignUp/SignUp.tsx
packages/clerk-js/src/ui/contexts/components/SignIn.ts
packages/clerk-js/src/ui/contexts/components/SignUp.ts
packages/clerk-js/src/utils/__tests__/redirectUrls.test.ts
packages/clerk-js/src/utils/redirectUrls.ts

When using the `<SignInButton />` or `<SignUpButton />` within modal mode and no redirect_url is provided, redirect to the current page vs `/`.
Resolves SDKI-616

fix(clerk-js): Redirect to current page within modal with no redirect url

---

.changeset/young-beans-trade.md
packages/nextjs/src/server/errors.ts
packages/nextjs/src/server/utils.ts

In Keyless mode it is expected that the user will eventually set keys as environment variables. When they do that, the nextjs server will restart, but there seems to be a mismatch because first the rendering lifecycle runs with the new keys and then the keys are updated in the middleware. This causes an error to be thrown to the user which we can actually improve.
**For the happy path**: we avoid displaying that error by retrying to decrypt data with the dummy key.
**For any other case**: when swapping keys or going back to headless you will now see this (see picture). this does not only reply to keyless.

chore(nextjs): Improve experience when swapping keys on Keyless mode

---

.changeset/wet-jars-tickle.md
packages/clerk-js/src/core/auth/cookies/devBrowser.ts
packages/clerk-js/src/core/auth/devBrowser.ts

This reverts commit fa82b43. Fixing a number of recently reported customer issues.

fix(clerk-js): Revert #4776

---

.changeset/old-dryers-approve.md
packages/types/src/externalAccount.ts
packages/types/src/factors.ts
packages/types/src/signIn.ts
packages/types/src/signUp.ts
packages/types/src/user.ts

This PR introduces two newly added params: `oidcLoginHint` and `oidcPrompt`

feat(types): Add `oidcPrompt` and `oidcLoginHint`

---

.changeset/shiny-pandas-love.md
packages/vue/src/components/SignInButton.ts
packages/vue/src/components/SignUpButton.ts

We are exposing the `initialValues` prop in the React SDK within unstyled components [here](https://github.com/clerk/javascript/pull/4567). This PR ports that into the Vue SDK.
```vue
<template>
<SignUpButton
:initial-values="{ emailAddress: 'example@clerk.dev' }"
/>
</template>
```
No major version yet so just patching this one

chore(vue): Expose `initialValues` prop within `<SignInButton />` and `<SignUpButton />`

---

.changeset/ten-taxis-decide.md
packages/clerk-js/src/core/clerk.ts

Rethrow unrelated errors during init so they can be caught by the normal retry mechanism that existed before the fraud engine changes

fix(clerk-js): Rethrow errors if not requires_captcha during init

---

.changeset/friendly-trains-love.md
packages/clerk-js/src/ui/components/UserProfile/EnterpriseAccountsSection.tsx

Resolves ORGS-434
Previously, it was merging the provider key to our CDN URL, therefore SAML custom was resolving to an invalid path/asset:
FAPI already returns a logo URL which is serialized for each enterprise connection type, and we can always trust that now instead of concatenating manually.

fix(clerk-js): Fix broken enterprise connection icon for custom SAML provider

---

.changeset/light-impalas-visit.md
packages/expo/src/index.ts

fix(clerk-expo): Re-export the `isClerkRuntimeError()` utility

---

.changeset/bright-mangos-pump.md
packages/clerk-js/src/core/clerk.ts
packages/clerk-js/src/ui/components/KeylessPrompt/index.tsx
packages/clerk-js/src/ui/components/KeylessPrompt/use-revalidate-environment.ts

We have decided to open a new tab for developers to claim their application while on Keyless mode. This means we need to "listen" for the updated `claimedAt` property from environment when the developer has claimed and returns back to the tab where application is running.

fix(clerk-js): Revalidate environment on window focus for Keyless

---

.changeset/tame-wolves-sit.md
packages/vue/src/composables/useAuth.ts

This PR makes sure `getToken` from `useAuth()` composable returns a token by adding `immediate: true` to the watcher. Without this option, the internal `clerkLoaded` promise would never resolve if Clerk was already loaded.

fix(vue): Fix `getToken()` hanging when Clerk is already loaded

---

packages/nextjs/src/app-router/server/auth.ts
packages/nextjs/src/server/__tests__/clerkMiddleware.test.ts
packages/nextjs/src/server/protect.ts
packages/types/src/session.ts

chore(types,nextjs): Handle types in `protect()`

---

.changeset/nasty-adults-shave.md
packages/clerk-js/src/ui/components/SignIn/SignInSocialButtons.tsx
packages/clerk-js/src/ui/components/SignUp/SignUpSocialButtons.tsx
packages/clerk-js/src/ui/utils/index.ts
packages/clerk-js/src/ui/utils/web3CallbackErrorHandler.ts
packages/clerk-js/src/utils/web3.ts
packages/localizations/src/en-US.ts
packages/types/src/localization.ts

chore(clerk-js,types,localizations): Improve error handling when web3 wallet is not installed

---

.changeset/large-phones-peel.md
packages/react-router/src/ssr/types.ts

Previously such usage would have thrown type errors:
```ts
export async function loader(args: Route.LoaderArgs) {
return rootAuthLoader(args, async () => {
return data({ title: "React Router Clerk Starter" }, { headers: {} });
})
}
export function Layout({ children }: { children: React.ReactNode }) {
const data = useRouteLoaderData<typeof loader>('root')
return (
// TODO
);
}
```
We didn't account for the return type of the `data()` utility in our types. This should work now 👍

fix(react-router): Correct types for data() usage in callback

---

.changeset/fair-bobcats-pull.md
packages/backend/src/tokens/authObjects.ts
packages/nextjs/src/app-router/server/auth.ts
packages/nextjs/src/server/__tests__/clerkMiddleware.test.ts
packages/nextjs/src/server/protect.ts
packages/react/src/hooks/__tests__/useAuth.test.tsx
packages/types/src/jwtv2.ts
packages/types/src/organizationMembership.ts
packages/types/src/session.ts

Resolves ORGS-441
System permissions (e.g., `org:sys_domains:manage`) are intentionally excluded from session claims to maintain reasonable JWT sizes. While these permissions work in client-side authorization checks (where they're validated against FAPI organization memberships), they cannot be verified server-side.
Despite documentation updates, developers continue to use server-side authorization checks with system permissions, leading to confusion and support tickets.
Add type-level validation to catch misuse of system permissions during development. I've opted not to introduce a runtime warning since developers might ignore it.

chore(backend,nextjs,types): Prevent system permissions usage in server-side

---

.changeset/shaggy-otters-hug.md
packages/clerk-js/src/ui/components/KeylessPrompt/index.tsx

fix(clerk-js): Keyless toast's collapse behavior

---

.changeset/brave-steaks-press.md
packages/nextjs/src/server/clerkMiddleware.ts

In our middleware, we rewrite protected pages to a known fake page to trigger a not found error. Previously, we utilized the `Origin` header to determine the base URL to rewrite to, which triggered an actual page request in Next.js 15, resulting in an infinite loop of middleware invocations. This PR adjusts the base origin of the rewrite to use `nextRequest.url`, which Next.js will always understand as an internal page, thus not triggering an additional invocation of middleware.

fix(nextjs): Always use nextUrl to build rewritten URLs

---

.changeset/eighty-jars-destroy.md
packages/clerk-js/src/ui/components/SignIn/SignInStart.tsx
packages/clerk-js/src/utils/getClerkQueryParam.ts

This PR updates the `SignIn` component to navigate to `SignUp` (either the nested combined flow route or the full-page `SignUp` component) based on the `__clerk_status` parameter passed with ticket flows.

fix(nextjs): Redirect to sign-up based on clerk_status

---

.changeset/grumpy-foxes-sneeze.md
packages/backend/src/tokens/__tests__/request.test.ts
packages/backend/src/tokens/request.ts

The dev satellite sync relies on the `__clerk_synced` query parameter to indicate termination of the sync flow. We recently removed the check for `__clerk_synced`, but it needs to be re-added for the dev sync flow when communicating with the primary application.

fix(backend): Satellite domains dev sync

---

.changeset/bright-mangos-grow.md
packages/backend/src/api/resources/JSON.ts
packages/backend/src/api/resources/Session.ts

This PR aligns the `Session` resource in the `@clerk/backend` SDK to match the OpenAPI spec of Backend API

fix(backend): Align Session resource with OpenAPI spec

---

.changeset/thirty-fireants-cough.md
packages/nextjs/src/app-router/keyless-actions.ts
packages/nextjs/src/app-router/server/auth.ts
packages/nextjs/src/server/clerkClient.ts
packages/nextjs/src/server/createGetAuth.ts
packages/nextjs/src/server/data/getAuthDataFromRequest.ts
packages/nextjs/src/server/headers-utils.ts
packages/nextjs/src/server/utils.ts

When `clerkMiddleware` is not used in an application we know that any attempt to use `await auth()` will fail, so we don't need to force "middleware" to rerun in order for our server side helpers to have the correct keys. Accessing them will certainly fail either way.
In this scenario, we could have simply perform `detectClerkMiddleware()` inside the Server ClerkProvider, but we want to avoid doing that since that will opt in all routes into dynamic rendering implicitly which may annoy many developers.
Calling `buildRequestLike` inside a server action in Next.js will cause the application to break due to bundling issues of the framework that cause `fs` to leak into he client. For that reason, I've adjusted the implementation to work with the standard `Request` from WebAPI.

fix(nextjs): Detect middlware usage to avoid infinite loop on Keyless mode

---

.changeset/tame-glasses-smoke.md
packages/clerk-js/src/core/clerk.ts

Ensure the clerk-js UI chunks aren't loaded due to the `ensureMounted()` call within `handleKeylessPrompt()`, which is only necessary if a specific Clerk option is passed.

fix(clerk-js): Only call ensureMounted() if necessary

---

.changeset/spotty-berries-bake.md
packages/backend/src/api/endpoints/InvitationApi.ts

Added a `query` param for `GetInvitationList` API request params type.
I did this according to https://clerk.com/docs/reference/backend-api/tag/Invitations#operation/ListInvitations

fix(backend): Add `query` to `GetInvitationListParams`

---

packages/clerk-js/src/ui/common/__tests__/redirects.test.ts
packages/clerk-js/src/ui/common/redirects.ts
packages/clerk-js/src/ui/components/SignIn/SignInFactorOneEmailLinkCard.tsx
packages/clerk-js/src/ui/components/UserProfile/VerifyWithLink.tsx

This PR updates the `buildEmailLinkRedirectUrl` utility to factor in the intent of the redirect URL when calculating the URL. This results in sign-in links pointing to `/sign-in/verify` and sign up links in the combined flow pointing to `/sign-in/create/verify`. This prevents an issue where signing in using the combined flow generates a redirect_url pointing to `/sign-in/create/verify` which results in language pertaining to sign-up.

fix(clerk-js): Use correct email link redirect_url based on intent

---

.changeset/lemon-ducks-hug.md
packages/localizations/src/be-BY.ts
packages/localizations/src/cs-CZ.ts
packages/localizations/src/da-DK.ts
packages/localizations/src/de-DE.ts
packages/localizations/src/es-ES.ts
packages/localizations/src/fr-FR.ts
packages/localizations/src/it-IT.ts
packages/localizations/src/nl-NL.ts
packages/localizations/src/pt-PT.ts
packages/types/src/localization.ts

This PR expands on the fix and issue mentioned in #4878

fix(localizations): Force interpolation for `socialButtonsBlockButtonManyInView`

---

.changeset/friendly-news-fix.md
packages/chrome-extension/tsup.config.ts

If you look at https://unpkg.com/browse/@clerk/chrome-extension@2.1.11/dist/esm/index.js you'll see that we end up with:
```js
import { setErrorThrowerOptions } from './chunk-BGR6KYCZ.js';
export { ... } from './chunk-BGR6KYCZ.js';
import './chunk-V7OWHRAI.js';
import '@clerk/shared/loadClerkJsScript';
setErrorThrowerOptions({ packageName: "@clerk/chrome-extension" });
```
The unused `import '@clerk/shared/loadClerkJsScript';` is problematic because inside is "remotely hosted code" that the Chrome extension store is flagging. In https://github.com/clerk/javascript/pull/4551 build flags were added and they work. But the unused imports are not removed during bundling.
So the fix is to also mark `@clerk/shared` _not_ external and bundle it. Then tsup seems to be able to remove those unused …

fix(chrome-extension): Bundle @clerk/shared to properly tree-shake

---

packages/clerk-js/src/ui/components/SignIn/SignInStart.tsx
packages/clerk-js/src/ui/components/SignIn/handleCombinedFlowTransfer.ts
packages/clerk-js/src/ui/router/Route.tsx
packages/clerk-js/src/ui/router/RouteContext.tsx

- Ensure the `__clerk_ticket` query parameter is preserved when navigating internally.
- Adds a new `searchParams` option to our internal router `navigate()` method to allow passing structured search params, instead of relying on concatenating them onto the `to` argument.

fix(clerk-js): Preserve __clerk_ticket for internal sign-in navigation

---

.changeset/good-eggs-retire.md
packages/backend/src/api/endpoints/SessionApi.ts
packages/backend/src/api/resources/Cookies.ts
packages/backend/src/api/resources/Deserializer.ts
packages/backend/src/api/resources/JSON.ts
packages/backend/src/api/resources/index.ts
packages/backend/src/tokens/__tests__/request.test.ts
packages/backend/src/tokens/request.ts

Supports the `format=cookies` parameter for the session refresh endpoint. When this parameter is passed, the API will return an array of `set-cookie` header values to be passed along with the response.
SDKI-832

feat(backend): Set cookies from the refresh token flow

---

.github/workflows/ci.yml

We are using a deprecated GH action that will stop working soon: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
Seems to already be failing on some PRs: https://github.com/clerk/javascript/actions/runs/12811667573/job/35721593254?pr=4788

fix(repo): Update actions/upload-artifacts to v4

---

.changeset/new-mails-protect.md
packages/clerk-js/src/core/clerk.ts

Updates our `SignIn` telemetry event to include a property we can use to detect the combined flow usage.

chore(clerk-js): Combined flow telemetry

---

.changeset/quiet-dingos-laugh.md
packages/elements/src/internals/machines/sign-in/router.machine.ts
packages/elements/src/internals/machines/sign-up/router.machine.ts
packages/elements/src/internals/machines/sign-up/start.types.ts
packages/elements/src/internals/machines/types/router.types.ts
packages/elements/src/react/common/connections.tsx
packages/elements/src/react/common/loading.tsx
packages/elements/src/react/hooks/use-third-party-provider.hook.ts
packages/elements/src/react/utils/map-scope-to-strategy.ts
packages/elements/src/utils/third-party-strategies.ts
packages/types/src/signUp.ts

Allows to use `enterprise_sso` for custom flows with `@clerk/elements`
```tsx
<Clerk.Connection name="enterprise_sso">Sign in with SSO</Clerk.Connection>
<Clerk.Field name="identifier">
<Clerk.Label>Email Address</Clerk.Label>
<Clerk.Input type="text" required />
</Clerk.Field>
```
https://github.com/user-attachments/assets/1fcfec79-e10e-4725-a441-8a81cbf873f2

chore(elements,types): Support `enterprise_sso` strategy

---

.changeset/thin-laws-lie.md
integration/templates/react-router-library/package.json
integration/templates/react-router-node/package.json
packages/react-router/README.md
packages/react-router/package.json
playground/react-router/package.json
pnpm-lock.yaml

This PR bumps `react-router` peer dependency to [`^7.1.2`](https://github.com/remix-run/react-router/blob/main/CHANGELOG.md#v712) for upstream context mismatch fix.
Fixes https://github.com/clerk/javascript/issues/4826

chore(react-router): Bump `react-router` peer dependency

---

.changeset/yellow-cycles-invent.md
packages/clerk-js/src/utils/captcha/CaptchaChallenge.ts
packages/clerk-js/src/utils/captcha/retrieveCaptchaInfo.ts
packages/clerk-js/src/utils/captcha/turnstile.ts
packages/clerk-js/src/utils/captcha/types.ts

The turnstile script now returns 403 if proxied through the worker. This is a change on the CF side, so we: 
1. removed the code from the worker
2. removed the fallback logic from clerkjs
3. if challenges.cloudflare.com fails, then the clerkjs will send a captha_error payload instead of falling back to the proxy

fix(clerk-js): Do not use CF proxy as fallback for challenges.cloudflare.com

---

.changeset/brown-feet-perform.md
packages/clerk-js/src/utils/captcha/retrieveCaptchaInfo.ts

Smart Bot Protection on development instances that use Core 1 does not work as expected. This is because we run Turnstile only if the instance is a production instance. This was changed in Core 2, but this change should have been backported to Core 1 too.

fix(clerk-js): Fix Smart Bot Protection in development instances

---

.changeset/chilled-beds-smash.md
packages/clerk-js/src/ui/components/KeylessPrompt/index.tsx

- Remove 'Learn more' link and update copy text
- Refine popover's shadows and borders for smoother edges against dark backgrounds
Before
After

fix(clerk-js): Keyless UI shadows and copy improvement

---

.changeset/friendly-owls-jump.md
packages/clerk-js/src/ui/components/UserProfile/MfaPhoneCodeScreen.tsx

There's an infinite loading state happening when successfully adding 2FA via the security tab on the <UserButton/> component.
Fixes SDK-2034

fix(clerk-js): Ensure callback is called when adding a MFA phone number

---

.changeset/tough-suns-sparkle.md
packages/clerk-js/src/ui/elements/CaptchaElement.tsx
packages/clerk-js/src/utils/captcha/turnstile.ts

This PR fixes the layout shift caused by the Turnstile script, especially when in Smart mode there was no interactive challenge.
Before (Smart without interaction):
https://github.com/user-attachments/assets/ec682c00-8d0a-4284-b30c-14bc924158b3
After (Smart without interaction):
https://github.com/user-attachments/assets/230aa11e-6fb2-4e5e-973b-d2d0d30aca93
After (Smart with interaction):
https://github.com/user-attachments/assets/4092672d-dfd8-449b-b6d9-0de8c347b9aa

fix(clerk-js): Fix layout shift when Smart CAPTCHA executes an interactive challenge

---

.changeset/real-kings-help.md
packages/nextjs/src/app-router/client/ClerkProvider.tsx
packages/nextjs/src/app-router/client/keyless-cookie-sync.tsx
packages/nextjs/src/app-router/keyless-actions.ts
packages/nextjs/src/app-router/server/ClerkProvider.tsx
packages/nextjs/src/server/clerkMiddleware.ts
packages/nextjs/src/server/keyless.ts
packages/nextjs/src/server/utils.ts
packages/nextjs/src/utils/feature-flags.ts

The previous `canUseKeyless__client` did not depend on `process.env.NODE_ENV`, which during `pnpm build` would case `ClientClerkProvider` to render `LazyCreateKeylessApplication` which then "bypasses" any error related to missing PK.
The above was handled gracefully, as clerk-js would simply not be attempted to load. But this PR brings back the intended behaviour.

fix(nextjs): [Keyless] Prevent successful build when keys are not explicitly set

---

.changeset/short-tomatoes-shake.md
packages/clerk-js/src/ui/components/SignUp/SignUpForm.tsx
packages/clerk-js/src/ui/components/SignUp/SignUpStart.tsx
packages/clerk-js/src/ui/elements/CaptchaElement.tsx

fix(clerk-js): Fix interactive bot protection widget not appearing on transfer flow

---

.changeset/soft-pumpkins-rescue.md
packages/clerk-js/src/ui/components/KeylessPrompt/index.tsx
packages/clerk-js/src/ui/components/KeylessPrompt/use-revalidate-environment.ts

Throttling requests to `/v1/environment`.

chore(clerk-js): Keyless prompt revalidate environment at most every 10 seconds

---

.changeset/dirty-students-hang.md
packages/clerk-js/src/ui/components/KeylessPrompt/index.tsx

fix(clerk-js): Remove text shimmer animation from Keyless prompt UI

---

.changeset/eighty-tigers-doubt.md
package.json
packages/clerk-js/src/ui/components/SignUp/SignUpForm.tsx
packages/clerk-js/src/ui/components/SignUp/SignUpStart.tsx
packages/clerk-js/src/ui/elements/CaptchaElement.tsx
packages/clerk-js/src/utils/captcha/turnstile.ts

This PR is a Core 1 backport of the following fixes:
- Fix bot protection layout shift on the sign-up form. #4924 
- Fix the transfer flow when CAPTCHA is interactive. #4941 
https://github.com/user-attachments/assets/1f3372aa-5106-41f1-bc3b-cfadd4395434

[Core 1 backport] fix(clerk-js): Improvements on Smart bot protection

---

package.json

Setting the `engines` config to enforce using `pnpm@15` and above as some earlier v9 versions produce a different `pnpm-lock.yaml` file

fix(repo): Enforce pnpm@15 and above

---

.changeset/unlucky-horses-brush.md
packages/clerk-js/src/ui/components/KeylessPrompt/index.tsx

fix(clerk-js): Add "Go to dashboard" link in Keyless popover

---

.changeset/five-plants-sin.md
packages/clerk-js/src/ui/contexts/components/SignIn.ts
packages/clerk-js/src/ui/contexts/components/SignUp.ts

This PR fixes an issue where certain query parameters were not preserved due to us passing an empty `authQueryString` to the `buildRedirectUrl` call for `ssoCallbackUrl`. This resulted in the generation of `ssoCallbackUrl` values that did not retain important parameters such as `sign_in_force_redirect_url`.

fix(clerk-js): Use authQueryString when building callback URLs

---

.changeset/dirty-cooks-pay.md
packages/react-router/src/ssr/types.ts
packages/remix/src/ssr/types.ts
packages/tanstack-start/src/server/types.ts

The `authorizedParties` TypeScript type was incorrectly set in three SDKs. This PR changes the type aliases to reuse the existing type from the Backend SDK which has the correct type.
https://github.com/clerk/javascript/blob/d450f71c89cdb71fcd339c0ba409ce4e49c4b6e7/packages/backend/src/jwt/verifyJwt.ts#L98
Fixes https://github.com/clerk/javascript/issues/4960

fix(*): Correct type for authorizedParties

---

.changeset/popular-mails-jam.md
packages/shared/src/error.ts

Fixes an issue in custom flow within a next.js project where `isEmailLinkError` is always returning false for the following code due to checking for the instance of EmailLinkError and multiple versions of share packages being included.
```tsx
try {
await handleEmailLinkVerification({
...
});
} catch (err: any) {
if (isEmailLinkError(err)) {
...
}
}
```

fix(shared): Update isEmailLinkError check to look for err name

---

.changeset/shiny-crabs-exercise.md

We can safely move the React Router SDK out of beta and into a non-zero version range. So this is a really _boring_ major update as-in there are no changes at all. Just a version bump ☺️

chore(react-router): Bump version to v1

---

.changeset/cyan-beds-cross.md
packages/shared/package.json
packages/shared/src/handleValueOrFn.ts

Re-adds `handleValueOrFn` to `@clerk/shared` subpaths with a deprecation warning.
Fixes ECO-321

fix(shared): Remove `handleValueOrFn` from subpaths

---

.changeset/chatty-lemons-hug.md
packages/clerk-js/src/core/__tests__/clerk.test.ts
packages/clerk-js/src/core/__tests__/fapiClient.test.ts
packages/clerk-js/src/core/clerk.ts
packages/clerk-js/src/core/fapiClient.ts

Ensure `createFapiClient()` always receives a domain so we can decide if we should be using it or not.

fix(clerk-js): Always pass domain to createFapiClient()

---

.changeset/dull-ravens-fix.md
packages/backend/src/api/endpoints/OrganizationApi.ts

`orderBy` is a valid query param for retrieving memberships of a given organization, however it wasn't being forward to fetch call.
https://clerk.com/docs/reference/backend-api/tag/Organization-Memberships#operation/ListOrganizationMemberships!in=query&path=order_by&t=request

fix(backend): Add `orderBy` to `getOrganizationMembershipList`

---

.changeset/purple-foxes-develop.md
packages/clerk-js/src/core/resources/SignUp.ts
packages/clerk-js/src/ui/components/SignUp/SignUpStart.tsx
packages/types/src/signUp.ts

Currently, when a user lands on the sign-up component with a ticket, it sends a request to the Clerk API and starts a new sign-up attempt. If the process requires a password, it will start another new sign-up attempt on submit, losing the original context.
The issue occurs mainly when the server responds with a `422` error because of e.g. a pwned password. If the user then switches to an OAuth strategy, the initial sign-up attempt should be reused with the same context instead of starting over and potentially losing data.
This PR fixes the issue by adding an `upsert` method to the `SignUp` resource. This method reuses the existing sign-up attempt ID if one already exists. While this change could have been made directly in place, adding this new method seems to me like a cleaner approach. …

fix(clerk-js,types): Reuse existing sign-up if available

---

.changeset/wet-beers-compete.md
packages/clerk-js/src/ui/components/KeylessPrompt/index.tsx

fix(clerk-js): Removed nested <p> from Keyless popover

---

.changeset/weak-monkeys-approve.md
packages/nextjs/src/app-router/server/ClerkProvider.tsx

fix(nextjs): Avoid calling `safeParseClerkFile` before checking if keyless is allowed

---

.changeset/mighty-otters-remain.md
packages/clerk-js/src/core/__tests__/clerk.test.ts
packages/clerk-js/src/core/clerk.ts
pnpm-lock.yaml

Ensure `proxyUrl` is passed to `createFapiClient()`.

fix(clerk-js): Pass proxyUrl to createFapiClient

---

.changeset/selfish-worms-switch.md
packages/expo/src/hooks/index.ts
packages/expo/src/hooks/useOAuth.ts
packages/expo/src/hooks/useSSO.ts
packages/expo/src/hooks/useSso.ts

Resolves ORGS-454
This PR introduces a new React hook to trigger a wider range of SSO types such as SAML with the `enterprise_sso` strategy.
SAML support for native flows has been released on FAPI, and implemented by our native IOS SDK. It leverages the same `rotating_token_nonce` solution on SSO callback as it currently has for social OAuth.
```ts
const { startSSOFlow } = useSSO()
const [email, setEmail] = useState("") // Derived from a input field
const handleSSO = async () => {
if (!isLoaded) return
try {
// Triggers SSO on a browser window on mobile + opens in a new tab for web
// On authorization, redirects back to the application
const { createdSessionId, setActive, signIn, signUp } = await startSSOFlow({
identifier: email,
strategy: "enterprise_sso"
})
// If the sign-in was …
```

feat(clerk-expo): Introduce SAML support

---

.changeset/thirty-badgers-hammer.md
packages/clerk-js/bundlewatch.config.json
packages/clerk-js/src/ui/components/KeylessPrompt/index.tsx

Managing urls to dashboard like that is not sustainable, this will be addressed the following PR, once the flow has been finalized

fix(clerk-js): Navigate to specific instance for configuration after keyless

---

renovate.json5
scripts/renovate-config-generator.mjs

Our Renovate PRs fail due to the dedupe check. Since we previously used npm we didn't change the [postUpdateOptions](https://docs.renovatebot.com/configuration-options/#postupdateoptions) to account for that. Afterwards the Renovate PRs should be ready without us having to run dedupe.

chore(repo): Use pnpmDedupe for Renovate

---

.changeset/kind-crabs-unite.md
packages/nextjs/src/app-router/client/ClerkProvider.tsx
packages/nextjs/src/app-router/client/keyless-creator-reader.tsx
packages/nextjs/src/app-router/keyless-actions.ts
packages/nextjs/src/app-router/server/ClerkProvider.tsx
packages/nextjs/src/server/keyless-node.ts

If keys are not explicitly set, keyless will kick in, if keyless creation fails, then fallback to throwing error for missing publishable key

chore(nextjs): Gracefully handle failure to create keyless

---

.changeset/nasty-houses-boil.md
integration/templates/tanstack-router/package.json
integration/templates/tanstack-start/package.json
packages/tanstack-start/package.json
pnpm-lock.yaml

Since TanStack Router and Start [v1.85.9](https://github.com/TanStack/router/releases/tag/v1.85.9), they've upgraded Vinxi to 0.5. This PR bumps our Vinxi dependency to 0.5 and minimum `@tanstack/start` and `@tanstack/react-router` version to 1.85.9.

chore(tanstack-start): Bump Vinxi to 0.5 and TanStack minimum version

---

.changeset/cool-teachers-join.md
packages/clerk-js/src/utils/captcha/getCaptchaToken.ts
packages/clerk-js/src/utils/captcha/turnstile.ts

Turnstile RHC found its way back into the `clerk.no-rhc.mjs` build. This works to remove it.
Fixes ECO-350

fix(clerk-js): Remove RHC for unsupported environments

---

.changeset/violet-years-dream.md
packages/clerk-js/src/ui/components/SignIn/SignIn.tsx

Ensure when within the combined flow, the signInUrl is passed correctly to the sign-up components.

fix(clerk-js): Pass signInUrl to sign up context when in combined flow

---

.changeset/witty-ladybugs-fix.md
packages/nextjs/src/app-router/server/currentUser.ts
packages/nextjs/src/server/buildClerkProps.ts
packages/nextjs/src/server/createGetAuth.ts
packages/react/src/hooks/__tests__/useRoutingProps.test.tsx
packages/react/src/hooks/useAuth.ts
packages/react/src/hooks/useSignIn.ts
packages/react/src/hooks/useSignUp.ts
packages/react/src/isomorphicClerk.ts
packages/react/typedoc.json
packages/shared/src/react/hooks/useClerk.ts
packages/shared/src/react/hooks/useOrganization.tsx
packages/shared/src/react/hooks/useOrganizationList.tsx
packages/shared/src/react/hooks/useReverification.ts
packages/shared/src/react/hooks/useSession.ts
packages/shared/src/react/hooks/useSessionList.ts
packages/shared/src/react/hooks/useUser.ts
packages/shared/src/react/types.ts
packages/types/src/appearance.ts
packages/types/src/hooks.ts
packages/types/typedoc.json
tsconfig.typedoc.json
typedoc.config.mjs

Improve and add JSDoc comments to the public API of `@clerk/clerk-react` to document all client-side helpers (later with Typedoc). Since some of the hooks are in `@clerk/shared` you'll also see changes there.
Some comments are duplicated and _not_ DRY, unfortunately you can't add a comment to a type alias and use that instead. TypeScript doesn't support that 😢

chore(clerk-react): Improve JSDoc comments

---

.changeset/neat-planets-raise.md
integration/tests/elements/next-sign-in.test.ts
integration/tests/elements/next-sign-up.test.ts
packages/clerk-js/src/core/clerk.ts
packages/clerk-js/src/utils/redirectUrls.ts
packages/elements/src/internals/machines/sign-in/router.machine.ts
packages/elements/src/internals/machines/sign-up/router.machine.ts
packages/types/src/clerk.ts

Ensures `redirect_url` parameters passed to Elements components are always passed through `build*Url()` methods before use. Also updates the methods to accept a `params` option.
```ts
Clerk.buildAfterSignInUrl({ params: new URLSearchParams({ redirect_url: '/dashboard' }) })
```
fixes SDKI-854

feat(clerk-js,elements): Pass params through `build*Url()` methods

---

.changeset/smart-worms-collect.md
packages/clerk-js/src/ui/components/OrganizationProfile/OrganizationProfile.tsx
packages/clerk-js/src/ui/components/SignIn/SignIn.tsx
packages/clerk-js/src/ui/components/SignUp/SignUp.tsx
packages/clerk-js/src/ui/components/UserProfile/UserProfile.tsx
packages/clerk-js/src/ui/components/UserVerification/index.tsx
packages/clerk-js/src/ui/types.ts
packages/types/src/clerk.ts

Revert "refactor(clerk-js,types): Remove virtual routing option from component types"

---

.changeset/quiet-ties-walk.md
packages/tanstack-start/package.json
packages/tanstack-start/src/server/middlewareHandler.ts
pnpm-lock.yaml

Reverts clerk/javascript#5051
This reversion is no longer needed (and didn't actually fix the issue) as the underlying h3 version compatibility issue 
has been resolved upstream in the TanStack Router repository ([TanStack/router#3310](https://github.com/TanStack/router/pull/3310))

Revert "fix(tanstack-start): Fix event handler return type mismatch"

---

.changeset/smooth-insects-perform.md
packages/testing/src/playwright/setupClerkTestingToken.ts
packages/types/src/json.ts

This PR adds support for bypassing the Turnstile script when running tests on Playwright and have the Bot Protection enabled for sign-ups in the Clerk Dashboard.
Cypress support will be added in a follow-up PR

fix(testing): Fix captcha triggering issue in Playwright tests

---

integration/models/applicationConfig.ts
integration/presets/envs.ts
integration/tests/next-quickstart-keyless.test.ts

Keyless applications on e2e tests are never claimed and that hurts some of our metrics. This PR switches to the staging database for keyless applications, until we have a proper fix that all teams are happy with.

chore(e2e): Run keyless e2e tests in staging database

---

.changeset/friendly-ears-bow.md
packages/clerk-js/src/ui/lazyModules/providers.tsx

Adding a deprecation warning for virtual routing usage, that is to be removed in the next major release.
Resolves SDKI-858

chore(clerk-js): Add virtual routing deprecation warning

---

.changeset/seven-games-arrive.md
packages/clerk-js/src/ui/components/UserProfile/ConnectedAccountsMenu.tsx
packages/clerk-js/src/ui/components/UserProfile/ConnectedAccountsSection.tsx
packages/clerk-js/src/ui/components/UserProfile/EmailsSection.tsx
packages/clerk-js/src/ui/components/UserProfile/MfaSection.tsx
packages/clerk-js/src/ui/components/UserProfile/PasskeySection.tsx
packages/clerk-js/src/ui/components/UserProfile/PhoneSection.tsx
packages/clerk-js/src/ui/components/UserProfile/Web3Form.tsx
packages/clerk-js/src/ui/components/UserProfile/Web3Section.tsx
packages/clerk-js/src/ui/components/UserProfile/__tests__/ConnectedAccountsSection.test.tsx
packages/clerk-js/src/ui/components/UserProfile/__tests__/EmailsSection.test.tsx
packages/clerk-js/src/ui/components/UserProfile/__tests__/MfaPage.test.tsx
packages/clerk-js/src/ui/components/UserProfile/__tests__/PasskeysSection.test.tsx
packages/clerk-js/src/ui/components/UserProfile/__tests__/PhoneSection.test.tsx
packages/clerk-js/src/ui/elements/Action/ActionRoot.tsx
packages/clerk-js/src/ui/elements/Section.tsx

- Currently within user profile, you can open both add and remove section forms at once which leads to some awkward UX
- This PR updates some logic to only be able to render one at a time
**BEFORE**
https://github.com/user-attachments/assets/b88b9c85-4df1-4bc2-8d20-7e5d1272cdce
**AFTER**
https://github.com/user-attachments/assets/a8fd20b0-18b4-4754-8e0f-b8442900f835
Fixes SDKI-817

fix(clerk-js): Ensure only one action is present in UserProfile sections

---

.changeset/healthy-panthers-shave.md
integration/templates/react-vite/src/custom-user-button/with-dynamic-labels.tsx
integration/templates/react-vite/src/main.tsx
integration/tests/custom-pages.test.ts
packages/react/src/components/ClerkHostRenderer.tsx

In this pr we re-render the `<UserButton />` component when the props are changing 
e.g.
Before this change the following example didn't work, the label was always `Chat is OFF`
```
<UserButton>
<UserButton.MenuItems>
<UserButton.Action
label={`Chat is ${open ? 'ON' : 'OFF'}`}
labelIcon={<DotIcon />}
onClick={() => setIsOpen(!open)}
/>
</UserButton.MenuItems>
</UserButton>
```
Now the `<UserButton />` appropriate 
https://github.com/user-attachments/assets/17463463-07e1-4eef-aeb6-75ae1b2ba918

fix(clerk-react): Re-render `<UserButton />` when `<UserButton />` props change

---

.changeset/tasty-socks-hide.md
packages/clerk-js/src/core/clerk.ts
packages/clerk-js/src/core/resources/Base.ts

This fix prevents the browser from getting into an infinite loop when the `/v1/client` endpoint returns `403`.

fix(clerk-js): Prevent infinite loop when client is blocked

---

.changeset/silver-dodos-invite.md
packages/clerk-js/src/core/clerk.ts
packages/clerk-js/src/utils/__tests__/url.test.ts
packages/clerk-js/src/utils/url.ts

`createAllowedRedirectOrigins` now takes the instance type into account to include the Frontend API URL for development instances.
This came up while releasing the new version of Clerk as an IdP, which requires a redirect to `{frontendApi}/oauth/authorize`. For local development, this previously had to be manually added to the allowed origins. Since it's a safe URL to include by default, it makes sense to add it everytime for development instances.
Fixes: SDK-2033

feat(clerk-js): Add Frontend API URL to allowed redirect origins

---

.changeset/shaggy-rocks-look.md
packages/localizations/src/es-MX.ts

Changing the translation of "profile" to "perfil"
Before: 
After:

chore(localizations): Update "profile" treatment on latin-american spanish

---

.changeset/witty-cougars-tickle.md
packages/clerk-js/src/ui/components/SignIn/SignInFactorOneCodeForm.tsx

https://github.com/user-attachments/assets/346dc624-08f6-49cb-822d-c9309c6d08b9
https://github.com/user-attachments/assets/f4b6cde4-08db-4485-858c-86dc8575b60e

fix(clerk-js): Avoid triggering email code verification twice on React strict mode

---

.changeset/violet-seas-speak.md
packages/backend/src/api/__tests__/factory.test.ts
packages/backend/src/api/endpoints/UserApi.ts

Deprecate usage of the `oauth_` prefix in `client.users.getUserOauthAccessToken()`

chore(backend): Deprecate usage of the `oauth_` prefix in `getUserOauthAccessToken()`

---

.changeset/forty-tools-jump.md
packages/clerk-js/bundlewatch.config.json
packages/clerk-js/package.json
pnpm-lock.yaml

Update `@coinbase/wallet-sdk` dependency to `4.3.0`, to resolve [SDK Security Advisory](https://github.com/coinbase/coinbase-wallet-sdk/security/advisories/GHSA-8rgj-285w-qcq4)

chore(clerk-js): Bump Coinbase sdk version to `4.3.0`

---

.changeset/flat-horses-battle.md
packages/expo/src/hooks/useSSO.ts

The ability to pass a custom redirect URL was removed on the first version of `useSSO`, testing back then, deep linking wasn't working for both platforms (iOS and Android), and the assumption was to leverage a fixed URL to parse the nonce token. 
However, deep linking is working on Android and some developers are falling into a 404 context.
This PR allows providing a custom redirect URL to `startSSOFlow`, and also returns the result of `WebBrowser.openAuthSessionAsync` so developers can debug it's output on cases where the native configuration could be wrong, such as lacking permissions to open web browsers from the application manifest.
Here's an OAuth flow deep linking to a custom redirect URL on Android:
https://github.com/user-attachments/assets/7dc06677-890c-4333-8dab-2dc10447c7c1

fix(clerk-expo): Accept custom redirect URL for SSO callback

---

.changeset/grumpy-kangaroos-ring.md
integration/templates/vue-vite/src/components/CustomUserButton.vue
integration/tests/vue/components.test.ts
packages/vue/src/components/ui-components/UserButton/index.ts

The `<UserButton />` component was missing the ability to add custom user profile links via `<UserButton.UserProfileLink>`.
The implementation is already available, but I forgot to include it in the exported component. We should be able to do this in this PR:
```vue
<script setup>
import { UserButton } from '@clerk/vue'
</script>
<template>
<UserButton>
<UserButton.UserProfileLink
label="Homepage"
url="/"
>
<template #labelIcon>
<div>Icon</div>
</template>
</UserButton.UserProfileLink>
</UserButton>
</template>
```
Resolves ECO-374

fix(vue): Include missing `UserProfileLink` component inside `<UserButton />` component

---

packages/astro/src/astro-components/unstyled/SignInButton.astro
packages/astro/src/astro-components/unstyled/SignOutButton.astro
packages/astro/src/astro-components/unstyled/SignUpButton.astro
packages/astro/src/types.ts

Prop types working:
https://github.com/user-attachments/assets/2bb43e87-3548-4f8f-aa39-a40c8b0a4884
Output:

feat(astro): Add appearance option to Astro unstyled components

---

.changeset/soft-flowers-tan.md
packages/localizations/src/hr-HR.ts

This is a simple change extending croatian language localizations

Add legal consent localizations for hr-HR

---

.changeset/tiny-moose-appear.md
packages/upgrade/src/app.js
packages/upgrade/src/util/get-clerk-version.js

A user reported this error while running the upgrade tool on their repo:
```shell
Cannot read properties of null (reading '0')
node_modules/@clerk/upgrade/dist/util/get-clerk-version.js:6:43
```
This comes from these lines:
```js
const clerk = pkg.dependencies.clerk;
return clerk ? semverRegex().exec(clerk)[0][0] : false;
```
`clerk` will always be `undefined` because `read-pkg` doesn't normalize namespaced packages in such a way. It e.g. returns back `dependencies: { '@clerk/nextjs': '^5.11.2', 'read-pkg': '^9.0.1' },`.
But for whatever reason for this user the regex is executed.
Anyways, the function is unused anyways and the desired functionality is already fulfilled by the `guessFrameworks` function.

fix(upgrade): Remove unused getMajorVersion function

---

.changeset/quiet-ladybugs-reply.md
packages/nextjs/src/app-router/client/ClerkProvider.tsx
packages/nextjs/src/app-router/client/useInternalNavFun.ts
packages/nextjs/src/global.d.ts
packages/types/src/snapshots.ts
packages/types/src/utils.ts

https://github.com/user-attachments/assets/f79e0336-b85d-4222-9ba6-2d189ef1921a
https://github.com/user-attachments/assets/de4029bc-9657-46d3-9566-b1d4bc08a2fd

fix(nextjs): Shallow routing for in-component navigations

---

.changeset/unlucky-spiders-kick.md

Add changeset for tanstack-start changes in https://github.com/clerk/javascript/pull/5142

chore(repo): Add missing changeset for tanstack-start EmailLinkErrorCodeStatus

---

.changeset/fast-teachers-attack.md
packages/nextjs/src/server/__tests__/clerkMiddleware.test.ts
packages/nextjs/src/server/clerkMiddleware.ts

Portrait https://github.com/clerk/javascript/pull/5147
The ability to set `clerkMiddleware` options with a request callback was introduced [here](https://github.com/clerk/javascript/pull/5147), to cover the cases of setting a satellite domain based on the incoming host.
However, the logic was only tested as synchronously accessing the request, and we forgot to support the callback to be async to cover the other cases as fetching options from an external data source. 
The above is indicated in our docs as "dynamically":

fix(nextjs): Update `clerkMiddleware` request callback to accept an async function

---

.changeset/spicy-turtles-tease.md
integration/tests/nuxt/middleware.test.ts
packages/nuxt/src/runtime/server/errors.ts
packages/nuxt/src/runtime/server/getAuth.ts
packages/nuxt/src/runtime/server/index.ts

This PR introduces a `getAuth()` helper to our Nuxt SDK similar to our other SDKs ([Next.js](https://clerk.com/docs/references/nextjs/get-auth)) that retrieves the current auth state.
Example:
```ts
import { getAuth } from '@clerk/nuxt/server';
export default eventHandler((event) => {
const { userId } = getAuth(event);
if (!userId) {
// User is not authenticated
}
});
```
Resolves ECO-405

feat(nuxt): Introduce `getAuth()` helper

---

.changeset/small-llamas-love.md
integration/templates/next-app-router/src/app/sign-in-or-up/[[...catchall]]/page.tsx
integration/templates/next-app-router/src/app/sign-up/[[...catchall]]/page.tsx
integration/testUtils/usersService.ts
integration/tests/sign-in-or-up-component.test.ts
integration/tests/unsafeMetadata.test.ts
packages/clerk-js/src/ui/components/SignIn/SignIn.tsx

This PR fixes an issue where we were not passing the `unsafeMetadata` prop from `<SignIn>` to the nested `SignUpContext`, which prevented it from being associated with sign ups. It also adds tests for `unsafeMetadata` in both the normal and combined flows.

fix(clerk-js): Pass unsafeMetadata to nested sign-up context in combined flow

---

.changeset/good-olives-unite.md
packages/clerk-js/src/core/clerk.ts
packages/shared/src/telemetry/events/component-mounted.ts
packages/types/src/telemetry.ts

Support passing additional payload values to `eventPrebuiltComponentMounted()`. This ensures we are actually recording `withSignUp`

fix(clerk-js): Ensure withSignUp is collected in telemetry

---

.changeset/unlucky-doors-yawn.md
packages/clerk-js/src/core/clerk.ts

Tracks usage of custom pages and custom items, and i squeezed the standalone prop as well :)

fix(clerk-js): Track usage of custom pages and custom items

---

.changeset/dirty-crabs-happen.md
packages/clerk-js/src/ui/components/UserVerification/AlternativeMethods.tsx

| ![Screenshot 2025-02-14 at 1 36 22 PM](https://github.com/user-attachments/assets/4bb1155e-fd4e-4dd2-8561-ce609930eccf) | ![Screenshot 2025-02-14 at 1 36 37 PM](https://github.com/user-attachments/assets/acb1e398-04c8-4803-b40c-60c2e0e78821) |

fix(clerk-js): Remove logo from verification alternative methods card

---

.changeset/rotten-jokes-destroy.md
packages/shared/package.json
packages/shared/src/__tests__/organization.test.ts
packages/shared/src/organization.ts
packages/shared/src/react/hooks/useOrganization.tsx
packages/vue/src/composables/useOrganization.ts

This PR moves the duplicated `getCurrentOrganizationMembership()` function in both `@clerk/vue` and `@clerk/shared/react` to `@clerk/shared/organization`.

chore(vue,shared): Move `getCurrentOrganizationMembership` helper to shared package

---

.changeset/sharp-owls-live.md
integration/templates/react-vite/src/custom-user-button/with-dynamic-label-and-custom-pages.tsx
integration/templates/react-vite/src/main.tsx
integration/tests/custom-pages.test.ts
packages/react/src/components/ClerkHostRenderer.tsx

fix(clerk-react): Prevent `UserProfileModal` re-render in `<UserButton />` with custom props

---

.changeset/olive-elephants-share.md
packages/agent-toolkit/package.json
packages/astro/package.json
packages/nuxt/package.json
packages/react-router/package.json
packages/vue/package.json

We should update some packages to allow for require(esm) to work correctly.
https://joyeecheung.github.io/blog/2024/03/18/require-esm-in-node-js/
We should use this everywhere for ESM-only packages:
```json
"type": "module",
"exports": {
"types": "./index.d.ts",
"default": "./index.js"
},
```
Then ESM will be correctly resolved. Because as per https://nodejs.org/api/packages.html#conditional-exports it says:
> "import" - matches when the package is loaded via import or import()
So with our current setup the `require()` won't work.
> "default" - the generic fallback that always matches.
Good 👍

fix(*): Update some package.json conditional exports

---

.changeset/sixty-ways-melt.md
packages/clerk-js/src/core/auth/CaptchaHeartbeat.ts
packages/clerk-js/src/core/fraudProtection.ts
packages/clerk-js/src/core/resources/SignUp.ts
packages/clerk-js/src/utils/captcha/CaptchaChallenge.ts
packages/clerk-js/src/utils/captcha/turnstile.ts
packages/clerk-js/src/utils/captcha/types.ts

Passes the `action` property with the following values:
- `verify`
- `signup`
- `heartbeat`

chore(clerk-js): Utilize the `action` property of Turnstile

---

.changeset/new-pots-itch.md
packages/react/src/isomorphicClerk.ts

Aligns types between `IsomorphicClerk` and `Clerk` to ensure the implementation remains in sync.

chore(clerk-react): Align types between Clerk and IsomorphicClerk

---

.changeset/poor-cobras-sin.md
packages/clerk-js/src/core/clerk.ts
packages/shared/src/telemetry/events/component-mounted.ts

This PR allows for telemetry data to be collected when the following components render
- GoogleOneTap (only modal)
- UserVerification (only modal)
- SignIn as modal
- SignUp as modal
- UserProfile as modal
- OrganizationProfile as modal
- CreateOrganization as modal
- Waitlist as Modal

feat(clerk-js): Track usage of UI modals

---

.changeset/moody-owls-return.md
packages/clerk-js/bundlewatch.config.json
packages/clerk-js/rspack.config.js

This PR fixes an issue where code within `node_modules` would not be transformed according to our `"browserslist"` configuration, which resulted in modern JS syntax being used within our bundle. By adding a new loader that does not contain the `exclude: /node_modules/` directive, we ensure that all bundled code is transformed by SWC according to our `"browserslist"` targets.

fix(clerk-js): Transform node_modules with swc

---

.changeset/rude-hats-chew.md
integration/templates/next-app-router-quickstart/src/app/globals.css
integration/templates/next-app-router/src/app/globals.css
integration/templates/react-cra/src/index.css
integration/templates/tanstack-router/package.json
integration/templates/tanstack-start/app.config.ts
integration/templates/tanstack-start/app/client.tsx
integration/templates/tanstack-start/app/routes/__root.tsx
integration/templates/tanstack-start/app/ssr.tsx
integration/templates/tanstack-start/package.json
packages/tanstack-start/package.json
pnpm-lock.yaml

The `@tanstack/start` package [has been deprecated](https://github.com/TanStack/router/discussions/2863#discussioncomment-12318045) in favor of `@tanstack/react-start`. This PR updates the
dependencies to use the new package name.
Since our TanStack Start SDK is still in beta, a `minor` bump will do 👍🏼 
Resolves ECO-439

chore(tanstack-start): Migrate to `@tanstack/react-start`

---

.changeset/itchy-pigs-learn.md
packages/dev-cli/src/commands/setup.js

This PR fixes an issue with `clerk-dev` where we would attempt to import a lock file even when one was not present. This was due to the `importPackageLock` function continuing to execute even after `resolve()` was called.

fix(dev-cli): Prevent import of lockfile when none is present

---

.changeset/mean-roses-dress.md
packages/clerk-js/src/ui/elements/Modal.tsx
packages/clerk-js/src/ui/hooks/useScrollLock.ts

This fixes an issue with  modal overlays which was introduced by a previous attempt that was fixing scroll locking [PR](https://github.com/clerk/javascript/pull/5233)
Using `FloatingOverlay` in the previous PR was resulting some sites to break with the following error 
```
Blocked aria-hidden on an element because its descendant retained focus. 
The focus must not be hidden from assistive technology users. 
Avoid using aria-hidden on a focused element or its ancestor. Consider using the inert attribute instead, which will also prevent focus. 
For more details, see the aria-hidden section of the WAI-ARIA specification at https://w3c.github.io/aria/#aria-hidden.
```

fix(clerk-js): Issue with scroll locking on modals

---

.changeset/wise-cameras-clean.md
packages/localizations/src/nl-NL.ts

The translation was wrong. In english the text is 'Already have access?' and 'Sign in'. And when clicking you are indeed taking to the login screen. In dutch the question was 'Don't have an account yet? (Nog geen account?)' and 'Neem deel aan de wachtlijst (Join the waiting list)' which then takes you to a login screen. Now it's properly translated.

fix(localizations): Update `waitlist.start` values for `nl-NL`

---

.changeset/rude-pumas-jog.md
packages/backend/src/api/endpoints/OrganizationApi.ts

BAPI has been updated to have `inviterUserId` as nullable/optional but we forgot to update the types here 
https://clerk.com/docs/reference/backend-api/tag/Organization-Invitations#operation/CreateOrganizationInvitation!path=inviter_user_id&t=request

fix(backend): Update `inviterUserId` type to optional

---

.changeset/poor-insects-yell.md
packages/clerk-js/src/ui/components/Waitlist/WaitlistForm.tsx

In this pr we're displaying the validation fields errors in `<Waitlist />` component. Before this pr we didn't display them correctly

fix(clerk-js): Display emailAddress validation errors in `<Waitlist />` component

---

.changeset/tricky-hats-sort.md
packages/backend/src/api/request.ts

Properly remove authorization header when `requireSecretKey: false`  and `secretKey` does not exist.

fix(backend): Remove `Authorization` header when `secretKey` is not required

---

.changeset/tame-seahorses-jump.md
packages/types/src/clerk.ts

chore(clerk-js): Remove unused `experimental.combinedFlow`

---

.changeset/serious-mice-approve.md
packages/clerk-js/src/ui/contexts/components/SignIn.ts

When a user passes `withSignUp={false}` we should opt out of combined flow even when `signUpUrl` is undefined.

fix(clerk-js): Add explicit check for `withSignUp` being false

---

.changeset/afraid-cats-study.md
packages/clerk-js/src/ui/components/SignUp/SignUpStart.tsx

Removes legal consent checkbox from sign-up start card when only social or web3 strategies are enabled.
Fixes SDKI-904

fix(clerk-js): Remove extra legal consent checkbox

---

.changeset/soft-walls-speak.md
packages/nuxt/package.json
packages/nuxt/src/module.ts
packages/nuxt/src/runtime/server/clerkMiddleware.ts
packages/nuxt/src/runtime/server/h3.d.ts
pnpm-lock.yaml

Previously `event.context.auth` inside [eventHandlers](https://h3.unjs.io/guide/event-handler) was typed as '`any`'. This is now fixed with 
Nuxt 3.16's [improved addTypeTemplate support for Nitro types](https://github.com/nuxt/nuxt/pull/31079).
Before:
After:
Resolves ECO-437

fix(nuxt): Add TypeScript support for auth object in event handlers

---

.changeset/blue-owls-beam.md
packages/backend/src/index.ts

This affects all BE sdks that rely in `@clerk/backend` for example it throttles the logging of `clerkMiddleware` usage in `@clerk/nextjs`.

chore(backend): Change telemetry sampling rate from 1 to 0.1

---

.changeset/wise-stingrays-protect.md
packages/clerk-js/src/core/constants.ts
packages/clerk-js/src/ui/components/SignIn/SignInStart.tsx
packages/clerk-js/src/ui/components/SignIn/__tests__/SignInStart.test.tsx

Consider form_password_pwned error as an instant password error. This will lead to the sign in beeing created again without the password field beeing submitted this time.

feat(clerk-js): Handle pwned password in SignInStart first party submit

---

.changeset/purple-hounds-tie.md
packages/clerk-js/src/core/resources/Session.ts
packages/clerk-js/src/ui/components/UserVerification/AlternativeMethods.tsx
packages/clerk-js/src/ui/components/UserVerification/UVFactorOnePasskeysCard.tsx
packages/clerk-js/src/ui/components/UserVerification/UserVerificationFactorOne.tsx
packages/clerk-js/src/ui/components/UserVerification/useReverificationAlternativeStrategies.ts
packages/localizations/src/en-US.ts
packages/types/src/localization.ts
packages/types/src/session.ts
packages/types/src/sessionVerification.ts

This PR introduces passkeys as a first factor strategy for re-verification

feat(clerk-js,localizations,types): Support passkeys for first factor re-verification

---

integration/scripts/proxyServer.ts

Long story short... crashing the proxy server is bad. 
Long story long... 
Our integration tests run against app servers using Next.js in dev mode, meaning Hot Module Replacement (HMR) is enabled. In some tests, we route traffic through a proxy server, which unexpectedly crashed when handling the `/_next/webpack-hmr` route.
Why? Because our proxy server wasn’t handling errors properly.
- Implemented error handling in the proxy server to prevent crashes.
- This issue started suddenly, likely because we always install the latest version of each Next.js major release in our test matrix.
- Suspicious Timing? Next.js v15.2.2 was released today, and it seems like the HMR route behavior changed. Coincidence? I think not.
- Should we be running Next.js in dev mode during tests?
- Should we pin …

fix(repo):  Handle errors in E2E proxy server

---

.changeset/purple-lamps-beg.md
packages/clerk-js/src/ui/components/PricingTable/PlanCard.tsx
packages/clerk-js/src/ui/customizables/elementDescriptors.ts
packages/types/src/appearance.ts

Conditionally render plan card avatar and badge.
| 1 | 2 | 3 |
|--------|--------|--------|
| ![Screenshot 2025-03-13 at 4 01 09 PM](https://github.com/user-attachments/assets/7ce9c844-2d7e-48d0-9ac0-1e690de5e125) | ![Screenshot 2025-03-13 at 4 01 52 PM](https://github.com/user-attachments/assets/91376696-14f0-46a9-8c08-54562cd1b0e1) | ![Screenshot 2025-03-13 at 4 04 02 PM](https://github.com/user-attachments/assets/0bc00fb1-762c-4065-b929-0707957e432c) | 
Resolves COM-112

fix(clerk-js): Conditionally render avatar

---

.changeset/serious-badgers-lie.md
packages/clerk-js/sandbox/template.html
packages/clerk-js/src/ui/components/PricingTable/PlanCard.tsx

When a C2 is not signed-in, redirect them to sign-in from the `<PlanCard />`
Resolves COM-147

feat(clerk-js): PlanCard redirect to sign in when not signed in

---

.changeset/chatty-lobsters-approve.md
packages/clerk-js/src/ui/components/Checkout/CheckoutForm.tsx

Use portal to fix positioning:
| ![Screenshot 2025-03-14 at 3 36 04 PM](https://github.com/user-attachments/assets/578237fd-7ab4-4f37-9c00-91cd9223388b) | ![Screenshot 2025-03-14 at 3 35 41 PM](https://github.com/user-attachments/assets/6791a194-c1a3-4914-855b-2a2684f32295) | 
Add text color to ensure select options render correctly for diff themes:
| ![Screenshot 2025-03-14 at 3 36 27 PM](https://github.com/user-attachments/assets/34b76556-8239-46ca-a7be-efea6f4471b1) | ![Screenshot 2025-03-14 at 3 35 12 PM](https://github.com/user-attachments/assets/2fec7d51-4488-4f5a-8a38-ef4253555344) |

fix(clerk-js): Fix `<CheckoutForm />` select positioning and option text color

---

.changeset/thick-bags-promise.md
packages/astro/src/react/hooks.ts
packages/clerk-js/src/core/resources/Session.ts
packages/clerk-js/src/core/resources/SessionWithActivities.ts
packages/clerk-js/src/utils/jwt.ts
packages/react/src/contexts/AuthContext.ts
packages/types/src/hooks.ts
packages/types/src/json.ts
packages/types/src/jwt.ts
packages/types/src/jwtv2.ts
packages/types/src/session.ts
packages/vue/src/types.ts

These types were duplicated and the new updated ones exist inside `jwtv2.ts`. This PR marks the out of date types as deprecated in favour of the one that are up to date.

chore(types): Deprecate old jwt types

---

.changeset/five-hounds-judge.md
packages/clerk-js/src/ui/components/PricingTable/PlanCard.tsx
packages/clerk-js/src/ui/customizables/elementDescriptors.ts
packages/types/src/appearance.ts

refactor(clerk-js,types): Simplify plan card avatar badge container styling

---

.changeset/eight-paws-add.md
packages/expo/src/provider/singleton/createClerkInstance.ts

Adds a console error message on Expo app if the Native API toggle is disabled on Clerk Dashboard.
Screenshot:

fix(clerk-expo): Add console error for disabled Native API

---

renovate.json5
scripts/renovate-config-generator.mjs

Making all ESLint packages part of the same dependency upgrade group

fix(repo): Group typescript-eslint with other linting upgrades

---

.changeset/tough-nails-explain.md
packages/clerk-js/src/ui/elements/Drawer.tsx
packages/clerk-js/src/ui/foundations/sizes.ts
packages/clerk-js/src/ui/foundations/transitions.ts

Dial in the `<Drawer/>` animations.
BEFORE:
https://github.com/user-attachments/assets/d0a6b3ea-51ca-4d7a-b9f2-d3dfcd28a88d
AFTER:
https://github.com/user-attachments/assets/1640d28d-00af-4588-a6a7-a49099ee09c9

refactor(clerk-js): `<Drawer />` animation timing/easing adjustments

---

.changeset/forty-ladybugs-tie.md
packages/clerk-js/bundlewatch.config.json
packages/clerk-js/src/ui/components/PricingTable/PlanDetailDrawer.tsx
packages/clerk-js/src/ui/customizables/elementDescriptors.ts
packages/clerk-js/src/ui/elements/Drawer.tsx
packages/types/src/appearance.ts

Introduce `<Drawer.Confirmation />` component to be used within Commerce cancel subscription flow.
https://github.com/user-attachments/assets/759cfb4e-7260-40f9-9ffc-5ee25fcda098
Resolves COM-148

refactor(clerk-js): Introduce `<Drawer.Confirmation />` component

---

.changeset/calm-files-confess.md
packages/backend/src/api/resources/Enums.ts

Adds status `expired` to `InvitationStatus`
I'm receiving this status on the API but the typings are missing it

fix(backend): Missing invitation status `expired`

---

.changeset/fast-rocks-repeat.md
packages/clerk-js/src/ui/elements/Drawer.tsx

Default `<Drawer.Confirmation />` to `alertdialog` role.

refactor(clerk-js): Default `<Drawer.Confirmation />` to `alertdialog` role

---

.changeset/chilled-garlics-knock.md
packages/clerk-js/src/ui/components/Checkout/Checkout.tsx
packages/clerk-js/src/ui/components/Checkout/CheckoutComplete.tsx
packages/clerk-js/src/ui/components/Checkout/CheckoutForm.tsx
packages/clerk-js/src/ui/components/PricingTable/PlanCard.tsx
packages/clerk-js/src/ui/elements/Disclosure.tsx
packages/clerk-js/src/ui/elements/Drawer.tsx
packages/clerk-js/src/ui/elements/LineItems.tsx
packages/clerk-js/src/ui/elements/SegmentedControl.tsx

Add support for passing localizationKeys into the new commerce related components.
Localization keys will be added in a future PR, this is just to support passing localization keys to the components.

refactor(clerk-js): Add localization support to commerce components

---

.changeset/fresh-plums-run.md
packages/clerk-js/src/core/clerk.ts
packages/clerk-js/src/core/resources/OrganizationSettings.ts
packages/clerk-js/src/core/resources/__tests__/Environment.test.ts
packages/clerk-js/src/core/resources/__tests__/__snapshots__/Environment.test.ts.snap
packages/clerk-js/src/ui/components/OrganizationList/__tests__/OrganizationList.test.tsx
packages/clerk-js/src/ui/components/OrganizationSwitcher/__tests__/OrganizationSwitcher.test.tsx
packages/clerk-js/src/ui/components/SessionTask/SessionTask.tsx
packages/clerk-js/src/ui/contexts/components/OrganizationList.ts
packages/clerk-js/src/ui/contexts/components/OrganizationSwitcher.ts
packages/clerk-js/src/ui/utils/test/fixtureHelpers.ts
packages/clerk-js/src/ui/utils/test/fixtures.ts
packages/types/src/organizationSettings.ts

Resolves ORGS-537
Introduces `force_organization_selection` on environment settings. When enabled, all organization components should hide the "personal workspace" options. 
This is also important for the after-auth flow with `force_organization_selection`, to avoid displaying the option to select a personal account on `OrganizationList`, and to also not display "Personal Workspace" on `OrganizationSwitcher`

chore(clerk-js,types): Hide personal workspace options when organization selection is enforced

---

.changeset/ninety-bugs-jam.md
packages/backend/src/tokens/__tests__/request.test.ts
packages/backend/src/tokens/authenticateContext.ts
packages/nextjs/src/server/clerkMiddleware.ts

Handle cases where we get Authorization header with basic auth, like `Basic ....` instead of `Bearer ....`
Right now we would throw an error since we assume any authorization header contains a `Bearer` token.
Also switched from `.replace` to `.slice` for perf since we know the string will begin with `Basic ` or `Bearer ` 
Fixes: SDKI-896

fix(backend): Handle Basic auth gracefully

---

.changeset/config.json

This PR is a follow up to #5327, so we don't publish any new versions until #5394

chore(repo): Add `@clerk/tanstack-start` to changesets ignored packages

---

integration/tests/vue/components.test.ts

Small PR that fixes [this failing job](https://github.com/clerk/javascript/actions/runs/13954215106/job/39061170565?pr=5399).

test(vue): Get exact selector when testing Organization Profile custom pages and links

---

.typedoc/custom-theme.mjs

By default the Typedoc markdown plugin returns a union in such a format:
```md
`foo` | `bar`
`foo` | [`Foo`](bar)
```
We want to have it instead like this:
```md
`foo | bar`
`foo | [Foo](bar)`
```
Fixes https://linear.app/clerk/issue/ECO-519/wrap-union-types-in-one-code-block

chore(repo): Modify Typedoc union type output

---

.changeset/late-cheetahs-raise.md
packages/clerk-js/src/index.browser.ts
packages/clerk-js/src/index.headless.browser.ts

In scenarios where the clerk-js script is injected multiple times, it's possible that `window.Clerk` can be re-assigned while Clerk is loading, causing Clerk to get stuck in a state where it never gets marked as "loaded". Adding this check ensures that even if the script is re-injected, we don't re-assign the original `window.Clerk`.

fix(clerk-js): Ensure window.Clerk is only ever assigned once

---

.changeset/purple-balloons-join.md
integration/testUtils/index.ts
integration/testUtils/organizationsService.ts
integration/testUtils/sessionTaskPageObject.ts
integration/tests/session-tasks-sign-in.test.ts
integration/tests/session-tasks-sign-up.test.ts
packages/clerk-js/bundlewatch.config.json
packages/clerk-js/src/core/__tests__/clerk.test.ts
packages/clerk-js/src/core/clerk.ts
packages/clerk-js/src/core/sessionTasks.ts
packages/clerk-js/src/ui/components/OrganizationList/OrganizationListPage.tsx
packages/clerk-js/src/ui/components/OrganizationList/UserMembershipList.tsx
packages/clerk-js/src/ui/components/SessionTask/SessionTask.tsx
packages/clerk-js/src/ui/components/SignIn/SignIn.tsx
packages/clerk-js/src/ui/components/SignUp/SignUp.tsx
packages/clerk-js/src/ui/contexts/components/SessionTask.ts
packages/clerk-js/src/ui/types.ts
packages/clerk-js/src/utils/beforeUnloadTracker.ts
packages/react/src/isomorphicClerk.ts
packages/types/src/clerk.ts

Resolves ORGS-581
Handles navigation to next tasks on an after-auth flow. Once all tasks get completed, it navigates to the `redirectUrlComplete` option, which defaults to after sign-in/sign-up URL based on the `Clerk.client` state. 
For AIO components, there's no signature changes and it'll work out of the box 
For custom flows, `Clerk.nextTask` should be called after performing a FAPI mutation that resolves a task. Here's an example for the upcoming force MFA task:
```ts 
await fapiClient.configureTotp(...) 
await Clerk.__experimental_nextTask()
```
Building your on custom React "onboarding" components: 
```tsx
function MyFirstOnboardingPage(){ 
const clerk = useClerk()
const handleOrganizationSelection = async (organization: string) => {
// Select the organization into the current …
```

feat(clerk-js,clerk-react,types): Navigate to next task

---

.changeset/pretty-months-wonder.md
.changeset/tricky-deers-know.md
integration/templates/next-app-router/src/app/(reverification)/action-with-use-reverification/page.tsx
integration/tests/reverification.test.ts
packages/clerk-js/bundlewatch.config.json
packages/clerk-js/src/ui/common/RemoveResourceForm.tsx
packages/clerk-js/src/ui/components/UserProfile/ActiveDevicesSection.tsx
packages/clerk-js/src/ui/components/UserProfile/AddAuthenticatorApp.tsx
packages/clerk-js/src/ui/components/UserProfile/ConnectedAccountsMenu.tsx
packages/clerk-js/src/ui/components/UserProfile/ConnectedAccountsSection.tsx
packages/clerk-js/src/ui/components/UserProfile/DeleteUserForm.tsx
packages/clerk-js/src/ui/components/UserProfile/EmailForm.tsx
packages/clerk-js/src/ui/components/UserProfile/EmailsSection.tsx
packages/clerk-js/src/ui/components/UserProfile/MfaBackupCodeCreateForm.tsx
packages/clerk-js/src/ui/components/UserProfile/MfaPhoneCodeScreen.tsx
packages/clerk-js/src/ui/components/UserProfile/PasskeySection.tsx
packages/clerk-js/src/ui/components/UserProfile/PasswordForm.tsx
packages/clerk-js/src/ui/components/UserProfile/PhoneForm.tsx
packages/clerk-js/src/ui/components/UserProfile/UsernameForm.tsx
packages/clerk-js/src/ui/components/UserProfile/Web3Form.tsx
packages/clerk-js/src/ui/components/UserProfile/Web3Section.tsx
packages/nextjs/src/client-boundary/hooks.ts
packages/nextjs/src/errors.ts
packages/react-router/src/errors.ts
packages/react/src/errors.ts
packages/remix/src/errors.ts
packages/shared/src/error.ts
packages/shared/src/react/__tests__/useReverification.test.ts
packages/shared/src/react/hooks/useReverification.ts
packages/tanstack-start/src/errors.ts

This PR refactors `useReverification` to allow it to be used both for AIO and custom UI's.
This refactor will introduce breaking changes to `useReverification` as now it will not return an array but instead will return the fetcher, an also the `throwOnCancel` and `onCancel` options are dropped and all errors even canceling will be thrown.
```tsx
import { useReverification } from '@clerk/clerk-react'
import { isReverificationCancelledError } from '@clerk/clerk-react/errors'
export function MyButton() {
const enhancedFetcher = useReverification(() => fetch('/api/fetcher'))
const handleClick = async () => {
try {
const myData = await enhancedFetcher()
} catch (e) {
// Handle if user cancels the reverification process
if (isReverificationCancelledError(e)) {
console.error('User cancelled …
```

feat(clerk-js,shared): Refactor useReverification to support custom UIs

---

.changeset/small-ads-rescue.md
integration/tests/resiliency.test.ts
packages/clerk-js/src/core/clerk.ts

Update the resiliency logic for failed client attempts to allow the creation of a dev browser.

fix(clerk-js): Create client from jwt only on network errors or 5xx

---

.changeset/breezy-walls-tease.md
packages/clerk-js/bundlewatch.config.json
packages/clerk-js/src/ui/components/UserProfile/UserProfileRoutes.tsx

Lazy load BillingPage only when commerce is enabled, to avoid unnecessary loading of Stripe.

fix(clerk-js): Lazily load BillingPage in UserProfile

---

.changeset/clever-walls-shave.md
.changeset/spicy-radios-happen.md
packages/backend/src/createRedirect.ts
packages/shared/src/__tests__/buildAccountsBaseUrl.test.ts
packages/shared/src/buildAccountsBaseUrl.ts

This PR moves the `buildAccountsBaseUrl` logic into a shared utility function within the `@clerk/shared` package so it can be reused between both `@clerk/backend` (included in this PR) and `clerk-js` (to be used in the upcoming auth with popup PR.

feat(backend,shared): Move buildAccountsBaseUrl to shared utility

---

.changeset/stale-boxes-attend.md
packages/clerk-js/bundlewatch.config.json
packages/clerk-js/src/ui/components/SignUp/SignUpStart.tsx

This PR introduces a change in the behavior introduced in #4720
Currently, we may end up rate-limited on phone number verification codes.
This PR addresses runs the `signUp.create` only when there is no ticket flow.
For all the other cases, we keep using `signUp.upsert` in order to not lose the ticket context.

fix(clerk-js): Use a new signUp attempt on SignUpStart component when there is no ticket flow

---

.changeset/sad-feet-fail.md
packages/clerk-js/src/ui/components/PricingTable/PricingTableMatrix.tsx

Fixes issue where scrollable content was visible underneath the sticky header.

fix(clerk-js): Add background color to `<PricingTableMatrix />` component

---

.changeset/stale-students-care.md
packages/nextjs/package.json

For more details, please see https://github.com/advisories/GHSA-f82v-jwr5-mffw

fix(nextjs): Update peerDependencies to only allow patched versions

---

.changeset/common-melons-camp.md
packages/clerk-js/src/ui/components/UserProfile/UserProfileRoutes.tsx

Quick fix to move the lazily-loaded `BillingPage` out of the component body to prevent re-renders.

fix(clerk-js): Fix lazy-loading of `BillingPage` within `UserProfile`

---

.changeset/cool-suits-sell.md
packages/backend/src/api/endpoints/OrganizationApi.ts

Follows up from https://github.com/clerk/clerk_go/pull/7916 - `RevokeOrganizationInvitationParams.requestUserId` got updated to a optional param a couple of months ago but it wasn't updated in the `@clerk/backend` types

fix(backend): Update `RevokeOrganizationInvitationParams.requestUserId` param to optional

---

.github/actions/init-blacksmith/action.yml
.github/actions/init/action.yml
.github/workflows/release-canary.yml

Addressing upcoming turborepo breaking change: ` WARNING  TURBO_REMOTE_ONLY is deprecated and will be removed in a future major version. Use TURBO_CACHE=remote:rw`

chore(repo): Do not use deprecated Turbo env var

---

.changeset/polite-pillows-report.md
packages/shared/src/react/hooks/useReverification.ts

This PR removes the beta warning from `useReverification` hook

chore(shared): Remove the beta warning comment from useReverification hook

---

.changeset/tame-clowns-brush.md
packages/clerk-js/src/ui/components/UserVerification/__tests__/UVFactorOne.test.tsx
packages/localizations/src/bg-BG.ts
packages/localizations/src/en-GB.ts
packages/localizations/src/en-US.ts

This PR changes the password re-verification flow description to define that you need to enter the current password

fix(localizations): Define that you have to enter the current password

---

.changeset/modern-rings-relax.md
packages/nuxt/src/global.d.ts
packages/nuxt/src/module.ts
packages/nuxt/src/runtime/plugin.ts
packages/vue/src/index.ts
packages/vue/src/plugin.ts

Small PR that makes Vue Clerk plugin installation type-safe
https://github.com/user-attachments/assets/d1295443-ee4e-4765-9c12-42b399ef61c8
Resolves ECO-518

chore(vue): Make plugin installation type-safe

---

.changeset/thick-rooms-repeat.md
packages/expo-passkeys/package.json
packages/expo-passkeys/src/ClerkExpoPasskeysModule.ts
pnpm-lock.yaml

Removed `expo-modules-core` from dependencies in favor of `expo` as a peer dependency to allow broader compatibility with Expo SDK versions `^50 || ^51 || ^52`.
The [Expo module template](https://github.com/expo/expo/blob/main/packages/expo-module-template/src/%7B%25-%20project.moduleName%20%25%7D.ts) also imports functions directly from the `expo` module instead of the `expo-modules-core` package, which is meant to be used internally.

chore(expo-passkeys): Use Expo bundled version

---

.changeset/smart-chefs-fail.md
packages/clerk-js/src/ui/elements/CaptchaElement.tsx

Fixes the following Turnstile console warning:
```
[Cloudflare Turnstile] Language en-US is not supported, falling back to: en-us.
```
It was already falling back to the correct language, e.g. falling back to `es-es` if `es-ES` was passed.
However it expects the language code to be in lowercase.
Supported values here: https://developers.cloudflare.com/turnstile/reference/supported-languages/

fix(clerk-js): Fix Turnstile console warning when locale is used

---

.changeset/cool-houses-bake.md
packages/nextjs/src/server/clerkMiddleware.ts

Addressing outstanding TS issue in clerkMiddleware

fix(nextjs): Update clerkMiddleware type

---

.changeset/poor-lights-look.md
packages/clerk-js/src/ui/components/SignIn/SignInFactorOneCodeForm.tsx

This PR fixes a bug where the prepare first factor wasn't triggered after signing out and tried to use the same identified and strategy to sign in again.
This was a cache issue and the cache key was identical as it was just the factor, the difference was that this was a different sign in

fix(clerk-js): Using the same identifier and strategy not triggers prepare after sign out

---

.changeset/fair-ants-invent.md
packages/backend/src/api/__tests__/factory.test.ts
packages/backend/src/api/request.ts
packages/clerk-js/bundlewatch.config.json
packages/clerk-js/src/core/resources/Base.ts
packages/clerk-js/src/core/resources/__tests__/Base.test.ts
packages/shared/src/error.ts

This PR exposes the `Retry-After` header on the `retryAfter` property of `ClerkAPIResponseError`. This is to allow developers to catch the error and know how long they should wait to retry the request.

feat(clerk-js,backend,shared): Expose retryAfter header on ClerkAPIResponseError

---

.github/workflows/nightly-checks.yml

Addresses issue from our nightly runs: https://github.com/clerk/javascript/actions/runs/14165884118/job/39678911621

fix(repo): Unblock nightly nextjs integration tests

---

.github/workflows/nightly-checks.yml

Addressing jobs timing out in CI

fix(repo): Extending timeout for nightly-checks action

---

.github/workflows/nightly-checks.yml

Extending the timeout for the nightly checks job. Also upgraded react to 19.1.0

fix(repo): Updating the timeout for nightly-checks job

---

.changeset/spotty-schools-juggle.md
packages/astro/src/server/clerk-middleware.ts
packages/nextjs/src/server/clerkMiddleware.ts
packages/nuxt/src/runtime/server/clerkMiddleware.ts

Removes the `METHOD_CALLED` telemetry event from `clerkMiddleware()` as it's being fired more than intended. We can revisit in the future, but due to the reliance on the async `clerkClient()`, we can't just move it back to the middleware factory method.

chore(nextjs): Remove telemetry event from `clerkMiddleware()`

---

.changeset/old-roses-wave.md
packages/clerk-js/src/ui/utils/originPrefersPopup.ts

Adds v0's preview domain (`vusercontent.net`) to the list of domains where we prefer the popup oauth flow.

chore(clerk-js): Add v0 preview domain to popup preferred list

---

.changeset/tall-needles-drive.md
packages/clerk-js/src/ui/elements/Card/CardClerkAndPagesTag.tsx

chore(clerk-js): Update secured by clerk link URL

---

.changeset/chatty-loops-watch.md
integration/templates/nuxt-node/server/api/me.js
packages/nuxt/src/module.ts
packages/nuxt/src/runtime/server/__tests__/clerkMiddleware.test.ts
packages/nuxt/src/runtime/server/clerkMiddleware.ts
packages/nuxt/src/runtime/server/getAuth.ts

Resolves ORGS-622
Deprecate `event.context.auth` in favor of `event.context.auth()`: 
```diff
export default clerkMiddleware((event) => {
+ const { userId } = event.context.auth()
- const { userId } = event.context.auth
const isAdminRoute = event.path.startsWith('/api/admin')
if (!userId && isAdminRoute) {
throw createError({
statusCode: 401,
statusMessage: 'Unauthorized: User not signed in',
})
}
})
```
This change is needed for an upcoming feature in which options are passed to auth: `auth({ treatPendingAsSignedOn })`

chore(nuxt): Expose `event.context.auth()` as function

---

.changeset/new-showers-appear.md
packages/clerk-js/src/core/clerk.ts
packages/types/src/clerk.ts
packages/types/src/session.ts

Part of ORGS-621
`Clerk.isSignedIn` will return `false` by default if the `Clerk.session.status === pending`. This will make it easier for custom flows migration when force-an-org gets enabled by default on a instance: 
```js
const clerk = new Clerk(pubKey)
await clerk.load()
// Only mounts UI that relies on the user object, if the session switches to 'active'
if (clerk.isSignedIn) {
clerk.mountUserButton(userbuttonDiv)
} else {
// ......
}
```

chore(clerk-js,types): Handle pending sessions as signed-out in `isSignedIn` for custom flows

---

.changeset/major-spoons-fold.md
packages/backend/src/tokens/authObjects.ts
packages/clerk-js/src/core/jwt-client.ts
packages/clerk-js/src/utils/__tests__/jwt.test.ts
packages/types/src/jwtv2.ts

This PR does some groundwork to allow versioning the JWT token, the changes are mostly type changes that are adding the base session claims that are shared between versions and also allows the ability to add claims only for specific versions.
This also adds a "generator" function that will generate the properties returned/used in `signedInAuthObject` based on the JWT version, this will allow to keep backward compatibility between the old `org_permissions` claim and the new one that will need decoding in order to be backwards compatible.

feat(backend,clerk-js,types): JWT versioning

---

.changeset/common-teams-do.md
.changeset/early-boats-help.md
.changeset/modern-paws-mate.md
packages/astro/src/env.d.ts
packages/astro/src/integration/create-integration.ts
packages/astro/src/react/hooks.ts
packages/nextjs/src/client-boundary/PromisifiedAuthProvider.tsx
packages/react/src/hooks/__tests__/useAuth.test.tsx
packages/react/src/hooks/__tests__/useAuth.type.test.ts
packages/react/src/hooks/useAuth.ts
packages/react/src/isomorphicClerk.ts
packages/shared/src/authorization.ts
packages/vue/src/composables/useAuth.ts
packages/vue/src/plugin.ts
packages/vue/src/types.ts

Part of ORGS-621 
Allows to pass `treatPendingAsSignedOut` as an option to `useAuth` - refer to the following behavior when a session has a pending status:
```ts
// userId is undefined, since pending is treat as signed-out state (default behavior)
const { userId } = useAuth() 
// userId is defined, since pending is treat as signed-out state (opt-in behavior)
const { userId } = useAuth({ treatPendingAsSignedOut: true })
```
Globally changing the default: 
```tsx
<ClerkProvider treatPendingAsSignedOut={false} />
```
--- 
Example from Nuxt route middleware: 
```ts
const isProtectedRoute = createRouteMatcher(['/dashboard(.*)', '/forum(.*)'])
export default defineNuxtRouteMiddleware((to) => {
const { userId } = useAuth()
// If the user has a pending session, they aren't allowed to access
// …
```

chore(shared,vue,nextjs,astro,clerk-react): Update `useAuth` to handle pending session as signed-out

---

.changeset/big-chairs-smile.md
packages/clerk-js/src/ui/components/Checkout/CheckoutForm.tsx
packages/clerk-js/src/ui/components/PaymentSources/AddPaymentSource.tsx

Adds support for Apple Pay to `AddPaymentSource` component, and removes the unusable "collapsed" state.

feat(clerk-js): Add commerce support for Apple Pay

---

.changeset/salty-zebras-matter.md
packages/clerk-js/src/core/__tests__/clerk.test.ts
packages/clerk-js/src/core/clerk.ts

- Do not trigger navigation to tasks on `setActive` if it's called from outside UI components 
- Do not delay emitting state, this was a wrong workaround to avoid UI updating on session updates, eg: `SignIn` rendered inside `SignedOut`, which got fixed now that `SignedOut` treats pending sessions as signed out by default https://github.com/clerk/javascript/pull/5512
```ts
await setActive({ session })
const task = clerk.currentTask; 
mountTaskComponentIfAny(task)
```
Or use `clerk.__experimental_nextTask` for orchestrating navigation:
```ts
await setActive({ session })
await clerk.__experimental_nextTask({ redirectUrlComplete: afterTasksUrl })
```

chore(clerk-js): Trigger navigation to tasks on `setActive` for internal routing only 

---

.changeset/lucky-emus-share.md
packages/clerk-js/src/ui/hooks/useFetch.ts

Currently, `useFetch` caches data using only a string-ified version of the params as a key, which very easily leads to cache collisions.
This adds an optional `resourceId` param that is used in conjunction with the params to create the cache key. This is optional and not breaking.

fix(clerk-js): Add optional `resourceId` to `useFetch` hook

---

.changeset/smart-pianos-know.md
packages/types/src/jwtv2.ts

This PR marks the new session claim `ver` as experimental

chore(types): Mark `ver` claim as experimental

---

.changeset/long-toys-boil.md
packages/localizations/src/es-MX.ts

Just added the waitlist strings for es-MX.

feat(localizations): Add waitlist values for es-MX

---

.changeset/new-plants-lick.md
packages/clerk-js/src/core/clerk.ts
packages/clerk-js/src/ui/components/SignIn/SignInSocialButtons.tsx
packages/types/src/clerk.ts

In this pr we're handling the redirect to `two-factor` when user try to login with web3 and has enabled the `Multi-factor authentication`
https://github.com/user-attachments/assets/07f2ab5b-ca62-4da5-a0b1-9a7324aea80d
https://github.com/user-attachments/assets/5b05234c-6499-4a0f-bc09-849d175a8202

fix(clerk-js): Handle two factor redirect when authenticate with web3

---

.github/workflows/ci.yml

https://github.com/vercel/next.js/releases/tag/v14.2.28 was released, so we can revert the pin done in https://github.com/clerk/javascript/pull/5558

chore(e2e): Remove Next.js 14 pin

---

.changeset/deep-moose-slide.md
packages/astro/src/react/hooks.ts

1. Fixes the issue in the screenshot.
2. Uses an updated `useStore` in order for authContext to not merge with `clerkContext`.

fix(astro): Construct derived state when als is empty

---

integration/presets/longRunningApps.ts
integration/tests/oauth-flows.test.ts

This PR adds tests for sign in transferred to sign up on an instance with legal consent required, both via the mounted component and via the modal.

test(e2e): Add tests for transfer sign up with legal consent

---

.github/workflows/release.yml

We want to get https://github.com/clerk/generated-typedoc/ updated once a new release is out (so that documentation only gets updated once it's live). The repository has a GitHub action (https://github.com/clerk/generated-typedoc/blob/main/.github/workflows/update-docs.yml) to update its contents through a PR.
This PR adds a trigger for this workflow once the release has happened.

chore(repo): Notify generated-typedoc of new release

---

.changeset/fine-ducks-love.md
packages/elements/package.json
packages/elements/src/internals/machines/sign-in/router.types.ts
packages/elements/src/internals/machines/sign-in/verification.machine.ts
packages/elements/src/internals/machines/sign-up/continue.machine.ts
packages/elements/src/internals/machines/sign-up/router.types.ts
packages/elements/src/internals/machines/sign-up/verification.machine.ts
packages/elements/src/internals/utils/inspector/console/console.ts
packages/elements/src/react/hooks/use-active-states.hook.ts
packages/elements/src/react/hooks/use-active-tags.hook.ts
packages/elements/src/react/sign-in/context/router.context.ts
packages/elements/src/react/sign-up/context/router.context.ts
pnpm-lock.yaml

Upgrading `xstate` and `@xstate/react` to allow for react@19 as a peer dep.
https://github.com/statelyai/xstate/blob/main/packages/xstate-react/CHANGELOG.md#500
Fixes: SDK-2101

feat(elements): Upgrade xstate and @xstate/react

---

.changeset/new-peas-win.md
packages/localizations/src/en-GB.ts
packages/localizations/src/en-US.ts

fix(localizations): Improve the CAPTCHA error message to better assist users

---

.changeset/old-breads-check.md
packages/shared/src/__tests__/jwtPayloadParser.test.ts
packages/shared/src/jwtPayloadParser.ts

This PR fixes an issue with feature parsing in the new JWT schema

chore(shared): Fix JWT v2 feature parsing

---

.changeset/open-papers-cross.md
packages/clerk-js/rspack.config.js
packages/clerk-js/src/ui/components/PaymentSources/AddPaymentSource.tsx
scripts/search-for-rhc.mjs

Ensure Stripe dependencies aren't bundled/chunked for non-RHC environments
ECO-595

fix(clerk-js,chrome-extension): Externalize StripeJS (Non-RHC only)

---

.changeset/thin-foxes-exist.md
packages/backend/src/api/endpoints/UserApi.ts
packages/backend/src/api/resources/JSON.ts
packages/backend/src/api/resources/OrganizationInvitation.ts

Adds the following User-centric functionality to the Backend API client.
```ts
import { createClerkClient } from '@clerk/backend';
const clerkClient = createClerkClient(...);
await clerkClient.users.getOrganizationInvitationList({
userId: 'user_xxxxxx',
status: 'pending',
});
await clerkClient.users.deleteUserPasskey({
userId: 'user_xxxxxx',
passkeyIdentificationId: 'xxxxxxx',
});
await clerkClient.users.deleteUserWeb3Wallet({
userId: 'user_xxxxxx',
web3WalletIdentificationId: 'xxxxxxx',
});
await clerkClient.users.deleteUserExternalAccount({
userId: 'user_xxxxxx',
externalAccountId: 'xxxxxxx',
});
await clerkClient.users.deleteUserBackupCodes('user_xxxxxx');
await clerkClient.users.deleteUserTOTP('user_xxxxxx');
```
Fixes ECO-591

feat(backend): Adds user-centric functionality to Backend API client

---

.changeset/rich-jobs-serve.md
packages/backend/src/api/endpoints/SessionApi.ts

Adds `createSession` to the Sessions Backend API client.
ECO-589

feat(backend): Adds `createSession` to the Backend API client

---

.changeset/busy-ducks-strive.md
packages/backend/src/api/endpoints/UserApi.ts

Add support for `md5_phpass` and `ldap_ssha` hashers.

feat(backend): Add support for md5_phpass and ldap_ssha hashers

---

.changeset/open-cases-happen.md
.changeset/slick-taxis-cut.md
packages/chrome-extension/tsup.config.ts
packages/clerk-js/rspack.config.js
packages/clerk-js/src/ui/components/PaymentSources/AddPaymentSource.tsx
scripts/search-for-rhc.mjs

fix(clerk-js,chrome-extension): Stripe bundles

---

.changeset/violet-jobs-brush.md
packages/clerk-js/bundlewatch.config.json
packages/clerk-js/src/core/modules/commerce/CommerceBilling.ts
packages/clerk-js/src/core/resources/CommerceCheckout.ts
packages/clerk-js/src/ui/components/Checkout/CheckoutPage.tsx
packages/clerk-js/src/ui/hooks/useCheckout.ts

Invalidates cached checkout on Checkout drawer unmount.
Fixes https://linear.app/clerk/issue/COM-428/bug-need-to-invalidate-checkout-object-on-drawer-close

fix(clerk-js): Invalidate cached checkout

---

.changeset/grumpy-queens-make.md
packages/clerk-js/src/ui/components/CreateOrganization/CreateOrganizationForm.tsx

Ensure Organization slug contains at least one alphanumeric character
Fixes: SDKI-989

fix(clerk-js): Ensure Organization slug includes alphanumeric characters

---

.changeset/eight-wombats-hunt.md
packages/clerk-js/src/core/auth/CaptchaHeartbeat.ts
packages/clerk-js/src/core/fraudProtection.test.ts
packages/clerk-js/src/core/fraudProtection.ts
packages/clerk-js/src/core/resources/Client.ts
packages/clerk-js/src/core/resources/__tests__/Client.test.ts
packages/types/src/client.ts

Rename the `sendCaptchaToken` to `__internal_sendCaptchaToken` because it's not Public API.

fix(clerk-js): Rename the `sendCaptchaToken` to `__internal_sendCaptchaToken`

---

.changeset/clear-lights-talk.md
packages/clerk-js/bundlewatch.config.json
packages/clerk-js/src/core/clerk.ts
packages/clerk-js/src/core/resources/CommerceSettings.ts
packages/clerk-js/src/core/resources/__tests__/__snapshots__/Environment.test.ts.snap
packages/clerk-js/src/ui/components/OrganizationProfile/OrganizationProfileRoutes.tsx
packages/clerk-js/src/ui/components/PaymentSources/AddPaymentSource.tsx
packages/clerk-js/src/ui/components/UserProfile/UserProfileRoutes.tsx
packages/clerk-js/src/ui/utils/createCustomPages.tsx
packages/clerk-js/src/utils/componentGuards.ts
packages/types/src/commerceSettings.ts

chore(clerk-js): Nest existing commerce settings under `billing`

---

.changeset/silly-bats-open.md
packages/clerk-js/src/ui/elements/LineItems.tsx
packages/clerk-js/src/ui/utils/truncateTextWithEndVisible.ts

fix(clerk-js): Reduce line truncation maxLength

---

.changeset/fuzzy-chefs-change.md
packages/backend/src/api/endpoints/AllowlistIdentifierApi.ts
packages/backend/src/api/endpoints/BlocklistIdentifierApi.ts
packages/backend/src/api/endpoints/index.ts
packages/backend/src/api/factory.ts
packages/backend/src/api/resources/AllowlistIdentifier.ts
packages/backend/src/api/resources/BlocklistIdentifier.ts
packages/backend/src/api/resources/Deserializer.ts
packages/backend/src/api/resources/Enums.ts
packages/backend/src/api/resources/JSON.ts
packages/backend/src/api/resources/index.ts
packages/backend/src/index.ts

Adds the Blocklist Identifier endpoints to the Backend API client.
```ts
import { createClerkClient } from '@clerk/backend';
const clerkClient = createClerkClient(...);
await clerkClient.blocklistIdentifiers.getBlocklistIdentifierList();
await clerkClient.blocklistIdentifiers.createBlocklistIdentifier({ identifier });
await clerkClient.blocklistIdentifiers.deleteBlocklistIdentifier('blocklistIdentifierId');
```
Updates the ability paginate Allowlist Identifier reponses and access `identifierType` and `instanceId` from the response.
```ts
import { createClerkClient } from '@clerk/backend';
const clerkClient = createClerkClient(...);
const res = await clerkClient.blocklistIdentifiers.getAllowlistIdentifierList({ limit, offset });
```
ECO-580

feat(backend): Add Blocklist Identifiers to Backend API client

---

.changeset/tired-experts-dig.md
packages/localizations/src/de-DE.ts

Deleting an account is currently not possible, as the terms "Account löschen" is expected, although "Konto löschen" is requested to confirm. Details of the issue can be found in the linked issue. Note that this issue prevents Clerk from being GDPR compliant in Germany right now ⚠️.
Fixes https://github.com/clerk/javascript/issues/5623

fix(localizations): German "Delete account" confirmation

---

.changeset/thick-showers-drop.md
packages/backend/src/api/endpoints/WaitlistEntryApi.ts
packages/backend/src/api/endpoints/index.ts
packages/backend/src/api/factory.ts
packages/backend/src/api/resources/Deserializer.ts
packages/backend/src/api/resources/Enums.ts
packages/backend/src/api/resources/JSON.ts
packages/backend/src/api/resources/WaitlistEntry.ts
packages/backend/src/api/resources/index.ts

Manually adds `/waitlist_entry` endpoints to the Backend SDK API client.
Fixes ECO-592

feat(backend): Add Waitlist Entry endpoints to Backend API client

---

.changeset/solid-heads-turn.md
packages/backend/src/api/resources/Organization.ts

`Organization.slug` should never be `null`
Fixes ECO-600
Closes #5634

fix(backend): Update typing of Organization.slug

---

.changeset/cool-mugs-drop.md
packages/clerk-js/src/ui/contexts/components/Plans.tsx

Fix commerce plans call by adding default `payer_type`.

fix(clerk-js): Add `payer_type` param default to plans call

---

.changeset/red-rivers-call.md
packages/backend/src/api/resources/JSON.ts
packages/backend/src/api/resources/OauthAccessToken.ts

Include expiresAt in OauthAccessToken resource.
https://clerk.com/docs/reference/backend-api/tag/Users#operation/GetOAuthAccessToken!c=200&path=expires_at&t=response

feat(backend): Include expiresAt in OauthAccessToken resource

---

.changeset/cute-ghosts-decide.md
packages/backend/src/api/endpoints/InvitationApi.ts
packages/backend/src/api/resources/Enums.ts
packages/types/src/organizationInvitation.ts

Appends `expired` to invitation status types
Fixes ECO-604

fix(backend,types): Append `expired` status to invitation types

---

.changeset/cruel-baths-sleep.md
integration/tests/oauth-flows.test.ts
packages/clerk-js/bundlewatch.config.json
packages/clerk-js/src/ui/Components.tsx
packages/clerk-js/src/ui/components/SignIn/SignIn.tsx
packages/clerk-js/src/ui/contexts/components/SignIn.ts
packages/clerk-js/src/ui/contexts/components/SignUp.ts
packages/clerk-js/src/ui/types.ts
packages/clerk-js/src/utils/disambiguateRedirectOptions.ts

Fixes an issue where `fallbackRedirectUrl` and `forceRedirectUrl` passed to a specific flow would be improperly passed to the other flow in a modal case.
Example:
```
Clerk.openSignUp({ forceRedirectUrl: '/?form=signup' }) // would apply to sign ins if user clicks sign in in the footer
```

fix(clerk-js): Disambiguate redirect url options between flows

---

.changeset/free-crews-sin.md
packages/nextjs/src/server/__tests__/content-security-policy.test.ts
packages/nextjs/src/server/clerkMiddleware.ts
packages/nextjs/src/server/content-security-policy.ts

We are going to adjust the CSP configuration option from `mode` to boolean `strict`
Fixes: SDKI-995

feat(nextjs): Use strict param in CSP generation

---

.changeset/wild-cases-wash.md
packages/nextjs/src/server/clerkMiddleware.ts

Defaulting `strict` to false and making it optional so it does not need to be specified

fix(nextjs): Make strict CSP param optional and default to false

---

.changeset/eighty-suns-argue.md
packages/clerk-js/src/ui/elements/Header.tsx
packages/clerk-js/src/ui/primitives/Dd.tsx
packages/clerk-js/src/ui/primitives/Dl.tsx
packages/clerk-js/src/ui/primitives/Dt.tsx

| ![Screenshot 2025-04-16 at 5 43 48 PM](https://github.com/user-attachments/assets/db812a73-c8a2-475a-ad87-fe4616833cb7) | ![Screenshot 2025-04-16 at 5 45 17 PM](https://github.com/user-attachments/assets/b1f27c27-5390-4b88-9a45-3f8de507c4e4) | 
Fixes COM-481

fix(clerk-js): Reset definition list components margins

---

.changeset/rude-mirrors-jog.md
packages/clerk-js/src/ui/components/Checkout/CheckoutForm.tsx
packages/clerk-js/src/ui/components/PricingTable/SubscriptionDetailDrawer.tsx

Ensure we are properly catching and displaying checkout form errors. Also makes `SubscriptionDetailDrawer` badging style match the plan card badging.

chore(clerk-js): Improve checkout error handling

---

.changeset/dirty-ads-heal.md
packages/localizations/src/es-MX.ts

Form email and password inputs spanish texts

chore(localizations): Update `es-MX` translations

---

integration/testUtils/usersService.ts
integration/tests/oauth-flows.test.ts

Adds a new `ensureBapiUserExists` for e2e tests that need to ensure the suer exists, but don't care if they're created or already exist.

feat(e2e): Add ensureBapiUserExists method

---

.changeset/eight-friends-fail.md
packages/clerk-js/src/ui/lazyModules/providers.tsx

Moves the `Suspense` boundary to only wrap the lazily loaded children in `LazyDrawerRenderer` – otherwise it was causing a double-mount that was triggering `useCheckout` twice, creating duplicate checkout API calls.

fix(clerk-js): Fix duplicate checkout calls

---

integration/tests/resiliency.test.ts

debugging the test failures in https://github.com/clerk/javascript/pull/5668 but skipping the test for now

chore(repo): Skip flaky test

---

.changeset/mean-impalas-reply.md
packages/clerk-js/src/ui/lazyModules/providers.tsx

Fixes inconsistent issue with mounting Checkout drawer by rolling back the Suspense wrapper placement change.

fix(clerk-js): Rollback drawer suspense change

---

.changeset/fruity-areas-train.md
integration/testUtils/index.ts
integration/tests/non-secure-context.test.ts
integration/tests/resiliency.test.ts
integration/tests/reverification.test.ts
packages/testing/src/playwright/helpers.ts
packages/testing/src/playwright/setupClerkTestingToken.ts
pnpm-lock.yaml

Switching over our interception of FAPI calls from `page.route` to `context.route` as routes set up with [page.route()](https://playwright.dev/docs/api/class-page#page-route) take precedence over browser context routes when request matches both handlers.
This allows for consumers to use `page.route` to override calls to FAPI consistently. 
Related: https://github.com/clerk/javascript/pull/5672

fix(testing): Better route interception hierarchy

---

.changeset/curly-candles-dance.md
packages/localizations/src/en-GB.ts
packages/localizations/src/en-US.ts

This updates the `not_allowed_access` error code localization to account for all possible error cases:
- Disposable Emails
- Email Sub-addresses
- Allowlist/Blocklist
Fixes ECO-614

chore(localizations): Account for all possible cases from `not_allowed_access` error codes

---

.changeset/icy-lemons-fall.md
packages/clerk-js/src/ui/components/OrganizationProfile/OrganizationBillingPage.tsx
packages/clerk-js/src/ui/components/OrganizationProfile/OrganizationProfileRoutes.tsx
packages/clerk-js/src/ui/components/Subscriptions/SubscriptionsList.tsx
packages/clerk-js/src/ui/components/UserProfile/BillingPage.tsx
packages/clerk-js/src/ui/components/UserProfile/UserProfileRoutes.tsx
packages/clerk-js/src/ui/contexts/components/Plans.tsx
packages/clerk-js/src/ui/hooks/useFetch.ts

This PR fixes:
1. the flash from "Plans" to "Subscriptions" when subscriptions load after the first render.
2. on cancel subscription revalidate the fetched subscriptions
3. on cancel subscription close the drawer
4. avoid conflicts when opening a drawer when some of the listed subscriptions are cancelled.
https://github.com/user-attachments/assets/12a75518-d9e6-49d5-b365-28ba5b3bf3ae

fix(clerk-js): Minor UI fixes for commerce

---

.changeset/shaky-crabs-show.md
packages/react/src/errors/messages.ts

There are error messages which pop-up when using `<UserButton.*>` stating that only specific components may be used as children. This error will also pop-up when the component tree is correct but is contained within a server component.
This PR is a quick-fix to add client component details to the error message in an effort to unblock developers who may find themselves in this state.
Fixes ECO-617

fix(clerk-react): Add details to `UserButton.*` error message

---

.changeset/cool-roses-scream.md
packages/backend/src/constants.ts
packages/nextjs/src/server/__tests__/content-security-policy.test.ts
packages/nextjs/src/server/clerkMiddleware.ts
packages/nextjs/src/server/content-security-policy.ts

Adding `reportTo` and `reportOnly` configuration options
Fixes: SDKI-1001

feat(nextjs): CSP reporting mode

---

.changeset/dull-peaches-camp.md
packages/clerk-js/src/ui/components/PaymentSources/PaymentSources.tsx

Using the same cache key allows for existing data to be displayed, improving unnecessary layout shifts.

fix(clerk-js): Use the same cache key for payment sources across checkout and profiles

---

.changeset/silver-symbols-worry.md
packages/clerk-js/src/ui/components/Checkout/CheckoutForm.tsx
packages/clerk-js/src/ui/components/PricingTable/PricingTable.tsx

- Fixes CLS issues when rendering account funds
- Renames "accounts funds" to "payment sources" for consistency
- Auto opes the "Add a new payment source" drawer only if no payments sources exist

fix(clerk-js): Incremental improvements for account funds

---

.changeset/fluffy-snails-sort.md
packages/clerk-js/src/ui/components/PaymentSources/AddPaymentSource.tsx

fix(clerk-js): Revalidate payment sources from  `<Checkout />`

---

.changeset/easy-zebras-wave.md
packages/clerk-js/src/ui/components/Subscriptions/SubscriptionDetails.tsx
packages/clerk-js/src/ui/contexts/components/Plans.tsx

https://github.com/user-attachments/assets/4ce90515-a501-4a93-9a75-b3a5866d0c65
https://github.com/user-attachments/assets/2faf604f-08d3-4d6d-9c3f-4800cc6f8bde

fix(clerk-js): Avoid laggy ui when closing drawer after canceling subscription

---

.changeset/tough-cameras-lie.md
packages/clerk-js/src/core/constants.ts
packages/clerk-js/src/ui/components/SignIn/SignInStart.tsx
packages/clerk-js/src/ui/components/SignUp/SignUpStart.tsx

Add support for the 2 new error codes on OAuth flows:
- `device_blocked`
- `action_blocked`
This affects the message that is being shown on the UI component.

fix(clerk-js): Add support for 2 new OAuth error codes

---

.changeset/clear-trains-rhyme.md
packages/clerk-js/src/ui/components/Subscriptions/SubscriptionsList.tsx
packages/clerk-js/src/ui/contexts/components/Plans.tsx

fix(clerk-js): Display "Switch to this plan" when a subscription already exists

---

.changeset/clean-doodles-thank.md
packages/clerk-js/src/ui/components/PricingTable/PricingTable.tsx
packages/clerk-js/src/ui/components/PricingTable/PricingTableDefault.tsx
packages/types/src/clerk.ts

`<PricingTable layout="matrix" />` is not ready for production use yet. Let's exclude it from the types so developers are not tempted to use it.

fix(clerk-js,types): Exclude matrix variant from the public api

---

.changeset/nine-pets-learn.md
packages/clerk-js/src/core/resources/CommerceCheckout.ts
packages/clerk-js/src/core/resources/CommerceInvoice.ts
packages/clerk-js/src/utils/commerce.ts
packages/types/src/commerce.ts
packages/types/src/json.ts

Split `CommerceTotals` to `CommerceCheckoutTotals` and `CommerceInvoiceTotals`

chore(clerk-js,types): Split shared `CommerceTotals`

---

.changeset/shy-chairs-speak.md
packages/clerk-js/src/core/clerk.ts
packages/clerk-js/src/core/warnings.ts

fix(clerk-js): Replace commerce with billing when components cannot render

---

.changeset/puny-dancers-worry.md
packages/clerk-js/src/ui/Components.tsx
packages/clerk-js/src/ui/lazyModules/MountedCheckoutDrawer.tsx
packages/clerk-js/src/ui/lazyModules/MountedSubscriptionDetailDrawer.tsx
packages/clerk-js/src/ui/lazyModules/drawers.tsx

https://github.com/user-attachments/assets/0c44a103-adba-4bf4-8ad3-9ce8f7b3445d
https://github.com/user-attachments/assets/d55cae13-1e86-415c-8c86-90a622a41244

fix(clerk-js): Force re-mount drawers on session switch

---

.changeset/soft-schools-bake.md
packages/clerk-js/sandbox/template.html
packages/clerk-js/src/core/resources/CommerceCheckout.ts

Adding retries when any errors with >=500 status code occur

feat(clerk-js): Add retry if 500 errors for confirmation checkout request

---

.changeset/breezy-hairs-smell.md
packages/clerk-js/bundlewatch.config.json
packages/clerk-js/src/ui/components/Checkout/CheckoutForm.tsx
packages/clerk-js/src/ui/components/PaymentSources/AddPaymentSource.tsx
packages/clerk-js/src/ui/components/PaymentSources/PaymentSources.tsx
packages/types/src/commerce.ts

This PR remove the additional request for adding payment source on checkout confirm as the checkout confirm can handle both new and old payment sources

feat(commerce): Checkout confirm request handles both new/existing payment sources

---

.changeset/clean-walls-invite.md
packages/clerk-js/src/utils/captcha/turnstile.ts

Fixes a layout shift caused by the addition of a div under the DOM body element.

fix(clerk-js): Fix layout shift caused by the invisible captcha mechanism

---

packages/backend/src/tokens/__tests__/handshake.test.ts
packages/backend/src/tokens/handshake.ts
packages/backend/src/tokens/request.ts

Refactoring Handshake related code to HandShake service

refactor(backend): Introduce HandshakeService

---

.changeset/rare-memes-count.md
packages/clerk-js/src/ui/components/Plans/PlanDetails.tsx
packages/clerk-js/src/ui/components/PricingTable/PricingTableDefault.tsx

Noticed some unintentional spacing within staging AP.
| ![Screenshot 2025-04-29 at 11 24 37 AM](https://github.com/user-attachments/assets/1fc7e74f-781d-4f4c-a5b8-1c04b92f8e77) | ![Screenshot 2025-04-29 at 11 24 58 AM](https://github.com/user-attachments/assets/a7da3014-5bff-4b9f-897a-44fd228754ee) | 
| ![Screenshot 2025-04-29 at 11 25 14 AM](https://github.com/user-attachments/assets/bb52e04e-aac2-4f0e-a871-2d2df112e1a4) | ![Screenshot 2025-04-29 at 11 25 35 AM](https://github.com/user-attachments/assets/f89cb3f1-a007-42fd-98ff-e27309078cd3) |

fix(clerk-js): Reset ul list styling within pricing table and plan details

---

.changeset/eighty-singers-poke.md
packages/clerk-js/rspack.config.js
packages/clerk-js/src/index.chips.browser.ts
packages/clerk-js/src/index.chips.ts

Correctly build the chips.browser variant. We were using clerk.js as a base, which is not a browser variant

fix(clerk-js): Correct chips entry point

---

.changeset/stale-waves-rhyme.md
packages/clerk-js/package.json
pnpm-lock.yaml

This updates https://github.com/zpao/qrcode.react from 3.1.0 to 4.2.0 as 4.2.0 includes React 19 as a peerDep. The changelog for 4.0.0 is at https://github.com/zpao/qrcode.react/blob/trunk/CHANGELOG.md#400---2024-08-27. The breaking changes don't affect us as we already used the named import and didn't use the `style` prop.
Fixes ECO-621
Fixes https://github.com/clerk/javascript/issues/5752

chore(clerk-js): Update qrcode.react to 4.2.0

---

.changeset/puny-pants-cough.md
packages/clerk-js/src/core/clerk.ts
packages/clerk-js/src/core/warnings.ts

fix(clerk-js): Throw error when opening `<Checkout />` without a session

---

.changeset/eighty-windows-grow.md
packages/clerk-js/src/core/resources/CommerceCheckout.ts

This PR adds the logic to retry the checkout confirmation request if there is another checkout already in progress

fix(clerk-js): Retry checkout confirm if there is another checkout already in progress

---

.changeset/hungry-foxes-sell.md
packages/clerk-js/src/core/auth/cookies/session.ts

Staying standards compliant, and forcing SameSite=none for partitioned cookies

fix(clerk-js): Force SameSite=none for chips

---

.changeset/clever-parts-build.md
packages/clerk-js/src/ui/components/PricingTable/PricingTable.tsx

| ![Screenshot 2025-04-30 at 5 41 16 PM](https://github.com/user-attachments/assets/235c9502-e978-4a8c-965c-2026bedfadce) | ![Screenshot 2025-04-30 at 5 40 39 PM](https://github.com/user-attachments/assets/f556b4c7-82f8-4b60-be58-d74ba1c02371) |

fix(clerk-js): Fix PricingTable spacing within profile components

---

.changeset/giant-owls-cut.md
packages/clerk-js/src/core/auth/cookies/__tests__/clientUat.test.ts
packages/clerk-js/src/core/auth/cookies/__tests__/session.test.ts
packages/clerk-js/src/core/auth/cookies/clientUat.ts

Looks like this was missed in the initial change to send the Partitioned attribute for the `__session` cookie

fix(clerk-js): Add Partitioned to __client_uat in CHIPS build

---

.changeset/fuzzy-donkeys-post.md
packages/clerk-js/sandbox/template.html
packages/clerk-js/src/ui/components/Checkout/CheckoutForm.tsx
packages/clerk-js/src/utils/commerce.ts
packages/types/src/commerce.ts

Use the `totals.proration.credit` for showing the proration credit in the checkout flows

fix(clerk-js): Use the credit amount from FAPI for credit proration checkout flow

---

.changeset/shaky-parents-type.md
packages/clerk-js/src/ui/components/Checkout/CheckoutComplete.tsx
packages/clerk-js/src/ui/components/Checkout/CheckoutForm.tsx
packages/clerk-js/src/utils/commerce.ts

This PR changes all the usages of `grand_total` with `total_due_now`

fix(clerk-js): User total due now in checkout flows instead of grand total

---

.changeset/mighty-years-learn.md
packages/clerk-js/src/ui/components/Checkout/CheckoutPage.tsx

Always revalidate checkout requests when checkout drawer opens in order to avoid having stale data when trying to change plan

fix(clerk-js): Always revalidate checkout checkout when drawer opens

---

.changeset/happy-radios-juggle.md
packages/clerk-js/src/core/__tests__/clerk.test.ts
packages/clerk-js/src/core/clerk.ts
packages/clerk-js/src/ui/components/SessionTasks/index.tsx
packages/react/src/isomorphicClerk.ts
packages/types/src/clerk.ts

Renames experimental method from `nextTask` to `navigateToTask` to make it more explict to the consumer that this logic triggers a navigation

chore(clerk-js): Rename `__experimental_nextTask` to `__experimental_navigateToTask`

---

packages/clerk-js/src/ui/components/Checkout/CheckoutPage.tsx
packages/clerk-js/src/ui/hooks/useCheckout.ts

Use localized or FAPI's long_message instead of the hardcoded value

fix(clerk-js): Improve error handling for unexpected errors in checkout process

---

.changeset/stupid-animals-taste.md
packages/clerk-js/src/ui/components/Checkout/CheckoutComplete.tsx
packages/clerk-js/src/ui/components/Checkout/CheckoutForm.tsx

Adjusts the layout and order of the checkout's line items. Also removes `Invoice ID` from the checkout complete page.
https://linear.app/clerk/issue/COM-726/remove-invoice-line-from-checkout-complete-page
https://linear.app/clerk/issue/COM-713/frontend-when-switching-to-an-annual-plan-display-the-annual-total

chore(clerk-js): Adjust the checkout line item rows

---

.changeset/cold-toes-rhyme.md
packages/expo-passkeys/package.json

This is a small PR adding support to [stable Expo 53](https://expo.dev/changelog/sdk-53). No breaking changes or new features were introduced.

chore(expo-passkeys): Add support for Expo 53

---

.changeset/purple-cities-study.md
packages/clerk-js/bundlewatch.config.json
packages/clerk-js/src/ui/components/Checkout/CheckoutComplete.tsx
packages/clerk-js/src/ui/components/Checkout/CheckoutForm.tsx
packages/clerk-js/src/ui/components/Checkout/CheckoutPage.tsx
packages/clerk-js/src/ui/elements/Drawer.tsx

Smooth out the transition from checking out to checkout complete state.
https://github.com/user-attachments/assets/3cb7af02-fb22-4c00-b74e-f3e9921a01db
SLOW-MO
https://github.com/user-attachments/assets/c292206b-f5b6-41cb-8dfd-42e1a9fe8304

feat(clerk-js): Add transition animations into checkout complete state

---

.changeset/eager-goats-vanish.md
packages/clerk-js/src/ui/components/Checkout/CheckoutComplete.tsx
packages/clerk-js/src/ui/components/Plans/PlanDetails.tsx
packages/clerk-js/src/ui/components/PricingTable/PricingTableDefault.tsx
packages/clerk-js/src/ui/contexts/components/Plans.tsx
packages/clerk-js/src/ui/customizables/elementDescriptors.ts
packages/types/src/appearance.ts

Allows downgrading to the free plan through a normal checkout downgrade flow. Badges and CTAs reflect the appropriate implicit states for the free plan card.
https://linear.app/clerk/issue/COM-725/support-checkout-flow-with-default-free-plan

feat(clerk-js,types): Support switching to free plan

---

.changeset/sad-teeth-argue.md
packages/clerk-js/src/ui/components/Plans/PlanDetails.tsx
packages/localizations/src/en-US.ts
packages/types/src/localization.ts

Adds the ability within `PlanDetails` to switch from an existing monthly subscription to an annual subscription for the same plan.
https://linear.app/clerk/issue/COM-686/add-ability-to-change-plan-period-for-existing-subscription

feat(clerk-js,localizations): Switching monthly to annual for existing subscription

---

.changeset/shiny-olives-worry.md
packages/clerk-js/src/ui/components/BlankCaptchaModal/index.tsx

Fixes the following warning message when captcha modal is triggered:
```
[Cloudflare Turnstile] Language en-US is not supported, falling back to: en-us.
```

fix(clerk-js): Fix turnstile language fallback warning on captcha modal

---

.changeset/tidy-pots-sin.md
packages/clerk-js/package.json
packages/clerk-js/src/core/clerk.ts
packages/clerk-js/src/ui/components/Checkout/CheckoutComplete.tsx
packages/clerk-js/src/ui/contexts/components/Checkout.ts
packages/clerk-js/src/ui/types.ts
packages/nextjs/src/utils/mergeNextClerkPropsWithEnv.ts
packages/react-router/src/utils/env.ts
packages/react/src/isomorphicClerk.ts
packages/remix/src/ssr/loadOptions.ts
packages/remix/src/ssr/types.ts
packages/remix/src/ssr/utils.ts
packages/tanstack-react-start/src/utils/env.ts
packages/types/src/clerk.ts
packages/types/src/redirects.ts

- Renames __experimental_checkoutContinueUrl to checkoutContinueUrl
- Filters checkoutContinueUrl accepted origins

refactor(repo): Rename __experimental_checkoutContinueUrl to checkoutContinueUrl

---

.changeset/salty-worms-attack.md
integration/templates/next-app-router/src/app/jwt-v2-organizations/(tests)/conditionals.tsx
integration/templates/next-app-router/src/app/jwt-v2-organizations/(tests)/has-client/page.tsx
integration/templates/next-app-router/src/app/jwt-v2-organizations/(tests)/has-server/page.tsx
integration/templates/next-app-router/src/app/jwt-v2-organizations/(tests)/has-ssr/client.tsx
integration/tests/protect-jwt-v2.test.ts
packages/backend/src/tokens/__tests__/authObjects.test.ts
packages/shared/src/authorization.ts

This PR allows for
- `has({role: "admin"})` instead of `has({ role: "org:admin })` (the later is still permitted)
- `has({permission: "friends:add"})` instead of `has({ permission: "org:friends:add })` (the later is still permitted)

feat(shared): Allow for `has({ role | permission})` without scope

---

.changeset/shiny-impalas-occur.md
packages/clerk-js/src/core/clerk.ts
packages/clerk-js/src/ui/Components.tsx
packages/clerk-js/src/ui/components/Checkout/Checkout.tsx
packages/clerk-js/src/ui/components/Checkout/CheckoutPage.tsx
packages/clerk-js/src/ui/components/Plans/PlanDetails.tsx
packages/clerk-js/src/ui/hooks/useCheckout.ts
packages/clerk-js/src/ui/lazyModules/MountedCheckoutDrawer.tsx
packages/clerk-js/src/ui/lazyModules/MountedPlanDetailDrawer.tsx
packages/clerk-js/src/ui/types.ts
packages/react/src/isomorphicClerk.ts
packages/types/src/clerk.ts

…nal_CheckoutProps and __internal_PlanDetailsProps

refactor(types): Rename CheckoutProps and PlanDetailsProps to __internal_CheckoutProps and __internal_PlanDetailsProps

---

turbo.json

This PR updates our Turborepo configuration for integration tests to depend on `@clerk/testing`. This ensures that running `turbo test:integration:<testName>` builds the latest version of `@clerk/testing` before running the tests.

fix(repo): Update integration tests to dependOn @clerk/testing

---

.changeset/upset-ravens-love.md
packages/clerk-js/src/ui/components/PricingTable/PricingTableDefault.tsx
packages/clerk-js/src/ui/elements/Switch.tsx

We need to make the label for `<Switch />` required as otherwise it's not an accessible component when left out. It needs a description for people to understand what it's about.
I also added the `is` prefix to the booleans as we a) use this in other places and b) makes their purpose clearer.

fix(clerk-js): Require label for Switch

---

.changeset/tender-glasses-post.md
packages/clerk-js/bundlewatch.config.json
packages/clerk-js/sandbox/template.html
packages/clerk-js/src/ui/components/Subscriptions/SubscriptionsList.tsx
packages/localizations/src/en-US.ts

chore(clerk-js): Sort subscriptions list by status

---

.changeset/icy-papers-hunt.md
packages/clerk-js/src/ui/elements/Drawer.tsx

Fixes a bug surfaced in Safari where the Drawer positioning was incorrectly being calculated causing the drawer to shift the content within the profile scroll boxes.
BEFORE:
https://github.com/user-attachments/assets/b82f8590-e5a3-469e-9989-c675a5a9e70e
AFTER:
https://github.com/user-attachments/assets/9951b73b-ad4e-495e-aa2f-0e4af04051a8
Fixes COM-749

fix(clerk-js): Ensure drawer works corrrectly in safari

---

.changeset/fuzzy-hotels-lay.md
packages/clerk-js/src/ui/components/OrganizationProfile/OrganizationBillingPage.tsx

chore(clerk-js): Add gap between no-permissions notice and pricing table

---

.changeset/rare-tips-dream.md
packages/clerk-js/sandbox/template.html
packages/clerk-js/src/ui/components/Checkout/CheckoutForm.tsx

chore(clerk-js): Remove top border from checkout form

---

.changeset/spotty-pugs-laugh.md
packages/clerk-js/src/ui/components/Checkout/CheckoutForm.tsx

fix(clerk-js): Render long message for submitError within CheckoutForm

---

.changeset/pink-bats-share.md
packages/clerk-js/bundlewatch.config.json
packages/clerk-js/src/ui/components/Checkout/CheckoutPage.tsx
packages/clerk-js/src/ui/contexts/components/Plans.tsx

When trying to switch from an annual plan to a monthly plan that has lower price FAPI returns an error, this PR handles that error and displays a custom UI
BEFORE:
AFTER:

fix(clerk-js): Handle invalid_plan_change error with custom UI

---

.changeset/violet-poets-move.md
packages/clerk-js/src/ui/components/PricingTable/PricingTableDefault.tsx
packages/clerk-js/src/ui/contexts/components/Plans.tsx

Fixes a case where the plan button was improperly showing when a plan wasn't eligible to upgrade to annual. Also fixes logic around the logic to display "Subscribe" vs. "Switch to this plan" when no subscriptions are present.

fix(clerk-js): Fix PricingTable plan button display logic

---

.changeset/red-corners-show.md
packages/clerk-js/src/ui/components/OrganizationProfile/OrganizationBillingPage.tsx

BEFORE:
AFTER:
https://github.com/user-attachments/assets/36462c51-90bf-4342-9f48-1ccbd90844a1

chore(clerk-js): Remove no manage billing permissions alert from the of start billing page

---

.changeset/two-keys-act.md
packages/clerk-js/src/ui/components/PaymentSources/PaymentSources.tsx

Implements loading state to prevent setting payment source remount as the data is fetched. Follows similar approach to found in `ActiveDevicesSection` component.
BEFORE
https://github.com/user-attachments/assets/01e7181c-bc2b-4282-abb6-d5b1c4ebd543
AFTER
https://github.com/user-attachments/assets/1e9682bf-c6d0-49ee-93e0-170b0164199c
Resolves COM-771

refactor(clerk-js): Add loading state to <PaymentSources /> component

---

.changeset/smart-horses-wish.md
packages/clerk-js/src/ui/components/OrganizationSwitcher/OrganizationSwitcherTrigger.tsx
packages/clerk-js/src/ui/components/OrganizationSwitcher/UserMembershipList.tsx
packages/types/src/appearance.ts

Adding descriptor ids to OrganizationSwitcherTrigger and UserMembershipList to allow targeting these elements more easily.

chore(clerk-js,types): Add descriptor ids to UserMembershipList and OrganizationSwitcherTrigger

---

.changeset/rude-friends-create.md
packages/clerk-js/src/ui/elements/Drawer.tsx

https://github.com/user-attachments/assets/b5f20c65-0dff-4512-a4c8-5d31759a6097
https://github.com/user-attachments/assets/417e9ffe-cf1d-40d6-b2ca-5f0f93e133a1

fix(clerk-js): Improve mobile `<Drawer />` sizing

---

.changeset/famous-fans-create.md
packages/clerk-js/bundlewatch.config.json
packages/clerk-js/src/ui/components/PricingTable/PricingTable.tsx
packages/clerk-js/src/ui/contexts/components/Plans.tsx
packages/clerk-js/src/ui/lazyModules/MountedCheckoutDrawer.tsx
packages/clerk-js/src/ui/lazyModules/MountedPlanDetailDrawer.tsx
packages/types/src/clerk.ts

- Correctly pipe checkout and plan detail drawer appearance through the pricing table component
- Removes internal prefix as this is a public facing option
Note: Docs already document this as `checkoutProps` for PricingTable properties.

fix(clerk-js,types): Correctly pass Checkout appearance prop through PricingTable

---

.changeset/twenty-monkeys-camp.md
packages/clerk-js/src/core/resources/CommerceCheckout.ts
packages/clerk-js/src/ui/components/Checkout/CheckoutComplete.tsx
packages/types/src/commerce.ts
packages/types/src/json.ts

Fix the "Plan starts at" date when a user downgrades from a paid plan to the free plan

fix(clerk-js): Add planPeriodStart to CommerceCheckout

---

.changeset/five-tips-own.md
packages/vue/src/components/controlComponents.ts
packages/vue/src/composables/useAuth.ts
packages/vue/src/plugin.ts
packages/vue/src/types.ts

This PR adds billing features to `useAuth()` composable and `<Protect>` component in Vue. A port of https://github.com/clerk/javascript/pull/5582 into Vue.

feat(vue): Introduce billing in `useAuth()` and `<Protect>`

---

.changeset/stupid-gifts-juggle.md
packages/clerk-js/src/ui/elements/Navbar.tsx

Fixes issue in Safari where navigating between tabs in the profile components, cause the icon to shift unexpectedly.
BEFORE
https://github.com/user-attachments/assets/9ad7ffac-cf73-4640-85d1-c3f4445a8880
AFTER
https://github.com/user-attachments/assets/1c50ccfc-9c6f-4e97-b7a6-a28e61d70e79

fix(clerk-js): Remove navbar icon shift in safari

---

.changeset/breezy-pillows-marry.md
packages/tanstack-react-start/src/server/clerkClient.ts

This PR updates the `clerkClient()` function to make the options parameter explicitly optional. Since the function already sets default values for all required config (secretKey, publishableKey, etc.) from env vars,

chore(tanstack-react-start): Make `clerkClient()` options parameter optional

---

.changeset/four-mangos-punch.md
packages/nuxt/src/module.ts
packages/vue/src/plugin.ts

This PR updates the Vue plugin and Nuxt module option types to accept a `isSatellite` prop. We also add a default `undefined` `isSatellite` value to the Nuxt module so it can be overridden by `NUXT_PUBLIC_CLERK_IS_SATELLITE` env var.
Related discord thread - https://discord.com/channels/856971667393609759/1021521740800733244/threads/1371557423038599190

chore(vue,nuxt): Add satellite application types

---

.changeset/hip-dancers-write.md
packages/clerk-js/src/ui/components/OrganizationProfile/OrganizationBillingPage.tsx
packages/clerk-js/src/ui/components/Subscriptions/SubscriptionsList.tsx
packages/clerk-js/src/ui/components/UserProfile/BillingPage.tsx
packages/localizations/src/en-US.ts
packages/types/src/localization.ts

Cleans up the display of the empty subscription list / button when the default free plan is hidden.
Before:
After:

chore(clerk-js,types,localizations): Clean up empty subscription list

---

.changeset/fresh-lamps-serve.md
packages/clerk-js/src/ui/components/Plans/PlanDetails.tsx

| ![Screenshot 2025-05-13 at 6 28 59 PM](https://github.com/user-attachments/assets/50461209-1e93-45a1-9294-8d513e530ba4) | ![Screenshot 2025-05-13 at 6 28 37 PM](https://github.com/user-attachments/assets/4f5c7e24-aa91-4a2a-b080-f9cf24c839f3) |

fix(clerk-js): PlanDetails heading spacing

---

.changeset/mighty-forks-joke.md
packages/clerk-js/src/ui/customizables/elementDescriptors.ts
packages/clerk-js/src/ui/elements/Drawer.tsx
packages/clerk-js/src/ui/elements/Switch.tsx
packages/types/src/appearance.ts

- Adds descriptor to target the root content element
- Fixes z-index issues with drawer content and modal close buttons

chore(clerk-js,types): Add drawer root descriptor

---

.changeset/dirty-keys-heal.md
packages/clerk-js/bundlewatch.config.json
packages/clerk-js/src/core/resources/SignIn.ts
packages/clerk-js/src/core/resources/SignUp.ts
packages/clerk-js/src/ui/components/SignIn/SignInSocialButtons.tsx
packages/clerk-js/src/ui/components/SignIn/SignInStart.tsx
packages/clerk-js/src/ui/components/SignUp/SignUpContinue.tsx
packages/clerk-js/src/ui/components/SignUp/SignUpSocialButtons.tsx
packages/clerk-js/src/ui/components/SignUp/SignUpStart.tsx
packages/clerk-js/src/utils/completeSignUpFlow.ts
packages/types/src/clerk.ts
packages/types/src/factors.ts
packages/types/src/redirects.ts

Resolves ORGS-647
Add `oidcPrompt` prop to `SignIn` and `SignUp` components and `authenticateWithRedirect` method to control the OIDC authentication prompt behavior during Enterprise SSO flows.
```tsx
<SignUp oidcPrompt='select_account' /> 
<SignIn oidcPrompt='select_account' /> 
```
```ts
signUp.authenticateWithRedirect({ redirectUrl: '/sso-callback', oidcPrompt: 'select_account' })
```

feat(types,clerk-js): Add `oidcPrompt` prop to `SignIn/SignUp` components

---

.changeset/cute-hoops-find.md
packages/clerk-js/src/ui/Components.tsx
packages/types/src/clerk.ts

Introduce `__experimental_startPath` option to `openOrganizationProfile`.
This enables folks to open to a specific nav item.
```ts
clerk.openOrganizationProfile({
__experimental_startPath: '/billing'
});
```

feat(clerk-js,types): Add __experimental_startPath to `openOrganizationProfile`

---

.changeset/smart-hats-run.md
packages/clerk-js/src/ui/components/Checkout/useCheckout.ts

This PR fixes an issue where checkout data where being stale in some cases

fix(clerk-js): Preven't checkout data from being stale

---

.changeset/breezy-snakes-hide.md
packages/clerk-js/src/ui/components/UserProfile/MfaSection.tsx

Aligns the MFA's default method action menu to no have the "Set as default" action menu, in order to have consistency with other sections on UP, e.g. Phone Numbers

chore(clerk-js): Hide set as default from default MFA's action menu

---

packages/nextjs/src/server/clerkMiddleware.ts
packages/nextjs/src/server/data/getAuthDataFromRequest.ts

When a request that comes in contains a machine token, skip the keyless check for missing PK or SK so it throws the missing PK or SK error

chore(nextjs): Restrict keyless to session auth

---

.changeset/plain-keys-visit.md
packages/clerk-js/src/ui/elements/Drawer.tsx

This PR updates the scroll lock functionality for the Drawer to only lock when we are using the fixed strategy. When Drawers are used in the profile components where the strategy is absolute, we don't want to lock scroll as that can prevent folks from seeing the full profile component.
Resolves COM-799

fix(clerk-js): Only lock scroll when Drawer is using fixed strategy

---

.github/workflows/ci.yml

Pinning version of `pr-pkg-new` in CI

chore(repo): Pin version of pkg-pr-new

---

.changeset/lazy-mugs-bet.md
packages/clerk-js/src/ui/components/SignUp/SignUpStart.tsx

Fix minor bug where WhatsApp button is not showing if no other Social Button exists

fix(clerk-js): Fix showing alternative phone code provider when no other SSO exists

---

.changeset/slick-windows-listen.md
packages/clerk-js/src/ui/components/UserProfile/UsernameForm.tsx

Fixes issue where min/max username lengths errors were not properly interpolated within profile component.
| ![Screenshot 2025-05-16 at 2 58 17 PM](https://github.com/user-attachments/assets/7064c7b9-13fe-4590-8bb5-c4160610612e) | ![Screenshot 2025-05-16 at 2 57 53 PM](https://github.com/user-attachments/assets/225ae361-7f32-4087-b380-b98253d5545d) | 
Fixes SDK-2110

fix(clerk-js): Translate username error in username form

---

.changeset/lazy-laws-sniff.md
packages/clerk-js/src/ui/components/KeylessPrompt/index.tsx

Fixes an issue where the keyless prompt was rendering above the newly added drawer component. To fix, we remove the z-index definition from the prompt. Alternatively I considered conditionally hiding the prompt when a drawer is open but the caused the initial expanded to always fire, even after it was closed once. So the z-index solution felt like the best approach.
https://github.com/user-attachments/assets/d5bffacd-9c15-46a3-b800-f947ed3fec1c
Fixes SDK-2115

fix(clerk-js): Ensure drawers render above keyless prompt

---

.changeset/full-boxes-learn.md
packages/clerk-js/src/ui/components/PaymentSources/PaymentSources.tsx

Allows removal of all payment methods when there are no active subscriptions.

chore(clerk-js): Allow removal of payment methods when no active subscriptions

---

.changeset/famous-wolves-open.md
packages/clerk-js/src/ui/components/Plans/PlanDetails.tsx

When implicitly on the default free plan, do not show cancel subscription option.
| ![Screenshot 2025-05-16 at 2 15 33 PM](https://github.com/user-attachments/assets/70322963-db72-423a-98fa-0e3a578f6d7a) | ![Screenshot 2025-05-16 at 2 14 15 PM](https://github.com/user-attachments/assets/569cd7a6-7680-4cd1-93e0-f06a11d2b84c) |
Fixes COM-823

fix(clerk-js): Remove cancel button from free plan

---

.changeset/flat-papers-begin.md
packages/backend/src/tokens/authObjects.ts
packages/backend/src/tokens/authStatus.ts
packages/backend/src/tokens/request.ts
packages/express/src/__tests__/helpers.ts
packages/express/src/__tests__/requireAuth.test.ts
packages/express/src/authenticateRequest.ts
packages/express/src/getAuth.ts
packages/express/src/requireAuth.ts
packages/express/src/types.ts

Allows passing `treatPendingAsSignedOut` to `getAuth`
```ts
// `pending` sessions will be treated as signed-out by default
const { userId } = getAuth(req)
```
```ts
// Both `active` and `pending` sessions will be treated as authenticated when `treatPendingAsSignedOut` is false
const { userId } = getAuth(req, { treatPendingAsSignedOut: false })
```

chore(backend,express): Introduce `treatPendingAsSignedOut` option to `getAuth`

---

.changeset/sixty-carpets-stare.md
packages/astro/src/server/clerk-middleware.ts
packages/astro/src/server/get-auth.ts

Allow passing `treatPendingAsSignedOut` to `auth`, `getAuth`, and server-side control components.
```ts
const { userId } = getAuth(req, { treatPendingAsSignedOut: false })
```
```ts
clerkMiddleware((auth, context) => {
const { redirectToSignIn, userId } = auth({ treatPendingAsSignedOut: false })
// Both `active` and `pending` sessions will be treated as authenticated when `treatPendingAsSignedOut` is false
if (!userId && isProtectedRoute(context.request)) {
return redirectToSignIn()
}
})
```

chore(astro): Introduce `treatPendingAsSignedOut` option to server-side utilities

---

.changeset/tall-insects-mix.md
packages/backend/src/tokens/__tests__/handshake.test.ts
packages/backend/src/tokens/handshake.ts

Fixes an issue in our handshake redirect loop detection. In a recent refactoring, we stopped reading the redirect counter, resulting in the loop detection not functioning properly.

refactor(backend): Fix handshake redirect loop detection

---

.changeset/dark-tips-strive.md
packages/clerk-js/src/ui/components/PaymentSources/PaymentSources.tsx

Fixes the logic for allowing removal of all payment methods if there are no _paid_ subscriptions.

fix(clerk-js): Allow removal of all payment methods if no paid subs

---

.changeset/poor-results-lay.md
packages/clerk-js/src/ui/components/Statements/StatementPage.tsx

Pass the full statement id into `SectionContentDetailsListItem` as internally it handles truncation and ensures the full value is copied to the clipboard.
Fixes COM-857

fix(clerk-js): Pass full statement id as value

---

.changeset/wide-seas-check.md
packages/backend/src/api/endpoints/OrganizationApi.ts

Add missing parameters to `getOrganizationMembershipList` for the Backend API requests
ECO-653
ECO-654

fix(backend): Add missing req params to `getOrganizationMembershipList`

---

.changeset/rotten-trams-rush.md
packages/clerk-js/src/core/clerk.ts

This PR drops throttling for multisession apps to fix edge cases when quickly switching between tabs with different sessions, in apps that have multisession support enabled.

fix(clerk): Do not throttle touch for multisession apps

---

.changeset/rotten-banks-rush.md
packages/clerk-js/bundlewatch.config.json
packages/clerk-js/src/ui/components/Checkout/CheckoutComplete.tsx
packages/clerk-js/src/ui/customizables/elementDescriptors.ts
packages/types/src/appearance.ts

The current highlight approach uses an overlay element the uses `mix-blend-mode` to interact with the elements within the checkout success drawer. This works well for white background usage, but as soon as the user modifies to the `colorBackground` value to be a light gray or uses the dark theme for example, the blend mode does not work due to the different in colors.
This updated approach uses an SVG and mask to implement the highlight in the rings which works across any `colorBackground` usage. One downside is we lose the interaction with the checkmark element and text but I am not sure we can have an implementation that supports that where users can input any background color.
BEFORE
https://github.com/user-attachments/assets/1b64ade4-5cb4-4dd7-a0f4-61d241082973
AFTER …

refactor(clerk-js): Update checkout success highlight approach

---

.changeset/little-wings-bathe.md
packages/clerk-js/src/ui/components/SignIn/__tests__/handleCombinedFlowTransfer.test.ts
packages/clerk-js/src/ui/components/SignIn/handleCombinedFlowTransfer.ts

This PR fixes an issue where the combined flow wouldn't trigger correctly when invoked with a phone number while phone number was an optional field. It resolves the issue by treating phone_number as a non-optional field when a phone number identifier is used. Additionally, it adds some very, _very_ basic unit tests for the `handleCombinedFlowTransfer` function.
For context, we don't automatically convert sign ins to sign ups in the combined flow if there are possible optional fields that the user might want to complete. Before this PR, `phone_number` was an optional field. If the user tried to sign in with a phone number not associated with an account, we would consider `phone_number` an optional field, and redirect to the `create` step. This was unnecessary since the user already …

fix(clerk-js): Do not treat phone_number as optional if used as identifier

---

.changeset/angry-clouds-prove.md
packages/backend/src/api/endpoints/OrganizationApi.ts

Adds missing `client.organizations.getInstanceOrganizationMembershipList`
Fixes ECO-662

feat(backend): Add `getInstanceOrganizationMembershipList`

---

.changeset/happy-bees-post.md
packages/clerk-js/src/core/resources/CommercePaymentSource.ts
packages/clerk-js/src/ui/components/PaymentSources/PaymentSources.tsx
packages/types/src/commerce.ts
packages/types/src/json.ts

Uses the new `is_removable` flag on a payment source to determine whether it should be allowed to be removed from the UI

chore(clerk-js,types): Use is_removable flag on payment sources

---

.changeset/hungry-mangos-shout.md
packages/backend/package.json
packages/backend/src/webhooks.ts
pnpm-lock.yaml

The `verifyWebhook()` required the installation of the `svix` package. This refactors `verifyWebhook()` to manually verify the incoming Clerk webhook event following [Verifying Webhooks Manually](https://docs.svix.com/receiving/verifying-payloads/how-manual)

fix(backend): Remove peerDep of `svix` for `verifyWebhook()`

---

integration/tests/tanstack-start/basic.test.ts

Use `toMatchObject()` instead of `toContain()` for header checks which allows for partial object matching. The previous one fails because `toContain()` is for arrays and strings. Failing test [here](https://github.com/clerk/javascript/actions/runs/15447324241/job/43482299028)

test(tanstack-react-start): Use correct test matcher for checking headers

---

.changeset/nasty-items-jog.md
packages/clerk-js/src/ui/components/SignIn/SignInStart.tsx
packages/clerk-js/src/ui/components/SignUp/SignUpStart.tsx

We've introduced FAPI changes to return `missing_requirements` / `needs_first_factor` when a sign-in/sign-up gets created with an org invite that is related to an active enterprise connection. 
This PR updates the ticket flows to check against those new statuses and initiate enterprise SSO redirection.
https://github.com/user-attachments/assets/460b4862-c9cb-4a12-8cad-0ab67a034b63

feat(clerk-js): Initiate enterprise SSO from ticket flows

---

packages/clerk-js/src/ui/customizables/__tests__/parseVariables.spec.ts
packages/clerk-js/src/ui/customizables/parseVariables.ts

This PR adds a new function, `removeInvalidValues`, that will remove values specified with CSS variables from `appearance.variables` when modern color is not supported. It will also log a warning to the console indicating that a fallback value is being used.

feat(clerk-js): Remove CSS variables when modern color isn't supported

---

packages/clerk-js/src/ui/components/PaymentAttempts/PaymentAttemptPage.tsx
packages/clerk-js/src/ui/components/Statements/Statement.tsx
packages/clerk-js/src/ui/customizables/parseVariables.ts
packages/clerk-js/src/ui/elements/LineItems.tsx
packages/clerk-js/src/ui/foundations/colors.ts
packages/clerk-js/src/ui/polishedAppearance.ts
packages/clerk-js/src/ui/styledSystem/common.ts
packages/types/src/appearance.ts

Adds `colorRing` variable option. When specified overrides the default ring outline color `neutralAlpha200`.
https://github.com/user-attachments/assets/f06ebc19-7478-4a72-92ab-f58bdeca1bc6

feat(clerk-js): Expose CSS variables for clerk appearance variables

---

packages/clerk-js/src/ui/customizables/parseVariables.ts
packages/clerk-js/src/ui/elements/Modal.tsx
packages/clerk-js/src/ui/foundations/colors.ts
packages/types/src/appearance.ts

This PR adds `colorModalBackdrop` as a variable option

feat(clerk-js): Add `colorModalBackdrop` variable option

---

.changeset/seven-trees-double.md
packages/clerk-js/src/core/resources/CommerceSettings.ts
packages/clerk-js/src/ui/utils/test/fixtureHelpers.ts
packages/clerk-js/src/ui/utils/test/fixtures.ts
packages/types/src/commerceSettings.ts

Internally clerk-js and our hooks already use the payer specific flags (e.g. `user.enabled`). The react hooks from `@clerk/shared` never got to used this old properties, thus compatibility with old versions is **assured**. We should remove this before the Clerk Billing goes to GA, to ensure that we are not making breaking changes later on. 
Environment is already considered unstable, thus such a change should be permitted.

chore(clerk-js, types): Drop top level billing flags from environment
