- packages/backend-core/src/api/resources/JSON.ts
- packages/backend-core/src/api/resources/Props.ts
- packages/backend-core/src/api/resources/User.ts
- Addition of `unsafe_metadata` type on UserJSON resource
> fix(backend-core): Fix user type with unsafe_metadata

- .github/ISSUE_TEMPLATE/ask_a_question.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- README.md
Add discord links in issue templates, and Ask a question issue template
> chore(repo): Add first badges and question issue template

- packages/backend-core/src/Base.ts
Fixes and small enhancement on the `getAuthState` algorithm. Will fully comply to the formal spec soon.
> fix(backend-core): Enhancement of the auth state algorithm

- .gitignore
- docs/MONOREPO.md
- lerna.json
- package-lock.json
- package.json
- packages/backend-core/src/Base.ts
- packages/sdk-node/src/Clerk.ts
Minor Lerna additions
- Naive [Turborepo](https://turborepo.org/docs/guides/migrate-from-lerna) addition. It caches results from tests in packages that have not changed. Same with the build process(_understands inter-package dependencies_).
- Lerna allowed branches config.
(_Let's validate on the next deployment that the distribution files are receiving the correct `package.json version` after the `version` command_)
> chore(repo): Add turborepo

- packages/backend-core/src/Base.ts
- Remove the check for no-referrer on interstitial development logic.
> fix(backend-core): Remove the no-referrer check for interstitial

- packages/backend-core/README.md
- packages/backend-core/src/Base.ts
- packages/backend-core/src/__tests__/utils/jwt.test.ts
- packages/backend-core/src/util/jwt.ts
- packages/backend-core/src/util/types.ts
- packages/edge/README.md
- packages/edge/src/vercel-edge.ts
- packages/sdk-node/README.md
- packages/sdk-node/src/Clerk.ts
> Support to verify authorized party (azp) session token claim

- packages/backend-core/src/api/collection/UserApi.ts
Add support for a new param to skip password checks during user creation
> feat(backend-core): Support for skipPasswordChecks param during user creation

- packages/edge/src/vercel-edge.ts
- packages/sdk-node/src/Clerk.ts
Add a custom header X-Clerk-SDK in every request which contains the current SDK version 
- For `clerk-sdk-node` with the format `node/<version>`
- For `vercel-edge` with the format `vercel-edge/<version>`
> Add custom header X-Clerk-SDK in every request for clerk-sdk-node and vercel-edge packages

- package.json
- turbo.json
Nothing special - tidy up turborepo's config 🙃
> chore(repo): Move `turbo` config into `turbo.json`

- .github/workflows/ci.js.yml
> chore(repo): Add CI with Github actions

- .dockerignore
- Dockerfile
- package.json
Teach local dev servers to run in a docker container. This can be used for a dockerized local development environment.
> chore(repo): Dockerize the repo

- .npmrc
Enforce strict package.json `engines` check.
> chore(repo): Enforce strict engine versions

- packages/clerk-js/src/ui/userProfile/UserProfile.test.tsx
- packages/clerk-js/src/ui/userProfile/account/Account.test.tsx
- packages/clerk-js/src/ui/userProfile/account/Account.tsx
- packages/clerk-js/src/ui/userProfile/account/profileCard/ProfileCard.test.tsx
- packages/clerk-js/src/ui/userProfile/account/profileCard/ProfileCard.tsx
- packages/clerk-js/src/ui/userProfile/account/profileCard/__snapshots__/ProfileCard.test.tsx.snap
- packages/clerk-js/src/ui/userProfile/emailAdressess/AddNewEmail.test.tsx
- packages/clerk-js/src/ui/userProfile/emailAdressess/EmailDetail.test.tsx
- packages/clerk-js/src/ui/userProfile/emailAdressess/utils.ts
- packages/clerk-js/src/ui/userProfile/security/ChangePassword.test.tsx
- packages/clerk-js/src/ui/userProfile/security/ChangePassword.tsx
- packages/clerk-js/src/ui/userProfile/security/Security.test.tsx
- packages/clerk-js/src/ui/userProfile/security/Security.tsx
- packages/clerk-js/src/ui/userProfile/security/index.tsx
> Replace auth config with user settings in user profile

- package-lock.json
- packages/backend-core/package.json
Include `tslib` independently on @clerk/backend-core.
> fix(backend-core): Include tslib independently

- package-lock.json
- packages/clerk-js/package.json
- packages/nextjs/package.json
- packages/shared/package.json
> chore(repo): Bump versions to tackle CVE

- packages/clerk-js/src/ui/signUp/SignUpVerify.test.tsx
- packages/clerk-js/src/ui/signUp/SignUpVerify.tsx
- packages/clerk-js/src/ui/signUp/__snapshots__/SignUpVerify.test.tsx.snap
- packages/clerk-js/src/ui/userProfile/UserProfile.test.tsx
- packages/clerk-js/src/ui/userProfile/account/Account.tsx
- packages/clerk-js/src/ui/userProfile/account/personalInformation/PersonalInformationCard.tsx
- packages/clerk-js/src/ui/userProfile/emailAdressess/utils.ts
Various ClerkJS fixes for the new user_settings modelling. For more information have a look at the commit messages.
> Clerk js user settings fixes

- package.json
- packages/remix/src/client/RemixClerkProvider.tsx
- packages/remix/src/client/utils.ts
- packages/remix/src/errors.ts
- packages/remix/src/ssr/rootAuthLoader.ts
- Make clerkState required
- Allow rootAuthLoader emtpy responses
> Remix improvements

- packages/clerk-js/src/ui/Components.tsx
> Fix SignIn/SignUp modal styles

- lerna.json
Allow staging branch releases and versioning.
> chore(repo): Allow staging version and publish

- packages/clerk-js/src/ui/common/constants.ts
- packages/types/src/oauth.ts
Adds declarations for supporting the `oauth_microsoft` strategy.
> feat(types): Add support for oauth_microsoft

- packages/clerk-js/src/ui/signUp/SignUpStart.tsx
https://recordit.co/liTL5idol8
Invalid token hides the email input and the user will not be able to sign up without changing the screen.
https://recordit.co/O5qAO1GJID
Much better :)
> fix(clerk-js): Clear invalid invitation token value

- packages/types/LICENSE
- packages/types/README.md
- packages/types/docs/CODE_OF_CONDUCT.md
- packages/types/docs/CONTRIBUTING.md
- packages/types/docs/SECURITY.md
☝️ Build is failing but unrelated to my changes. The build succeeds for the `@clerk/types` package without errors.
- LICENSE
> chore(types): Update docs

- packages/backend-core/src/Base.ts
- packages/backend-core/src/__tests__/utils/request.test.ts
- packages/backend-core/src/util/request.ts
Revise the cross-origin check based on request headers.
Please take a look at the code of the process and tests.
> fix(backend-core): More robust cross-origin check for dev/prod

- packages/react/src/hooks/useOrganizations.ts
> feat(clerk-react): Add isLoaded to `useOrganizations` hook

- packages/react/LICENSE
- packages/react/README.md
- packages/react/docs/CODE_OF_CONDUCT.md
- packages/react/docs/CONTRIBUTING.md
- packages/react/docs/SECURITY.md
> chore(clerk-react): Update docs

- packages/nextjs/src/middleware/withServerSideAuth.ts
- packages/remix/src/ssr/rootAuthLoader.ts
Minor cleanup - this PR extracts the overloads into a separate interface
> Minor SSR type cleanup

- packages/expo/LICENSE
- packages/expo/README.md
- packages/expo/docs/CODE_OF_CONDUCT.md
- packages/expo/docs/CONTRIBUTING.md
- packages/expo/docs/SECURITY.md
☝️ Build is failing but unrelated to my changes. The build succeeds for the `@clerk/clerk-expo` package without errors.
- LICENSE
> chore(clerk-expo): Update docs

- packages/nextjs/LICENSE
- packages/nextjs/README.md
- packages/nextjs/docs/CODE_OF_CONDUCT.md
- packages/nextjs/docs/CONTRIBUTING.md
- packages/nextjs/docs/SECURITY.md
- packages/types/README.md
- LICENSE
I also updated the README in `@clerk/types` to use absolute paths.
> chore(nextjs): Update docs

- packages/clerk-js/src/core/resources/Session.ts
- packages/edge/src/vercel-edge/index.ts
- packages/edge/src/vercel-edge/types.ts
- packages/edge/src/vercel-edge/utils/getAuthData.ts
- packages/nextjs/src/middleware/utils/getAuthData.ts
- packages/react/src/hooks/useAuth.ts
- packages/react/src/hooks/utils.ts
- packages/remix/src/ssr/getAuthData.ts
- packages/types/src/session.ts
- packages/types/src/ssr.ts
- packages/types/src/token.ts
> getToken improvements

- packages/clerk-js/src/core/constants.ts
- packages/clerk-js/src/core/resources/SignIn.ts
- packages/clerk-js/src/ui/signIn/factorOne/SignInFactorOneInputBased.tsx
- packages/clerk-js/src/utils/resourceParams.test.ts
- packages/clerk-js/src/utils/resourceParams.ts
- packages/types/src/factors.ts
> fix(clerk-js): Fix signIn.prepareFirstFactor params

- packages/backend-core/src/__tests__/apis/UserApi.test.ts
> fix(backend-core): Fix users.getCount() nock test

- packages/edge/LICENSE
- packages/edge/README.md
- packages/edge/docs/CODE_OF_CONDUCT.md
- packages/edge/docs/CONTRIBUTING.md
- packages/edge/docs/SECURITY.md
☝️ Both test and build fail but are unrelated to my changes
- Updated LICENSE
> chore(edge): Update docs

- packages/clerk-js/src/core/resources/EmailAddress.ts
- packages/clerk-js/src/core/resources/SignIn.ts
- packages/types/src/emailAddress.ts
> fix(clerk-js): Make prepareVerification params object required

- packages/backend-core/src/api/collection/UserApi.ts
Type fix - add skipPasswordRequirement to users.create params
> fix(backend-core): Add skipPasswordRequirement param to users.create

- packages/clerk-js/LICENSE
- packages/clerk-js/README.md
- packages/clerk-js/docs/CODE_OF_CONDUCT.md
- packages/clerk-js/docs/CONTRIBUTING.md
- packages/clerk-js/docs/SECURITY.md
☝️ Both test and build fail but are unrelated to my changes
- Updated LICENSE
> chore(clerk-js): Update docs

- packages/remix/LICENSE
- packages/remix/README.md
- packages/remix/docs/CODE_OF_CONDUCT.md
- packages/remix/docs/CONTRIBUTING.md
- packages/remix/docs/SECURITY.md
☝️ Both test and build fail but are unrelated to my changes.
- LICENSE
> chore(remix): Update docs

- packages/gatsby-plugin-clerk/src/gatsby-browser.tsx
- packages/gatsby-plugin-clerk/src/ssr/withServerAuth.ts
- packages/nextjs/src/middleware/withServerSideAuth.ts
> Gatsby fixes

- packages/shared/components/oneTimeCodeInput/OneTimeCodeInput.tsx
- packages/shared/components/oneTimeCodeInput/useWebOTP.ts
> feat(clerk-js,shared): Add support for android WebOTP

- packages/remix/src/client/Interstitial.tsx
Update the interstitial logic on @clerk/remix .
> fix(remix): Update interstitial logic

- packages/gatsby-plugin-clerk/README.md
Introduces the README file for `gatsby-plugin-clerk`. This PR needs to be merged after the `gatsby-plugin-clerk` GA version is released.
> chore(gatsby-plugin-clerk): Add readme

- packages/backend-core/src/api/resources/Enums.ts
- packages/backend-core/src/types/jwt.ts
- packages/types/src/organizationMembership.ts
This PR includes the new organization role `guest_member`.
> feat(types): Include new organization role `guest_member`

- packages/remix/src/client/Interstitial.tsx
Add cross origin anonymous to remix interstitial
https://www.notion.so/clerkdev/a853f869f69c414b85e6d5290a2c4172?v=b253a2f980c641de8992cc63ed416fa0&p=3b6ebb2a3a2d44b4b7d67b2966169e40
> feat(remix): Add cross origin anonymous to remix interstitial

- packages/clerk-js/src/core/resources/SignUp.ts
- packages/clerk-js/src/core/resources/User.test.ts
- packages/clerk-js/src/core/resources/User.ts
- packages/clerk-js/src/core/resources/Web3Wallet.test.ts
- packages/clerk-js/src/core/resources/Web3Wallet.ts
- packages/types/src/signUp.ts
- packages/types/src/user.ts
- packages/types/src/web3Wallet.ts
Enhance Web3Wallet resource with new operations. Those are 
- create() which creates a new web3 wallet
- prepareVerification() to prepare the relevant web3 wallet verification
- attemptVerification() to verify the web3 wallet
- destroy() to delete it.
> feat(types,clerk-js): Enhance Web3 wallet resource with relevant operations

- packages/clerk-js/tsconfig.stable.json
Fixes a type-checking Issue found by @raptisj during local dev.
> chore(repo): Exclude v4 related files from dev type checking

- packages/clerk-js/src/v4/styledSystem/createVariants.test.ts
- packages/clerk-js/src/v4/styledSystem/createVariants.ts
> chore(repo): Make infiniteProxy stringifiable

- packages/clerk-js/src/utils/url.ts
https://clerkinc.slack.com/archives/G01K0A2254L/p1654514716574759
> fix(clerk-js): Fix new URL constructor

- packages/sdk-node/src/__tests__/exports.test.ts
> fix(clerk-sdk-node): Temporarily disable exports test on release

- packages/types/src/oauth.ts
> feat(types): Introduce Line OAuth

- packages/types/src/oauth.ts
> fix(types): Typo rename Line to LINE

- packages/backend-core/API.md
- packages/backend-core/README.md
> fix(backend-core): Fix backend-core ClerkBackendApi reference

- packages/clerk-js/src/core/resources/DisplayConfig.ts
- packages/types/src/displayConfig.ts
> feat(types): Add clerk_js_version to display_config

- package.json
- packages/clerk-js/src/v4/SignIn/SignInAccountSwitcher.tsx
- packages/clerk-js/src/v4/SignIn/SignInStart.tsx
- packages/clerk-js/src/v4/SignUp/SignUpContinue.tsx
- packages/clerk-js/src/v4/SignUp/SignUpStart.tsx
- turbo.json
- Adds "add account" button in sign in `/choose` page, as [discussed in internally](https://clerkinc.slack.com/archives/C03KKU8LWUQ/p1659846294728949)
- Correctly hides divider in SignInStart, SignUpStart and SignUpContinue if the instance has no social providers enabled, or no field-related auth factors enabled
> V4 fixes round 1

- package-lock.json
- packages/themes/CHANGELOG.md
- packages/themes/LICENSE
- packages/themes/README.md
- packages/themes/docs/CODE_OF_CONDUCT.md
- packages/themes/docs/CONTRIBUTING.md
- packages/themes/docs/SECURITY.md
- packages/themes/package.json
- packages/themes/src/createTheme.ts
- packages/themes/src/index.ts
- packages/themes/src/themes/dark.ts
- packages/themes/src/themes/index.ts
- packages/themes/src/themes/neobrutalism.ts
- packages/themes/src/themes/shadesOfPurple.ts
- packages/themes/tsconfig.build.json
- packages/themes/tsconfig.json
- packages/types/src/appearance.ts
Introduces `@clerk/themes` package. For now, this is considered an unstable, "experimental" package and we version it as such: `0.0.1`
It includes the bare minimum setup needed to make the default `dark` theme available
> feat(themes): Introduce @clerk/themes

- packages/clerk-js/src/v4/UserButton/UserButtonPopover.tsx
- packages/clerk-js/src/v4/UserProfile/ConnectedAccountsSection.tsx
- packages/clerk-js/src/v4/customizables/classGeneration.ts
- packages/clerk-js/src/v4/customizables/colorOptionToHslaScale.ts
- packages/clerk-js/src/v4/customizables/elementDescriptors.ts
- packages/clerk-js/src/v4/customizables/parseVariables.ts
- packages/clerk-js/src/v4/elements/PoweredByClerk.tsx
- packages/clerk-js/src/v4/hooks/useEnabledThirdPartyProviders.tsx
- packages/clerk-js/src/v4/styledSystem/breakpoints.tsx
- packages/clerk-js/src/v4/styledSystem/createCssVariables.ts
- packages/clerk-js/src/v4/utils/fromEntries.ts
- packages/clerk-js/src/v4/utils/index.ts
- packages/themes/src/themes/dark.ts
- Multiple descriptor ids per element
- Correctly theme github and apple logos on dark mode
- ponyfil Object.fromEntries
> v4 Improvements

- packages/types/src/oauth.ts
> feat(types): Introduce Instagram OAuth

- packages/clerk-js/src/ui/SignUp/SignUpStart.tsx
> fix(clerk-js): Correctly set ticket value for invitation flows

- packages/clerk-js/src/ui/customizables/parseAppearance.ts
- packages/types/src/appearance.ts
Sets `showOptionalFields` to true
> fix(clerk-js): Hide form if no required fields exist

- packages/edge/src/vercel-edge/index.ts
- packages/edge/src/vercel-edge/utils/injectAuthIntoRequest.ts
Added an `actorId` property in the request auth object. The value comes from the JWT `act.sub` claim. See #363 for more details.
> feat(edge): Add actorId in auth middleware

- packages/types/src/session.ts
> fix(types): Add isImpersonated in SessionResource

- packages/clerk-js/src/ui/UserButton/UserButtonPopover.tsx
- packages/clerk-js/src/ui/elements/Footer.tsx
- packages/clerk-js/src/ui/localization/defaultEnglishResource.ts
- packages/types/src/localization.ts
- packages/types/src/utils.ts
- Fix an internal TS warning reported by @chanioxaris 
- Add the missing help, privacy and terms footer keys
> Localizations part 2

- packages/clerk-js/src/ui/UserProfile/RemoveResourcePage.tsx
> fix(clerk-js): Typo on remove phone number page

- packages/clerk-js/src/core/clerk.ts
- packages/clerk-js/src/core/resources/Environment.ts
- packages/clerk-js/src/ui/Components.tsx
This unstable feature can be used to create demo pages for our components with custom user settings
http://recordit.co/LcGiMQgK5L
> feat(clerk-js): Allow external env updates in ClerkJS

- packages/nextjs/src/server/types.ts
- packages/nextjs/src/server/utils/getAuthDataFromClaims.ts
- packages/nextjs/src/server/utils/requestResponseUtils.ts
- packages/nextjs/src/server/utils/withClerkMiddleware.ts
> fix(nextjs): Set _authResult private prop for middleware use, misc fixes

- packages/clerk-js/src/ui/ImpersonationFab/ImpersonationFab.tsx
Make the impersonation fab max-width animation smoother by passing a ch value.
> fix(clerk-js): Smoother ImpersonationFab animation

- packages/clerk-js/src/ui/elements/Accordion.tsx
- packages/clerk-js/src/ui/elements/ArrowBlockButton.tsx
- packages/clerk-js/src/ui/elements/IdentityPreview.tsx
- packages/clerk-js/src/ui/elements/UserPreview.tsx
> fix(clerk-js): Display ellipsis properly where needed

- packages/clerk-js/src/ui/ImpersonationFab/ImpersonationFab.tsx
> fix(clerk-js): Only sign out from current session via ImpersonationFab

- packages/types/src/oauth.ts
Introduce Coinbase & Spotify OAuth provider
- https://www.notion.so/clerkdev/Sign-in-with-Coinbase-7ed326ccd8f94a26a464bff26517acc2
- https://www.notion.so/clerkdev/Sign-in-with-Spotify-62289ee4e0264197be7ce19f2468a1cc
> feat(types): Introduce Coinbase & Spotify OAuth provider

- packages/clerk-js/src/ui/localization/defaultEnglishResource.ts
- packages/types/src/localization.ts
> fix(clerk-js): Add form_password_incorrect to localization keys

- packages/clerk-js/src/ui/ImpersonationFab/ImpersonationFab.tsx
Better detect when the ImpersonationFab is (partly) outside of the viewport.
> fix(clerk-js): Improve repositioning of ImpersonationFab

- packages/clerk-js/src/core/resources/SignIn.ts
- packages/clerk-js/src/core/resources/SignUp.ts
- packages/clerk-js/src/ui/elements/SocialButtons.tsx
- packages/clerk-js/src/ui/elements/contexts/CardStateContext.tsx
> fix(clerk-js): Set status correctly in useCardState hook

- packages/clerk-js/src/ui/components/UserButton/OtherSessionActions.tsx
> feat(clerk-js): Replace Switch Account text with icon

- packages/clerk-js/src/ui/elements/Menu.tsx
- packages/clerk-js/src/ui/elements/index.ts
- packages/clerk-js/src/ui/foundations/zIndices.ts
- packages/clerk-js/src/ui/hooks/usePopover.ts
Example:
```
<Menu>
<MenuTrigger>
<Button sx={{ width: '100px' }}>Open</Button>
</MenuTrigger>
<MenuList>
<MenuItem>Action A</MenuItem>
<MenuItem>Action B</MenuItem>
<MenuItem>Very Long Action C</MenuItem>
<MenuItem>Action D</MenuItem>
<MenuItem>Action E</MenuItem>
</MenuList>
</Menu>
```
> feat(clerk-js): Introduce Menu element

- packages/clerk-js/src/ui/elements/contexts/CardStateContext.tsx
- packages/clerk-js/src/ui/localization/defaultEnglishResource.ts
- packages/clerk-js/src/ui/localization/makeLocalizable.tsx
- packages/clerk-js/src/ui/utils/errorHandler.ts
- packages/types/src/localization.ts
> Make global errors translatable

- playground/nextjs/middleware.ts
- playground/nextjs/package.json
- playground/nextjs/pages/_app.tsx
- playground/nextjs/pages/index.tsx
- playground/nextjs/pages/sign-in/[[...index]].tsx
- playground/nextjs/pages/sign-up/[[...index]].tsx
- playground/nextjs/pages/user/[[...index]].tsx
Introduces a simple Nextjs app that is using the local Clerk packages by default. This is intended to be used for local dev/testing.
> chore(repo): Introduce basic playground/nextjs structure

- packages/clerk-js/src/ui/components/UserProfile/ProfilePage.tsx
Fix optional field bug in user profile
> fix(clerk-js): Fix optional field bug in user profile

- packages/clerk-js/src/ui/components/OrganizationProfile/MemberListTable.tsx
- packages/clerk-js/src/ui/components/OrganizationProfile/OrganizationMembers.tsx
- packages/clerk-js/src/ui/components/OrganizationProfile/OrganizationProfileNavbar.tsx
- packages/clerk-js/src/ui/elements/Navbar.tsx
- packages/clerk-js/src/ui/elements/OrganizationPreview.tsx
- packages/clerk-js/src/ui/elements/UserPreview.tsx
- Add missing empty state for the member table
- Add OrganizationPreview to the navbar
> More OrganizationProfile components

- packages/clerk-js/src/ui/components/UserProfile/RemoveResourcePage.tsx
- packages/clerk-js/src/ui/elements/ContentPage.tsx
> fix(clerk-js): Fix localizationKeys for RemoveResourcePage

- packages/clerk-js/src/ui/elements/PhoneInput/PhoneInput.tsx
- packages/clerk-js/src/ui/elements/Select.tsx
> fix(clerk-js): Make Select element themable

- packages/clerk-js/src/ui/components/OrganizationProfile/MemberListTable.tsx
- packages/clerk-js/src/ui/elements/Pagination.tsx
- packages/clerk-js/src/ui/elements/Select.tsx
- packages/clerk-js/src/ui/foundations/opacity.ts
- packages/clerk-js/src/ui/primitives/Table.tsx
- packages/clerk-js/src/ui/primitives/Td.tsx
- packages/clerk-js/src/ui/primitives/Th.tsx
> feat(clerk-js): Table gaps and hover styles WIP

- packages/clerk-js/src/ui/components/UserProfile/AddAuthenticatorApp.tsx
> fix(clerk-js): Copyright on UserProfile TOTP page to continue on attempt verification

- packages/clerk-js/src/ui/components/OrganizationSwitcher/OtherOrganizationActions.tsx
> refactor(clerk-js): Reuse PreviewButton in OtherOrganizationActions

- packages/clerk-js/package.json
- packages/clerk-js/src/ui/components/OrganizationProfile/InviteMembersPage.tsx
- packages/clerk-js/src/ui/components/OrganizationProfile/OrganizationProfileRoutes.tsx
- packages/clerk-js/src/ui/elements/Alert.tsx
- packages/clerk-js/src/ui/elements/Select.tsx
- packages/clerk-js/src/ui/elements/TagInput.tsx
- packages/clerk-js/src/ui/elements/index.ts
- packages/clerk-js/src/ui/primitives/Alert.tsx
> feat(clerk-js): Set up the InviteMembersPage UI for OrganizationProfile

- packages/clerk-js/src/ui/components/OrganizationProfile/OrganizationProfileNavbar.tsx
> fix(clerk-js): Correctly truncate the name in the OrganizationProfile Navbar

- packages/clerk-js/src/ui/components/OrganizationProfile/InviteMembersPage.tsx
- packages/clerk-js/src/ui/elements/Form.tsx
- packages/clerk-js/src/ui/elements/TagInput.tsx
Note: The role select styles (the padding in this case) are fixed in another PR.  Also, the `Continue` button will change with localization!
> feat(clerk-js): More InviteMembersPage styles

- packages/clerk-js/src/ui/components/OrganizationProfile/ActiveMembersList.tsx
- packages/clerk-js/src/ui/components/OrganizationProfile/InvitationMemberList.tsx
> feat(clerk-js): maxWidth for UserPreview in OrgMembers table

- packages/clerk-js/src/ui/elements/PhoneInput/PhoneInput.tsx
- packages/clerk-js/src/ui/elements/Select.tsx
> feat(clerk-js): Default buttonOptionBuilder and aria styles after first key press

- packages/clerk-js/src/ui/components/OrganizationProfile/InviteMembersForm.tsx
- packages/clerk-js/src/ui/components/OrganizationProfile/MemberListTable.tsx
- packages/clerk-js/src/ui/elements/PhoneInput/PhoneInput.tsx
- packages/clerk-js/src/ui/elements/Select.tsx
```tsx
<Select 
options={[{value: '1'}, {value:'2'}, {value:'3'}]} 
value={value} 
onChange={(option => setValue(option.value)}
/>
```
```tsx
<Select 
options={[{value: '1', label:'number 1'}, {value:'2', label:'number 2'}, {value:'3', label:'number:2'}]} 
value={value} 
onChange={(option => setValue(option.value)}
/>
```
```tsx
<Select 
options={[{value: '1'}, {value:'2'}, {value:'3'}]}
optionBulder={(option, index, isFocused) => (<>YourJSX</>)}
value={value} 
onChange={(option => setValue(option.value)}
>
<SelectOptionList />
<SelectButton>
Your JSX based on the current value
</SelectButton>
</Select>
```
* placeholder: Button Text for when the `value` is `null`
* searchPlaceholder: Placeholder for the `SearchInput`
* noResultsMessage: Message to show when no search results exist
* …
> refactor(clerk-js): Refactor Select component for easier usage

- packages/clerk-js/src/ui/components/OrganizationProfile/CreateOrganizationPage.tsx
- packages/clerk-js/src/ui/components/OrganizationSwitcher/OrganizationSwitcherPopover.tsx
- packages/clerk-js/src/ui/components/OrganizationSwitcher/OrganizationSwitcherTrigger.tsx
- packages/clerk-js/src/ui/components/OrganizationSwitcher/OtherOrganizationActions.tsx
- packages/clerk-js/src/ui/contexts/ClerkUIComponentsContext.tsx
- packages/types/src/clerk.ts
> fix(clerk-js): Rename OrganizationProfile and OrganizationSwitcher props

- packages/clerk-js/src/ui/contexts/ClerkUIComponentsContext.tsx
- packages/clerk-js/src/ui/elements/Menu.tsx
- packages/clerk-js/src/ui/elements/Modal.tsx
- packages/clerk-js/src/ui/hooks/usePopover.ts
- packages/react/src/contexts/SessionContext.tsx
> fix(clerk-react): Use shared session context

- packages/backend-core/src/api/resources/Enums.ts
- packages/types/src/oauth.ts
https://www.notion.so/clerkdev/Sign-in-with-Atlassian-b3dcb47718774e40ba7cacfa47d8d17e
> feat(types): Support for oauth_atlassian

- packages/clerk-js/src/ui/components/OrganizationProfile/ActionConfirmationPage.tsx
- packages/clerk-js/src/ui/components/OrganizationProfile/OrganizationProfileNavbar.tsx
- packages/clerk-js/src/ui/components/OrganizationProfile/OrganizationProfileRoutes.tsx
- packages/clerk-js/src/ui/components/OrganizationProfile/OrganizationSettings.tsx
- packages/clerk-js/src/ui/localization/defaultEnglishResource.ts
- packages/types/src/localization.ts
> feat(clerk-js): Leave organization confirmation page

- packages/clerk-js/src/ui/components/OrganizationSwitcher/OrganizationSwitcherPopover.tsx
- packages/clerk-js/src/ui/contexts/ClerkUIComponentsContext.tsx
- packages/react/src/components/index.ts
- packages/types/src/clerk.ts
- playground/nextjs/pages/_app.tsx
- playground/nextjs/pages/create-organization/[[...index]].tsx
- playground/nextjs/pages/organization/[[...index]].tsx
> Organization components release preparation

- packages/clerk-js/src/core/resources/Image.ts
- packages/clerk-js/src/core/resources/User.ts
- packages/clerk-js/src/ui/components/UserProfile/ProfilePage.tsx
- packages/clerk-js/src/ui/components/UserProfile/UserProfileAvatarUploader.tsx
- packages/clerk-js/src/ui/elements/AvatarUploader.tsx
- packages/clerk-js/src/ui/localization/defaultEnglishResource.ts
- packages/types/src/localization.ts
- packages/types/src/user.ts
> fix(clerk-js): Delete user profile image

- packages/clerk-js/src/ui/components/OrganizationSwitcher/OrganizationSwitcherPopover.tsx
- packages/clerk-js/src/ui/components/OrganizationSwitcher/OrganizationSwitcherTrigger.tsx
- packages/clerk-js/src/ui/components/OrganizationSwitcher/OtherOrganizationActions.tsx
> fix(clerk-js): Add missing personal workspace subtitle to previews

- packages/sdk-node/src/Clerk.ts
-  [x] 🐛 Bug fix
That way customers will be able to pass clock tolerance and other available options.
https://www.npmjs.com/package/jsonwebtoken
> fix(clerk-sdk-node): Pass jsonwebtoken verify options

- packages/clerk-js/src/core/resources/Organization.ts
- packages/clerk-js/src/ui/components/CreateOrganization/CreateOrganizationPage.tsx
- packages/clerk-js/src/ui/components/OrganizationProfile/OrganizationProfileAvatarUploader.tsx
- packages/clerk-js/src/ui/components/OrganizationProfile/ProfileSettingsPage.tsx
- packages/clerk-js/src/ui/components/UserProfile/ProfilePage.tsx
- packages/clerk-js/src/ui/components/UserProfile/UserProfileAvatarUploader.tsx
- packages/clerk-js/src/ui/elements/Avatar.tsx
- packages/clerk-js/src/ui/elements/AvatarUploader.tsx
- packages/clerk-js/src/ui/utils/index.ts
- packages/clerk-js/src/ui/utils/userUtils.ts
- packages/types/src/organization.ts
Add delete organization logo functionality
https://user-images.githubusercontent.com/23478420/200788991-7b7e29c0-7377-41df-9106-bb974e392da2.mov
https://user-images.githubusercontent.com/23478420/200789051-73778787-8dfe-43fd-a133-87da7bf1e460.mov
> Delete org logo

- packages/clerk-js/src/ui/components/CreateOrganization/CreateOrganizationPage.tsx
> fix(clerk-js): Remove incorrect conditional return value in CreateOrganizationPage

- packages/clerk-js/src/ui/components/OrganizationProfile/ActiveMembersList.tsx
> fix(clerk-js): Disable role select if admin is the only member

- packages/backend-core/README.md
> chore(backend-core): Correct package title in README

- packages/clerk-js/src/ui/components/CreateOrganization/CreateOrganizationPage.tsx
- packages/clerk-js/src/ui/components/OrganizationProfile/ActionConfirmationPage.tsx
- packages/clerk-js/src/ui/components/OrganizationProfile/ActiveMembersList.tsx
- packages/clerk-js/src/ui/components/OrganizationProfile/InviteMembersForm.tsx
- packages/clerk-js/src/ui/components/OrganizationProfile/InviteMembersPage.tsx
- packages/clerk-js/src/ui/components/OrganizationProfile/InvitedMembersList.tsx
- packages/clerk-js/src/ui/components/OrganizationProfile/MemberListTable.tsx
- packages/clerk-js/src/ui/components/OrganizationProfile/OrganizationMembers.tsx
- packages/clerk-js/src/ui/components/OrganizationProfile/OrganizationSettings.tsx
- packages/clerk-js/src/ui/components/OrganizationProfile/ProfileSettingsPage.tsx
- packages/clerk-js/src/ui/customizables/index.ts
- packages/clerk-js/src/ui/elements/Alert.tsx
- packages/clerk-js/src/ui/elements/SuccessPage.tsx
- packages/clerk-js/src/ui/elements/ThreeDotsMenu.tsx
- packages/clerk-js/src/ui/localization/defaultEnglishResource.ts
- packages/types/src/localization.ts
Add localization keys for the org components
> feat(clerk-js,types): Organization components localization

- packages/clerk-js/src/ui/common/EmailLinkCompleteFlowCard.tsx
- packages/clerk-js/src/ui/common/EmailLinkStatusCard.tsx
- packages/clerk-js/src/ui/common/EmailLinkVerify.tsx
- packages/clerk-js/src/ui/localization/defaultEnglishResource.ts
- packages/types/src/localization.ts
> feat(clerk-js): Add localization keys for magic link flow

- packages/clerk-js/src/ui/components/OrganizationProfile/ActionConfirmationPage.tsx
- packages/clerk-js/src/ui/components/OrganizationProfile/ActiveMembersList.tsx
- packages/clerk-js/src/ui/components/OrganizationProfile/InvitedMembersList.tsx
- packages/clerk-js/src/ui/components/OrganizationProfile/OrganizationSettings.tsx
- packages/clerk-js/src/ui/localization/defaultEnglishResource.ts
- packages/types/src/localization.ts
> fix(clerk-js,types): Rename organization localization keys

- packages/clerk-js/src/ui/elements/Alert.tsx
> fix(clerk-js): Correctly set Alert localization keys

- packages/clerk-js/src/ui/elements/IconButton.tsx
> fix(clerk-js): Show icon when using IconButton with localizationKey

- packages/clerk-js/src/ui/localization/defaultEnglishResource.ts
> fix(clerk-js): Correct the emailLink localization value

- packages/clerk-js/src/ui/elements/PhoneInput/PhoneInput.tsx
- packages/clerk-js/src/ui/elements/PhoneInput/countryCodeData.ts
- packages/clerk-js/src/ui/elements/PhoneInput/useFormattedPhoneNumber.ts
- packages/clerk-js/src/ui/utils/phoneUtils.test.ts
- packages/clerk-js/src/ui/utils/phoneUtils.ts
Refactor phone number input to change flags onPaste
An example where the last phone number is not valid
https://user-images.githubusercontent.com/23478420/197823787-41f50d1a-7c1f-45dd-84c9-2b3e8792529e.mov
> Phone number improvements

- packages/shared/src/utils/date.test.ts
- packages/shared/src/utils/date.ts
> fix(shared): Add optional locale param to `formatRelative`

- packages/types/src/oauth.ts
- https://www.notion.so/clerkdev/Sign-in-with-Xero-80ac4bd776404b9986754c920837e5b6
- https://www.notion.so/clerkdev/Sign-in-with-Box-5b33c96faad44ad3b62fb68365661db6
> feat(types): Introduce Xero & Box OAuth provider types

- packages/clerk-js/setupJest.ts
- packages/clerk-js/src/ui/components/UserProfile/ProfilePage.tsx
- packages/clerk-js/src/ui/components/UserProfile/RootPage.tsx
- packages/clerk-js/src/ui/components/UserProfile/__tests__/RootPage.test.tsx
- packages/clerk-js/src/ui/components/UserProfile/__tests__/UserProfile.test.tsx
- packages/clerk-js/src/ui/utils/test/fixtureHelpers.ts
- packages/clerk-js/src/ui/utils/test/mockHelpers.ts
> test(clerk-js): Start testing the UserProfile pages

- packages/clerk-js/src/ui/components/UserProfile/__tests__/RootPage.test.tsx
- packages/clerk-js/src/ui/utils/test/fixtureHelpers.ts
> test(clerk-js): Add withUser phone_numbers overrides

- packages/clerk-js/src/ui/utils/test/createFixtures.tsx
Allow settings component props before every render happens. The helper is automatically bound to the correct component
Example usage:
> test(clerk-js): Support settings props before render

- packages/clerk-js/src/ui/components/UserProfile/__tests__/RootPage.test.tsx
- packages/clerk-js/src/ui/utils/test/fixtureHelpers.ts
> test(clerk-js): Add overrides for external accounts in fixture helpers

- packages/clerk-js/src/ui/components/UserButton/__tests__/UserButton.test.tsx
This PR adds tests for the UserButton component
> test(clerk-js): Add tests for UserButton

- packages/clerk-js/src/ui/components/SignUp/__tests__/SignUpEmailLinkFlowComplete.test.tsx
- packages/clerk-js/src/ui/components/UserProfile/ConnectedAccountsPage.tsx
- packages/clerk-js/src/ui/components/UserProfile/MfaBackupCodeCreatePage.tsx
- packages/clerk-js/src/ui/components/UserProfile/__tests__/ConnectedAccountsPage.test.tsx
- packages/clerk-js/src/ui/components/UserProfile/__tests__/EmailPage.test.tsx
- packages/clerk-js/src/ui/components/UserProfile/__tests__/MfaBackupCodeCreatePage.test.tsx
- packages/clerk-js/src/ui/components/UserProfile/__tests__/MfaPage.test.tsx
- packages/clerk-js/src/ui/components/UserProfile/__tests__/PasswordPage.test.tsx
- packages/clerk-js/src/ui/components/UserProfile/__tests__/PhonePage.test.tsx
- packages/clerk-js/src/ui/components/UserProfile/__tests__/ProfilePage.test.tsx
- packages/clerk-js/src/ui/components/UserProfile/__tests__/RemoveConnectedAccountPage.test.tsx
- packages/clerk-js/src/ui/components/UserProfile/__tests__/RemoveEmailPage.test.tsx
- packages/clerk-js/src/ui/components/UserProfile/__tests__/RemoveMfaPhoneCodePage.test.tsx
- packages/clerk-js/src/ui/components/UserProfile/__tests__/RemoveMfaTOTPPage.test.tsx
- packages/clerk-js/src/ui/components/UserProfile/__tests__/RemovePhonePage.test.tsx
- packages/clerk-js/src/ui/components/UserProfile/__tests__/RootPage.test.tsx
- packages/clerk-js/src/ui/components/UserProfile/__tests__/UsernamePage.test.tsx
- packages/clerk-js/src/ui/utils/test/fixtureHelpers.ts
> test(clerk-js): Tests for UserProfile

- packages/clerk-js/src/core/clerk.redirects.test.ts
- packages/clerk-js/src/core/clerk.test.ts
- packages/clerk-js/src/utils/__tests__/url.test.ts
- packages/clerk-js/src/utils/url.ts
> Test clerk redirects

- package-lock.json
- packages/edge/package.json
- packages/react/package.json
- packages/shared/package.json
> chore(repo): Tidy up peer dependencies

- packages/clerk-js/src/core/resources/EmailAddress.ts
- packages/clerk-js/src/ui/components/UserProfile/__tests__/RemoveConnectedAccountPage.test.tsx
- packages/clerk-js/src/ui/components/UserProfile/__tests__/RemoveEmailPage.test.tsx
- packages/clerk-js/src/ui/components/UserProfile/__tests__/RemovePhonePage.test.tsx
- packages/clerk-js/src/ui/utils/test/mockHelpers.ts
> test(clerk-js): Correctly mock emails/phones/accounts

- packages/clerk-js/src/ui/components/OrganizationSwitcher/__tests__/OrganizationSwitcher.test.tsx
- packages/clerk-js/src/ui/utils/test/fixtureHelpers.ts
This PR adds fixture helpers for testing Organization components. Also, tests for OrganizationSwitcher are added.
> Test OrganizationSwitcher

- packages/clerk-js/src/ui/components/OrganizationProfile/__tests__/InviteMembersPage.test.tsx
- packages/clerk-js/src/ui/components/OrganizationProfile/__tests__/LeaveOrganizationPage.test.tsx
- packages/clerk-js/src/ui/components/OrganizationProfile/__tests__/OrganizationMembers.test.tsx
- packages/clerk-js/src/ui/components/OrganizationProfile/__tests__/OrganizationProfile.test.tsx
- packages/clerk-js/src/ui/components/OrganizationProfile/__tests__/OrganizationSettings.test.tsx
- packages/clerk-js/src/ui/components/OrganizationProfile/__tests__/ProfileSettingsPage.test.tsx
- packages/clerk-js/src/ui/components/UserProfile/__tests__/RemoveEmailPage.test.tsx
- packages/clerk-js/src/ui/utils/test/mockHelpers.ts
> Test Organization Profile

- packages/clerk-js/src/ui/components/OrganizationProfile/BillingWidget.tsx
- packages/clerk-js/src/ui/components/OrganizationProfile/InviteMembersPage.tsx
- packages/clerk-js/src/ui/components/OrganizationProfile/MembershipWidget.tsx
- packages/clerk-js/src/ui/components/OrganizationProfile/OrganizationMembers.tsx
- packages/clerk-js/src/ui/components/OrganizationSwitcher/OrganizationSwitcherPopover.tsx
- packages/clerk-js/src/ui/components/OrganizationSwitcher/OrganizationSwitcherTrigger.tsx
- packages/clerk-js/src/ui/contexts/ClerkUIComponentsContext.tsx
- packages/clerk-js/src/ui/customizables/elementDescriptors.ts
- packages/clerk-js/src/ui/icons/billing.svg
- packages/clerk-js/src/ui/icons/index.ts
- packages/types/src/appearance.ts
Edit billing options and member limit widget
> Orgs billing links

- packages/clerk-js/src/ui/components/OrganizationProfile/BillingWidget.tsx
- packages/clerk-js/src/ui/components/OrganizationProfile/MembershipWidget.tsx
> fix(clerk-js): Rename memberships widget

- packages/clerk-js/src/ui/components/OrganizationProfile/OrganizationMembers.tsx
> fix(clerk-js): Add memberships widget in invite tab

- packages/clerk-js/src/ui/components/OrganizationProfile/OrganizationMembers.tsx
- packages/clerk-js/src/ui/components/OrganizationProfile/OrganizationSettings.tsx
- packages/clerk-js/src/ui/elements/IconButton.tsx
- packages/clerk-js/src/ui/elements/PasswordInput.tsx
> feat(clerk-js): Enforce aria-label in IconButton

- packages/clerk-js/src/ui/elements/PhoneInput/PhoneInput.tsx
Get proper phone value on paste
> fix(clerk-js): Get phone value on paste

- packages/backend/src/tokens/authState.test.ts
- packages/backend/src/tokens/authState.ts
> feat(backend): Add orgSlug to authState

- packages/clerk-js/src/ui/components/OrganizationSwitcher/OrganizationSwitcherPopover.tsx
- packages/clerk-js/src/ui/elements/Actions.tsx
Tweak options spacing in organization switcher
> fix(clerk-js): Tweak options spacing in organization switcher

- .github/PULL_REQUEST_TEMPLATE.md
> chore(repo): Add missing packages (@clerk/backend, @clerk/shared) in PR template

- package-lock.json
- package.json
- packages/nextjs/src/server/utils/requestResponseUtils.ts
> Bump typescript

- packages/clerk-js/src/ui/components/SignIn/SignInFactorOne.tsx
- packages/clerk-js/src/ui/components/SignIn/SignInFactorOneEmailLinkCard.tsx
- packages/clerk-js/src/ui/components/SignUp/SignUpEmailLinkCard.tsx
- packages/clerk-js/src/ui/components/UserProfile/VerifyWithLink.tsx
- packages/clerk-js/src/ui/elements/ErrorCard.tsx
- packages/localizations/src/de-DE.ts
- packages/localizations/src/en-US.ts
- packages/localizations/src/fr-FR.ts
- packages/types/src/localization.ts
> fix(clerk-js,types,localizations): Add missing localization keys

- packages/clerk-js/src/ui/components/OrganizationProfile/OrganizationMembers.tsx
> fix(clerk-js): Fix spacing between membership widget and members table

- packages/clerk-js/src/ui/components/OrganizationSwitcher/OtherOrganizationActions.tsx
- packages/clerk-js/src/ui/components/UserButton/OtherSessionActions.tsx
> feat(clerk-js): Align all User and Org previews

- playground/nextjs/styles/globals.css
> chore(repo): Fix body colors in playground

- packages/clerk-js/src/ui/elements/Select.tsx
> fix(clerk-js): Fix Select error for pressing enter with no selection

- packages/clerk-js/src/ui/utils/errorHandler.ts
> fix(clerk-js): Clear field error state on resubmission

- packages/clerk-js/src/ui/contexts/OptionsContext.tsx
- packages/clerk-js/src/ui/localization/__tests__/makeLocalizable.test.tsx
- packages/clerk-js/src/ui/localization/__tests__/parseLocalization.test.tsx
- packages/clerk-js/src/ui/localization/localizationModifiers.ts
> test(clerk-js): Test localization

- packages/clerk-js/package.json
- packages/clerk-js/src/ui/components/CreateOrganization/CreateOrganizationPage.tsx
- packages/clerk-js/src/ui/components/OrganizationProfile/InviteMembersForm.tsx
- packages/clerk-js/src/ui/components/OrganizationProfile/ProfileSettingsPage.tsx
- packages/clerk-js/src/ui/components/SignIn/SignInFactorOnePasswordCard.tsx
- packages/clerk-js/src/ui/components/SignIn/SignInFactorTwoBackupCodeCard.tsx
- packages/clerk-js/src/ui/components/SignIn/SignInStart.tsx
- packages/clerk-js/src/ui/components/SignUp/SignUpForm.tsx
- packages/clerk-js/src/ui/components/UserProfile/EmailPage.tsx
- packages/clerk-js/src/ui/components/UserProfile/PasswordPage.tsx
- packages/clerk-js/src/ui/components/UserProfile/PhonePage.tsx
- packages/clerk-js/src/ui/components/UserProfile/ProfilePage.tsx
- packages/clerk-js/src/ui/components/UserProfile/UsernamePage.tsx
- packages/clerk-js/src/ui/elements/Form.tsx
- packages/types/src/appearance.ts
> feat(clerk-js): Add elementIds for formFieldRow

- CODEOWNERS
Add some codeowners for this repo
> chore: Add dimkl as backend/ owner

- packages/localizations/src/de-DE.ts
- packages/localizations/src/en-US.ts
- packages/localizations/src/fr-FR.ts
- packages/localizations/src/it-IT.ts
> fix(repo): Add correct organization settings subtitle

- packages/backend/src/tokens/factory.ts
> fix(backend): Correctly propagate jwtKey

- packages/clerk-js/src/utils/url.ts
> fix(clerk-js): Add missing dev instance suffix for new accounts.dev urls

- packages/nextjs/package.json
- packages/nextjs/server.d.ts
- packages/nextjs/src/api/__tests__/__snapshots__/exports.test.ts.snap
- packages/nextjs/src/api/index.ts
- packages/nextjs/src/middleware/withServerSideAuth.ts
> Export clerk-sdk-node types from nextjs/api

- packages/sdk-node/src/clerkClient.ts
This PR adds a `base.verifySessionToken` export until we update the RedwoodJS framework codebase.
> fix(clerk-sdk-node): Add verifySessionToken export for Redwood compatibility

- packages/localizations/src/en-US.ts
> fix(repo): Fix typo in emailAddressPage.emailCode.formSubtitle

- packages/nextjs/src/api/requireAuth.ts
- packages/nextjs/src/api/withAuth.ts
- packages/sdk-node/src/__tests__/__snapshots__/exports.test.ts.snap
- packages/sdk-node/src/clerkClient.ts
- packages/sdk-node/src/index.ts
- packages/sdk-node/src/requireAuth.ts
- packages/sdk-node/src/utils.ts
- packages/sdk-node/src/withAuth.ts
> Introduce withAuth and requireAuth in clerk-sdk-node

- packages/backend/src/tokens/jwt.test.ts
- packages/backend/src/tokens/request.test.ts
- packages/backend/src/util/request.test.ts
…nderstand
Comment out todo tests to make results easier to read and understand!
> fix(backend): Comment out todo tests to make test results easier to understand

- packages/react/src/contexts/ClerkProvider.tsx
- packages/react/src/utils/scriptLoader.ts
- packages/shared/src/errors/thrower.test.ts
- packages/shared/src/errors/thrower.ts
> chore(clerk-react,shared): Eliminate missing frontendApi error message

- packages/clerk-js/src/ui/components/UserProfile/__tests__/ProfilePage.test.tsx
- packages/clerk-js/src/ui/primitives/Image.tsx
- packages/clerk-js/src/utils/url.ts
> feat(clerk-js): Specify image size and support retina displays

- packages/react/README.md
Drop REACT_APP_CLERK_FRONTEND_API environment variable usage example from docs.
> chore(clerk-react): Update docs about process.env

- packages/clerk-js/src/core/tokenCache.test.ts
- packages/clerk-js/src/ui/utils/test/runFakeTimers.ts
> chore(clerk-js): Fix flaky tests

- packages/clerk-js/src/core/clerk.ts
> fix(clerk-js): Transform correct value for proxyUrl

- packages/backend/src/api/endpoints/UserApi.ts
> AUTH-193 fix(clerk-sdk-node): Add UserPasswordHashingParams to CreateUserParams

- packages/backend/src/api/endpoints/UserApi.ts
Resolves issue: https://github.com/clerkinc/javascript/issues/739
> chore(backend): Add externalId in users endpoint

- packages/clerk-js/src/core/clerk.test.ts
- packages/clerk-js/src/core/clerk.ts
Improve test coverage for `Clerk.setActive` and fix some flaky tests and typos. For more information check commit titles and descriptions.
> Js 35 fix tests

- packages/clerk-js/src/ui/components/UserProfile/ConnectedAccountsPage.tsx
- packages/clerk-js/src/ui/components/UserProfile/ConnectedAccountsSection.tsx
- packages/clerk-js/src/ui/hooks/useClerkModalStateParams.tsx
- packages/clerk-js/src/ui/router/BaseRouter.tsx
- packages/clerk-js/src/ui/router/RouteContext.tsx
- packages/clerk-js/src/utils/__tests__/queryStateParams.test.ts
- packages/clerk-js/src/utils/queryStateParams.ts
Bug in default open when redirecting from auth flow
> fix(clerk-js): Bug in default open when redirecting from auth flow

- packages/clerk-js/src/core/clerk.ts
- packages/react/src/isomorphicClerk.ts
> chore(clerk-js,clerk-react): Remove usage of Function type

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
- packages/gatsby-plugin-clerk/README.md
This PR updates the Gatsby README file. Also, it adds the package to all github template files.
> Update Gatsby README file

- packages/clerk-js/src/ui/common/authPropHelpers.ts
- packages/clerk-js/src/utils/__tests__/url.test.ts
- packages/clerk-js/src/utils/url.ts
> fix(clerk-js): Prevent reflected XSS using the `javascript` protocol

- packages/clerk-js/src/ui/common/authPropHelpers.ts
- packages/clerk-js/src/utils/__tests__/url.test.ts
- packages/clerk-js/src/utils/url.ts
> fix(clerk-js): Do not discard relative redirect urls

- playground/remix-node/.eslintrc.js
- playground/remix-node/app/root.tsx
- playground/remix-node/app/routes/index.tsx
- playground/remix-node/package-lock.json
- playground/remix-node/package.json
This PR 
- Removes `experimental` when importing Clerk components from our remix package
- Updates dependencies
- Fixes issue with React being `undefined` inside Clerk components by explicitly adding `@clerk/clerk-react` to package.json
> chore(repo): Update remix-node playground

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- package-lock.json
- package.json
- packages/fastify/LICENSE
- packages/fastify/README.md
- packages/fastify/docs/CODE_OF_CONDUCT.md
- packages/fastify/docs/CONTRIBUTING.md
- packages/fastify/docs/SECURITY.md
- packages/fastify/package.json
- packages/fastify/src/index.ts
- packages/fastify/tsconfig.json
- packages/fastify/tsup.config.ts
- playground/fastify/package-lock.json
- playground/fastify/tsconfig.json
> chore(repo): Scaffold @clerk/fastify package

- .jit/config.yml
> chore(repo): Exclude jit from tests files

- packages/react/src/isomorphicClerk.ts
Adds redirectWithAuth to IsomorphicClerk, so it is correctly returned by useClerk during runtime
> fix(clerk-react): Add `redirectWithAuth` to isomorphicClerk

- packages/clerk-js/src/ui/customizables/elementDescriptors.ts
- packages/clerk-js/src/ui/elements/Card.tsx
- packages/clerk-js/src/ui/elements/Modal.tsx
- packages/clerk-js/src/ui/icons/close.svg
- packages/clerk-js/src/ui/icons/index.ts
- packages/types/src/appearance.ts
> feat(clerk-js,types): Add a close modal button

- packages/backend/src/tokens/interstitialRule.ts
- packages/backend/src/tokens/request.ts
Improve interstitial rules mapping to flow diagram
> Chore: Refactor interstitial rules order

- packages/nextjs/src/client/index.tsx
> feat(nextjs): Invoke the NextJS middleware when the client-side auth state changes

- packages/backend/src/index.ts
- packages/backend/src/tokens/interstitial.ts
- packages/fastify/src/clerkPlugin.ts
- packages/fastify/src/index.ts
- packages/fastify/src/types.ts
- packages/fastify/src/withClerkMiddleware.ts
- packages/sdk-node/src/clerkClient.ts
> Fastify touch ups 

- packages/sdk-node/src/__tests__/middleware.test.ts
- packages/sdk-node/src/authenticateRequest.ts
- packages/sdk-node/src/clerkExpressRequireAuth.ts
- packages/sdk-node/src/clerkExpressWithAuth.ts
> fix(clerk-sdk-node): Handle isUnknown case separetely & add tests

- packages/nextjs/src/middleware/withServerSideAuth.ts
- packages/nextjs/src/server/withClerkMiddleware.ts
> clerk(nextjs): Handle isUnknown case separately

- packages/expo/README.md
Update the clerk-expo README with a basic clerk expo setup guide
> chore(clerk-expo): Update README

- packages/types/src/oauth.ts
Introduce Slack OAuth provider
> feat(types): Introduce Slack OAuth provider

- packages/backend/src/api/endpoints/SessionApi.ts
Introduce a new optional param 'status' which gives the ability to filter out the sessions by provided a specific status
> feat(backend): Introduce status param for getSessionList()

- packages/backend/src/tokens/interstitialRule.ts
Removed unnecessary async from functions
Created `InterstitialRuleResult`
Reduced occasions of `as any`
> chore(backend): Improved types for interstitial rules

- packages/remix/src/ssr/getAuth.ts
- packages/remix/src/ssr/rootAuthLoader.ts
- packages/remix/src/ssr/utils.ts
Changes:
- Handle isUnknown case separately in packages/remix
- Fix npm audit vulnerabilities in playground/remix-node
- Drop unused testing dev deps from packages/remix
> chore(remix): Handle isUnknown case separately

- packages/backend/src/api/endpoints/UserApi.ts
> feat(backend): Add pbkdf2_sha256 to available hashers

- README.md
Sort packages & add remix package reference
> chore(repo): update packages in README

- packages/backend/src/api/endpoints/UserApi.ts
https://clerk.dev/docs/reference/backend-api/tag/Users#operation/UpdateUser
> fix(backend): Update user params

- .jit/config.yml
> Jit ignore playground

- packages/backend/src/api/endpoints/UserApi.ts
> feat(backend): Support users/{userId}/verify_otp endpoint

- packages/clerk-js/src/ui/components/UserButton/UserButton.tsx
Fixes https://github.com/clerkinc/javascript/issues/813
> feat(clerk-js,types): Add topLevelIdentifier descriptor for UserButton

- packages/clerk-js/src/core/clerk.test.ts
- packages/clerk-js/src/core/clerk.ts
- packages/clerk-js/src/core/eventBus.ts
- packages/clerk-js/src/core/events.ts
- packages/clerk-js/src/core/resources/Session.test.ts
- packages/clerk-js/src/core/resources/Session.ts
- packages/clerk-js/src/core/resources/__snapshots__/Session.test.ts.snap
- packages/clerk-js/src/core/services/authentication/AuthenticationService.ts
- packages/clerk-js/src/core/test/fixtures.ts
- packages/clerk-js/src/ui/utils/test/fixtureHelpers.ts
Introduce `core/eventBus` singleton module to support event bus architecture. To fix the issue of cookie not being in sync after `getToken()` is being called we have introduced an `token:update` custom event with the `TokenResource` passed in event data when token is being set and added an event listener to update the cookie using that event and it's token resource.
The `core/eventBus` module is internal so it's not being exposed.
> Fix(clerk-js): Sync __session cookie on token:update event

- packages/backend/src/api/endpoints/UserApi.ts
Adds https://clerk.dev/docs/reference/backend-api/tag/Users#operation/VerifyPassword
> feat(backend): Users Verify Password API

- packages/nextjs/src/app-beta/ClerkProvider.tsx
- packages/nextjs/src/app-beta/client/ClerkProvider.tsx
- packages/themes/src/themes/dark.ts
- packages/themes/src/themes/neobrutalism.ts
- playground/nextjs/app/app-dir/page.tsx
- playground/nextjs/package-lock.json
- playground/nextjs/package.json
Localization is easy. For appearance, the simplest solution seems to be to get rid of the function in our prebuilt themes, since there is no need for it right now (we just return an object without using the arguments). If a user wants to use the callback for elements he will get the error from next.js (as with any function prop while in a server component) and will have to add the use client directive in his file (same thing would apply if the developer wanted to pass the `navigate` prop).
Closes #637
> feat(nextjs): Improve types and add support for localization/appearance in app-beta

- packages/clerk-js/src/core/resources/Session.ts
> fix(clerk-js): Dispatch token update only for session token

- packages/clerk-js/docs/events.md
> chore(clerk-js): Add docs for events module

- packages/backend/src/api/resources/JSON.ts
- packages/backend/src/api/resources/SignInTokens.ts
Added the url property on the SignInToken resource.
> feat(backend): Sign in tokens url

- packages/backend/package.json
- packages/backend/src/util/parsePublishableKey.ts
- packages/shared/src/utils/isomorphicAtob.ts
> Support experimental-edge runtimes

- packages/types/src/clerk.ts
> fix(types): Remove deprecated only prop from <UserProfile/>

- packages/backend/src/api/endpoints/OrganizationApi.ts
- packages/backend/src/api/resources/OrganizationInvitation.ts
> Include publicMetadata in OrganizationInvitation

- packages/clerk-js/src/core/fapiClient.ts
- packages/clerk-js/src/core/resources/Environment.ts
- packages/clerk-js/src/ui/components/SignUp/SignUpForm.tsx
- packages/clerk-js/src/ui/components/UserProfile/PhonePage.tsx
- packages/clerk-js/src/ui/elements/FormControl.tsx
- packages/clerk-js/src/ui/elements/PhoneInput/PhoneInput.tsx
- packages/types/src/environment.ts
- packages/types/src/json.ts
> fix(types,clerk-js): Correctly handle null country header

- packages/clerk-js/src/core/clerk.test.ts
- packages/clerk-js/src/core/clerk.ts
- packages/clerk-js/src/core/services/authentication/AuthenticationService.ts
- packages/clerk-js/src/core/services/authentication/SessionCookiePoller.ts
- packages/clerk-js/src/core/services/authentication/SessionCookieService.ts
- packages/clerk-js/src/core/services/index.ts
- packages/clerk-js/src/core/tokenCache.ts
> chore(repo): Move token:update event handling to authentication service

- packages/remix/src/client/RemixClerkProvider.tsx
> chore(remix): Remove unnecessary code from RemixClerkProvider

- playground/express/.env.sample
- playground/express/.gitignore
- playground/express/README.md
- playground/express/package.json
- playground/express/src/loadEnv.ts
- playground/express/src/routes/index.ts
- playground/express/src/routes/private.ts
- playground/express/src/routes/public.ts
- playground/express/src/server.ts
- playground/express/src/views/home.ejs
- playground/express/tsconfig.json
Introduce express framework playground app for testing.
> chore(repo): Introduce express JS playground app

- packages/backend/docs/CODE_OF_CONDUCT.md
- packages/backend/docs/SECURITY.md
- packages/backend/src/tokens/errors.ts
- packages/backend/src/tokens/keys.test.ts
- packages/backend/src/tokens/keys.ts
- packages/backend/src/tokens/request.test.ts
- packages/clerk-js/src/core/errors.ts
- packages/expo/docs/CODE_OF_CONDUCT.md
- packages/expo/docs/SECURITY.md
- packages/nextjs/docs/CODE_OF_CONDUCT.md
- packages/nextjs/docs/SECURITY.md
- packages/nextjs/examples/next/pages/index.tsx
- packages/react/docs/CODE_OF_CONDUCT.md
- packages/react/docs/SECURITY.md
- packages/react/src/isomorphicClerk.ts
- packages/remix/docs/CODE_OF_CONDUCT.md
- packages/remix/docs/SECURITY.md
- packages/sdk-node/package.json
- packages/themes/docs/CODE_OF_CONDUCT.md
- packages/themes/docs/SECURITY.md
- packages/types/docs/CODE_OF_CONDUCT.md
- packages/types/docs/SECURITY.md
Replace all contact emails with the new `support@clerk.com` email
> Replace all contact emails with the new support@clerk.com email

- packages/localizations/src/index.ts
- packages/localizations/src/sv-SE.ts
> feat: added sv-SE localization

- packages/backend/src/api/resources/Enums.ts
- packages/backend/src/api/resources/Invitation.ts
- packages/backend/src/api/resources/JSON.ts
> fix(backend): Add `status` prop to the Invitation resource

- packages/clerk-js/src/core/resources/User.test.ts
- packages/clerk-js/src/core/resources/User.ts
This commit updates the new endpoint for password change to match the one in the BE, i.e.
```
POST /v1/me/password/change -> POST /v1/me/change_password
```
> chore(clerk-js): Changed update password endpoint

- packages/fastify/src/withClerkMiddleware.ts
> fix(fastify): Fix possible case of uncaught promises in withClerkMiddleware

- packages/clerk-js/src/core/resources/Base.ts
> fix(clerk-js): Fix typo in response header

- packages/nextjs/src/server/getAuth.ts
- packages/nextjs/src/server/types.ts
- packages/nextjs/src/server/withClerkMiddleware.ts
- packages/types/src/key.ts
```
withClerkMiddleware((req) => {
//stuff
getAuth(req, {secretKey})
//more stuff
}, {publishableKey, secretKey})
```
> feat(nextjs,types): Support runtime SK/PK for nextjs

- .github/ISSUE_TEMPLATE/ask_a_question.md
- .github/ISSUE_TEMPLATE/bug_report.md
- README.md
- packages/gatsby-plugin-clerk/src/errors.ts
> chore(repo): Fix Clerk docs reference

- packages/clerk-js/package.json
- packages/clerk-js/src/core/clerk.ts
- packages/clerk-js/src/core/fapiClient.ts
- packages/clerk-js/src/core/resources/UserSettings.ts
- packages/clerk-js/src/ui/components/OrganizationProfile/MembershipWidget.tsx
- packages/clerk-js/src/ui/components/SignUp/SignUpSocialButtons.tsx
- packages/clerk-js/src/ui/customizables/colorOptionToHslaScale.ts
- packages/clerk-js/src/ui/customizables/parseVariables.ts
- packages/clerk-js/src/ui/elements/UserPreview.tsx
- packages/react/src/isomorphicClerk.ts
- packages/types/src/clerk.ts
- packages/types/src/signUp.ts
> fix(clerk-js,types): Fix typescript errors

- packages/expo/src/useOAuth.ts
- packages/types/src/signUp.ts
Fixes and improvements for the new useOAuth hook.
> Expo oauth fixes

- .github/ISSUE_TEMPLATE/ask_a_question.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- packages/chrome-extension/README.md
- packages/clerk-js/README.md
- packages/expo/README.md
- packages/fastify/README.md
- packages/gatsby-plugin-clerk/README.md
- packages/localizations/README.md
- packages/nextjs/README.md
- packages/react/README.md
- packages/remix/README.md
- packages/sdk-node/README.md
- packages/themes/README.md
- packages/types/README.md
> chore(repo): Update discord links

- packages/clerk-js/src/ui/utils/test/fixtureHelpers.ts
> chore(clerk-js): Remove duplication when creating environment fixtures

- packages/clerk-js/src/ui/elements/Avatar.tsx
> fix(clerk-js): Make the border shimmer a border box

- packages/localizations/src/en-US.ts
- packages/types/src/localization.ts
> fix(clerk-js): Localize password validation error

- packages/clerk-js/src/ui/elements/Avatar.tsx
> chore(clerk-js): Disable avatar shimmer for now

- packages/backend/src/api/endpoints/UserApi.ts
Added two new parameters to the `updateUser()` API payload.
- `skipPasswordChecks` Ignores any password policy when updating the password.
- `signOutOfOtherSessions` Will log the user out of all active session after the password has been updated.
> feat(backend): Add password related parameters to updateUser()

- packages/clerk-js/src/core/resources/SignIn.ts
- packages/types/src/factors.ts
- packages/types/src/signIn.ts
- packages/types/src/strategies.ts
Add `resetPassword` method as a core resource and add `reset_password_code` strategy in prepare_first_factors.
> COR-267 fix(clerk-js): Add resetPassword method as a core resource

- packages/clerk-js/src/ui/components/OrganizationSwitcher/OrganizationSwitcherPopover.tsx
- packages/clerk-js/src/ui/components/OrganizationSwitcher/OrganizationSwitcherTrigger.tsx
- packages/clerk-js/src/ui/components/OrganizationSwitcher/OtherOrganizationActions.tsx
- packages/clerk-js/src/ui/components/SignIn/SignInFactorOneCodeForm.tsx
- packages/clerk-js/src/ui/components/SignIn/SignInFactorOneEmailLinkCard.tsx
- packages/clerk-js/src/ui/components/SignIn/SignInFactorOnePasswordCard.tsx
- packages/clerk-js/src/ui/components/SignIn/SignInFactorTwoCodeForm.tsx
- packages/clerk-js/src/ui/components/UserProfile/ProfilePage.tsx
- packages/clerk-js/src/ui/components/UserProfile/__tests__/ProfilePage.test.tsx
- packages/clerk-js/src/ui/elements/Avatar.tsx
- packages/clerk-js/src/ui/elements/AvatarUploader.tsx
- packages/clerk-js/src/ui/elements/IdentityPreview.tsx
- packages/clerk-js/src/ui/elements/OrganizationAvatar.tsx
- packages/clerk-js/src/ui/elements/UserAvatar.tsx
- packages/clerk-js/src/ui/elements/UserPreview.tsx
- packages/clerk-js/src/utils/decodeBase16.ts
- packages/clerk-js/src/utils/index.ts
- packages/clerk-js/src/utils/user.ts
> feat(clerk-js): Enable new images and avatar animations in the components

- packages/localizations/src/en-US.ts
> chore(clerk-js): Update english label for incorrect password

- packages/clerk-js/src/ui/elements/Form.tsx
> fix(clerk-js): Remove forgotten console.log

- packages/nextjs/package.json
- packages/nextjs/src/server/authenticateRequest.ts
- packages/react/package.json
> chore(nextjs): Remove explicitly-set params

- packages/nextjs/src/app-router/client/ClerkProvider.tsx
- packages/nextjs/src/app-router/client/useAwaitableNavigate.ts
- packages/nextjs/src/client-boundary/useInvalidateCacheOnAuthChange.tsx
- packages/nextjs/src/client-boundary/useInvokeMiddlewareOnAuthChange.tsx
- packages/nextjs/src/pages/ClerkProvider.tsx
- packages/nextjs/src/utils/invalidateNextRouterCache.ts
> chore(nextjs):  Refactor useAwaitableNavigate

- packages/clerk-js/src/ui/hooks/__tests__/usePasswordComplexity.test.tsx
- packages/clerk-js/src/ui/hooks/usePasswordComplexity.ts
- packages/types/src/userSettings.ts
> feat(clerk-js): Use allowed special characters for password from environment

- packages/nextjs/src/app-router/client/useAwaitableNavigate.ts
- packages/nextjs/src/index.ts
> Release fixes

- packages/clerk-js/src/ui/hooks/__tests__/usePasswordComplexity.test.tsx
- packages/clerk-js/src/ui/hooks/usePasswordComplexity.ts
- packages/clerk-js/src/ui/localization/makeLocalizable.tsx
- packages/clerk-js/src/ui/utils/index.ts
- packages/clerk-js/src/ui/utils/intl.ts
- packages/clerk-js/tsconfig.json
- packages/localizations/src/da-DK.ts
- packages/localizations/src/de-DE.ts
- packages/localizations/src/en-US.ts
- packages/localizations/src/es-ES.ts
- packages/localizations/src/fr-FR.ts
- packages/localizations/src/it-IT.ts
- packages/localizations/src/nl-NL.ts
- packages/localizations/src/pt-BR.ts
- packages/localizations/src/ru-RU.ts
- packages/localizations/src/sv-SE.ts
- packages/types/src/localization.ts
> COR-303: Add ISO locale in @clerk/localizations + Intl.ListFormat 

- packages/nextjs/src/app-router/server/auth.ts
- packages/nextjs/src/server/authMiddleware.test.ts
- packages/nextjs/src/server/authMiddleware.ts
- packages/nextjs/src/server/errors.ts
- packages/nextjs/src/server/getAuth.ts
- packages/nextjs/src/server/index.ts
- packages/nextjs/src/utils/debugLogger.test.ts
- packages/nextjs/src/utils/debugLogger.ts
- packages/nextjs/src/utils/response.ts
- Introduce withLogger and more debug logs for authMiddleware
- passing debug: true to authMiddleware also enables debug for auth() and getAuth()
- split auth and getAuth to improve error messages
- better TRPC support by changing the default matchers to allow for /api and /trpc routes
- improve the default ignoredRoute warning message
> App router improvements

- packages/clerk-js/src/ui/components/SignIn/SignInFactorOnePasswordCard.tsx
> fix(clerk-js): Leaking unsupported props directly to dom elements

- packages/clerk-js/src/ui/components/SignIn/ResetPassword.tsx
- packages/clerk-js/src/ui/components/SignIn/__tests__/ResetPassword.test.tsx
> Add missing information text in Reset Password form

- packages/backend/src/api/resources/Webhooks.ts
> Update Webhooks types (organizations, email, sms)

- packages/remix/src/ssr/authenticateRequest.ts
- packages/shared/src/utils/proxy.ts
> Sanitize protocol in `getRequestUrl`

- packages/clerk-js/src/core/errors.ts
> chore(clerk-js): Remove support email address from network/init errors

- packages/remix/src/ssr/authenticateRequest.ts
> COR-357 fix(remix): Prioritize options over env

- packages/clerk-js/src/core/clerk.ts
For flows like OAuth2 IDP in dev instances that use URL based session syncing, we need to add the dev session jwt as a query parameter so FAPI can recognize it on redirect (i.e. redirect to `/oauth/authorize`). If the user is signed in, we perform the redirect with this added query param.
> fix(clerk-js): Redirect for FAPI initiated flows if user is signed in

- packages/clerk-js/src/core/resources/SignIn.ts
- packages/clerk-js/src/ui/elements/Avatar.tsx
- packages/clerk-js/src/ui/elements/IdentityPreview.tsx
> refactor(clerk-js): Remove gravatar fallback in <Avatar />, keep for IdentityPreview

- packages/backend/src/api/resources/JSON.ts
There are a few nullable attributes in the UserJSON interface that are wrongly typed. This fixes it. Below is an example response payload from a `user.created` event (anonymized).
```
{
"data": {
"backup_code_enabled": false,
"banned": false,
"birthday": "",
"created_at": 1684002709120,
"email_addresses": [
{
"email_address": "x",
"id": "x",
"linked_to": [
{
"id": "x",
"type": "oauth_google"
}
],
"object": "email_address",
"reserved": false,
"verification": {
"attempts": null,
"expire_at": null,
"status": "verified",
"strategy": "from_oauth_google"
}
}
],
"external_accounts": [
{
"approved_scopes": "email https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile openid profile",
"email_address": "x",
"family_name": "x",
"given_name": "x",
"google_id": …
```
> fix(backend): Add nullable types to UserJSON type

- packages/clerk-js/src/utils/__tests__/url.test.ts
> test(clerk-js): Add test for undefined allowedRedirectOrigins

- packages/clerk-js/src/ui/components/SignIn/SignInFactorTwoAlternativeMethods.tsx
- packages/clerk-js/src/ui/components/SignIn/__tests__/SignInFactorTwo.test.tsx
> fix(clerk-js): Update 2FA alternative methods label

- packages/nextjs/src/app-router/client/ClerkProvider.tsx
This fix is required in order for our server components to update when auth state changes
> fix(nextjs): Perform a router.refresh() after auth state change

- packages/localizations/src/index.ts
> fix(localizations): Missing export of Danish locale

- playground/express/src/routes/public.ts
- playground/express/src/views/home.ejs
> Express playground support for multidomain environment variables

- packages/clerk-js/src/core/clerk.ts
- packages/clerk-js/src/ui/components/OrganizationProfile/ProfileSettingsPage.tsx
- packages/clerk-js/src/ui/components/SignIn/SignInFactorOneCodeForm.tsx
- packages/clerk-js/src/ui/components/SignIn/SignInFactorOneEmailLinkCard.tsx
- packages/clerk-js/src/ui/components/SignIn/SignInFactorOnePasswordCard.tsx
- packages/clerk-js/src/ui/components/SignIn/SignInFactorTwoCodeForm.tsx
- packages/clerk-js/src/ui/components/UserProfile/ProfilePage.tsx
- packages/clerk-js/src/ui/elements/ApplicationLogo.tsx
- packages/clerk-js/src/ui/elements/OrganizationAvatar.tsx
- packages/clerk-js/src/ui/elements/UserAvatar.tsx
- packages/clerk-js/src/ui/elements/UserPreview.tsx
- packages/clerk-js/src/ui/hooks/useEnabledThirdPartyProviders.tsx
- packages/types/src/clerk.ts
Remove images FF. This needs to be merged and released after https://github.com/clerkinc/javascript/pull/1239
Already reviewed in https://github.com/clerkinc/javascript/pull/1240
> Remove experimental_enableClerkImages FF

- packages/clerk-js/src/ui/elements/FormControl.tsx
- packages/clerk-js/src/ui/foundations/transitions.ts
> Slow down animation for field text states

- packages/clerk-js/src/ui/common/SSOCallback.tsx
- packages/clerk-js/src/ui/elements/LoadingCard.tsx
https://github.com/clerkinc/javascript/assets/19269911/e13d073b-a3db-4e31-a390-659355a633f4
> Handle errors in SSOCallback

- packages/localizations/src/pt-BR.ts
A more precise and friendly message.
> Update pwned message for pt-BR.ts

- packages/clerk-js/src/ui/common/SSOCallback.tsx
> chore(clerk-js): Remove unlocalized value from SSOCallback

- packages/clerk-js/src/ui/elements/IdentityPreview.tsx
- packages/clerk-js/src/utils/image.ts
> chore(clerk-js): Proxy avatar placeholder through img.clerk.com

- packages/backend/src/redirections.ts
Fixes a minor misspelling. I noticed it while looking through a bunch of the packages.
> chore(backend): Fix spelling of Sing* -> Sign*

- packages/clerk-js/src/ui/components/SignIn/SignIn.tsx
> fix(clerk-js): Add missing param to SignInSSOCallback

- .changeset/config.json
- .github/actions/setup/action.yml
- .github/workflows/release-snapshot.yml
- package.json
> CICD Improvements

- .changeset/tasty-cars-battle.md
- package-lock.json
- packages/backend/package.json
> Address npm audit issues

- .changeset/late-lizards-compete.md
- packages/nextjs/src/index.ts
> fix(nextjs): Resolve build App Router build issues

- .changeset/shaggy-meals-warn.md
- packages/sdk-node/package.json
- packages/sdk-node/tsup.config.ts
> fix(clerk-sdk-node): Fix ESM build issues

- .changeset/dry-moles-melt.md
- packages/clerk-js/src/ui/localization/__tests__/makeLocalizable.test.tsx
- packages/localizations/src/cs-CZ.ts
- packages/localizations/src/da-DK.ts
- packages/localizations/src/de-DE.ts
- packages/localizations/src/en-US.ts
- packages/localizations/src/es-ES.ts
- packages/localizations/src/fr-FR.ts
- packages/localizations/src/he-IL.ts
- packages/localizations/src/it-IT.ts
- packages/localizations/src/ja-JP.ts
- packages/localizations/src/ko-KR.ts
- packages/localizations/src/nb-NO.ts
- packages/localizations/src/nl-NL.ts
- packages/localizations/src/pl-PL.ts
- packages/localizations/src/pt-BR.ts
- packages/localizations/src/ru-RU.ts
- packages/localizations/src/sv-SE.ts
- packages/localizations/src/tr-TR.ts
- packages/localizations/src/vi-VN.ts
- packages/localizations/src/zh-CN.ts
- packages/types/src/localization.ts
> fix(clerk-js,types,localizations): Add  form_username_invalid_character unstable error localization key

- .changeset/short-camels-smoke.md
- packages/clerk-js/src/ui/components/OrganizationSwitcher/OtherOrganizationActions.tsx
> fix(clerk-js): Remove personal email from organization action list

- .changeset/friendly-planes-impress.md
- packages/localizations/src/fr-FR.ts
Add some translation on the french localization package.
> Add more translation fr-FR

- integration/tests/db-jwt.test.ts
> [WIP] test(nextjs): Add basic testing structure for Dev Browser JWT

- .changeset/eighty-planets-sit.md
- packages/clerk-js/src/core/resources/Organization.ts
- packages/clerk-js/src/core/resources/OrganizationMembershipRequest.test.ts
- packages/clerk-js/src/core/resources/OrganizationMembershipRequest.ts
- packages/clerk-js/src/core/resources/__snapshots__/Organization.test.ts.snap
- packages/clerk-js/src/core/resources/__snapshots__/OrganizationMembership.test.ts.snap
- packages/clerk-js/src/core/resources/__snapshots__/OrganizationMembershipRequest.test.ts.snap
- packages/clerk-js/src/core/resources/internal.ts
- packages/shared/src/hooks/useOrganization.tsx
- packages/types/src/index.ts
- packages/types/src/json.ts
- packages/types/src/organization.ts
- packages/types/src/organizationMembershipRequest.ts
> feat(clerk-js,shared): Introduce OrganizationMembershipRequest and membershipRequests within useOrganization

- .changeset/giant-timers-film.md
- packages/clerk-js/bundlewatch.config.json
- packages/clerk-js/src/core/resources/OrganizationMembershipRequest.ts
- packages/clerk-js/src/core/resources/__snapshots__/OrganizationMembershipRequest.test.ts.snap
- packages/clerk-js/src/ui/components/OrganizationProfile/ActiveMembersList.tsx
- packages/clerk-js/src/ui/components/OrganizationProfile/InvitedMembersList.tsx
- packages/clerk-js/src/ui/components/OrganizationProfile/MemberListTable.tsx
- packages/clerk-js/src/ui/components/OrganizationProfile/OrganizationMembers.tsx
- packages/clerk-js/src/ui/components/OrganizationProfile/OrganizationMembersTabInvitations.tsx
- packages/clerk-js/src/ui/components/OrganizationProfile/OrganizationMembersTabRequests.tsx
- packages/clerk-js/src/ui/components/OrganizationProfile/RequestToJoinList.tsx
- packages/clerk-js/src/utils/pagesToOffset.ts
- packages/localizations/src/en-US.ts
- packages/shared/src/hooks/useOrganization.tsx
- packages/types/src/localization.ts
- packages/types/src/organization.ts
- packages/types/src/organizationDomain.ts
> feat(clerk-js,types,localizations): Introduces Membership Requests in <OrganizationProfile />

- .changeset/chilled-trees-count.md
> chore(clerk-js): Trigger staging release

- .github/workflows/release-prod.yml
Minor change - the workflow id needs to be the same as the file in the clerkinc/cloudflare-workers repo.
> chore(repo): Update the workflow id triggered by release-prod

- docs/CONTRIBUTING.md
Adding some extra context on issue labels and triage process to our contributing docs!
> Add more information about how we triage issues to contributing docs

- .changeset/forty-candles-tickle.md
- packages/clerk-js/src/ui/components/OrganizationProfile/ActionConfirmationPage.tsx
https://github.com/clerkinc/javascript/assets/19269911/8f46e265-23a8-48f8-8b74-ffeb13ddc38f
https://github.com/clerkinc/javascript/assets/19269911/7f9b86c7-cb92-49a2-8714-eadfbf16e8c1
> fix(clerk-js): ActionConfirmationPage incorrect submit on enter

- .github/PULL_REQUEST_TEMPLATE.md
- docs/CONTRIBUTING.md
Updates our PR template and contributing docs to include a section on contribution documentation expectations. Also fixes a few small formatting issues in the contributing docs.
fixes JS-613
> chore(repo): Adds docs on JSDoc comment expectations

- .changeset/calm-wolves-tie.md
- .changeset/hot-chairs-refuse.md
- packages/clerk-js/src/core/resources/Organization.ts
- packages/shared/src/hooks/useOrganization.tsx
- packages/types/src/organization.ts
> feat(clerk-js,shared): getMemberships support for paginated responses + useOrganization adds `memberships`

- .changeset/strong-shoes-attack.md
- packages/clerk-js/src/ui/elements/SuccessPage.tsx
> fix(clerk-js): SuccessPage multiple localizations as text

- .changeset/strong-keys-greet.md
- packages/shared/src/utils/index.ts
- packages/shared/src/utils/runtimeEnvironment.ts
Identify development mode using the `process.env` or `import.meta.env`.
> feat(shared): Introduce isDevelopmentEnvironment() helper to check identify application runtime mode

- .changeset/late-carrots-notice.md
- packages/react/src/isomorphicClerk.ts
> chore(clerk-react): Apply deprecation warnings

- docs/CONTRIBUTING.md
Adds more information on how to write great changesets to our `CONTRIBUTING` docs
> chore(repo): Add changesets framework to CONTRIBUTING

- docs/CONTRIBUTING.md
Fix a broken link in our `CONTRIBUTING` doc.
> chore(repo): Fix link to changesets section in CONTRIBUTING.md

- .changeset/happy-turkeys-explode.md
- packages/clerk-js/src/core/resources/SamlAccount.ts
- packages/clerk-js/src/core/resources/User.ts
- packages/clerk-js/src/core/resources/UserSettings.ts
- packages/types/src/clerk.ts
- packages/types/src/factors.ts
- packages/types/src/json.ts
- packages/types/src/samlAccount.ts
- packages/types/src/strategies.ts
- packages/types/src/user.ts
- packages/types/src/userSettings.ts
Experimtal Saml types:
- `User.samlAccounts`
- `SamlAccount`
- `UserSettingsResource.saml`
- `UserSettingsJSON.saml`
- `SamlSettings`
- `UserResource.samlAccounts`
- `SamlAccountResource`
- `SamlStrategy`
- `UserJSON.saml_accounts`
- `SamlAccountJSON`
- `SamlConfig`
- `SamlFactor`
- `HandleSamlCallbackParams`
> chore(clerk-js,types): Convert Saml related types from experimental to stable

- .changeset/violet-dots-wait.md
- packages/clerk-js/src/core/clerk.ts
> fix(clerk-js): Incorrect deprecation message for `__unstable__membershipUpdate`

- .github/workflows/checks.yml
As described in https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue
> chore(repo): Add merge_group trigger to checks.yml

- .changeset/slimy-hornets-obey.md
- packages/clerk-js/src/core/clerk.ts
- packages/react/src/isomorphicClerk.ts
> chore(clerk-js,clerk-react): Update JSDocs to mark `setActive` stable

- .vscode/settings.json
> chore(repo): Organize imports and fix eslint errors on save

- .github/workflows/ci.yml
Otherwise, merge queue will not run the required checks
> fix(repo): Add merge_group trigger

- .github/workflows/ci.yml
Minor change to better hint why a quality check failed
> chore(repo): Rename formatting-linting job

- .github/workflows/release.yml
Rename misnamed "Production release PR" to generic "Release" since we'll be using this action both for pre-release versions and later our normal releases.
Also re-adds the `commit` since our commitlint wants this.
> chore(repo): Adjust release workflow

- .github/workflows/release.yml
> fix(repo): Pass explicit env var to GHA changesets

- .github/workflows/release.yml
> fix(repo): Add missing npx

- .changeset/spotty-apples-march.md
- packages/clerk-js/src/core/clerk.ts
- packages/clerk-js/src/core/resources/Error.ts
- packages/clerk-js/src/ui/components/SignIn/SignInFactorOneCodeForm.tsx
- packages/clerk-js/src/ui/components/SignIn/SignInFactorOneEmailLinkCard.tsx
- packages/clerk-js/src/ui/components/SignIn/SignInFactorOnePasswordCard.tsx
- packages/clerk-js/src/ui/components/SignIn/SignInFactorTwoBackupCodeCard.tsx
- packages/clerk-js/src/ui/components/SignIn/SignInFactorTwoCodeForm.tsx
- packages/clerk-js/src/ui/components/SignIn/__tests__/SignInFactorOne.test.tsx
- packages/clerk-js/src/ui/components/SignIn/__tests__/SignInFactorTwo.test.tsx
- packages/clerk-js/src/ui/elements/contexts/CardStateContext.tsx
- packages/clerk-js/src/ui/utils/test/mockHelpers.ts
- packages/shared/src/error.ts
Backporting #2043 to the release/v4 branch
(cherry picked from commit 0d1052ac284b909786fd0e4744b02fcf4d1a8be6)
> feat(clerk-js,shared): Add a navigateWithError utility for SignIn (#2043)

- .github/workflows/ci.yml
- .github/workflows/release-canary.yml
- .github/workflows/release.yml
- turbo.json
> chore(repo): Rename release workflow; Update global Turbo deps

- .github/workflows/preview.retheme.yml
Removes check that can never pass: https://github.com/clerk/javascript/actions/runs/6828163244/job/18571767458
> chore(repo): Fix retheme deploy preview

- CODEOWNERS
As decided in our team meeting
> Remove codeowners for all activity, too much noice

- .changeset/khaki-spoons-teach.md
- packages/clerk-js/src/ui/components/OrganizationProfile/InviteMembersForm.tsx
- packages/clerk-js/src/ui/components/OrganizationProfile/__tests__/InviteMembersPage.test.tsx
> fix(clerk-js): Require role to be selected before sending organization invite

- .changeset/brown-clouds-divide.md
- packages/clerk-js/src/ui/components/OrganizationSwitcher/OrganizationSwitcherTrigger.tsx
> fix(clerk-js): Avoid wrapping NotificationCountBadge of OrgSwitcher with Gate (#2147)

- .changeset/flat-clocks-clap.md
- packages/localizations/src/ru-RU.ts
> feat(localization): extend ru-RU localization

- .changeset/flat-clocks-clap.md
- packages/localizations/src/ru-RU.ts
> Backport ru-RU additions

- .changeset/dull-wasps-begin.md
- packages/clerk-js/src/ui.retheme/components/OrganizationProfile/ActiveMembersList.tsx
- packages/clerk-js/src/ui.retheme/components/OrganizationProfile/InvitedMembersList.tsx
- packages/clerk-js/src/ui/components/OrganizationProfile/ActiveMembersList.tsx
- packages/clerk-js/src/ui/components/OrganizationProfile/InvitedMembersList.tsx
This is valuable for AP where custom localization cannot be applied.
> fix(clerk-js): Fallback to custom role name if localization is not provided

- .changeset/dull-wasps-begin.md
- packages/clerk-js/src/ui/components/OrganizationProfile/ActiveMembersList.tsx
- packages/clerk-js/src/ui/components/OrganizationProfile/InvitedMembersList.tsx
> fix(clerk-js): Fallback to custom role name if localization is not provided (#2194)

- .changeset/clever-moose-act.md
- packages/clerk-js/src/ui.retheme/components/OrganizationProfile/VerifyDomainPage.tsx
- packages/clerk-js/src/ui/components/OrganizationProfile/VerifyDomainPage.tsx
https://github.com/clerk/javascript/assets/19269911/3bcc4f54-6958-4e44-b323-f14820c59443
https://github.com/clerk/javascript/assets/19269911/cd74d69a-e904-46bd-9361-17b08d888e03
> fix(clerk-js): Reset CodeControl when resetting wizard in VerifyDomainPage

- .changeset/sharp-trains-ring.md
- packages/clerk-js/src/core/clerk.test.ts
- packages/clerk-js/src/core/clerk.ts
- packages/types/src/clerk.retheme.ts
- packages/types/src/clerk.ts
> feat(clerk-js,types): Add `routerDebug` option

- .changeset/young-experts-attack.md
- packages/clerk-js/src/core/clerk.ts
Add a setter on `Clerk` to address an error originating from older versions of the react SDK.
> fix(clerk-js): Add setter for sdkMetadata to address error

- playground/nextjs/pages/_app.tsx
- playground/nextjs/pages/api/sendEmail.ts
- playground/nextjs/pages/session-examples/index.tsx
- playground/nextjs/pages/user-examples/index.tsx
This PR fixes the build of the `playground/nextjs` app.
> fix(*): Fix retheme deployment preview template

- .changeset/moody-zoos-deliver.md
- packages/clerk-js/src/core/test/fixtures.ts
- packages/clerk-js/src/ui/components/OrganizationProfile/ActiveMembersList.tsx
- packages/clerk-js/src/ui/components/OrganizationProfile/DomainList.tsx
- packages/clerk-js/src/ui/components/OrganizationProfile/OrganizationProfileRoutes.tsx
- packages/clerk-js/src/ui/components/OrganizationProfile/VerifiedDomainPage.tsx
- packages/types/src/organizationMembership.ts
> chore(clerk-js,types): Remove system delete permission for domains and memberships (#2256)

- docs/CICD.md
- docs/CONTRIBUTING.md
- integration/README.md
This improves our guide for integration testing by making it more structured, concise, and additional information.
[Read the preview](https://github.com/clerk/javascript/blob/lekoarts/sdk-1046-write-public-docs-for-e2e-tests/integration/README.md)
This PR also updates our contributing guide to point to this integration testing suite.
> chore(repo): Improve integration tests docs

- .changeset/many-gifts-swim.md
- package-lock.json
- packages/shared/package.json
[Changelog](https://github.com/vercel/swr/releases) since 2.2.0
> chore(shared): Upgrade swr to 2.2.4

- .changeset/warm-clouds-fly.md
- packages/clerk-js/src/ui/components/OrganizationProfile/ProfileSettingsPage.tsx
Backports https://github.com/clerk/javascript/pull/2400
> fix(clerk-js): Prevent submitting on enter in Organization Profile form

- .changeset/two-crews-talk.md
- packages/clerk-js/src/ui/components/OrganizationProfile/RemoveDomainPage.tsx
- packages/clerk-js/src/ui/components/OrganizationProfile/VerifiedDomainPage.tsx
- packages/clerk-js/src/ui/components/OrganizationProfile/VerifyDomainPage.tsx
- packages/clerk-js/src/ui/components/OrganizationProfile/__tests__/InviteMembersPage.test.tsx
- packages/clerk-js/src/ui/components/OrganizationProfile/__tests__/OrganizationMembers.test.tsx
- packages/clerk-js/src/ui/components/OrganizationSwitcher/OrganizationSwitcherPopover.tsx
- packages/clerk-js/src/ui/components/OrganizationSwitcher/OrganizationSwitcherTrigger.tsx
- packages/clerk-js/src/ui/components/OrganizationSwitcher/__tests__/OrganizationSwitcher.test.tsx
- packages/clerk-js/src/ui/elements/OrganizationPreview.tsx
- packages/clerk-js/src/ui/hooks/useFetch.ts
- packages/clerk-js/src/ui/hooks/useFetchRoles.ts
> fix(clerk-js): Fetching custom role in OrganizationSwitcher with cache (#2430)

- packages/localizations/src/tr-TR.ts
Added missing unstable_errors -> form_code_incorrect for trTR
> chore(localizations): Add missing form_code_incorrect for tr

- .changeset/funny-pots-brush.md
- packages/sdk-node/src/__tests__/middleware.test.ts
- packages/sdk-node/src/authenticateRequest.ts
- packages/sdk-node/src/clerkExpressRequireAuth.ts
- packages/sdk-node/src/clerkExpressWithAuth.ts
Adds support for the handshake flow in `@clerk/clerk-sdk-node`. Validated within the express playground that this properly handles the handshake redirects.
> feat(clerk-sdk-node): Implement support for the handshake flow

- playground/nextjs/app/app-dir/create-organization/page.tsx
- playground/nextjs/app/app-dir/organization/page.tsx
- playground/nextjs/app/app-dir/sign-in/page.tsx
- playground/nextjs/app/app-dir/sign-up/page.tsx
- playground/nextjs/app/app-dir/user/page.tsx
This PR updates all components that must have a path inside the `app-dir` version of the NextJS playground.
> chore(repo): Added paths in app-dir version of NextJS Playground

- playground/nextjs/app/app-dir/page.tsx
- playground/nextjs/app/app-dir/sign-in/page.tsx
- playground/nextjs/app/app-dir/sign-up/page.tsx
> fix(repo): Add redirectUrl to app-dir in nextjs playground

- .changeset/nine-mayflies-smoke.md
- packages/nextjs/src/client-boundary/uiComponents.tsx
- packages/remix/src/client/uiComponents.tsx
> fix(nextjs,remix): CustomPages in remix & nextjs SDKs

- .changeset/sixty-rats-bathe.md
- package-lock.json
- packages/expo/package.json
- packages/expo/src/singleton.ts
Cherrypick of #2528 to be released in V4
> chore: backport #2528

- .changeset/tough-peas-teach.md
- packages/clerk-js/src/ui/components/OrganizationProfile/OrganizationMembersTabInvitations.tsx
- packages/clerk-js/src/ui/components/OrganizationProfile/OrganizationMembersTabRequests.tsx
- packages/clerk-js/src/ui/components/OrganizationProfile/OrganizationProfileRoutes.tsx
- packages/clerk-js/src/ui/contexts/ClerkUIComponentsContext.tsx
https://github.com/clerk/javascript/assets/19269911/e148dd47-d4e4-4dff-a287-33705fdbaf67
https://github.com/clerk/javascript/assets/19269911/a9014d61-032d-4274-b48c-26ce45dc7c7f
> fix(clerk-js): Take account custom pages when redirecting inside OrganizationProfile

- .changeset/light-shirts-lick.md
- packages/clerk-js/src/core/clerk.ts
- packages/clerk-js/src/core/warnings.ts
- packages/clerk-js/src/utils/componentGuards.ts
> chore(clerk-js): Log warning if org components are mounted and the feature is turned off

- .changeset/sweet-ladybugs-sneeze.md
- packages/backend/src/api/endpoints/UserApi.ts
Backport of https://github.com/clerk/javascript/pull/2619
> fix(backend): Add UserPasswordHashingParams to updateUser [backport]

- .changeset/strange-ravens-own.md
> chore(): Add changeset for Retheme project

- packages/localizations/src/ja-JP.ts
I have modified the Japanese localization file.
> Japanese localization fixes

- .changeset/rude-gorillas-smash.md
> chore(repo): Trigger patch version bump to generate @clerk/shared beta

- .changeset/late-geckos-impress.md
- packages/clerk-js/src/ui/components/OrganizationSwitcher/OrganizationSwitcherPopover.tsx
- packages/clerk-js/src/ui/contexts/ClerkUIComponentsContext.tsx
- packages/types/src/clerk.ts
> feat(clerk-js): Accept skipInvitationScreen as a prop from OrganizationSwitcher #2713

- scripts/snapshot.mjs
Removes ignored package from snapshot script
> chore(repo): Fix snapshot script

- packages/elements/src/internals/machines/sign-in/machines/router.machine.ts
- packages/elements/src/internals/machines/sign-up/machines/router.machine.ts
- packages/elements/src/internals/machines/third-party/machine.ts
- packages/elements/src/react/sign-in/root.tsx
Handles SSO callbacks in the new flow.
Fixes SDK-1146
> feat(elements): Handle SSO callbacks

- .github/workflows/semgrep.yml
Add semgrep in monitoring mode to scan for security issues in the background such as:
- Committed secrets
- First-party code vulnerabilities
- Dependency vulnerabilities
> chore(repo): Add github action for semgrep to run security scans in monitoring mode

- .changeset/calm-pears-attack.md
- packages/shared/src/__tests__/devbrowser.test.ts
- packages/shared/src/devBrowser.ts
> fix(shared,clerk-js): Do not replace current URL if it does not contain a clerk token

- packages/upgrade/source/versions/core-2/common/changed-localization-keys.md
- packages/upgrade/source/versions/core-2/common/new-localization-keys.md
- packages/upgrade/source/versions/core-2/common/removed-localization-keys.md
Update with the latest localization changes.
> chore(upgrade): Update with the latest localization changes

- scripts/notify.mjs
Fixes the formatting on `notify.mjs`
> Fix formatting on `notify.mjs`

- .github/ISSUE_TEMPLATE/BUG_REPORT.yml
Change the wording to make the minimal reproduction required and the recordings an optional addition.
> chore(repo): Update BUG_REPORT template

- .github/ISSUE_TEMPLATE/BUG_REPORT.yml
> chore(repo): Further clarify BUG_REPORT template

- .changeset/big-guests-deny.md
- packages/localizations/src/ru-RU.ts
add some translation for ru-RU locale
> feat(localizations): add missing translations

- .changeset/selfish-mugs-love.md
- package-lock.json
- packages/themes/package.json
Backporting https://github.com/clerk/javascript/pull/2665 to the release/v4 branch
(cherry-picked from the commit https://github.com/clerk/javascript/commit/582813c7148c42c2aa1d451bc577ff7b1b07c973)
> fix(themes): Add tslib and @clerk/types as dependencies to @clerk/themes (#2665)

- .changeset/weak-adults-juggle.md
Add the missing localization package in the changeset
> chore(clerk-js): Update changeset with missing package

- .changeset/sour-trees-glow.md
- packages/localizations/package.json
- packages/localizations/src/ca-ES.ts
- packages/localizations/src/index.ts
Catalan language has been added. This is a first version that has been generated using AI, with human review to ensure no  translation errors have occurred (and fixed those that happened)
The file has been created following es-ES, as it is the closest localisation already available.
> feat(localizations): Added catalan language

- .changeset/six-experts-approve.md
- packages/clerk-js/src/ui/components/SignIn/shared.ts
https://github.com/clerk/javascript/assets/19269911/35cb13a1-e039-4f61-b65c-4e576bcdb7e6
https://github.com/clerk/javascript/assets/19269911/1c3771fd-00a5-40b7-b53c-dc4ed3f3e539
> chore(clerk-js): Improve error handling for autofill resulting in better UX

- .changeset/wise-geese-rest.md
- packages/backend/src/api/endpoints/InvitationApi.ts
> fix(backend): Fix pagination params types for invitations.getInvitationList()

- packages/clerk-js/src/core/resources/Organization.ts
- packages/clerk-js/src/core/resources/User.ts
- packages/types/src/billing.ts
> fix(clerk-js,types): Change CreatePortalSessionParams props to camel case

- packages/clerk-js/src/core/resources/Billing.ts
> chore(clerk-js): Add interface implementation for PortalSession and CheckoutSession classes

- packages/clerk-js/src/core/resources/OrganizationSettings.ts
- packages/clerk-js/src/core/resources/UserSettings.ts
- packages/types/src/billing.ts
- packages/types/src/organizationSettings.ts
- packages/types/src/userSettings.ts
In t his pr we are adding `billing` property to `UserSettings` & `OrganizationSettings`
> feat(clerk-js,types): Add billing property to UserSettings & OrganizationSettings

- packages/localizations/src/en-US.ts
- packages/types/src/localization.ts
In this PR we are adding localization keys for the Manage plan screen of the billing page.
> chore(localizations): Add Manage plan localization keys

- packages/clerk-js/src/ui/components/OrganizationProfile/OrganizationProfileNavbar.tsx
- packages/clerk-js/src/ui/components/OrganizationProfile/OrganizationProfileRoutes.tsx
- packages/clerk-js/src/ui/components/OrganizationProfile/__tests__/OrganizationProfile.test.tsx
- packages/clerk-js/src/ui/components/UserProfile/UserProfileNavbar.tsx
- packages/clerk-js/src/ui/components/UserProfile/UserProfileRoutes.tsx
- packages/clerk-js/src/ui/components/UserProfile/__tests__/UserProfile.test.tsx
- packages/clerk-js/src/ui/utils/test/fixtureHelpers.ts
- packages/localizations/src/en-US.ts
> feat(clerk-js): Hide Billing tab from UserProfile & OrganizationProfile if billing not enabled

- packages/clerk-js/src/core/resources/__snapshots__/Organization.test.ts.snap
- packages/clerk-js/src/core/resources/__snapshots__/OrganizationMembership.test.ts.snap
- packages/clerk-js/src/ui/utils/__tests__/createCustomPages.test.ts
> test(clerk-js): Update tests

- packages/clerk-js/src/core/resources/Billing.ts
- packages/clerk-js/src/core/resources/Organization.ts
- packages/clerk-js/src/core/resources/User.ts
- packages/clerk-js/src/ui/common/CurrentPlanSection.tsx
- packages/clerk-js/src/ui/common/PaymentMethodSection.tsx
- packages/types/src/billing.ts
- packages/types/src/json.ts
- packages/types/src/organization.ts
- packages/types/src/user.ts
> refactor(clerk-js,types): Add CurrentBillingPlan resource

- packages/clerk-js/src/ui/utils/currency.ts
> chore(clerk-js): Pass locale to currency utils

- packages/clerk-js/src/core/resources/Billing.ts
- packages/clerk-js/src/ui/common/Billing/PlanAndBillingScreen.tsx
- packages/types/src/billing.ts
- packages/types/src/json.ts
> chore(clerk-js,types): Change billingCycle property to nullable

- packages/clerk-js/src/ui/common/Billing/ManageBillingPlanScreen.tsx
In this commit we are adding animation when a user click the show all/less button on billing plan card.
> chore(clerk-js): Add animation to show more features on billing card

- packages/clerk-js/src/core/resources/Session.test.ts
- packages/clerk-js/src/core/resources/Session.ts
- packages/clerk-js/src/core/test/fixtures.ts
> fix(clerk-js): Add missing plan authorization for Session.checkAuthorization

- packages/clerk-js/src/ui/common/Billing/PlanAndBillingScreen.tsx
- packages/clerk-js/src/ui/components/OrganizationProfile/OrganizationBillingPage.tsx
- packages/clerk-js/src/ui/hooks/useFetch.ts
> fix(clerk-js): Add payment method redirect fix

- packages/clerk-js/src/core/resources/Organization.ts
- packages/clerk-js/src/core/resources/OrganizationMembership.ts
- packages/clerk-js/src/core/resources/Session.ts
- packages/react/src/utils/deriveState.ts
- packages/types/src/json.ts
- packages/types/src/organization.ts
> chore(clerk-js,types,clerk-react): Resolve `orgPlan` on client

- .changeset/tall-news-invent.md
- packages/clerk-js/src/ui/common/SSOCallback.tsx
Fixes the Turnstile when SSO transfer flow is used and Smart Bot Protection is enabled.
Screenshot of the loading screen:
> fix(clerk-js): Fix transfer flow when having the Smart Bot Protection enabled

- packages/clerk-js/src/ui/common/Billing/ManageBillingPlanScreen.tsx
> chore(clerk-js): Plan features layout fixes

- package-lock.json
- packages/elements/examples/nextjs/app/sign-in/[[...sign-in]]/page.tsx
- packages/elements/examples/nextjs/package.json
- packages/elements/package.json
- packages/elements/src/internals/machines/sign-in/machines/reset-password.machine.ts
- packages/elements/src/internals/machines/sign-in/machines/router.machine.ts
- packages/elements/src/internals/machines/sign-up/machines/router.machine.ts
- packages/elements/src/internals/machines/third-party/machine.ts
- packages/elements/src/react/sign-in/context/router.context.ts
- packages/elements/src/react/sign-in/root.tsx
Reset machine upon successful authentication
> feat(elements): Reset machine

- packages/clerk-js/src/core/resources/OrganizationSettings.ts
- packages/clerk-js/src/core/resources/UserSettings.ts
- packages/clerk-js/src/ui/common/Billing/BillingProvider.tsx
- packages/clerk-js/src/ui/common/Billing/PlanAndBillingScreen.tsx
- packages/clerk-js/src/ui/components/OrganizationProfile/OrganizationBillingPage.tsx
- packages/clerk-js/src/ui/components/UserProfile/BillingPage.tsx
- packages/types/src/billing.ts
> feat(clerk-js,types): Hide Manage billing button when stripe billing portal is disabled

- packages/clerk-js/src/ui/common/Billing/ManageBillingPlanScreen.tsx
> refactor(clerk-js): Billing plans page remove unnecessary code

- .changeset/empty-actors-deliver.md
- packages/clerk-js/src/ui/components/SignIn/__tests__/SignInFactorOne.test.tsx
- packages/localizations/src/en-US.ts
Rename email id to email address
> chore(localizations): Rename email id to email address

- .gitignore
Allow for custom non-committed apps in playground
> chore(repo): Add playground/custom to gitignore

- .changeset/clean-boats-invite.md
- packages/clerk-js/src/ui/components/OrganizationList/OrganizationListPage.tsx
- packages/clerk-js/src/ui/components/OrganizationList/__tests__/OrganizationList.test.tsx
> fix(clerk-js): Hide "Create Organization" on OrganizationList when disabled for user

- .changeset/gentle-trainers-marry.md
- packages/backend/src/api/endpoints/OrganizationApi.ts
- packages/backend/src/api/endpoints/UserApi.ts
- packages/backend/src/api/endpoints/util-types.ts
This PR syncs the @clerk/backend types with our Backend docs
- https://clerk.com/docs/reference/backend-api/tag/Organization-Memberships#operation/ListOrganizationMemberships!in=query&path=order_by&t=request
- https://clerk.com/docs/reference/backend-api/tag/Users#operation/GetUserList!in=query&path=order_by&t=request
> chore(backend): Update types of `orderBy` in OrganizationApi and UserApi

- .changeset/three-flies-mix.md
- .github/workflows/ci.yml
- .github/workflows/release.yml
- packages/elements/src/react/sign-in/verifications.tsx
- Release `@clerk/elements@0.2.0`
- Update return type of `<SignIn.Strategy>`
> build(elements): Release 0.2.0

- .changeset/thin-mails-shake.md
- packages/react/src/utils/loadClerkJsScript.ts
> fix(clerk-react): Remove typo in clerkjs script attributes

- .changeset/smooth-pugs-deny.md
- packages/themes/src/themes/neobrutalism.ts
Fix Neobrutalism theme in Core 2
> fix(themes): Fix Neobrutalism theme in Core 2

- .changeset/green-eggs-kiss.md
- packages/clerk-js/src/ui/elements/LoadingCard.tsx
- packages/clerk-js/src/utils/captcha.ts
This is a backport of PR #3351
> [Core1 Backport] fix(clerk-js): Fix ticket flow on Smart CAPTCHA

- .changeset/small-tips-eat.md
- package-lock.json
- packages/shared/package.json
> chore(shared): Unpin swr version

- .changeset/great-parents-invent.md
- packages/localizations/src/pt-BR.ts
Adds missing keys, fixes some typos
> fix(localizations): Review PT-BR localization

- .github/actions/init/action.yml
> ci(*): Add comment for the pinned node version

- .changeset/tiny-timers-sit.md
- packages/types/src/oauth.ts
This provider won't be available in the dashboard.
> feat(types): Add support for Enstall OAuth provider

- .changeset/tiny-timers-sit.md
- .github/actions/init/action.yml
- packages/types/src/oauth.ts
Cherry picked from https://github.com/clerk/javascript/pull/3466
> feat(types): Add support for Enstall OAuth provider (#3466)

- packages/ui/theme-builder/README.md
- packages/ui/theme-builder/package-lock.json
- packages/ui/theme-builder/package.json
- packages/ui/theme-builder/scripts/deploy.mjs
- packages/ui/turbo.json
Add a small script to facilitate deploying the theme-builder app to Vercel as needed.
> feat(ui): Add theme-builder deploy

- .github/workflows/pr-title-linter.yml
- commitlint.config.ts
Remove unnecessary tasks from the PR title linter.
`~2m15s => ~18s`
Fixes SDK-1803
> chore(repo): Speed up PR title linter

- .changeset/forty-cats-shave.md
- packages/elements/src/internals/machines/form/form.machine.ts
- packages/elements/src/internals/machines/sign-up/start.machine.ts
- packages/elements/src/internals/machines/sign-up/verification.machine.ts
- packages/elements/src/react/common/form/index.tsx
- [1] Fixes issue where resend UI was not being updated on click
- [2] Fixes email address error rendering
**1. Resend ui update**
https://github.com/user-attachments/assets/c101c6ad-5db3-4661-b864-672c9ac82f0d
**2. Email address error:**
https://linear.app/clerk/issue/SDKI-133/signup-verifications-clicking-on-resend-for-email-link-doesnt-work-as
https://linear.app/clerk/issue/SDKI-131/signup-start-missing-field-error-for-when-account-is-already-taken
> fix(elements): Ensure default values are correctly being set

- .changeset/warm-points-mix.md
- packages/astro/src/internal/create-clerk-instance.ts
- packages/astro/src/types.ts
This change improves the UX by a lot, because path routing will not result in full page reloads.
> feat(astro): Navigation in UI components without full page reload

- .changeset/brown-dolls-hide.md
> feat(astro): Release Astro v1

- integration/testUtils/appPageObject.ts
- integration/testUtils/index.ts
- integration/testUtils/signInPageObject.ts
- integration/tests/sessions/root-subdomain-prod-instances.test.ts
> chore(repo): Test that handshake is throw if suffixed client_uat is not found

- .github/actions/ensure-stable-pr/action.yml
- .github/workflows/preview.yml
- .github/workflows/release-snapshot.yml
Ensures that the PR hasn't changed between when the comment was created and checkout occurs.
Fixes SDK-1848
> fix(repo): Ensure unchanged PR on comment actions

- .github/actions/ensure-stable-pr/action.yml
Adds `github-token` to composite action.
> fix(repo): Fix syntax error in composite GHA

- .github/workflows/preview.yml
- .github/workflows/release-snapshot.yml
> fix(repo): Check for PR updates

- .github/workflows/preview.yml
- .github/workflows/release-snapshot.yml
> fix(repo): GHA Syntax Error

- .github/workflows/preview.yml
- .github/workflows/release-snapshot.yml
> fix(repo): GHA context output

- .github/workflows/preview.yml
- .github/workflows/release-snapshot.yml
> fix(repo): GHA PR changes check

- .changeset/rude-wasps-wonder.md
- packages/clerk-js/src/core/resources/SignUp.ts
Co-authored-by: Kevin Wang <26389321+thiskevinwang@users.noreply.github.com>
(cherry picked from commit 17bbe01994beb9c5e53355cc692a5d71ddf4cc8c)
> feat(clerk-js): Adjust captcha parameter handling for sign ups with Google (#3806)

- package-lock.json
Try to fix failing CI due to lock file
> chore(repo): Lock file

- .changeset/sixty-drinks-drum.md
- packages/clerk-js/src/ui/components/UserProfile/Web3Section.tsx
Display shortened web3 wallet address on user profile
> chore(clerk-js):  Display shortened web3 wallet address on user profile

- .changeset/four-experts-learn.md
- packages/tanstack-start/src/client/ClerkProvider.tsx
- packages/tanstack-start/src/server/middlewareHandler.ts
This PR fixes types of `createClerkHandler`
> chore(tanstack-start): Fix types for createClerkHandler

- .changeset/curly-rabbits-appear.md
- packages/elements/src/internals/machines/sign-in/start.machine.ts
- packages/elements/src/internals/machines/sign-in/verification.machine.ts
- packages/elements/src/internals/machines/sign-up/start.machine.ts
- packages/elements/src/react/utils/map-scope-to-strategy.ts
> feat(elements): Add support for Coinbase Wallet Web3 provider

- .changeset/sweet-birds-nail.md
- packages/localizations/src/zh-CN.ts
Update Simplified Chinese according to the latest en-US version
> This is my first pr and if I've done anything wrong then I'm very sorry
> fix(localizations):Update Simplified Chinese Translation

- package-lock.json
This PR fixes a warning about conflicting peer dep showing up when installing dependencies in the monorepo
> fix(tanstack-start): Fix conflicting peer dependencies

- .changeset/young-jeans-prove.md
- package-lock.json
- packages/nextjs/package.json
- packages/nextjs/src/utils/pathMatchers.ts
- packages/nextjs/src/utils/pathToRegexp.ts
> Vendor path-to-regexp (v4)

- .changeset/hot-pants-change.md
- packages/clerk-js/src/ui/hooks/useEnabledThirdPartyProviders.tsx
> fix(clerk-js): Handle gracefully yet unknown to our components Web3 providers [backport]  (#4263)

- .changeset/unlucky-crabs-hunt.md
- packages/localizations/package.json
- packages/localizations/src/be-BY.ts
- packages/localizations/src/index.ts
- packages/localizations/src/utils/generate.ts
- packages/react/src/contexts/__tests__/ClerkProvider.test.tsx
This merge request introduces a new Belarus (be-BY) localization for the project. It includes translations for all relevant strings and ensures that the new locale is fully supported across the application.
> feat(localizations): Add be-BY localization

- package-lock.json
Fixing the `package-lock.json` file which is in a non-deterministic state by running `npm install`
> fix(repo): Update non-deterministic package-lock.json

- package.json
The `npm install` command needed adjustment to allow for differing Node versions in the `engines` field.
> chore(repo): Fix Release action

- .changeset/gorgeous-dingos-knock.md
- packages/backend/src/api/endpoints/UserApi.ts
- packages/backend/src/api/resources/JSON.ts
- packages/backend/src/api/resources/User.ts
- Adding `legalAcceptedAt` on `User`
- Adding `legalAcceptedAt` and `skipLegalChecks` on `CreateUserParams` and `UpdateUserParams`
- Adding `legal_accepted_at` on `UserJSON`
> feat(backend): Add legal related properties

- .changeset/funny-penguins-own.md
- packages/upgrade/src/codemods/index.js
- packages/upgrade/src/components/SDKWorkflow.js
> fix(upgrade): Pass transform option

- .changeset/gentle-numbers-sit.md
- packages/nextjs/src/app-router/server-actions.ts
Thanks to @ChristianIvicevic for opening #4388, this PR also updates the return value of the server action to not cause an error.
> fix(nextjs): Fix cookies() usage in server action

- .changeset/rude-ravens-sin.md
- packages/localizations/src/sv-SE.ts
Fixes formatting from https://github.com/clerk/javascript/pull/4292
> chore(localizations): Fix formatting of sv-SE

- .changeset/chilled-crabs-stare.md
- packages/clerk-js/src/utils/__tests__/url.test.ts
- packages/clerk-js/src/utils/authPropHelpers.ts
- packages/clerk-js/src/utils/url.ts
> fix(clerk-js): Handle protocol-relative or path-traversal URLs

- package-lock.json
We should dive deeper into this drift in the lockfile
> fix(repo): Correcting the lockfile

- .changeset/chilled-days-guess.md
- package-lock.json
- packages/shared/package.json
Found a couple of missing dependencies in the shared package
> fix(shared): Adding missing deps

- .changeset/few-crews-dress.md
- packages/localizations/src/el-GR.ts
> fix(localizations): Add legal consent translations to `el-GR` localization

- .changeset/mean-foxes-protect.md
- integration/templates/next-app-router/src/app/(reverification)/actions.ts
- packages/clerk-js/src/core/resources/__tests__/Session.test.ts
- packages/clerk-js/src/ui/components/UserVerification/useUserVerificationSession.tsx
- packages/react/src/hooks/__tests__/useAuth.test.ts
- packages/shared/src/authorization.ts
- packages/types/src/sessionVerification.ts
Update reverification config values to snake_case.
For `__experimental_ReverificationConfig`
- `strictMfa` changes to `strict_mfa`
For `__experimental_SessionVerificationLevel`
- `firstFactor` changes to `first_factor`
- - `secondFactor` changes to `second_factor`
- - `multiFactor` changes to `multi_factor`
> chore(types,shared): Update reverification config values to snake_case

- .changeset/serious-pigs-speak.md
- packages/clerk-js/src/core/clerk.ts
- packages/clerk-js/src/core/resources/Base.ts
- packages/clerk-js/src/core/resources/Session.ts
- packages/clerk-js/src/ui/Components.tsx
- packages/clerk-js/src/ui/components/BlankCaptchaModal/index.tsx
- packages/clerk-js/src/ui/elements/Modal.tsx
- packages/clerk-js/src/ui/elements/contexts/FlowMetadataContext.tsx
- packages/clerk-js/src/ui/hooks/usePopover.ts
- packages/clerk-js/src/ui/lazyModules/components.ts
- packages/clerk-js/src/ui/lazyModules/providers.tsx
- packages/clerk-js/src/utils/captcha/getCaptchaToken.ts
- packages/clerk-js/src/utils/captcha/hcaptcha.ts
- packages/clerk-js/src/utils/captcha/retrieveCaptchaInfo.ts
- packages/clerk-js/src/utils/captcha/turnstile.ts
- packages/clerk-js/src/utils/captcha/types.ts
- packages/shared/package.json
- packages/shared/src/dom/index.ts
- packages/shared/src/dom/waitForElement.ts
- packages/shared/subpaths.mjs
- packages/shared/tsup.config.ts
> Protect /tokens with captcha

- .github/workflows/pr-title-linter.yml
Checkout the root package.json file so we can install the correct version of pnpm
> fix(repo): PR title linter sparse checkout

- .changeset/proud-poems-walk.md
- packages/localizations/src/el-GR.ts
> fix(localizations): Improve `el-GR` localization

- .changeset/long-rabbits-ring.md
- packages/clerk-js/src/core/auth/AuthCookieService.ts
- packages/clerk-js/src/core/clerk.ts
Collect a captcha token after the first tokens request
> fix(clerk-js): Fix tokenCache.test.ts

- .changeset/cyan-ducks-accept.md
- packages/clerk-js/src/core/fraudProtection.ts
> fix(clerk-js): Catch and ignore captcha errors during heartbeat

- .changeset/fast-wolves-love.md
- packages/clerk-js/src/core/__tests__/tokenCache.test.ts
- packages/clerk-js/src/core/auth/CaptchaHeartbeat.ts
- packages/clerk-js/src/core/clerk.ts
- packages/clerk-js/src/core/fraudProtection.ts
- packages/clerk-js/src/core/resources/Client.ts
- packages/clerk-js/src/core/resources/DisplayConfig.ts
- packages/clerk-js/src/core/resources/Session.ts
- packages/clerk-js/src/core/tokenCache.ts
- packages/clerk-js/src/utils/captcha/CaptchaChallenge.ts
- packages/types/src/client.ts
- packages/types/src/displayConfig.ts
> fix(clerk-js): Decouple captcha heartbeat from token refresh

- integration/presets/envs.ts
- integration/presets/longRunningApps.ts
- integration/templates/next-app-router/src/app/layout.tsx
- integration/templates/next-app-router/src/app/sign-in/[[...catchall]]/page.tsx
- integration/tests/combined-sign-in-flow.test.ts
- integration/tests/combined-sign-up-flow.test.ts
This PR adds e2e tests for the new combined sign in/sign up flows.
Resolves SDKI-761
> test(e2e): Add tests for combined sign in/sign up flow

- packages/clerk-js/src/ui/components/UserProfile/UsernameForm.tsx
> fix(clerk-js): Do not send stale field value when updating username

- .changeset/calm-tools-sneeze.md
- packages/tanstack-start/errors/package.json
- packages/tanstack-start/package.json
- packages/tanstack-start/src/errors.ts
> fix(tanstack-start): Export error helpers form @clerk/clerk-react

- .changeset/gold-monkeys-collect.md
- .changeset/twelve-spiders-obey.md
- packages/backend/src/api/resources/AccountlessApplication.ts
- packages/backend/src/api/resources/JSON.ts
- packages/clerk-js/src/core/clerk.ts
- packages/clerk-js/src/ui/Components.tsx
- packages/clerk-js/src/ui/components/KeylessPrompt/index.tsx
- packages/nextjs/src/app-router/client/keyless-creator-reader.tsx
- packages/nextjs/src/app-router/keyless-actions.ts
- packages/nextjs/src/app-router/server/ClerkProvider.tsx
- packages/types/src/clerk.ts
> feat(clerk-js,backend): Url for copying instance keys on Keyless mode

- .changeset/quick-geckos-unite.md
- packages/clerk-js/bundlewatch.config.json
- packages/clerk-js/jest.setup.ts
- packages/clerk-js/src/core/clerk.ts
- packages/clerk-js/src/globals.d.ts
- packages/clerk-js/src/ui/Components.tsx
- packages/clerk-js/src/ui/lazyModules/components.ts
> feat(clerk-js): Display a prompt on Keyless mode

- .changeset/large-hats-clap.md
- packages/remix/README.md
Point people towards the new `@clerk/react-router` SDK if they want to use React Router v7.
> chore(remix): Add note about React Router v7 to README

- .changeset/ninety-wasps-rush.md
- packages/localizations/src/pl-PL.ts
Translate some of the untranslated keys in pl-PL.ts, mainly formFieldInputPlaceholder and for new features announced recently.
> fix(localizations): Improve `pl-PL` localization

- .changeset/rotten-berries-jog.md
- packages/clerk-js/src/ui/components/SignUp/SignUpContinue.tsx
| ![Screenshot 2025-01-06 at 9 57 52 AM](https://github.com/user-attachments/assets/7711310f-b94a-4cee-a9b8-63402ad6e613) | ![Screenshot 2025-01-06 at 9 57 37 AM](https://github.com/user-attachments/assets/56048296-1bf7-48f9-bb79-42ec6f2fb8dc) |
> fix(clerk-js): Add createUsernameError to sign-up continue flow

- packages/localizations/src/pt-BR.ts
> fix: 2 typos in pt-BR translation

- .changeset/brave-sloths-fail.md
- packages/clerk-js/src/ui/components/KeylessPrompt/index.tsx
> fix(clerk-js): Keyless button to open new tab

- .github/labeler.yml
I've also ordered it alphabetically 😄 I created any missing labels, too.
> chore(repo): Add missing packages to labeler.yml

- integration/testUtils/emailService.ts
- integration/tests/email-link.test.ts
- package.json
- turbo.json
> Revert "fix(e2e): Runs email-link tests"

- .github/workflows/ci.yml
- pnpm-lock.yaml
Making sure the pnpm lockfile is always deduped when creating a PR
> feat(repo): Ensure lockfile is deduped

- .changeset/breezy-scissors-flash.md
- packages/clerk-js/src/core/constants.ts
- packages/clerk-js/src/ui/components/SignUp/SignUpStart.tsx
Adds one more error code in order to display the correct error message on SignUp.
> fix(clerk-js): Improve error handling for invalid captcha during sign-up

- .changeset/strange-rings-applaud.md
- packages/clerk-js/src/ui/components/KeylessPrompt/index.tsx
> fix(clerk-js): Expand Keyless UI if user is signed-in

- .changeset/wet-donuts-tap.md
- packages/nextjs/src/app-router/server/ClerkProvider.tsx
> chore(nextjs): Append `return_url` when logging the claimUrl for on Keyless

- .changeset/clever-crabs-smell.md
- packages/shared/src/keys.ts
Porting over the fix from @Wolfleader101
Closes: https://github.com/clerk/javascript/pull/4991
> fix(shared): Handle ATOB errors

- .changeset/metal-jokes-notice.md
- packages/themes/src/themes/dark.ts
| ![Screenshot 2025-02-07 at 9 14 36 AM](https://github.com/user-attachments/assets/c8256281-40f1-4692-b356-566e94cb00d8) | ![Screenshot 2025-02-07 at 9 14 22 AM](https://github.com/user-attachments/assets/49647994-808d-4536-9d39-edb089c8fd7c) |
> fix(themes): Invert OKX Wallet icon in dark theme

- README.md
Was doing a Clerk walk through with a friend and noticed we could clean up our README a bit :)
> chore(repo): Clean up README.md

- .changeset/angry-ravens-grin.md
- packages/clerk-js/bundlewatch.config.json
- packages/clerk-js/src/ui/components/SignIn/SignInSocialButtons.tsx
Fixes issue for web3 providers during combined flow when additional fields are required.
BEFORE:
https://github.com/user-attachments/assets/39ebe6a1-13c8-4988-b678-fc03b0dae3b0
AFTER:
https://github.com/user-attachments/assets/da485054-30a3-40af-a768-2e7cb5376187
Fixes SDKI-864
> fix(clerk-js): Update web3 `signUpContinueUrl` when in combined flow

- .changeset/early-beans-notice.md
- packages/clerk-js/src/ui/components/UserProfile/EmailsSection.tsx
This PR introduces re-verification when trying to change primary email address
> fix(clerk-js): Trigger re-verification when changing primary email

- .lintstagedrc.json
A small PR that adds `.vue` extension to lint-staged config
https://github.com/user-attachments/assets/2df6d833-712b-4e88-a0b2-3f432f003155
> chore(repo): Include .vue files in pre-commit linting and formatting

- .github/workflows/release-canary.yml
- .github/workflows/release.yml
Switches the repo we dispatch release events to.
> chore(repo): Dispatch events to sdk-infra-workers

- .changeset/cold-gifts-add.md
- packages/react/src/components/controlComponents.tsx
Without this compat check in place, the most recent `@clerk/clerk-react` release would be incompatible with all previous v5 clerk-js releases
> fix(clerk-react): Enhance RedirectToSignIn session check for compatibility with older clerk-js versions

- .changeset/sixty-hornets-drop.md
- packages/clerk-js/src/ui/components/UserProfile/UserProfileSection.tsx
> chore(clerk-js): Remove `primaryWeb3Wallet` from `<UserPreview />` in `UserProfileSection`

- .changeset/tidy-llamas-matter.md
- packages/expo/src/index.ts
Fixes #5314 and addresses feedback of #5315
> chore(clerk-expo): Export `TokenCache` type

- .changeset/soft-houses-camp.md
- packages/clerk-js/src/ui/components/PricingTable/PlanCard.tsx
Only show `annualMonthlyAmount` when it's greater than 0.
> fix(clerk-js): Update plan fee rendering within `<PlanCard />`

- .github/workflows/validate-renovate-config.yml
I don't believe this is necessary anymore since we are running newer node
> chore(repo): Do not pin Renovate version

- .changeset/rare-buckets-move.md
- packages/clerk-js/src/ui/components/Checkout/CheckoutForm.tsx
> chore(clerk-js): Remove paypal button from `<CheckoutForm />`

- .changeset/tender-ghosts-smell.md
- packages/clerk-js/src/core/clerk.ts
Removes a `console.error` from OAuth transfer flow
> fix(clerk-js): Remove console.error from transfer flow

- .changeset/wide-glasses-wink.md
- packages/clerk-js/src/ui/components/UserVerification/UserVerificationFactorOne.tsx
- packages/clerk-js/src/ui/components/UserVerification/UserVerificationFactorTwo.tsx
This PR filters our any strategy that's not supported for reverification
> chore(clerk-js): Filters out non supported strategies for reverification

- .changeset/mighty-cloths-brush.md
- packages/clerk-js/src/ui/lazyModules/providers.tsx
> fix(clerk-js): Wrap Checkout in VirtualRouter

- .changeset/modern-paws-mate.md
Previous PR https://github.com/clerk/javascript/pull/5507 accidentally added some patches between minors
> fix(repo): Fix changeset versioning

- .changeset/hip-nights-itch.md
> fix(vue): Add missing changeset for sessionClaims in useAuth()

- .changeset/fluffy-teeth-decide.md
- packages/shared/src/__tests__/jwtPayloadParser.test.ts
- packages/shared/src/jwtPayloadParser.ts
> fix(shared): Remove padding from parsePermissions

- integration/testUtils/impersonationPageObjects.ts
- integration/testUtils/index.ts
- integration/tests/impersonation-flow.test.ts
Adds an E2E impersonation flow to the `@generic` tests
Fixes SDKI-981
> feat(e2e): Test impersonation with actor tokens

- .changeset/fuzzy-pears-win.md
- packages/clerk-js/sandbox/app.ts
- packages/clerk-js/src/core/clerk.ts
- packages/clerk-js/src/ui/components/OrganizationProfile/OrganizationProfileRoutes.tsx
- packages/clerk-js/src/ui/components/UserProfile/UserProfileRoutes.tsx
- packages/clerk-js/src/ui/utils/createCustomPages.tsx
Removes the experimental commerce flag now that we have environment commerce settings.
> chore(clerk-js): Removes experimental commerce flag

- .changeset/shy-items-grow.md
- packages/clerk-js/src/core/resources/CommerceInvoice.ts
- packages/types/src/commerce.ts
- packages/types/src/json.ts
> chore(clerk-js): Remove stale invoice properties

- packages/clerk-js/src/core/resources/CommerceCheckout.ts
- packages/clerk-js/src/ui/components/Checkout/CheckoutForm.tsx
- packages/types/src/commerce.ts
- packages/types/src/json.ts
…
Add isImmediatePlanChange to handle immediate plan changes
> feat(clerk-js): Add isImmediatePlanChange to handle immediate plan changes

- .changeset/seven-bikes-poke.md
- packages/clerk-js/src/ui/components/Checkout/CheckoutForm.tsx
> fix(clerk-js): Fix credits section show check

- .changeset/afraid-tigers-swim.md
- packages/clerk-js/src/core/modules/commerce/CommerceBilling.ts
- packages/clerk-js/src/core/resources/Organization.ts
Use the subscription endpoints at `/organizations/{orgID}/commerce/subscriptions` instead of `/organizations/{orgID}/subscriptions`.
> chore(clerk-js): Update organization subscription endpoints

- .changeset/cute-moose-unite.md
- packages/clerk-js/src/ui/components/Statements/Statement.tsx
https://github.com/user-attachments/assets/6ac12cab-9944-4c48-9d6f-c35cc16b0552
Fixes COM-757
> fix(clerk-js): Ensure statements ui is scrollable

- .changeset/polite-hands-film.md
- packages/clerk-js/src/ui/components/PaymentSources/PaymentSources.tsx
BEFORE:
https://github.com/user-attachments/assets/829c7710-941f-483c-919c-8dd78e0884cb
AFTER:
https://github.com/user-attachments/assets/a9b758d8-04eb-4fc5-9079-7112b36f7620
> fix(clerk-js): Sort payment sources by default attribute

- .changeset/purple-ghosts-win.md
- packages/clerk-js/src/ui/customizables/elementDescriptors.ts
- packages/clerk-js/src/ui/elements/UserPreview.tsx
- packages/types/src/appearance.ts
> chore(clerk-js,types): Add descriptor to user preview idetifier text

- .changeset/nine-bats-design.md
- packages/clerk-js/sandbox/template.html
- packages/clerk-js/src/ui/components/Checkout/CheckoutForm.tsx
**BEFORE:**
https://github.com/user-attachments/assets/cddcd9ea-4af4-4e3b-902a-eeacbae57c19
**AFTER:**
https://github.com/user-attachments/assets/c7888394-59ba-4d39-8a1c-3c41a0cf5d14
> fix(clerk-js): Add default value to payment method segment

- .changeset/lovely-waves-beg.md
- .changeset/purple-mice-pay.md
- integration/tests/pricing-table.test.ts
- packages/clerk-js/bundlewatch.config.json
- packages/clerk-js/src/ui/components/Checkout/CheckoutForm.tsx
- packages/clerk-js/src/ui/components/PaymentSources/AddPaymentSource.tsx
- packages/clerk-js/src/ui/hooks/useFetch.ts
- packages/testing/src/playwright/unstable/page-objects/checkout.ts
> fix(clerk-js): Revalidate payment methods after checking out with test card

- .changeset/new-coins-attend.md
- packages/clerk-js/bundlewatch.config.json
- packages/clerk-js/src/ui/components/SignUp/SignUpStart.tsx
- packages/clerk-js/src/ui/components/SignUp/__tests__/signUpFormHelpers.test.ts
- packages/clerk-js/src/ui/components/SignUp/signUpFormHelpers.ts
Check if emailAddress or phoneNumber are pre-filled in combined flow to select the correct identifier to show
Fixes: SDKI-1015
> fix(clerk-js): Check for email/phone in combined flow

- .changeset/modern-fans-tease.md
- packages/shared/src/react/hooks/useOrganization.tsx
- packages/shared/src/react/hooks/useOrganizationList.tsx
In `useOrganizationList()` the check is:
```ts
const isClerkLoaded = !!(clerk.loaded && user);
```
This is only true is Clerk is loaded and there is an authenticated user. Updated the code comments to reflect that.
> chore(shared): Updated isLoaded comments to reflect check the code performs

- renovate.json5
- scripts/renovate-config-generator.mjs
> chore(repo): Exclude floating-ui from renovate

- CODEOWNERS
The team felt that at its current state, the file is not useful.
> chore(repo): Drop CODEOWNERS file

- packages/clerk-js/src/ui/elements/__tests__/CodeControl.spec.tsx
> chore(clerk-js): Add tests for `CodeControl` component

- packages/clerk-js/src/core/clerk.ts
- packages/types/src/clerk.ts
> Remove `#handlePendingSession` branch and introduce `navigate` option
